package com.hisun.TD;

public class TDB1340_AWA_1340 {
    public char BV_TYP = ' ';
    public short BV_TYP_NO = 0;
    public String BV_CD = " ";
    public short BV_CD_NO = 0;
    public String BV_NO = " ";
    public short BV_NO_NO = 0;
    public char PRT_FLG = ' ';
    public short PRT_FLG_NO = 0;
    public String ID_TYP = " ";
    public short ID_TYP_NO = 0;
    public String ID_NO = " ";
    public short ID_NO_NO = 0;
    public String CI_NO = " ";
    public short CI_NO_NO = 0;
    public String CI_NAME = " ";
    public short CI_NAME_NO = 0;
    public String PROD_CD = " ";
    public short PROD_CD_NO = 0;
    public String CCY = " ";
    public short CCY_NO = 0;
    public char CCY_TYP = ' ';
    public short CCY_TYP_NO = 0;
    public String TERM = " ";
    public short TERM_NO = 0;
    public short OPEN_CNT = 0;
    public short OPEN_CNT_NO = 0;
    public double EVRBAL = 0;
    public short EVRBAL_NO = 0;
    public double TOTBAL = 0;
    public short TOTBAL_NO = 0;
    public int SDT = 0;
    public short SDT_NO = 0;
    public int DDT = 0;
    public short DDT_NO = 0;
    public char RAT_TYP = ' ';
    public short RAT_TYP_NO = 0;
    public double PCT_S = 0;
    public short PCT_S_NO = 0;
    public double FLT_RAT = 0;
    public short FLT_RAT_NO = 0;
    public String RUL_CD = " ";
    public short RUL_CD_NO = 0;
    public double INT_RAT = 0;
    public short INT_RAT_NO = 0;
    public double PRV_RAT = 0;
    public short PRV_RAT_NO = 0;
    public double OVE_RAT = 0;
    public short OVE_RAT_NO = 0;
    public char D_MTH = ' ';
    public short D_MTH_NO = 0;
    public String D_ID_TYP = " ";
    public short D_ID_TYP_NO = 0;
    public String D_ID_NO = " ";
    public short D_ID_NO_NO = 0;
    public String D_INF = " ";
    public short D_INF_NO = 0;
    public char PSW_FLG = ' ';
    public short PSW_FLG_NO = 0;
    public String PSW = " ";
    public short PSW_NO = 0;
    public char CR_FLG = ' ';
    public short CR_FLG_NO = 0;
    public char DR_FLG = ' ';
    public short DR_FLG_NO = 0;
    public char CT_FLG = ' ';
    public short CT_FLG_NO = 0;
    public String OP_AC = " ";
    public short OP_AC_NO = 0;
    public char OP_BVTYP = ' ';
    public short OP_BVTYP_NO = 0;
    public String OP_BVNO = " ";
    public short OP_BVNO_NO = 0;
    public String OP_NAME = " ";
    public short OP_NAME_NO = 0;
    public String OP_REV = " ";
    public short OP_REV_NO = 0;
    public char OP_DRAW = ' ';
    public short OP_DRAW_NO = 0;
    public String OP_PSW = " ";
    public short OP_PSW_NO = 0;
    public String OP_IDTYP = " ";
    public short OP_IDTYP_NO = 0;
    public String OP_IDNO = " ";
    public short OP_IDNO_NO = 0;
    public short OP_CVV = 0;
    public short OP_CVV_NO = 0;
    public String OP_TRK2 = " ";
    public short OP_TRK2_NO = 0;
    public String OP_TRK3 = " ";
    public short OP_TRK3_NO = 0;
    public char CHQ_TYPE = ' ';
    public short CHQ_TYPE_NO = 0;
    public String CHQ_NO = " ";
    public short CHQ_NO_NO = 0;
    public int CHQ_DATE = 0;
    public short CHQ_DATE_NO = 0;
    public String CHQ_PSW = " ";
    public short CHQ_PSW_NO = 0;
    public char OP_PRT = ' ';
    public short OP_PRT_NO = 0;
    public char INR_MTH = ' ';
    public short INR_MTH_NO = 0;
    public String INR_TERM = " ";
    public short INR_TERM_NO = 0;
    public String ZC_PROD = " ";
    public short ZC_PROD_NO = 0;
    public short ZC_NUM = 0;
    public short ZC_NUM_NO = 0;
    public char UP_FLG = ' ';
    public short UP_FLG_NO = 0;
    public String STL_AC = " ";
    public short STL_AC_NO = 0;
    public String DD_NAME = " ";
    public short DD_NAME_NO = 0;
    public char HEP_TYP = ' ';
    public short HEP_TYP_NO = 0;
    public String FRG_IND = " ";
    public short FRG_IND_NO = 0;
    public String OIC_NO = " ";
    public short OIC_NO_NO = 0;
    public String RES_CD = " ";
    public short RES_CD_NO = 0;
    public String SUB_DP = " ";
    public short SUB_DP_NO = 0;
    public char MON_TYP = ' ';
    public short MON_TYP_NO = 0;
    public char ACO_TYP = ' ';
    public short ACO_TYP_NO = 0;
    public String REMARK = " ";
    public short REMARK_NO = 0;
    public TDB1340_ACO1[] ACO1 = new TDB1340_ACO1[20];
    public TDB1340_ACO2[] ACO2 = new TDB1340_ACO2[20];
    public TDB1340_ACO3[] ACO3 = new TDB1340_ACO3[20];
    public TDB1340_ACO4[] ACO4 = new TDB1340_ACO4[20];
    public TDB1340_ACO5[] ACO5 = new TDB1340_ACO5[20];
    public TDB1340_ACO6[] ACO6 = new TDB1340_ACO6[20];
    public TDB1340_ACO7[] ACO7 = new TDB1340_ACO7[20];
    public TDB1340_ACO8[] ACO8 = new TDB1340_ACO8[20];
    public TDB1340_ACO9[] ACO9 = new TDB1340_ACO9[20];
    public TDB1340_ACO10[] ACO10 = new TDB1340_ACO10[20];
    public TDB1340_AWA_1340() {
        for (int i=0;i<20;i++) ACO1[i] = new TDB1340_ACO1();
        for (int i=0;i<20;i++) ACO2[i] = new TDB1340_ACO2();
        for (int i=0;i<20;i++) ACO3[i] = new TDB1340_ACO3();
        for (int i=0;i<20;i++) ACO4[i] = new TDB1340_ACO4();
        for (int i=0;i<20;i++) ACO5[i] = new TDB1340_ACO5();
        for (int i=0;i<20;i++) ACO6[i] = new TDB1340_ACO6();
        for (int i=0;i<20;i++) ACO7[i] = new TDB1340_ACO7();
        for (int i=0;i<20;i++) ACO8[i] = new TDB1340_ACO8();
        for (int i=0;i<20;i++) ACO9[i] = new TDB1340_ACO9();
        for (int i=0;i<20;i++) ACO10[i] = new TDB1340_ACO10();
    }
}
