package com.hisun.TD;

public class TDCBVEXC {
    public String BV_CD_O = " ";
    public char BV_TYP_O = ' ';
    public String BV_NO_O = " ";
    public String MAIN_AC_O = " ";
    public String CARD_NO_O = " ";
    public short CVV_O = 0;
    public int AC_SEQ_O = 0;
    public String AC_O = " ";
    public short P_SEQ_O = 0;
    public short P_POS_O = 0;
    public String AC_NM = " ";
    public char DRAW_MTH_O = ' ';
    public String PSW_O = " ";
    public int SEAL_NO_O = 0;
    public String ID_TYP_O = " ";
    public String ID_NO_O = " ";
    public String BV_CD_I = " ";
    public char BV_TYP_I = ' ';
    public String BV_NO_I = " ";
    public String MAIN_AC_I = " ";
    public String CARD_NO_I = " ";
    public String AC_I = " ";
    public short P_SEQ_I = 0;
    public String AC_NM_I = " ";
    public char DRAW_MTH_I = ' ';
    public String PSW_I = " ";
    public String ID_TYP_I = " ";
    public String ID_NO_I = " ";
    public char CERF_OPT = ' ';
    public char BOOK_TYP = ' ';
    public String BOOK_NO = " ";
    public String BOOK_TOP = " ";
    public String PLD_NO = " ";
    public char INT_STS = ' ';
    public String REMARK = " ";
    public char PLD_STS = ' ';
    public short PSBK_SEQ = 0;
    public int PAGE_ROW = 0;
    public int PAGE_NUM = 0;
}
