package com.hisun.TD;

public class TDCTLZCC {
    public String BV_CD = " ";
    public char BV_TYP = ' ';
    public char PRT_FLG = ' ';
    public String BV_NO = " ";
    public String CARD_NO = " ";
    public short CVV = 0;
    public int AC_SEQ = 0;
    public String AC = " ";
    public String NAME = " ";
    public String ADDR = " ";
    public String CCY = " ";
    public char CCY_TYP = ' ';
    public short FC_CD = 0;
    public double PSBK_BAL = 0;
    public double TXN_AMT = 0;
    public char CT_FLG = ' ';
    public String OPP_AC = " ";
    public String OPP_BV_NO = " ";
    public String OPP_CARD_NO = " ";
    public short OPP_CVV = 0;
    public String OPP_NAME = " ";
    public String OPP_REV_NO = " ";
    public char OPP_DRAW_MTH = ' ';
    public String OPP_PSW = " ";
    public String OPP_ID_TYP = " ";
    public String OPP_ID_NO = " ";
    public int OPP_SEAL_NO = 0;
    public char CHQ_TYPE = ' ';
    public String CHQ_NO = " ";
    public int CHQ_DATE = 0;
    public String PAY_PSW = " ";
    public String TXN_CHNL = " ";
    public char TXN_PNT = ' ';
    public short NOR_NUM = 0;
    public short LOS_DNUM = 0;
    public short LOS_NUM = 0;
    public String CI_NO = " ";
    public int LAST_DT = 0;
    public String AC_TRK2 = " ";
    public String AC_TRK3 = " ";
    public String OPP_TRK2 = " ";
    public String OPP_TRK3 = " ";
}
