package com.hisun.TD;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;
import com.hisun.CI.*;
import com.hisun.BP.*;

import java.io.IOException;
import java.sql.SQLException;

public class TDOT5103 {
    int JIBS_tmp_int;
    String JIBS_tmp_str[] = new String[10];
    String JIBS_NumStr;
    String WS_ERR_MSG = " ";
    short WS_FLD_NO = 0;
    char WS_CI_TYP = ' ';
    short WS_RC = 0;
    short WS_RC_DISP = 0;
    TDCMSG_ERROR_MSG TDCMSG_ERROR_MSG = new TDCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCMSG SCCMSG = new SCCMSG();
    SCCCALL SCCCALL = new SCCCALL();
    CICCUST CICCUST = new CICCUST();
    BPCPQPRD BPCPQPRD = new BPCPQPRD();
    TDCMACO TDCMACO = new TDCMACO();
    TDCTZZC TDCTZZC = new TDCTZZC();
    TDCTTZC TDCTTZC = new TDCTTZC();
    TDCTDHC TDCTDHC = new TDCTDHC();
    TDCTXYC TDCTXYC = new TDCTXYC();
    TDCOOADV TDCOOADV = new TDCOOADV();
    BPCUBUSE BPCUBUSE = new BPCUBUSE();
    TDCBVCD TDCBVCD = new TDCBVCD();
    BPCPRMM BPCPRMM = new BPCPRMM();
    BPRPRMT BPRPRMT = new BPRPRMT();
    TDCTCDEC TDCTCDEC = new TDCTCDEC();
    SCCCLDT SCCCLDT = new SCCCLDT();
    TDCKHCR TDCKHCR = new TDCKHCR();
    SCCGWA SCCGWA;
    TDB5103_AWA_5103 TDB5103_AWA_5103;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "TDOT5103 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "TDB5103_AWA_5103>");
        TDB5103_AWA_5103 = (TDB5103_AWA_5103) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        CEP.TRC(SCCGWA, TDB5103_AWA_5103.INOUT);
        CEP.TRC(SCCGWA, TDB5103_AWA_5103.OPP_NAME);
        CEP.TRC(SCCGWA, TDB5103_AWA_5103.INT_AC);
        CEP.TRC(SCCGWA, TDB5103_AWA_5103.BV_CD);
        CEP.TRC(SCCGWA, TDB5103_AWA_5103.RULE);
        CEP.TRC(SCCGWA, TDB5103_AWA_5103.APP_NO);
        CEP.TRC(SCCGWA, TDB5103_AWA_5103.VAL_DT);
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.AC_DATE);
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, TDB5103_AWA_5103.AC_NO);
        if (SCCGWA.COMM_AREA.CANCEL_IND == 'Y') {
            B010_GET_CI_INFO();
            B020_GET_PROD_MODEL_PROC();
            B030_TRANS_DATA_PROC();
        } else {
            CEP.TRC(SCCGWA, TDB5103_AWA_5103.INOUT);
            CEP.TRC(SCCGWA, TDB5103_AWA_5103.OPP_NAME);
            CEP.TRC(SCCGWA, TDB5103_AWA_5103.INT_AC);
            B010_TRANS_MACO_PROC();
            CEP.TRC(SCCGWA, TDB5103_AWA_5103.INOUT);
            CEP.TRC(SCCGWA, TDB5103_AWA_5103.OPP_NAME);
            CEP.TRC(SCCGWA, TDB5103_AWA_5103.INT_AC);
            B030_TRANS_DATA_PROC();
        }
    }
    public void B010_GET_CI_INFO() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, CICCUST);
        if (TDB5103_AWA_5103.CI_NO.trim().length() > 0) {
            CICCUST.DATA.CI_NO = TDB5103_AWA_5103.CI_NO;
            CICCUST.FUNC = 'C';
        } else {
            CEP.TRC(SCCGWA, TDB5103_AWA_5103.AC_NO);
            CEP.TRC(SCCGWA, TDB5103_AWA_5103.GAC_NO);
            if (TDB5103_AWA_5103.AC_NO.trim().length() == 0) {
                CICCUST.DATA.AGR_NO = TDB5103_AWA_5103.GAC_NO;
            } else {
                CICCUST.DATA.AGR_NO = TDB5103_AWA_5103.AC_NO;
            }
            CICCUST.FUNC = 'A';
        }
        S000_LINK_CIZCUST();
        WS_CI_TYP = CICCUST.O_DATA.O_CI_TYP;
        CEP.TRC(SCCGWA, WS_CI_TYP);
    }
    public void B010_TRANS_MACO_PROC_CANCEL() throws IOException,SQLException,Exception {
        if (TDB5103_AWA_5103.BV_TYP != ' ' 
            && TDB5103_AWA_5103.BV_TYP != '4') {
            IBS.init(SCCGWA, BPCPRMM);
            BPCPRMM.FUNC = '3';
            BPRPRMT.KEY.TYP = "TDP";
            BPRPRMT.KEY.CD = "" + TDB5103_AWA_5103.BV_TYP;
            JIBS_tmp_int = BPRPRMT.KEY.CD.length();
            for (int i=0;i<1-JIBS_tmp_int;i++) BPRPRMT.KEY.CD = "0" + BPRPRMT.KEY.CD;
            BPCPRMM.EFF_DT = SCCGWA.COMM_AREA.AC_DATE;
            BPCPRMM.DAT_PTR = BPRPRMT;
            S000_CALL_BPZPRMM();
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, BPRPRMT.DAT_TXT);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], TDCBVCD);
            TDB5103_AWA_5103.BV_CD = TDCBVCD.CD;
        }
        IBS.init(SCCGWA, BPCUBUSE);
        BPCUBUSE.TLR = SCCGWA.COMM_AREA.TL_ID;
        BPCUBUSE.TYPE = '0';
        BPCUBUSE.BV_CODE = TDB5103_AWA_5103.BV_CD;
        BPCUBUSE.BEG_NO = TDB5103_AWA_5103.BV_NO;
        BPCUBUSE.END_NO = TDB5103_AWA_5103.BV_NO;
        BPCUBUSE.NUM = 1;
        S000_CALL_BPZUBUSE();
    }
    public void B010_TRANS_MACO_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, CICCUST);
    }
    public void B020_GET_PROD_MODEL_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCPQPRD);
        CEP.TRC(SCCGWA, TDB5103_AWA_5103.PROD_CD);
        BPCPQPRD.PRDT_CODE = TDB5103_AWA_5103.PROD_CD;
        S000_CALL_BPZPQPRD();
    }
    public void B030_TRANS_DATA_PROC() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, TDB5103_AWA_5103.TXN_AMT);
        IBS.init(SCCGWA, TDCKHCR);
        TDCKHCR.PROD_CD = TDB5103_AWA_5103.PROD_CD;
        TDCKHCR.MPROD_CD = TDB5103_AWA_5103.MPROD_CD;
        TDCKHCR.BV_CD = TDB5103_AWA_5103.BV_CD;
        CEP.TRC(SCCGWA, TDB5103_AWA_5103.BV_CD);
        TDCKHCR.BV_TYP = TDB5103_AWA_5103.BV_TYP;
        TDCKHCR.PRT_FLG = TDB5103_AWA_5103.PRT_FLG;
        TDCKHCR.BV_NO = TDB5103_AWA_5103.BV_NO;
        TDCKHCR.CVV = TDB5103_AWA_5103.CVV;
        TDCKHCR.ID_TYP = TDB5103_AWA_5103.ID_TYP;
        TDCKHCR.ID_NO = TDB5103_AWA_5103.ID_NO;
        TDCKHCR.CI_NO = TDB5103_AWA_5103.CI_NO;
        TDCKHCR.NAME = TDB5103_AWA_5103.AC_NAME;
        TDCKHCR.CCY = TDB5103_AWA_5103.CCY;
        TDCKHCR.CCY_TYP = TDB5103_AWA_5103.CCY_TYP;
        TDCKHCR.FC_CD = TDB5103_AWA_5103.FC_CD;
        TDCKHCR.FC_NO = TDB5103_AWA_5103.FC_NO;
        TDCKHCR.TXN_AMT = TDB5103_AWA_5103.TXN_AMT;
        TDCKHCR.TERM = TDB5103_AWA_5103.TERM;
        TDCKHCR.INSTR_MTH = TDB5103_AWA_5103.INR_MTH;
        TDCKHCR.INSTR_TERM = TDB5103_AWA_5103.INR_TERM;
        TDCKHCR.CD_AMT = TDB5103_AWA_5103.CD_AMT;
        TDCKHCR.DRAW_MTH = TDB5103_AWA_5103.D_MTH;
        CEP.TRC(SCCGWA, TDB5103_AWA_5103.D_MTH);
        CEP.TRC(SCCGWA, TDCKHCR.DRAW_MTH);
        CEP.TRC(SCCGWA, TDB5103_AWA_5103.INT_RAT);
        CEP.TRC(SCCGWA, TDB5103_AWA_5103.INT_SEL);
        CEP.TRC(SCCGWA, TDB5103_AWA_5103.PSW);
        CEP.TRC(SCCGWA, TDB5103_AWA_5103.CPSW_FLG);
        TDCKHCR.CUS_PSW_FLG = TDB5103_AWA_5103.CPSW_FLG;
        TDCKHCR.PSW = TDB5103_AWA_5103.PSW;
        TDCKHCR.CROS_CR_FLG = TDB5103_AWA_5103.CR_FLG;
        TDCKHCR.CROS_DR_FLG = TDB5103_AWA_5103.DR_FLG;
        TDCKHCR.VAL_DT = TDB5103_AWA_5103.VAL_DT;
        TDCKHCR.INT_SEL = TDB5103_AWA_5103.INT_SEL;
        TDCKHCR.SPRD_PCT = TDB5103_AWA_5103.PCT_S;
        TDCKHCR.SPRD_PNT = TDB5103_AWA_5103.FLT_RAT;
        TDCKHCR.AC_RUL_CD = TDB5103_AWA_5103.ACRUL_CD;
        TDCKHCR.INT_RAT = TDB5103_AWA_5103.INT_RAT;
        TDCKHCR.CT_FLG = TDB5103_AWA_5103.CT_FLG;
        CEP.TRC(SCCGWA, TDB5103_AWA_5103.OPP_AC);
        TDCKHCR.OPP_AC = TDB5103_AWA_5103.OPP_AC;
        CEP.TRC(SCCGWA, TDB5103_AWA_5103.OPBV_TYP);
        TDCKHCR.OPP_BV = TDB5103_AWA_5103.OPBV_TYP;
        TDCKHCR.OPP_BV_NO = TDB5103_AWA_5103.OPBV_NO;
        TDCKHCR.OPP_NAME = TDB5103_AWA_5103.OPP_NAME;
        TDCKHCR.OPP_REV_NO = TDB5103_AWA_5103.OPREV_NO;
        TDCKHCR.OPP_DRAW_MTH = TDB5103_AWA_5103.OPD_MTH;
        TDCKHCR.OPP_PSW = TDB5103_AWA_5103.OP_PSW;
        TDCKHCR.OPP_ID_TYP = TDB5103_AWA_5103.OP_IDTYP;
        TDCKHCR.OPP_ID_NO = TDB5103_AWA_5103.OP_IDNO;
        TDCKHCR.CHQ_TYPE = TDB5103_AWA_5103.CHQ_TYPE;
        TDCKHCR.CHQ_NO = TDB5103_AWA_5103.CHQ_NO;
        TDCKHCR.CHQ_DATE = TDB5103_AWA_5103.CHQ_DATE;
        TDCKHCR.TXN_CHNL = TDB5103_AWA_5103.TXN_CHNL;
        JIBS_NumStr = "" + TDB5103_AWA_5103.TXN_PNT;
        TDCKHCR.TXN_PNT = JIBS_NumStr.charAt(0);
        TDCKHCR.AC = TDB5103_AWA_5103.AC_NO;
        if (SCCGWA.COMM_AREA.CANCEL_IND == 'Y') {
            TDCKHCR.AC = TDB5103_AWA_5103.GAC_NO;
        }
        TDCKHCR.CALR_STD = TDB5103_AWA_5103.CALR_STD;
        CEP.TRC(SCCGWA, TDB5103_AWA_5103.ZC_NUM);
        TDCKHCR.ZC_NUM = TDB5103_AWA_5103.ZC_NUM;
        CEP.TRC(SCCGWA, TDB5103_AWA_5103.INOUT);
        CEP.TRC(SCCGWA, TDB5103_AWA_5103.OPP_NAME);
        CEP.TRC(SCCGWA, TDB5103_AWA_5103.INT_AC);
        TDCKHCR.INT_AC = TDB5103_AWA_5103.INT_AC;
        TDCKHCR.STL_INT_AC = TDB5103_AWA_5103.STL_ITAC;
        TDCKHCR.TAX_RAT = TDB5103_AWA_5103.TAX_RAT;
        TDCKHCR.PRV_RAT = TDB5103_AWA_5103.PRV_RAT;
        TDCKHCR.EXP_DT = TDB5103_AWA_5103.EXP_DT;
        TDCKHCR.XC_UP_FLG = TDB5103_AWA_5103.UP_FLG;
        TDCKHCR.OPP_TRK2 = TDB5103_AWA_5103.OP_TRK2;
        TDCKHCR.OPP_TRK3 = TDB5103_AWA_5103.OP_TRK3;
        TDCKHCR.PAY_PSW = TDB5103_AWA_5103.PSW;
        TDCKHCR.AC_TRK2 = TDB5103_AWA_5103.TRK2;
        TDCKHCR.AC_TRK3 = TDB5103_AWA_5103.TRK3;
        TDCKHCR.AC_NAME = TDB5103_AWA_5103.AC_NAME;
        TDCKHCR.ACTI_NO = TDB5103_AWA_5103.ACTI_NO;
        TDCKHCR.RMIT_BK = TDB5103_AWA_5103.RMIT_BK;
        TDCKHCR.EXP_DT = TDB5103_AWA_5103.EXP_DT;
        TDCKHCR.ATTY_ID_TYP = TDB5103_AWA_5103.D_ID_TYP;
        TDCKHCR.ATTY_ID_NO = TDB5103_AWA_5103.D_ID_NO;
        TDCKHCR.D_INF = TDB5103_AWA_5103.D_INF;
        TDCKHCR.RATE_TYP = TDB5103_AWA_5103.RATE_TYP;
        TDCKHCR.TENOR = TDB5103_AWA_5103.TENOR;
        TDCKHCR.CHQ_PSW = TDB5103_AWA_5103.CHQ_PSW;
        TDCKHCR.OPP_CVV = TDB5103_AWA_5103.OPP_CVV;
        TDCKHCR.MMO = TDB5103_AWA_5103.MMO;
        TDCKHCR.SEAL_NO = TDB5103_AWA_5103.SEAL_NO;
        TDCKHCR.AUTO_FLG = TDB5103_AWA_5103.AUTO_FLG;
        TDCKHCR.PERD_TYP = TDB5103_AWA_5103.PERD_TYP;
        TDCKHCR.CD_PERD = TDB5103_AWA_5103.CD_PERD;
        TDCKHCR.FRAT_DT = TDB5103_AWA_5103.FRAT_DT;
        TDCKHCR.GK_BVTYP = TDB5103_AWA_5103.GK_BVTYP;
        TDCKHCR.GK_BAL = TDB5103_AWA_5103.GK_BAL;
        TDCKHCR.GK_PSW = TDB5103_AWA_5103.GK_PSW;
        TDCKHCR.INOUT = TDB5103_AWA_5103.INOUT;
        TDCKHCR.RMIT_NM = TDB5103_AWA_5103.RMIT_NM;
        TDCKHCR.FRG_IND = TDB5103_AWA_5103.FRG_IND;
        TDCKHCR.OIC_NO = TDB5103_AWA_5103.OIC_NO;
        TDCKHCR.RES_CD = TDB5103_AWA_5103.RES_CD;
        TDCKHCR.SUB_DP = TDB5103_AWA_5103.SUB_DP;
        TDCKHCR.MON_TYP = TDB5103_AWA_5103.MON_TYP;
        TDCKHCR.ACO_TYP = TDB5103_AWA_5103.ACO_TYP;
        TDCKHCR.REMARK = TDB5103_AWA_5103.REMARK;
        TDCKHCR.OVE_RAT = TDB5103_AWA_5103.OVE_RAT;
        TDCKHCR.DUE_RAT = TDB5103_AWA_5103.DUE_RAT;
        TDCKHCR.ATTY_NAME = TDB5103_AWA_5103.OPP_NAME;
        TDCKHCR.GACO_AC = TDB5103_AWA_5103.GACO_AC;
        TDCKHCR.GAC_NO = TDB5103_AWA_5103.GAC_NO;
        TDCKHCR.GFST = TDB5103_AWA_5103.GFST;
        TDCKHCR.APP_NO = TDB5103_AWA_5103.APP_NO;
        CEP.TRC(SCCGWA, TDB5103_AWA_5103.RULE);
        TDCKHCR.RULE = TDB5103_AWA_5103.RULE;
        TDCKHCR.RECOM_TYP = TDB5103_AWA_5103.RECM_TYP;
        TDCKHCR.RECOM_ID_TYPE = TDB5103_AWA_5103.RCID_TYP;
        TDCKHCR.RECOM_ID_NO = TDB5103_AWA_5103.RCID_NO;
        CEP.TRC(SCCGWA, TDB5103_AWA_5103.NOTI_FLG);
        TDCKHCR.NOTI_FLG = TDB5103_AWA_5103.NOTI_FLG;
        TDCKHCR.ACBR_FLG = TDB5103_AWA_5103.ACBR_FLG;
        CEP.TRC(SCCGWA, TDCKHCR.RULE);
        CEP.TRC(SCCGWA, TDB5103_AWA_5103.GACO_AC);
        CEP.TRC(SCCGWA, TDB5103_AWA_5103.GAC_NO);
        CEP.TRC(SCCGWA, TDB5103_AWA_5103.GFST);
        S000_CALL_TDZKHCR();
        CEP.TRC(SCCGWA, TDCKHCR.GFST);
        TDB5103_AWA_5103.AC_NO = TDCKHCR.AC;
        TDB5103_AWA_5103.GAC_NO = TDCKHCR.AC;
        TDB5103_AWA_5103.GACO_AC = TDCKHCR.GACO_AC;
        TDB5103_AWA_5103.GFST = TDCKHCR.GFST;
    }
    public void S000_CALL_TDZTCDEC() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "TD-TCDE-CR", TDCTCDEC);
    }
    public void S000_CALL_BPZPRMM() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-PARM-MAINTAIN", BPCPRMM);
        if (BPCPRMM.RC.RC_RTNCODE != 0) {
            WS_ERR_MSG = IBS.CLS2CPY(SCCGWA, BPCPRMM.RC);
            CEP.ERR(SCCGWA, WS_ERR_MSG);
        }
    }
    public void S000_CALL_BPZUBUSE() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-U-TLR-BV-USE", BPCUBUSE);
    }
    public void S000_LINK_CIZCUST() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "CI-INQ-CUST", CICCUST);
        if (CICCUST.RC.RC_CODE != 0) {
            WS_ERR_MSG = IBS.CLS2CPY(SCCGWA, CICCUST.RC);
            CEP.ERR(SCCGWA, WS_ERR_MSG);
        }
    }
    public void S000_CALL_TDZMACO() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "TD-MACO-CR", TDCMACO);
    }
    public void S000_CALL_BPZPQPRD() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-P-QUERY-PRDT-INFO", BPCPQPRD);
        if (BPCPQPRD.RC.RC_CODE != 0) {
            WS_ERR_MSG = IBS.CLS2CPY(SCCGWA, BPCPQPRD.RC);
            CEP.ERR(SCCGWA, WS_ERR_MSG);
        }
    }
    public void S000_CALL_TDZKHCR() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "TD-KH-CR", TDCKHCR);
    }
    public void S000_CALL_TDZTDHC() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "TD-TDH-CR", TDCTDHC);
    }
    public void S000_CALL_TDZTTZC() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "TD-TTZ-CR", TDCTTZC);
    }
    public void S000_CALL_TDZTXYC() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "TD-TXY-CR", TDCTXYC);
    }
    public void S000_CALL_SCSSCLDT() throws IOException,SQLException,Exception {
        SCSSCLDT SCSSCLDT1 = new SCSSCLDT();
        WS_RC = 0;
        SCSSCLDT1.MP(SCCGWA, SCCCLDT);
        if (WS_RC != 0) {
            SCCCLDT.RC = WS_RC;
        }
        CEP.TRC(SCCGWA, SCCCLDT.RC);
        if (SCCCLDT.RC != 0) {
            CEP.ERR(SCCGWA, TDCMSG_ERROR_MSG.TD_OTHER_ERR);
        }
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
