package com.hisun.TD;

public class TDRIREV {
    public TDRIREV_KEY KEY = new TDRIREV_KEY();
    public int END_DATE = 0;
    public char RATE_SEL = ' ';
    public char ERLY_TYP = ' ';
    public String ACTI_NO = " ";
    public char DOCU_FLG = ' ';
    public String DOCU_NO = " ";
    public String INT_RUL_CD = " ";
    public double BAL = 0;
    public String CCY = " ";
    public String TERM = " ";
    public short LVL = 0;
    public String GRPS_NO = " ";
    public String ASS_LVL = " ";
    public int BR = 0;
    public String CITY_CD = " ";
    public String CHNL_NO = " ";
    public String OTH_FIL = " ";
    public double PRD_RATE = 0;
    public String RATE_TYPE = " ";
    public String TENOR = " ";
    public double PRD_SPRD = 0;
    public char INT_SEL = ' ';
    public double SPRD_PNT = 0;
    public double SPRD_PCT = 0;
    public double DIS_SPRD = 0;
    public double CON_SPRD = 0;
    public double CON_RATE = 0;
    public String FEE_RUL_CD = " ";
    public double MIN_INT_RATE = 0;
    public double MAX_INT_RATE = 0;
    public String NAR = " ";
    public int OWNER_BR = 0;
    public int OWNER_BRDP = 0;
    public int OWNER_BK = 0;
    public String CRT_TLR = " ";
    public int CRT_DATE = 0;
    public String UPD_TLT = " ";
    public int UPD_DATE = 0;
    public int UPD_TIME = 0;
    public String TS = " ";
}
