package com.hisun.TD;

import com.hisun.SC.*;
import com.hisun.SC.SCCCALL;
import com.hisun.SC.SCCEXCP;
import com.hisun.SC.SCCFMT;
import com.hisun.SC.SCCGBPA_BP_AREA;
import com.hisun.SC.SCCGSCA_SC_AREA;
import com.hisun.SC.SCCGWA;
import com.hisun.SC.SCCMSG;

import java.io.IOException;
import java.sql.SQLException;

public class TDZQAPBL {
    DBParm TDTAPBL_RD;
    String WS_AGR_NO = " ";
    char WS_APBL_FLG = ' ';
    TDCMSG_ERROR_MSG TDCMSG_ERROR_MSG = new TDCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCFMT SCCFMT = new SCCFMT();
    SCCMSG SCCMSG = new SCCMSG();
    TDRAPBL TDRAPBL = new TDRAPBL();
    SCCGWA SCCGWA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    TDCQAPBL TDCQAPBL;
    public void MP(SCCGWA SCCGWA, TDCQAPBL TDCQAPBL) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        this.TDCQAPBL = TDCQAPBL;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "TDZQAPBL return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B010_CHECK_INPUT_DATA();
        B020_INQ_BY_ACO_AC();
    }
    public void B010_CHECK_INPUT_DATA() throws IOException,SQLException,Exception {
    }
    public void B020_INQ_BY_ACO_AC() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, TDCQAPBL.ACO_AC);
        IBS.init(SCCGWA, TDRAPBL);
        TDRAPBL.KEY.ACO_AC = TDCQAPBL.ACO_AC;
        T000_READ_TDTAPBL();
        TDCQAPBL.MCCY = TDRAPBL.MCCY;
        TDCQAPBL.MAPP = TDRAPBL.MAPP;
        TDCQAPBL.BRCH_OLD = TDRAPBL.BRCH_OLD;
        TDCQAPBL.BRCH_NEW = TDRAPBL.BRCH_NEW;
        TDCQAPBL.MCNTR_TYPE = TDRAPBL.MCNTR_TYPE;
        TDCQAPBL.MPROD_TYPE = TDRAPBL.MPROD_TYPE;
        TDCQAPBL.MREF_NO = TDRAPBL.MREF_NO;
        TDCQAPBL.MCI_NO = TDRAPBL.MCI_NO;
        TDCQAPBL.TGLM_1 = TDRAPBL.TGLM_1;
        TDCQAPBL.TITM1_1 = TDRAPBL.TITM1_1;
        TDCQAPBL.TITM2_1 = TDRAPBL.TITM2_1;
        TDCQAPBL.TGLM_2 = TDRAPBL.TGLM_2;
        TDCQAPBL.TITM1_2 = TDRAPBL.TITM1_2;
        TDCQAPBL.TITM2_2 = TDRAPBL.TITM2_2;
        TDCQAPBL.TGLM_3 = TDRAPBL.TGLM_3;
        TDCQAPBL.TITM1_3 = TDRAPBL.TITM1_3;
        TDCQAPBL.TITM2_3 = TDRAPBL.TITM2_3;
        TDCQAPBL.TGLM_4 = TDRAPBL.TGLM_4;
        TDCQAPBL.TITM1_4 = TDRAPBL.TITM1_4;
        TDCQAPBL.TITM2_4 = TDRAPBL.TITM2_4;
        TDCQAPBL.TGLM_5 = TDRAPBL.TGLM_5;
        TDCQAPBL.TITM1_5 = TDRAPBL.TITM1_5;
        TDCQAPBL.TITM2_5 = TDRAPBL.TITM2_5;
        TDCQAPBL.TGLM_6 = TDRAPBL.TGLM_6;
        TDCQAPBL.TITM1_6 = TDRAPBL.TITM1_6;
        TDCQAPBL.TITM2_6 = TDRAPBL.TITM2_6;
        TDCQAPBL.TGLM_7 = TDRAPBL.TGLM_7;
        TDCQAPBL.TITM1_7 = TDRAPBL.TITM1_7;
        TDCQAPBL.TITM2_7 = TDRAPBL.TITM2_7;
        TDCQAPBL.TGLM_8 = TDRAPBL.TGLM_8;
        TDCQAPBL.TITM1_8 = TDRAPBL.TITM1_8;
        TDCQAPBL.TITM2_8 = TDRAPBL.TITM2_8;
        TDCQAPBL.TGLM_9 = TDRAPBL.TGLM_9;
        TDCQAPBL.TITM1_9 = TDRAPBL.TITM1_9;
        TDCQAPBL.TITM2_9 = TDRAPBL.TITM2_9;
        TDCQAPBL.TGLM_10 = TDRAPBL.TGLM_10;
        TDCQAPBL.TITM1_10 = TDRAPBL.TITM1_10;
        TDCQAPBL.TITM2_10 = TDRAPBL.TITM2_10;
        TDCQAPBL.TBAL1 = TDRAPBL.TBAL1;
        TDCQAPBL.TBAL2 = TDRAPBL.TBAL2;
        TDCQAPBL.TBAL3 = TDRAPBL.TBAL3;
        TDCQAPBL.TBAL4 = TDRAPBL.TBAL4;
        TDCQAPBL.TBAL5 = TDRAPBL.TBAL5;
        TDCQAPBL.TBAL6 = TDRAPBL.TBAL6;
        TDCQAPBL.TBAL7 = TDRAPBL.TBAL7;
        TDCQAPBL.TBAL8 = TDRAPBL.TBAL8;
        TDCQAPBL.TBAL9 = TDRAPBL.TBAL9;
        TDCQAPBL.TBAL10 = TDRAPBL.TBAL10;
        TDCQAPBL.TBAL11 = TDRAPBL.TBAL11;
        TDCQAPBL.TBAL12 = TDRAPBL.TBAL12;
        TDCQAPBL.TBAL13 = TDRAPBL.TBAL13;
        TDCQAPBL.TBAL14 = TDRAPBL.TBAL14;
        TDCQAPBL.TBAL15 = TDRAPBL.TBAL15;
        TDCQAPBL.TBAL16 = TDRAPBL.TBAL16;
        TDCQAPBL.TBAL17 = TDRAPBL.TBAL17;
        TDCQAPBL.TBAL18 = TDRAPBL.TBAL18;
        TDCQAPBL.TBAL19 = TDRAPBL.TBAL19;
        TDCQAPBL.TBAL20 = TDRAPBL.TBAL20;
        TDCQAPBL.TBAL21 = TDRAPBL.TBAL21;
        TDCQAPBL.TBAL22 = TDRAPBL.TBAL22;
        TDCQAPBL.TBAL23 = TDRAPBL.TBAL23;
        TDCQAPBL.TBAL24 = TDRAPBL.TBAL24;
        TDCQAPBL.TBAL25 = TDRAPBL.TBAL25;
        TDCQAPBL.TBAL26 = TDRAPBL.TBAL26;
        TDCQAPBL.TBAL27 = TDRAPBL.TBAL27;
        TDCQAPBL.TBAL28 = TDRAPBL.TBAL28;
        TDCQAPBL.TBAL29 = TDRAPBL.TBAL29;
        TDCQAPBL.TBAL30 = TDRAPBL.TBAL30;
        TDCQAPBL.TBAL31 = TDRAPBL.TBAL31;
        TDCQAPBL.TBAL32 = TDRAPBL.TBAL32;
        TDCQAPBL.TBAL33 = TDRAPBL.TBAL33;
        TDCQAPBL.TBAL34 = TDRAPBL.TBAL34;
        TDCQAPBL.TBAL35 = TDRAPBL.TBAL35;
        TDCQAPBL.TBAL36 = TDRAPBL.TBAL36;
        TDCQAPBL.TBAL37 = TDRAPBL.TBAL37;
        TDCQAPBL.TBAL38 = TDRAPBL.TBAL38;
        TDCQAPBL.TBAL39 = TDRAPBL.TBAL39;
        TDCQAPBL.TBAL40 = TDRAPBL.TBAL40;
        TDCQAPBL.TBAL41 = TDRAPBL.TBAL41;
        TDCQAPBL.TBAL42 = TDRAPBL.TBAL42;
        TDCQAPBL.TBAL43 = TDRAPBL.TBAL43;
        TDCQAPBL.TBAL44 = TDRAPBL.TBAL44;
        TDCQAPBL.TBAL45 = TDRAPBL.TBAL45;
        TDCQAPBL.TBAL46 = TDRAPBL.TBAL46;
        TDCQAPBL.TBAL47 = TDRAPBL.TBAL47;
        TDCQAPBL.TBAL48 = TDRAPBL.TBAL48;
        TDCQAPBL.TBAL49 = TDRAPBL.TBAL49;
        TDCQAPBL.TBAL50 = TDRAPBL.TBAL50;
        TDCQAPBL.TBAL51 = TDRAPBL.TBAL51;
        TDCQAPBL.TBAL52 = TDRAPBL.TBAL52;
        TDCQAPBL.TBAL53 = TDRAPBL.TBAL53;
        TDCQAPBL.TBAL54 = TDRAPBL.TBAL54;
        TDCQAPBL.TBAL55 = TDRAPBL.TBAL55;
        TDCQAPBL.TBAL56 = TDRAPBL.TBAL56;
        TDCQAPBL.TBAL57 = TDRAPBL.TBAL57;
        TDCQAPBL.TBAL58 = TDRAPBL.TBAL58;
        TDCQAPBL.TBAL59 = TDRAPBL.TBAL59;
        TDCQAPBL.TBAL60 = TDRAPBL.TBAL60;
        TDCQAPBL.TBAL61 = TDRAPBL.TBAL61;
        TDCQAPBL.TBAL62 = TDRAPBL.TBAL62;
        TDCQAPBL.TBAL63 = TDRAPBL.TBAL63;
        TDCQAPBL.TBAL64 = TDRAPBL.TBAL64;
        TDCQAPBL.TBAL65 = TDRAPBL.TBAL65;
        TDCQAPBL.TBAL66 = TDRAPBL.TBAL66;
        TDCQAPBL.TBAL67 = TDRAPBL.TBAL67;
        TDCQAPBL.TBAL68 = TDRAPBL.TBAL68;
        TDCQAPBL.TBAL69 = TDRAPBL.TBAL69;
        TDCQAPBL.TBAL70 = TDRAPBL.TBAL70;
        TDCQAPBL.TBAL71 = TDRAPBL.TBAL71;
        TDCQAPBL.TBAL72 = TDRAPBL.TBAL72;
        TDCQAPBL.TBAL73 = TDRAPBL.TBAL73;
        TDCQAPBL.TBAL74 = TDRAPBL.TBAL74;
        TDCQAPBL.TBAL75 = TDRAPBL.TBAL75;
        TDCQAPBL.TBAL76 = TDRAPBL.TBAL76;
        TDCQAPBL.PRIN_AMT = TDRAPBL.PRIN_AMT;
        TDCQAPBL.IB_BK_DT = TDRAPBL.IB_BK_DT;
        TDCQAPBL.DY_AMT = TDRAPBL.DY_AMT;
        TDCQAPBL.DY_AMT_ADJ = TDRAPBL.DY_AMT_ADJ;
        TDCQAPBL.DY_AMT_POST = TDRAPBL.DY_AMT_POST;
        TDCQAPBL.DY_AMT_TOT = TDRAPBL.DY_AMT_TOT;
        TDCQAPBL.DY_AMT_TOT_ALL = TDRAPBL.DY_AMT_TOT_ALL;
        TDCQAPBL.STR_DATE = TDRAPBL.STR_DATE;
        TDCQAPBL.MAT_DATE = TDRAPBL.MAT_DATE;
        TDCQAPBL.RATE = TDRAPBL.RATE;
        TDCQAPBL.REMK = TDRAPBL.REMK;
        TDCQAPBL.DORMANT_FLAG = TDRAPBL.DORMANT_FLAG;
        TDCQAPBL.ACCR_TIME_FLG = TDRAPBL.ACCR_TIME_FLG;
        TDCQAPBL.DESC = TDRAPBL.DESC;
        TDCQAPBL.OWNER_BK = TDRAPBL.OWNER_BK;
        TDCQAPBL.CRT_TLR = TDRAPBL.CRT_TLR;
        TDCQAPBL.CRT_DATE = TDRAPBL.CRT_DATE;
        TDCQAPBL.UPD_TLT = TDRAPBL.UPD_TLT;
        TDCQAPBL.UPD_DATE = TDRAPBL.UPD_DATE;
        TDCQAPBL.UPD_TIME = TDRAPBL.UPD_TIME;
        TDCQAPBL.TS = TDRAPBL.TS;
    }
    public void T000_READ_TDTAPBL() throws IOException,SQLException,Exception {
        TDTAPBL_RD = new DBParm();
        TDTAPBL_RD.TableName = "TDTAPBL";
        IBS.READ(SCCGWA, TDRAPBL, TDTAPBL_RD);
        if (SCCGWA.COMM_AREA.DBIO_FLG == '0') {
            WS_APBL_FLG = 'F';
        } else if (SCCGWA.COMM_AREA.DBIO_FLG == '1') {
            WS_APBL_FLG = 'N';
        } else {
            WS_APBL_FLG = 'E';
        }
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
