package com.hisun.PN;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;

import java.io.IOException;
import java.sql.SQLException;

public class PNOT1200 {
    String CPN_U_PNZUCCLR = "PN-U-CLR-PNT";
    char K_ERROR = 'E';
    String WS_ERR_MSG = " ";
    short WS_FLD_NO = 0;
    PNCMSG_ERROR_MSG PNCMSG_ERROR_MSG = new PNCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    SCCFMT SCCFMT = new SCCFMT();
    PNCUCCLR PNCUCCLR = new PNCUCCLR();
    SCCGWA SCCGWA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    PNB1200_AWA_1200 PNB1200_AWA_1200;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "PNOT1200 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "PNB1200_AWA_1200>");
        PNB1200_AWA_1200 = (PNB1200_AWA_1200) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B100_IPT_CHK_PROC();
        B200_CLR_PNT_PROC();
    }
    public void B100_IPT_CHK_PROC() throws IOException,SQLException,Exception {
        if (PNB1200_AWA_1200.BILL_NO.trim().length() == 0) {
            CEP.ERRC(SCCGWA, PNCMSG_ERROR_MSG.PN_NO_MUST_IPT, PNB1200_AWA_1200.BILL_NO_NO);
        }
        if (PNB1200_AWA_1200.BILL_KND.trim().length() == 0) {
            CEP.ERRC(SCCGWA, PNCMSG_ERROR_MSG.PN_KND_MUST_IPT, PNB1200_AWA_1200.BILL_NO);
        }
        if (PNB1200_AWA_1200.ENCRY_NO.trim().length() == 0) {
            CEP.ERRC(SCCGWA, PNCMSG_ERROR_MSG.PN_ENCRY_NOT_IPT, PNB1200_AWA_1200.ENCRY_NO_NO);
        }
        if (PNB1200_AWA_1200.STL_FLG == ' ') {
            CEP.ERRC(SCCGWA, PNCMSG_ERROR_MSG.PN_STLFLG_NOT_IPT, PNB1200_AWA_1200.STL_FLG_NO);
        }
        if (PNB1200_AWA_1200.CLR_CHNL == ' ') {
            CEP.ERRC(SCCGWA, PNCMSG_ERROR_MSG.PN_CLR_CHNL_IPT, PNB1200_AWA_1200.CLR_CHNL_NO);
        }
        if (SCCGWA.COMM_AREA.MSG_PROC_AREA.MSG_TYPE == K_ERROR 
            && SCCGWA.COMM_AREA.MSG_PROC_AREA.MSG_ID.MSG_CODE != 0) {
            CEP.ERR(SCCGWA, PNCMSG_ERROR_MSG.PN_INPUT_DATA_ERR);
        }
    }
    public void B200_CLR_PNT_PROC() throws IOException,SQLException,Exception {
        B210_CLR_PNT_PROC();
    }
    public void B210_CLR_PNT_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, PNCUCCLR);
        PNCUCCLR.KND = PNB1200_AWA_1200.BILL_KND;
        CEP.TRC(SCCGWA, PNB1200_AWA_1200.BILL_KND);
        CEP.TRC(SCCGWA, PNCUCCLR.KND);
        PNCUCCLR.CC_NO = PNB1200_AWA_1200.BILL_NO;
        CEP.TRC(SCCGWA, PNB1200_AWA_1200.BILL_NO);
        PNCUCCLR.ISS_DATE = PNB1200_AWA_1200.ISS_DATE;
        CEP.TRC(SCCGWA, PNB1200_AWA_1200.ISS_DATE);
        PNCUCCLR.ISS_AMT = PNB1200_AWA_1200.ISS_AMT;
        CEP.TRC(SCCGWA, PNB1200_AWA_1200.ISS_AMT);
        CEP.TRC(SCCGWA, PNCUCCLR.ISS_AMT);
        PNCUCCLR.CLR_CHNL = PNB1200_AWA_1200.CLR_CHNL;
        CEP.TRC(SCCGWA, PNB1200_AWA_1200.CLR_CHNL);
        PNCUCCLR.ENCRY_NO = PNB1200_AWA_1200.ENCRY_NO;
        CEP.TRC(SCCGWA, PNB1200_AWA_1200.ENCRY_NO);
        PNCUCCLR.STL_FLG = PNB1200_AWA_1200.STL_FLG;
        CEP.TRC(SCCGWA, PNB1200_AWA_1200.STL_FLG);
        PNCUCCLR.LHD_AC = PNB1200_AWA_1200.LHD_AC;
        CEP.TRC(SCCGWA, PNB1200_AWA_1200.LHD_AC);
        PNCUCCLR.LHD_NM = PNB1200_AWA_1200.LHD_NM;
        CEP.TRC(SCCGWA, PNB1200_AWA_1200.LHD_NM);
        PNCUCCLR.CLR_BK = PNB1200_AWA_1200.CLR_BK;
        CEP.TRC(SCCGWA, PNB1200_AWA_1200.CLR_BK);
        PNCUCCLR.PRDMO_CD = PNB1200_AWA_1200.PRDMO_CD;
        CEP.TRC(SCCGWA, PNB1200_AWA_1200.PRDMO_CD);
        PNCUCCLR.PROD_CD = PNB1200_AWA_1200.PROD_CD;
        CEP.TRC(SCCGWA, PNB1200_AWA_1200.PROD_CD);
        PNCUCCLR.EVENT_CD = PNB1200_AWA_1200.EVENT_CD;
        CEP.TRC(SCCGWA, PNB1200_AWA_1200.EVENT_CD);
        PNCUCCLR.PRDGL_CD = PNB1200_AWA_1200.PRDGL_CD;
        CEP.TRC(SCCGWA, PNB1200_AWA_1200.PRDGL_CD);
        PNCUCCLR.ACCT_BR = PNB1200_AWA_1200.ACCT_BR;
        CEP.TRC(SCCGWA, PNB1200_AWA_1200.ACCT_BR);
        PNCUCCLR.BCC_CINO = PNB1200_AWA_1200.BCC_CINO;
        CEP.TRC(SCCGWA, PNB1200_AWA_1200.BCC_CINO);
        S000_CALL_PNZUCCLR();
    }
    public void S000_CALL_PNZUCCLR() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, CPN_U_PNZUCCLR, PNCUCCLR);
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
