package com.hisun.PN;

import java.io.IOException;
import java.sql.SQLException;

import com.hisun.BP.BPCPORUP_DATA_INFO;
import com.hisun.BP.BPCPRMR;
import com.hisun.BP.BPRPRMT;
import com.hisun.IB.IBCQINF;
import com.hisun.SC.SCCCALL;
import com.hisun.SC.SCCEXCP;
import com.hisun.SC.SCCFMT;
import com.hisun.SC.SCCGBPA_BP_AREA;
import com.hisun.SC.SCCGSCA_SC_AREA;
import com.hisun.SC.SCCGWA;
import com.hisun.SC.SCCMPAG;
import com.hisun.SC.SCCMSG;
import com.hisun.SC.SCCTPCL;

public class PNZGHYC {
    boolean pgmRtn = false;
    String K_PARM_TYPE_TYPE = "PNYC";
    String K_PARM_CODE_TYPE = "IBACC";
    String WS_ERR_MSG = " ";
    int WS_VCH_CNT = 0;
    short WS_TOTAL_CNT = 0;
    double WS_TOTAL_AMT = 0;
    char WS_KND = ' ';
    char WS_IO_FLG = ' ';
    char WS_STS = ' ';
    char WS_MOVE_TYP = ' ';
    PNZGHYC_WS_PARMT_VAL WS_PARMT_VAL = new PNZGHYC_WS_PARMT_VAL();
    char WS_REC_FLG = ' ';
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCFMT SCCFMT = new SCCFMT();
    SCCMPAG SCCMPAG = new SCCMPAG();
    SCCMSG SCCMSG = new SCCMSG();
    SCCTPCL SCCTPCL = new SCCTPCL();
    PNCMSG_ERROR_MSG PNCMSG_ERROR_MSG = new PNCMSG_ERROR_MSG();
    BPCPRMR BPCPRMR = new BPCPRMR();
    PNCGHYC PNCGHYC = new PNCGHYC();
    PNRDFT PNRDFT = new PNRDFT();
    BPRPRMT BPRPRMT = new BPRPRMT();
    IBCQINF IBCQINF = new IBCQINF();
    SCCGWA SCCGWA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    BPCPORUP_DATA_INFO BPCPORUP;
    PNCGHYC1 PNCGHYC1;
    public void MP(SCCGWA SCCGWA, PNCGHYC1 PNCGHYC1) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        this.PNCGHYC1 = PNCGHYC1;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        if (pgmRtn) return;
        B000_MAIN_PROC();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, "PNZGHYC return!");
        Z_RET();
        if (pgmRtn) return;
        JIBS_RETURN();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        BPCPORUP = (BPCPORUP_DATA_INFO) SCCGWA.COMM_AREA.TR_BR_PTR;
        PNCGHYC1.RC.RC_MMO = "PN";
        PNCGHYC1.RC.RC_CODE = 0;
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B010_READ_UPDATE_PNTDFT();
        if (pgmRtn) return;
        PNCGHYC1.RETURN_DATE.YC_CNT = WS_TOTAL_CNT;
        PNCGHYC1.RETURN_DATE.YC_AMT = WS_TOTAL_AMT;
        if (WS_TOTAL_AMT != 0) {
            B020_SEND_FUND_OUT();
            if (pgmRtn) return;
        }
    }
    public void B010_READ_UPDATE_PNTDFT() throws IOException,SQLException,Exception {
        WS_KND = '1';
        WS_IO_FLG = 'O';
        WS_STS = '1';
        WS_MOVE_TYP = '1';
        if ("0".trim().length() == 0) WS_TOTAL_AMT = 0;
        else WS_TOTAL_AMT = Double.parseDouble("0");
        WS_REC_FLG = 'Y';
        T000_STARTBR_PNTDFT();
        if (pgmRtn) return;
        T000_READNEXT_PNTDFT();
        if (pgmRtn) return;
        while (WS_REC_FLG != 'N') {
            WS_TOTAL_CNT += 1;
            WS_TOTAL_AMT += PNRDFT.ISS_AMT;
            PNRDFT.UPDTBL_TLR = SCCGWA.COMM_AREA.TL_ID;
            PNRDFT.UPDTBL_DATE = SCCGWA.COMM_AREA.AC_DATE;
            T000_REWRITE_PNTDFT();
            if (pgmRtn) return;
            T000_READNEXT_PNTDFT();
            if (pgmRtn) return;
        }
        T000_ENDBR_PNTDFT();
        if (pgmRtn) return;
    }
    public void B020_SEND_FUND_OUT() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, SCCTPCL);
        SCCTPCL.SERV_AREA.OBJ_SYSTEM = "MIDA";
        SCCTPCL.SERV_AREA.SERV_CODE = "683600";
        SCCTPCL.SERV_AREA.SERV_TYPE = 'Y';
        B030_MOVE_DATA_PNCGHYC();
        if (pgmRtn) return;
        SCCTPCL.INP_AREA.SERV_DATA_LEN = 1044;
        SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, PNCGHYC.IN_DATA);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_CSIF_NOTICE);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_BVMS_INQ);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_BH_FILE_SEND);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_BH_FILE_ECIF);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_AC_CHG_INF);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_ACGL_GL0002);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_PASSWORD_CHK);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_SMS_INFO);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_ECIF_SG0001);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_CHG_NOTICE);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_ACGL_GL0001);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_ECIF_AC0001);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_LOAN_NOTICE);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.SN_SMS_NOTICE);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_ECIF_AC0002);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.CC_CHANGE_CARD);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.SC_SCF_NOTICE);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_ECIF_AC0003);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_IBIL_NOTICE);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_BROADCAST);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_CASH_CHG);
        S000_CALL_SCZTPCL();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA_LEN);
        CEP.TRC(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, PNCGHYC.OUT_DATA);
        CEP.TRC(SCCGWA, PNCGHYC.OUT_DATA.STATUS);
        CEP.TRC(SCCGWA, PNCGHYC.OUT_DATA);
        CEP.TRC(SCCGWA, PNCGHYC.OUT_DATA.OCHANNELCODE);
        CEP.TRC(SCCGWA, PNCGHYC.OUT_DATA.OCHANNELDATE);
        CEP.TRC(SCCGWA, PNCGHYC.OUT_DATA.OCHANNELSERNO);
        CEP.TRC(SCCGWA, PNCGHYC.OUT_DATA.STATUS);
        CEP.TRC(SCCGWA, PNCGHYC.OUT_DATA.ERRORCODE);
        CEP.TRC(SCCGWA, PNCGHYC.OUT_DATA.ERRORMSG);
        if (PNCGHYC.OUT_DATA.STATUS != '0') {
            IBS.CPY2CLS(SCCGWA, PNCMSG_ERROR_MSG.PN_CALL_YCCPN_FAIL, PNCGHYC1.RC);
            CEP.TRC(SCCGWA, PNCGHYC1.RC);
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void B030_MOVE_DATA_PNCGHYC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, PNCGHYC);
        PNCGHYC.IN_DATA.TEMPLATECODE = "002028";
        PNCGHYC.IN_DATA.TRANSCODE = "IA00101";
        PNCGHYC.IN_DATA.SYSID = "002028";
        PNCGHYC.IN_DATA.UNITNO = "000000000001";
        PNCGHYC.IN_DATA.SUBUNITNO = "000000000000";
        if ("173000".trim().length() == 0) PNCGHYC.IN_DATA.ZONENO = 0;
        else PNCGHYC.IN_DATA.ZONENO = Integer.parseInt("173000");
        if ("173001".trim().length() == 0) PNCGHYC.IN_DATA.BRNO = 0;
        else PNCGHYC.IN_DATA.BRNO = Integer.parseInt("173001");
        PNCGHYC.IN_DATA.TELLERNO = SCCGWA.COMM_AREA.TL_ID;
        PNCGHYC.IN_DATA.CASHTELNO = "AAAE0005";
        PNCGHYC.IN_DATA.TERMINALNO = SCCGWA.COMM_AREA.TERM_ID;
        PNCGHYC.IN_DATA.CHANNELCODE = "008";
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.CHNL);
        PNCGHYC.IN_DATA.CHANNELDATE = SCCGWA.COMM_AREA.AC_DATE;
        PNCGHYC.IN_DATA.CHANNELSERNO = SCCGWA.COMM_AREA.JRN_NO;
        PNCGHYC.IN_DATA.ACCMODE = '2';
        IBS.init(SCCGWA, BPRPRMT);
        IBS.init(SCCGWA, BPCPRMR);
        BPCPRMR.FUNC = ' ';
        BPRPRMT.KEY.TYP = K_PARM_TYPE_TYPE;
        BPRPRMT.KEY.CD = K_PARM_CODE_TYPE;
        CEP.TRC(SCCGWA, BPRPRMT.KEY.TYP);
        CEP.TRC(SCCGWA, BPRPRMT.KEY.CD);
        BPCPRMR.DAT_PTR = BPRPRMT;
        S000_CALL_BPZPRMR();
        if (pgmRtn) return;
