package com.hisun.BP;

public class BPB3900_AWA_3900 {
    public char FUNC = ' ';
    public short FUNC_NO = 0;
    public String PLBOX_NO = " ";
    public short PLBOX_NO_NO = 0;
    public String PLBOX_NM = " ";
    public short PLBOX_NM_NO = 0;
    public String TLR = " ";
    public short TLR_NO = 0;
    public String TLR_NAME = " ";
    public short TLR_NAME_NO = 0;
    public String LST_TLR = " ";
    public short LST_TLR_NO = 0;
    public char RET_FLG = ' ';
    public short RET_FLG_NO = 0;
    public char FLG = ' ';
    public short FLG_NO = 0;
    public char BOX_CHK = ' ';
    public short BOX_CHK_NO = 0;
    public char VLT_CHK = ' ';
    public short VLT_CHK_NO = 0;
    public char BV_BOX_C = ' ';
    public short BV_BOX_C_NO = 0;
    public char BV_VLT_C = ' ';
    public short BV_VLT_C_NO = 0;
    public char BL_BOX_C = ' ';
    public short BL_BOX_C_NO = 0;
    public char BL_VLT_C = ' ';
    public short BL_VLT_C_NO = 0;
    public char STS = ' ';
    public short STS_NO = 0;
    public int UPD_DT = 0;
    public short UPD_DT_NO = 0;
    public String UPD_TLR = " ";
    public short UPD_TLR_NO = 0;
    public String BNK = " ";
    public short BNK_NO = 0;
    public int BR = 0;
    public short BR_NO = 0;
}
