package com.hisun.BP;

public class BPB8080_AWA_8080 {
    public long JRNNO = 0;
    public short JRNNO_NO = 0;
    public String AC = " ";
    public short AC_NO = 0;
    public String TX_TOOL = " ";
    public short TX_TOOL_NO = 0;
    public String TX_CCY = " ";
    public short TX_CCY_NO = 0;
    public String TX_CD = " ";
    public short TX_CD_NO = 0;
    public String TX_TLR = " ";
    public short TX_TLR_NO = 0;
    public int STR_DT = 0;
    public short STR_DT_NO = 0;
    public int END_DT = 0;
    public short END_DT_NO = 0;
    public short JRN_SEQ = 0;
    public short JRN_SEQ_NO = 0;
    public String CI_NO = " ";
    public short CI_NO_NO = 0;
    public int TX_BR = 0;
    public short TX_BR_NO = 0;
    public char REC_FLG = ' ';
    public short REC_FLG_NO = 0;
    public char DC_FLG = ' ';
    public short DC_FLG_NO = 0;
    public int BR = 0;
    public short BR_NO = 0;
    public String PROD_CD = " ";
    public short PROD_CD_NO = 0;
    public char JUMP_FLG = ' ';
    public short JUMP_FLG_NO = 0;
    public char SORT_FLG = ' ';
    public short SORT_FLG_NO = 0;
    public int LIST_CNT = 0;
    public short LIST_CNT_NO = 0;
    public int PG_NO = 0;
    public short PG_NO_NO = 0;
    public int TOT_RC = 0;
    public short TOT_RC_NO = 0;
    public int TOD_RC = 0;
    public short TOD_RC_NO = 0;
}
