package com.hisun.BP;

public class BPCDEF04_CURR_GLMST1_INFO {
    public BPCDEF04_CURR_MST1_BASIC CURR_MST1_BASIC = new BPCDEF04_CURR_MST1_BASIC();
    public BPCDEF04_CURR_MST1_REL_ITMS[] CURR_MST1_REL_ITMS = new BPCDEF04_CURR_MST1_REL_ITMS[60];
    public BPCDEF04_CURR_GLMST1_INFO() {
        for (int i=0;i<60;i++) CURR_MST1_REL_ITMS[i] = new BPCDEF04_CURR_MST1_REL_ITMS();
    }
}
