package com.hisun.BP;

public class BPCFSCH1 {
    public String CTRT_NO = " ";
    public String CTRT_DESC = " ";
    public char FILLER3 = 0X02;
    public String CI_NO = " ";
    public String CI_ABBR_NAME = " ";
    public char FILLER6 = 0X02;
    public String FEE_TYPE = " ";
    public int BOOK_CENTRE = 0;
    public String PRD_TYPE = " ";
    public int START_DATE = 0;
    public int MATURITY_DATE = 0;
    public char UCT_FLG = ' ';
    public char SETTLE_FREQ = ' ';
    public short FREQ_COUNT = 0;
    public int FIRST_CHG_DATE = 0;
    public char HOLI_OVER = ' ';
    public String CAL_CODE1 = " ";
    public char HOLI_METHOD = ' ';
    public String CAL_CODE2 = " ";
    public char PAY_IND = ' ';
    public char CASHFLOW_IND = ' ';
    public String BANK_PORTF = " ";
    public char ACCRUAL_TYPE = ' ';
    public char PRICE_METHOD = ' ';
    public String TXN_CCY = " ";
    public double TXN_AMT = 0;
    public char REL_CTRT_SRC = ' ';
    public String REL_CTRT_NO = " ";
    public String REL_CTRT_TYPE = " ";
    public String REL_COL_NO = " ";
    public long REL_LMT_NO = 0;
    public double FIR_DSCT = 0;
    public short PROMPT_DAYS = 0;
    public short AMT_TYPE = 0;
    public String REL_PROD_TYPE = " ";
    public double MULTI = 0;
    public String INT_BAS = " ";
    public char AGGR_TYPE = ' ';
    public String REF_CCY = " ";
    public char REF_METHOD = ' ';
    public String FEE_CCY = " ";
    public BPCFSCH1_STD_INFO[] STD_INFO = new BPCFSCH1_STD_INFO[5];
    public char AUTO_CHG_FLAG = ' ';
    public String CHARGE_CCY = " ";
    public double CHARGE_AMT = 0;
    public char CHARGE_METHOD = ' ';
    public String CHARGE_AC = " ";
    public String NOSTRO_AC = " ";
    public String CHQ_NO = " ";
    public int GL_MASTER1 = 0;
    public int GL_MASTER2 = 0;
    public int GL_MASTER3 = 0;
    public int GL_MASTER4 = 0;
    public BPCFSCH1_R_CENT_DATA[] R_CENT_DATA = new BPCFSCH1_R_CENT_DATA[5];
    public char FEE_STATUS = ' ';
    public String REMARK = " ";
    public char FILLER66 = 0X02;
    public double FCHG_MIN_AMT = 0;
    public String CHG_CCY_REAL = " ";
    public String CP_NO = " ";
    public int SALE_DT = 0;
    public char CCY_TYPE = ' ';
    public String CREV_NO = " ";
    public BPCFSCH1() {
        for (int i=0;i<5;i++) STD_INFO[i] = new BPCFSCH1_STD_INFO();
        for (int i=0;i<5;i++) R_CENT_DATA[i] = new BPCFSCH1_R_CENT_DATA();
    }
}
