package com.hisun.BP;

public class BPCOUFEC {
    public String CTNO = " ";
    public String FEE_DESC = " ";
    public char FILLER3 = 0X02;
    public String CINO = " ";
    public String CI_ABBR_NM = " ";
    public char FILLER6 = 0X02;
    public String CT_TYP = " ";
    public String FEE_TYP = " ";
    public int BOOK_ACCT = 0;
    public String PRDT_TYP = " ";
    public int START_DT = 0;
    public int MATURITY_DT = 0;
    public char HOL_OVR = ' ';
    public String CAL_CD1 = " ";
    public char HOL_METH = ' ';
    public String CAL_CD2 = " ";
    public char PAY_IND = ' ';
    public char CSH_FLW_IND = ' ';
    public String BK_PFLO = " ";
    public char PAY_METH = ' ';
    public char ACU_TYP = ' ';
    public char FIE_PRC_METH = ' ';
    public String TXN_CCY = " ";
    public double TXN_AMT = 0;
    public String RLTD_CTNO = " ";
    public String RLTD_CT_TYP = " ";
    public short AMT_TYP = 0;
    public String RLTD_PRDT_TYP = " ";
    public double AMT_PCT = 0;
    public String INT_BASIC = " ";
    public char AGGR_TYP = ' ';
    public String REF_CCY = " ";
    public char REF_METH = ' ';
    public BPCOUFEC_REF_FEE_DATA[] REF_FEE_DATA = new BPCOUFEC_REF_FEE_DATA[5];
    public String CHG_CCY = " ";
    public double CHG_AMT = 0;
    public char CHG_METH = ' ';
    public String CHG_ACNO = " ";
    public String NOSTRO_CD = " ";
    public String CHQ_NO = " ";
    public int GL_MST_BR = 0;
    public int GL_MST_HO = 0;
    public int GL_MST_IAS39 = 0;
    public int GL_MST_UNUS = 0;
    public BPCOUFEC_TXN_OIC_DATA[] TXN_OIC_DATA = new BPCOUFEC_TXN_OIC_DATA[5];
    public char CT_STS = ' ';
    public String REMARK = " ";
    public char FILLER57 = 0X02;
    public double FEE_BAS_AMT = 0;
    public String CHG_CCY_REAL = " ";
    public double CHG_AMT_REAL = 0;
    public String TICKET = " ";
    public double RATE = 0;
    public char FILLER63 = 0X01;
    public int EXG_DATE = 0;
    public int EXG_TIME = 0;
    public double FCHG_MIN_AMT = 0;
    public long JNL_NO = 0;
    public int REAL_AC_DATE = 0;
    public String VOUCHER_NO = " ";
    public int CREATE_DATE = 0;
    public String CREATE_TELL = " ";
    public int UPDTBL_DATE = 0;
    public String LAST_TELL = " ";
    public String SUP_TEL1 = " ";
    public String SUP_TEL2 = " ";
    public String CP_NO = " ";
    public int SALE_DT = 0;
    public char CCY_TYPE = ' ';
    public char CHG_FLAG = ' ';
    public String CREV_NO = " ";
    public BPCOUFEC() {
        for (int i=0;i<5;i++) REF_FEE_DATA[i] = new BPCOUFEC_REF_FEE_DATA();
        for (int i=0;i<5;i++) TXN_OIC_DATA[i] = new BPCOUFEC_TXN_OIC_DATA();
    }
}
