package com.hisun.BP;

import com.hisun.PY.QPORG_RC;

public class BPCQPORG {
    QPORG_RC RC = new QPORG_RC();
    String BNK = " ";
    int BR = 0;
    int SUPR_BR = 0;
    char ATTR = ' ';
    char LVL = ' ';
    String TYP = " ";
    int EFF_DT = 0;
    int EXP_DT = 0;
    String CHN_NM = " ";
    String CHN_ADDR = " ";
    String ENG_NM = " ";
    String ENG_ADDR = " ";
    String ABBR = " ";
    String LINK_MAN = " ";
    String LINK_TEL = " ";
    String POST = " ";
    char TLR_MAX = ' ';
    char ATH_MAX = ' ';
    String FX_BUSI = " ";
    long CNAP_NO = 0;
    char ACCT_FLG = ' ';
    int OPN_DT = 0;
    char RUN_HDAY = ' ';
    char RUN_MODE = ' ';
    String CALD_CD = " ";
    int OPN_TM = 0;
    int CLS_TM = 0;
    int HOPN_TM = 0;
    int HCLS_TM = 0;
    char ORG_STS = ' ';
    int UPT_DT = 0;
    String UPT_TLR = " ";
    String FAX = " ";
    String TELEX = " ";
    char PRO_FLG = ' ';
    char COST_FLG = ' ';
    int GL_MST = 0;
    String DEF_PTR = " ";
    String PAY_PTR = " ";
    String CFM_PTR = " ";
    String SWF_ID = " ";
    String BIC_NO = " ";
    String IBAN_NO = " ";
    int CI_LEN = 0;
    String COUN_CD = " ";
    String CITY_CD = " ";
    char UNSCH_HOL = ' ';
    int UNSCH_HOL_TM = 0;
    char OPN_CHECK_FLG = ' ';
    char VOU_CHECK_FLG = ' ';
    char INT_TAX_FLG = ' ';
    int ERP_BRAN = 0;
    int BRANCH_BR = 0;
    String VIL_TYP = " ";
    String TRA_TYP = " ";
    char INT_BR_FLG = ' ';
    String AREA_CD = " ";
    char STS = ' ';
    int BBR = 0;
}
