package com.hisun.BP;

public class BPCSTLRM {
    public char FUNC = ' ';
    public String TLR = " ";
    public String STAFNO = " ";
    public int TLR_BR = 0;
    public short TLR_TKS = 0;
    public int EFF_DATE = 0;
    public int EXP_DATE = 0;
    public String TLR_CNAME = " ";
    public String TLR_ENAME = " ";
    public char TLR_TYPE = ' ';
    public char TLR_LVL = ' ';
    public char TX_LVL = ' ';
    public char AUTH_LVL = ' ';
    public char AUTH_REG = ' ';
    public char CBR_SIGN = ' ';
    public char TRM_TYPE = ' ';
    public String TLR_STSW = " ";
    public char KPSW_FLG = ' ';
    public char TX_MODE = ' ';
    public String PRT_IP = " ";
    public String TELE = " ";
    public String PST_ADDRESS = " ";
    public char SIGN_TRM_FLG = ' ';
    public BPCSTLRM_TRM_INFO TRM_INFO = new BPCSTLRM_TRM_INFO();
    public char PSW_TYP = ' ';
    public String IDEN_DEV_ID = " ";
    public int TM_OUT_LMT = 0;
    public char ACC_SEN_CUS = ' ';
    public char ACC_SEN_GL = ' ';
    public char SUPER_FLG = ' ';
    public String DFT_PRTR_NM = " ";
    public String PAY_PRTR_NM = " ";
    public String CNF_PRTR_NM = " ";
    public String ID_TYP = " ";
    public String ID_NO = " ";
    public String CI_NO = " ";
    public char REG_TYP = ' ';
    public String CRD_NO = " ";
    public int NEW_BR = 0;
    public char CHK_FLG = ' ';
}
