package com.hisun.BP;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;

import java.io.IOException;
import java.sql.SQLException;

public class BPOT9128 {
    String JIBS_tmp_str[] = new String[10];
    BPOT9128_WS_TEMP_VARIABLE WS_TEMP_VARIABLE = new BPOT9128_WS_TEMP_VARIABLE();
    char WS_SEQ_FLG = ' ';
    char WS_FUNC_FLG = ' ';
    BPCMSG_ERROR_MSG BPCMSG_ERROR_MSG = new BPCMSG_ERROR_MSG();
    SCCMSG SCCMSG = new SCCMSG();
    SCCCALL SCCCALL = new SCCCALL();
    SCCSUBS SCCSUBS = new SCCSUBS();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCFMT SCCFMT = new SCCFMT();
    BPRFCTR BPRFCTR = new BPRFCTR();
    BPCRFCTR BPCRFCTR = new BPCRFCTR();
    BPCUMENT BPCUMENT = new BPCUMENT();
    BPCSGSEQ BPCSGSEQ = new BPCSGSEQ();
    BPRPACCR BPRPACCR = new BPRPACCR();
    BPCRACCR BPCRACCR = new BPCRACCR();
    BPCSFECT BPCSFECT = new BPCSFECT();
    BPCFFTXI BPCFFTXI = new BPCFFTXI();
    BPCFFCON BPCFFCON = new BPCFFCON();
    BPCRFAMO BPCRFAMO = new BPCRFAMO();
    BPRFAMO BPRFAMO = new BPRFAMO();
    SCCGWA SCCGWA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    BPCPORUP_DATA_INFO BPCPORUP;
    BPB9120_AWA_9120 BPB9120_AWA_9120;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "BPOT9128 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "BPB9120_AWA_9120>");
        BPB9120_AWA_9120 = (BPB9120_AWA_9120) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        BPCPORUP = (BPCPORUP_DATA_INFO) SCCGWA.COMM_AREA.TR_BR_PTR;
        IBS.init(SCCGWA, WS_TEMP_VARIABLE);
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, "IIIIIII");
        CEP.TRC(SCCGWA, BPB9120_AWA_9120.CTRT_NO);
        CEP.TRC(SCCGWA, BPB9120_AWA_9120.REL_CTNO);
        CEP.TRC(SCCGWA, BPB9120_AWA_9120.CI_NO);
        CEP.TRC(SCCGWA, BPB9120_AWA_9120.CI_S_NM);
        CEP.TRC(SCCGWA, BPB9120_AWA_9120.FEE_TYP);
        CEP.TRC(SCCGWA, BPB9120_AWA_9120.PRDT_TYP);
        CEP.TRC(SCCGWA, BPB9120_AWA_9120.PAY_IND);
        CEP.TRC(SCCGWA, BPB9120_AWA_9120.SETT_DT);
        CEP.TRC(SCCGWA, BPB9120_AWA_9120.CHG_CCY);
        CEP.TRC(SCCGWA, BPB9120_AWA_9120.CHG_AMT);
        B100_CHECK_INPUT();
        B200_CHARGE_PROC();
    }
    public void B100_CHECK_INPUT() throws IOException,SQLException,Exception {
    }
    public void B200_CHARGE_PROC() throws IOException,SQLException,Exception {
        B200_10_GET_FEE_CNTR();
        if (SCCGWA.COMM_AREA.TR_BANK.equalsIgnoreCase("043")) {
            B200_20_SET_FFTXI_CN();
            B200_30_SET_FFCON_CN();
        } else {
            B200_20_SET_FFTXI();
            B200_30_SET_FFCON();
        }
        B200_40_UPD_FEE_CNTR();
    }
    public void B300_UPDATE_BPTFAMO() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPRFAMO);
        IBS.init(SCCGWA, BPCRFAMO);
        BPCRFAMO.INFO.FUNC = 'C';
        BPRFAMO.KEY.CTRT_NO = BPRFCTR.KEY.CTRT_NO;
        BPRFAMO.AMO_DATE = 0;
        BPRFAMO.FEE_AMO_AMT = BPRFCTR.CHARGE_AMT;
        BPRFAMO.AMO_AMT_TODAY = 0;
        BPRFAMO.AMO_AMT_MONTH = 0;
        BPRFAMO.AMO_AMT_TOTAL = 0;
        BPRFAMO.UPDTBL_DATE = SCCGWA.COMM_AREA.AC_DATE;
        BPRFAMO.LAST_TELL = "ONLLINE";
        S000_CALL_BPZRFAMO();
    }
    public void B200_10_GET_FEE_CNTR() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCSFECT);
        BPCSFECT.CTNO = BPB9120_AWA_9120.CTRT_NO;
        BPCSFECT.START_DT = BPB9120_AWA_9120.STR_DT;
        BPCSFECT.FUNC_CODE = 'I';
        CEP.TRC(SCCGWA, BPCSFECT.CTNO);
        CEP.TRC(SCCGWA, BPCSFECT.START_DT);
        CEP.TRC(SCCGWA, BPCSFECT.FUNC_CODE);
        S000_CALL_BPZSFECT();
        if (BPCSFECT.PAY_METH == 'P') {
            WS_TEMP_VARIABLE.WS_SET_DATE = BPCSFECT.START_DT;
        } else {
            WS_TEMP_VARIABLE.WS_SET_DATE = BPCSFECT.MATURITY_DT;
        }
        CEP.TRC(SCCGWA, "1111111111111111");
        CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[1-1].TXN_OIC);
        CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[1-1].OIC_ACCT);
        CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[1-1].PRFT_PCT);
        CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[2-1].TXN_OIC);
        CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[2-1].OIC_ACCT);
        CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[2-1].PRFT_PCT);
        CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[3-1].TXN_OIC);
        CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[3-1].OIC_ACCT);
        CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[3-1].PRFT_PCT);
        CEP.TRC(SCCGWA, BPCSFECT.START_DT);
        CEP.TRC(SCCGWA, BPCSFECT.MATURITY_DT);
        CEP.TRC(SCCGWA, WS_TEMP_VARIABLE.WS_SET_DATE);
    }
    public void B200_20_SET_FFTXI() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCFFTXI);
        BPCFFTXI.TX_DATA.AUH_FLG = '0';
        if (BPB9120_AWA_9120.PAY_IND == 'R') {
            BPCFFTXI.TX_DATA.CHG_AC_INFO.VALUE_DATE = WS_TEMP_VARIABLE.WS_SET_DATE;
            BPCFFTXI.TX_DATA.CHG_AC_INFO.AC_TYP = BPCSFECT.CHG_METH;
            if (BPCSFECT.CHG_METH == '0') {
                CEP.TRC(SCCGWA, "CHARGE METHOD:DD ACCOUNT");
                BPCFFTXI.TX_DATA.CHG_AC_INFO.CHG_AC = BPCSFECT.CHG_ACNO;
            } else if (BPCSFECT.CHG_METH == '1') {
                CEP.TRC(SCCGWA, "CHARGE METHOD:SUSPEND ACCOUNT");
                BPCFFTXI.TX_DATA.CHG_AC_INFO.CHG_AC = BPCSFECT.CHG_ACNO;
            } else if (BPCSFECT.CHG_METH == '2') {
                CEP.TRC(SCCGWA, "CHARGE METHOD:CHEQUE NO");
                BPCFFTXI.TX_DATA.CHG_AC_INFO.CHG_AC = BPCSFECT.CHG_ACNO;
                BPCFFTXI.TX_DATA.CHG_AC_INFO.CHQ_NO = BPCSFECT.CHQ_NO;
            } else if (BPCSFECT.CHG_METH == '3') {
                CEP.TRC(SCCGWA, "CHARGE METHOD:INNER AC NO");
                BPCFFTXI.TX_DATA.CHG_AC_INFO.CHG_AC = BPCSFECT.CHG_ACNO;
            } else {
                IBS.CPY2CLS(SCCGWA, BPCMSG_ERROR_MSG.BP_FEE_CHG_MTH_ERR, WS_TEMP_VARIABLE.WS_MSGID);
                S000_ERR_MSG_PROC();
            }
            BPCFFTXI.TX_DATA.CHG_AC_INFO.CHG_CCY = BPCSFECT.CHG_CCY;
            CEP.TRC(SCCGWA, "2222222222222222");
            CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[1-1].TXN_OIC);
            CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[1-1].OIC_ACCT);
            CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[1-1].PRFT_PCT);
            CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[2-1].TXN_OIC);
            CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[2-1].OIC_ACCT);
            CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[2-1].PRFT_PCT);
            CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[3-1].TXN_OIC);
            CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[3-1].OIC_ACCT);
            CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[3-1].PRFT_PCT);
        } else {
            BPCFFTXI.TX_DATA.DIS_AC_INFO.DIS_VAL_DATE = WS_TEMP_VARIABLE.WS_SET_DATE;
            BPCFFTXI.TX_DATA.DIS_AC_INFO.DIS_AC_TYP = BPCSFECT.CHG_METH;
            if (BPCSFECT.CHG_METH == '0') {
                CEP.TRC(SCCGWA, "CHARGE METHOD:DD ACCOUNT");
                BPCFFTXI.TX_DATA.DIS_AC_INFO.DIS_AC = BPCSFECT.CHG_ACNO;
            } else if (BPCSFECT.CHG_METH == '1') {
                CEP.TRC(SCCGWA, "CHARGE METHOD:SUSPEND ACCOUNT");
                BPCFFTXI.TX_DATA.DIS_AC_INFO.DIS_AC = BPCSFECT.CHG_ACNO;
            } else if (BPCSFECT.CHG_METH == '2') {
                CEP.TRC(SCCGWA, "CHARGE METHOD:CHEQUE NO");
                BPCFFTXI.TX_DATA.DIS_AC_INFO.DIS_AC = BPCSFECT.CHG_ACNO;
                BPCFFTXI.TX_DATA.CHG_AC_INFO.CHQ_NO = BPCSFECT.CHQ_NO;
            } else if (BPCSFECT.CHG_METH == '3') {
                CEP.TRC(SCCGWA, "CHARGE METHOD:INNER AC NO");
                BPCFFTXI.TX_DATA.CHG_AC_INFO.CHG_AC = BPCSFECT.CHG_ACNO;
            } else {
                IBS.CPY2CLS(SCCGWA, BPCMSG_ERROR_MSG.BP_FEE_CHG_MTH_ERR, WS_TEMP_VARIABLE.WS_MSGID);
                S000_ERR_MSG_PROC();
            }
            BPCFFTXI.TX_DATA.DIS_AC_INFO.DIS_CCY = BPCSFECT.CHG_CCY;
            CEP.TRC(SCCGWA, "3333333333333333");
            CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[1-1].TXN_OIC);
            CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[1-1].OIC_ACCT);
            CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[1-1].PRFT_PCT);
            CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[2-1].TXN_OIC);
            CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[2-1].OIC_ACCT);
            CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[2-1].PRFT_PCT);
            CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[3-1].TXN_OIC);
            CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[3-1].OIC_ACCT);
            CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[3-1].PRFT_PCT);
        }
        CEP.TRC(SCCGWA, BPCSFECT.CINO);
        if (BPCSFECT.CINO.trim().length() > 0) {
            BPCFFTXI.TX_DATA.CI_NO = BPCSFECT.CINO;
        }
        BPCFFTXI.TX_DATA.FEE_CTRT_NO = BPB9120_AWA_9120.CTRT_NO;
        BPCFFTXI.TX_DATA.REL_CTRT_NO = BPB9120_AWA_9120.REL_CTNO;
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.AC_DATE);
        CEP.TRC(SCCGWA, BPCSFECT.MATURITY_DT);
        if (BPCSFECT.MATURITY_DT == SCCGWA.COMM_AREA.AC_DATE) {
            BPCFFTXI.TX_DATA.LAST_FLAG = 'Y';
        } else {
            BPCFFTXI.TX_DATA.LAST_FLAG = 'N';
        }
        S000_CALL_BPZFFTXI();
        CEP.TRC(SCCGWA, "4444444444444444");
        CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[1-1].TXN_OIC);
        CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[1-1].OIC_ACCT);
        CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[1-1].PRFT_PCT);
        CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[2-1].TXN_OIC);
        CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[2-1].OIC_ACCT);
        CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[2-1].PRFT_PCT);
        CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[3-1].TXN_OIC);
        CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[3-1].OIC_ACCT);
        CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[3-1].PRFT_PCT);
    }
    public void B200_30_SET_FFCON() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCFFCON);
        BPCFFCON.FEE_INFO.FEE_CNT += 1;
        WS_TEMP_VARIABLE.WS_CNT = BPCFFCON.FEE_INFO.FEE_CNT;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].CHG_FLG = '0';
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].FEE_CODE = BPB9120_AWA_9120.FEE_TYP;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].FEE_CCY = BPB9120_AWA_9120.CHG_CCY;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].FEE_BAS = BPB9120_AWA_9120.BAS_AMT;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].FEE_AMT = BPB9120_AWA_9120.CHG_AMT;
        CEP.TRC(SCCGWA, BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].FEE_AMT);
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].CHG_AC_TY = BPCSFECT.CHG_METH;
        CEP.TRC(SCCGWA, BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].CHG_AC_TY);
        if (BPCSFECT.CHG_METH == '0') {
            CEP.TRC(SCCGWA, "CHARGE METHOD:DD ACCOUNT");
            BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].CHG_AC = BPCSFECT.CHG_ACNO;
        } else if (BPCSFECT.CHG_METH == '1') {
            CEP.TRC(SCCGWA, "CHARGE METHOD:SUSPEND ACCOUNT");
            BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].CHG_AC = BPCSFECT.CHG_ACNO;
        } else if (BPCSFECT.CHG_METH == '2') {
            CEP.TRC(SCCGWA, "CHARGE METHOD:CHEQUE NO");
            BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].CHG_AC = BPCSFECT.CHG_ACNO;
        } else if (BPCSFECT.CHG_METH == '3') {
            CEP.TRC(SCCGWA, "CHARGE METHOD:INNER AC NO");
            BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].CHG_AC = BPCSFECT.CHG_ACNO;
        } else {
            IBS.CPY2CLS(SCCGWA, BPCMSG_ERROR_MSG.BP_FEE_CHG_MTH_ERR, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].CHG_CCY = BPB9120_AWA_9120.CHG_CCYR;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].CHG_AMT = BPB9120_AWA_9120.CHG_AMTR;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].CHG_BAS = BPB9120_AWA_9120.CHG_AMTR;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].ADJ_AMT = BPB9120_AWA_9120.CHG_AMTR;
        BPCFFCON.FEE_INFO.TICKET_NO = BPB9120_AWA_9120.TICKET;
        BPCFFCON.FEE_INFO.EX_RATE = BPB9120_AWA_9120.RATE;
        BPCFFCON.FEE_INFO.REMARK = BPB9120_AWA_9120.FEE_RMK;
        CEP.TRC(SCCGWA, BPCFFCON.FEE_INFO.FEE_CNT);
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].TO_ACCT_CEN = BPCSFECT.BOOK_ACCT;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].GL_MASTER1 = BPCSFECT.GL_MST_BR;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].GL_MASTER2 = BPCSFECT.GL_MST_HO;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].GL_MASTER3 = BPCSFECT.GL_MST_IAS39;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].GL_MASTER4 = BPCSFECT.GL_MST_UNUS;
        S000_CALL_BPZFFCON();
        CEP.TRC(SCCGWA, BPCFFCON.FEE_INFO.FEE_CNT);
        CEP.TRC(SCCGWA, "5555555555555555");
        CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[1-1].TXN_OIC);
        CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[1-1].OIC_ACCT);
        CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[1-1].PRFT_PCT);
        CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[2-1].TXN_OIC);
        CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[2-1].OIC_ACCT);
        CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[2-1].PRFT_PCT);
        CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[3-1].TXN_OIC);
        CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[3-1].OIC_ACCT);
        CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[3-1].PRFT_PCT);
    }
    public void B200_20_SET_FFTXI_CN() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCFFTXI);
        BPCFFTXI.TX_DATA.AUH_FLG = '0';
        if (BPCSFECT.PAY_IND == 'R') {
            if (BPCSFECT.PAY_METH == 'P') {
                BPCFFTXI.TX_DATA.CHG_AC_INFO.VALUE_DATE = BPCSFECT.START_DT;
            } else {
                BPCFFTXI.TX_DATA.CHG_AC_INFO.VALUE_DATE = BPCSFECT.MATURITY_DT;
            }
            BPCFFTXI.TX_DATA.CHG_AC_INFO.AC_TYP = BPCSFECT.CHG_METH;
        } else {
            if (BPCSFECT.PAY_METH == 'P') {
                BPCFFTXI.TX_DATA.DIS_AC_INFO.DIS_VAL_DATE = BPCSFECT.START_DT;
            } else {
                BPCFFTXI.TX_DATA.DIS_AC_INFO.DIS_VAL_DATE = BPCSFECT.MATURITY_DT;
            }
            BPCFFTXI.TX_DATA.DIS_AC_INFO.DIS_AC_TYP = BPCSFECT.CHG_METH;
        }
        CEP.TRC(SCCGWA, BPCSFECT.CHG_METH);
        if (BPCSFECT.CHG_METH == '0') {
            CEP.TRC(SCCGWA, "CHARGE METHOD:DD ACCOUNT");
            BPCFFTXI.TX_DATA.CHG_AC_INFO.CHG_AC = BPCSFECT.CHG_ACNO;
            BPCFFTXI.TX_DATA.DIS_AC_INFO.DIS_AC = BPCSFECT.CHG_ACNO;
            BPCFFTXI.TX_DATA.CCY_TYPE = BPCSFECT.CCY_TYPE;
        } else if (BPCSFECT.CHG_METH == '2'
            || BPCSFECT.CHG_METH == '4'
            || BPCSFECT.CHG_METH == '5'
            || BPCSFECT.CHG_METH == '6'
            || BPCSFECT.CHG_METH == '7'
            || BPCSFECT.CHG_METH == '8'
            || BPCSFECT.CHG_METH == '9') {
            BPCFFTXI.TX_DATA.CHG_AC_INFO.CHG_AC = BPCSFECT.CHG_ACNO;
            BPCFFTXI.TX_DATA.DIS_AC_INFO.DIS_AC = BPCSFECT.CHG_ACNO;
            BPCFFTXI.TX_DATA.CHG_AC_INFO.CHQ_NO = BPCSFECT.CHQ_NO;
            BPCFFTXI.TX_DATA.CARD_PSBK_NO = BPCSFECT.CP_NO;
            BPCFFTXI.TX_DATA.SALE_DATE = BPCSFECT.SALE_DT;
            BPCFFTXI.TX_DATA.CCY_TYPE = BPCSFECT.CCY_TYPE;
        } else if (BPCSFECT.CHG_METH == '3') {
            CEP.TRC(SCCGWA, "CHARGE METHOD:IB NO");
            BPCFFTXI.TX_DATA.CHG_AC_INFO.CHG_AC = BPCSFECT.CHG_ACNO;
            BPCFFTXI.TX_DATA.DIS_AC_INFO.DIS_AC = BPCSFECT.CHG_ACNO;
        } else {
            IBS.CPY2CLS(SCCGWA, BPCMSG_ERROR_MSG.BP_FEE_CHG_MTH_ERR, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        BPCFFTXI.TX_DATA.FEE_CTRT_NO = BPCSFECT.CTNO;
        BPCFFTXI.TX_DATA.BSNS_NO = BPB9120_AWA_9120.REL_CTNO;
        CEP.TRC(SCCGWA, BPCFFTXI.TX_DATA.FEE_CTRT_NO);
        if (BPCSFECT.CINO.trim().length() > 0) {
            BPCFFTXI.TX_DATA.CI_NO = BPCSFECT.CINO;
        }
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.AC_DATE);
        CEP.TRC(SCCGWA, BPCSFECT.MATURITY_DT);
        if (BPCSFECT.MATURITY_DT == SCCGWA.COMM_AREA.AC_DATE) {
            BPCFFTXI.TX_DATA.LAST_FLAG = 'Y';
        } else {
            BPCFFTXI.TX_DATA.LAST_FLAG = 'N';
        }
        S000_CALL_BPZFFTXI();
    }
    public void B200_30_SET_FFCON_CN() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCFFCON);
        BPCFFCON.FEE_INFO.FEE_CNT += 1;
        WS_TEMP_VARIABLE.WS_CNT = BPCFFCON.FEE_INFO.FEE_CNT;
        CEP.TRC(SCCGWA, WS_TEMP_VARIABLE.WS_CNT);
        CEP.TRC(SCCGWA, BPCSFECT.PAY_IND);
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].CHG_FLG = BPCSFECT.PAY_IND;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].FEE_CODE = BPCSFECT.FEE_TYP;
        BPCFFCON.FEE_INFO.PROD_CODE1 = BPCSFECT.PRDT_TYP;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].FEE_CCY = BPCSFECT.REF_CCY;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].FEE_BAS = BPCSFECT.FEE_BAS_AMT;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].FEE_AMT = BPCSFECT.CHG_AMT;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].CHG_AC_TY = BPCSFECT.CHG_METH;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].CHG_AC = BPCSFECT.CHG_ACNO;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].CHG_CCY = BPCSFECT.CHG_CCY_REAL;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].CHG_AMT = BPCSFECT.CHG_AMT_REAL;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].CHG_BAS = BPCSFECT.CHG_AMT_REAL;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].ADJ_AMT = BPCSFECT.CHG_AMT_REAL;
        CEP.TRC(SCCGWA, BPCSFECT.CHG_CCY_REAL);
        CEP.TRC(SCCGWA, BPCSFECT.CHG_AMT_REAL);
        BPCFFCON.FEE_INFO.TICKET_NO = BPCSFECT.TICKET;
        BPCFFCON.FEE_INFO.EX_RATE = BPCSFECT.RATE;
        BPCFFCON.FEE_INFO.REMARK = BPCSFECT.REMARK;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].TO_ACCT_CEN = BPCSFECT.BOOK_ACCT;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].GL_MASTER1 = BPCSFECT.GL_MST_BR;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].GL_MASTER2 = BPCSFECT.GL_MST_HO;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].GL_MASTER3 = BPCSFECT.GL_MST_IAS39;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].GL_MASTER4 = BPCSFECT.GL_MST_UNUS;
        S000_CALL_BPZFFCON();
        CEP.TRC(SCCGWA, WS_TEMP_VARIABLE.WS_CNT);
        CEP.TRC(SCCGWA, BPCFFCON.FEE_INFO.FEE_INFO1[WS_TEMP_VARIABLE.WS_CNT-1].FEE_CODE);
    }
    public void B200_40_UPD_FEE_CNTR() throws IOException,SQLException,Exception {
        if (BPCSFECT.PAY_METH == 'P') {
            CEP.TRC(SCCGWA, "FEE CONTRACT STATUS:SETTLED");
            BPCSFECT.CT_STS = '1';
        } else {
            CEP.TRC(SCCGWA, "FEE CONTRACT STATUS:COMPLETE");
            BPCSFECT.CT_STS = '2';
        }
        IBS.init(SCCGWA, BPRFCTR);
        IBS.init(SCCGWA, BPCRFCTR);
        BPRFCTR.KEY.CTRT_NO = BPCSFECT.CTNO;
        BPCRFCTR.INFO.FUNC = 'R';
        S000_CALL_BPZRFCTR();
        BPRFCTR.FEE_STATUS = BPCSFECT.CT_STS;
        BPRFCTR.UPDTBL_DATE = SCCGWA.COMM_AREA.AC_DATE;
        BPRFCTR.JNL_NO = SCCGWA.COMM_AREA.JRN_NO;
        BPRFCTR.REAL_AC_DATE = SCCGWA.COMM_AREA.AC_DATE;
        BPRFCTR.VOUCHER_NO = SCCGWA.COMM_AREA.VCH_NO;
        BPCRFCTR.INFO.FUNC = 'U';
        S000_CALL_BPZRFCTR();
    }
    public void B200_60_UPD_FEE_ACCR() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPRPACCR);
        IBS.init(SCCGWA, BPCRACCR);
        BPRPACCR.KEY.CTRT_NO = BPCSFECT.CTNO;
        BPCRACCR.INFO.FUNC = 'R';
        S000_CALL_BPZRACCR();
        if (BPCRACCR.RETURN_INFO == 'F') {
            BPRPACCR.LAST_SETTLE_DATE = BPRPACCR.SETTLE_DATE;
            BPRPACCR.SETTLE_DATE = SCCGWA.COMM_AREA.AC_DATE;
            BPRPACCR.SETTLE_AMT_TOTAL = BPB9120_AWA_9120.CHG_AMT;
            BPRPACCR.ACCRUAL_AMT_TOTAL = 0;
            BPRPACCR.UPDTBL_DATE = SCCGWA.COMM_AREA.AC_DATE;
            BPRPACCR.LAST_TELL = SCCGWA.COMM_AREA.TL_ID;
            BPRPACCR.SUP_TEL1 = SCCGWA.COMM_AREA.SUP1_ID;
            BPRPACCR.SUP_TEL2 = SCCGWA.COMM_AREA.SUP2_ID;
            BPCRACCR.INFO.FUNC = 'U';
            S000_CALL_BPZRACCR();
        } else {
            IBS.init(SCCGWA, BPRPACCR);
            IBS.init(SCCGWA, BPCRACCR);
            BPRPACCR.KEY.CTRT_NO = BPCSFECT.CTNO;
            BPRPACCR.SETTLE_DATE = SCCGWA.COMM_AREA.AC_DATE;
            BPRPACCR.SETTLE_AMT_TOTAL = BPB9120_AWA_9120.CHG_AMT;
            BPRPACCR.ACCRUAL_AMT_TOTAL = 0;
            BPRPACCR.UPDTBL_DATE = SCCGWA.COMM_AREA.AC_DATE;
            BPRPACCR.LAST_TELL = SCCGWA.COMM_AREA.TL_ID;
            BPRPACCR.SUP_TEL1 = SCCGWA.COMM_AREA.SUP1_ID;
            BPRPACCR.SUP_TEL2 = SCCGWA.COMM_AREA.SUP2_ID;
            BPCRACCR.INFO.FUNC = 'C';
            S000_CALL_BPZRACCR();
        }
    }
    public void B200_50_UPD_ENVENT() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCSGSEQ);
        BPCSGSEQ.TYPE = "SEQ";
        BPCSGSEQ.CODE = "DYBATNO";
        BPCSGSEQ.AC_DATE = SCCGWA.COMM_AREA.AC_DATE;
        BPCSGSEQ.RUN_MODE = 'O';
        S000_CALL_BPZSGSEQ();
    }
    public void B200_50_01_UPD_ST_EVT() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCUMENT);
        BPCUMENT.DIARY_DATA.CONTRACT_NO = BPCSFECT.CTNO;
        BPCUMENT.DIARY_DATA.DIARY_TYPE = "ST";
        BPCUMENT.DIARY_DATA.DIARY_DATE = BPCSFECT.START_DT;
        CEP.TRC(SCCGWA, "ST EVENT - UPD");
        CEP.TRC(SCCGWA, BPCUMENT.DIARY_DATA.CONTRACT_NO);
        CEP.TRC(SCCGWA, BPCUMENT.DIARY_DATA.DIARY_TYPE);
        CEP.TRC(SCCGWA, BPCUMENT.DIARY_DATA.DIARY_DATE);
        BPCUMENT.PROC_DATA.FUNC_CODE = "R ";
        S000_CALL_BPZUMENT();
        BPCUMENT.DIARY_DATA.DIARY_STATUS = 'A';
        BPCUMENT.DIARY_DATA.TRN_DATE = SCCGWA.COMM_AREA.AC_DATE;
        BPCUMENT.DIARY_DATA.TRN_JRN_NO = SCCGWA.COMM_AREA.JRN_NO;
        BPCUMENT.DIARY_DATA.DIARY_BATNO = BPCSGSEQ.SEQ;
        BPCUMENT.PROC_DATA.FUNC_CODE = "M1";
        S000_CALL_BPZUMENT();
    }
    public void B200_50_02_UPD_MA_EVT() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCUMENT);
        BPCUMENT.DIARY_DATA.CONTRACT_NO = BPCSFECT.CTNO;
        BPCUMENT.DIARY_DATA.DIARY_TYPE = "MA";
        BPCUMENT.DIARY_DATA.DIARY_DATE = BPCSFECT.MATURITY_DT;
        CEP.TRC(SCCGWA, "MA EVENT - UPD");
        CEP.TRC(SCCGWA, BPCUMENT.DIARY_DATA.CONTRACT_NO);
        CEP.TRC(SCCGWA, BPCUMENT.DIARY_DATA.DIARY_TYPE);
        CEP.TRC(SCCGWA, BPCUMENT.DIARY_DATA.DIARY_DATE);
        BPCUMENT.PROC_DATA.FUNC_CODE = "R ";
        S000_CALL_BPZUMENT();
        BPCUMENT.DIARY_DATA.DIARY_STATUS = 'A';
        BPCUMENT.DIARY_DATA.TRN_DATE = SCCGWA.COMM_AREA.AC_DATE;
        BPCUMENT.DIARY_DATA.TRN_JRN_NO = SCCGWA.COMM_AREA.JRN_NO;
        BPCUMENT.DIARY_DATA.DIARY_BATNO = BPCSGSEQ.SEQ;
        BPCUMENT.PROC_DATA.FUNC_CODE = "M1";
        S000_CALL_BPZUMENT();
    }
    public void S000_CALL_BPZRACCR() throws IOException,SQLException,Exception {
        BPCRACCR.INFO.POINTER = BPRPACCR;
        BPCRACCR.INFO.REC_LEN = 192;
        IBS.CALLCPN(SCCGWA, "BP-R-MGM-ACCR", BPCRACCR);
        if (BPCRACCR.RC.RC_CODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, BPCRACCR.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_BPZSFECT() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-S-FECT-MAINT", BPCSFECT);
        CEP.TRC(SCCGWA, BPCSFECT.RC);
        if (BPCSFECT.RC.RC_CODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, BPCSFECT.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_BPZFFTXI() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-F-F-TX-INFO", BPCFFTXI);
        CEP.TRC(SCCGWA, BPCFFTXI.RC);
        if (BPCFFTXI.RC.RC_CODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, BPCFFTXI.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_BPZFFCON() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-F-F-CON-CHG-INFO", BPCFFCON);
        CEP.TRC(SCCGWA, BPCFFCON.RC);
        if (BPCFFCON.RC.RC_CODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, BPCFFCON.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_BPZRFCTR() throws IOException,SQLException,Exception {
        BPCRFCTR.INFO.POINTER = BPRFCTR;
        BPCRFCTR.INFO.REC_LEN = 889;
        IBS.CALLCPN(SCCGWA, "BP-R-MGM-FEECTR", BPCRFCTR);
        CEP.TRC(SCCGWA, BPCRFCTR.RC);
        if (BPCRFCTR.RC.RC_CODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, BPCRFCTR.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_BPZUMENT() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-U-MENT-MAINT", BPCUMENT);
        CEP.TRC(SCCGWA, BPCUMENT.PROC_DATA.RC);
        if (BPCUMENT.PROC_DATA.RC.RC_RTNCODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, BPCUMENT.PROC_DATA.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_BPZSGSEQ() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-S-GET-SEQ", BPCSGSEQ);
        CEP.TRC(SCCGWA, BPCSGSEQ.RC);
        if (BPCSGSEQ.RC.RC_CODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, BPCSGSEQ.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_BPZRFAMO() throws IOException,SQLException,Exception {
        BPCRFAMO.INFO.POINTER = BPRFAMO;
        BPCRFAMO.INFO.REC_LEN = 155;
        IBS.CALLCPN(SCCGWA, "BP-R-MGM-FAMO", BPCRFAMO);
        CEP.TRC(SCCGWA, BPCRFAMO.RC);
        if (BPCRFAMO.RC.RC_CODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, BPCRFAMO.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, WS_TEMP_VARIABLE.WS_MSGID);
        CEP.ERR(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_FLD_NO);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
