package com.hisun.BP;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;

import java.io.IOException;
import java.sql.SQLException;

public class BPOT4081 {
    String K_MMO = "BP";
    String K_OUTPUT_FMT = "BP215";
    String WS_ERR_MSG = " ";
    short WS_FLD_NO = 0;
    short WS_IDX = 0;
    BPCMSG_ERROR_MSG BPCMSG_ERROR_MSG = new BPCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCFMT SCCFMT = new SCCFMT();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    BPCSENTY BPCSENTY = new BPCSENTY();
    SCCGWA SCCGWA;
    BPB4051_AWA_4051 BPB4051_AWA_4051;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "BPOT4081 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "BPB4051_AWA_4051>");
        BPB4051_AWA_4051 = (BPB4051_AWA_4051) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        IBS.init(SCCGWA, BPCSENTY);
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, BPB4051_AWA_4051.FUNC);
        CEP.TRC(SCCGWA, BPB4051_AWA_4051.CNTR_TYP);
        CEP.TRC(SCCGWA, BPB4051_AWA_4051.MODNO);
        IBS.init(SCCGWA, BPCSENTY);
        BPCSENTY.INPUT_DATA.FUNC = BPB4051_AWA_4051.FUNC;
        CEP.TRC(SCCGWA, BPCSENTY.INPUT_DATA.FUNC);
        BPCSENTY.INPUT_DATA.HIDE_INFO.LST_UPD_DATE = BPB4051_AWA_4051.UPD_DATE;
        BPCSENTY.INPUT_DATA.HIDE_INFO.LST_UPD_TM = BPB4051_AWA_4051.UPD_TIME;
        BPCSENTY.INPUT_DATA.CNTR_TYPE = BPB4051_AWA_4051.CNTR_TYP;
        CEP.TRC(SCCGWA, BPB4051_AWA_4051.CNTR_TYP);
        if (BPB4051_AWA_4051.PROD_TYP.equalsIgnoreCase("*")) {
            BPCSENTY.INPUT_DATA.PROD_TYPE = " ";
        } else {
            BPCSENTY.INPUT_DATA.PROD_TYPE = BPB4051_AWA_4051.PROD_TYP;
        }
        if (BPB4051_AWA_4051.BR2 == 999999) {
            BPCSENTY.INPUT_DATA.BR_AC = 0;
        } else {
            BPCSENTY.INPUT_DATA.BR_AC = BPB4051_AWA_4051.BR2;
        }
        BPCSENTY.INPUT_DATA.MODNO = BPB4051_AWA_4051.MODNO;
        if ((BPCSENTY.INPUT_DATA.MODNO.trim().length() == 0 
            || BPCSENTY.INPUT_DATA.MODNO.charAt(0) == 0X00) 
            && BPCSENTY.INPUT_DATA.FUNC != 'A') {
            WS_ERR_MSG = BPCMSG_ERROR_MSG.BP_ACCU_MOD_MUST_INPUT;
            S000_ERR_MSG_PROC();
        }
        BPCSENTY.INPUT_DATA.EVENT_TYPE = BPB4051_AWA_4051.EVT_TYPE;
        CEP.TRC(SCCGWA, BPB4051_AWA_4051.UPD_DATE);
        CEP.TRC(SCCGWA, BPB4051_AWA_4051.UPD_TIME);
        BPCSENTY.INPUT_DATA.GL_BOOK = BPB4051_AWA_4051.GL_BOOK;
        BPCSENTY.INPUT_DATA.SORT_SEQ = BPB4051_AWA_4051.SORT_SEQ;
        BPCSENTY.INPUT_DATA.TR_GROUP = BPB4051_AWA_4051.TR_GROUP;
        BPCSENTY.INPUT_DATA.GLMST_PNT = BPB4051_AWA_4051.GL_PNT;
        BPCSENTY.INPUT_DATA.DR_CR = BPB4051_AWA_4051.DR_CR;
        BPCSENTY.INPUT_DATA.ITM_CODE = BPB4051_AWA_4051.ITM_CODE;
        BPCSENTY.INPUT_DATA.ITM_PNT = BPB4051_AWA_4051.ITM_PNT;
        BPCSENTY.INPUT_DATA.BR_FLG = BPB4051_AWA_4051.BR_FLG;
        BPCSENTY.INPUT_DATA.BR = BPB4051_AWA_4051.BR;
        BPCSENTY.INPUT_DATA.CCY_PNT = BPB4051_AWA_4051.CCY_PNT;
        CEP.TRC(SCCGWA, BPB4051_AWA_4051.CCY_PNT);
        BPCSENTY.INPUT_DATA.POST_AUTH = BPB4051_AWA_4051.PST_AUTH;
        BPCSENTY.INPUT_DATA.RM_FLG = BPB4051_AWA_4051.RM_FLG;
        BPCSENTY.INPUT_DATA.EFF_DAYS = BPB4051_AWA_4051.EFF_DAYS;
        BPCSENTY.INPUT_DATA.REMARK = BPB4051_AWA_4051.REMARK;
        BPCSENTY.INPUT_DATA.HIDE_INFO.EVENT_POS = BPB4051_AWA_4051.EVT_POS;
        CEP.TRC(SCCGWA, BPB4051_AWA_4051.EVT_POS);
        CEP.TRC(SCCGWA, BPB4051_AWA_4051.SORT_SEQ);
        for (WS_IDX = 1; WS_IDX <= 60; WS_IDX += 1) {
            BPCSENTY.INPUT_DATA.AMT_METHOD[WS_IDX-1].AMT_PNT = BPB4051_AWA_4051.AMT_MTD[WS_IDX-1].AMT_PNT;
            BPCSENTY.INPUT_DATA.AMT_METHOD[WS_IDX-1].AMT_FLG = BPB4051_AWA_4051.AMT_MTD[WS_IDX-1].AMT_FLG;
        }
        S000_CALL_BPZSENTY();
    }
    public void S000_CALL_BPZSENTY() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-S-MAINT-ENTY", BPCSENTY);
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG, WS_FLD_NO);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
