package com.hisun.BP;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;

import java.io.IOException;
import java.sql.SQLException;

public class BPOT3911 {
    char K_ERROR = 'E';
    String K_OUTPUT_FMT = "BP165";
    String CPN_S_MGM_BPRD = "BP-S-MGM-BPRD ";
    String CPN_F_TLR_INF_QUERY = "BP-F-TLR-INF-QUERY";
    String WS_ERR_MSG = " ";
    short WS_FLD_NO = 0;
    String WS_HEAD_NO = " ";
    String WS_BV_NO = " ";
    int WS_LENGTH = 0;
    BPCMSG_ERROR_MSG BPCMSG_ERROR_MSG = new BPCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCFMT SCCFMT = new SCCFMT();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    BPCSBPRD BPCSBPRD = new BPCSBPRD();
    BPCFTLRQ BPCFTLRQ = new BPCFTLRQ();
    SCCGWA SCCGWA;
    BPB3910_AWA_3910 BPB3910_AWA_3910;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "BPOT3911 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "BPB3910_AWA_3910>");
        BPB3910_AWA_3910 = (BPB3910_AWA_3910) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        IBS.init(SCCGWA, BPCSBPRD);
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B010_CHECK_INPUT();
        B020_MODIFY_BPRD_RECORD();
    }
    public void B010_CHECK_INPUT() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCFTLRQ);
        BPCFTLRQ.INFO.TLR = SCCGWA.COMM_AREA.TL_ID;
        S000_CALL_BPZFTLRQ();
        if (BPCFTLRQ.INFO.TX_LVL == '0') {
            WS_ERR_MSG = BPCMSG_ERROR_MSG.BP_NOT_DIRECTOR_TLR;
            WS_FLD_NO = 0;
            S000_ERR_MSG_PROC();
        }
        if (BPB3910_AWA_3910.EFF_DATE >= BPB3910_AWA_3910.EXP_DATE) {
            WS_ERR_MSG = BPCMSG_ERROR_MSG.BP_DATE_RANGE_ERR;
            WS_FLD_NO = BPB3910_AWA_3910.EFF_DATE_NO;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        if (BPB3910_AWA_3910.EXP_DATE < SCCGWA.COMM_AREA.AC_DATE) {
            WS_ERR_MSG = BPCMSG_ERROR_MSG.BP_LESS_ACDATE;
            WS_FLD_NO = BPB3910_AWA_3910.EXP_DATE_NO;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        WS_LENGTH = 10;
        if (BPB3910_AWA_3910.HEAD_LEN > WS_LENGTH) {
            WS_ERR_MSG = BPCMSG_ERROR_MSG.BP_HADNO_MORE_LENGTH;
            WS_FLD_NO = BPB3910_AWA_3910.HEAD_LEN_NO;
            S000_ERR_MSG_PROC_INFOR();
        }
        WS_LENGTH = 20;
        CEP.TRC(SCCGWA, BPB3910_AWA_3910.NO_LEN);
        CEP.TRC(SCCGWA, WS_LENGTH);
        if (BPB3910_AWA_3910.NO_LEN > WS_LENGTH) {
            WS_ERR_MSG = BPCMSG_ERROR_MSG.BP_BVNO_MORE_LENGTH;
            WS_FLD_NO = BPB3910_AWA_3910.NO_LEN_NO;
            S000_ERR_MSG_PROC_INFOR();
        }
        if (BPB3910_AWA_3910.B_LMTUP < BPB3910_AWA_3910.B_LMT 
            || BPB3910_AWA_3910.V_LMTUP < BPB3910_AWA_3910.V_LMT) {
            WS_ERR_MSG = BPCMSG_ERROR_MSG.BP_BV_LMT_INVALID;
            S000_ERR_MSG_PROC_INFOR();
        }
    }
    public void B020_MODIFY_BPRD_RECORD() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCSBPRD);
        BPCSBPRD.FUNC = 'M';
        BPCSBPRD.OUTPUT_FMT = K_OUTPUT_FMT;
        if (SCCGWA.COMM_AREA.TR_BANK.equalsIgnoreCase("043")) {
            R000_TRANS_DATA_PARAMETER_CH();
        } else {
            R000_TRANS_DATA_PARAMETER();
        }
        S000_CALL_BPZSBPRD();
    }
    public void R000_TRANS_DATA_PARAMETER() throws IOException,SQLException,Exception {
        BPCSBPRD.FUNC = BPB3910_AWA_3910.FUNC;
        BPCSBPRD.BR = BPB3910_AWA_3910.BR;
        BPCSBPRD.CODE = BPB3910_AWA_3910.CODE;
        BPCSBPRD.TYPE = BPB3910_AWA_3910.TYPE;
        BPCSBPRD.BV_CNM = BPB3910_AWA_3910.BV_CNM;
        BPCSBPRD.BV_ENM = BPB3910_AWA_3910.BV_ENM;
        BPCSBPRD.BV_CNMS = BPB3910_AWA_3910.BV_CNMS;
        BPCSBPRD.BV_ENMS = BPB3910_AWA_3910.BV_ENMS;
        BPCSBPRD.BV_CFLG = BPB3910_AWA_3910.BV_CFLG;
        BPCSBPRD.LEVEL = BPB3910_AWA_3910.LEVEL;
        BPCSBPRD.HEAD_LENGTH = BPB3910_AWA_3910.HEAD_LEN;
        BPCSBPRD.NO_LENGTH = BPB3910_AWA_3910.NO_LEN;
        BPCSBPRD.USE_MODE = BPB3910_AWA_3910.USE_MODE;
        BPCSBPRD.USE_CTL = BPB3910_AWA_3910.USE_CTL;
        BPCSBPRD.CTL_FLG = BPB3910_AWA_3910.CTL_FLG;
        BPCSBPRD.CNT_FLG = BPB3910_AWA_3910.CNT_FLG;
        BPCSBPRD.CNT_UT = BPB3910_AWA_3910.CNT_UT;
        BPCSBPRD.COST_PRICE = BPB3910_AWA_3910.COST_PRI;
        BPCSBPRD.SER_CHARGE = BPB3910_AWA_3910.SER_CHAR;
        BPCSBPRD.CCY = BPB3910_AWA_3910.CCY;
        BPCSBPRD.AC_TYP = BPB3910_AWA_3910.AC_TYP;
        BPCSBPRD.CUT_FLG = BPB3910_AWA_3910.CUT_FLG;
        BPCSBPRD.OUT_FLG = BPB3910_AWA_3910.OUT_FLG;
        BPCSBPRD.SELL_FLG = BPB3910_AWA_3910.SELL_FLG;
        BPCSBPRD.AUTO_REL_DAY = BPB3910_AWA_3910.AUTO_DAY;
        BPCSBPRD.PP_FLG = BPB3910_AWA_3910.PP_FLG;
        BPCSBPRD.VAL_DAY = BPB3910_AWA_3910.VAL_DAY;
        BPCSBPRD.B_LMT = BPB3910_AWA_3910.B_LMT;
        BPCSBPRD.V_LMT = BPB3910_AWA_3910.V_LMT;
        BPCSBPRD.B_LMTUP = BPB3910_AWA_3910.B_LMTUP;
        BPCSBPRD.V_LMTUP = BPB3910_AWA_3910.V_LMTUP;
        BPCSBPRD.STS = BPB3910_AWA_3910.STS;
        BPCSBPRD.EFF_DATE = BPB3910_AWA_3910.EFF_DATE;
        BPCSBPRD.EXP_DATE = BPB3910_AWA_3910.EXP_DATE;
        CEP.TRC(SCCGWA, BPB3910_AWA_3910.CUT_FLG);
        CEP.TRC(SCCGWA, BPCSBPRD.CUT_FLG);
    }
    public void R000_TRANS_DATA_PARAMETER_CH() throws IOException,SQLException,Exception {
        BPCSBPRD.FUNC = BPB3910_AWA_3910.FUNC;
        BPCSBPRD.BR = BPB3910_AWA_3910.BR;
        BPCSBPRD.CODE = BPB3910_AWA_3910.CODE;
        BPCSBPRD.TYPE = BPB3910_AWA_3910.TYPE;
        BPCSBPRD.BV_CNM = BPB3910_AWA_3910.BV_CNM;
        BPCSBPRD.BV_ENM = BPB3910_AWA_3910.BV_ENM;
        BPCSBPRD.BV_CNMS = BPB3910_AWA_3910.BV_CNMS;
        BPCSBPRD.BV_ENMS = BPB3910_AWA_3910.BV_ENMS;
        BPCSBPRD.BV_CFLG = BPB3910_AWA_3910.BV_CFLG;
        BPCSBPRD.LEVEL = BPB3910_AWA_3910.LEVEL;
        BPCSBPRD.HEAD_LENGTH = BPB3910_AWA_3910.HEAD_LEN;
        BPCSBPRD.NO_LENGTH = BPB3910_AWA_3910.NO_LEN;
        BPCSBPRD.USE_MODE = BPB3910_AWA_3910.USE_MODE;
        BPCSBPRD.USE_CTL = BPB3910_AWA_3910.USE_CTL;
        BPCSBPRD.CTL_FLG = BPB3910_AWA_3910.CTL_FLG;
        BPCSBPRD.CNT_FLG = BPB3910_AWA_3910.CNT_FLG;
        BPCSBPRD.CNT_UT = BPB3910_AWA_3910.CNT_UT;
        BPCSBPRD.COST_PRICE = BPB3910_AWA_3910.COST_PRI;
        BPCSBPRD.SER_CHARGE = BPB3910_AWA_3910.SER_CHAR;
        BPCSBPRD.CCY = BPB3910_AWA_3910.CCY;
        BPCSBPRD.AC_TYP = BPB3910_AWA_3910.AC_TYP;
        BPCSBPRD.CUT_FLG = BPB3910_AWA_3910.CUT_FLG;
        BPCSBPRD.OUT_FLG = BPB3910_AWA_3910.OUT_FLG;
        BPCSBPRD.SELL_FLG = BPB3910_AWA_3910.SELL_FLG;
        BPCSBPRD.AUTO_REL_DAY = BPB3910_AWA_3910.AUTO_DAY;
        BPCSBPRD.PP_FLG = BPB3910_AWA_3910.PP_FLG;
        BPCSBPRD.VAL_DAY = BPB3910_AWA_3910.VAL_DAY;
        BPCSBPRD.B_LMT = BPB3910_AWA_3910.B_LMT;
        BPCSBPRD.V_LMT = BPB3910_AWA_3910.V_LMT;
        BPCSBPRD.B_LMTUP = BPB3910_AWA_3910.B_LMTUP;
        BPCSBPRD.V_LMTUP = BPB3910_AWA_3910.V_LMTUP;
        BPCSBPRD.STS = BPB3910_AWA_3910.STS;
        BPCSBPRD.EFF_DATE = BPB3910_AWA_3910.EFF_DATE;
        BPCSBPRD.EXP_DATE = BPB3910_AWA_3910.EXP_DATE;
        BPCSBPRD.BV_RANGE = BPB3910_AWA_3910.BV_RANGE;
        BPCSBPRD.BOOK_ROW = BPB3910_AWA_3910.BOOK_ROW;
        BPCSBPRD.PAGE_ROW = BPB3910_AWA_3910.PAGE_ROW;
        BPCSBPRD.CHK_FLG = BPB3910_AWA_3910.CHK_FLG;
        BPCSBPRD.BV_SRC = BPB3910_AWA_3910.BV_SRC;
        BPCSBPRD.STR_POS = BPB3910_AWA_3910.STR_POS;
        BPCSBPRD.REL_BV = BPB3910_AWA_3910.REL_BV;
        CEP.TRC(SCCGWA, "XGQ001");
        CEP.TRC(SCCGWA, BPCSBPRD.STR_POS);
        CEP.TRC(SCCGWA, BPCSBPRD.REL_BV);
        CEP.TRC(SCCGWA, BPCSBPRD.CHK_FLG);
        CEP.TRC(SCCGWA, BPCSBPRD.BV_SRC);
        CEP.TRC(SCCGWA, BPB3910_AWA_3910.CUT_FLG);
        CEP.TRC(SCCGWA, BPCSBPRD.CUT_FLG);
    }
    public void S000_CALL_BPZSBPRD() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, "BEFORE-CALL-BPZSBPRD");
        IBS.CALLCPN(SCCGWA, "BP-S-MGM-BPRD", BPCSBPRD);
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG, WS_FLD_NO);
    }
    public void S000_ERR_MSG_PROC_INFOR() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG, WS_LENGTH, WS_FLD_NO);
    }
    public void S000_ERR_MSG_PROC_CONTINUE() throws IOException,SQLException,Exception {
        CEP.ERRC(SCCGWA, WS_ERR_MSG, WS_FLD_NO);
    }
    public void S000_CALL_BPZFTLRQ() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, CPN_F_TLR_INF_QUERY, BPCFTLRQ);
        if (BPCFTLRQ.RC.RC_CODE != 0) {
            WS_ERR_MSG = IBS.CLS2CPY(SCCGWA, BPCFTLRQ.RC);
            WS_FLD_NO = 0;
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_ERR_MSG_PROC_LAST() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
