package com.hisun.BP;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;

import java.io.IOException;
import java.sql.SQLException;

public class BPOT7525 {
    String K_OUTPUT_FMT = "BP831";
    String CPN_P_SET_SBUS_TRN = "SC-SET-SUBS-TRANS";
    String CPN_ORGM_READ = "BP-R-BRW-ORGM       ";
    String WS_ERR_MSG = " ";
    short WS_FLD_NO = 0;
    BPOT7525_WS_ORGM_KEY WS_ORGM_KEY = new BPOT7525_WS_ORGM_KEY();
    BPCMSG_ERROR_MSG BPCMSG_ERROR_MSG = new BPCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCFMT SCCFMT = new SCCFMT();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    SCCSUBS SCCSUBS = new SCCSUBS();
    BPCSMORG BPCSMORG = new BPCSMORG();
    BPCO7525_OPT_7525 BPCO7525_OPT_7525 = new BPCO7525_OPT_7525();
    BPCRORGM BPCRORGM = new BPCRORGM();
    BPRORGM BPRPORGM = new BPRORGM();
    SCCGWA SCCGWA;
    BPB4520_AWA_4520 BPB4520_AWA_4520;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "BPOT7525 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "BPB4520_AWA_4520>");
        BPB4520_AWA_4520 = (BPB4520_AWA_4520) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B010_CHECK_INPUT();
        B020_QUERY_ORG_INFO();
        R010_TRANS_DATA_OUPUT();
        B030_SET_SUB_TRN();
    }
    public void B010_CHECK_INPUT() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, BPB4520_AWA_4520.BR);
        CEP.TRC(SCCGWA, BPB4520_AWA_4520.EFF_DT);
        WS_ORGM_KEY.WS_ORGM_BNK = SCCGWA.COMM_AREA.TR_BANK;
        BPB4520_AWA_4520.BNK = WS_ORGM_KEY.WS_ORGM_BNK;
        WS_ORGM_KEY.WS_ORGM_BR = BPB4520_AWA_4520.BR;
        if (BPB4520_AWA_4520.BNK.equalsIgnoreCase("0") 
            || BPB4520_AWA_4520.BNK.charAt(0) == 0X00) {
            WS_ERR_MSG = BPCMSG_ERROR_MSG.BP_INPUT_ERROR;
            WS_FLD_NO = BPB4520_AWA_4520.BNK_NO;
            S000_ERR_MSG_PROC();
        }
        if (BPB4520_AWA_4520.BR == 0 
            || BPB4520_AWA_4520.BR == 0X00) {
            WS_ERR_MSG = BPCMSG_ERROR_MSG.BP_INPUT_ERROR;
            WS_FLD_NO = BPB4520_AWA_4520.BR_NO;
            S000_ERR_MSG_PROC();
        }
    }
    public void B020_QUERY_ORG_INFO() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPRPORGM);
        IBS.init(SCCGWA, BPCRORGM);
        BPRPORGM.KEY.IBS_AC_BK = SCCGWA.COMM_AREA.TR_BANK;
        BPRPORGM.KEY.BR = WS_ORGM_KEY.WS_ORGM_BR;
        if (BPB4520_AWA_4520.EFF_DT == 0) {
            BPRPORGM.EFF_DT = 99991231;
        } else {
            BPRPORGM.EFF_DT = BPB4520_AWA_4520.EFF_DT;
        }
        CEP.TRC(SCCGWA, BPRPORGM.EFF_DT);
        BPCRORGM.INFO.FUNC = 'R';
        BPCRORGM.INFO.POINTER = BPRPORGM;
        BPCRORGM.INFO.LEN = 1252;
        S000_CALL_BPZRORGM();
        if (BPCRORGM.RETURN_INFO == 'N') {
            WS_ERR_MSG = BPCMSG_ERROR_MSG.BP_ORG_NOTFND;
            S000_ERR_MSG_PROC();
        }
    }
    public void R010_TRANS_DATA_OUPUT() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCO7525_OPT_7525);
        BPCO7525_OPT_7525.BNK = BPB4520_AWA_4520.BNK;
        BPCO7525_OPT_7525.BR = BPB4520_AWA_4520.BR;
        BPCO7525_OPT_7525.EFF_DT = BPRPORGM.EFF_DT;
        BPCO7525_OPT_7525.EXP_DT = BPRPORGM.EXP_DT;
        BPCO7525_OPT_7525.ORG_CDESC = BPRPORGM.CDESC;
        BPCO7525_OPT_7525.SUPR_BR = BPRPORGM.SUPR_BR;
        BPCO7525_OPT_7525.ATTR = BPRPORGM.ATTR;
        BPCO7525_OPT_7525.LVL = BPRPORGM.LVL;
        BPCO7525_OPT_7525.TYP = "ORGM";
        BPCO7525_OPT_7525.CHN_NM = BPRPORGM.CHN_NM;
        BPCO7525_OPT_7525.CHN_ADDR = BPRPORGM.CHN_ADDR;
        BPCO7525_OPT_7525.ENG_NM = BPRPORGM.ENG_NM;
        BPCO7525_OPT_7525.ENG_ADDR = BPRPORGM.ENG_ADDR;
        BPCO7525_OPT_7525.ABBR = BPRPORGM.ABBR;
        BPCO7525_OPT_7525.LINK_MAN = BPRPORGM.LINK_MAN;
        BPCO7525_OPT_7525.LINK_TEL = BPRPORGM.LINK_TEL;
        BPCO7525_OPT_7525.POST = BPRPORGM.POST;
        BPCO7525_OPT_7525.TLR_MAX = BPRPORGM.TLR_MAX;
        BPCO7525_OPT_7525.ATH_MAX = BPRPORGM.ATH_MAX;
        BPCO7525_OPT_7525.FX_BUSI = BPRPORGM.FX_BUSI;
        BPCO7525_OPT_7525.CNAP_NO = BPRPORGM.CNAP_NO;
        BPCO7525_OPT_7525.ACCT_FLG = BPRPORGM.ACCT_FLG;
        BPCO7525_OPT_7525.OPN_DT = BPRPORGM.OPN_DT;
        BPCO7525_OPT_7525.RUN_HDAY = BPRPORGM.RUN_HDAY;
        BPCO7525_OPT_7525.CALD_CD = BPRPORGM.CALD_CD;
        BPCO7525_OPT_7525.OPN_TM = BPRPORGM.OPN_TM;
        BPCO7525_OPT_7525.CLS_TM = BPRPORGM.CLS_TM;
        BPCO7525_OPT_7525.HOPN_TM = BPRPORGM.HOPN_TM;
        BPCO7525_OPT_7525.HCLS_TM = BPRPORGM.HCLS_TM;
        BPCO7525_OPT_7525.FAX = BPRPORGM.FAX;
        BPCO7525_OPT_7525.TELEX = BPRPORGM.TELEX;
        BPCO7525_OPT_7525.COUN_CD = BPRPORGM.COUN_CD;
        BPCO7525_OPT_7525.CITY_CD = BPRPORGM.CITY_CD;
        BPCO7525_OPT_7525.UNSCH_HOL = BPRPORGM.UNSCH_HOL;
        BPCO7525_OPT_7525.UNSCH_HOL_TM = BPRPORGM.UNSCH_HOL_TM;
        BPCO7525_OPT_7525.OPN_CHECK_FLG = BPRPORGM.OPN_CHECK_FLG;
        BPCO7525_OPT_7525.VOU_CHECK_FLG = BPRPORGM.VOU_CHECK_FLG;
        BPCO7525_OPT_7525.INT_TAX_FLG = BPRPORGM.INT_TAX_FLG;
        BPCO7525_OPT_7525.TRA_TYP = BPRPORGM.TRA_TYP;
        BPCO7525_OPT_7525.VIL_TYP = BPRPORGM.VIL_TYP;
        BPCO7525_OPT_7525.AREA_CD = BPRPORGM.AREA_CD;
        BPCO7525_OPT_7525.BR_STS = BPRPORGM.BR_STS;
        BPCO7525_OPT_7525.INT_BR_FLG = BPRPORGM.INT_BR_FLG;
        BPCO7525_OPT_7525.TRA_REG_FLG = BPRPORGM.TRA_REG_FLG;
        BPCO7525_OPT_7525.FIN_LIC_NO = BPRPORGM.FIN_LIC_NO;
        IBS.init(SCCGWA, SCCFMT);
        SCCFMT.FMTID = K_OUTPUT_FMT;
        SCCFMT.DATA_PTR = BPCO7525_OPT_7525;
        SCCFMT.DATA_LEN = 0;
        IBS.FMT(SCCGWA, SCCFMT);
    }
    public void B030_SET_SUB_TRN() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, SCCSUBS);
        SCCSUBS.AP_CODE = 999;
        SCCSUBS.TR_CODE = 4524;
        S000_SET_SUBS_TRN();
    }
    public void S000_CALL_BPZRORGM() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, CPN_ORGM_READ, BPCRORGM);
        if (BPCRORGM.RC.RC_CODE != 0 
            || BPCRORGM.RETURN_INFO == 'N') {
            WS_ERR_MSG = BPCMSG_ERROR_MSG.BP_PARM_NOTFND;
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_SET_SUBS_TRN() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, CPN_P_SET_SBUS_TRN, SCCSUBS);
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG, WS_FLD_NO);
    }
    public void S000_ERR_MSG_PROC_CONTINUE() throws IOException,SQLException,Exception {
        CEP.ERRC(SCCGWA, WS_ERR_MSG, WS_FLD_NO);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
