package com.hisun.BP;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;

import java.io.IOException;
import java.sql.SQLException;

public class BPOT9398 {
    String JIBS_tmp_str[] = new String[10];
    BPOT9398_WS_TEMP_VARIABLE WS_TEMP_VARIABLE = new BPOT9398_WS_TEMP_VARIABLE();
    int WS_I = 0;
    int WS_J = 0;
    BPOT9398_WS_REVE_DATA WS_REVE_DATA = new BPOT9398_WS_REVE_DATA();
    char WS_SEQ_FLG = ' ';
    char WS_FUNC_FLG = ' ';
    BPCMSG_ERROR_MSG BPCMSG_ERROR_MSG = new BPCMSG_ERROR_MSG();
    SCCMSG SCCMSG = new SCCMSG();
    SCCCALL SCCCALL = new SCCCALL();
    SCCSUBS SCCSUBS = new SCCSUBS();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCFMT SCCFMT = new SCCFMT();
    SCRJRN SCRJRN = new SCRJRN();
    SCRJRNH SCRJRNH = new SCRJRNH();
    SCCPJRN SCCPJRN = new SCCPJRN();
    BPCSFECT BPCSFECT = new BPCSFECT();
    BPCOUFEC BPCOUFEC = new BPCOUFEC();
    SCCGWA SCCGWA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    BPCPORUP_DATA_INFO BPCPORUP;
    BPB9120_AWA_9120 BPB9120_AWA_9120;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "BPOT9398 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "BPB9120_AWA_9120>");
        BPB9120_AWA_9120 = (BPB9120_AWA_9120) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        BPCPORUP = (BPCPORUP_DATA_INFO) SCCGWA.COMM_AREA.TR_BR_PTR;
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B100_CHECK_INPUT();
        B200_INQ_FEECTR_PROC();
        B300_OUTPUT_PROC();
    }
    public void B100_CHECK_INPUT() throws IOException,SQLException,Exception {
    }
    public void B200_INQ_FEECTR_PROC() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, "IIIIIIIIII");
        CEP.TRC(SCCGWA, BPB9120_AWA_9120.CTRT_NO);
        CEP.TRC(SCCGWA, BPB9120_AWA_9120.FEE_DESC);
        CEP.TRC(SCCGWA, BPB9120_AWA_9120.CI_NO);
        CEP.TRC(SCCGWA, BPB9120_AWA_9120.CI_S_NM);
        CEP.TRC(SCCGWA, BPB9120_AWA_9120.CNTR_TYP);
        CEP.TRC(SCCGWA, BPB9120_AWA_9120.FEE_TYP);
        CEP.TRC(SCCGWA, BPB9120_AWA_9120.BK_ACCT);
        CEP.TRC(SCCGWA, BPB9120_AWA_9120.PRDT_TYP);
        CEP.TRC(SCCGWA, BPB9120_AWA_9120.STR_DT);
        CEP.TRC(SCCGWA, BPB9120_AWA_9120.MAT_DT);
        CEP.TRC(SCCGWA, BPB9120_AWA_9120.HOL_OVRD);
        CEP.TRC(SCCGWA, BPB9120_AWA_9120.HOL_METH);
        CEP.TRC(SCCGWA, BPB9120_AWA_9120.PAY_IND);
        CEP.TRC(SCCGWA, BPB9120_AWA_9120.CSH_IND);
        CEP.TRC(SCCGWA, BPB9120_AWA_9120.PORT_CD);
        CEP.TRC(SCCGWA, BPB9120_AWA_9120.PAY_METH);
        CEP.TRC(SCCGWA, BPB9120_AWA_9120.ACR_TYP);
        CEP.TRC(SCCGWA, BPB9120_AWA_9120.PRC_METH);
        CEP.TRC(SCCGWA, BPB9120_AWA_9120.TXN_CCY);
        IBS.init(SCCGWA, BPCSFECT);
        BPCSFECT.CTNO = BPB9120_AWA_9120.CTRT_NO;
        BPCSFECT.START_DT = BPB9120_AWA_9120.STR_DT;
        BPCSFECT.FUNC_CODE = 'I';
        S000_CALL_BPZSFECT();
    }
    public void B300_OUTPUT_PROC() throws IOException,SQLException,Exception {
        R000_SET_SUBC_TXN_CODE();
        IBS.init(SCCGWA, SCCFMT);
        IBS.init(SCCGWA, BPCOUFEC);
        BPCOUFEC.CTNO = BPCSFECT.CTNO;
        BPCOUFEC.FEE_DESC = BPCSFECT.FEE_DESC;
        BPCOUFEC.CINO = BPCSFECT.CINO;
        BPCOUFEC.CI_ABBR_NM = BPCSFECT.CI_ABBR_NM;
        BPCOUFEC.CT_TYP = BPCSFECT.CT_TYP;
        BPCOUFEC.FEE_TYP = BPCSFECT.FEE_TYP;
        BPCOUFEC.BOOK_ACCT = BPCSFECT.BOOK_ACCT;
        BPCOUFEC.PRDT_TYP = BPCSFECT.PRDT_TYP;
        BPCOUFEC.START_DT = BPCSFECT.START_DT;
        BPCOUFEC.MATURITY_DT = BPCSFECT.MATURITY_DT;
        BPCOUFEC.HOL_OVR = BPCSFECT.HOL_OVR;
        BPCOUFEC.CAL_CD1 = BPCSFECT.CAL_CD1;
        BPCOUFEC.HOL_METH = BPCSFECT.HOL_METH;
        BPCOUFEC.CAL_CD2 = BPCSFECT.CAL_CD2;
        BPCOUFEC.PAY_IND = BPCSFECT.PAY_IND;
        BPCOUFEC.CSH_FLW_IND = BPCSFECT.CSH_FLW_IND;
        BPCOUFEC.BK_PFLO = BPCSFECT.BK_PFLO;
        BPCOUFEC.PAY_METH = BPCSFECT.PAY_METH;
        BPCOUFEC.ACU_TYP = BPCSFECT.ACU_TYP;
        BPCOUFEC.FIE_PRC_METH = BPCSFECT.FIX_PRC_METH;
        BPCOUFEC.TXN_CCY = BPCSFECT.TXN_CCY;
        BPCOUFEC.TXN_AMT = BPCSFECT.TXN_AMT;
        BPCOUFEC.RLTD_CTNO = BPCSFECT.RLTD_CTNO;
        BPCOUFEC.RLTD_CT_TYP = BPCSFECT.RLTD_CT_TYP;
        BPCOUFEC.AMT_TYP = BPCSFECT.AMT_TYP;
        BPCOUFEC.RLTD_PRDT_TYP = BPCSFECT.RLTD_PRDT_TYP;
        BPCOUFEC.AMT_PCT = BPCSFECT.AMT_PCT;
        BPCOUFEC.INT_BASIC = BPCSFECT.INT_BASIC;
        BPCOUFEC.AGGR_TYP = BPCSFECT.AGGR_TYP;
        BPCOUFEC.REF_CCY = BPCSFECT.REF_CCY;
        BPCOUFEC.REF_METH = BPCSFECT.REF_METH;
        for (WS_I = 1; WS_I <= 5; WS_I += 1) {
            BPCOUFEC.REF_FEE_DATA[WS_I-1].REF_AMT = BPCSFECT.REF_FEE_DATA[WS_I-1].REF_AMT;
            BPCOUFEC.REF_FEE_DATA[WS_I-1].REF_PCT = BPCSFECT.REF_FEE_DATA[WS_I-1].REF_PCT;
            BPCOUFEC.REF_FEE_DATA[WS_I-1].FEE_AMT = BPCSFECT.REF_FEE_DATA[WS_I-1].FEE_AMT;
            BPCOUFEC.REF_FEE_DATA[WS_I-1].FEE_RATE = BPCSFECT.REF_FEE_DATA[WS_I-1].FEE_RATE;
        }
        BPCOUFEC.CHG_CCY = BPCSFECT.CHG_CCY;
        BPCOUFEC.CHG_AMT = BPCSFECT.CHG_AMT;
        BPCOUFEC.CHG_METH = BPCSFECT.CHG_METH;
        BPCOUFEC.CHG_ACNO = BPCSFECT.CHG_ACNO;
        BPCOUFEC.NOSTRO_CD = BPCSFECT.NOSTRO_CD;
        BPCOUFEC.CHQ_NO = BPCSFECT.CHQ_NO;
        BPCOUFEC.GL_MST_BR = BPCSFECT.GL_MST_BR;
        BPCOUFEC.GL_MST_HO = BPCSFECT.GL_MST_HO;
        BPCOUFEC.GL_MST_IAS39 = BPCSFECT.GL_MST_IAS39;
        BPCOUFEC.GL_MST_UNUS = BPCSFECT.GL_MST_UNUS;
        for (WS_J = 1; WS_J <= 3; WS_J += 1) {
            BPCOUFEC.TXN_OIC_DATA[WS_J-1].TXN_OIC = BPCSFECT.TXN_OIC_DATA[WS_J-1].TXN_OIC;
            BPCOUFEC.TXN_OIC_DATA[WS_J-1].OIC_ACCT = BPCSFECT.TXN_OIC_DATA[WS_J-1].OIC_ACCT;
            BPCOUFEC.TXN_OIC_DATA[WS_J-1].PRFT_PCT = BPCSFECT.TXN_OIC_DATA[WS_J-1].PRFT_PCT;
        }
        BPCOUFEC.CT_STS = BPCSFECT.CT_STS;
        BPCOUFEC.REMARK = BPCSFECT.REMARK;
        CEP.TRC(SCCGWA, BPCOUFEC.CTNO);
        CEP.TRC(SCCGWA, BPCOUFEC.FEE_DESC);
        CEP.TRC(SCCGWA, BPCOUFEC.CINO);
        CEP.TRC(SCCGWA, BPCOUFEC.CI_ABBR_NM);
        CEP.TRC(SCCGWA, BPCOUFEC.CT_TYP);
        CEP.TRC(SCCGWA, BPCOUFEC.FEE_TYP);
        CEP.TRC(SCCGWA, BPCOUFEC.BOOK_ACCT);
        CEP.TRC(SCCGWA, BPCOUFEC.PRDT_TYP);
        CEP.TRC(SCCGWA, BPCOUFEC.START_DT);
        CEP.TRC(SCCGWA, BPCOUFEC.MATURITY_DT);
        CEP.TRC(SCCGWA, BPCOUFEC.HOL_OVR);
        CEP.TRC(SCCGWA, BPCOUFEC.HOL_METH);
        CEP.TRC(SCCGWA, BPCOUFEC.PAY_IND);
        CEP.TRC(SCCGWA, BPCOUFEC.CSH_FLW_IND);
        CEP.TRC(SCCGWA, BPCOUFEC.BK_PFLO);
        CEP.TRC(SCCGWA, BPCOUFEC.PAY_METH);
        CEP.TRC(SCCGWA, BPCOUFEC.ACU_TYP);
        CEP.TRC(SCCGWA, BPCOUFEC.FIE_PRC_METH);
        CEP.TRC(SCCGWA, BPCOUFEC.TXN_CCY);
        CEP.TRC(SCCGWA, BPCOUFEC.TXN_AMT);
        CEP.TRC(SCCGWA, BPCOUFEC.RLTD_CTNO);
        CEP.TRC(SCCGWA, BPCOUFEC.RLTD_CT_TYP);
        CEP.TRC(SCCGWA, BPCOUFEC.AMT_TYP);
        CEP.TRC(SCCGWA, BPCOUFEC.RLTD_PRDT_TYP);
        CEP.TRC(SCCGWA, BPCOUFEC.AMT_PCT);
        CEP.TRC(SCCGWA, BPCOUFEC.INT_BASIC);
        CEP.TRC(SCCGWA, BPCOUFEC.AGGR_TYP);
        CEP.TRC(SCCGWA, BPCOUFEC.REF_CCY);
        CEP.TRC(SCCGWA, BPCOUFEC.REF_METH);
        CEP.TRC(SCCGWA, BPCOUFEC.REF_FEE_DATA[1-1].REF_AMT);
        CEP.TRC(SCCGWA, BPCOUFEC.REF_FEE_DATA[1-1].REF_PCT);
        CEP.TRC(SCCGWA, BPCOUFEC.REF_FEE_DATA[1-1].FEE_AMT);
        CEP.TRC(SCCGWA, BPCOUFEC.REF_FEE_DATA[1-1].FEE_RATE);
        CEP.TRC(SCCGWA, BPCOUFEC.REF_FEE_DATA[2-1].REF_AMT);
        CEP.TRC(SCCGWA, BPCOUFEC.REF_FEE_DATA[2-1].REF_PCT);
        CEP.TRC(SCCGWA, BPCOUFEC.REF_FEE_DATA[2-1].FEE_AMT);
        CEP.TRC(SCCGWA, BPCOUFEC.REF_FEE_DATA[2-1].FEE_RATE);
        CEP.TRC(SCCGWA, BPCOUFEC.REF_FEE_DATA[3-1].REF_AMT);
        CEP.TRC(SCCGWA, BPCOUFEC.REF_FEE_DATA[3-1].REF_PCT);
        CEP.TRC(SCCGWA, BPCOUFEC.REF_FEE_DATA[3-1].FEE_AMT);
        CEP.TRC(SCCGWA, BPCOUFEC.REF_FEE_DATA[3-1].FEE_RATE);
        CEP.TRC(SCCGWA, BPCOUFEC.REF_FEE_DATA[4-1].REF_AMT);
        CEP.TRC(SCCGWA, BPCOUFEC.REF_FEE_DATA[4-1].REF_PCT);
        CEP.TRC(SCCGWA, BPCOUFEC.REF_FEE_DATA[4-1].FEE_AMT);
        CEP.TRC(SCCGWA, BPCOUFEC.REF_FEE_DATA[4-1].FEE_RATE);
        CEP.TRC(SCCGWA, BPCOUFEC.REF_FEE_DATA[5-1].REF_AMT);
        CEP.TRC(SCCGWA, BPCOUFEC.REF_FEE_DATA[5-1].REF_PCT);
        CEP.TRC(SCCGWA, BPCOUFEC.REF_FEE_DATA[5-1].FEE_AMT);
        CEP.TRC(SCCGWA, BPCOUFEC.REF_FEE_DATA[5-1].FEE_RATE);
        CEP.TRC(SCCGWA, BPCOUFEC.CHG_CCY);
        CEP.TRC(SCCGWA, BPCOUFEC.CHG_AMT);
        CEP.TRC(SCCGWA, BPCOUFEC.CHG_METH);
        CEP.TRC(SCCGWA, BPCOUFEC.CHG_ACNO);
        CEP.TRC(SCCGWA, BPCOUFEC.NOSTRO_CD);
        CEP.TRC(SCCGWA, BPCOUFEC.CHQ_NO);
        CEP.TRC(SCCGWA, BPCOUFEC.GL_MST_BR);
        CEP.TRC(SCCGWA, BPCOUFEC.GL_MST_HO);
        CEP.TRC(SCCGWA, BPCOUFEC.GL_MST_IAS39);
        CEP.TRC(SCCGWA, BPCOUFEC.GL_MST_UNUS);
        CEP.TRC(SCCGWA, BPCOUFEC.TXN_OIC_DATA[1-1].TXN_OIC);
        CEP.TRC(SCCGWA, BPCOUFEC.TXN_OIC_DATA[1-1].OIC_ACCT);
        CEP.TRC(SCCGWA, BPCOUFEC.TXN_OIC_DATA[1-1].PRFT_PCT);
        CEP.TRC(SCCGWA, BPCOUFEC.TXN_OIC_DATA[2-1].TXN_OIC);
        CEP.TRC(SCCGWA, BPCOUFEC.TXN_OIC_DATA[2-1].OIC_ACCT);
        CEP.TRC(SCCGWA, BPCOUFEC.TXN_OIC_DATA[2-1].PRFT_PCT);
        CEP.TRC(SCCGWA, BPCOUFEC.TXN_OIC_DATA[3-1].TXN_OIC);
        CEP.TRC(SCCGWA, BPCOUFEC.TXN_OIC_DATA[3-1].OIC_ACCT);
        CEP.TRC(SCCGWA, BPCOUFEC.TXN_OIC_DATA[3-1].PRFT_PCT);
        CEP.TRC(SCCGWA, BPCOUFEC.CT_STS);
        CEP.TRC(SCCGWA, BPCOUFEC.REMARK);
        SCCFMT.FMTID = "BPX01";
        SCCFMT.DATA_PTR = BPCOUFEC;
        SCCFMT.DATA_LEN = 1367;
        IBS.FMT(SCCGWA, SCCFMT);
    }
    public void R000_SET_SUBC_TXN_CODE() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, SCCSUBS);
        SCCSUBS.AP_CODE = 999;
        SCCSUBS.TR_CODE = 9123;
        S000_SET_SUBS_TRN();
        CEP.TRC(SCCGWA, SCCSUBS.AP_CODE);
        CEP.TRC(SCCGWA, SCCSUBS.TR_CODE);
    }
    public void S000_CALL_BPZSFECT() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-S-FECT-MAINT", BPCSFECT);
        CEP.TRC(SCCGWA, BPCSFECT.RC);
        if (BPCSFECT.RC.RC_CODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, BPCSFECT.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_SET_SUBS_TRN() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "SC-SET-SUBS-TRANS", SCCSUBS);
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, WS_TEMP_VARIABLE.WS_MSGID);
        CEP.ERR(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_FLD_NO);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
