package com.hisun.BP;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;

import java.io.IOException;
import java.sql.SQLException;

public class BPOT9124 {
    String JIBS_tmp_str[] = new String[10];
    BPOT9124_WS_TEMP_VARIABLE WS_TEMP_VARIABLE = new BPOT9124_WS_TEMP_VARIABLE();
    char WS_SEQ_FLG = ' ';
    BPCMSG_ERROR_MSG BPCMSG_ERROR_MSG = new BPCMSG_ERROR_MSG();
    SCCMSG SCCMSG = new SCCMSG();
    SCCCALL SCCCALL = new SCCCALL();
    BPCSFECT BPCSFECT = new BPCSFECT();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCGWA SCCGWA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    BPCPORUP_DATA_INFO BPCPORUP;
    BPB9124_AWA_9124 BPB9124_AWA_9124;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "BPOT9124 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "BPB9124_AWA_9124>");
        BPB9124_AWA_9124 = (BPB9124_AWA_9124) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        BPCPORUP = (BPCPORUP_DATA_INFO) SCCGWA.COMM_AREA.TR_BR_PTR;
        IBS.init(SCCGWA, WS_TEMP_VARIABLE);
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B100_CHECK_INPUT();
        B200_DEL_FEE_CNTR_PROC();
    }
    public void B100_CHECK_INPUT() throws IOException,SQLException,Exception {
    }
    public void B200_DEL_FEE_CNTR_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCSFECT);
        BPCSFECT.FUNC_CODE = 'D';
        R000_MOVE_DATA();
        S000_CALL_BPZSFECT();
    }
    public void R000_MOVE_DATA() throws IOException,SQLException,Exception {
        BPCSFECT.CTNO = BPB9124_AWA_9124.CTNO;
        BPCSFECT.FEE_DESC = BPB9124_AWA_9124.FEE_DESC;
        BPCSFECT.CINO = BPB9124_AWA_9124.CINO;
        BPCSFECT.CI_ABBR_NM = BPB9124_AWA_9124.CI_CNM;
        BPCSFECT.CT_TYP = BPB9124_AWA_9124.CT_TYP;
        BPCSFECT.FEE_TYP = BPB9124_AWA_9124.FEE_TYP;
        BPCSFECT.BOOK_ACCT = BPB9124_AWA_9124.BOOK_BR;
        BPCSFECT.PRDT_TYP = BPB9124_AWA_9124.PRDT_TYP;
        BPCSFECT.START_DT = BPB9124_AWA_9124.START_DT;
        BPCSFECT.MATURITY_DT = BPB9124_AWA_9124.END_DT;
        BPCSFECT.HOL_OVR = BPB9124_AWA_9124.HOL_OVR;
        BPCSFECT.CAL_CD1 = BPB9124_AWA_9124.CAL_CD1;
        BPCSFECT.CAL_CD2 = BPB9124_AWA_9124.CAL_CD2;
        BPCSFECT.HOL_METH = BPB9124_AWA_9124.HOL_METH;
        BPCSFECT.PAY_IND = BPB9124_AWA_9124.PAY_IND;
        BPCSFECT.CSH_FLW_IND = BPB9124_AWA_9124.CSH_FLW;
        BPCSFECT.BK_PFLO = BPB9124_AWA_9124.BK_PFLO;
        BPCSFECT.PAY_METH = BPB9124_AWA_9124.PAY_METH;
        BPCSFECT.ACU_TYP = BPB9124_AWA_9124.ACU_TYP;
        BPCSFECT.FIX_PRC_METH = BPB9124_AWA_9124.FEE_METH;
        BPCSFECT.TXN_CCY = BPB9124_AWA_9124.TXN_CCY;
        BPCSFECT.TXN_AMT = BPB9124_AWA_9124.TXN_AMT;
        BPCSFECT.RLTD_CTNO = BPB9124_AWA_9124.RLT_CTNO;
        BPCSFECT.RLTD_CT_TYP = BPB9124_AWA_9124.RLT_CTYP;
        BPCSFECT.AMT_TYP = BPB9124_AWA_9124.AMT_TYP;
        BPCSFECT.RLTD_PRDT_TYP = BPB9124_AWA_9124.RLT_PTYP;
        BPCSFECT.AMT_PCT = BPB9124_AWA_9124.AMT_PCT;
        BPCSFECT.INT_BASIC = BPB9124_AWA_9124.FBAS_CNT;
        BPCSFECT.AGGR_TYP = BPB9124_AWA_9124.AGGR_TYP;
        BPCSFECT.REF_CCY = BPB9124_AWA_9124.REF_CCY;
        BPCSFECT.REF_METH = BPB9124_AWA_9124.REF_METH;
        for (WS_TEMP_VARIABLE.WS_I = 1; WS_TEMP_VARIABLE.WS_I <= 5; WS_TEMP_VARIABLE.WS_I += 1) {
            BPCSFECT.REF_FEE_DATA[WS_TEMP_VARIABLE.WS_I-1].REF_AMT = BPB9124_AWA_9124.REF_FEED[WS_TEMP_VARIABLE.WS_I-1].REF_AMT;
            BPCSFECT.REF_FEE_DATA[WS_TEMP_VARIABLE.WS_I-1].REF_PCT = BPB9124_AWA_9124.REF_FEED[WS_TEMP_VARIABLE.WS_I-1].REF_PCT;
            BPCSFECT.REF_FEE_DATA[WS_TEMP_VARIABLE.WS_I-1].AGG_MTH = BPB9124_AWA_9124.REF_FEED[WS_TEMP_VARIABLE.WS_I-1].AGG_MTH;
            BPCSFECT.REF_FEE_DATA[WS_TEMP_VARIABLE.WS_I-1].FEE_AMT = BPB9124_AWA_9124.REF_FEED[WS_TEMP_VARIABLE.WS_I-1].FEE_AMT;
            BPCSFECT.REF_FEE_DATA[WS_TEMP_VARIABLE.WS_I-1].FEE_RATE = BPB9124_AWA_9124.REF_FEED[WS_TEMP_VARIABLE.WS_I-1].FEE_RATE;
        }
        BPCSFECT.CHG_CCY = BPB9124_AWA_9124.CHG_CCY;
        BPCSFECT.CHG_AMT = BPB9124_AWA_9124.CHG_AMT;
        BPCSFECT.CHG_METH = BPB9124_AWA_9124.CHG_METH;
        BPCSFECT.CHG_ACNO = BPB9124_AWA_9124.CHG_ACNO;
        BPCSFECT.NOSTRO_CD = BPB9124_AWA_9124.NOSAC_CD;
        BPCSFECT.CHQ_NO = BPB9124_AWA_9124.CHQ_NO;
        BPCSFECT.GL_MST_BR = BPB9124_AWA_9124.GLMST_BR;
        BPCSFECT.GL_MST_HO = BPB9124_AWA_9124.GLMST_HO;
        BPCSFECT.GL_MST_IAS39 = BPB9124_AWA_9124.GLMST_IA;
        BPCSFECT.GL_MST_UNUS = BPB9124_AWA_9124.GLMST_UN;
        for (WS_TEMP_VARIABLE.WS_J = 1; WS_TEMP_VARIABLE.WS_J <= 5; WS_TEMP_VARIABLE.WS_J += 1) {
            BPCSFECT.TXN_OIC_DATA[WS_TEMP_VARIABLE.WS_J-1].TXN_OIC = BPB9124_AWA_9124.TXN_OICD[WS_TEMP_VARIABLE.WS_J-1].TXN_OIC;
            BPCSFECT.TXN_OIC_DATA[WS_TEMP_VARIABLE.WS_J-1].OIC_ACCT = BPB9124_AWA_9124.TXN_OICD[WS_TEMP_VARIABLE.WS_J-1].OIC_ACCT;
            BPCSFECT.TXN_OIC_DATA[WS_TEMP_VARIABLE.WS_J-1].PRFT_PCT = BPB9124_AWA_9124.TXN_OICD[WS_TEMP_VARIABLE.WS_J-1].PRFT_PCT;
        }
        BPCSFECT.CT_STS = BPB9124_AWA_9124.CT_STS;
        BPCSFECT.REMARK = BPB9124_AWA_9124.REMARK;
        BPCSFECT.FEE_BAS_AMT = BPB9124_AWA_9124.FEEB_AMT;
        BPCSFECT.CHG_CCY_REAL = BPB9124_AWA_9124.CHG_CCYR;
        BPCSFECT.CHG_AMT_REAL = BPB9124_AWA_9124.CHG_AMTR;
        BPCSFECT.TICKET = BPB9124_AWA_9124.TICKET;
        BPCSFECT.RATE = BPB9124_AWA_9124.RATE;
        BPCSFECT.EXG_DATE = BPB9124_AWA_9124.EXG_DATE;
        BPCSFECT.EXG_TIME = BPB9124_AWA_9124.EXG_TIME;
        BPCSFECT.MIN_AMT = BPB9124_AWA_9124.MIN_AMT;
        BPCSFECT.CP_NO = BPB9124_AWA_9124.CP_NO;
        BPCSFECT.SALE_DT = BPB9124_AWA_9124.SALE_DT;
        BPCSFECT.CCY_TYPE = BPB9124_AWA_9124.CCY_TYPE;
        BPCSFECT.CREV_NO = BPB9124_AWA_9124.CREV_NO;
    }
    public void S000_CALL_BPZSFECT() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-S-FECT-MAINT", BPCSFECT);
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, WS_TEMP_VARIABLE.WS_MSGID);
        CEP.ERR(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_FLD_NO);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
