package com.hisun.BP;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;

import java.io.IOException;
import java.sql.SQLException;

public class BPOT1290 {
    String WS_ERR_MSG = " ";
    short WS_FLD_NO = 0;
    BPCMSG_ERROR_MSG BPCMSG_ERROR_MSG = new BPCMSG_ERROR_MSG();
    SCCCALL SCCCALL = new SCCCALL();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCMSG SCCMSG = new SCCMSG();
    BPCSFEAG BPCSFEAG = new BPCSFEAG();
    SCCGWA SCCGWA;
    SCCGSCA_SC_AREA SCCGSCA_SC_AREA;
    SCCGBPA_BP_AREA SCCGBPA_BP_AREA;
    SCCGCPT SCCGCPT;
    SCCGMSG SCCGMSG;
    SCCAWAC SCCAWAC;
    BPB1290_AWA_1290 BPB1290_AWA_1290;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "BPOT1290 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        SCCGSCA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        SCCGBPA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        SCCGCPT = (SCCGCPT) SCCGSCA_SC_AREA.CMPT_AREA_PTR;
        SCCGMSG = (SCCGMSG) SCCGSCA_SC_AREA.MSG_AREA_PTR;
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "BPB1290_AWA_1290>");
        BPB1290_AWA_1290 = (BPB1290_AWA_1290) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        SCCAWAC = new SCCAWAC();
        IBS.init(SCCGWA, SCCAWAC);
        IBS.CPY2CLS(SCCGWA, SCCGWA.COMM_AREA.AWAC_AREA_PTR, SCCAWAC);
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B010_CHECK_INPUT();
        B020_ADD_RECORD();
    }
    public void B010_CHECK_INPUT() throws IOException,SQLException,Exception {
    }
    public void B020_ADD_RECORD() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCSFEAG);
        BPCSFEAG.PRDT_CODE = BPB1290_AWA_1290.PRDT_CD;
        BPCSFEAG.CLT_TYPE = BPB1290_AWA_1290.CLT_TYPE;
        BPCSFEAG.EFF_DATE = BPB1290_AWA_1290.EFF_DATE;
        BPCSFEAG.EXP_DATE = BPB1290_AWA_1290.EXP_DATE;
        BPCSFEAG.SGN_RNG = BPB1290_AWA_1290.SGN_RNG;
        BPCSFEAG.CCY = BPB1290_AWA_1290.CCY;
        BPCSFEAG.CAL_CYC = BPB1290_AWA_1290.CAL_CYC;
        BPCSFEAG.PERD_CNT = BPB1290_AWA_1290.PERD_CNT;
        BPCSFEAG.HOLI_MTH = BPB1290_AWA_1290.HOLI_MTH;
        CEP.TRC(SCCGWA, BPB1290_AWA_1290.HOLI_MTH);
        CEP.TRC(SCCGWA, BPCSFEAG.HOLI_MTH);
        BPCSFEAG.COMP_DATE = BPB1290_AWA_1290.COMP_DT;
        BPCSFEAG.REMARK = BPB1290_AWA_1290.REMARK;
        BPCSFEAG.FEE_CDS[1-1].FEE_CD = BPB1290_AWA_1290.FEE_CD1;
        BPCSFEAG.FEE_CDS[2-1].FEE_CD = BPB1290_AWA_1290.FEE_CD2;
        BPCSFEAG.FEE_CDS[3-1].FEE_CD = BPB1290_AWA_1290.FEE_CD3;
        BPCSFEAG.FEE_CDS[4-1].FEE_CD = BPB1290_AWA_1290.FEE_CD4;
        BPCSFEAG.FEE_CDS[5-1].FEE_CD = BPB1290_AWA_1290.FEE_CD5;
        BPCSFEAG.FEE_CDS[6-1].FEE_CD = BPB1290_AWA_1290.FEE_CD6;
        BPCSFEAG.FEE_CDS[7-1].FEE_CD = BPB1290_AWA_1290.FEE_CD7;
        BPCSFEAG.FEE_CDS[8-1].FEE_CD = BPB1290_AWA_1290.FEE_CD8;
        BPCSFEAG.FEE_CDS[9-1].FEE_CD = BPB1290_AWA_1290.FEE_CD9;
        BPCSFEAG.FEE_CDS[10-1].FEE_CD = BPB1290_AWA_1290.FEE_CD10;
        BPCSFEAG.FEE_CDS[11-1].FEE_CD = BPB1290_AWA_1290.FEE_CD11;
        BPCSFEAG.FEE_CDS[12-1].FEE_CD = BPB1290_AWA_1290.FEE_CD12;
        BPCSFEAG.FEE_CDS[13-1].FEE_CD = BPB1290_AWA_1290.FEE_CD13;
        BPCSFEAG.FEE_CDS[14-1].FEE_CD = BPB1290_AWA_1290.FEE_CD14;
        BPCSFEAG.FEE_CDS[15-1].FEE_CD = BPB1290_AWA_1290.FEE_CD15;
        BPCSFEAG.FEE_CDS[16-1].FEE_CD = BPB1290_AWA_1290.FEE_CD16;
        BPCSFEAG.FEE_CDS[17-1].FEE_CD = BPB1290_AWA_1290.FEE_CD17;
        BPCSFEAG.FEE_CDS[18-1].FEE_CD = BPB1290_AWA_1290.FEE_CD18;
        BPCSFEAG.FEE_CDS[19-1].FEE_CD = BPB1290_AWA_1290.FEE_CD19;
        BPCSFEAG.FEE_CDS[20-1].FEE_CD = BPB1290_AWA_1290.FEE_CD20;
        BPCSFEAG.FUNC = 'A';
        S000_CALL_BPZSFEAG();
    }
    public void S000_CALL_BPZSFEAG() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-MAINTAIN-BPTFEAG", BPCSFEAG);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
