package com.hisun.BP;

public class BPOT9127_WS_OUTPUT_DATA {
    BPOT9127_WS_CI_DATA WS_CI_DATA = new BPOT9127_WS_CI_DATA();
    BPOT9127_WS_PROD_DATA WS_PROD_DATA = new BPOT9127_WS_PROD_DATA();
    BPOT9127_WS_CCY_DATA WS_CCY_DATA = new BPOT9127_WS_CCY_DATA();
    BPOT9127_WS_CTRT_DATA WS_CTRT_DATA = new BPOT9127_WS_CTRT_DATA();
    String WS_ABBR_NAME = " ";
    String WS_PRODMO = " ";
    String WS_PROD_CD = " ";
}
