package com.hisun.BP;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;

import java.io.IOException;
import java.sql.SQLException;

public class BPOT4280 {
    char K_ERROR = 'E';
    String K_OUTPUT_FMT = "BP353";
    String CPN_BPTMLCJN_MAINTAIN = "BP-F-S-MANT-MLCJN  ";
    String WS_ERR_MSG = " ";
    short WS_FLD_NO = 0;
    short WS_CNT1 = 0;
    BPCMSG_ERROR_MSG BPCMSG_ERROR_MSG = new BPCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCFMT SCCFMT = new SCCFMT();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    BPCSMLCJ BPCSMLCJ = new BPCSMLCJ();
    BPRMLCJN BPRMLCJN = new BPRMLCJN();
    SCCGWA SCCGWA;
    BPB4280_AWA_4280 BPB4280_AWA_4280;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "BPOT4280 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "BPB4280_AWA_4280>");
        BPB4280_AWA_4280 = (BPB4280_AWA_4280) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        IBS.init(SCCGWA, BPCSMLCJ);
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B010_CHECK_INPUT();
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.CI_NO);
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.CI_TYP);
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.CI_NAME);
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.BRI_DT);
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.SEX);
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.COUNTRY);
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.IMP_SAN);
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.STOP_SAN);
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.LST_TYP);
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.MATCH);
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.TYPE);
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.REASON);
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.DIS_MTH);
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.REMARK);
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.BL_NAME);
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.BL_SEX);
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.BL_BDAY);
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.OP_FUNC);
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.NET_NM);
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.IDT_TYPE);
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.UPD_RES);
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.UPD_CNT);
        if (BPB4280_AWA_4280.OP_FUNC == 'A') {
            B020_CREATE_MLCJ_RECORD();
        }
        if (BPB4280_AWA_4280.OP_FUNC == 'U') {
            B030_UPDATE_MLCJ_RECORD();
        }
        if (BPB4280_AWA_4280.OP_FUNC == 'Q') {
            B030_QUERY_MLCJ_RECORD();
        }
    }
    public void B010_CHECK_INPUT() throws IOException,SQLException,Exception {
    }
    public void B020_CREATE_MLCJ_RECORD() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCSMLCJ);
        IBS.init(SCCGWA, BPRMLCJN);
        BPCSMLCJ.INFO.FUNC = 'A';
        BPCSMLCJ.INFO.OUTPUT_FMT = K_OUTPUT_FMT;
        R000_TRANS_DATA_PARAMETER();
    }
    public void B030_UPDATE_MLCJ_RECORD() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCSMLCJ);
        IBS.init(SCCGWA, BPRMLCJN);
        BPCSMLCJ.INFO.FUNC = 'U';
        BPCSMLCJ.INFO.OUTPUT_FMT = K_OUTPUT_FMT;
        R020_TRANS_DATA_PARAMETER();
    }
    public void B030_QUERY_MLCJ_RECORD() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCSMLCJ);
        IBS.init(SCCGWA, BPRMLCJN);
        BPCSMLCJ.INFO.FUNC = 'Q';
        BPCSMLCJ.INFO.OUTPUT_FMT = K_OUTPUT_FMT;
        R010_TRANS_DATA_PARAMETER();
    }
    public void R010_TRANS_DATA_PARAMETER() throws IOException,SQLException,Exception {
        BPRMLCJN.KEY.TR_DATE = BPB4280_AWA_4280.TR_DATE;
        BPRMLCJN.KEY.TR_JRNNO = BPB4280_AWA_4280.TR_JRNNO;
        BPCSMLCJ.INFO.POINTER = BPRMLCJN;
        BPCSMLCJ.INFO.LEN = 1429;
        S000_CALL_BPZSMLCJ();
    }
    public void R000_TRANS_DATA_PARAMETER() throws IOException,SQLException,Exception {
        BPRMLCJN.KEY.TR_DATE = SCCGWA.COMM_AREA.TR_DATE;
        BPRMLCJN.KEY.TR_JRNNO = SCCGWA.COMM_AREA.JRN_NO;
        BPRMLCJN.CI_NO = BPB4280_AWA_4280.CI_NO;
        BPRMLCJN.CI_TYP = BPB4280_AWA_4280.CI_TYP;
        BPRMLCJN.CI_NAME = BPB4280_AWA_4280.CI_NAME;
        BPRMLCJN.BIRTH_DAY = BPB4280_AWA_4280.BRI_DT;
        BPRMLCJN.SEX = BPB4280_AWA_4280.SEX;
        BPRMLCJN.COUNTRY = BPB4280_AWA_4280.COUNTRY;
        BPRMLCJN.IMP_SANCODE = BPB4280_AWA_4280.IMP_SAN;
        BPRMLCJN.STOP_SANCODE = BPB4280_AWA_4280.STOP_SAN;
        BPRMLCJN.LIST_TYPE = BPB4280_AWA_4280.LST_TYP;
        BPRMLCJN.MATCHING_SCOPE = BPB4280_AWA_4280.MATCH;
        BPRMLCJN.TYPE = BPB4280_AWA_4280.TYPE;
        BPRMLCJN.REASON = BPB4280_AWA_4280.REASON;
        BPRMLCJN.DIS_MTH = BPB4280_AWA_4280.DIS_MTH;
        BPRMLCJN.REMARK = BPB4280_AWA_4280.REMARK;
        BPRMLCJN.BLIST_NAME = BPB4280_AWA_4280.BL_NAME;
        BPRMLCJN.BLIST_SEX = BPB4280_AWA_4280.BL_SEX;
        BPRMLCJN.BLIST_BDAY = BPB4280_AWA_4280.BL_BDAY;
        BPRMLCJN.OP_FUNC = BPB4280_AWA_4280.OP_FUNC;
        BPRMLCJN.NET_NM = BPB4280_AWA_4280.NET_NM;
        BPRMLCJN.IDT_TYPE = BPB4280_AWA_4280.IDT_TYPE;
        BPRMLCJN.UPD_RES = BPB4280_AWA_4280.UPD_RES;
        BPRMLCJN.UPD_CNT = BPB4280_AWA_4280.UPD_CNT;
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.UPD_CNT);
        BPRMLCJN.TX_CODE = IBS.CLS2CPY(SCCGWA, SCCGWA.COMM_AREA.TR_ID);
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.UPD_CNT);
        BPRMLCJN.TX_TLR = SCCGWA.COMM_AREA.TL_ID;
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.UPD_CNT);
        BPRMLCJN.TR_TM = SCCGWA.COMM_AREA.TR_TIME;
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.UPD_CNT);
        BPCSMLCJ.INFO.POINTER = BPRMLCJN;
        BPCSMLCJ.INFO.LEN = 1429;
        S000_CALL_BPZSMLCJ();
    }
    public void R020_TRANS_DATA_PARAMETER() throws IOException,SQLException,Exception {
        BPRMLCJN.KEY.TR_DATE = BPB4280_AWA_4280.TR_DATE;
        BPRMLCJN.KEY.TR_JRNNO = BPB4280_AWA_4280.TR_JRNNO;
        BPRMLCJN.CI_NO = BPB4280_AWA_4280.CI_NO;
        BPRMLCJN.CI_TYP = BPB4280_AWA_4280.CI_TYP;
        BPRMLCJN.CI_NAME = BPB4280_AWA_4280.CI_NAME;
        BPRMLCJN.BIRTH_DAY = BPB4280_AWA_4280.BRI_DT;
        BPRMLCJN.SEX = BPB4280_AWA_4280.SEX;
        BPRMLCJN.COUNTRY = BPB4280_AWA_4280.COUNTRY;
        BPRMLCJN.IMP_SANCODE = BPB4280_AWA_4280.IMP_SAN;
        BPRMLCJN.STOP_SANCODE = BPB4280_AWA_4280.STOP_SAN;
        BPRMLCJN.LIST_TYPE = BPB4280_AWA_4280.LST_TYP;
        BPRMLCJN.MATCHING_SCOPE = BPB4280_AWA_4280.MATCH;
        BPRMLCJN.TYPE = BPB4280_AWA_4280.TYPE;
        BPRMLCJN.REASON = BPB4280_AWA_4280.REASON;
        BPRMLCJN.DIS_MTH = BPB4280_AWA_4280.DIS_MTH;
        BPRMLCJN.REMARK = BPB4280_AWA_4280.REMARK;
        BPRMLCJN.BLIST_NAME = BPB4280_AWA_4280.BL_NAME;
        BPRMLCJN.BLIST_SEX = BPB4280_AWA_4280.BL_SEX;
        BPRMLCJN.BLIST_BDAY = BPB4280_AWA_4280.BL_BDAY;
        BPRMLCJN.OP_FUNC = BPB4280_AWA_4280.OP_FUNC;
        BPRMLCJN.NET_NM = BPB4280_AWA_4280.NET_NM;
        BPRMLCJN.IDT_TYPE = BPB4280_AWA_4280.IDT_TYPE;
        BPRMLCJN.UPD_RES = BPB4280_AWA_4280.UPD_RES;
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.UPD_RES);
        CEP.TRC(SCCGWA, BPRMLCJN.UPD_RES);
        BPRMLCJN.UPD_CNT = BPB4280_AWA_4280.UPD_CNT;
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.UPD_CNT);
        BPRMLCJN.TX_CODE = IBS.CLS2CPY(SCCGWA, SCCGWA.COMM_AREA.TR_ID);
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.UPD_CNT);
        BPRMLCJN.TX_TLR = SCCGWA.COMM_AREA.TL_ID;
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.UPD_CNT);
        BPRMLCJN.TR_TM = SCCGWA.COMM_AREA.TR_TIME;
        CEP.TRC(SCCGWA, BPB4280_AWA_4280.UPD_CNT);
        BPCSMLCJ.INFO.POINTER = BPRMLCJN;
        BPCSMLCJ.INFO.LEN = 1429;
        S000_CALL_BPZSMLCJ();
    }
    public void S000_CALL_BPZSMLCJ() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, "11111");
        IBS.CALLCPN(SCCGWA, "BP-F-S-MANT-MLCJN", BPCSMLCJ);
        if (BPCSMLCJ.RC.RC_RTNCODE != 0) {
            WS_ERR_MSG = IBS.CLS2CPY(SCCGWA, BPCSMLCJ.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG, WS_FLD_NO);
    }
    public void S000_ERR_MSG_PROC_CONTINUE() throws IOException,SQLException,Exception {
        CEP.ERRC(SCCGWA, WS_ERR_MSG, WS_FLD_NO);
    }
    public void S000_ERR_MSG_PROC_LAST() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
