package com.hisun.BP;

import com.hisun.FX.*;
import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;

import java.io.IOException;
import java.sql.SQLException;

public class BPOT5901 {
    String CPN_S_BPPROD_DEF = "BP-S-MGM-BPPROD";
    String WS_ERR_MSG = " ";
    short WS_FLD_NO = 0;
    String WS_CONT_TYPE = " ";
    BPCMSG_ERROR_MSG BPCMSG_ERROR_MSG = new BPCMSG_ERROR_MSG();
    FXCMSG_ERROR_MSG FXCMSG_ERROR_MSG = new FXCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    BPCSPROD BPCSPROD = new BPCSPROD();
    SCCGWA SCCGWA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    BPB5900_AWA_5900 BPB5900_AWA_5900;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "BPOT5901 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "BPB5900_AWA_5900>");
        BPB5900_AWA_5900 = (BPB5900_AWA_5900) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B010_CHECK_INPUT();
        B020_ADD_REC_PROC();
    }
    public void B010_CHECK_INPUT() throws IOException,SQLException,Exception {
    }
    public void B020_ADD_REC_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCSPROD);
        BPCSPROD.KEY.PRD_TYPE = BPB5900_AWA_5900.PRD_TYPE;
        BPCSPROD.DATA_TXT.DESC = BPB5900_AWA_5900.DESC;
        BPCSPROD.DATA_TXT.CDESC = BPB5900_AWA_5900.CDESC;
        BPCSPROD.DATA_TXT.EFF_DATE = BPB5900_AWA_5900.EFF_DATE;
        BPCSPROD.DATA_TXT.EXP_DATE = BPB5900_AWA_5900.EXP_DATE;
        BPCSPROD.DATA_TXT.CONT_TYP = BPB5900_AWA_5900.CONT_TYP;
        BPCSPROD.DATA_TXT.ES_FLG = BPB5900_AWA_5900.ES_FLG;
        BPCSPROD.DATA_TXT.EX_TYPE = BPB5900_AWA_5900.EX_TYPE;
        BPCSPROD.DATA_TXT.TRD_TYP = BPB5900_AWA_5900.TRD_TYP;
        BPCSPROD.DATA_TXT.EX_GROUP = BPB5900_AWA_5900.EX_GROUP;
        BPCSPROD.DATA_TXT.SET_TYPE = BPB5900_AWA_5900.SET_TYPE;
        BPCSPROD.DATA_TXT.PART_FLG = BPB5900_AWA_5900.PART_FLG;
        BPCSPROD.DATA_TXT.UL_FLG = BPB5900_AWA_5900.UL_FLG;
        BPCSPROD.DATA_TXT.FAV_CODE1 = BPB5900_AWA_5900.FVCODE1;
        BPCSPROD.DATA_TXT.FAV_CODE2 = BPB5900_AWA_5900.FVCODE2;
        BPCSPROD.DATA_TXT.FAV_CODE3 = BPB5900_AWA_5900.FVCODE3;
        BPCSPROD.DATA_TXT.FAV_CODE4 = BPB5900_AWA_5900.FVCODE4;
        BPCSPROD.DATA_TXT.FAV_CODE5 = BPB5900_AWA_5900.FVCODE5;
        BPCSPROD.DATA_TXT.FAV_BUY = BPB5900_AWA_5900.FV_BUY;
        BPCSPROD.DATA_TXT.FAV_SELL = BPB5900_AWA_5900.FV_SELL;
        BPCSPROD.DATA_TXT.RMK = BPB5900_AWA_5900.RMK;
        BPCSPROD.FUNC = 'A';
        S000_CALL_BPZSPROD();
    }
    public void S000_CALL_BPZSPROD() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, CPN_S_BPPROD_DEF, BPCSPROD);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
