package com.hisun.BP;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;

import java.io.IOException;
import java.sql.SQLException;

public class BPOT8003 {
    char K_ERROR = 'E';
    String K_OUTPUT_FMT = "BP085";
    String CPN_RM_FEE_CON = "BP-F-S-RM-FEE-CON";
    String CPN_SET_TX_INF = "BP-F-F-TX-INFO";
    String WS_ERR_MSG = " ";
    short WS_FLD_NO = 0;
    short WS_CNT1 = 0;
    BPCMSG_ERROR_MSG BPCMSG_ERROR_MSG = new BPCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCFMT SCCFMT = new SCCFMT();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    BPCORTS1 BPCORTS1 = new BPCORTS1();
    BPCFFTXI BPCFFTXI = new BPCFFTXI();
    SCCGWA SCCGWA;
    BPB8003_AWA_8003 BPB8003_AWA_8003;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "BPOT8003 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "BPB8003_AWA_8003>");
        BPB8003_AWA_8003 = (BPB8003_AWA_8003) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.MSG_PROC_AREA.MSG_TYPE);
        B010_CHECK_INPUT();
        B015_SET_TX_CHG_INFO();
        B020_RM_FEE_CALCULATE();
    }
    public void B010_CHECK_INPUT() throws IOException,SQLException,Exception {
    }
    public void B015_SET_TX_CHG_INFO() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.MSG_PROC_AREA.MSG_TYPE);
        IBS.init(SCCGWA, BPCFFTXI);
        BPCFFTXI.TX_DATA.AUH_FLG = '0';
        BPCFFTXI.TX_DATA.CHG_AC_INFO.AC_TYP = '0';
        BPCFFTXI.TX_DATA.CHG_AC_INFO.CHG_AC = BPB8003_AWA_8003.CHG_AC;
        BPCFFTXI.TX_DATA.CHG_AC_INFO.CHG_CCY = BPB8003_AWA_8003.CHG_CCY;
        S000_CALL_BPZFFTXI();
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.MSG_PROC_AREA.MSG_TYPE);
    }
    public void B020_RM_FEE_CALCULATE() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.MSG_PROC_AREA.MSG_TYPE);
        IBS.init(SCCGWA, BPCORTS1);
        BPCORTS1.OUTPUT_FMT = K_OUTPUT_FMT;
        BPCORTS1.DATA.REMT_CCY = BPB8003_AWA_8003.REMT_CCY;
        CEP.TRC(SCCGWA, BPB8003_AWA_8003.REMT_CCY);
        BPCORTS1.DATA.REMT_AMT = BPB8003_AWA_8003.REMT_AMT;
        CEP.TRC(SCCGWA, BPB8003_AWA_8003.REMT_AMT);
        BPCORTS1.DATA.PAY_CCY = BPB8003_AWA_8003.PAY_CCY1;
        CEP.TRC(SCCGWA, BPB8003_AWA_8003.PAY_CCY1);
        BPCORTS1.DATA.SEL_RAT1 = BPB8003_AWA_8003.SEL_RAT1;
        CEP.TRC(SCCGWA, BPB8003_AWA_8003.SEL_RAT1);
        CEP.TRC(SCCGWA, "CHECK 1");
        BPCORTS1.DATA.TC_NO1 = BPB8003_AWA_8003.TC_NO1;
        BPCORTS1.DATA.BIC_NO1 = BPB8003_AWA_8003.BIC_NO1;
        BPCORTS1.DATA.AC_NO1 = BPB8003_AWA_8003.AC_NO1;
        CEP.TRC(SCCGWA, BPB8003_AWA_8003.TC_NO1);
        CEP.TRC(SCCGWA, BPB8003_AWA_8003.BIC_NO1);
        CEP.TRC(SCCGWA, BPB8003_AWA_8003.AC_NO1);
        BPCORTS1.DATA.AC_AMT1 = BPB8003_AWA_8003.AC_AMT1;
        BPCORTS1.DATA.CASH_AMT = BPB8003_AWA_8003.CASH_AMT;
        BPCORTS1.DATA.TRF_AMT = BPB8003_AWA_8003.TRF_AMT;
        BPCORTS1.DATA.PAY_CCY2 = BPB8003_AWA_8003.PAY_CCY2;
        CEP.TRC(SCCGWA, BPB8003_AWA_8003.PAY_CCY2);
        BPCORTS1.DATA.SEL_RAT2 = BPB8003_AWA_8003.SEL_RAT2;
        BPCORTS1.DATA.TC_NO2 = BPB8003_AWA_8003.TC_NO2;
        BPCORTS1.DATA.AC_AMT2 = BPB8003_AWA_8003.AC_AMT2;
        CEP.TRC(SCCGWA, BPB8003_AWA_8003.AC_AMT2);
        BPCORTS1.DATA.OTH_METH = BPB8003_AWA_8003.OTH_METH;
        CEP.TRC(SCCGWA, "CHECK 2");
        CEP.TRC(SCCGWA, BPB8003_AWA_8003.CHG_CCY);
        BPCORTS1.DATA.CHG_CCY = BPB8003_AWA_8003.CHG_CCY;
        BPCORTS1.DATA.COM_USD = BPB8003_AWA_8003.COM_USD;
        BPCORTS1.DATA.COM_PAY = BPB8003_AWA_8003.COM_PAY;
        BPCORTS1.DATA.COR_USD = BPB8003_AWA_8003.COR_USD;
        BPCORTS1.DATA.COR_PAY = BPB8003_AWA_8003.COR_PAY;
        BPCORTS1.DATA.LIE_USD = BPB8003_AWA_8003.LIE_USD;
        BPCORTS1.DATA.LIE_PAY = BPB8003_AWA_8003.LIE_PAY;
        BPCORTS1.DATA.CAB_USD = BPB8003_AWA_8003.CAB_USD;
        BPCORTS1.DATA.CAB_PAY = BPB8003_AWA_8003.CAB_PAY;
        BPCORTS1.DATA.OTH_USD = BPB8003_AWA_8003.OTH_USD;
        BPCORTS1.DATA.OTH_PAY = BPB8003_AWA_8003.OTH_PAY;
        BPCORTS1.DATA.CHG_AC = BPB8003_AWA_8003.CHG_AC;
        CEP.TRC(SCCGWA, BPB8003_AWA_8003.CHG_AC);
        BPCORTS1.DATA.C_AC_AMT = BPB8003_AWA_8003.C_AC_AMT;
        BPCORTS1.DATA.C_CS_AMT = BPB8003_AWA_8003.C_CS_AMT;
        BPCORTS1.DATA.C_TR_AMT = BPB8003_AWA_8003.C_TR_AMT;
        BPCORTS1.DATA.SEND_MSG = BPB8003_AWA_8003.SEND_MSG;
        BPCORTS1.DATA.DER_CODE = BPB8003_AWA_8003.DER_CODE;
        CEP.TRC(SCCGWA, BPB8003_AWA_8003.DER_CODE);
        CEP.TRC(SCCGWA, "CHECK 3");
        for (WS_CNT1 = 1; WS_CNT1 <= 20; WS_CNT1 += 1) {
            CEP.TRC(SCCGWA, WS_CNT1);
            CEP.TRC(SCCGWA, BPB8003_AWA_8003.FEE_INFO[WS_CNT1-1].FEE_CODE);
            if (BPB8003_AWA_8003.FEE_INFO[WS_CNT1-1].FEE_CODE.trim().length() > 0 
                && BPB8003_AWA_8003.FEE_INFO[WS_CNT1-1].FEE_CODE.charAt(0) != 0X00) {
                BPCORTS1.DATA.FEE_INFO[WS_CNT1-1].FEE_CODE = BPB8003_AWA_8003.FEE_INFO[WS_CNT1-1].FEE_CODE;
                BPCORTS1.DATA.FEE_INFO[WS_CNT1-1].FEE_CCY = BPB8003_AWA_8003.FEE_INFO[WS_CNT1-1].FEE_CCY;
                BPCORTS1.DATA.FEE_INFO[WS_CNT1-1].FEE_BAS = BPB8003_AWA_8003.FEE_INFO[WS_CNT1-1].FEE_BAS;
                BPCORTS1.DATA.FEE_INFO[WS_CNT1-1].FEE_AMT = BPB8003_AWA_8003.FEE_INFO[WS_CNT1-1].FEE_AMT;
                BPCORTS1.DATA.FEE_INFO[WS_CNT1-1].CHG_BAS = BPB8003_AWA_8003.FEE_INFO[WS_CNT1-1].F_C_BAS;
                BPCORTS1.DATA.FEE_INFO[WS_CNT1-1].CHG_AMT = BPB8003_AWA_8003.FEE_INFO[WS_CNT1-1].F_C_AMT;
                BPCORTS1.DATA.FEE_INFO[WS_CNT1-1].ADJ_AMT = BPB8003_AWA_8003.FEE_INFO[WS_CNT1-1].F_A_AMT;
                BPCORTS1.DATA.FEE_INFO[WS_CNT1-1].DER_LIMIT = BPB8003_AWA_8003.FEE_INFO[WS_CNT1-1].F_D_AMT;
                BPCORTS1.DATA.FEE_INFO[WS_CNT1-1].DER_AUTH = BPB8003_AWA_8003.FEE_INFO[WS_CNT1-1].F_D_AUH;
                CEP.TRC(SCCGWA, "CHECK 4");
            }
        }
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.MSG_PROC_AREA.MSG_TYPE);
        CEP.TRC(SCCGWA, "CHECK 5");
        S000_CALL_BPZFRTS1();
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.MSG_PROC_AREA.MSG_TYPE);
    }
    public void S000_CALL_BPZFRTS1() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, CPN_RM_FEE_CON, BPCORTS1);
    }
    public void S000_CALL_BPZFSCHG() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, CPN_RM_FEE_CON, BPCORTS1);
    }
    public void S000_CALL_BPZFFTXI() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, CPN_SET_TX_INF, BPCFFTXI);
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG, WS_FLD_NO);
    }
    public void S000_ERR_MSG_PROC_CONTINUE() throws IOException,SQLException,Exception {
        CEP.ERRC(SCCGWA, WS_ERR_MSG, WS_FLD_NO);
    }
    public void S000_ERR_MSG_PROC_LAST() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
