package com.hisun.BP;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;

import java.io.IOException;
import java.sql.SQLException;

public class BPOT9123 {
    String JIBS_tmp_str[] = new String[10];
    BPOT9123_WS_TEMP_VARIABLE WS_TEMP_VARIABLE = new BPOT9123_WS_TEMP_VARIABLE();
    char WS_SEQ_FLG = ' ';
    BPCMSG_ERROR_MSG BPCMSG_ERROR_MSG = new BPCMSG_ERROR_MSG();
    SCCMSG SCCMSG = new SCCMSG();
    SCCCALL SCCCALL = new SCCCALL();
    BPCSFECT BPCSFECT = new BPCSFECT();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCGWA SCCGWA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    BPCPORUP_DATA_INFO BPCPORUP;
    BPB9123_AWA_9123 BPB9123_AWA_9123;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "BPOT9123 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "BPB9123_AWA_9123>");
        BPB9123_AWA_9123 = (BPB9123_AWA_9123) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        BPCPORUP = (BPCPORUP_DATA_INFO) SCCGWA.COMM_AREA.TR_BR_PTR;
        IBS.init(SCCGWA, WS_TEMP_VARIABLE);
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B100_CHECK_INPUT();
        B200_UPD_FEE_CNTR_PROC();
    }
    public void B100_CHECK_INPUT() throws IOException,SQLException,Exception {
    }
    public void B200_UPD_FEE_CNTR_PROC() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.CTNO);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.FEE_DESC);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.CINO);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.CI_CNM);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.CT_TYP);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.FEE_TYP);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.BOOK_BR);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.PRDT_TYP);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.START_DT);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.END_DT);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.HOL_OVR);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.CAL_CD1);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.HOL_METH);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.CAL_CD2);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.PAY_IND);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.CSH_FLW);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.BK_PFLO);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.PAY_METH);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.ACU_TYP);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.FEE_METH);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.TXN_CCY);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.RLT_CTNO);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.RLT_CTYP);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.AMT_TYP);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.RLT_PTYP);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.FBAS_CNT);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.AGGR_TYP);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.REF_CCY);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.REF_METH);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.CHG_CCY);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.CHG_METH);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.CHG_ACNO);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.NOSAC_CD);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.CHQ_NO);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.GLMST_BR);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.GLMST_HO);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.GLMST_IA);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.GLMST_UN);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.CT_STS);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.REMARK);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.TXN_OICD[1-1].TXN_OIC);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.TXN_OICD[1-1].OIC_ACCT);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.TXN_OICD[2-1].TXN_OIC);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.TXN_OICD[2-1].OIC_ACCT);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.TXN_OICD[3-1].TXN_OIC);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.TXN_OICD[3-1].OIC_ACCT);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.CP_NO);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.SALE_DT);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.CCY_TYPE);
        CEP.TRC(SCCGWA, BPB9123_AWA_9123.CREV_NO);
        IBS.init(SCCGWA, BPCSFECT);
        BPCSFECT.FUNC_CODE = 'U';
        R000_MOVE_DATA();
        S000_CALL_BPZSFECT();
    }
    public void R000_MOVE_DATA() throws IOException,SQLException,Exception {
        BPCSFECT.CTNO = BPB9123_AWA_9123.CTNO;
        BPCSFECT.FEE_DESC = BPB9123_AWA_9123.FEE_DESC;
        BPCSFECT.CINO = BPB9123_AWA_9123.CINO;
        BPCSFECT.CI_ABBR_NM = BPB9123_AWA_9123.CI_CNM;
        BPCSFECT.CT_TYP = BPB9123_AWA_9123.CT_TYP;
        BPCSFECT.FEE_TYP = BPB9123_AWA_9123.FEE_TYP;
        BPCSFECT.BOOK_ACCT = BPB9123_AWA_9123.BOOK_BR;
        BPCSFECT.PRDT_TYP = BPB9123_AWA_9123.PRDT_TYP;
        BPCSFECT.START_DT = BPB9123_AWA_9123.START_DT;
        BPCSFECT.MATURITY_DT = BPB9123_AWA_9123.END_DT;
        BPCSFECT.HOL_OVR = BPB9123_AWA_9123.HOL_OVR;
        BPCSFECT.CAL_CD1 = BPB9123_AWA_9123.CAL_CD1;
        BPCSFECT.CAL_CD2 = BPB9123_AWA_9123.CAL_CD2;
        BPCSFECT.HOL_METH = BPB9123_AWA_9123.HOL_METH;
        BPCSFECT.PAY_IND = BPB9123_AWA_9123.PAY_IND;
        BPCSFECT.CSH_FLW_IND = BPB9123_AWA_9123.CSH_FLW;
        BPCSFECT.BK_PFLO = BPB9123_AWA_9123.BK_PFLO;
        BPCSFECT.PAY_METH = BPB9123_AWA_9123.PAY_METH;
        BPCSFECT.ACU_TYP = BPB9123_AWA_9123.ACU_TYP;
        BPCSFECT.TXN_CCY = BPB9123_AWA_9123.TXN_CCY;
        BPCSFECT.TXN_AMT = BPB9123_AWA_9123.TXN_AMT;
        BPCSFECT.RLTD_CTNO = BPB9123_AWA_9123.RLT_CTNO;
        BPCSFECT.RLTD_CT_TYP = BPB9123_AWA_9123.RLT_CTYP;
        BPCSFECT.AMT_TYP = BPB9123_AWA_9123.AMT_TYP;
        BPCSFECT.RLTD_PRDT_TYP = BPB9123_AWA_9123.RLT_PTYP;
        BPCSFECT.AMT_PCT = BPB9123_AWA_9123.AMT_PCT;
        BPCSFECT.INT_BASIC = BPB9123_AWA_9123.FBAS_CNT;
        BPCSFECT.AGGR_TYP = BPB9123_AWA_9123.AGGR_TYP;
        BPCSFECT.REF_CCY = BPB9123_AWA_9123.REF_CCY;
        BPCSFECT.REF_METH = BPB9123_AWA_9123.REF_METH;
        for (WS_TEMP_VARIABLE.WS_I = 1; WS_TEMP_VARIABLE.WS_I <= 5; WS_TEMP_VARIABLE.WS_I += 1) {
            BPCSFECT.REF_FEE_DATA[WS_TEMP_VARIABLE.WS_I-1].REF_AMT = BPB9123_AWA_9123.REF_FEED[WS_TEMP_VARIABLE.WS_I-1].REF_AMT;
            BPCSFECT.REF_FEE_DATA[WS_TEMP_VARIABLE.WS_I-1].REF_PCT = BPB9123_AWA_9123.REF_FEED[WS_TEMP_VARIABLE.WS_I-1].REF_PCT;
            BPCSFECT.REF_FEE_DATA[WS_TEMP_VARIABLE.WS_I-1].AGG_MTH = BPB9123_AWA_9123.REF_FEED[WS_TEMP_VARIABLE.WS_I-1].AGG_MTH;
            BPCSFECT.REF_FEE_DATA[WS_TEMP_VARIABLE.WS_I-1].FEE_AMT = BPB9123_AWA_9123.REF_FEED[WS_TEMP_VARIABLE.WS_I-1].FEE_AMT;
            BPCSFECT.REF_FEE_DATA[WS_TEMP_VARIABLE.WS_I-1].FEE_RATE = BPB9123_AWA_9123.REF_FEED[WS_TEMP_VARIABLE.WS_I-1].FEE_RATE;
        }
        BPCSFECT.CHG_CCY = BPB9123_AWA_9123.CHG_CCY;
        BPCSFECT.CHG_AMT = BPB9123_AWA_9123.CHG_AMT;
        BPCSFECT.CHG_METH = BPB9123_AWA_9123.CHG_METH;
        BPCSFECT.CHG_ACNO = BPB9123_AWA_9123.CHG_ACNO;
        BPCSFECT.CHQ_NO = BPB9123_AWA_9123.CHQ_NO;
        BPCSFECT.GL_MST_BR = BPB9123_AWA_9123.GLMST_BR;
        BPCSFECT.GL_MST_HO = BPB9123_AWA_9123.GLMST_HO;
        BPCSFECT.GL_MST_IAS39 = BPB9123_AWA_9123.GLMST_IA;
        BPCSFECT.GL_MST_UNUS = BPB9123_AWA_9123.GLMST_UN;
        for (WS_TEMP_VARIABLE.WS_J = 1; WS_TEMP_VARIABLE.WS_J <= 5; WS_TEMP_VARIABLE.WS_J += 1) {
            BPCSFECT.TXN_OIC_DATA[WS_TEMP_VARIABLE.WS_J-1].TXN_OIC = BPB9123_AWA_9123.TXN_OICD[WS_TEMP_VARIABLE.WS_J-1].TXN_OIC;
            BPCSFECT.TXN_OIC_DATA[WS_TEMP_VARIABLE.WS_J-1].OIC_ACCT = BPB9123_AWA_9123.TXN_OICD[WS_TEMP_VARIABLE.WS_J-1].OIC_ACCT;
            CEP.TRC(SCCGWA, "BBBBBBBBB");
            CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[WS_TEMP_VARIABLE.WS_J-1].PRFT_PCT);
            BPCSFECT.TXN_OIC_DATA[WS_TEMP_VARIABLE.WS_J-1].PRFT_PCT = BPB9123_AWA_9123.TXN_OICD[WS_TEMP_VARIABLE.WS_J-1].PRFT_PCT;
            CEP.TRC(SCCGWA, "AAAAAAAAA");
            CEP.TRC(SCCGWA, BPCSFECT.TXN_OIC_DATA[WS_TEMP_VARIABLE.WS_J-1].PRFT_PCT);
        }
        if (BPCSFECT.PAY_METH == 'P') {
            if (BPCSFECT.START_DT > SCCGWA.COMM_AREA.AC_DATE) {
                CEP.TRC(SCCGWA, "FEE CONTRACT STATUS:UNSETTLE");
                BPCSFECT.CT_STS = '0';
            } else {
                if (BPCSFECT.MATURITY_DT != BPCSFECT.START_DT) {
                    CEP.TRC(SCCGWA, "FEE CONTRACT STATUS:SETTLED");
                    BPCSFECT.CT_STS = '1';
                } else {
                    CEP.TRC(SCCGWA, "FEE CONTRACT STATUS:COMPLETE");
                    BPCSFECT.CT_STS = '2';
                }
            }
        } else {
            BPCSFECT.CT_STS = '0';
        }
        if (BPB9123_AWA_9123.CHG_METH == '1') {
            BPCSFECT.CHG_FLG = 'N';
            BPCSFECT.CT_STS = '1';
        } else {
            BPCSFECT.CHG_FLG = 'Y';
        }
        BPCSFECT.REMARK = BPB9123_AWA_9123.REMARK;
        BPCSFECT.FEE_BAS_AMT = BPB9123_AWA_9123.FEEB_AMT;
        BPCSFECT.CHG_CCY_REAL = BPB9123_AWA_9123.CHG_CCY;
        BPCSFECT.CHG_AMT_REAL = BPB9123_AWA_9123.CHG_AMT;
        BPCSFECT.TICKET = BPB9123_AWA_9123.TICKET;
        BPCSFECT.RATE = BPB9123_AWA_9123.RATE;
        BPCSFECT.EXG_DATE = BPB9123_AWA_9123.EXG_DATE;
        BPCSFECT.EXG_TIME = BPB9123_AWA_9123.EXG_TIME;
        BPCSFECT.MIN_AMT = BPB9123_AWA_9123.MIN_AMT;
        BPCSFECT.CP_NO = BPB9123_AWA_9123.CP_NO;
        BPCSFECT.SALE_DT = BPB9123_AWA_9123.SALE_DT;
        BPCSFECT.CCY_TYPE = BPB9123_AWA_9123.CCY_TYPE;
        BPCSFECT.CREV_NO = BPB9123_AWA_9123.CREV_NO;
    }
    public void S000_CALL_BPZSFECT() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-S-FECT-MAINT", BPCSFECT);
    }
    public void S000_ERR_MSG_PROC_CONTINUE() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, WS_TEMP_VARIABLE.WS_ERR_MSG);
        CEP.ERRC(SCCGWA, WS_TEMP_VARIABLE.WS_ERR_MSG, WS_TEMP_VARIABLE.WS_FLD_NO);
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, WS_TEMP_VARIABLE.WS_MSGID);
        CEP.ERR(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_FLD_NO);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
