package com.hisun.BP;

public class BPRFEAG {
    public BPRFEAG_KEY KEY = new BPRFEAG_KEY();
    public int EXP_DATE = 0;
    public String CHG_AC = " ";
    public String CCY = " ";
    public char CLT_RANGE = ' ';
    public char CAL_CYCLE = ' ';
    public short PERIDO_CNT = 0;
    public int FIRST_CHG_DATE = 0;
    public int LATELY_CHG_DATE = 0;
    public int NEXT_CHG_DATE = 0;
    public char HOLI_METHOD = ' ';
    public int FEE_COMP_DATE = 0;
    public String HLD_NO = " ";
    public String FEE_CODE1 = " ";
    public String FEE_CODE2 = " ";
    public String FEE_CODE3 = " ";
    public String FEE_CODE4 = " ";
    public String FEE_CODE5 = " ";
    public String FEE_CODE6 = " ";
    public String FEE_CODE7 = " ";
    public String FEE_CODE8 = " ";
    public String FEE_CODE9 = " ";
    public String FEE_CODE10 = " ";
    public String FEE_CODE11 = " ";
    public String FEE_CODE12 = " ";
    public String FEE_CODE13 = " ";
    public String FEE_CODE14 = " ";
    public String FEE_CODE15 = " ";
    public String FEE_CODE16 = " ";
    public String FEE_CODE17 = " ";
    public String FEE_CODE18 = " ";
    public String FEE_CODE19 = " ";
    public String FEE_CODE20 = " ";
    public String REMARK = " ";
    public int CREATE_DATE = 0;
    public int CREATE_TIME = 0;
    public String CREATE_TELL = " ";
    public String LAST_TELL = " ";
    public String SUP_TEL1 = " ";
    public String SUP_TEL2 = " ";
    public String TS = " ";
}
