package com.hisun.BP;

import com.hisun.SC.*;
import com.hisun.CI.*;

import java.io.IOException;
import java.sql.SQLException;

public class BPZGFAVD {
    int JIBS_tmp_int;
    String JIBS_tmp_str[] = new String[10];
    boolean pgmRtn = false;
    String PGM_BPZGFAVD = "BPZGFAVD";
    String TBL_BPTEXFAV = "BPTEXFAV";
    String CPN_BP_FAVM = "BP-FAVM ";
    int WS_REC_LEN = 0;
    String WS_ERR_MSG = " ";
    short WS_FLD_NO = 0;
    short WS_I = 0;
    String WS_GRPS_NO = " ";
    BPCMSG_ERROR_MSG BPCMSG_ERROR_MSG = new BPCMSG_ERROR_MSG();
    SCCCALL SCCCALL = new SCCCALL();
    SCCEXCP SCCEXCP = new SCCEXCP();
    BPCRFAVM BPCRFAVM = new BPCRFAVM();
    SCCMSG SCCMSG = new SCCMSG();
    CICSGRS CICSGRS = new CICSGRS();
    CICCUST CICCUST = new CICCUST();
    BPREXFAV BPREXFAV = new BPREXFAV();
    SCCGWA SCCGWA;
    String LK_REC = " ";
    BPCGFAV BPCGFAV;
    public void MP(SCCGWA SCCGWA, BPCGFAV BPCGFAV) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        this.BPCGFAV = BPCGFAV;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        if (pgmRtn) return;
        B000_MAIN_PROC();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, "BPZGFAVD return!");
        Z_RET();
        if (pgmRtn) return;
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B001_CHECK_PROC();
        if (pgmRtn) return;
        B002_MAIN_PROC();
        if (pgmRtn) return;
    }
    public void B002_MAIN_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPREXFAV);
        IBS.init(SCCGWA, BPCRFAVM);
        if (BPREXFAV.KEY.FAV_CODE == null) BPREXFAV.KEY.FAV_CODE = "";
        JIBS_tmp_int = BPREXFAV.KEY.FAV_CODE.length();
        for (int i=0;i<5-JIBS_tmp_int;i++) BPREXFAV.KEY.FAV_CODE += " ";
        JIBS_tmp_str[0] = "" + BPCGFAV.INFO.FAV_TYP;
        JIBS_tmp_int = JIBS_tmp_str[0].length();
        for (int i=0;i<1-JIBS_tmp_int;i++) JIBS_tmp_str[0] = "0"+JIBS_tmp_str[0];
        BPREXFAV.KEY.FAV_CODE = JIBS_tmp_str[0] + BPREXFAV.KEY.FAV_CODE.substring(1);
        if (BPREXFAV.KEY.FAV_CODE == null) BPREXFAV.KEY.FAV_CODE = "";
        JIBS_tmp_int = BPREXFAV.KEY.FAV_CODE.length();
        for (int i=0;i<5-JIBS_tmp_int;i++) BPREXFAV.KEY.FAV_CODE += " ";
        JIBS_tmp_str[0] = "" + BPCGFAV.INFO.SEQ;
        JIBS_tmp_int = JIBS_tmp_str[0].length();
        for (int i=0;i<4-JIBS_tmp_int;i++) JIBS_tmp_str[0] = "0"+JIBS_tmp_str[0];
        BPREXFAV.KEY.FAV_CODE = BPREXFAV.KEY.FAV_CODE.substring(0, 2 - 1) + JIBS_tmp_str[0] + BPREXFAV.KEY.FAV_CODE.substring(2 + 4 - 1);
        BPREXFAV.EFF_DATE = BPCGFAV.INFO.EFF_DATE;
        BPREXFAV.EXP_DATE = BPCGFAV.INFO.EXP_DATE;
        BPREXFAV.KEY.CCY = BPCGFAV.INFO.CCY;
        BPREXFAV.FAV_TYPE = BPCGFAV.INFO.FAV_TYPE;
        CEP.TRC(SCCGWA, BPREXFAV.KEY.CCY);
        BPCRFAVM.INFO.FUNC = 'Q';
        BPCRFAVM.INFO.LEN = 2915;
        BPCRFAVM.INFO.POINTER = BPREXFAV;
        IBS.CALLCPN(SCCGWA, CPN_BP_FAVM, BPCRFAVM);
        if (BPCRFAVM.RETURN_INFO == 'F'
            || BPCRFAVM.RETURN_INFO == 'N') {
        } else {
            WS_ERR_MSG = IBS.CLS2CPY(SCCGWA, BPCRFAVM.RC);
            Z_RET();
            if (pgmRtn) return;
        }
        CEP.TRC(SCCGWA, BPREXFAV);
        CEP.TRC(SCCGWA, BPREXFAV.CSBUY_SP01);
        CEP.TRC(SCCGWA, BPREXFAV.CSSELL_SP01);
        CEP.TRC(SCCGWA, BPREXFAV.FXBUY_SP01);
        CEP.TRC(SCCGWA, BPREXFAV.FXSELL_SP01);
        CEP.TRC(SCCGWA, BPREXFAV.EFF_DATE);
        CEP.TRC(SCCGWA, BPREXFAV.EXP_DATE);
        if (BPREXFAV.EFF_DATE > SCCGWA.COMM_AREA.AC_DATE 
            || BPREXFAV.EXP_DATE < SCCGWA.COMM_AREA.AC_DATE) {
            BPREXFAV.CSBUY_SP01 = 0;
            BPREXFAV.CSSELL_SP01 = 0;
            BPREXFAV.FXBUY_SP01 = 0;
            BPREXFAV.FXSELL_SP01 = 0;
            BPREXFAV.CSBUY_SP02 = 0;
            BPREXFAV.CSSELL_SP02 = 0;
            BPREXFAV.FXBUY_SP02 = 0;
            BPREXFAV.FXSELL_SP02 = 0;
            BPREXFAV.CSBUY_SP03 = 0;
            BPREXFAV.CSSELL_SP03 = 0;
            BPREXFAV.FXBUY_SP03 = 0;
            BPREXFAV.FXSELL_SP03 = 0;
            BPREXFAV.CSBUY_SP04 = 0;
            BPREXFAV.CSSELL_SP04 = 0;
            BPREXFAV.FXBUY_SP04 = 0;
            BPREXFAV.FXSELL_SP04 = 0;
            BPREXFAV.CSBUY_SP05 = 0;
            BPREXFAV.CSSELL_SP05 = 0;
            BPREXFAV.FXBUY_SP05 = 0;
            BPREXFAV.FXSELL_SP05 = 0;
            BPREXFAV.CSBUY_SP06 = 0;
            BPREXFAV.CSSELL_SP06 = 0;
            BPREXFAV.FXBUY_SP06 = 0;
            BPREXFAV.FXSELL_SP06 = 0;
            BPREXFAV.CSBUY_SP07 = 0;
            BPREXFAV.CSSELL_SP07 = 0;
            BPREXFAV.FXBUY_SP07 = 0;
            BPREXFAV.FXSELL_SP07 = 0;
            BPREXFAV.CSBUY_SP08 = 0;
            BPREXFAV.CSSELL_SP08 = 0;
            BPREXFAV.FXBUY_SP08 = 0;
            BPREXFAV.FXSELL_SP08 = 0;
            BPREXFAV.CSBUY_SP09 = 0;
            BPREXFAV.CSSELL_SP09 = 0;
            BPREXFAV.FXBUY_SP09 = 0;
            BPREXFAV.FXSELL_SP09 = 0;
            BPREXFAV.CSBUY_SP10 = 0;
            BPREXFAV.CSSELL_SP10 = 0;
            BPREXFAV.FXBUY_SP10 = 0;
            BPREXFAV.FXSELL_SP10 = 0;
        }
        if (BPCRFAVM.RETURN_INFO == 'F') {
            CEP.TRC(SCCGWA, BPREXFAV.FAV_TYPE);
            CEP.TRC(SCCGWA, BPCGFAV.INFO.CI_NO);
            BPCGFAV.INFO.CAL_MTH = BPREXFAV.CAL_MTH;
            if (BPREXFAV.FAV_TYPE.equalsIgnoreCase("1")) {
                if (BPCGFAV.INFO.STR_AMT != 0) {
                    B002_01_COMPARE_AMT();
                    if (pgmRtn) return;
                    BPCGFAV.INFO.EXEC_FLG = 'Y';
                } else {
                    BPCGFAV.INFO.EXEC_FLG = 'N';
                }
            } else if (BPREXFAV.FAV_TYPE.equalsIgnoreCase("2")) {
                if (BPCGFAV.INFO.CI_NO.trim().length() > 0) {
                    B002_02_COMPARE_AC_TYP();
                    if (pgmRtn) return;
                    BPCGFAV.INFO.EXEC_FLG = 'Y';
                } else {
                    BPCGFAV.INFO.EXEC_FLG = 'N';
                }
            } else if (BPREXFAV.FAV_TYPE.equalsIgnoreCase("3")) {
                if (BPCGFAV.INFO.CI_NO.trim().length() > 0) {
                    B002_03_COMPARE_GRP_NO();
                    if (pgmRtn) return;
                    BPCGFAV.INFO.EXEC_FLG = 'Y';
                } else {
                    BPCGFAV.INFO.EXEC_FLG = 'N';
                }
            } else if (BPREXFAV.FAV_TYPE.equalsIgnoreCase("4")) {
                CEP.TRC(SCCGWA, BPCGFAV.INFO.CHNL_NO);
                if (BPCGFAV.INFO.CHNL_NO.trim().length() > 0) {
                    B002_04_COMPARE_CHNL_NO();
                    if (pgmRtn) return;
                    BPCGFAV.INFO.EXEC_FLG = 'Y';
                } else {
                    BPCGFAV.INFO.EXEC_FLG = 'N';
                }
            }
        } else {
            BPCGFAV.INFO.EXEC_FLG = 'N';
            BPCGFAV.INFO.CSBUY_SP01 = 0;
            BPCGFAV.INFO.CSSELL_SP01 = 0;
            BPCGFAV.INFO.FXBUY_SP01 = 0;
            BPCGFAV.INFO.FXSELL_SP01 = 0;
        }
    }
    public void B002_01_COMPARE_AMT() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, BPREXFAV.STR_AMT01);
        CEP.TRC(SCCGWA, BPREXFAV.STR_AMT02);
        CEP.TRC(SCCGWA, BPREXFAV.STR_AMT03);
        CEP.TRC(SCCGWA, BPREXFAV.STR_AMT04);
        CEP.TRC(SCCGWA, BPREXFAV.STR_AMT05);
        CEP.TRC(SCCGWA, BPREXFAV.STR_AMT06);
        CEP.TRC(SCCGWA, BPREXFAV.STR_AMT07);
        CEP.TRC(SCCGWA, BPREXFAV.STR_AMT08);
        CEP.TRC(SCCGWA, BPREXFAV.STR_AMT09);
        CEP.TRC(SCCGWA, BPREXFAV.STR_AMT10);
        if (BPCGFAV.INFO.STR_AMT >= BPREXFAV.STR_AMT01 
            && BPREXFAV.STR_AMT01 != 0) {
            CEP.TRC(SCCGWA, BPCGFAV.INFO.STR_AMT);
            CEP.TRC(SCCGWA, BPREXFAV.STR_AMT01);
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP01;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP01;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP01;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP01;
        }
        if (BPCGFAV.INFO.STR_AMT >= BPREXFAV.STR_AMT02 
            && BPREXFAV.STR_AMT02 != 0) {
            CEP.TRC(SCCGWA, BPCGFAV.INFO.STR_AMT);
            CEP.TRC(SCCGWA, BPREXFAV.STR_AMT02);
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP02;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP02;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP02;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP02;
        }
        if (BPCGFAV.INFO.STR_AMT >= BPREXFAV.STR_AMT03 
            && BPREXFAV.STR_AMT03 != 0) {
            CEP.TRC(SCCGWA, BPCGFAV.INFO.STR_AMT);
            CEP.TRC(SCCGWA, BPREXFAV.STR_AMT03);
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP03;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP03;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP03;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP03;
        }
        if (BPCGFAV.INFO.STR_AMT >= BPREXFAV.STR_AMT04 
            && BPREXFAV.STR_AMT04 != 0) {
            CEP.TRC(SCCGWA, BPCGFAV.INFO.STR_AMT);
            CEP.TRC(SCCGWA, BPREXFAV.STR_AMT04);
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP04;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP04;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP04;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP04;
        }
        if (BPCGFAV.INFO.STR_AMT >= BPREXFAV.STR_AMT05 
            && BPREXFAV.STR_AMT05 != 0) {
            CEP.TRC(SCCGWA, BPCGFAV.INFO.STR_AMT);
            CEP.TRC(SCCGWA, BPREXFAV.STR_AMT05);
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP05;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP05;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP05;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP05;
        }
        if (BPCGFAV.INFO.STR_AMT >= BPREXFAV.STR_AMT06 
            && BPREXFAV.STR_AMT06 != 0) {
            CEP.TRC(SCCGWA, BPCGFAV.INFO.STR_AMT);
            CEP.TRC(SCCGWA, BPREXFAV.STR_AMT06);
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP06;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP06;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP06;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP06;
        }
        if (BPCGFAV.INFO.STR_AMT >= BPREXFAV.STR_AMT07 
            && BPREXFAV.STR_AMT07 != 0) {
            CEP.TRC(SCCGWA, BPCGFAV.INFO.STR_AMT);
            CEP.TRC(SCCGWA, BPREXFAV.STR_AMT07);
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP07;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP07;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP07;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP07;
        }
        if (BPCGFAV.INFO.STR_AMT >= BPREXFAV.STR_AMT08 
            && BPREXFAV.STR_AMT08 != 0) {
            CEP.TRC(SCCGWA, BPCGFAV.INFO.STR_AMT);
            CEP.TRC(SCCGWA, BPREXFAV.STR_AMT08);
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP08;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP08;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP08;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP08;
        }
        if (BPCGFAV.INFO.STR_AMT >= BPREXFAV.STR_AMT09 
            && BPREXFAV.STR_AMT09 != 0) {
            CEP.TRC(SCCGWA, BPCGFAV.INFO.STR_AMT);
            CEP.TRC(SCCGWA, BPREXFAV.STR_AMT09);
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP09;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP09;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP09;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP09;
        }
        if (BPCGFAV.INFO.STR_AMT >= BPREXFAV.STR_AMT10 
            && BPREXFAV.STR_AMT10 != 0) {
            CEP.TRC(SCCGWA, BPCGFAV.INFO.STR_AMT);
            CEP.TRC(SCCGWA, BPREXFAV.STR_AMT10);
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP10;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP10;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP10;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP10;
        }
        CEP.TRC(SCCGWA, BPCGFAV.INFO.CSBUY_SP01);
        CEP.TRC(SCCGWA, BPCGFAV.INFO.CSSELL_SP01);
        CEP.TRC(SCCGWA, BPCGFAV.INFO.FXBUY_SP01);
        CEP.TRC(SCCGWA, BPCGFAV.INFO.FXSELL_SP01);
    }
    public void B002_04_COMPARE_CHNL_NO() throws IOException,SQLException,Exception {
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_A01) 
            && BPREXFAV.CHNL_NO_A01.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP01;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP01;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP01;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP01;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_A02) 
            && BPREXFAV.CHNL_NO_A02.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP01;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP01;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP01;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP01;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_A03) 
            && BPREXFAV.CHNL_NO_A03.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP01;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP01;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP01;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP01;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_A04) 
            && BPREXFAV.CHNL_NO_A04.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP01;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP01;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP01;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP01;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_A05) 
            && BPREXFAV.CHNL_NO_A05.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP01;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP01;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP01;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP01;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_A06) 
            && BPREXFAV.CHNL_NO_A06.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP01;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP01;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP01;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP01;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_A07) 
            && BPREXFAV.CHNL_NO_A07.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP01;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP01;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP01;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP01;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_A08) 
            && BPREXFAV.CHNL_NO_A08.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP01;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP01;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP01;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP01;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_A09) 
            && BPREXFAV.CHNL_NO_A09.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP01;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP01;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP01;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP01;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_A10) 
            && BPREXFAV.CHNL_NO_A10.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP01;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP01;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP01;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP01;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_B01) 
            && BPREXFAV.CHNL_NO_B01.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP02;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP02;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP02;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP02;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_B02) 
            && BPREXFAV.CHNL_NO_B02.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP02;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP02;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP02;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP02;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_B03) 
            && BPREXFAV.CHNL_NO_B03.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP02;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP02;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP02;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP02;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_B04) 
            && BPREXFAV.CHNL_NO_B04.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP02;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP02;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP02;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP02;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_B05) 
            && BPREXFAV.CHNL_NO_B05.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP02;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP02;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP02;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP02;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_B06) 
            && BPREXFAV.CHNL_NO_B06.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP02;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP02;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP02;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP02;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_B07) 
            && BPREXFAV.CHNL_NO_B07.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP02;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP02;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP02;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP02;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_B08) 
            && BPREXFAV.CHNL_NO_B08.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP02;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP02;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP02;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP02;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_B09) 
            && BPREXFAV.CHNL_NO_B09.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP02;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP02;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP02;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP02;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_B10) 
            && BPREXFAV.CHNL_NO_B10.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP02;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP02;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP02;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP02;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_C01) 
            && BPREXFAV.CHNL_NO_C01.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP03;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP03;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP03;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP03;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_C02) 
            && BPREXFAV.CHNL_NO_C02.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP03;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP03;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP03;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP03;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_C03) 
            && BPREXFAV.CHNL_NO_C03.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP03;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP03;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP03;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP03;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_C04) 
            && BPREXFAV.CHNL_NO_C04.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP03;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP03;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP03;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP03;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_C05) 
            && BPREXFAV.CHNL_NO_C05.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP03;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP03;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP03;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP03;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_C06) 
            && BPREXFAV.CHNL_NO_C06.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP03;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP03;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP03;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP03;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_C07) 
            && BPREXFAV.CHNL_NO_C07.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP03;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP03;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP03;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP03;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_C08) 
            && BPREXFAV.CHNL_NO_C08.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP03;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP03;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP03;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP03;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_C09) 
            && BPREXFAV.CHNL_NO_C09.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP03;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP03;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP03;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP03;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_C10) 
            && BPREXFAV.CHNL_NO_C10.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP03;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP03;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP03;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP03;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_D01) 
            && BPREXFAV.CHNL_NO_D01.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP04;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP04;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP04;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP04;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_D02) 
            && BPREXFAV.CHNL_NO_D02.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP04;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP04;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP04;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP04;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_D03) 
            && BPREXFAV.CHNL_NO_D03.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP04;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP04;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP04;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP04;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_D04) 
            && BPREXFAV.CHNL_NO_D04.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP04;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP04;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP04;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP04;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_D05) 
            && BPREXFAV.CHNL_NO_D05.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP04;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP04;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP04;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP04;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_D06) 
            && BPREXFAV.CHNL_NO_D06.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP04;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP04;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP04;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP04;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_D07) 
            && BPREXFAV.CHNL_NO_D07.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP04;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP04;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP04;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP04;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_D08) 
            && BPREXFAV.CHNL_NO_D08.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP04;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP04;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP04;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP04;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_D09) 
            && BPREXFAV.CHNL_NO_D09.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP04;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP04;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP04;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP04;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_D10) 
            && BPREXFAV.CHNL_NO_D10.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP04;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP04;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP04;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP04;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_E01) 
            && BPREXFAV.CHNL_NO_E01.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP05;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP05;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP05;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP05;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_E02) 
            && BPREXFAV.CHNL_NO_E02.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP05;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP05;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP05;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP05;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_E03) 
            && BPREXFAV.CHNL_NO_E03.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP05;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP05;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP05;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP05;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_E04) 
            && BPREXFAV.CHNL_NO_E04.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP05;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP05;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP05;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP05;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_E05) 
            && BPREXFAV.CHNL_NO_E05.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP05;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP05;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP05;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP05;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_E06) 
            && BPREXFAV.CHNL_NO_E06.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP05;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP05;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP05;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP05;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_E07) 
            && BPREXFAV.CHNL_NO_E07.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP05;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP05;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP05;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP05;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_E08) 
            && BPREXFAV.CHNL_NO_E08.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP05;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP05;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP05;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP05;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_E09) 
            && BPREXFAV.CHNL_NO_E09.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP05;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP05;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP05;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP05;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_E10) 
            && BPREXFAV.CHNL_NO_E10.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP05;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP05;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP05;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP05;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_F01) 
            && BPREXFAV.CHNL_NO_F01.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP06;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP06;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP06;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP06;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_F02) 
            && BPREXFAV.CHNL_NO_F02.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP06;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP06;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP06;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP06;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_F03) 
            && BPREXFAV.CHNL_NO_F03.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP06;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP06;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP06;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP06;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_F04) 
            && BPREXFAV.CHNL_NO_F04.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP06;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP06;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP06;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP06;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_F05) 
            && BPREXFAV.CHNL_NO_F05.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP06;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP06;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP06;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP06;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_F06) 
            && BPREXFAV.CHNL_NO_F06.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP06;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP06;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP06;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP06;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_F07) 
            && BPREXFAV.CHNL_NO_F07.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP06;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP06;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP06;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP06;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_F08) 
            && BPREXFAV.CHNL_NO_F08.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP06;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP06;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP06;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP06;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_F09) 
            && BPREXFAV.CHNL_NO_F09.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP06;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP06;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP06;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP06;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_F10) 
            && BPREXFAV.CHNL_NO_F10.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP06;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP06;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP06;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP06;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_G01) 
            && BPREXFAV.CHNL_NO_G01.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP07;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP07;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP07;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP07;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_G02) 
            && BPREXFAV.CHNL_NO_G02.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP07;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP07;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP07;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP07;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_G03) 
            && BPREXFAV.CHNL_NO_G03.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP07;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP07;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP07;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP07;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_G04) 
            && BPREXFAV.CHNL_NO_G04.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP07;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP07;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP07;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP07;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_G05) 
            && BPREXFAV.CHNL_NO_G05.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP07;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP07;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP07;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP07;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_G06) 
            && BPREXFAV.CHNL_NO_G06.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP07;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP07;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP07;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP07;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_G07) 
            && BPREXFAV.CHNL_NO_G07.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP07;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP07;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP07;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP07;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_G08) 
            && BPREXFAV.CHNL_NO_G08.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP07;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP07;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP07;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP07;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_G09) 
            && BPREXFAV.CHNL_NO_G09.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP07;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP07;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP07;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP07;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_G10) 
            && BPREXFAV.CHNL_NO_G10.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP07;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP07;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP07;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP07;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_H01) 
            && BPREXFAV.CHNL_NO_H01.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP08;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP08;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP08;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP08;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_H02) 
            && BPREXFAV.CHNL_NO_H02.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP08;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP08;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP08;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP08;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_H03) 
            && BPREXFAV.CHNL_NO_H03.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP08;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP08;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP08;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP08;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_H04) 
            && BPREXFAV.CHNL_NO_H04.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP08;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP08;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP08;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP08;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_H05) 
            && BPREXFAV.CHNL_NO_H05.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP08;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP08;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP08;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP08;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_H06) 
            && BPREXFAV.CHNL_NO_H06.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP08;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP08;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP08;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP08;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_H07) 
            && BPREXFAV.CHNL_NO_H07.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP08;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP08;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP08;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP08;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_H08) 
            && BPREXFAV.CHNL_NO_H08.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP08;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP08;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP08;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP08;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_H09) 
            && BPREXFAV.CHNL_NO_H09.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP08;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP08;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP08;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP08;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_H10) 
            && BPREXFAV.CHNL_NO_H10.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP08;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP08;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP08;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP08;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_I01) 
            && BPREXFAV.CHNL_NO_I01.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP09;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP09;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP09;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP09;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_I02) 
            && BPREXFAV.CHNL_NO_I02.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP09;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP09;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP09;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP09;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_I03) 
            && BPREXFAV.CHNL_NO_I03.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP09;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP09;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP09;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP09;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_I04) 
            && BPREXFAV.CHNL_NO_I04.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP09;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP09;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP09;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP09;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_I05) 
            && BPREXFAV.CHNL_NO_I05.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP09;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP09;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP09;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP09;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_I06) 
            && BPREXFAV.CHNL_NO_I06.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP09;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP09;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP09;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP09;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_I07) 
            && BPREXFAV.CHNL_NO_I07.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP09;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP09;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP09;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP09;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_I08) 
            && BPREXFAV.CHNL_NO_I08.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP09;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP09;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP09;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP09;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_I09) 
            && BPREXFAV.CHNL_NO_I09.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP09;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP09;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP09;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP09;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_I10) 
            && BPREXFAV.CHNL_NO_I10.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP09;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP09;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP09;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP09;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_J01) 
            && BPREXFAV.CHNL_NO_J01.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP10;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP10;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP10;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP10;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_J02) 
            && BPREXFAV.CHNL_NO_J02.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP10;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP10;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP10;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP10;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_J03) 
            && BPREXFAV.CHNL_NO_J03.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP10;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP10;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP10;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP10;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_J04) 
            && BPREXFAV.CHNL_NO_J04.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP10;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP10;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP10;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP10;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_J05) 
            && BPREXFAV.CHNL_NO_J05.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP10;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP10;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP10;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP10;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_J06) 
            && BPREXFAV.CHNL_NO_J06.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP10;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP10;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP10;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP10;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_J07) 
            && BPREXFAV.CHNL_NO_J07.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP10;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP10;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP10;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP10;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_J08) 
            && BPREXFAV.CHNL_NO_J08.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP10;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP10;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP10;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP10;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_J09) 
            && BPREXFAV.CHNL_NO_J09.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP10;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP10;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP10;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP10;
        }
        if (BPCGFAV.INFO.CHNL_NO.equalsIgnoreCase(BPREXFAV.CHNL_NO_J10) 
            && BPREXFAV.CHNL_NO_J10.trim().length() > 0) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP10;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP10;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP10;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP10;
        }
        CEP.TRC(SCCGWA, "================CHNL====================");
        CEP.TRC(SCCGWA, BPCGFAV.INFO.CSBUY_SP01);
        CEP.TRC(SCCGWA, BPCGFAV.INFO.CSSELL_SP01);
        CEP.TRC(SCCGWA, BPCGFAV.INFO.FXBUY_SP01);
        CEP.TRC(SCCGWA, BPCGFAV.INFO.FXSELL_SP01);
    }
    public void B002_03_01_LINK_CIZSGRS() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, CICSGRS);
        CICSGRS.DATA.CI_NO = BPCGFAV.INFO.CI_NO;
        CEP.TRC(SCCGWA, BPREXFAV.GRP_NO_A01);
        CEP.TRC(SCCGWA, BPREXFAV.GRP_NO_A02);
        CEP.TRC(SCCGWA, BPREXFAV.GRP_NO_A03);
        CEP.TRC(SCCGWA, BPREXFAV.GRP_NO_A04);
        CEP.TRC(SCCGWA, BPREXFAV.GRP_NO_A05);
        CEP.TRC(SCCGWA, BPREXFAV.GRP_NO_A06);
        CEP.TRC(SCCGWA, BPREXFAV.GRP_NO_A07);
        CEP.TRC(SCCGWA, BPREXFAV.GRP_NO_A08);
        CEP.TRC(SCCGWA, BPREXFAV.GRP_NO_A09);
        CEP.TRC(SCCGWA, BPREXFAV.GRP_NO_A10);
        WS_I = 1;
        if (BPREXFAV.GRP_NO_A01.trim().length() > 0) {
            CICSGRS.DATA.MULTI_DATA[WS_I-1].GRS_NO = BPREXFAV.GRP_NO_A01;
            WS_I += 1;
        }
        if (BPREXFAV.GRP_NO_A02.trim().length() > 0) {
            CICSGRS.DATA.MULTI_DATA[WS_I-1].GRS_NO = BPREXFAV.GRP_NO_A02;
            WS_I += 1;
        }
        if (BPREXFAV.GRP_NO_A03.trim().length() > 0) {
            CICSGRS.DATA.MULTI_DATA[WS_I-1].GRS_NO = BPREXFAV.GRP_NO_A03;
            WS_I += 1;
        }
        if (BPREXFAV.GRP_NO_A04.trim().length() > 0) {
            CICSGRS.DATA.MULTI_DATA[WS_I-1].GRS_NO = BPREXFAV.GRP_NO_A04;
            WS_I += 1;
        }
        if (BPREXFAV.GRP_NO_A05.trim().length() > 0) {
            CICSGRS.DATA.MULTI_DATA[WS_I-1].GRS_NO = BPREXFAV.GRP_NO_A05;
            WS_I += 1;
        }
        if (BPREXFAV.GRP_NO_A06.trim().length() > 0) {
            CICSGRS.DATA.MULTI_DATA[WS_I-1].GRS_NO = BPREXFAV.GRP_NO_A06;
            WS_I += 1;
        }
        if (BPREXFAV.GRP_NO_A07.trim().length() > 0) {
            CICSGRS.DATA.MULTI_DATA[WS_I-1].GRS_NO = BPREXFAV.GRP_NO_A07;
            WS_I += 1;
        }
        if (BPREXFAV.GRP_NO_A08.trim().length() > 0) {
            CICSGRS.DATA.MULTI_DATA[WS_I-1].GRS_NO = BPREXFAV.GRP_NO_A08;
            WS_I += 1;
        }
        if (BPREXFAV.GRP_NO_A09.trim().length() > 0) {
            CICSGRS.DATA.MULTI_DATA[WS_I-1].GRS_NO = BPREXFAV.GRP_NO_A09;
            WS_I += 1;
        }
        if (BPREXFAV.GRP_NO_A10.trim().length() > 0) {
            CICSGRS.DATA.MULTI_DATA[WS_I-1].GRS_NO = BPREXFAV.GRP_NO_A10;
        }
        CEP.TRC(SCCGWA, BPCGFAV.INFO.CI_NO);
        CEP.TRC(SCCGWA, CICSGRS.DATA.MULTI_DATA[1-1].GRS_NO);
        CEP.TRC(SCCGWA, CICSGRS.DATA.MULTI_DATA[2-1].GRS_NO);
        CEP.TRC(SCCGWA, CICSGRS.DATA.MULTI_DATA[3-1].GRS_NO);
        CEP.TRC(SCCGWA, CICSGRS.DATA.MULTI_DATA[4-1].GRS_NO);
        CEP.TRC(SCCGWA, CICSGRS.DATA.MULTI_DATA[5-1].GRS_NO);
        CEP.TRC(SCCGWA, CICSGRS.DATA.MULTI_DATA[6-1].GRS_NO);
        CEP.TRC(SCCGWA, CICSGRS.DATA.MULTI_DATA[7-1].GRS_NO);
        CEP.TRC(SCCGWA, CICSGRS.DATA.MULTI_DATA[8-1].GRS_NO);
        CEP.TRC(SCCGWA, CICSGRS.DATA.MULTI_DATA[9-1].GRS_NO);
        CEP.TRC(SCCGWA, CICSGRS.DATA.MULTI_DATA[10-1].GRS_NO);
        S000_CALL_CIZSGRS();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, CICSGRS.OUT_DATA[1-1].GRPS_NO);
        CEP.TRC(SCCGWA, CICSGRS.OUT_DATA[2-1].GRPS_NO);
        CEP.TRC(SCCGWA, CICSGRS.OUT_DATA[3-1].GRPS_NO);
        CEP.TRC(SCCGWA, CICSGRS.OUT_DATA[4-1].GRPS_NO);
        CEP.TRC(SCCGWA, CICSGRS.OUT_DATA[5-1].GRPS_NO);
        CEP.TRC(SCCGWA, CICSGRS.OUT_DATA[6-1].GRPS_NO);
        CEP.TRC(SCCGWA, CICSGRS.OUT_DATA[7-1].GRPS_NO);
        CEP.TRC(SCCGWA, CICSGRS.OUT_DATA[8-1].GRPS_NO);
        CEP.TRC(SCCGWA, CICSGRS.OUT_DATA[9-1].GRPS_NO);
        CEP.TRC(SCCGWA, CICSGRS.OUT_DATA[10-1].GRPS_NO);
    }
    public void B002_03_COMPARE_GRP_NO() throws IOException,SQLException,Exception {
        if (BPCGFAV.INFO.CI_NO.trim().length() > 0) {
            if (BPREXFAV.GRP_NO_A01.trim().length() > 0 
                || BPREXFAV.GRP_NO_A02.trim().length() > 0 
                || BPREXFAV.GRP_NO_A03.trim().length() > 0 
                || BPREXFAV.GRP_NO_A04.trim().length() > 0 
                || BPREXFAV.GRP_NO_A05.trim().length() > 0 
                || BPREXFAV.GRP_NO_A06.trim().length() > 0 
                || BPREXFAV.GRP_NO_A07.trim().length() > 0 
                || BPREXFAV.GRP_NO_A08.trim().length() > 0 
                || BPREXFAV.GRP_NO_A09.trim().length() > 0 
                || BPREXFAV.GRP_NO_A10.trim().length() > 0) {
                B002_03_01_LINK_CIZSGRS();
                if (pgmRtn) return;
                if (CICSGRS.OUT_DATA[1-1].GRPS_NO.trim().length() > 0 
                    || CICSGRS.OUT_DATA[2-1].GRPS_NO.trim().length() > 0 
                    || CICSGRS.OUT_DATA[3-1].GRPS_NO.trim().length() > 0 
                    || CICSGRS.OUT_DATA[4-1].GRPS_NO.trim().length() > 0 
                    || CICSGRS.OUT_DATA[5-1].GRPS_NO.trim().length() > 0 
                    || CICSGRS.OUT_DATA[6-1].GRPS_NO.trim().length() > 0 
                    || CICSGRS.OUT_DATA[7-1].GRPS_NO.trim().length() > 0 
                    || CICSGRS.OUT_DATA[8-1].GRPS_NO.trim().length() > 0 
                    || CICSGRS.OUT_DATA[9-1].GRPS_NO.trim().length() > 0 
                    || CICSGRS.OUT_DATA[10-1].GRPS_NO.trim().length() > 0) {
                    BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP01;
                    BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP01;
                    BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP01;
                    BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP01;
                }
            }
            CEP.TRC(SCCGWA, "===============GRPS================");
            CEP.TRC(SCCGWA, BPCGFAV.INFO.CSBUY_SP01);
            CEP.TRC(SCCGWA, BPCGFAV.INFO.CSSELL_SP01);
            CEP.TRC(SCCGWA, BPCGFAV.INFO.FXBUY_SP01);
            CEP.TRC(SCCGWA, BPCGFAV.INFO.FXSELL_SP01);
        }
    }
    public void B002_02_COMPARE_AC_TYP() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, BPCGFAV.INFO.AC_TYP);
        CEP.TRC(SCCGWA, BPREXFAV.AC_TYP_A01);
        if ((BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_A01) 
            && BPREXFAV.AC_TYP_A01.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_A02) 
            && BPREXFAV.AC_TYP_A02.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_A03) 
            && BPREXFAV.AC_TYP_A03.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_A04) 
            && BPREXFAV.AC_TYP_A04.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_A05) 
            && BPREXFAV.AC_TYP_A05.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_A06) 
            && BPREXFAV.AC_TYP_A06.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_A07) 
            && BPREXFAV.AC_TYP_A07.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_A08) 
            && BPREXFAV.AC_TYP_A08.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_A09) 
            && BPREXFAV.AC_TYP_A09.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_A10) 
            && BPREXFAV.AC_TYP_A10.trim().length() > 0)) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP01;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP01;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP01;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP01;
        }
        if ((BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_B01) 
            && BPREXFAV.AC_TYP_B01.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_B02) 
            && BPREXFAV.AC_TYP_B02.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_B03) 
            && BPREXFAV.AC_TYP_B03.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_B04) 
            && BPREXFAV.AC_TYP_B04.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_B05) 
            && BPREXFAV.AC_TYP_B05.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_B06) 
            && BPREXFAV.AC_TYP_B06.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_B07) 
            && BPREXFAV.AC_TYP_B07.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_B08) 
            && BPREXFAV.AC_TYP_B08.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_B09) 
            && BPREXFAV.AC_TYP_B09.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_B10) 
            && BPREXFAV.AC_TYP_B10.trim().length() > 0)) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP02;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP02;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP02;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP02;
        }
        if ((BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_C01) 
            && BPREXFAV.AC_TYP_C01.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_C02) 
            && BPREXFAV.AC_TYP_C02.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_C03) 
            && BPREXFAV.AC_TYP_C03.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_C04) 
            && BPREXFAV.AC_TYP_C04.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_C05) 
            && BPREXFAV.AC_TYP_C05.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_C06) 
            && BPREXFAV.AC_TYP_C06.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_C07) 
            && BPREXFAV.AC_TYP_C07.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_C08) 
            && BPREXFAV.AC_TYP_C08.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_C09) 
            && BPREXFAV.AC_TYP_C09.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_C10) 
            && BPREXFAV.AC_TYP_C10.trim().length() > 0)) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP03;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP03;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP03;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP03;
        }
        if ((BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_D01) 
            && BPREXFAV.AC_TYP_D01.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_D02) 
            && BPREXFAV.AC_TYP_D02.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_D03) 
            && BPREXFAV.AC_TYP_D03.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_D04) 
            && BPREXFAV.AC_TYP_D04.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_D05) 
            && BPREXFAV.AC_TYP_D05.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_D06) 
            && BPREXFAV.AC_TYP_D06.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_D07) 
            && BPREXFAV.AC_TYP_D07.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_D08) 
            && BPREXFAV.AC_TYP_D08.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_D09) 
            && BPREXFAV.AC_TYP_D09.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_D10) 
            && BPREXFAV.AC_TYP_D10.trim().length() > 0)) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP04;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP04;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP04;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP04;
        }
        if ((BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_E01) 
            && BPREXFAV.AC_TYP_E01.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_E02) 
            && BPREXFAV.AC_TYP_E02.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_E03) 
            && BPREXFAV.AC_TYP_E03.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_E04) 
            && BPREXFAV.AC_TYP_E04.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_E05) 
            && BPREXFAV.AC_TYP_E05.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_E06) 
            && BPREXFAV.AC_TYP_E06.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_E07) 
            && BPREXFAV.AC_TYP_E07.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_E08) 
            && BPREXFAV.AC_TYP_E08.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_E09) 
            && BPREXFAV.AC_TYP_E09.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_E10) 
            && BPREXFAV.AC_TYP_E10.trim().length() > 0)) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP05;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP05;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP05;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP05;
        }
        if ((BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_F01) 
            && BPREXFAV.AC_TYP_F01.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_F02) 
            && BPREXFAV.AC_TYP_F02.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_F03) 
            && BPREXFAV.AC_TYP_F03.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_F04) 
            && BPREXFAV.AC_TYP_F04.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_F05) 
            && BPREXFAV.AC_TYP_F05.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_F06) 
            && BPREXFAV.AC_TYP_F06.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_F07) 
            && BPREXFAV.AC_TYP_F07.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_F08) 
            && BPREXFAV.AC_TYP_F08.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_F09) 
            && BPREXFAV.AC_TYP_F09.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_F10) 
            && BPREXFAV.AC_TYP_F10.trim().length() > 0)) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP06;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP06;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP06;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP06;
        }
        if ((BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_G01) 
            && BPREXFAV.AC_TYP_G01.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_G02) 
            && BPREXFAV.AC_TYP_G02.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_G03) 
            && BPREXFAV.AC_TYP_G03.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_G04) 
            && BPREXFAV.AC_TYP_G04.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_G05) 
            && BPREXFAV.AC_TYP_G05.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_G06) 
            && BPREXFAV.AC_TYP_G06.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_G07) 
            && BPREXFAV.AC_TYP_G07.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_G08) 
            && BPREXFAV.AC_TYP_G08.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_G09) 
            && BPREXFAV.AC_TYP_G09.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_G10) 
            && BPREXFAV.AC_TYP_G10.trim().length() > 0)) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP07;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP07;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP07;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP07;
        }
        if ((BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_H01) 
            && BPREXFAV.AC_TYP_H01.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_H02) 
            && BPREXFAV.AC_TYP_H02.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_H03) 
            && BPREXFAV.AC_TYP_H03.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_H04) 
            && BPREXFAV.AC_TYP_H04.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_H05) 
            && BPREXFAV.AC_TYP_H05.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_H06) 
            && BPREXFAV.AC_TYP_H06.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_H07) 
            && BPREXFAV.AC_TYP_H07.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_H08) 
            && BPREXFAV.AC_TYP_H08.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_H09) 
            && BPREXFAV.AC_TYP_H09.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_H10) 
            && BPREXFAV.AC_TYP_H10.trim().length() > 0)) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP08;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP08;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP08;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP08;
        }
        if ((BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_I01) 
            && BPREXFAV.AC_TYP_I01.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_I02) 
            && BPREXFAV.AC_TYP_I02.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_I03) 
            && BPREXFAV.AC_TYP_I03.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_I04) 
            && BPREXFAV.AC_TYP_I04.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_I05) 
            && BPREXFAV.AC_TYP_I05.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_I06) 
            && BPREXFAV.AC_TYP_I06.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_I07) 
            && BPREXFAV.AC_TYP_I07.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_I08) 
            && BPREXFAV.AC_TYP_I08.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_I09) 
            && BPREXFAV.AC_TYP_I09.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_I10) 
            && BPREXFAV.AC_TYP_I10.trim().length() > 0)) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP09;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP09;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP09;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP09;
        }
        if ((BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_J01) 
            && BPREXFAV.AC_TYP_J01.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_J02) 
            && BPREXFAV.AC_TYP_J02.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_J03) 
            && BPREXFAV.AC_TYP_J03.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_J04) 
            && BPREXFAV.AC_TYP_J04.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_J05) 
            && BPREXFAV.AC_TYP_J05.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_J06) 
            && BPREXFAV.AC_TYP_J06.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_J07) 
            && BPREXFAV.AC_TYP_J07.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_J08) 
            && BPREXFAV.AC_TYP_J08.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_J09) 
            && BPREXFAV.AC_TYP_J09.trim().length() > 0) 
            || (BPCGFAV.INFO.AC_TYP.equalsIgnoreCase(BPREXFAV.AC_TYP_J10) 
            && BPREXFAV.AC_TYP_J10.trim().length() > 0)) {
            BPCGFAV.INFO.CSBUY_SP01 = BPREXFAV.CSBUY_SP10;
            BPCGFAV.INFO.CSSELL_SP01 = BPREXFAV.CSSELL_SP10;
            BPCGFAV.INFO.FXBUY_SP01 = BPREXFAV.FXBUY_SP10;
            BPCGFAV.INFO.FXSELL_SP01 = BPREXFAV.FXSELL_SP10;
        }
        CEP.TRC(SCCGWA, "============AC-TYP-LVL======");
        CEP.TRC(SCCGWA, BPCGFAV.INFO.CSBUY_SP01);
        CEP.TRC(SCCGWA, BPCGFAV.INFO.CSSELL_SP01);
        CEP.TRC(SCCGWA, BPCGFAV.INFO.FXBUY_SP01);
        CEP.TRC(SCCGWA, BPCGFAV.INFO.FXSELL_SP01);
    }
    public void B001_CHECK_PROC() throws IOException,SQLException,Exception {
        if (BPCGFAV.INFO.FAV_TYP == ' ') {
            CEP.ERR(SCCGWA, BPCMSG_ERROR_MSG.BP_FIELD_MUSTINPUT);
        }
        if (BPCGFAV.INFO.SEQ == 0) {
            CEP.ERR(SCCGWA, BPCMSG_ERROR_MSG.BP_FIELD_MUSTINPUT);
        }
    }
    public void S000_CALL_CIZSGRS() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "CI-SEARCH-GRS       ", CICSGRS);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
    if (SCCGWA.COMM_AREA.BSP_FLG.equalsIgnoreCase("BSP") || SCCGWA.COMM_AREA.CHNL.equalsIgnoreCase("BAT")) { //FROM #IFDEF BAT
        if (BPCGFAV.RC.RC_CODE != 0) {
            CEP.TRC(SCCGWA, " BPCGFAV = ");
            CEP.TRC(SCCGWA, BPCGFAV);
        }
    } //FROM #ENDIF
        pgmRtn = true;
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
