package com.hisun.BP;

public class BPZMMTL_WS_KEY {
    String WS_KEY_INFO = " ";
    BPZMMTL_WS_CI_KEY_DTL WS_CI_KEY_DTL = new BPZMMTL_WS_CI_KEY_DTL();
    BPZMMTL_WS_CI_KEY_DTINF WS_CI_KEY_DTINF = new BPZMMTL_WS_CI_KEY_DTINF();
    BPZMMTL_WS_AI_KEY_ENTY WS_AI_KEY_ENTY = new BPZMMTL_WS_AI_KEY_ENTY();
    BPZMMTL_WS_AI_KEY_GLM WS_AI_KEY_GLM = new BPZMMTL_WS_AI_KEY_GLM();
    short WS_KEY_BEGSEQ = 0;
    short WS_KEY_KEYSEQ = 0;
}
