package com.hisun.BP;

public class BPZPCHDY_WS_TXN_HIS_DATA {
    BPZPCHDY_WS_OLD_MONTH WS_OLD_MONTH = new BPZPCHDY_WS_OLD_MONTH();
    BPZPCHDY_WS_NEW_MONTH WS_NEW_MONTH = new BPZPCHDY_WS_NEW_MONTH();
    String WS_OLD_NAME = " ";
    int WS_OLD_EFF_DATE = 0;
    int WS_OLD_EXP_DATE = 0;
    BPZPCHDY_WS_HIS_REF WS_HIS_REF = new BPZPCHDY_WS_HIS_REF();
}
