package com.hisun.BP;

import com.hisun.SC.SCCPCWA;

public class BPZSGOBL_WS_VARIABLES {
    BPZSGOBL_WS_TEMP_VARIABLE WS_TEMP_VARIABLE = new BPZSGOBL_WS_TEMP_VARIABLE();
    SCCPCWA SCCPCWA = new SCCPCWA();
}
