package com.hisun.BP;

public class BPZSCALE_WS_TXN_HIS_DATA {
    BPZSCALE_WS_OLD_MONTH WS_OLD_MONTH = new BPZSCALE_WS_OLD_MONTH();
    BPZSCALE_WS_NEW_MONTH WS_NEW_MONTH = new BPZSCALE_WS_NEW_MONTH();
    String WS_OLD_NAME = " ";
    int WS_OLD_EFF_DATE = 0;
    int WS_OLD_EXP_DATE = 0;
    BPZSCALE_WS_HIS_REF WS_HIS_REF = new BPZSCALE_WS_HIS_REF();
}
