package com.hisun.BP;

import com.hisun.SC.*;
import com.hisun.AI.*;
import com.hisun.IB.*;

import java.io.IOException;
import java.sql.SQLException;

public class BPZSCFHD {
    int JIBS_tmp_int;
    String JIBS_tmp_str[] = new String[10];
    short IB_CODE = 16;
    short IB_JJ = 60;
    String SC_SCOSWAP1 = "SC-SCOSWAP1      ";
    String OUTPUT_FMT = "BP103";
    String BUSS_TYPE = "99";
    String F_TLR_INFO_QUERY = "BP-F-TLR-INF-QUERY  ";
    String F_TLR_PEND_MGM = "BP-F-TLR-PEND-MGM   ";
    String U_CMOV_CONFIRM = "BP-U-CMOV-CONFIRM   ";
    String P_INQ_IBAC = "BP-P-INQ-IBAC       ";
    String P_ADD_CHIS = "BP-P-ADD-CHIS       ";
    String F_F_CON_CHG_INFO = "BP-F-F-CON-CHG-INFO ";
    String U_CASH_IN = "BP-U-CASH-IN        ";
    BPZSCFHD_WS_VARIABLES WS_VARIABLES = new BPZSCFHD_WS_VARIABLES();
    BPZSCFHD_WS2 WS2 = new BPZSCFHD_WS2();
    BPCOCFHD_WS_COND_FLG WS_COND_FLG = new BPCOCFHD_WS_COND_FLG();
    BPCSWB02_AWA_0002 AWA_0002 = new BPCSWB02_AWA_0002();
    BPCMSG_ERROR_MSG ERROR_MSG = new BPCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCFMT SCCFMT = new SCCFMT();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    BPCUCMOV BPCUCMOV = new BPCUCMOV();
    BPCFTLRQ BPCFTLRQ = new BPCFTLRQ();
    BPCPQIBA BPCPQIBA = new BPCPQIBA();
    BPCPCHIS BPCPCHIS = new BPCPCHIS();
    BPCFTLPM BPCFTLPM = new BPCFTLPM();
    AICPIAEV AICPIAEV = new AICPIAEV();
    IBCPOSTA IBCPOSTA = new IBCPOSTA();
    BPCFFTXI BPCFFTXI = new BPCFFTXI();
    BPCFFCON BPCFFCON = new BPCFFCON();
    BPCUCSIN BPCUCSIN = new BPCUCSIN();
    SCCGWA SCCGWA;
    BPCSCFHD BPCSCFHD;
    SCCGSCA_SC_AREA SC_AREA;
    SCCGBPA_BP_AREA BP_AREA;
    SCCGCPT SCCGCPT;
    SCCGMSG SCCGMSG;
    BPCPQBNK_DATA_INFO DATA_INFO;
    BPRTRT BPRTRT;
    SCCAWAC SCCAWAC;
    BPRVWA BPRVWA;
    public void MP(SCCGWA SCCGWA, BPCSCFHD BPCSCFHD) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        this.BPCSCFHD = BPCSCFHD;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "BPZSCFHD return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, SCCEXCP);
        SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        SCCGCPT = (SCCGCPT) SC_AREA.CMPT_AREA_PTR;
        SCCGMSG = (SCCGMSG) SC_AREA.MSG_AREA_PTR;
        BPRTRT = (BPRTRT) SC_AREA.TR_PARM_PTR;
        DATA_INFO = (BPCPQBNK_DATA_INFO) SCCGWA.COMM_AREA.BANK_AREA_PTR;
        SCCAWAC = new SCCAWAC();
        IBS.init(SCCGWA, SCCAWAC);
        IBS.CPY2CLS(SCCGWA, SCCGWA.COMM_AREA.AWAC_AREA_PTR, SCCAWAC);
        BPRVWA = (BPRVWA) BP_AREA.VCH_AREA.VCH_AREA_PTR;
        IBS.init(SCCGWA, WS_VARIABLES);
        IBS.init(SCCGWA, WS2);
        SCCGWA.COMM_AREA.MSG_PROC_AREA.MSG_ID.MSG_AP_MMO = SCCGWA.COMM_AREA.AP_MMO;
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, "B000 BEGIN");
        B010_CHECK_TELLER();
        for (WS_VARIABLES.CCY_CNT = 1; WS_VARIABLES.CCY_CNT <= 5 
            && BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].CCY.trim().length() != 0; WS_VARIABLES.CCY_CNT += 1) {
            B020_GET_IBAC_INFO();
            B030_ON_WAY_PROC();
            if (BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].FEE_AMT != 0) {
                B031_FEE_OUT();
            }
            if (BPCSCFHD.CONF_KIND == '1' 
                && BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].RTN_AMT != 0) {
                B050_IN_STORE_PROC();
                B025_HISTORY_PROC();
            }
        }
        B040_OUTPUT_PROC();
    }
    public void B010_CHECK_TELLER() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCFTLRQ);
        BPCFTLRQ.INFO.TLR = SCCGWA.COMM_AREA.TL_ID;
        S000_CALL_BPZFTLRQ();
        if (BPCFTLRQ.INFO.TLR_STSW == null) BPCFTLRQ.INFO.TLR_STSW = "";
        JIBS_tmp_int = BPCFTLRQ.INFO.TLR_STSW.length();
        for (int i=0;i<64-JIBS_tmp_int;i++) BPCFTLRQ.INFO.TLR_STSW += " ";
        if (!BPCFTLRQ.INFO.TLR_STSW.substring(6 - 1, 6 + 1 - 1).equalsIgnoreCase("1")) {
            WS_VARIABLES.ERR_MSG = ERROR_MSG.BP_MUST_BE_AMTTLR;
            S000_ERR_MSG_PROC();
        }
    }
    public void B020_GET_IBAC_INFO() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCPQIBA);
        B020_02_DEBIT_IBAC();
    }
    public void B020_02_DEBIT_IBAC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, IBCPOSTA);
        IBCPOSTA.NOSTRO_CD = BPCSCFHD.SWIFT;
        IBCPOSTA.JRNNO = SCCGWA.COMM_AREA.JRN_NO;
        IBCPOSTA.CCY_TYP = '2';
        IBCPOSTA.VAL_DATE = SCCGWA.COMM_AREA.AC_DATE;
        IBCPOSTA.AMT = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].CONF_AMT;
        IBCPOSTA.CCY = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].CCY;
        IBCPOSTA.SIGN = 'D';
        IBCPOSTA.ENTRY_FLG = '1';
        CEP.TRC(SCCGWA, IBCPOSTA.VAL_DATE);
        CEP.TRC(SCCGWA, IBCPOSTA.AMT);
        CEP.TRC(SCCGWA, IBCPOSTA.CCY);
        CEP.TRC(SCCGWA, IBCPOSTA.SIGN);
        CEP.TRC(SCCGWA, IBCPOSTA.ENTRY_FLG);
        S000_CALL_IBZDRAC();
        if (IBCPOSTA.RC.RC_CODE != 0) {
            CEP.ERR(SCCGWA, ERROR_MSG.BP_POSTA_RC_CD_ERR);
        }
    }
    public void B020_01_CREDIT_IBAC() throws IOException,SQLException,Exception {
        S00_CALL_SCSSGADR();
        CEP.TRC(SCCGWA, WS_VARIABLES.CCY_CNT);
        CEP.TRC(SCCGWA, BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].CCY);
        CEP.TRC(SCCGWA, BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].TOTAL_AMT);
        IBS.init(SCCGWA, AWA_0002);
        AWA_0002.S_AP = IB_CODE;
        AWA_0002.S_JJ = IB_JJ;
        if (SCCGWA.COMM_AREA.CANCEL_IND == 'Y') {
            AWA_0002.S_TRCD = 2209;
        } else {
            AWA_0002.S_TRCD = 2200;
        }
        if (BPCPQIBA.DATA_INFO.IB_AC.trim().length() == 0) AWA_0002.S_TRDATA[1-1].S_AC = 0;
        else AWA_0002.S_TRDATA[1-1].S_AC = Long.parseLong(BPCPQIBA.DATA_INFO.IB_AC);
        AWA_0002.S_TRDATA[1-1].S_CCY = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].CCY;
        AWA_0002.S_AMTDA[1-1].S_AMT = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].TOTAL_AMT;
        AWA_0002.S_FLAGD[1-1].S_FLAG2X = "01";
        AWA_0002.S_FLAGD[2-1].S_FLAG2X = "04";
        AWA_0002.S_DATA[1-1].S_DATE = SCCGWA.COMM_AREA.AC_DATE;
        CEP.TRC(SCCGWA, AWA_0002.S_TRDATA[1-1].S_AC);
        CEP.TRC(SCCGWA, AWA_0002.S_TRDATA[1-1].S_CCY);
        CEP.TRC(SCCGWA, AWA_0002.S_AMTDA[1-1].S_AMT);
        CEP.TRC(SCCGWA, AWA_0002.S_FLAGD[1-1].S_FLAG2X);
        CEP.TRC(SCCGWA, AWA_0002.S_FLAGD[2-1].S_FLAG2X);
        CEP.TRC(SCCGWA, AWA_0002.S_DATA[1-1].S_DATE);
    }
    public void B025_HISTORY_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCPCHIS);
        BPCPCHIS.TLR = SCCGWA.COMM_AREA.TL_ID;
        BPCPCHIS.PLBOX_NO = BPCUCSIN.PLBOX_NO;
        BPCPCHIS.CASH_TYP = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].CASH_TYP;
        BPCPCHIS.CCY = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].CCY;
        BPCPCHIS.AMT = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].RTN_AMT;
        BPCPCHIS.VB_FLG = '1';
        BPCPCHIS.IN_OUT = 'D';
        BPCPCHIS.CS_KIND = BPCSCFHD.CS_KIND;
        CEP.TRC(SCCGWA, BPCSCFHD.CONF_NO);
        BPCPCHIS.CONF_SEQ = BPCSCFHD.CONF_NO;
        S000_CALL_BPZPCHIS();
    }
    public void B030_ON_WAY_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCUCMOV);
        BPCUCMOV.MOV_TYPE = '2';
        BPCUCMOV.MOVE_DATE = BPCSCFHD.MOVE_DT;
        BPCUCMOV.CASH_TYP = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].CASH_TYP;
        BPCUCMOV.CCY = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].CCY;
        BPCUCMOV.TOTAL_AMT = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].TOTAL_AMT;
        BPCUCMOV.CONF_SEQ = BPCSCFHD.CONF_NO;
        BPCUCMOV.CS_KIND = BPCSCFHD.CS_KIND;
        BPCUCMOV.IN_AC = BPCPQIBA.DATA_INFO.IB_AC;
        BPCUCMOV.IN_TLR = SCCGWA.COMM_AREA.TL_ID;
        BPCUCMOV.IN_BR = SCCGWA.COMM_AREA.BR_DP.TR_BRANCH;
        BPCUCMOV.OUT_BR = BPCSCFHD.OUT_BR;
        S000_CALL_BPZUCMOV();
    }
    public void B031_FEE_OUT() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCFFTXI);
        BPCFFTXI.TX_DATA.AUH_FLG = '0';
        BPCFFTXI.TX_DATA.CHG_AC_INFO.VALUE_DATE = SCCGWA.COMM_AREA.AC_DATE;
        BPCFFTXI.TX_DATA.CHG_AC_INFO.AC_TYP = '2';
        BPCFFTXI.TX_DATA.CHG_AC_INFO.CHG_AC = IBCPOSTA.AC;
        BPCFFTXI.TX_DATA.CHG_AC_INFO.CHG_CCY = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].CCY;
        BPCFFTXI.TX_DATA.SVR_CD = SCCGWA.COMM_AREA.SERV_CODE;
        S000_CALL_BPZFFTXI();
        IBS.init(SCCGWA, BPCFFCON);
        BPCFFCON.FEE_INFO.FEE_CNT += 1;
        WS_VARIABLES.ITM = BPCFFCON.FEE_INFO.FEE_CNT;
        BPCFFCON.FEE_INFO.ACCOUNT_BR = BPCSCFHD.OUT_BR;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_VARIABLES.ITM-1].CHG_FLG = '0';
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_VARIABLES.ITM-1].FEE_CODE = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].FEE_CD;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_VARIABLES.ITM-1].FEE_CCY = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].CCY;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_VARIABLES.ITM-1].FEE_BAS = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].FEE_AMT;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_VARIABLES.ITM-1].FEE_AMT = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].FEE_AMT;
        CEP.TRC(SCCGWA, BPCFFCON.FEE_INFO.FEE_INFO1[WS_VARIABLES.ITM-1].FEE_AMT);
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_VARIABLES.ITM-1].CHG_AC_TY = BPCFFTXI.TX_DATA.CHG_AC_INFO.AC_TYP;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_VARIABLES.ITM-1].CHG_AC = BPCFFTXI.TX_DATA.CHG_AC_INFO.CHG_AC;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_VARIABLES.ITM-1].CHG_CCY = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].CCY;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_VARIABLES.ITM-1].CHG_BAS = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].FEE_AMT;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_VARIABLES.ITM-1].CHG_AMT = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].FEE_AMT;
        BPCFFCON.FEE_INFO.FEE_INFO1[WS_VARIABLES.ITM-1].ADJ_AMT = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].FEE_AMT;
        CEP.TRC(SCCGWA, BPCFFCON.FEE_INFO.FEE_INFO1[WS_VARIABLES.ITM-1].CHG_AC_TY);
        CEP.TRC(SCCGWA, BPCFFCON.FEE_INFO.FEE_INFO1[WS_VARIABLES.ITM-1].CHG_AC);
        CEP.TRC(SCCGWA, BPCFFCON.FEE_INFO.FEE_CNT);
        S000_CALL_BPZFFCON();
    }
    public void B035_DEL_TLR_PENDING_NO() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCFTLPM);
        BPCFTLPM.OP_CODE = 'D';
        BPCFTLPM.TLR = BPCSCFHD.OUT_TLR;
        BPCFTLPM.BUSS_TYP = BUSS_TYPE;
        BPCFTLPM.TX_COUNT = 1;
        S000_CALL_BPZFTLPM();
    }
    public void B040_OUTPUT_PROC() throws IOException,SQLException,Exception {
        WS2.BR = SCCGWA.COMM_AREA.BR_DP.TR_BRANCH;
        WS2.C_SWIFT = BPCSCFHD.SWIFT;
        WS2.CS_KIND = BPCSCFHD.CS_KIND;
        WS2.MOVE_DT = BPCSCFHD.MOVE_DT;
        WS2.CONF_SEQ = BPCSCFHD.CONF_NO;
        for (WS_VARIABLES.CCY_CNT = 1; WS_VARIABLES.CCY_CNT <= 5 
            && BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].CCY.trim().length() != 0; WS_VARIABLES.CCY_CNT += 1) {
            WS2.OCFHD_CCY_INFO[WS_VARIABLES.CCY_CNT-1].CASH_TYP = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].CASH_TYP;
            WS2.OCFHD_CCY_INFO[WS_VARIABLES.CCY_CNT-1].CCY = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].CCY;
            WS2.OCFHD_CCY_INFO[WS_VARIABLES.CCY_CNT-1].AMT = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].TOTAL_AMT;
            WS2.OCFHD_CCY_INFO[WS_VARIABLES.CCY_CNT-1].CONF_AMT = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].CONF_AMT;
            WS2.OCFHD_CCY_INFO[WS_VARIABLES.CCY_CNT-1].RTN_AMT = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].RTN_AMT;
            WS2.OCFHD_CCY_INFO[WS_VARIABLES.CCY_CNT-1].AC = IBCPOSTA.AC;
            for (WS_VARIABLES.START_CNT = 1; WS_VARIABLES.START_CNT <= 12 
                && BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].CCY_INFO.CCY_DETAIL[WS_VARIABLES.START_CNT-1].CCY_VAL != 0; WS_VARIABLES.START_CNT += 1) {
                WS_VARIABLES.INFO_CNT = ( WS_VARIABLES.CCY_CNT - 1 ) * 12 + WS_VARIABLES.START_CNT;
                WS2.OCFHD_DT_INFO[WS_VARIABLES.INFO_CNT-1].P_PVAL = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].CCY_INFO.CCY_DETAIL[WS_VARIABLES.START_CNT-1].CCY_VAL;
                WS2.OCFHD_DT_INFO[WS_VARIABLES.INFO_CNT-1].P_NUM = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].CCY_INFO.CCY_DETAIL[WS_VARIABLES.START_CNT-1].CCY_NUM;
                WS2.OCFHD_DT_INFO[WS_VARIABLES.INFO_CNT-1].P_MFLG = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].CCY_INFO.CCY_DETAIL[WS_VARIABLES.START_CNT-1].CCY_MFLG;
                WS2.DT_CNT = WS_VARIABLES.INFO_CNT;
            }
            WS2.CCY_CNT = WS_VARIABLES.CCY_CNT;
        }
        IBS.init(SCCGWA, SCCFMT);
        SCCFMT.FMTID = OUTPUT_FMT;
        SCCFMT.DATA_PTR = WS2;
        SCCFMT.DATA_LEN = 2056;
        IBS.FMT(SCCGWA, SCCFMT);
    }
    public void B050_IN_STORE_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCUCSIN);
        BPCUCSIN.CASH_STAT = '1';
        BPCUCSIN.VB_BR = SCCGWA.COMM_AREA.BR_DP.TR_BRANCH;
        BPCUCSIN.VB_TLR = SCCGWA.COMM_AREA.TL_ID;
        BPCUCSIN.VB_FLG = '1';
        BPCUCSIN.CASH_TYP = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].CASH_TYP;
        BPCUCSIN.CCY = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].CCY;
        BPCUCSIN.CS_KIND = BPCSCFHD.CS_KIND;
        BPCUCSIN.TX_AMT = BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].RTN_AMT;
        JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, BPCSCFHD.DATA_INFO[WS_VARIABLES.CCY_CNT-1].CCY_INFO);
        IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], BPCUCSIN.PAR_INFO);
        S000_CALL_BPZUCSIN();
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_VARIABLES.ERR_MSG);
    }
    public void S000_CALL_IBZDRAC() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "IB-DEBIT-AC", IBCPOSTA);
        if (IBCPOSTA.RC.RC_CODE != 0) {
            WS_VARIABLES.ERR_MSG = IBS.CLS2CPY(SCCGWA, IBCPOSTA.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void S00_CALL_SCSSGADR() throws IOException,SQLException,Exception {
        SCCGCPT.SWA_PTR = AWA_0002;
    }
    public void S00_LINK_SCOSWAP1() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, SC_SCOSWAP1, SCCGWA);
    }
    public void S000_CALL_BPZFTLPM() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, F_TLR_PEND_MGM, BPCFTLPM);
        if (BPCFTLPM.RC.RC_CODE != 0) {
            WS_VARIABLES.ERR_MSG = IBS.CLS2CPY(SCCGWA, BPCFTLPM.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_BPZPCHIS() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, P_ADD_CHIS, BPCPCHIS);
        if (BPCPCHIS.RC.RC_CODE != 0) {
            WS_VARIABLES.ERR_MSG = IBS.CLS2CPY(SCCGWA, BPCPCHIS.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_BPZUCMOV() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, U_CMOV_CONFIRM, BPCUCMOV);
        if (BPCUCMOV.RC.RC_CODE != 0) {
            WS_VARIABLES.ERR_MSG = IBS.CLS2CPY(SCCGWA, BPCUCMOV.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_BPZFTLRQ() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, F_TLR_INFO_QUERY, BPCFTLRQ);
        if (BPCFTLRQ.RC.RC_CODE != 0) {
            WS_VARIABLES.ERR_MSG = IBS.CLS2CPY(SCCGWA, BPCFTLRQ.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_BPZPQIBA() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, P_INQ_IBAC, BPCPQIBA);
        if (BPCPQIBA.RC.RC_CODE != 0) {
            WS_VARIABLES.ERR_MSG = IBS.CLS2CPY(SCCGWA, BPCPQIBA.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_BPZFFTXI() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-F-F-TX-INFO", BPCFFTXI);
        if (BPCFFTXI.RC.RC_CODE != 0) {
            WS_VARIABLES.ERR_MSG = IBS.CLS2CPY(SCCGWA, BPCFFTXI.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_BPZFFCON() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, F_F_CON_CHG_INFO, BPCFFCON);
        if (BPCFFCON.RC.RC_CODE != 0) {
            WS_VARIABLES.ERR_MSG = IBS.CLS2CPY(SCCGWA, BPCFFCON.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_BPZUCSIN() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, U_CASH_IN, BPCUCSIN);
        if (BPCUCSIN.RC.RC_CODE != 0) {
            WS_VARIABLES.ERR_MSG = IBS.CLS2CPY(SCCGWA, BPCUCSIN.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
