package com.hisun.BP;

public class BPZSMAGC_WS_TXN_HIS_DATA {
    BPZSMAGC_WS_OLD_MONTH WS_OLD_MONTH = new BPZSMAGC_WS_OLD_MONTH();
    BPZSMAGC_WS_NEW_MONTH WS_NEW_MONTH = new BPZSMAGC_WS_NEW_MONTH();
    String WS_OLD_NAME = " ";
    String WS_OLD_BCAL_CODE = " ";
    int WS_OLD_EFF_DATE = 0;
    int WS_OLD_EXP_DATE = 0;
    BPZSMAGC_WS_HIS_REF WS_HIS_REF = new BPZSMAGC_WS_HIS_REF();
}
