package com.hisun.BP;

import com.hisun.SC.*;

import java.io.IOException;
import java.sql.SQLException;

public class BPZTFFAV {
    DBParm BPTFFAV_RD;
    brParm BPTFFAV_BR = new brParm();
    boolean pgmRtn = false;
    char WS_TBL_FARM_FLAG = ' ';
    BPCMSG_ERROR_MSG BPCMSG_ERROR_MSG = new BPCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    BPRFFAV BPRFFAV = new BPRFFAV();
    SCCGWA SCCGWA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    BPCTFFAV BPCTFFAV;
    BPVFEXP BPVVFAV;
    public void MP(SCCGWA SCCGWA, BPCTFFAV BPCTFFAV) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        this.BPCTFFAV = BPCTFFAV;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        if (pgmRtn) return;
        B000_MAIN_PROC();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, "BPZTFFAV return!");
        Z_RET();
        if (pgmRtn) return;
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        BPVVFAV = (BPVFEXP) BPCTFFAV.INFO.POINTER;
        IBS.init(SCCGWA, BPCTFFAV.RC);
        CEP.TRC(SCCGWA, BPCTFFAV.INFO.REC_LEN);
        CEP.TRC(SCCGWA, BPVVFAV);
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, BPCTFFAV.INFO.FUNC);
        R000_TRANS_DATA_TO_BPRFFAV();
        if (pgmRtn) return;
        if (BPCTFFAV.INFO.FUNC == '0') {
            B010_CREATE_RECORD_PROC();
            if (pgmRtn) return;
        } else if (BPCTFFAV.INFO.FUNC == '4') {
            B020_READUPD_RECORD_PROC();
            if (pgmRtn) return;
        } else if (BPCTFFAV.INFO.FUNC == '3') {
            B030_QUERY_RECORD_PROC();
            if (pgmRtn) return;
        } else if (BPCTFFAV.INFO.FUNC == '1') {
            B040_UPDATE_RECORD_PROC();
            if (pgmRtn) return;
        } else if (BPCTFFAV.INFO.FUNC == '2') {
            B050_DELETE_RECORD_PROC();
            if (pgmRtn) return;
        } else if (BPCTFFAV.INFO.FUNC == '5') {
            B060_BROWSE_RECORD_PROC();
            if (pgmRtn) return;
        } else {
            IBS.init(SCCGWA, SCCEXCP);
            SCCEXCP.MSG_TEXT.KEY_OR_OTHER = "INVALID FUNC(" + BPCTFFAV.INFO.FUNC + ")";
            CEP.EXCP(SCCGWA, SCCEXCP.MSG_TEXT.KEY_OR_OTHER);
        }
        R000_TRANS_DATA_TO_BPVFFAV();
        if (pgmRtn) return;
    }
    public void B010_CREATE_RECORD_PROC() throws IOException,SQLException,Exception {
        T000_WRITE_BPTFFAV();
        if (pgmRtn) return;
    }
    public void B020_READUPD_RECORD_PROC() throws IOException,SQLException,Exception {
        T000_READ_BPTFFAV_UPD();
        if (pgmRtn) return;
        if (WS_TBL_FARM_FLAG == 'D') {
            IBS.CPY2CLS(SCCGWA, BPCMSG_ERROR_MSG.BP_FARM_NOTFND, BPCTFFAV.RC);
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void B030_QUERY_RECORD_PROC() throws IOException,SQLException,Exception {
        T000_READ_BPTFFAV();
        if (pgmRtn) return;
    }
    public void B040_UPDATE_RECORD_PROC() throws IOException,SQLException,Exception {
        T000_REWRITE_BPTFFAV();
        if (pgmRtn) return;
    }
    public void B050_DELETE_RECORD_PROC() throws IOException,SQLException,Exception {
        T000_DELETE_BPTFFAV();
        if (pgmRtn) return;
    }
    public void B060_BROWSE_RECORD_PROC() throws IOException,SQLException,Exception {
        if (BPCTFFAV.INFO.OPT == '0') {
            T000_STARTBR_BPTFFAV();
            if (pgmRtn) return;
        } else if (BPCTFFAV.INFO.OPT == '1') {
            T000_READNEXT_BPTFFAV();
            if (pgmRtn) return;
        } else if (BPCTFFAV.INFO.OPT == '2') {
            T000_ENDBR_BPTFFAV();
            if (pgmRtn) return;
        } else {
            IBS.init(SCCGWA, SCCEXCP);
            SCCEXCP.MSG_TEXT.KEY_OR_OTHER = "INVALID OPT (" + BPCTFFAV.INFO.OPT + ")";
            CEP.EXCP(SCCGWA, SCCEXCP.MSG_TEXT.KEY_OR_OTHER);
        }
    }
    public void R000_TRANS_DATA_TO_BPRFFAV() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPRFFAV);
        BPRFFAV.KEY.PRFR_CODE = BPVVFAV.KEY.PRFR_CODE;
        BPRFFAV.EFF_DATE = BPVVFAV.DATE.EFF_DATE;
        BPRFFAV.EXP_DATE = BPVVFAV.DATE.EXP_DATE;
        BPRFFAV.FFAV_DESC = BPVVFAV.VAL.DESC;
        BPRFFAV.FAV_TYPE = BPVVFAV.VAL.FAV_TYPE;
        BPRFFAV.FAV_PERIOD = BPVVFAV.VAL.FAV_PERIOD;
        BPRFFAV.MAX_FAV_AMT = BPVVFAV.VAL.MAX_FAV_AMT;
        BPRFFAV.MAX_FAV_PCT = BPVVFAV.VAL.MAX_FAV_PCT;
        BPRFFAV.FAV_COLL = BPVVFAV.VAL.FAV_COLL;
        BPRFFAV.FAV_CPNT = BPVVFAV.VAL.FAV_CPNT;
        BPRFFAV.CAL_SOURCE = BPVVFAV.VAL.CAL_SOURCE;
        BPRFFAV.CAL_CYC = BPVVFAV.VAL.CAL_CYC;
        BPRFFAV.CYC_NUM = BPVVFAV.VAL.CYC_NUM;
        BPRFFAV.COLL_TYPE = BPVVFAV.VAL.COLL_TYPE;
        BPRFFAV.FAV_SPLT_FLG = BPVVFAV.VAL.FAV_SPLT_FLG;
        BPRFFAV.ADJ_TYP = BPVVFAV.VAL.ADJ_TYP;
        BPRFFAV.DIF_VAL = BPVVFAV.VAL.DIF_VAL;
        BPRFFAV.STR_AMT_1 = BPVVFAV.VAL.FAV_DATA[1-1].STR_AMT;
        BPRFFAV.STR_CNT_1 = BPVVFAV.VAL.FAV_DATA[1-1].STR_CNT;
        BPRFFAV.STR_TIME_1 = BPVVFAV.VAL.FAV_DATA[1-1].STR_TIME;
        BPRFFAV.END_TIME_1 = BPVVFAV.VAL.FAV_DATA[1-1].END_TIME;
        BPRFFAV.CI_LEVEL_1 = BPVVFAV.VAL.FAV_DATA[1-1].CI_LEVEL;
        BPRFFAV.AC_LEVEL_1 = BPVVFAV.VAL.FAV_DATA[1-1].AC_LEVEL;
        BPRFFAV.STATUS_1 = BPVVFAV.VAL.FAV_DATA[1-1].STATUS;
        BPRFFAV.GROUP_NO_1 = BPVVFAV.VAL.FAV_DATA[1-1].GROUP;
        BPRFFAV.SEGMENT_1 = BPVVFAV.VAL.FAV_DATA[1-1].SEGMENT;
        BPRFFAV.PROD_CODE_1 = BPVVFAV.VAL.FAV_DATA[1-1].PROD_CODE;
        BPRFFAV.BR_1 = BPVVFAV.VAL.FAV_DATA[1-1].BR;
        BPRFFAV.FAV_AMT_1 = BPVVFAV.VAL.FAV_DATA[1-1].FAV_AMT;
        BPRFFAV.FAV_PCT_1 = BPVVFAV.VAL.FAV_DATA[1-1].FAV_PCT;
        BPRFFAV.FAV_CNT_1 = BPVVFAV.VAL.FAV_DATA[1-1].FAV_CNT;
        BPRFFAV.STR_AMT_2 = BPVVFAV.VAL.FAV_DATA[2-1].STR_AMT;
        BPRFFAV.STR_CNT_2 = BPVVFAV.VAL.FAV_DATA[2-1].STR_CNT;
        BPRFFAV.STR_TIME_2 = BPVVFAV.VAL.FAV_DATA[2-1].STR_TIME;
        BPRFFAV.END_TIME_2 = BPVVFAV.VAL.FAV_DATA[2-1].END_TIME;
        BPRFFAV.CI_LEVEL_2 = BPVVFAV.VAL.FAV_DATA[2-1].CI_LEVEL;
        BPRFFAV.AC_LEVEL_2 = BPVVFAV.VAL.FAV_DATA[2-1].AC_LEVEL;
        BPRFFAV.STATUS_2 = BPVVFAV.VAL.FAV_DATA[2-1].STATUS;
        BPRFFAV.GROUP_NO_2 = BPVVFAV.VAL.FAV_DATA[2-1].GROUP;
        BPRFFAV.SEGMENT_2 = BPVVFAV.VAL.FAV_DATA[2-1].SEGMENT;
        BPRFFAV.PROD_CODE_2 = BPVVFAV.VAL.FAV_DATA[2-1].PROD_CODE;
        BPRFFAV.BR_2 = BPVVFAV.VAL.FAV_DATA[2-1].BR;
        BPRFFAV.FAV_AMT_2 = BPVVFAV.VAL.FAV_DATA[2-1].FAV_AMT;
        BPRFFAV.FAV_PCT_2 = BPVVFAV.VAL.FAV_DATA[2-1].FAV_PCT;
        BPRFFAV.FAV_CNT_2 = BPVVFAV.VAL.FAV_DATA[2-1].FAV_CNT;
        BPRFFAV.STR_AMT_3 = BPVVFAV.VAL.FAV_DATA[3-1].STR_AMT;
        BPRFFAV.STR_CNT_3 = BPVVFAV.VAL.FAV_DATA[3-1].STR_CNT;
        BPRFFAV.STR_TIME_3 = BPVVFAV.VAL.FAV_DATA[3-1].STR_TIME;
        BPRFFAV.END_TIME_3 = BPVVFAV.VAL.FAV_DATA[3-1].END_TIME;
        BPRFFAV.CI_LEVEL_3 = BPVVFAV.VAL.FAV_DATA[3-1].CI_LEVEL;
        BPRFFAV.AC_LEVEL_3 = BPVVFAV.VAL.FAV_DATA[3-1].AC_LEVEL;
        BPRFFAV.STATUS_3 = BPVVFAV.VAL.FAV_DATA[3-1].STATUS;
        BPRFFAV.GROUP_NO_3 = BPVVFAV.VAL.FAV_DATA[3-1].GROUP;
        BPRFFAV.SEGMENT_3 = BPVVFAV.VAL.FAV_DATA[3-1].SEGMENT;
        BPRFFAV.PROD_CODE_3 = BPVVFAV.VAL.FAV_DATA[3-1].PROD_CODE;
        BPRFFAV.BR_3 = BPVVFAV.VAL.FAV_DATA[3-1].BR;
        BPRFFAV.FAV_AMT_3 = BPVVFAV.VAL.FAV_DATA[3-1].FAV_AMT;
        BPRFFAV.FAV_PCT_3 = BPVVFAV.VAL.FAV_DATA[3-1].FAV_PCT;
        BPRFFAV.FAV_CNT_3 = BPVVFAV.VAL.FAV_DATA[3-1].FAV_CNT;
        BPRFFAV.STR_AMT_4 = BPVVFAV.VAL.FAV_DATA[4-1].STR_AMT;
        BPRFFAV.STR_CNT_4 = BPVVFAV.VAL.FAV_DATA[4-1].STR_CNT;
        BPRFFAV.STR_TIME_4 = BPVVFAV.VAL.FAV_DATA[4-1].STR_TIME;
        BPRFFAV.END_TIME_4 = BPVVFAV.VAL.FAV_DATA[4-1].END_TIME;
        BPRFFAV.CI_LEVEL_4 = BPVVFAV.VAL.FAV_DATA[4-1].CI_LEVEL;
        BPRFFAV.AC_LEVEL_4 = BPVVFAV.VAL.FAV_DATA[4-1].AC_LEVEL;
        BPRFFAV.STATUS_4 = BPVVFAV.VAL.FAV_DATA[4-1].STATUS;
        BPRFFAV.GROUP_NO_4 = BPVVFAV.VAL.FAV_DATA[4-1].GROUP;
        BPRFFAV.SEGMENT_4 = BPVVFAV.VAL.FAV_DATA[4-1].SEGMENT;
        BPRFFAV.PROD_CODE_4 = BPVVFAV.VAL.FAV_DATA[4-1].PROD_CODE;
        BPRFFAV.BR_4 = BPVVFAV.VAL.FAV_DATA[4-1].BR;
        BPRFFAV.FAV_AMT_4 = BPVVFAV.VAL.FAV_DATA[4-1].FAV_AMT;
        BPRFFAV.FAV_PCT_4 = BPVVFAV.VAL.FAV_DATA[4-1].FAV_PCT;
        BPRFFAV.FAV_CNT_4 = BPVVFAV.VAL.FAV_DATA[4-1].FAV_CNT;
        BPRFFAV.STR_AMT_5 = BPVVFAV.VAL.FAV_DATA[5-1].STR_AMT;
        BPRFFAV.STR_CNT_5 = BPVVFAV.VAL.FAV_DATA[5-1].STR_CNT;
        BPRFFAV.STR_TIME_5 = BPVVFAV.VAL.FAV_DATA[5-1].STR_TIME;
        BPRFFAV.END_TIME_5 = BPVVFAV.VAL.FAV_DATA[5-1].END_TIME;
        BPRFFAV.CI_LEVEL_5 = BPVVFAV.VAL.FAV_DATA[5-1].CI_LEVEL;
        BPRFFAV.AC_LEVEL_5 = BPVVFAV.VAL.FAV_DATA[5-1].AC_LEVEL;
        BPRFFAV.STATUS_5 = BPVVFAV.VAL.FAV_DATA[5-1].STATUS;
        BPRFFAV.GROUP_NO_5 = BPVVFAV.VAL.FAV_DATA[5-1].GROUP;
        BPRFFAV.SEGMENT_5 = BPVVFAV.VAL.FAV_DATA[5-1].SEGMENT;
        BPRFFAV.PROD_CODE_5 = BPVVFAV.VAL.FAV_DATA[5-1].PROD_CODE;
        BPRFFAV.BR_5 = BPVVFAV.VAL.FAV_DATA[5-1].BR;
        BPRFFAV.FAV_AMT_5 = BPVVFAV.VAL.FAV_DATA[5-1].FAV_AMT;
        BPRFFAV.FAV_PCT_5 = BPVVFAV.VAL.FAV_DATA[5-1].FAV_PCT;
        BPRFFAV.FAV_CNT_5 = BPVVFAV.VAL.FAV_DATA[5-1].FAV_CNT;
        BPRFFAV.STR_AMT_6 = BPVVFAV.VAL.FAV_DATA[6-1].STR_AMT;
        BPRFFAV.STR_CNT_6 = BPVVFAV.VAL.FAV_DATA[6-1].STR_CNT;
        BPRFFAV.STR_TIME_6 = BPVVFAV.VAL.FAV_DATA[6-1].STR_TIME;
        BPRFFAV.END_TIME_6 = BPVVFAV.VAL.FAV_DATA[6-1].END_TIME;
        BPRFFAV.CI_LEVEL_6 = BPVVFAV.VAL.FAV_DATA[6-1].CI_LEVEL;
        BPRFFAV.AC_LEVEL_6 = BPVVFAV.VAL.FAV_DATA[6-1].AC_LEVEL;
        BPRFFAV.STATUS_6 = BPVVFAV.VAL.FAV_DATA[6-1].STATUS;
        BPRFFAV.GROUP_NO_6 = BPVVFAV.VAL.FAV_DATA[6-1].GROUP;
        BPRFFAV.SEGMENT_6 = BPVVFAV.VAL.FAV_DATA[6-1].SEGMENT;
        BPRFFAV.PROD_CODE_6 = BPVVFAV.VAL.FAV_DATA[6-1].PROD_CODE;
        BPRFFAV.BR_6 = BPVVFAV.VAL.FAV_DATA[6-1].BR;
        BPRFFAV.FAV_AMT_6 = BPVVFAV.VAL.FAV_DATA[6-1].FAV_AMT;
        BPRFFAV.FAV_PCT_6 = BPVVFAV.VAL.FAV_DATA[6-1].FAV_PCT;
        BPRFFAV.FAV_CNT_6 = BPVVFAV.VAL.FAV_DATA[6-1].FAV_CNT;
        BPRFFAV.STR_AMT_7 = BPVVFAV.VAL.FAV_DATA[7-1].STR_AMT;
        BPRFFAV.STR_CNT_7 = BPVVFAV.VAL.FAV_DATA[7-1].STR_CNT;
        BPRFFAV.STR_TIME_7 = BPVVFAV.VAL.FAV_DATA[7-1].STR_TIME;
        BPRFFAV.END_TIME_7 = BPVVFAV.VAL.FAV_DATA[7-1].END_TIME;
        BPRFFAV.CI_LEVEL_7 = BPVVFAV.VAL.FAV_DATA[7-1].CI_LEVEL;
        BPRFFAV.AC_LEVEL_7 = BPVVFAV.VAL.FAV_DATA[7-1].AC_LEVEL;
        BPRFFAV.STATUS_7 = BPVVFAV.VAL.FAV_DATA[7-1].STATUS;
        BPRFFAV.GROUP_NO_7 = BPVVFAV.VAL.FAV_DATA[7-1].GROUP;
        BPRFFAV.SEGMENT_7 = BPVVFAV.VAL.FAV_DATA[7-1].SEGMENT;
        BPRFFAV.PROD_CODE_7 = BPVVFAV.VAL.FAV_DATA[7-1].PROD_CODE;
        BPRFFAV.BR_7 = BPVVFAV.VAL.FAV_DATA[7-1].BR;
        BPRFFAV.FAV_AMT_7 = BPVVFAV.VAL.FAV_DATA[7-1].FAV_AMT;
        BPRFFAV.FAV_PCT_7 = BPVVFAV.VAL.FAV_DATA[7-1].FAV_PCT;
        BPRFFAV.FAV_CNT_7 = BPVVFAV.VAL.FAV_DATA[7-1].FAV_CNT;
        BPRFFAV.STR_AMT_8 = BPVVFAV.VAL.FAV_DATA[8-1].STR_AMT;
        BPRFFAV.STR_CNT_8 = BPVVFAV.VAL.FAV_DATA[8-1].STR_CNT;
        BPRFFAV.STR_TIME_8 = BPVVFAV.VAL.FAV_DATA[8-1].STR_TIME;
        BPRFFAV.END_TIME_8 = BPVVFAV.VAL.FAV_DATA[8-1].END_TIME;
        BPRFFAV.CI_LEVEL_8 = BPVVFAV.VAL.FAV_DATA[8-1].CI_LEVEL;
        BPRFFAV.AC_LEVEL_8 = BPVVFAV.VAL.FAV_DATA[8-1].AC_LEVEL;
        BPRFFAV.STATUS_8 = BPVVFAV.VAL.FAV_DATA[8-1].STATUS;
        BPRFFAV.GROUP_NO_8 = BPVVFAV.VAL.FAV_DATA[8-1].GROUP;
        BPRFFAV.SEGMENT_8 = BPVVFAV.VAL.FAV_DATA[8-1].SEGMENT;
        BPRFFAV.PROD_CODE_8 = BPVVFAV.VAL.FAV_DATA[8-1].PROD_CODE;
        BPRFFAV.BR_8 = BPVVFAV.VAL.FAV_DATA[8-1].BR;
        BPRFFAV.FAV_AMT_8 = BPVVFAV.VAL.FAV_DATA[8-1].FAV_AMT;
        BPRFFAV.FAV_PCT_8 = BPVVFAV.VAL.FAV_DATA[8-1].FAV_PCT;
        BPRFFAV.FAV_CNT_8 = BPVVFAV.VAL.FAV_DATA[8-1].FAV_CNT;
        BPRFFAV.STR_AMT_9 = BPVVFAV.VAL.FAV_DATA[9-1].STR_AMT;
        BPRFFAV.STR_CNT_9 = BPVVFAV.VAL.FAV_DATA[9-1].STR_CNT;
        BPRFFAV.STR_TIME_9 = BPVVFAV.VAL.FAV_DATA[9-1].STR_TIME;
        BPRFFAV.END_TIME_9 = BPVVFAV.VAL.FAV_DATA[9-1].END_TIME;
        BPRFFAV.CI_LEVEL_9 = BPVVFAV.VAL.FAV_DATA[9-1].CI_LEVEL;
        BPRFFAV.AC_LEVEL_9 = BPVVFAV.VAL.FAV_DATA[9-1].AC_LEVEL;
        BPRFFAV.STATUS_9 = BPVVFAV.VAL.FAV_DATA[9-1].STATUS;
        BPRFFAV.GROUP_NO_9 = BPVVFAV.VAL.FAV_DATA[9-1].GROUP;
        BPRFFAV.SEGMENT_9 = BPVVFAV.VAL.FAV_DATA[9-1].SEGMENT;
        BPRFFAV.PROD_CODE_9 = BPVVFAV.VAL.FAV_DATA[9-1].PROD_CODE;
        BPRFFAV.BR_9 = BPVVFAV.VAL.FAV_DATA[9-1].BR;
        BPRFFAV.FAV_AMT_9 = BPVVFAV.VAL.FAV_DATA[9-1].FAV_AMT;
        BPRFFAV.FAV_PCT_9 = BPVVFAV.VAL.FAV_DATA[9-1].FAV_PCT;
        BPRFFAV.FAV_CNT_9 = BPVVFAV.VAL.FAV_DATA[9-1].FAV_CNT;
        BPRFFAV.STR_AMT_10 = BPVVFAV.VAL.FAV_DATA[10-1].STR_AMT;
        BPRFFAV.STR_CNT_10 = BPVVFAV.VAL.FAV_DATA[10-1].STR_CNT;
        BPRFFAV.STR_TIME_10 = BPVVFAV.VAL.FAV_DATA[10-1].STR_TIME;
        BPRFFAV.END_TIME_10 = BPVVFAV.VAL.FAV_DATA[10-1].END_TIME;
        BPRFFAV.CI_LEVEL_10 = BPVVFAV.VAL.FAV_DATA[10-1].CI_LEVEL;
        BPRFFAV.AC_LEVEL_10 = BPVVFAV.VAL.FAV_DATA[10-1].AC_LEVEL;
        BPRFFAV.STATUS_10 = BPVVFAV.VAL.FAV_DATA[10-1].STATUS;
        BPRFFAV.GROUP_NO_10 = BPVVFAV.VAL.FAV_DATA[10-1].GROUP;
        BPRFFAV.SEGMENT_10 = BPVVFAV.VAL.FAV_DATA[10-1].SEGMENT;
        BPRFFAV.PROD_CODE_10 = BPVVFAV.VAL.FAV_DATA[10-1].PROD_CODE;
        BPRFFAV.BR_10 = BPVVFAV.VAL.FAV_DATA[10-1].BR;
        BPRFFAV.FAV_AMT_10 = BPVVFAV.VAL.FAV_DATA[10-1].FAV_AMT;
        BPRFFAV.FAV_PCT_10 = BPVVFAV.VAL.FAV_DATA[10-1].FAV_PCT;
        BPRFFAV.FAV_CNT_10 = BPVVFAV.VAL.FAV_DATA[10-1].FAV_CNT;
    }
    public void R000_TRANS_DATA_TO_BPVFFAV() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPVVFAV);
        BPVVFAV.KEY.PRFR_CODE = BPRFFAV.KEY.PRFR_CODE;
        BPVVFAV.DATE.EFF_DATE = BPRFFAV.EFF_DATE;
        BPVVFAV.DATE.EXP_DATE = BPRFFAV.EXP_DATE;
        BPVVFAV.VAL.DESC = BPRFFAV.FFAV_DESC;
        BPVVFAV.VAL.FAV_TYPE = BPRFFAV.FAV_TYPE;
        BPVVFAV.VAL.FAV_PERIOD = BPRFFAV.FAV_PERIOD;
        BPVVFAV.VAL.MAX_FAV_AMT = BPRFFAV.MAX_FAV_AMT;
        BPVVFAV.VAL.MAX_FAV_PCT = BPRFFAV.MAX_FAV_PCT;
        BPVVFAV.VAL.FAV_COLL = BPRFFAV.FAV_COLL;
        BPVVFAV.VAL.FAV_CPNT = BPRFFAV.FAV_CPNT;
        BPVVFAV.VAL.CAL_SOURCE = BPRFFAV.CAL_SOURCE;
        BPVVFAV.VAL.CAL_CYC = BPRFFAV.CAL_CYC;
        BPVVFAV.VAL.CYC_NUM = BPRFFAV.CYC_NUM;
        BPVVFAV.VAL.COLL_TYPE = BPRFFAV.COLL_TYPE;
        BPVVFAV.VAL.FAV_SPLT_FLG = BPRFFAV.FAV_SPLT_FLG;
        BPVVFAV.VAL.ADJ_TYP = BPRFFAV.ADJ_TYP;
        BPVVFAV.VAL.DIF_VAL = BPRFFAV.DIF_VAL;
        BPVVFAV.VAL.FAV_DATA[1-1].STR_AMT = BPRFFAV.STR_AMT_1;
        BPVVFAV.VAL.FAV_DATA[1-1].STR_CNT = BPRFFAV.STR_CNT_1;
        BPVVFAV.VAL.FAV_DATA[1-1].STR_TIME = BPRFFAV.STR_TIME_1;
        BPVVFAV.VAL.FAV_DATA[1-1].END_TIME = BPRFFAV.END_TIME_1;
        BPVVFAV.VAL.FAV_DATA[1-1].CI_LEVEL = BPRFFAV.CI_LEVEL_1;
        BPVVFAV.VAL.FAV_DATA[1-1].AC_LEVEL = BPRFFAV.AC_LEVEL_1;
        BPVVFAV.VAL.FAV_DATA[1-1].STATUS = BPRFFAV.STATUS_1;
        BPVVFAV.VAL.FAV_DATA[1-1].GROUP = BPRFFAV.GROUP_NO_1;
        BPVVFAV.VAL.FAV_DATA[1-1].SEGMENT = BPRFFAV.SEGMENT_1;
        BPVVFAV.VAL.FAV_DATA[1-1].PROD_CODE = BPRFFAV.PROD_CODE_1;
        BPVVFAV.VAL.FAV_DATA[1-1].BR = BPRFFAV.BR_1;
        BPVVFAV.VAL.FAV_DATA[1-1].FAV_AMT = BPRFFAV.FAV_AMT_1;
        BPVVFAV.VAL.FAV_DATA[1-1].FAV_PCT = BPRFFAV.FAV_PCT_1;
        BPVVFAV.VAL.FAV_DATA[1-1].FAV_CNT = BPRFFAV.FAV_CNT_1;
        BPVVFAV.VAL.FAV_DATA[2-1].STR_AMT = BPRFFAV.STR_AMT_2;
        BPVVFAV.VAL.FAV_DATA[2-1].STR_CNT = BPRFFAV.STR_CNT_2;
        BPVVFAV.VAL.FAV_DATA[2-1].STR_TIME = BPRFFAV.STR_TIME_2;
        BPVVFAV.VAL.FAV_DATA[2-1].END_TIME = BPRFFAV.END_TIME_2;
        BPVVFAV.VAL.FAV_DATA[2-1].CI_LEVEL = BPRFFAV.CI_LEVEL_2;
        BPVVFAV.VAL.FAV_DATA[2-1].AC_LEVEL = BPRFFAV.AC_LEVEL_2;
        BPVVFAV.VAL.FAV_DATA[2-1].STATUS = BPRFFAV.STATUS_2;
        BPVVFAV.VAL.FAV_DATA[2-1].GROUP = BPRFFAV.GROUP_NO_2;
        BPVVFAV.VAL.FAV_DATA[2-1].SEGMENT = BPRFFAV.SEGMENT_2;
        BPVVFAV.VAL.FAV_DATA[2-1].PROD_CODE = BPRFFAV.PROD_CODE_2;
        BPVVFAV.VAL.FAV_DATA[2-1].BR = BPRFFAV.BR_2;
        BPVVFAV.VAL.FAV_DATA[2-1].FAV_AMT = BPRFFAV.FAV_AMT_2;
        BPVVFAV.VAL.FAV_DATA[2-1].FAV_PCT = BPRFFAV.FAV_PCT_2;
        BPVVFAV.VAL.FAV_DATA[2-1].FAV_CNT = BPRFFAV.FAV_CNT_2;
        BPVVFAV.VAL.FAV_DATA[3-1].STR_AMT = BPRFFAV.STR_AMT_3;
        BPVVFAV.VAL.FAV_DATA[3-1].STR_CNT = BPRFFAV.STR_CNT_3;
        BPVVFAV.VAL.FAV_DATA[3-1].STR_TIME = BPRFFAV.STR_TIME_3;
        BPVVFAV.VAL.FAV_DATA[3-1].END_TIME = BPRFFAV.END_TIME_3;
        BPVVFAV.VAL.FAV_DATA[3-1].CI_LEVEL = BPRFFAV.CI_LEVEL_3;
        BPVVFAV.VAL.FAV_DATA[3-1].AC_LEVEL = BPRFFAV.AC_LEVEL_3;
        BPVVFAV.VAL.FAV_DATA[3-1].STATUS = BPRFFAV.STATUS_3;
        BPVVFAV.VAL.FAV_DATA[3-1].GROUP = BPRFFAV.GROUP_NO_3;
        BPVVFAV.VAL.FAV_DATA[3-1].SEGMENT = BPRFFAV.SEGMENT_3;
        BPVVFAV.VAL.FAV_DATA[3-1].PROD_CODE = BPRFFAV.PROD_CODE_3;
        BPVVFAV.VAL.FAV_DATA[3-1].BR = BPRFFAV.BR_3;
        BPVVFAV.VAL.FAV_DATA[3-1].FAV_AMT = BPRFFAV.FAV_AMT_3;
        BPVVFAV.VAL.FAV_DATA[3-1].FAV_PCT = BPRFFAV.FAV_PCT_3;
        BPVVFAV.VAL.FAV_DATA[3-1].FAV_CNT = BPRFFAV.FAV_CNT_3;
        BPVVFAV.VAL.FAV_DATA[4-1].STR_AMT = BPRFFAV.STR_AMT_4;
        BPVVFAV.VAL.FAV_DATA[4-1].STR_CNT = BPRFFAV.STR_CNT_4;
        BPVVFAV.VAL.FAV_DATA[4-1].STR_TIME = BPRFFAV.STR_TIME_4;
        BPVVFAV.VAL.FAV_DATA[4-1].END_TIME = BPRFFAV.END_TIME_4;
        BPVVFAV.VAL.FAV_DATA[4-1].CI_LEVEL = BPRFFAV.CI_LEVEL_4;
        BPVVFAV.VAL.FAV_DATA[4-1].AC_LEVEL = BPRFFAV.AC_LEVEL_4;
        BPVVFAV.VAL.FAV_DATA[4-1].STATUS = BPRFFAV.STATUS_4;
        BPVVFAV.VAL.FAV_DATA[4-1].GROUP = BPRFFAV.GROUP_NO_4;
        BPVVFAV.VAL.FAV_DATA[4-1].SEGMENT = BPRFFAV.SEGMENT_4;
        BPVVFAV.VAL.FAV_DATA[4-1].PROD_CODE = BPRFFAV.PROD_CODE_4;
        BPVVFAV.VAL.FAV_DATA[4-1].BR = BPRFFAV.BR_4;
        BPVVFAV.VAL.FAV_DATA[4-1].FAV_AMT = BPRFFAV.FAV_AMT_4;
        BPVVFAV.VAL.FAV_DATA[4-1].FAV_PCT = BPRFFAV.FAV_PCT_4;
        BPVVFAV.VAL.FAV_DATA[4-1].FAV_CNT = BPRFFAV.FAV_CNT_4;
        BPVVFAV.VAL.FAV_DATA[5-1].STR_AMT = BPRFFAV.STR_AMT_5;
        BPVVFAV.VAL.FAV_DATA[5-1].STR_CNT = BPRFFAV.STR_CNT_5;
        BPVVFAV.VAL.FAV_DATA[5-1].STR_TIME = BPRFFAV.STR_TIME_5;
        BPVVFAV.VAL.FAV_DATA[5-1].END_TIME = BPRFFAV.END_TIME_5;
        BPVVFAV.VAL.FAV_DATA[5-1].CI_LEVEL = BPRFFAV.CI_LEVEL_5;
        BPVVFAV.VAL.FAV_DATA[5-1].AC_LEVEL = BPRFFAV.AC_LEVEL_5;
        BPVVFAV.VAL.FAV_DATA[5-1].STATUS = BPRFFAV.STATUS_5;
        BPVVFAV.VAL.FAV_DATA[5-1].GROUP = BPRFFAV.GROUP_NO_5;
        BPVVFAV.VAL.FAV_DATA[5-1].SEGMENT = BPRFFAV.SEGMENT_5;
        BPVVFAV.VAL.FAV_DATA[5-1].PROD_CODE = BPRFFAV.PROD_CODE_5;
        BPVVFAV.VAL.FAV_DATA[5-1].BR = BPRFFAV.BR_5;
        BPVVFAV.VAL.FAV_DATA[5-1].FAV_AMT = BPRFFAV.FAV_AMT_5;
        BPVVFAV.VAL.FAV_DATA[5-1].FAV_PCT = BPRFFAV.FAV_PCT_5;
        BPVVFAV.VAL.FAV_DATA[5-1].FAV_CNT = BPRFFAV.FAV_CNT_5;
        BPVVFAV.VAL.FAV_DATA[6-1].STR_AMT = BPRFFAV.STR_AMT_6;
        BPVVFAV.VAL.FAV_DATA[6-1].STR_CNT = BPRFFAV.STR_CNT_6;
        BPVVFAV.VAL.FAV_DATA[6-1].STR_TIME = BPRFFAV.STR_TIME_6;
        BPVVFAV.VAL.FAV_DATA[6-1].END_TIME = BPRFFAV.END_TIME_6;
        BPVVFAV.VAL.FAV_DATA[6-1].CI_LEVEL = BPRFFAV.CI_LEVEL_6;
        BPVVFAV.VAL.FAV_DATA[6-1].AC_LEVEL = BPRFFAV.AC_LEVEL_6;
        BPVVFAV.VAL.FAV_DATA[6-1].STATUS = BPRFFAV.STATUS_6;
        BPVVFAV.VAL.FAV_DATA[6-1].GROUP = BPRFFAV.GROUP_NO_6;
        BPVVFAV.VAL.FAV_DATA[6-1].SEGMENT = BPRFFAV.SEGMENT_6;
        BPVVFAV.VAL.FAV_DATA[6-1].PROD_CODE = BPRFFAV.PROD_CODE_6;
        BPVVFAV.VAL.FAV_DATA[6-1].BR = BPRFFAV.BR_6;
        BPVVFAV.VAL.FAV_DATA[6-1].FAV_AMT = BPRFFAV.FAV_AMT_6;
        BPVVFAV.VAL.FAV_DATA[6-1].FAV_PCT = BPRFFAV.FAV_PCT_6;
        BPVVFAV.VAL.FAV_DATA[6-1].FAV_CNT = BPRFFAV.FAV_CNT_6;
        BPVVFAV.VAL.FAV_DATA[7-1].STR_AMT = BPRFFAV.STR_AMT_7;
        BPVVFAV.VAL.FAV_DATA[7-1].STR_CNT = BPRFFAV.STR_CNT_7;
        BPVVFAV.VAL.FAV_DATA[7-1].STR_TIME = BPRFFAV.STR_TIME_7;
        BPVVFAV.VAL.FAV_DATA[7-1].END_TIME = BPRFFAV.END_TIME_7;
        BPVVFAV.VAL.FAV_DATA[7-1].CI_LEVEL = BPRFFAV.CI_LEVEL_7;
        BPVVFAV.VAL.FAV_DATA[7-1].AC_LEVEL = BPRFFAV.AC_LEVEL_7;
        BPVVFAV.VAL.FAV_DATA[7-1].STATUS = BPRFFAV.STATUS_7;
        BPVVFAV.VAL.FAV_DATA[7-1].GROUP = BPRFFAV.GROUP_NO_7;
        BPVVFAV.VAL.FAV_DATA[7-1].SEGMENT = BPRFFAV.SEGMENT_7;
        BPVVFAV.VAL.FAV_DATA[7-1].PROD_CODE = BPRFFAV.PROD_CODE_7;
        BPVVFAV.VAL.FAV_DATA[7-1].BR = BPRFFAV.BR_7;
        BPVVFAV.VAL.FAV_DATA[7-1].FAV_AMT = BPRFFAV.FAV_AMT_7;
        BPVVFAV.VAL.FAV_DATA[7-1].FAV_PCT = BPRFFAV.FAV_PCT_7;
        BPVVFAV.VAL.FAV_DATA[7-1].FAV_CNT = BPRFFAV.FAV_CNT_7;
        BPVVFAV.VAL.FAV_DATA[8-1].STR_AMT = BPRFFAV.STR_AMT_8;
        BPVVFAV.VAL.FAV_DATA[8-1].STR_CNT = BPRFFAV.STR_CNT_8;
        BPVVFAV.VAL.FAV_DATA[8-1].STR_TIME = BPRFFAV.STR_TIME_8;
        BPVVFAV.VAL.FAV_DATA[8-1].END_TIME = BPRFFAV.END_TIME_8;
        BPVVFAV.VAL.FAV_DATA[8-1].CI_LEVEL = BPRFFAV.CI_LEVEL_8;
        BPVVFAV.VAL.FAV_DATA[8-1].AC_LEVEL = BPRFFAV.AC_LEVEL_8;
        BPVVFAV.VAL.FAV_DATA[8-1].STATUS = BPRFFAV.STATUS_8;
        BPVVFAV.VAL.FAV_DATA[8-1].GROUP = BPRFFAV.GROUP_NO_8;
        BPVVFAV.VAL.FAV_DATA[8-1].SEGMENT = BPRFFAV.SEGMENT_8;
        BPVVFAV.VAL.FAV_DATA[8-1].PROD_CODE = BPRFFAV.PROD_CODE_8;
        BPVVFAV.VAL.FAV_DATA[8-1].BR = BPRFFAV.BR_8;
        BPVVFAV.VAL.FAV_DATA[8-1].FAV_AMT = BPRFFAV.FAV_AMT_8;
        BPVVFAV.VAL.FAV_DATA[8-1].FAV_PCT = BPRFFAV.FAV_PCT_8;
        BPVVFAV.VAL.FAV_DATA[8-1].FAV_CNT = BPRFFAV.FAV_CNT_8;
        BPVVFAV.VAL.FAV_DATA[9-1].STR_AMT = BPRFFAV.STR_AMT_9;
        BPVVFAV.VAL.FAV_DATA[9-1].STR_CNT = BPRFFAV.STR_CNT_9;
        BPVVFAV.VAL.FAV_DATA[9-1].STR_TIME = BPRFFAV.STR_TIME_9;
        BPVVFAV.VAL.FAV_DATA[9-1].END_TIME = BPRFFAV.END_TIME_9;
        BPVVFAV.VAL.FAV_DATA[9-1].CI_LEVEL = BPRFFAV.CI_LEVEL_9;
        BPVVFAV.VAL.FAV_DATA[9-1].AC_LEVEL = BPRFFAV.AC_LEVEL_9;
        BPVVFAV.VAL.FAV_DATA[9-1].STATUS = BPRFFAV.STATUS_9;
        BPVVFAV.VAL.FAV_DATA[9-1].GROUP = BPRFFAV.GROUP_NO_9;
        BPVVFAV.VAL.FAV_DATA[9-1].SEGMENT = BPRFFAV.SEGMENT_9;
        BPVVFAV.VAL.FAV_DATA[9-1].PROD_CODE = BPRFFAV.PROD_CODE_9;
        BPVVFAV.VAL.FAV_DATA[9-1].BR = BPRFFAV.BR_9;
        BPVVFAV.VAL.FAV_DATA[9-1].FAV_AMT = BPRFFAV.FAV_AMT_9;
        BPVVFAV.VAL.FAV_DATA[9-1].FAV_PCT = BPRFFAV.FAV_PCT_9;
        BPVVFAV.VAL.FAV_DATA[9-1].FAV_CNT = BPRFFAV.FAV_CNT_9;
        BPVVFAV.VAL.FAV_DATA[10-1].STR_AMT = BPRFFAV.STR_AMT_10;
        BPVVFAV.VAL.FAV_DATA[10-1].STR_CNT = BPRFFAV.STR_CNT_10;
        BPVVFAV.VAL.FAV_DATA[10-1].STR_TIME = BPRFFAV.STR_TIME_10;
        BPVVFAV.VAL.FAV_DATA[10-1].END_TIME = BPRFFAV.END_TIME_10;
        BPVVFAV.VAL.FAV_DATA[10-1].CI_LEVEL = BPRFFAV.CI_LEVEL_10;
        BPVVFAV.VAL.FAV_DATA[10-1].AC_LEVEL = BPRFFAV.AC_LEVEL_10;
        BPVVFAV.VAL.FAV_DATA[10-1].STATUS = BPRFFAV.STATUS_10;
        BPVVFAV.VAL.FAV_DATA[10-1].GROUP = BPRFFAV.GROUP_NO_10;
        BPVVFAV.VAL.FAV_DATA[10-1].SEGMENT = BPRFFAV.SEGMENT_10;
        BPVVFAV.VAL.FAV_DATA[10-1].PROD_CODE = BPRFFAV.PROD_CODE_10;
        BPVVFAV.VAL.FAV_DATA[10-1].BR = BPRFFAV.BR_10;
        BPVVFAV.VAL.FAV_DATA[10-1].FAV_AMT = BPRFFAV.FAV_AMT_10;
        BPVVFAV.VAL.FAV_DATA[10-1].FAV_PCT = BPRFFAV.FAV_PCT_10;
        BPVVFAV.VAL.FAV_DATA[10-1].FAV_CNT = BPRFFAV.FAV_CNT_10;
    }
    public void T000_READ_BPTFFAV() throws IOException,SQLException,Exception {
        BPTFFAV_RD = new DBParm();
        BPTFFAV_RD.TableName = "BPTFFAV";
        IBS.READ(SCCGWA, BPRFFAV, BPTFFAV_RD);
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.DBIO_FLG);
        if (SCCGWA.COMM_AREA.DBIO_FLG == '0') {
            BPCTFFAV.RETURN_INFO = 'F';
        } else if (SCCGWA.COMM_AREA.DBIO_FLG == '2') {
            BPCTFFAV.RETURN_INFO = 'D';
        } else if (SCCGWA.COMM_AREA.DBIO_FLG == '1') {
            BPCTFFAV.RETURN_INFO = 'N';
        } else {
            IBS.init(SCCGWA, SCCEXCP);
            SCCEXCP.MSG_TEXT.KEY_OR_OTHER = "INVALID FLG (" + SCCGWA.COMM_AREA.DBIO_FLG + ")";
            CEP.EXCP(SCCGWA, SCCEXCP.MSG_TEXT.KEY_OR_OTHER);
        }
    }
    public void T000_STARTBR_BPTFFAV() throws IOException,SQLException,Exception {
        BPTFFAV_BR.rp = new DBParm();
        BPTFFAV_BR.rp.TableName = "BPTFFAV";
        IBS.STARTBR(SCCGWA, BPRFFAV, BPTFFAV_BR);
        if (SCCGWA.COMM_AREA.DBIO_FLG == '0') {
            BPCTFFAV.RETURN_INFO = 'F';
        } else if (SCCGWA.COMM_AREA.DBIO_FLG == '1') {
            BPCTFFAV.RETURN_INFO = 'N';
        } else {
            IBS.init(SCCGWA, SCCEXCP);
            SCCEXCP.MSG_TEXT.KEY_OR_OTHER = "INVALID FLG (" + SCCGWA.COMM_AREA.DBIO_FLG + ")";
            CEP.EXCP(SCCGWA, SCCEXCP.MSG_TEXT.KEY_OR_OTHER);
        }
    }
    public void T000_READNEXT_BPTFFAV() throws IOException,SQLException,Exception {
        IBS.READNEXT(SCCGWA, BPRFFAV, this, BPTFFAV_BR);
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.DBIO_FLG);
        if (SCCGWA.COMM_AREA.DBIO_FLG == '0') {
            BPCTFFAV.RETURN_INFO = 'F';
        } else if (SCCGWA.COMM_AREA.DBIO_FLG == '1') {
            BPCTFFAV.RETURN_INFO = 'N';
        } else {
            IBS.init(SCCGWA, SCCEXCP);
            SCCEXCP.MSG_TEXT.KEY_OR_OTHER = "INVALID FLG (" + SCCGWA.COMM_AREA.DBIO_FLG + ")";
            CEP.EXCP(SCCGWA, SCCEXCP.MSG_TEXT.KEY_OR_OTHER);
        }
    }
    public void T000_ENDBR_BPTFFAV() throws IOException,SQLException,Exception {
        IBS.ENDBR(SCCGWA, BPTFFAV_BR);
    }
    public void T000_WRITE_BPTFFAV() throws IOException,SQLException,Exception {
        BPTFFAV_RD = new DBParm();
        BPTFFAV_RD.TableName = "BPTFFAV";
        BPTFFAV_RD.errhdl = true;
        IBS.WRITE(SCCGWA, BPRFFAV, BPTFFAV_RD);
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.DBIO_FLG);
        if (SCCGWA.COMM_AREA.DBIO_FLG == '0') {
            BPCTFFAV.RETURN_INFO = 'F';
        } else if (SCCGWA.COMM_AREA.DBIO_FLG == '2') {
            BPCTFFAV.RETURN_INFO = 'D';
        } else {
            IBS.init(SCCGWA, SCCEXCP);
            SCCEXCP.MSG_TEXT.KEY_OR_OTHER = "INVALID FLG (" + SCCGWA.COMM_AREA.DBIO_FLG + ")";
            CEP.EXCP(SCCGWA, SCCEXCP.MSG_TEXT.KEY_OR_OTHER);
        }
    }
    public void T000_READ_BPTFFAV_UPD() throws IOException,SQLException,Exception {
        BPTFFAV_RD = new DBParm();
        BPTFFAV_RD.TableName = "BPTFFAV";
        BPTFFAV_RD.upd = true;
        IBS.READ(SCCGWA, BPRFFAV, BPTFFAV_RD);
        if (SCCGWA.COMM_AREA.DBIO_FLG == '0') {
            WS_TBL_FARM_FLAG = 'N';
        } else if (SCCGWA.COMM_AREA.DBIO_FLG == '1') {
            WS_TBL_FARM_FLAG = 'D';
        } else {
            IBS.init(SCCGWA, SCCEXCP);
            SCCEXCP.MSG_TEXT.KEY_OR_OTHER = "INVALID FLG (" + SCCGWA.COMM_AREA.DBIO_FLG + ")";
            CEP.EXCP(SCCGWA, SCCEXCP.MSG_TEXT.KEY_OR_OTHER);
        }
    }
    public void T000_REWRITE_BPTFFAV() throws IOException,SQLException,Exception {
        BPTFFAV_RD = new DBParm();
        BPTFFAV_RD.TableName = "BPTFFAV";
        IBS.REWRITE(SCCGWA, BPRFFAV, BPTFFAV_RD);
        if (SCCGWA.COMM_AREA.DBIO_FLG == '0') {
            BPCTFFAV.RETURN_INFO = 'F';
        } else if (SCCGWA.COMM_AREA.DBIO_FLG == '2') {
            BPCTFFAV.RETURN_INFO = 'D';
        } else {
            IBS.init(SCCGWA, SCCEXCP);
            SCCEXCP.MSG_TEXT.KEY_OR_OTHER = "INVALID FLG (" + SCCGWA.COMM_AREA.DBIO_FLG + ")";
            CEP.EXCP(SCCGWA, SCCEXCP.MSG_TEXT.KEY_OR_OTHER);
        }
    }
    public void T000_DELETE_BPTFFAV() throws IOException,SQLException,Exception {
        BPTFFAV_RD = new DBParm();
        BPTFFAV_RD.TableName = "BPTFFAV";
        IBS.DELETE(SCCGWA, BPRFFAV, BPTFFAV_RD);
        if (SCCGWA.COMM_AREA.DBIO_FLG == '0') {
            BPCTFFAV.RETURN_INFO = 'F';
        } else if (SCCGWA.COMM_AREA.DBIO_FLG == '1') {
            BPCTFFAV.RETURN_INFO = 'N';
        } else {
            IBS.init(SCCGWA, SCCEXCP);
            SCCEXCP.MSG_TEXT.KEY_OR_OTHER = "INVALID FLG (" + SCCGWA.COMM_AREA.DBIO_FLG + ")";
            CEP.EXCP(SCCGWA, SCCEXCP.MSG_TEXT.KEY_OR_OTHER);
        }
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        pgmRtn = true;
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
