package com.hisun.BP;

public class BPZUINHD_WS_TS {
    BPZUINHD_WS_TS_QUEUE WS_TS_QUEUE = new BPZUINHD_WS_TS_QUEUE();
    BPZUINHD_WS_OUTPUT_FMT WS_OUTPUT_FMT = new BPZUINHD_WS_OUTPUT_FMT();
    BPZUINHD_WS_OUTPUT_FMT_CN WS_OUTPUT_FMT_CN = new BPZUINHD_WS_OUTPUT_FMT_CN();
}
