package com.hisun.BP;

public class BPZUGVCH_WS_COMPUTE {
    int CPU1_DATE = 0;
    BPZUGVCH_REDEFINES246 REDEFINES246 = new BPZUGVCH_REDEFINES246();
    int CPU2_DATE = 0;
    BPZUGVCH_REDEFINES251 REDEFINES251 = new BPZUGVCH_REDEFINES251();
}
