package com.hisun.BP;

public class BPZUGVCH_WS_VARIABLES {
    String ERR_MSG = " ";
    String ERR_INFO = " ";
    String RC = " ";
    String VCH_BR_CHAR = " ";
    BPZUGVCH_WS_CNT_INFO WS_CNT_INFO = new BPZUGVCH_WS_CNT_INFO();
    BPZUGVCH_WS_EXP_INFO WS_EXP_INFO = new BPZUGVCH_WS_EXP_INFO();
    BPZUGVCH_WS_CNTR_INFO WS_CNTR_INFO = new BPZUGVCH_WS_CNTR_INFO();
    String SUS_ITM = " ";
    int SUS_SEQ = 0;
    int ITM_SEQ = 0;
    BPZUGVCH_WS_CUR_EWA WS_CUR_EWA = new BPZUGVCH_WS_CUR_EWA();
    BPZUGVCH_WS_GLMST_CODE[] WS_GLMST_CODE = new BPZUGVCH_WS_GLMST_CODE[10];
    BPZUGVCH_WS_GLMST_DETAIL[] WS_GLMST_DETAIL = new BPZUGVCH_WS_GLMST_DETAIL[10];
    BPZUGVCH_WS_CUR_GLMST WS_CUR_GLMST = new BPZUGVCH_WS_CUR_GLMST();
    BPZUGVCH_WS_BOOK_PARM[] WS_BOOK_PARM = new BPZUGVCH_WS_BOOK_PARM[10];
    BPZUGVCH_WS_CUR_BOOK WS_CUR_BOOK = new BPZUGVCH_WS_CUR_BOOK();
    BPZUGVCH_WS_CUR_EVN_VCH WS_CUR_EVN_VCH = new BPZUGVCH_WS_CUR_EVN_VCH();
    char VCH_AC_FLG = ' ';
    BPZUGVCH_WS_VCH WS_VCH = new BPZUGVCH_WS_VCH();
    BPZUGVCH_WS_COMPUTE WS_COMPUTE = new BPZUGVCH_WS_COMPUTE();
    BPZUGVCH_WS_INTERNAL_AC WS_INTERNAL_AC = new BPZUGVCH_WS_INTERNAL_AC();
    public BPZUGVCH_WS_VARIABLES() {
        for (int i=0;i<10;i++) WS_GLMST_CODE[i] = new BPZUGVCH_WS_GLMST_CODE();
        for (int i=0;i<10;i++) WS_GLMST_DETAIL[i] = new BPZUGVCH_WS_GLMST_DETAIL();
        for (int i=0;i<10;i++) WS_BOOK_PARM[i] = new BPZUGVCH_WS_BOOK_PARM();
    }
}
