package com.hisun.BP;

public class BPZUIHIS_WS_TS_QUEUE {
    int WS_TS_TX_DT = 0;
    int WS_TS_AC_DT = 0;
    long WS_TS_JRNNO = 0;
    short WS_TS_JRN_SEQ = 0;
    String WS_TS_AC = " ";
    String WS_TS_REF_NO = " ";
    String WS_TS_TX_TOOL = " ";
    String WS_TS_APP_MMO = " ";
    String WS_TS_TX_CD = " ";
    int WS_TS_TX_BR = 0;
    short WS_TS_TX_DP = 0;
    String WS_TS_TX_TLR = " ";
    String WS_TS_SUP1 = " ";
    String WS_TS_SUP2 = " ";
    String WS_TS_TX_CHNL = " ";
    char WS_TS_FIN_FLG = ' ';
    String WS_TS_VCHNO = " ";
    String WS_TS_CI_NO = " ";
    char WS_TS_DRCR_FLG = ' ';
    String WS_TS_TX_CCY = " ";
    double WS_TS_TX_AMT = 0;
    char BPZUIHIS_FILLER61 = 0X01;
    double WS_TS_CUR_BAL = 0;
    char BPZUIHIS_FILLER63 = 0X01;
    int WS_TS_TX_VAL_DT = 0;
    String WS_TS_PROD_CD = " ";
    char WS_TS_STS = ' ';
    int WS_TS_TX_TM = 0;
    String WS_TS_REMARK = " ";
    char BPZUIHIS_FILLER69 = 0X02;
    char WS_TS_TX_TYPE = ' ';
    String WS_TX_TYP_CD = " ";
    String WS_MAKER_TLR = " ";
    String WS_NARRATIVE = " ";
    char BPZUIHIS_FILLER74 = 0X02;
    String WS_TX_MMO = " ";
    String WS_REL_AC = " ";
    char WS_STAFF_FLG = ' ';
    String WS_REL_CI_NAME = " ";
    char BPZUIHIS_FILLER79 = 0X02;
}
