package com.hisun.BP;

import com.hisun.AI.*;
import com.hisun.SC.*;
import java.lang.reflect.Method;

import java.io.IOException;
import java.sql.SQLException;

public class BPZUGLM {
    DBParm AITGLM_RD;
    int JIBS_tmp_int;
    String JIBS_tmp_str[] = new String[10];
    boolean pgmRtn = false;
    String K_PARM_TYPE = "AMGLM";
    String K_HIS_REMARKS = "GL MASTER MAINTENANCE";
    int WS_UPD_DT = 0;
    int WS_UPD_TM = 0;
    int WS_ITM_CNT = 0;
    String WS_PITM_NO = " ";
    int WS_CNT = 0;
    int WS_I = 0;
    int WS_GLMST = 0;
    int WS_GLMST1 = 0;
    int WS_QBKPM_CNT = 0;
    BPZUGLM_WS_QBKPM_INF[] WS_QBKPM_INF = new BPZUGLM_WS_QBKPM_INF[10];
    String WS_MSG_ERR = " ";
    String WS_INFO = " ";
    BPZUGLM_WS_KEY WS_KEY = new BPZUGLM_WS_KEY();
    BPZUGLM_WS_VAL WS_VAL = new BPZUGLM_WS_VAL();
    int WS_J = 0;
    BPZUGLM_WS_GLM_KEY WS_GLM_KEY = new BPZUGLM_WS_GLM_KEY();
    short WS_GLM_LAST_BEGSEQ = 0;
    String WS_CNTY = " ";
    String WS_GL_BOOK_FLG = " ";
    int WS_MST_NO = 0;
    char WS_FND_FLG = ' ';
    char WS_CNTY_FLG = ' ';
    char WS_CNGM_FLG = ' ';
    char WS_GLM_FLG = ' ';
    BPCMSG_ERROR_MSG BPCMSG_ERROR_MSG = new BPCMSG_ERROR_MSG();
    AICMSG_ERROR_MSG AICMSG_ERROR_MSG = new AICMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    BPCPARM BPCPARM = new BPCPARM();
    BPRPRMT BPRPRMT = new BPRPRMT();
    BPRPARM BPRPARM = new BPRPARM();
    BPCPRMM BPCPRMM = new BPCPRMM();
    BPCPITM BPCPITM = new BPCPITM();
    BPCPQPDM BPCPQPDM = new BPCPQPDM();
    BPCRCNGL BPCRCNGL = new BPCRCNGL();
    BPRCNGL BPRCNGL = new BPRCNGL();
    BPRCNGM BPRCNGM = new BPRCNGM();
    BPCQBKPM BPCQBKPM = new BPCQBKPM();
    AICPQITM AICPQITM = new AICPQITM();
    SCCMPAG SCCMPAG = new SCCMPAG();
    SCCMSG SCCMSG = new SCCMSG();
    SCCFMT SCCFMT = new SCCFMT();
    BPCPNHIS BPCPNHIS = new BPCPNHIS();
    BPCHGLM BPCHGLM = new BPCHGLM();
    BPCHGLM BPCHGLMN = new BPCHGLM();
    BPCHGLM BPCHGLMO = new BPCHGLM();
    AIRCMIB AIRCMIB = new AIRCMIB();
    AICRCMIB AICRCMIB = new AICRCMIB();
    AIRGLM AIRGLM = new AIRGLM();
    AIRGLM AIRNGLM = new AIRGLM();
    AIRGLM AIROGLM = new AIRGLM();
    AIRENTY AIRENTY = new AIRENTY();
    BPCPRMBR BPCPRMBR = new BPCPRMBR();
    SCCGWA SCCGWA;
    BPCUGLM BPCUGLM;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    SCCCWA SCCCWA;
    public BPZUGLM() {
        for (int i=0;i<10;i++) WS_QBKPM_INF[i] = new BPZUGLM_WS_QBKPM_INF();
    }
    public void MP(SCCGWA SCCGWA, BPCUGLM BPCUGLM) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        this.BPCUGLM = BPCUGLM;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        if (pgmRtn) return;
        B000_MAIN_PROC();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, "BPZUGLM return!");
        Z_RET();
        if (pgmRtn) return;
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        BPCUGLM.RC.RC_MMO = "BP";
        BPCUGLM.RC.RC_CODE = 0;
    if (!SCCGWA.COMM_AREA.BSP_FLG.equalsIgnoreCase("BSP") && !SCCGWA.COMM_AREA.CHNL.equalsIgnoreCase("BAT")) { //FROM #IFDEF ONL
        R000_SET_LK_MMT();
        if (pgmRtn) return;
    } //FROM #ENDIF
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, BPCUGLM.DATA.DATA_TXT.REL_ITMS[34-1].ITM_NO);
        CEP.TRC(SCCGWA, BPCUGLM.DATA);
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.AC_DATE);
        CEP.TRC(SCCGWA, BPCUGLM.DATA.P_EFF_DATE);
        CEP.TRC(SCCGWA, BPCUGLM.DATA.P_EXP_DATE);
        B010_CHECK_INPUT();
        if (pgmRtn) return;
        if (BPCUGLM.INFO.FUNC == 'I') {
            B020_QUERY_RECORD_PROC();
            if (pgmRtn) return;
            B021_MOVE_DATA();
            if (pgmRtn) return;
        } else if (BPCUGLM.INFO.FUNC == 'A') {
            B030_ADD_RECORD_PROC();
            if (pgmRtn) return;
            S000_HISTORY_PROCESS();
            if (pgmRtn) return;
            B021_MOVE_DATA();
            if (pgmRtn) return;
        } else if (BPCUGLM.INFO.FUNC == 'U') {
            B040_UPDATE_RECORD_PROC();
            if (pgmRtn) return;
            S000_HISTORY_PROCESS();
            if (pgmRtn) return;
            B021_MOVE_DATA();
            if (pgmRtn) return;
        } else if (BPCUGLM.INFO.FUNC == 'D') {
            B050_DELETE_RECORD_PROC();
            if (pgmRtn) return;
            S000_HISTORY_PROCESS();
            if (pgmRtn) return;
            B021_MOVE_DATA();
            if (pgmRtn) return;
        } else {
            WS_MSG_ERR = BPCMSG_ERROR_MSG.BP_FUNC_ERROR;
            S000_ERR_MSG_PROC();
            if (pgmRtn) return;
        }
    }
    public void B010_CHECK_INPUT() throws IOException,SQLException,Exception {
        if (BPCUGLM.INFO.FUNC == 'A' 
            || BPCUGLM.INFO.FUNC == 'U') {
            WS_CNTY = BPCUGLM.DATA.DATA_TXT.CNTY1;
            S000_CHK_CNTY();
            if (pgmRtn) return;
            if (BPCUGLM.DATA.DATA_TXT.CNTY2.trim().length() > 0) {
                WS_CNTY = BPCUGLM.DATA.DATA_TXT.CNTY2;
                S000_CHK_CNTY();
                if (pgmRtn) return;
            }
            if (BPCUGLM.DATA.DATA_TXT.CNTY3.trim().length() > 0) {
                WS_CNTY = BPCUGLM.DATA.DATA_TXT.CNTY3;
                S000_CHK_CNTY();
                if (pgmRtn) return;
            }
            WS_ITM_CNT = 60;
            for (WS_I = 1; WS_I <= WS_ITM_CNT; WS_I += 1) {
                CEP.TRC(SCCGWA, BPCUGLM.DATA.DATA_TXT.REL_ITMS[WS_I-1].ITM_NO);
                if (BPCUGLM.DATA.DATA_TXT.REL_ITMS[WS_I-1].ITM_NO.trim().length() > 0) {
                    CEP.TRC(SCCGWA, BPCUGLM.DATA.DATA_TXT.REL_ITMS[WS_I-1].ITM_NO);
                    CEP.TRC(SCCGWA, WS_I);
                    IBS.init(SCCGWA, AICPQITM);
                    AICPQITM.INPUT_DATA.COA_FLG = BPCUGLM.DATA.DATA_TXT.COA_FLG;
                    AICPQITM.INPUT_DATA.NO = BPCUGLM.DATA.DATA_TXT.REL_ITMS[WS_I-1].ITM_NO;
                    S000_CALL_AIZPQITM();
                    if (pgmRtn) return;
                    CEP.TRC(SCCGWA, "SHOW MIB FLG");
                    CEP.TRC(SCCGWA, AICPQITM.OUTPUT_DATA.MIB_FLG);
                    if (AICPQITM.OUTPUT_DATA.MIB_FLG == 'N' 
                        && BPCUGLM.DATA.DATA_TXT.REL_ITMS[WS_I-1].ITM_SEQ != 0) {
                        WS_INFO = BPCUGLM.DATA.DATA_TXT.REL_ITMS[WS_I-1].ITM_NO;
                        WS_MSG_ERR = BPCMSG_ERROR_MSG.BP_N_MIB_N_SEQ;
                        S000_ERR_MSG_PROC();
                        if (pgmRtn) return;
                    }
                    if (AICPQITM.OUTPUT_DATA.MIB_FLG == 'G' 
                        && BPCUGLM.DATA.DATA_TXT.REL_ITMS[WS_I-1].ITM_SEQ != 0) {
                        WS_INFO = BPCUGLM.DATA.DATA_TXT.REL_ITMS[WS_I-1].ITM_NO;
                        WS_MSG_ERR = BPCMSG_ERROR_MSG.BP_N_MIB_N_SEQ;
                        S000_ERR_MSG_PROC();
                        if (pgmRtn) return;
                    }
                    CEP.TRC(SCCGWA, AICPQITM.OUTPUT_DATA.MIB_FLG);
                    CEP.TRC(SCCGWA, BPCUGLM.DATA.DATA_TXT.REL_ITMS[WS_I-1].ITM_SEQ);
                    if (AICPQITM.OUTPUT_DATA.MIB_FLG == 'Y' 
                        && BPCUGLM.DATA.DATA_TXT.REL_ITMS[WS_I-1].ITM_SEQ == 0) {
                        WS_INFO = BPCUGLM.DATA.DATA_TXT.REL_ITMS[WS_I-1].ITM_NO;
                        WS_MSG_ERR = BPCMSG_ERROR_MSG.BP_Y_MIB_SEQ;
                        S000_ERR_MSG_PROC();
                        if (pgmRtn) return;
                    }
                    if (!(AICPQITM.OUTPUT_DATA.STS == 'A' 
                        || AICPQITM.OUTPUT_DATA.STS == 'P')) {
                        WS_INFO = BPCUGLM.DATA.DATA_TXT.REL_ITMS[WS_I-1].ITM_NO;
                        WS_MSG_ERR = BPCMSG_ERROR_MSG.BP_ITM_STS_N_AP;
                        S000_ERR_MSG_PROC();
                        if (pgmRtn) return;
                    }
                    if (AICPQITM.OUTPUT_DATA.ITM_LVL != '3') {
                        WS_INFO = BPCUGLM.DATA.DATA_TXT.REL_ITMS[WS_I-1].ITM_NO;
                        WS_MSG_ERR = BPCMSG_ERROR_MSG.BP_N_LV3;
                        S000_ERR_MSG_PROC();
                        if (pgmRtn) return;
                    }
                    CEP.TRC(SCCGWA, AICPQITM.OUTPUT_DATA.EXP_DATE);
                    CEP.TRC(SCCGWA, BPCUGLM.DATA.DATA_TXT.EXP_DATE);
                    CEP.TRC(SCCGWA, AICPQITM.OUTPUT_DATA.EFF_DATE);
                    CEP.TRC(SCCGWA, BPCUGLM.DATA.DATA_TXT.EFF_DATE);
                    if (AICPQITM.OUTPUT_DATA.STS == 'P') {
                        if (AICPQITM.OUTPUT_DATA.EFF_DATE > BPCUGLM.DATA.DATA_TXT.EFF_DATE) {
                            WS_INFO = BPCUGLM.DATA.DATA_TXT.REL_ITMS[WS_I-1].ITM_NO;
                            WS_MSG_ERR = BPCMSG_ERROR_MSG.BP_ITM_NE_GLM_EFFDT;
                            S000_ERR_MSG_PROC();
                            if (pgmRtn) return;
                        }
                    }
                    if (AICPQITM.OUTPUT_DATA.EXP_DATE < BPCUGLM.DATA.DATA_TXT.EXP_DATE) {
                        WS_MSG_ERR = BPCMSG_ERROR_MSG.BP_ITM_NE_GLM_EXPDT;
                        S000_ERR_MSG_PROC();
                        if (pgmRtn) return;
                    }
                    if (BPCUGLM.DATA.DATA_TXT.REL_ITMS[WS_I-1].ITM_SEQ != 0) {
                        IBS.init(SCCGWA, AIRCMIB);
                        IBS.init(SCCGWA, AICRCMIB);
                        AICRCMIB.FUNC = 'F';
                        AIRCMIB.KEY.GL_BOOK = "BK001";
                        AIRCMIB.KEY.ITM = BPCUGLM.DATA.DATA_TXT.REL_ITMS[WS_I-1].ITM_NO;
                        AIRCMIB.KEY.SEQ = BPCUGLM.DATA.DATA_TXT.REL_ITMS[WS_I-1].ITM_SEQ;
                        AICRCMIB.POINTER = AIRCMIB;
                        AICRCMIB.REC_LEN = 407;
                        S000_CALL_AIZRCMIB();
                        if (pgmRtn) return;
                        if (AICRCMIB.RETURN_INFO == 'N') {
                            WS_MSG_ERR = AICMSG_ERROR_MSG.AI_READ_AITCMIB_NOTFND;
                            S000_ERR_MSG_PROC();
                            if (pgmRtn) return;
                        }
                    }
                    if (BPCUGLM.DATA.DATA_TXT.CKFLG == 'Y') {
                        CEP.TRC(SCCGWA, BPCPITM.OUTPUT_DATA.GLMST);
                        WS_GLMST = BPCPITM.OUTPUT_DATA.GLMST;
                        if (WS_GLMST != BPCUGLM.DATA.KEY.REDEFINES16.MSTNO) {
                            WS_PITM_NO = BPCPITM.INPUT_DATA.NO;
                            WS_INFO = " ";
                            WS_INFO = "T" + "COA CODE:" + BPCPITM.INPUT_DATA.COA_FLG + "/" + "GL A/C NO.:" + WS_PITM_NO + "/" + "GL MASTER:" + BPCUGLM.DATA.KEY.REDEFINES16.MSTNO;
                            WS_MSG_ERR = BPCMSG_ERROR_MSG.BP_COA_NO_MATCH_GLMST;
                            S000_ERR_MSG_PROC();
                            if (pgmRtn) return;
                        }
                    }
                }
            }
        }
        if (BPCUGLM.INFO.FUNC == 'D') {
            IBS.init(SCCGWA, BPCRCNGL);
            IBS.init(SCCGWA, BPRCNGL);
            BPCRCNGL.FUNC = 'S';
            WS_FND_FLG = 'Y';
            S000_CALL_BPZRCNGL();
            if (pgmRtn) return;
            while (WS_FND_FLG != 'N') {
                IBS.init(SCCGWA, BPCRCNGL);
                IBS.init(SCCGWA, BPRCNGL);
                BPCRCNGL.FUNC = 'N';
                S000_CALL_BPZRCNGL();
                if (pgmRtn) return;
                if (BPRCNGL.MSTNO == BPCUGLM.DATA.KEY.REDEFINES16.MSTNO) {
                    WS_MSG_ERR = BPCMSG_ERROR_MSG.BP_GLMST_ALREADY_CNTR;
                    S000_ERR_MSG_PROC();
                    if (pgmRtn) return;
                }
            }
            BPCRCNGL.FUNC = 'E';
            S000_CALL_BPZRCNGL();
            if (pgmRtn) return;
        }
    }
    public void B020_QUERY_RECORD_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, AIRGLM);
        if (BPCUGLM.DATA.P_EFF_DATE == 0) {
            AIRGLM.KEY.EFF_DT = SCCGWA.COMM_AREA.AC_DATE;
        } else {
            AIRGLM.KEY.EFF_DT = BPCUGLM.DATA.P_EFF_DATE;
        }
        AIRGLM.KEY.GL_MSTNO = BPCUGLM.DATA.KEY.REDEFINES16.MSTNO;
        AIRGLM.KEY.IBS_AC_BK = SCCGWA.COMM_AREA.TR_BANK;
        T000_READ_AITGLM();
        if (pgmRtn) return;
    }
    public void B030_ADD_RECORD_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, AIRGLM);
        S000_INPUT_DATA_PROCESS();
        if (pgmRtn) return;
        T000_WRITE_AITGLM();
        if (pgmRtn) return;
        BPCHGLM.KEY.MSTNO = AIRGLM.KEY.GL_MSTNO;
        BPCHGLM.DATA.COA_FLG = AIRGLM.COA_FLG;
        BPCHGLM.DATA.SNAME = AIRGLM.DESC;
        BPCHGLM.DATA.LNAME = AIRGLM.CDESC;
        BPCHGLM.DATA.EFF_DATE = AIRGLM.KEY.EFF_DT;
        BPCHGLM.DATA.EXP_DATE = AIRGLM.KEY.EXP_DT;
        BPCHGLM.DATA.CNTY1 = AIRGLM.CNTY1;
        BPCHGLM.DATA.CNTY2 = AIRGLM.CNTY2;
        BPCHGLM.DATA.CNTY3 = AIRGLM.CNTY3;
        BPCHGLM.DATA.CKFLG = AIRGLM.CKFLG;
        BPCHGLM.DATA.REAL_GL = AIRGLM.REAL_GL;
        WS_ITM_CNT = 60;
        for (WS_I = 1; WS_I <= WS_ITM_CNT; WS_I += 1) {
            BPCHGLM.DATA.REL_ITMS[WS_I-1].ITM_NO = BPCUGLM.DATA.DATA_TXT.REL_ITMS[WS_I-1].ITM_NO;
            if (BPCUGLM.DATA.DATA_TXT.REL_ITMS[WS_I-1].ITM_NO.trim().length() == 0) BPCHGLM.DATA.REL_ITMS[WS_I-1].ITM_SEQ = 0;
            else BPCHGLM.DATA.REL_ITMS[WS_I-1].ITM_SEQ = Integer.parseInt(BPCUGLM.DATA.DATA_TXT.REL_ITMS[WS_I-1].ITM_NO);
        }
    }
    public void B040_UPDATE_RECORD_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, AIRGLM);
        AIRGLM.KEY.IBS_AC_BK = SCCGWA.COMM_AREA.TR_BANK;
        AIRGLM.KEY.GL_MSTNO = BPCUGLM.DATA.KEY.REDEFINES16.MSTNO;
        if (BPCUGLM.DATA.DATA_TXT.EFF_DATE == 0) {
            AIRGLM.KEY.EFF_DT = SCCGWA.COMM_AREA.AC_DATE;
        } else {
            AIRGLM.KEY.EFF_DT = BPCUGLM.DATA.DATA_TXT.EFF_DATE;
        }
        T000_READUP_AITGLM();
        if (pgmRtn) return;
        if (BPCUGLM.DATA.DATA_TXT.EFF_DATE != AIRGLM.KEY.EFF_DT) {
            CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.AC_DATE);
            if (AIRGLM.KEY.EFF_DT >= SCCGWA.COMM_AREA.AC_DATE) {
                WS_MSG_ERR = BPCMSG_ERROR_MSG.BP_NO_MOD_EFF_DATE;
                S000_ERR_MSG_PROC();
                if (pgmRtn) return;
            }
            if (BPCUGLM.DATA.DATA_TXT.EFF_DATE < SCCGWA.COMM_AREA.AC_DATE) {
                WS_MSG_ERR = BPCMSG_ERROR_MSG.BP_EFF_DATE_TOO_SMALL;
                S000_ERR_MSG_PROC();
                if (pgmRtn) return;
            }
        }
        WS_UPD_DT = AIRGLM.UPD_DATE;
        WS_UPD_TM = AIRGLM.UPD_TIME;
        if (BPCUGLM.DATA.DATA_TXT.UPD_DATE != WS_UPD_DT 
            || BPCUGLM.DATA.DATA_TXT.UPD_TIME != WS_UPD_TM) {
            CEP.TRC(SCCGWA, BPCUGLM.DATA.DATA_TXT.UPD_DATE);
            CEP.TRC(SCCGWA, BPCUGLM.DATA.DATA_TXT.UPD_TIME);
            WS_MSG_ERR = BPCMSG_ERROR_MSG.BP_RECORD_ALREADY_CHANG;
            S000_ERR_MSG_PROC();
            if (pgmRtn) return;
        }
        BPCHGLMO.KEY.MSTNO = AIRGLM.KEY.GL_MSTNO;
        BPCHGLMO.DATA.COA_FLG = AIRGLM.COA_FLG;
        BPCHGLMO.DATA.SNAME = AIRGLM.DESC;
        BPCHGLMO.DATA.LNAME = AIRGLM.CDESC;
        BPCHGLMO.DATA.EFF_DATE = AIRGLM.KEY.EFF_DT;
        BPCHGLMO.DATA.EXP_DATE = AIRGLM.KEY.EXP_DT;
        BPCHGLMO.DATA.CNTY1 = AIRGLM.CNTY1;
        BPCHGLMO.DATA.CNTY2 = AIRGLM.CNTY2;
        BPCHGLMO.DATA.CNTY3 = AIRGLM.CNTY3;
        BPCHGLMO.DATA.CKFLG = AIRGLM.CKFLG;
        BPCHGLMO.DATA.REAL_GL = AIRGLM.REAL_GL;
        BPCHGLMO.DATA.REL_ITMS[1-1].ITM_NO = AIRGLM.ITM_NO1;
        BPCHGLMO.DATA.REL_ITMS[1-1].ITM_SEQ = AIRGLM.ITM_SEQ1;
        BPCHGLMO.DATA.REL_ITMS[2-1].ITM_NO = AIRGLM.ITM_NO2;
        BPCHGLMO.DATA.REL_ITMS[2-1].ITM_SEQ = AIRGLM.ITM_SEQ2;
        BPCHGLMO.DATA.REL_ITMS[3-1].ITM_NO = AIRGLM.ITM_NO3;
        BPCHGLMO.DATA.REL_ITMS[3-1].ITM_SEQ = AIRGLM.ITM_SEQ3;
        BPCHGLMO.DATA.REL_ITMS[4-1].ITM_NO = AIRGLM.ITM_NO4;
        BPCHGLMO.DATA.REL_ITMS[4-1].ITM_SEQ = AIRGLM.ITM_SEQ4;
        BPCHGLMO.DATA.REL_ITMS[5-1].ITM_NO = AIRGLM.ITM_NO5;
        BPCHGLMO.DATA.REL_ITMS[5-1].ITM_SEQ = AIRGLM.ITM_SEQ5;
        BPCHGLMO.DATA.REL_ITMS[6-1].ITM_NO = AIRGLM.ITM_NO6;
        BPCHGLMO.DATA.REL_ITMS[6-1].ITM_SEQ = AIRGLM.ITM_SEQ6;
        BPCHGLMO.DATA.REL_ITMS[7-1].ITM_NO = AIRGLM.ITM_NO7;
        BPCHGLMO.DATA.REL_ITMS[7-1].ITM_SEQ = AIRGLM.ITM_SEQ7;
        BPCHGLMO.DATA.REL_ITMS[8-1].ITM_NO = AIRGLM.ITM_NO8;
        BPCHGLMO.DATA.REL_ITMS[8-1].ITM_SEQ = AIRGLM.ITM_SEQ8;
        BPCHGLMO.DATA.REL_ITMS[9-1].ITM_NO = AIRGLM.ITM_NO9;
        BPCHGLMO.DATA.REL_ITMS[9-1].ITM_SEQ = AIRGLM.ITM_SEQ9;
        BPCHGLMO.DATA.REL_ITMS[10-1].ITM_NO = AIRGLM.ITM_NO10;
        BPCHGLMO.DATA.REL_ITMS[10-1].ITM_SEQ = AIRGLM.ITM_SEQ10;
        BPCHGLMO.DATA.REL_ITMS[11-1].ITM_NO = AIRGLM.ITM_NO11;
        BPCHGLMO.DATA.REL_ITMS[11-1].ITM_SEQ = AIRGLM.ITM_SEQ11;
        BPCHGLMO.DATA.REL_ITMS[12-1].ITM_NO = AIRGLM.ITM_NO12;
        BPCHGLMO.DATA.REL_ITMS[12-1].ITM_SEQ = AIRGLM.ITM_SEQ12;
        BPCHGLMO.DATA.REL_ITMS[13-1].ITM_NO = AIRGLM.ITM_NO13;
        BPCHGLMO.DATA.REL_ITMS[13-1].ITM_SEQ = AIRGLM.ITM_SEQ13;
        BPCHGLMO.DATA.REL_ITMS[14-1].ITM_NO = AIRGLM.ITM_NO14;
        BPCHGLMO.DATA.REL_ITMS[14-1].ITM_SEQ = AIRGLM.ITM_SEQ14;
        BPCHGLMO.DATA.REL_ITMS[15-1].ITM_NO = AIRGLM.ITM_NO15;
        BPCHGLMO.DATA.REL_ITMS[15-1].ITM_SEQ = AIRGLM.ITM_SEQ15;
        BPCHGLMO.DATA.REL_ITMS[16-1].ITM_NO = AIRGLM.ITM_NO16;
        BPCHGLMO.DATA.REL_ITMS[16-1].ITM_SEQ = AIRGLM.ITM_SEQ16;
        BPCHGLMO.DATA.REL_ITMS[17-1].ITM_NO = AIRGLM.ITM_NO17;
        BPCHGLMO.DATA.REL_ITMS[17-1].ITM_SEQ = AIRGLM.ITM_SEQ17;
        BPCHGLMO.DATA.REL_ITMS[18-1].ITM_NO = AIRGLM.ITM_NO18;
        BPCHGLMO.DATA.REL_ITMS[18-1].ITM_SEQ = AIRGLM.ITM_SEQ18;
        BPCHGLMO.DATA.REL_ITMS[19-1].ITM_NO = AIRGLM.ITM_NO19;
        BPCHGLMO.DATA.REL_ITMS[19-1].ITM_SEQ = AIRGLM.ITM_SEQ19;
        BPCHGLMO.DATA.REL_ITMS[20-1].ITM_NO = AIRGLM.ITM_NO20;
        BPCHGLMO.DATA.REL_ITMS[20-1].ITM_SEQ = AIRGLM.ITM_SEQ20;
        BPCHGLMO.DATA.REL_ITMS[21-1].ITM_NO = AIRGLM.ITM_NO21;
        BPCHGLMO.DATA.REL_ITMS[21-1].ITM_SEQ = AIRGLM.ITM_SEQ21;
        BPCHGLMO.DATA.REL_ITMS[22-1].ITM_NO = AIRGLM.ITM_NO22;
        BPCHGLMO.DATA.REL_ITMS[22-1].ITM_SEQ = AIRGLM.ITM_SEQ22;
        BPCHGLMO.DATA.REL_ITMS[23-1].ITM_NO = AIRGLM.ITM_NO23;
        BPCHGLMO.DATA.REL_ITMS[23-1].ITM_SEQ = AIRGLM.ITM_SEQ23;
        BPCHGLMO.DATA.REL_ITMS[24-1].ITM_NO = AIRGLM.ITM_NO24;
        BPCHGLMO.DATA.REL_ITMS[24-1].ITM_SEQ = AIRGLM.ITM_SEQ24;
        BPCHGLMO.DATA.REL_ITMS[25-1].ITM_NO = AIRGLM.ITM_NO25;
        BPCHGLMO.DATA.REL_ITMS[25-1].ITM_SEQ = AIRGLM.ITM_SEQ25;
        BPCHGLMO.DATA.REL_ITMS[26-1].ITM_NO = AIRGLM.ITM_NO26;
        BPCHGLMO.DATA.REL_ITMS[26-1].ITM_SEQ = AIRGLM.ITM_SEQ26;
        BPCHGLMO.DATA.REL_ITMS[27-1].ITM_NO = AIRGLM.ITM_NO27;
        BPCHGLMO.DATA.REL_ITMS[27-1].ITM_SEQ = AIRGLM.ITM_SEQ27;
        BPCHGLMO.DATA.REL_ITMS[28-1].ITM_NO = AIRGLM.ITM_NO28;
        BPCHGLMO.DATA.REL_ITMS[28-1].ITM_SEQ = AIRGLM.ITM_SEQ28;
        BPCHGLMO.DATA.REL_ITMS[29-1].ITM_NO = AIRGLM.ITM_NO29;
        BPCHGLMO.DATA.REL_ITMS[29-1].ITM_SEQ = AIRGLM.ITM_SEQ29;
        BPCHGLMO.DATA.REL_ITMS[30-1].ITM_NO = AIRGLM.ITM_NO30;
        BPCHGLMO.DATA.REL_ITMS[30-1].ITM_SEQ = AIRGLM.ITM_SEQ30;
        BPCHGLMO.DATA.REL_ITMS[31-1].ITM_NO = AIRGLM.ITM_NO31;
        BPCHGLMO.DATA.REL_ITMS[31-1].ITM_SEQ = AIRGLM.ITM_SEQ31;
        BPCHGLMO.DATA.REL_ITMS[32-1].ITM_NO = AIRGLM.ITM_NO32;
        BPCHGLMO.DATA.REL_ITMS[32-1].ITM_SEQ = AIRGLM.ITM_SEQ32;
        BPCHGLMO.DATA.REL_ITMS[33-1].ITM_NO = AIRGLM.ITM_NO33;
        BPCHGLMO.DATA.REL_ITMS[33-1].ITM_SEQ = AIRGLM.ITM_SEQ33;
        BPCHGLMO.DATA.REL_ITMS[34-1].ITM_NO = AIRGLM.ITM_NO34;
        BPCHGLMO.DATA.REL_ITMS[34-1].ITM_SEQ = AIRGLM.ITM_SEQ34;
        BPCHGLMO.DATA.REL_ITMS[35-1].ITM_NO = AIRGLM.ITM_NO35;
        BPCHGLMO.DATA.REL_ITMS[35-1].ITM_SEQ = AIRGLM.ITM_SEQ35;
        BPCHGLMO.DATA.REL_ITMS[36-1].ITM_NO = AIRGLM.ITM_NO36;
        BPCHGLMO.DATA.REL_ITMS[36-1].ITM_SEQ = AIRGLM.ITM_SEQ36;
        BPCHGLMO.DATA.REL_ITMS[37-1].ITM_NO = AIRGLM.ITM_NO37;
        BPCHGLMO.DATA.REL_ITMS[37-1].ITM_SEQ = AIRGLM.ITM_SEQ37;
        BPCHGLMO.DATA.REL_ITMS[38-1].ITM_NO = AIRGLM.ITM_NO38;
        BPCHGLMO.DATA.REL_ITMS[38-1].ITM_SEQ = AIRGLM.ITM_SEQ38;
        BPCHGLMO.DATA.REL_ITMS[39-1].ITM_NO = AIRGLM.ITM_NO39;
        BPCHGLMO.DATA.REL_ITMS[39-1].ITM_SEQ = AIRGLM.ITM_SEQ39;
        BPCHGLMO.DATA.REL_ITMS[40-1].ITM_NO = AIRGLM.ITM_NO40;
        BPCHGLMO.DATA.REL_ITMS[40-1].ITM_SEQ = AIRGLM.ITM_SEQ40;
        BPCHGLMO.DATA.REL_ITMS[41-1].ITM_NO = AIRGLM.ITM_NO41;
        BPCHGLMO.DATA.REL_ITMS[41-1].ITM_SEQ = AIRGLM.ITM_SEQ41;
        BPCHGLMO.DATA.REL_ITMS[42-1].ITM_NO = AIRGLM.ITM_NO42;
        BPCHGLMO.DATA.REL_ITMS[42-1].ITM_SEQ = AIRGLM.ITM_SEQ42;
        BPCHGLMO.DATA.REL_ITMS[43-1].ITM_NO = AIRGLM.ITM_NO43;
        BPCHGLMO.DATA.REL_ITMS[43-1].ITM_SEQ = AIRGLM.ITM_SEQ43;
        BPCHGLMO.DATA.REL_ITMS[44-1].ITM_NO = AIRGLM.ITM_NO44;
        BPCHGLMO.DATA.REL_ITMS[44-1].ITM_SEQ = AIRGLM.ITM_SEQ44;
        BPCHGLMO.DATA.REL_ITMS[45-1].ITM_NO = AIRGLM.ITM_NO45;
        BPCHGLMO.DATA.REL_ITMS[45-1].ITM_SEQ = AIRGLM.ITM_SEQ45;
        BPCHGLMO.DATA.REL_ITMS[46-1].ITM_NO = AIRGLM.ITM_NO46;
        BPCHGLMO.DATA.REL_ITMS[46-1].ITM_SEQ = AIRGLM.ITM_SEQ46;
        BPCHGLMO.DATA.REL_ITMS[47-1].ITM_NO = AIRGLM.ITM_NO47;
        BPCHGLMO.DATA.REL_ITMS[47-1].ITM_SEQ = AIRGLM.ITM_SEQ47;
        BPCHGLMO.DATA.REL_ITMS[48-1].ITM_NO = AIRGLM.ITM_NO48;
        BPCHGLMO.DATA.REL_ITMS[48-1].ITM_SEQ = AIRGLM.ITM_SEQ48;
        BPCHGLMO.DATA.REL_ITMS[49-1].ITM_NO = AIRGLM.ITM_NO49;
        BPCHGLMO.DATA.REL_ITMS[49-1].ITM_SEQ = AIRGLM.ITM_SEQ49;
        BPCHGLMO.DATA.REL_ITMS[50-1].ITM_NO = AIRGLM.ITM_NO50;
        BPCHGLMO.DATA.REL_ITMS[50-1].ITM_SEQ = AIRGLM.ITM_SEQ50;
        BPCHGLMO.DATA.REL_ITMS[51-1].ITM_NO = AIRGLM.ITM_NO51;
        BPCHGLMO.DATA.REL_ITMS[51-1].ITM_SEQ = AIRGLM.ITM_SEQ51;
        BPCHGLMO.DATA.REL_ITMS[52-1].ITM_NO = AIRGLM.ITM_NO52;
        BPCHGLMO.DATA.REL_ITMS[52-1].ITM_SEQ = AIRGLM.ITM_SEQ52;
        BPCHGLMO.DATA.REL_ITMS[53-1].ITM_NO = AIRGLM.ITM_NO53;
        BPCHGLMO.DATA.REL_ITMS[53-1].ITM_SEQ = AIRGLM.ITM_SEQ53;
        BPCHGLMO.DATA.REL_ITMS[54-1].ITM_NO = AIRGLM.ITM_NO54;
        BPCHGLMO.DATA.REL_ITMS[54-1].ITM_SEQ = AIRGLM.ITM_SEQ54;
        BPCHGLMO.DATA.REL_ITMS[55-1].ITM_NO = AIRGLM.ITM_NO55;
        BPCHGLMO.DATA.REL_ITMS[55-1].ITM_SEQ = AIRGLM.ITM_SEQ55;
        BPCHGLMO.DATA.REL_ITMS[56-1].ITM_NO = AIRGLM.ITM_NO56;
        BPCHGLMO.DATA.REL_ITMS[56-1].ITM_SEQ = AIRGLM.ITM_SEQ56;
        BPCHGLMO.DATA.REL_ITMS[57-1].ITM_NO = AIRGLM.ITM_NO57;
        BPCHGLMO.DATA.REL_ITMS[57-1].ITM_SEQ = AIRGLM.ITM_SEQ57;
        BPCHGLMO.DATA.REL_ITMS[58-1].ITM_NO = AIRGLM.ITM_NO58;
        BPCHGLMO.DATA.REL_ITMS[58-1].ITM_SEQ = AIRGLM.ITM_SEQ58;
        BPCHGLMO.DATA.REL_ITMS[59-1].ITM_NO = AIRGLM.ITM_NO59;
        BPCHGLMO.DATA.REL_ITMS[59-1].ITM_SEQ = AIRGLM.ITM_SEQ59;
        BPCHGLMO.DATA.REL_ITMS[60-1].ITM_NO = AIRGLM.ITM_NO60;
        BPCHGLMO.DATA.REL_ITMS[60-1].ITM_SEQ = AIRGLM.ITM_SEQ60;
        CEP.TRC(SCCGWA, BPCUGLM);
        CEP.TRC(SCCGWA, BPCUGLM.DATA.DATA_TXT.EXP_DATE);
        T000_DELETE_AITGLM();
        if (pgmRtn) return;
        S000_INPUT_DATA_PROCESS();
        if (pgmRtn) return;
        BPCHGLMN.KEY.MSTNO = AIRGLM.KEY.GL_MSTNO;
        BPCHGLMN.DATA.COA_FLG = AIRGLM.COA_FLG;
        BPCHGLMN.DATA.SNAME = AIRGLM.DESC;
        BPCHGLMN.DATA.LNAME = AIRGLM.CDESC;
        BPCHGLMN.DATA.EFF_DATE = AIRGLM.KEY.EFF_DT;
        BPCHGLMN.DATA.EXP_DATE = AIRGLM.KEY.EXP_DT;
        BPCHGLMN.DATA.CNTY1 = AIRGLM.CNTY1;
        BPCHGLMN.DATA.CNTY2 = AIRGLM.CNTY2;
        BPCHGLMN.DATA.CNTY3 = AIRGLM.CNTY3;
        BPCHGLMN.DATA.CKFLG = AIRGLM.CKFLG;
        BPCHGLMN.DATA.REAL_GL = AIRGLM.REAL_GL;
        BPCHGLMN.DATA.REL_ITMS[1-1].ITM_NO = AIRGLM.ITM_NO1;
        BPCHGLMN.DATA.REL_ITMS[1-1].ITM_SEQ = AIRGLM.ITM_SEQ1;
        BPCHGLMN.DATA.REL_ITMS[2-1].ITM_NO = AIRGLM.ITM_NO2;
        BPCHGLMN.DATA.REL_ITMS[2-1].ITM_SEQ = AIRGLM.ITM_SEQ2;
        BPCHGLMN.DATA.REL_ITMS[3-1].ITM_NO = AIRGLM.ITM_NO3;
        BPCHGLMN.DATA.REL_ITMS[3-1].ITM_SEQ = AIRGLM.ITM_SEQ3;
        BPCHGLMN.DATA.REL_ITMS[4-1].ITM_NO = AIRGLM.ITM_NO4;
        BPCHGLMN.DATA.REL_ITMS[4-1].ITM_SEQ = AIRGLM.ITM_SEQ4;
        BPCHGLMN.DATA.REL_ITMS[5-1].ITM_NO = AIRGLM.ITM_NO5;
        BPCHGLMN.DATA.REL_ITMS[5-1].ITM_SEQ = AIRGLM.ITM_SEQ5;
        BPCHGLMN.DATA.REL_ITMS[6-1].ITM_NO = AIRGLM.ITM_NO6;
        BPCHGLMN.DATA.REL_ITMS[6-1].ITM_SEQ = AIRGLM.ITM_SEQ6;
        BPCHGLMN.DATA.REL_ITMS[7-1].ITM_NO = AIRGLM.ITM_NO7;
        BPCHGLMN.DATA.REL_ITMS[7-1].ITM_SEQ = AIRGLM.ITM_SEQ7;
        BPCHGLMN.DATA.REL_ITMS[8-1].ITM_NO = AIRGLM.ITM_NO8;
        BPCHGLMN.DATA.REL_ITMS[8-1].ITM_SEQ = AIRGLM.ITM_SEQ8;
        BPCHGLMN.DATA.REL_ITMS[9-1].ITM_NO = AIRGLM.ITM_NO9;
        BPCHGLMN.DATA.REL_ITMS[9-1].ITM_SEQ = AIRGLM.ITM_SEQ9;
        BPCHGLMN.DATA.REL_ITMS[10-1].ITM_NO = AIRGLM.ITM_NO10;
        BPCHGLMN.DATA.REL_ITMS[10-1].ITM_SEQ = AIRGLM.ITM_SEQ10;
        BPCHGLMN.DATA.REL_ITMS[11-1].ITM_NO = AIRGLM.ITM_NO11;
        BPCHGLMN.DATA.REL_ITMS[11-1].ITM_SEQ = AIRGLM.ITM_SEQ11;
        BPCHGLMN.DATA.REL_ITMS[12-1].ITM_NO = AIRGLM.ITM_NO12;
        BPCHGLMN.DATA.REL_ITMS[12-1].ITM_SEQ = AIRGLM.ITM_SEQ12;
        BPCHGLMN.DATA.REL_ITMS[13-1].ITM_NO = AIRGLM.ITM_NO13;
        BPCHGLMN.DATA.REL_ITMS[13-1].ITM_SEQ = AIRGLM.ITM_SEQ13;
        BPCHGLMN.DATA.REL_ITMS[14-1].ITM_NO = AIRGLM.ITM_NO14;
        BPCHGLMN.DATA.REL_ITMS[14-1].ITM_SEQ = AIRGLM.ITM_SEQ14;
        BPCHGLMN.DATA.REL_ITMS[15-1].ITM_NO = AIRGLM.ITM_NO15;
        BPCHGLMN.DATA.REL_ITMS[15-1].ITM_SEQ = AIRGLM.ITM_SEQ15;
        BPCHGLMN.DATA.REL_ITMS[16-1].ITM_NO = AIRGLM.ITM_NO16;
        BPCHGLMN.DATA.REL_ITMS[16-1].ITM_SEQ = AIRGLM.ITM_SEQ16;
        BPCHGLMN.DATA.REL_ITMS[17-1].ITM_NO = AIRGLM.ITM_NO17;
        BPCHGLMN.DATA.REL_ITMS[17-1].ITM_SEQ = AIRGLM.ITM_SEQ17;
        BPCHGLMN.DATA.REL_ITMS[18-1].ITM_NO = AIRGLM.ITM_NO18;
        BPCHGLMN.DATA.REL_ITMS[18-1].ITM_SEQ = AIRGLM.ITM_SEQ18;
        BPCHGLMN.DATA.REL_ITMS[19-1].ITM_NO = AIRGLM.ITM_NO19;
        BPCHGLMN.DATA.REL_ITMS[19-1].ITM_SEQ = AIRGLM.ITM_SEQ19;
        BPCHGLMN.DATA.REL_ITMS[20-1].ITM_NO = AIRGLM.ITM_NO20;
        BPCHGLMN.DATA.REL_ITMS[20-1].ITM_SEQ = AIRGLM.ITM_SEQ20;
        BPCHGLMN.DATA.REL_ITMS[21-1].ITM_NO = AIRGLM.ITM_NO21;
        BPCHGLMN.DATA.REL_ITMS[21-1].ITM_SEQ = AIRGLM.ITM_SEQ21;
        BPCHGLMN.DATA.REL_ITMS[22-1].ITM_NO = AIRGLM.ITM_NO22;
        BPCHGLMN.DATA.REL_ITMS[22-1].ITM_SEQ = AIRGLM.ITM_SEQ22;
        BPCHGLMN.DATA.REL_ITMS[23-1].ITM_NO = AIRGLM.ITM_NO23;
        BPCHGLMN.DATA.REL_ITMS[23-1].ITM_SEQ = AIRGLM.ITM_SEQ23;
        BPCHGLMN.DATA.REL_ITMS[24-1].ITM_NO = AIRGLM.ITM_NO24;
        BPCHGLMN.DATA.REL_ITMS[24-1].ITM_SEQ = AIRGLM.ITM_SEQ24;
        BPCHGLMN.DATA.REL_ITMS[25-1].ITM_NO = AIRGLM.ITM_NO25;
        BPCHGLMN.DATA.REL_ITMS[25-1].ITM_SEQ = AIRGLM.ITM_SEQ25;
        BPCHGLMN.DATA.REL_ITMS[26-1].ITM_NO = AIRGLM.ITM_NO26;
        BPCHGLMN.DATA.REL_ITMS[26-1].ITM_SEQ = AIRGLM.ITM_SEQ26;
        BPCHGLMN.DATA.REL_ITMS[27-1].ITM_NO = AIRGLM.ITM_NO27;
        BPCHGLMN.DATA.REL_ITMS[27-1].ITM_SEQ = AIRGLM.ITM_SEQ27;
        BPCHGLMN.DATA.REL_ITMS[28-1].ITM_NO = AIRGLM.ITM_NO28;
        BPCHGLMN.DATA.REL_ITMS[28-1].ITM_SEQ = AIRGLM.ITM_SEQ28;
        BPCHGLMN.DATA.REL_ITMS[29-1].ITM_NO = AIRGLM.ITM_NO29;
        BPCHGLMN.DATA.REL_ITMS[29-1].ITM_SEQ = AIRGLM.ITM_SEQ29;
        BPCHGLMN.DATA.REL_ITMS[30-1].ITM_NO = AIRGLM.ITM_NO30;
        BPCHGLMN.DATA.REL_ITMS[30-1].ITM_SEQ = AIRGLM.ITM_SEQ30;
        BPCHGLMN.DATA.REL_ITMS[31-1].ITM_NO = AIRGLM.ITM_NO31;
        BPCHGLMN.DATA.REL_ITMS[31-1].ITM_SEQ = AIRGLM.ITM_SEQ31;
        BPCHGLMN.DATA.REL_ITMS[32-1].ITM_NO = AIRGLM.ITM_NO32;
        BPCHGLMN.DATA.REL_ITMS[32-1].ITM_SEQ = AIRGLM.ITM_SEQ32;
        BPCHGLMN.DATA.REL_ITMS[33-1].ITM_NO = AIRGLM.ITM_NO33;
        BPCHGLMN.DATA.REL_ITMS[33-1].ITM_SEQ = AIRGLM.ITM_SEQ33;
        BPCHGLMN.DATA.REL_ITMS[34-1].ITM_NO = AIRGLM.ITM_NO34;
        BPCHGLMN.DATA.REL_ITMS[34-1].ITM_SEQ = AIRGLM.ITM_SEQ34;
        BPCHGLMN.DATA.REL_ITMS[35-1].ITM_NO = AIRGLM.ITM_NO35;
        BPCHGLMN.DATA.REL_ITMS[35-1].ITM_SEQ = AIRGLM.ITM_SEQ35;
        BPCHGLMN.DATA.REL_ITMS[36-1].ITM_NO = AIRGLM.ITM_NO36;
        BPCHGLMN.DATA.REL_ITMS[36-1].ITM_SEQ = AIRGLM.ITM_SEQ36;
        BPCHGLMN.DATA.REL_ITMS[37-1].ITM_NO = AIRGLM.ITM_NO37;
        BPCHGLMN.DATA.REL_ITMS[37-1].ITM_SEQ = AIRGLM.ITM_SEQ37;
        BPCHGLMN.DATA.REL_ITMS[38-1].ITM_NO = AIRGLM.ITM_NO38;
        BPCHGLMN.DATA.REL_ITMS[38-1].ITM_SEQ = AIRGLM.ITM_SEQ38;
        BPCHGLMN.DATA.REL_ITMS[39-1].ITM_NO = AIRGLM.ITM_NO39;
        BPCHGLMN.DATA.REL_ITMS[39-1].ITM_SEQ = AIRGLM.ITM_SEQ39;
        BPCHGLMN.DATA.REL_ITMS[40-1].ITM_NO = AIRGLM.ITM_NO40;
        BPCHGLMN.DATA.REL_ITMS[40-1].ITM_SEQ = AIRGLM.ITM_SEQ40;
        BPCHGLMN.DATA.REL_ITMS[41-1].ITM_NO = AIRGLM.ITM_NO41;
        BPCHGLMN.DATA.REL_ITMS[41-1].ITM_SEQ = AIRGLM.ITM_SEQ41;
        BPCHGLMN.DATA.REL_ITMS[42-1].ITM_NO = AIRGLM.ITM_NO42;
        BPCHGLMN.DATA.REL_ITMS[42-1].ITM_SEQ = AIRGLM.ITM_SEQ42;
        BPCHGLMN.DATA.REL_ITMS[43-1].ITM_NO = AIRGLM.ITM_NO43;
        BPCHGLMN.DATA.REL_ITMS[43-1].ITM_SEQ = AIRGLM.ITM_SEQ43;
        BPCHGLMN.DATA.REL_ITMS[44-1].ITM_NO = AIRGLM.ITM_NO44;
        BPCHGLMN.DATA.REL_ITMS[44-1].ITM_SEQ = AIRGLM.ITM_SEQ44;
        BPCHGLMN.DATA.REL_ITMS[45-1].ITM_NO = AIRGLM.ITM_NO45;
        BPCHGLMN.DATA.REL_ITMS[45-1].ITM_SEQ = AIRGLM.ITM_SEQ45;
        BPCHGLMN.DATA.REL_ITMS[46-1].ITM_NO = AIRGLM.ITM_NO46;
        BPCHGLMN.DATA.REL_ITMS[46-1].ITM_SEQ = AIRGLM.ITM_SEQ46;
        BPCHGLMN.DATA.REL_ITMS[47-1].ITM_NO = AIRGLM.ITM_NO47;
        BPCHGLMN.DATA.REL_ITMS[47-1].ITM_SEQ = AIRGLM.ITM_SEQ47;
        BPCHGLMN.DATA.REL_ITMS[48-1].ITM_NO = AIRGLM.ITM_NO48;
        BPCHGLMN.DATA.REL_ITMS[48-1].ITM_SEQ = AIRGLM.ITM_SEQ48;
        BPCHGLMN.DATA.REL_ITMS[49-1].ITM_NO = AIRGLM.ITM_NO49;
        BPCHGLMN.DATA.REL_ITMS[49-1].ITM_SEQ = AIRGLM.ITM_SEQ49;
        BPCHGLMN.DATA.REL_ITMS[50-1].ITM_NO = AIRGLM.ITM_NO50;
        BPCHGLMN.DATA.REL_ITMS[50-1].ITM_SEQ = AIRGLM.ITM_SEQ50;
        BPCHGLMN.DATA.REL_ITMS[51-1].ITM_NO = AIRGLM.ITM_NO51;
        BPCHGLMN.DATA.REL_ITMS[51-1].ITM_SEQ = AIRGLM.ITM_SEQ51;
        BPCHGLMN.DATA.REL_ITMS[52-1].ITM_NO = AIRGLM.ITM_NO52;
        BPCHGLMN.DATA.REL_ITMS[52-1].ITM_SEQ = AIRGLM.ITM_SEQ52;
        BPCHGLMN.DATA.REL_ITMS[53-1].ITM_NO = AIRGLM.ITM_NO53;
        BPCHGLMN.DATA.REL_ITMS[53-1].ITM_SEQ = AIRGLM.ITM_SEQ53;
        BPCHGLMN.DATA.REL_ITMS[54-1].ITM_NO = AIRGLM.ITM_NO54;
        BPCHGLMN.DATA.REL_ITMS[54-1].ITM_SEQ = AIRGLM.ITM_SEQ54;
        BPCHGLMN.DATA.REL_ITMS[55-1].ITM_NO = AIRGLM.ITM_NO55;
        BPCHGLMN.DATA.REL_ITMS[55-1].ITM_SEQ = AIRGLM.ITM_SEQ55;
        BPCHGLMN.DATA.REL_ITMS[56-1].ITM_NO = AIRGLM.ITM_NO56;
        BPCHGLMN.DATA.REL_ITMS[56-1].ITM_SEQ = AIRGLM.ITM_SEQ56;
        BPCHGLMN.DATA.REL_ITMS[57-1].ITM_NO = AIRGLM.ITM_NO57;
        BPCHGLMN.DATA.REL_ITMS[57-1].ITM_SEQ = AIRGLM.ITM_SEQ57;
        BPCHGLMN.DATA.REL_ITMS[58-1].ITM_NO = AIRGLM.ITM_NO58;
        BPCHGLMN.DATA.REL_ITMS[58-1].ITM_SEQ = AIRGLM.ITM_SEQ58;
        BPCHGLMN.DATA.REL_ITMS[59-1].ITM_NO = AIRGLM.ITM_NO59;
        BPCHGLMN.DATA.REL_ITMS[59-1].ITM_SEQ = AIRGLM.ITM_SEQ59;
        BPCHGLMN.DATA.REL_ITMS[60-1].ITM_NO = AIRGLM.ITM_NO60;
        BPCHGLMN.DATA.REL_ITMS[60-1].ITM_SEQ = AIRGLM.ITM_SEQ60;
        CEP.TRC(SCCGWA, BPCUGLM.DATA.DATA_TXT.EFF_DATE);
        CEP.TRC(SCCGWA, BPCUGLM.DATA.DATA_TXT.EXP_DATE);
        CEP.TRC(SCCGWA, BPCUGLM.DATA.P_EFF_DATE);
        CEP.TRC(SCCGWA, BPCUGLM.DATA.P_EXP_DATE);
        CEP.TRC(SCCGWA, AIRGLM);
        T000_WRITE_AITGLM();
        if (pgmRtn) return;
    }
    public void B050_DELETE_RECORD_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, AIRGLM);
        AIRGLM.KEY.IBS_AC_BK = SCCGWA.COMM_AREA.TR_BANK;
        AIRGLM.KEY.GL_MSTNO = BPCUGLM.DATA.KEY.REDEFINES16.MSTNO;
        if (BPCUGLM.DATA.DATA_TXT.EFF_DATE == 0) {
            AIRGLM.KEY.EFF_DT = SCCGWA.COMM_AREA.AC_DATE;
        } else {
            AIRGLM.KEY.EFF_DT = BPCUGLM.DATA.DATA_TXT.EFF_DATE;
        }
        if (BPCUGLM.DATA.DATA_TXT.EXP_DATE == 0) {
            AIRGLM.KEY.EXP_DT = SCCGWA.COMM_AREA.AC_DATE;
        } else {
            AIRGLM.KEY.EXP_DT = BPCUGLM.DATA.DATA_TXT.EXP_DATE;
        }
        T000_READUP_AITGLM();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, BPCUGLM.DATA.DATA_TXT.UPD_DATE);
        CEP.TRC(SCCGWA, BPCUGLM.DATA.DATA_TXT.UPD_TIME);
        WS_UPD_DT = AIRGLM.UPD_DATE;
        WS_UPD_TM = AIRGLM.UPD_TIME;
        CEP.TRC(SCCGWA, AIRGLM.UPD_DATE);
        CEP.TRC(SCCGWA, AIRGLM.UPD_TIME);
        if (BPCUGLM.DATA.DATA_TXT.UPD_DATE != WS_UPD_DT 
            || BPCUGLM.DATA.DATA_TXT.UPD_TIME != WS_UPD_TM) {
            WS_MSG_ERR = BPCMSG_ERROR_MSG.BP_RECORD_ALREADY_CHANG;
            S000_ERR_MSG_PROC();
            if (pgmRtn) return;
        }
        T000_DELETE_AITGLM();
        if (pgmRtn) return;
        BPCHGLM.KEY.MSTNO = AIRGLM.KEY.GL_MSTNO;
        BPCHGLM.DATA.COA_FLG = AIRGLM.COA_FLG;
        BPCHGLM.DATA.SNAME = AIRGLM.DESC;
        BPCHGLM.DATA.LNAME = AIRGLM.CDESC;
        BPCHGLM.DATA.EFF_DATE = AIRGLM.KEY.EFF_DT;
        BPCHGLM.DATA.EXP_DATE = AIRGLM.KEY.EXP_DT;
        BPCHGLM.DATA.CNTY1 = AIRGLM.CNTY1;
        BPCHGLM.DATA.CNTY2 = AIRGLM.CNTY2;
        BPCHGLM.DATA.CNTY3 = AIRGLM.CNTY3;
        BPCHGLM.DATA.CKFLG = AIRGLM.CKFLG;
        BPCHGLM.DATA.REAL_GL = AIRGLM.REAL_GL;
        BPCHGLM.DATA.REL_ITMS[1-1].ITM_NO = AIRGLM.ITM_NO1;
        BPCHGLM.DATA.REL_ITMS[1-1].ITM_SEQ = AIRGLM.ITM_SEQ1;
        BPCHGLM.DATA.REL_ITMS[2-1].ITM_NO = AIRGLM.ITM_NO2;
        BPCHGLM.DATA.REL_ITMS[2-1].ITM_SEQ = AIRGLM.ITM_SEQ2;
        BPCHGLM.DATA.REL_ITMS[3-1].ITM_NO = AIRGLM.ITM_NO3;
        BPCHGLM.DATA.REL_ITMS[3-1].ITM_SEQ = AIRGLM.ITM_SEQ3;
        BPCHGLM.DATA.REL_ITMS[4-1].ITM_NO = AIRGLM.ITM_NO4;
        BPCHGLM.DATA.REL_ITMS[4-1].ITM_SEQ = AIRGLM.ITM_SEQ4;
        BPCHGLM.DATA.REL_ITMS[5-1].ITM_NO = AIRGLM.ITM_NO5;
        BPCHGLM.DATA.REL_ITMS[5-1].ITM_SEQ = AIRGLM.ITM_SEQ5;
        BPCHGLM.DATA.REL_ITMS[6-1].ITM_NO = AIRGLM.ITM_NO6;
        BPCHGLM.DATA.REL_ITMS[6-1].ITM_SEQ = AIRGLM.ITM_SEQ6;
        BPCHGLM.DATA.REL_ITMS[7-1].ITM_NO = AIRGLM.ITM_NO7;
        BPCHGLM.DATA.REL_ITMS[7-1].ITM_SEQ = AIRGLM.ITM_SEQ7;
        BPCHGLM.DATA.REL_ITMS[8-1].ITM_NO = AIRGLM.ITM_NO8;
        BPCHGLM.DATA.REL_ITMS[8-1].ITM_SEQ = AIRGLM.ITM_SEQ8;
        BPCHGLM.DATA.REL_ITMS[9-1].ITM_NO = AIRGLM.ITM_NO9;
        BPCHGLM.DATA.REL_ITMS[9-1].ITM_SEQ = AIRGLM.ITM_SEQ9;
        BPCHGLM.DATA.REL_ITMS[10-1].ITM_NO = AIRGLM.ITM_NO10;
        BPCHGLM.DATA.REL_ITMS[10-1].ITM_SEQ = AIRGLM.ITM_SEQ10;
        BPCHGLM.DATA.REL_ITMS[11-1].ITM_NO = AIRGLM.ITM_NO11;
        BPCHGLM.DATA.REL_ITMS[11-1].ITM_SEQ = AIRGLM.ITM_SEQ11;
        BPCHGLM.DATA.REL_ITMS[12-1].ITM_NO = AIRGLM.ITM_NO12;
        BPCHGLM.DATA.REL_ITMS[12-1].ITM_SEQ = AIRGLM.ITM_SEQ12;
        BPCHGLM.DATA.REL_ITMS[13-1].ITM_NO = AIRGLM.ITM_NO13;
        BPCHGLM.DATA.REL_ITMS[13-1].ITM_SEQ = AIRGLM.ITM_SEQ13;
        BPCHGLM.DATA.REL_ITMS[14-1].ITM_NO = AIRGLM.ITM_NO14;
        BPCHGLM.DATA.REL_ITMS[14-1].ITM_SEQ = AIRGLM.ITM_SEQ14;
        BPCHGLM.DATA.REL_ITMS[15-1].ITM_NO = AIRGLM.ITM_NO15;
        BPCHGLM.DATA.REL_ITMS[15-1].ITM_SEQ = AIRGLM.ITM_SEQ15;
        BPCHGLM.DATA.REL_ITMS[16-1].ITM_NO = AIRGLM.ITM_NO16;
        BPCHGLM.DATA.REL_ITMS[16-1].ITM_SEQ = AIRGLM.ITM_SEQ16;
        BPCHGLM.DATA.REL_ITMS[17-1].ITM_NO = AIRGLM.ITM_NO17;
        BPCHGLM.DATA.REL_ITMS[17-1].ITM_SEQ = AIRGLM.ITM_SEQ17;
        BPCHGLM.DATA.REL_ITMS[18-1].ITM_NO = AIRGLM.ITM_NO18;
        BPCHGLM.DATA.REL_ITMS[18-1].ITM_SEQ = AIRGLM.ITM_SEQ18;
        BPCHGLM.DATA.REL_ITMS[19-1].ITM_NO = AIRGLM.ITM_NO19;
        BPCHGLM.DATA.REL_ITMS[19-1].ITM_SEQ = AIRGLM.ITM_SEQ19;
        BPCHGLM.DATA.REL_ITMS[20-1].ITM_NO = AIRGLM.ITM_NO20;
        BPCHGLM.DATA.REL_ITMS[20-1].ITM_SEQ = AIRGLM.ITM_SEQ20;
        BPCHGLM.DATA.REL_ITMS[21-1].ITM_NO = AIRGLM.ITM_NO21;
        BPCHGLM.DATA.REL_ITMS[21-1].ITM_SEQ = AIRGLM.ITM_SEQ21;
        BPCHGLM.DATA.REL_ITMS[22-1].ITM_NO = AIRGLM.ITM_NO22;
        BPCHGLM.DATA.REL_ITMS[22-1].ITM_SEQ = AIRGLM.ITM_SEQ22;
        BPCHGLM.DATA.REL_ITMS[23-1].ITM_NO = AIRGLM.ITM_NO23;
        BPCHGLM.DATA.REL_ITMS[23-1].ITM_SEQ = AIRGLM.ITM_SEQ23;
        BPCHGLM.DATA.REL_ITMS[24-1].ITM_NO = AIRGLM.ITM_NO24;
        BPCHGLM.DATA.REL_ITMS[24-1].ITM_SEQ = AIRGLM.ITM_SEQ24;
        BPCHGLM.DATA.REL_ITMS[25-1].ITM_NO = AIRGLM.ITM_NO25;
        BPCHGLM.DATA.REL_ITMS[25-1].ITM_SEQ = AIRGLM.ITM_SEQ25;
        BPCHGLM.DATA.REL_ITMS[26-1].ITM_NO = AIRGLM.ITM_NO26;
        BPCHGLM.DATA.REL_ITMS[26-1].ITM_SEQ = AIRGLM.ITM_SEQ26;
        BPCHGLM.DATA.REL_ITMS[27-1].ITM_NO = AIRGLM.ITM_NO27;
        BPCHGLM.DATA.REL_ITMS[27-1].ITM_SEQ = AIRGLM.ITM_SEQ27;
        BPCHGLM.DATA.REL_ITMS[28-1].ITM_NO = AIRGLM.ITM_NO28;
        BPCHGLM.DATA.REL_ITMS[28-1].ITM_SEQ = AIRGLM.ITM_SEQ28;
        BPCHGLM.DATA.REL_ITMS[29-1].ITM_NO = AIRGLM.ITM_NO29;
        BPCHGLM.DATA.REL_ITMS[29-1].ITM_SEQ = AIRGLM.ITM_SEQ29;
        BPCHGLM.DATA.REL_ITMS[30-1].ITM_NO = AIRGLM.ITM_NO30;
        BPCHGLM.DATA.REL_ITMS[30-1].ITM_SEQ = AIRGLM.ITM_SEQ30;
        BPCHGLM.DATA.REL_ITMS[31-1].ITM_NO = AIRGLM.ITM_NO31;
        BPCHGLM.DATA.REL_ITMS[31-1].ITM_SEQ = AIRGLM.ITM_SEQ31;
        BPCHGLM.DATA.REL_ITMS[32-1].ITM_NO = AIRGLM.ITM_NO32;
        BPCHGLM.DATA.REL_ITMS[32-1].ITM_SEQ = AIRGLM.ITM_SEQ32;
        BPCHGLM.DATA.REL_ITMS[33-1].ITM_NO = AIRGLM.ITM_NO33;
        BPCHGLM.DATA.REL_ITMS[33-1].ITM_SEQ = AIRGLM.ITM_SEQ33;
        BPCHGLM.DATA.REL_ITMS[34-1].ITM_NO = AIRGLM.ITM_NO34;
        BPCHGLM.DATA.REL_ITMS[34-1].ITM_SEQ = AIRGLM.ITM_SEQ34;
        BPCHGLM.DATA.REL_ITMS[35-1].ITM_NO = AIRGLM.ITM_NO35;
        BPCHGLM.DATA.REL_ITMS[35-1].ITM_SEQ = AIRGLM.ITM_SEQ35;
        BPCHGLM.DATA.REL_ITMS[36-1].ITM_NO = AIRGLM.ITM_NO36;
        BPCHGLM.DATA.REL_ITMS[36-1].ITM_SEQ = AIRGLM.ITM_SEQ36;
        BPCHGLM.DATA.REL_ITMS[37-1].ITM_NO = AIRGLM.ITM_NO37;
        BPCHGLM.DATA.REL_ITMS[37-1].ITM_SEQ = AIRGLM.ITM_SEQ37;
        BPCHGLM.DATA.REL_ITMS[38-1].ITM_NO = AIRGLM.ITM_NO38;
        BPCHGLM.DATA.REL_ITMS[38-1].ITM_SEQ = AIRGLM.ITM_SEQ38;
        BPCHGLM.DATA.REL_ITMS[39-1].ITM_NO = AIRGLM.ITM_NO39;
        BPCHGLM.DATA.REL_ITMS[39-1].ITM_SEQ = AIRGLM.ITM_SEQ39;
        BPCHGLM.DATA.REL_ITMS[40-1].ITM_NO = AIRGLM.ITM_NO40;
        BPCHGLM.DATA.REL_ITMS[40-1].ITM_SEQ = AIRGLM.ITM_SEQ40;
        BPCHGLM.DATA.REL_ITMS[41-1].ITM_NO = AIRGLM.ITM_NO41;
        BPCHGLM.DATA.REL_ITMS[41-1].ITM_SEQ = AIRGLM.ITM_SEQ41;
        BPCHGLM.DATA.REL_ITMS[42-1].ITM_NO = AIRGLM.ITM_NO42;
        BPCHGLM.DATA.REL_ITMS[42-1].ITM_SEQ = AIRGLM.ITM_SEQ42;
        BPCHGLM.DATA.REL_ITMS[43-1].ITM_NO = AIRGLM.ITM_NO43;
        BPCHGLM.DATA.REL_ITMS[43-1].ITM_SEQ = AIRGLM.ITM_SEQ43;
        BPCHGLM.DATA.REL_ITMS[44-1].ITM_NO = AIRGLM.ITM_NO44;
        BPCHGLM.DATA.REL_ITMS[44-1].ITM_SEQ = AIRGLM.ITM_SEQ44;
        BPCHGLM.DATA.REL_ITMS[45-1].ITM_NO = AIRGLM.ITM_NO45;
        BPCHGLM.DATA.REL_ITMS[45-1].ITM_SEQ = AIRGLM.ITM_SEQ45;
        BPCHGLM.DATA.REL_ITMS[46-1].ITM_NO = AIRGLM.ITM_NO46;
        BPCHGLM.DATA.REL_ITMS[46-1].ITM_SEQ = AIRGLM.ITM_SEQ46;
        BPCHGLM.DATA.REL_ITMS[47-1].ITM_NO = AIRGLM.ITM_NO47;
        BPCHGLM.DATA.REL_ITMS[47-1].ITM_SEQ = AIRGLM.ITM_SEQ47;
        BPCHGLM.DATA.REL_ITMS[48-1].ITM_NO = AIRGLM.ITM_NO48;
        BPCHGLM.DATA.REL_ITMS[48-1].ITM_SEQ = AIRGLM.ITM_SEQ48;
        BPCHGLM.DATA.REL_ITMS[49-1].ITM_NO = AIRGLM.ITM_NO49;
        BPCHGLM.DATA.REL_ITMS[49-1].ITM_SEQ = AIRGLM.ITM_SEQ49;
        BPCHGLM.DATA.REL_ITMS[50-1].ITM_NO = AIRGLM.ITM_NO50;
        BPCHGLM.DATA.REL_ITMS[50-1].ITM_SEQ = AIRGLM.ITM_SEQ50;
        BPCHGLM.DATA.REL_ITMS[51-1].ITM_NO = AIRGLM.ITM_NO51;
        BPCHGLM.DATA.REL_ITMS[51-1].ITM_SEQ = AIRGLM.ITM_SEQ51;
        BPCHGLM.DATA.REL_ITMS[52-1].ITM_NO = AIRGLM.ITM_NO52;
        BPCHGLM.DATA.REL_ITMS[52-1].ITM_SEQ = AIRGLM.ITM_SEQ52;
        BPCHGLM.DATA.REL_ITMS[53-1].ITM_NO = AIRGLM.ITM_NO53;
        BPCHGLM.DATA.REL_ITMS[53-1].ITM_SEQ = AIRGLM.ITM_SEQ53;
        BPCHGLM.DATA.REL_ITMS[54-1].ITM_NO = AIRGLM.ITM_NO54;
        BPCHGLM.DATA.REL_ITMS[54-1].ITM_SEQ = AIRGLM.ITM_SEQ54;
        BPCHGLM.DATA.REL_ITMS[55-1].ITM_NO = AIRGLM.ITM_NO55;
        BPCHGLM.DATA.REL_ITMS[55-1].ITM_SEQ = AIRGLM.ITM_SEQ55;
        BPCHGLM.DATA.REL_ITMS[56-1].ITM_NO = AIRGLM.ITM_NO56;
        BPCHGLM.DATA.REL_ITMS[56-1].ITM_SEQ = AIRGLM.ITM_SEQ56;
        BPCHGLM.DATA.REL_ITMS[57-1].ITM_NO = AIRGLM.ITM_NO57;
        BPCHGLM.DATA.REL_ITMS[57-1].ITM_SEQ = AIRGLM.ITM_SEQ57;
        BPCHGLM.DATA.REL_ITMS[58-1].ITM_NO = AIRGLM.ITM_NO58;
        BPCHGLM.DATA.REL_ITMS[58-1].ITM_SEQ = AIRGLM.ITM_SEQ58;
        BPCHGLM.DATA.REL_ITMS[59-1].ITM_NO = AIRGLM.ITM_NO59;
        BPCHGLM.DATA.REL_ITMS[59-1].ITM_SEQ = AIRGLM.ITM_SEQ59;
        BPCHGLM.DATA.REL_ITMS[60-1].ITM_NO = AIRGLM.ITM_NO60;
        BPCHGLM.DATA.REL_ITMS[60-1].ITM_SEQ = AIRGLM.ITM_SEQ60;
    }
    public void T000_READ_AITGLM() throws IOException,SQLException,Exception {
    if (!SCCGWA.COMM_AREA.BSP_FLG.equalsIgnoreCase("BSP") && !SCCGWA.COMM_AREA.CHNL.equalsIgnoreCase("BAT")) { //FROM #IFDEF ONL
        if (SCCGWA.COMM_AREA.PARM_IND == 'E') {
            WS_J = 0;
            WS_J = 1;
            SCCGWA.COMM_AREA.DBIO_FLG = '0';
            WS_GLM_FLG = 'N';
            IBS.init(SCCGWA, BPCPRMBR.CD);
            BPCPRMBR.TYP = "AITGLM";
            BPCPRMBR.CD.KEY = IBS.CLS2CPY(SCCGWA, WS_GLM_KEY);
            BPCPRMBR.LTH = 4767;
            BPCPRMBR.CD.KEY_KEYSEQ = (short) WS_J;
            BPCPRMBR.CD.KEY_BEGSEQ = WS_GLM_LAST_BEGSEQ;
            AIRGLM = (AIRGLM) IBS.HASHLKUP(SCCGWA, "AIRGLM", BPCPRMBR.CD);
            WS_J += 1;
            WS_GLM_LAST_BEGSEQ = 0;
            WS_GLM_LAST_BEGSEQ = BPCPRMBR.CD.KEY_BEGSEQ;
            if (SCCGWA.COMM_AREA.DBIO_FLG != '0') {
                AITGLM_RD = new DBParm();
                AITGLM_RD.TableName = "AITGLM";
                AITGLM_RD.where = "IBS_AC_BK = :AIRGLM.KEY.IBS_AC_BK "
                    + "AND GL_MSTNO = :AIRGLM.KEY.GL_MSTNO "
                    + "AND EFF_DT <= :AIRGLM.KEY.EFF_DT";
                IBS.READ(SCCGWA, AIRGLM, this, AITGLM_RD);
            }
        } else {
            AITGLM_RD = new DBParm();
            AITGLM_RD.TableName = "AITGLM";
            AITGLM_RD.where = "IBS_AC_BK = :AIRGLM.KEY.IBS_AC_BK "
                + "AND GL_MSTNO = :AIRGLM.KEY.GL_MSTNO "
                + "AND EFF_DT <= :AIRGLM.KEY.EFF_DT";
            IBS.READ(SCCGWA, AIRGLM, this, AITGLM_RD);
        }
    } else { //FROM #ELSE
        AITGLM_RD = new DBParm();
        AITGLM_RD.TableName = "AITGLM";
        AITGLM_RD.where = "IBS_AC_BK = :AIRGLM.KEY.IBS_AC_BK "
            + "AND GL_MSTNO = :AIRGLM.KEY.GL_MSTNO "
            + "AND EFF_DT <= :AIRGLM.KEY.EFF_DT";
        IBS.READ(SCCGWA, AIRGLM, this, AITGLM_RD);
    } //FROM #ENDIF
        if (SCCGWA.COMM_AREA.DBIO_FLG == '0') {
        } else if (SCCGWA.COMM_AREA.DBIO_FLG == '1') {
            WS_GLM_FLG = 'N';
            WS_MSG_ERR = AICMSG_ERROR_MSG.AI_AITGLM_NOTFND;
            S000_ERR_MSG_PROC();
            if (pgmRtn) return;
        } else {
            IBS.init(SCCGWA, SCCEXCP);
            SCCEXCP.MSG_TEXT.MSG_TEXT_D.TABLE_NAME = "AITGLM";
            SCCEXCP.MSG_TEXT.SYS_INFO = IBS.CLS2CPY(SCCGWA, SCCEXCP.MSG_TEXT.MSG_TEXT_D);
            SCCEXCP.MSG_TEXT.MSG_TEXT_D.DB_FUNC = "READ";
            B_DB_EXCP();
            if (pgmRtn) return;
        }
    }
    public void T000_WRITE_AITGLM() throws IOException,SQLException,Exception {
        AITGLM_RD = new DBParm();
        AITGLM_RD.TableName = "AITGLM";
        IBS.WRITE(SCCGWA, AIRGLM, AITGLM_RD);
        if (SCCGWA.COMM_AREA.PARM_IND == 'E') {
            SCCGWA.COMM_AREA.PARM_CHANGED = 12;
        }
        if (SCCGWA.COMM_AREA.DBIO_FLG == '0'
            || SCCGWA.COMM_AREA.DBIO_FLG == '1') {
        } else {
            IBS.init(SCCGWA, SCCEXCP);
            SCCEXCP.MSG_TEXT.MSG_TEXT_D.TABLE_NAME = "AITGLM";
            SCCEXCP.MSG_TEXT.SYS_INFO = IBS.CLS2CPY(SCCGWA, SCCEXCP.MSG_TEXT.MSG_TEXT_D);
            SCCEXCP.MSG_TEXT.MSG_TEXT_D.DB_FUNC = "WRITE";
            B_DB_EXCP();
            if (pgmRtn) return;
        }
    }
    public void T000_READUP_AITGLM() throws IOException,SQLException,Exception {
        AITGLM_RD = new DBParm();
        AITGLM_RD.TableName = "AITGLM";
        AITGLM_RD.where = "IBS_AC_BK = :AIRGLM.KEY.IBS_AC_BK "
            + "AND GL_MSTNO = :AIRGLM.KEY.GL_MSTNO "
            + "AND EFF_DT <= :AIRGLM.KEY.EFF_DT";
        AITGLM_RD.upd = true;
        IBS.READ(SCCGWA, AIRGLM, this, AITGLM_RD);
        if (SCCGWA.COMM_AREA.DBIO_FLG == '0') {
        } else if (SCCGWA.COMM_AREA.DBIO_FLG == '1') {
            WS_MSG_ERR = AICMSG_ERROR_MSG.AI_AITGLM_NOTFND;
            S000_ERR_MSG_PROC();
            if (pgmRtn) return;
        } else {
            IBS.init(SCCGWA, SCCEXCP);
            SCCEXCP.MSG_TEXT.MSG_TEXT_D.TABLE_NAME = "AITGLM";
            SCCEXCP.MSG_TEXT.SYS_INFO = IBS.CLS2CPY(SCCGWA, SCCEXCP.MSG_TEXT.MSG_TEXT_D);
            SCCEXCP.MSG_TEXT.MSG_TEXT_D.DB_FUNC = "READ";
            B_DB_EXCP();
            if (pgmRtn) return;
        }
    }
    public void T000_REWRITE_AITGLM() throws IOException,SQLException,Exception {
        AITGLM_RD = new DBParm();
        AITGLM_RD.TableName = "AITGLM";
        IBS.REWRITE(SCCGWA, AIRGLM, AITGLM_RD);
        if (SCCGWA.COMM_AREA.PARM_IND == 'E') {
            SCCGWA.COMM_AREA.PARM_CHANGED = 12;
        }
        if (SCCGWA.COMM_AREA.DBIO_FLG == '0'
            || SCCGWA.COMM_AREA.DBIO_FLG == '1') {
        } else {
            IBS.init(SCCGWA, SCCEXCP);
            SCCEXCP.MSG_TEXT.MSG_TEXT_D.TABLE_NAME = "AITGLM";
            SCCEXCP.MSG_TEXT.SYS_INFO = IBS.CLS2CPY(SCCGWA, SCCEXCP.MSG_TEXT.MSG_TEXT_D);
            SCCEXCP.MSG_TEXT.MSG_TEXT_D.DB_FUNC = "REWRITE";
            B_DB_EXCP();
            if (pgmRtn) return;
        }
    }
    public void T000_DELETE_AITGLM() throws IOException,SQLException,Exception {
        AITGLM_RD = new DBParm();
        AITGLM_RD.TableName = "AITGLM";
        IBS.DELETE(SCCGWA, AIRGLM, AITGLM_RD);
        if (SCCGWA.COMM_AREA.PARM_IND == 'E') {
            SCCGWA.COMM_AREA.PARM_CHANGED = 12;
        }
        if (SCCGWA.COMM_AREA.DBIO_FLG == '0'
            || SCCGWA.COMM_AREA.DBIO_FLG == '1') {
        } else {
            IBS.init(SCCGWA, SCCEXCP);
            SCCEXCP.MSG_TEXT.MSG_TEXT_D.TABLE_NAME = "AITGLM";
            SCCEXCP.MSG_TEXT.SYS_INFO = IBS.CLS2CPY(SCCGWA, SCCEXCP.MSG_TEXT.MSG_TEXT_D);
            SCCEXCP.MSG_TEXT.MSG_TEXT_D.DB_FUNC = "DELETE";
            B_DB_EXCP();
            if (pgmRtn) return;
        }
    }
    public void S000_FOUND_GL_BOOK_FLG() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCQBKPM);
        BPCQBKPM.COA_TYP = AIRGLM.COA_FLG;
        BPCQBKPM.FUNC = 'B';
        S000_CALL_BPZQBKPM();
        if (pgmRtn) return;
        WS_QBKPM_CNT = BPCQBKPM.CNT;
        for (WS_CNT = 1; WS_CNT <= BPCQBKPM.CNT; WS_CNT += 1) {
            WS_QBKPM_INF[WS_CNT-1].WS_BOOK_FLG = BPCQBKPM.DATA[WS_CNT-1].BOOK_FLG;
            WS_QBKPM_INF[WS_CNT-1].WS_COAFLG = BPCQBKPM.DATA[WS_CNT-1].COA_FLG;
            WS_QBKPM_INF[WS_CNT-1].WS_BOOK_TYP = BPCQBKPM.DATA[WS_CNT-1].BOOK_TYP;
        }
    }
    public void S000_CALL_AIZRCMIB() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "AI-R-MAIN-CMIB", AICRCMIB);
        if (AICRCMIB.RC.RC_CODE != 0) {
            WS_MSG_ERR = IBS.CLS2CPY(SCCGWA, AICRCMIB.RC);
            S000_ERR_MSG_PROC();
            if (pgmRtn) return;
        }
    }
    public void S000_CALL_BPZQBKPM() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-Q-MAINT-AMBKP", BPCQBKPM);
        if (BPCQBKPM.RC.RC_RTNCODE != 0) {
            WS_MSG_ERR = "" + BPCQBKPM.RC.RC_RTNCODE;
            JIBS_tmp_int = WS_MSG_ERR.length();
            for (int i=0;i<4-JIBS_tmp_int;i++) WS_MSG_ERR = "0" + WS_MSG_ERR;
            S000_ERR_MSG_PROC();
            if (pgmRtn) return;
        }
    }
    public void B021_MOVE_DATA() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, WS_KEY);
        JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, AIRGLM);
        IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], WS_VAL);
        CEP.TRC(SCCGWA, WS_VAL.WS_UPD_DATE);
        CEP.TRC(SCCGWA, WS_VAL.WS_UPD_TIME);
        if (BPCUGLM.INFO.FUNC == 'I') {
            IBS.init(SCCGWA, BPCUGLM);
            BPCUGLM.DATA.DATA_TXT.UPD_DATE = WS_VAL.WS_UPD_DATE;
            BPCUGLM.DATA.DATA_TXT.UPD_TIME = WS_VAL.WS_UPD_TIME;
        } else {
            IBS.init(SCCGWA, BPCUGLM);
        }
        CEP.TRC(SCCGWA, BPCUGLM.DATA.DATA_TXT.UPD_DATE);
        CEP.TRC(SCCGWA, BPCUGLM.DATA.DATA_TXT.UPD_TIME);
        BPCUGLM.DATA.KEY.REDEFINES16.MSTNO = WS_VAL.WS_GL_MSTNO;
        BPCUGLM.DATA.KEY.CD = IBS.CLS2CPY(SCCGWA, BPCUGLM.DATA.KEY.REDEFINES16);
        BPCUGLM.DATA.DATA_TXT.COA_FLG = WS_VAL.WS_COA_FLG;
        BPCUGLM.DATA.DATA_TXT.SNAME = WS_VAL.WS_SNAME;
        BPCUGLM.DATA.DATA_TXT.LNAME = WS_VAL.WS_LNAME;
        BPCUGLM.DATA.DATA_TXT.EFF_DATE = WS_VAL.WS_EFF_DATE;
        BPCUGLM.DATA.DATA_TXT.EXP_DATE = WS_VAL.WS_EXP_DATE;
        BPCUGLM.DATA.DATA_TXT.CNTY1 = WS_VAL.WS_CNTY1;
        BPCUGLM.DATA.DATA_TXT.CNTY2 = WS_VAL.WS_CNTY2;
        BPCUGLM.DATA.DATA_TXT.CNTY3 = WS_VAL.WS_CNTY3;
        BPCUGLM.DATA.DATA_TXT.CKFLG = WS_VAL.WS_CKFLG;
        BPCUGLM.DATA.DATA_TXT.REAL_GL = WS_VAL.WS_REAL_GL;
        BPCUGLM.DATA.DATA_TXT.MEMO_GL = WS_VAL.WS_MEMO_GL;
        BPCUGLM.DATA.P_EFF_DATE = WS_VAL.WS_EFF_DATE;
        BPCUGLM.DATA.P_EXP_DATE = WS_VAL.WS_EXP_DATE;
        CEP.TRC(SCCGWA, BPCUGLM);
        CEP.TRC(SCCGWA, WS_VAL.WS_REL_ITMS[34-1].WS_ITM_NO);
        for (WS_I = 1; WS_I <= 60; WS_I += 1) {
            if (!WS_VAL.WS_REL_ITMS[WS_I-1].WS_ITM_NO.equalsIgnoreCase("0")) {
                BPCUGLM.DATA.DATA_TXT.REL_ITMS[WS_I-1].ITM_NO = WS_VAL.WS_REL_ITMS[WS_I-1].WS_ITM_NO;
                BPCUGLM.DATA.DATA_TXT.REL_ITMS[WS_I-1].ITM_SEQ = WS_VAL.WS_REL_ITMS[WS_I-1].WS_ITM_SEQ;
                BPCUGLM.DATA.DATA_TXT.REL_ITMS[WS_I-1].REMARK = WS_VAL.WS_REL_ITMS[WS_I-1].WS_REMARK;
            }
        }
    }
    public void S000_CALL_BPZRCNGL() throws IOException,SQLException,Exception {
        BPCRCNGL.DAT_PTR = BPRCNGL;
        CEP.TRC(SCCGWA, BPRCNGL.MSTNO);
        IBS.CALLCPN(SCCGWA, "BP-R-MAINT-CNGL", BPCRCNGL);
        if (BPCRCNGL.RC.RC_RTNCODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, BPCRCNGL.RC);
            if (JIBS_tmp_str[0].equalsIgnoreCase(BPCMSG_ERROR_MSG.BP_CNTR_NOT_EXIST)) {
                WS_FND_FLG = 'N';
            } else {
                WS_MSG_ERR = IBS.CLS2CPY(SCCGWA, BPCRCNGL.RC);
                S000_ERR_MSG_PROC();
                if (pgmRtn) return;
            }
        }
    }
    public void S000_HISTORY_PROCESS() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCPNHIS);
        if (BPCUGLM.INFO.FUNC == 'A' 
            || BPCUGLM.INFO.FUNC == 'D') {
            S000_01_HISTORY_PROCESS();
            if (pgmRtn) return;
        }
        if (BPCUGLM.INFO.FUNC == 'U') {
            S000_02_HISTORY_PROCESS();
            if (pgmRtn) return;
        }
    }
    public void S000_01_HISTORY_PROCESS() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCHGLMO);
        IBS.init(SCCGWA, BPCHGLMN);
        if (BPCUGLM.INFO.FUNC == 'A') {
            BPCPNHIS.INFO.TX_TYP = 'A';
            IBS.CLONE(SCCGWA, BPCHGLM, BPCHGLMN);
        }
        if (BPCUGLM.INFO.FUNC == 'D') {
            BPCPNHIS.INFO.TX_TYP = 'D';
            IBS.CLONE(SCCGWA, BPCHGLM, BPCHGLMO);
        }
        BPCPNHIS.INFO.FMT_ID = "BPCHGLM";
        BPCPNHIS.INFO.JRNNO = SCCGWA.COMM_AREA.JRN_NO;
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.JRN_NO);
        CEP.TRC(SCCGWA, BPCPNHIS.INFO.JRNNO);
        CEP.TRC(SCCGWA, BPCPNHIS.INFO.TX_TYP_CD);
        BPCPNHIS.INFO.TX_RMK = K_HIS_REMARKS;
        BPCPNHIS.INFO.DATA_FLG = 'Y';
        BPCPNHIS.INFO.FMT_ID_LEN = 1174;
        BPCPNHIS.INFO.OLD_DAT_PT = BPCHGLMO;
        BPCPNHIS.INFO.NEW_DAT_PT = BPCHGLMN;
        S000_CALL_BPZPNHIS();
        if (pgmRtn) return;
    }
    public void S000_02_HISTORY_PROCESS() throws IOException,SQLException,Exception {
        BPCPNHIS.INFO.TX_TYP = 'M';
        BPCPNHIS.INFO.FMT_ID = "BPCHGLM";
        BPCPNHIS.INFO.JRNNO = SCCGWA.COMM_AREA.JRN_NO;
        CEP.TRC(SCCGWA, BPCPNHIS.INFO.TX_TYP_CD);
        BPCPNHIS.INFO.TX_RMK = K_HIS_REMARKS;
        BPCPNHIS.INFO.DATA_FLG = 'Y';
        BPCPNHIS.INFO.FMT_ID_LEN = 1174;
        BPCPNHIS.INFO.OLD_DAT_PT = BPCHGLMO;
        BPCPNHIS.INFO.NEW_DAT_PT = BPCHGLMN;
        S000_CALL_BPZPNHIS();
        if (pgmRtn) return;
    }
    public void S000_CALL_BPZPNHIS() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-REC-NHIS", BPCPNHIS);
        CEP.TRC(SCCGWA, BPCPNHIS.RC.RC_CODE);
        if (BPCPNHIS.RC.RC_CODE != 0) {
            WS_MSG_ERR = IBS.CLS2CPY(SCCGWA, BPCPNHIS.RC);
            S000_ERR_MSG_PROC();
            if (pgmRtn) return;
        }
    }
    public void S000_CALL_BPZPITM() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-P-CHK-ITM", BPCPITM);
        CEP.TRC(SCCGWA, BPCPITM.RC);
        if (BPCPITM.RC.RTNCODE != 0) {
            WS_MSG_ERR = IBS.CLS2CPY(SCCGWA, BPCPITM.RC);
            S000_ERR_MSG_PROC();
            if (pgmRtn) return;
        }
    }
    public void S000_CHK_CNTY() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCPQPDM);
        BPCPQPDM.PRDT_MODEL = WS_CNTY;
        BPCPQPDM.EFF_DT = SCCGWA.COMM_AREA.AC_DATE;
        WS_FND_FLG = 'Y';
        S000_CALL_BPZPQPDM();
        if (pgmRtn) return;
        if (WS_FND_FLG == 'N') {
            WS_MSG_ERR = BPCMSG_ERROR_MSG.BP_CNTR_TYPE_NOT_FOUND;
            S000_ERR_MSG_PROC();
            if (pgmRtn) return;
        }
    }
    public void S000_INPUT_DATA_PROCESS() throws IOException,SQLException,Exception {
        AIRGLM.KEY.GL_MSTNO = BPCUGLM.DATA.KEY.REDEFINES16.MSTNO;
        AIRGLM.COA_FLG = BPCUGLM.DATA.DATA_TXT.COA_FLG;
        AIRGLM.DESC = BPCUGLM.DATA.DATA_TXT.SNAME;
        AIRGLM.CDESC = BPCUGLM.DATA.DATA_TXT.LNAME;
        AIRGLM.KEY.EFF_DT = BPCUGLM.DATA.DATA_TXT.EFF_DATE;
        AIRGLM.KEY.EXP_DT = BPCUGLM.DATA.DATA_TXT.EXP_DATE;
        AIRGLM.OPT_FLG = BPCUGLM.DATA.DATA_TXT.OPT_FLG;
        AIRGLM.CNTY1 = BPCUGLM.DATA.DATA_TXT.CNTY1;
        AIRGLM.CNTY2 = BPCUGLM.DATA.DATA_TXT.CNTY2;
        AIRGLM.CNTY3 = BPCUGLM.DATA.DATA_TXT.CNTY3;
        AIRGLM.CKFLG = BPCUGLM.DATA.DATA_TXT.CKFLG;
        AIRGLM.REAL_GL = BPCUGLM.DATA.DATA_TXT.REAL_GL;
        AIRGLM.MEMO_GL = BPCUGLM.DATA.DATA_TXT.MEMO_GL;
        AIRGLM.UPD_TLR = BPCUGLM.DATA.DATA_TXT.UPD_TLR;
        AIRGLM.UPD_DATE = SCCGWA.COMM_AREA.TR_DATE;
        AIRGLM.UPD_TIME = SCCGWA.COMM_AREA.TR_TIME;
        AIRGLM.SUP_TEL1 = BPCUGLM.DATA.DATA_TXT.SUP_TEL1;
        AIRGLM.SUP_TEL2 = BPCUGLM.DATA.DATA_TXT.SUP_TEL2;
        AIRGLM.ITM_NO1 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[1-1].ITM_NO;
        AIRGLM.ITM_SEQ1 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[1-1].ITM_SEQ;
        AIRGLM.REMARK1 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[1-1].REMARK;
        AIRGLM.ITM_NO2 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[2-1].ITM_NO;
        AIRGLM.ITM_SEQ2 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[2-1].ITM_SEQ;
        AIRGLM.REMARK2 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[2-1].REMARK;
        AIRGLM.ITM_NO3 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[3-1].ITM_NO;
        AIRGLM.ITM_SEQ3 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[3-1].ITM_SEQ;
        AIRGLM.REMARK3 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[3-1].REMARK;
        AIRGLM.ITM_NO4 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[4-1].ITM_NO;
        AIRGLM.ITM_SEQ4 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[4-1].ITM_SEQ;
        AIRGLM.REMARK4 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[4-1].REMARK;
        AIRGLM.ITM_NO5 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[5-1].ITM_NO;
        AIRGLM.ITM_SEQ5 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[5-1].ITM_SEQ;
        AIRGLM.REMARK5 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[5-1].REMARK;
        AIRGLM.ITM_NO6 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[6-1].ITM_NO;
        AIRGLM.ITM_SEQ6 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[6-1].ITM_SEQ;
        AIRGLM.REMARK6 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[6-1].REMARK;
        AIRGLM.ITM_NO7 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[7-1].ITM_NO;
        AIRGLM.ITM_SEQ7 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[7-1].ITM_SEQ;
        AIRGLM.REMARK7 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[7-1].REMARK;
        AIRGLM.ITM_NO8 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[8-1].ITM_NO;
        AIRGLM.ITM_SEQ8 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[8-1].ITM_SEQ;
        AIRGLM.REMARK8 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[8-1].REMARK;
        AIRGLM.ITM_NO9 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[9-1].ITM_NO;
        AIRGLM.ITM_SEQ9 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[9-1].ITM_SEQ;
        AIRGLM.REMARK9 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[9-1].REMARK;
        AIRGLM.ITM_NO10 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[10-1].ITM_NO;
        AIRGLM.ITM_SEQ10 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[10-1].ITM_SEQ;
        AIRGLM.REMARK10 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[10-1].REMARK;
        AIRGLM.ITM_NO11 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[11-1].ITM_NO;
        AIRGLM.ITM_SEQ11 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[11-1].ITM_SEQ;
        AIRGLM.REMARK11 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[11-1].REMARK;
        AIRGLM.ITM_NO12 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[12-1].ITM_NO;
        AIRGLM.ITM_SEQ12 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[12-1].ITM_SEQ;
        AIRGLM.REMARK12 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[12-1].REMARK;
        AIRGLM.ITM_NO13 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[13-1].ITM_NO;
        AIRGLM.ITM_SEQ13 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[13-1].ITM_SEQ;
        AIRGLM.REMARK13 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[13-1].REMARK;
        AIRGLM.ITM_NO14 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[14-1].ITM_NO;
        AIRGLM.ITM_SEQ14 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[14-1].ITM_SEQ;
        AIRGLM.REMARK14 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[14-1].REMARK;
        AIRGLM.ITM_NO15 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[15-1].ITM_NO;
        AIRGLM.ITM_SEQ15 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[15-1].ITM_SEQ;
        AIRGLM.REMARK15 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[15-1].REMARK;
        AIRGLM.ITM_NO16 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[16-1].ITM_NO;
        AIRGLM.ITM_SEQ16 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[16-1].ITM_SEQ;
        AIRGLM.REMARK16 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[16-1].REMARK;
        AIRGLM.ITM_NO17 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[17-1].ITM_NO;
        AIRGLM.ITM_SEQ17 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[17-1].ITM_SEQ;
        AIRGLM.REMARK17 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[17-1].REMARK;
        AIRGLM.ITM_NO18 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[18-1].ITM_NO;
        AIRGLM.ITM_SEQ18 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[18-1].ITM_SEQ;
        AIRGLM.REMARK18 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[18-1].REMARK;
        AIRGLM.ITM_NO19 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[19-1].ITM_NO;
        AIRGLM.ITM_SEQ19 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[19-1].ITM_SEQ;
        AIRGLM.REMARK19 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[19-1].REMARK;
        AIRGLM.ITM_NO20 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[20-1].ITM_NO;
        AIRGLM.ITM_SEQ20 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[20-1].ITM_SEQ;
        AIRGLM.REMARK20 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[20-1].REMARK;
        AIRGLM.ITM_NO21 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[21-1].ITM_NO;
        AIRGLM.ITM_SEQ21 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[21-1].ITM_SEQ;
        AIRGLM.REMARK21 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[21-1].REMARK;
        AIRGLM.ITM_NO22 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[22-1].ITM_NO;
        AIRGLM.ITM_SEQ22 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[22-1].ITM_SEQ;
        AIRGLM.REMARK22 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[22-1].REMARK;
        AIRGLM.ITM_NO23 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[23-1].ITM_NO;
        AIRGLM.ITM_SEQ23 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[23-1].ITM_SEQ;
        AIRGLM.REMARK23 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[23-1].REMARK;
        AIRGLM.ITM_NO24 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[24-1].ITM_NO;
        AIRGLM.ITM_SEQ24 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[24-1].ITM_SEQ;
        AIRGLM.REMARK24 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[24-1].REMARK;
        AIRGLM.ITM_NO25 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[25-1].ITM_NO;
        AIRGLM.ITM_SEQ25 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[25-1].ITM_SEQ;
        AIRGLM.REMARK25 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[25-1].REMARK;
        AIRGLM.ITM_NO26 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[26-1].ITM_NO;
        AIRGLM.ITM_SEQ26 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[26-1].ITM_SEQ;
        AIRGLM.REMARK26 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[26-1].REMARK;
        AIRGLM.ITM_NO27 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[27-1].ITM_NO;
        AIRGLM.ITM_SEQ27 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[27-1].ITM_SEQ;
        AIRGLM.REMARK27 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[27-1].REMARK;
        AIRGLM.ITM_NO28 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[28-1].ITM_NO;
        AIRGLM.ITM_SEQ28 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[28-1].ITM_SEQ;
        AIRGLM.REMARK28 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[28-1].REMARK;
        AIRGLM.ITM_NO29 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[29-1].ITM_NO;
        AIRGLM.ITM_SEQ29 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[29-1].ITM_SEQ;
        AIRGLM.REMARK29 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[29-1].REMARK;
        AIRGLM.ITM_NO30 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[30-1].ITM_NO;
        AIRGLM.ITM_SEQ30 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[30-1].ITM_SEQ;
        AIRGLM.REMARK30 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[30-1].REMARK;
        AIRGLM.ITM_NO31 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[31-1].ITM_NO;
        AIRGLM.ITM_SEQ31 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[31-1].ITM_SEQ;
        AIRGLM.REMARK31 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[31-1].REMARK;
        AIRGLM.ITM_NO32 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[32-1].ITM_NO;
        AIRGLM.ITM_SEQ32 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[32-1].ITM_SEQ;
        AIRGLM.REMARK32 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[32-1].REMARK;
        AIRGLM.ITM_NO33 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[33-1].ITM_NO;
        AIRGLM.ITM_SEQ33 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[33-1].ITM_SEQ;
        AIRGLM.REMARK33 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[33-1].REMARK;
        AIRGLM.ITM_NO34 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[34-1].ITM_NO;
        AIRGLM.ITM_SEQ34 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[34-1].ITM_SEQ;
        AIRGLM.REMARK34 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[34-1].REMARK;
        AIRGLM.ITM_NO35 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[35-1].ITM_NO;
        AIRGLM.ITM_SEQ35 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[35-1].ITM_SEQ;
        AIRGLM.REMARK35 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[35-1].REMARK;
        AIRGLM.ITM_NO36 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[36-1].ITM_NO;
        AIRGLM.ITM_SEQ36 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[36-1].ITM_SEQ;
        AIRGLM.REMARK36 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[36-1].REMARK;
        AIRGLM.ITM_NO37 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[37-1].ITM_NO;
        AIRGLM.ITM_SEQ37 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[37-1].ITM_SEQ;
        AIRGLM.REMARK37 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[37-1].REMARK;
        AIRGLM.ITM_NO38 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[38-1].ITM_NO;
        AIRGLM.ITM_SEQ38 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[38-1].ITM_SEQ;
        AIRGLM.REMARK38 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[38-1].REMARK;
        AIRGLM.ITM_NO39 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[39-1].ITM_NO;
        AIRGLM.ITM_SEQ39 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[39-1].ITM_SEQ;
        AIRGLM.REMARK39 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[39-1].REMARK;
        AIRGLM.ITM_NO40 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[40-1].ITM_NO;
        AIRGLM.ITM_SEQ40 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[40-1].ITM_SEQ;
        AIRGLM.REMARK40 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[40-1].REMARK;
        AIRGLM.ITM_NO41 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[41-1].ITM_NO;
        AIRGLM.ITM_SEQ41 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[41-1].ITM_SEQ;
        AIRGLM.REMARK41 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[41-1].REMARK;
        AIRGLM.ITM_NO42 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[42-1].ITM_NO;
        AIRGLM.ITM_SEQ42 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[42-1].ITM_SEQ;
        AIRGLM.REMARK42 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[42-1].REMARK;
        AIRGLM.ITM_NO43 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[43-1].ITM_NO;
        AIRGLM.ITM_SEQ43 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[43-1].ITM_SEQ;
        AIRGLM.REMARK43 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[43-1].REMARK;
        AIRGLM.ITM_NO44 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[44-1].ITM_NO;
        AIRGLM.ITM_SEQ44 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[44-1].ITM_SEQ;
        AIRGLM.REMARK44 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[44-1].REMARK;
        AIRGLM.ITM_NO45 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[45-1].ITM_NO;
        AIRGLM.ITM_SEQ45 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[45-1].ITM_SEQ;
        AIRGLM.REMARK45 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[45-1].REMARK;
        AIRGLM.ITM_NO46 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[46-1].ITM_NO;
        AIRGLM.ITM_SEQ46 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[46-1].ITM_SEQ;
        AIRGLM.REMARK46 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[46-1].REMARK;
        AIRGLM.ITM_NO47 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[47-1].ITM_NO;
        AIRGLM.ITM_SEQ47 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[47-1].ITM_SEQ;
        AIRGLM.REMARK47 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[47-1].REMARK;
        AIRGLM.ITM_NO48 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[48-1].ITM_NO;
        AIRGLM.ITM_SEQ48 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[48-1].ITM_SEQ;
        AIRGLM.REMARK48 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[48-1].REMARK;
        AIRGLM.ITM_NO49 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[49-1].ITM_NO;
        AIRGLM.ITM_SEQ49 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[49-1].ITM_SEQ;
        AIRGLM.REMARK49 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[49-1].REMARK;
        AIRGLM.ITM_NO50 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[50-1].ITM_NO;
        AIRGLM.ITM_SEQ50 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[50-1].ITM_SEQ;
        AIRGLM.REMARK50 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[50-1].REMARK;
        AIRGLM.ITM_NO51 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[51-1].ITM_NO;
        AIRGLM.ITM_SEQ51 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[51-1].ITM_SEQ;
        AIRGLM.REMARK51 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[51-1].REMARK;
        AIRGLM.ITM_NO52 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[52-1].ITM_NO;
        AIRGLM.ITM_SEQ52 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[52-1].ITM_SEQ;
        AIRGLM.REMARK52 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[52-1].REMARK;
        AIRGLM.ITM_NO53 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[53-1].ITM_NO;
        AIRGLM.ITM_SEQ53 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[53-1].ITM_SEQ;
        AIRGLM.REMARK53 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[53-1].REMARK;
        AIRGLM.ITM_NO54 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[54-1].ITM_NO;
        AIRGLM.ITM_SEQ54 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[54-1].ITM_SEQ;
        AIRGLM.REMARK54 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[54-1].REMARK;
        AIRGLM.ITM_NO55 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[55-1].ITM_NO;
        AIRGLM.ITM_SEQ55 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[55-1].ITM_SEQ;
        AIRGLM.REMARK55 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[55-1].REMARK;
        AIRGLM.ITM_NO56 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[56-1].ITM_NO;
        AIRGLM.ITM_SEQ56 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[56-1].ITM_SEQ;
        AIRGLM.REMARK56 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[56-1].REMARK;
        AIRGLM.ITM_NO57 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[57-1].ITM_NO;
        AIRGLM.ITM_SEQ57 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[57-1].ITM_SEQ;
        AIRGLM.REMARK57 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[57-1].REMARK;
        AIRGLM.ITM_NO58 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[58-1].ITM_NO;
        AIRGLM.ITM_SEQ58 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[58-1].ITM_SEQ;
        AIRGLM.REMARK58 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[58-1].REMARK;
        AIRGLM.ITM_NO59 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[59-1].ITM_NO;
        AIRGLM.ITM_SEQ59 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[59-1].ITM_SEQ;
        AIRGLM.REMARK59 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[59-1].REMARK;
        AIRGLM.ITM_NO60 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[60-1].ITM_NO;
        AIRGLM.ITM_SEQ60 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[60-1].ITM_SEQ;
        AIRGLM.REMARK60 = BPCUGLM.DATA.DATA_TXT.REL_ITMS[60-1].REMARK;
        CEP.TRC(SCCGWA, BPCUGLM.DATA.KEY.REDEFINES16.MSTNO);
        CEP.TRC(SCCGWA, BPCUGLM.DATA.DATA_TXT.EFF_DATE);
        CEP.TRC(SCCGWA, BPCUGLM.DATA.DATA_TXT.EXP_DATE);
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.AC_DATE);
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.TR_DATE);
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.TR_TIME);
        CEP.TRC(SCCGWA, AIRGLM.COA_FLG);
        CEP.TRC(SCCGWA, AIRGLM.KEY.EFF_DT);
        CEP.TRC(SCCGWA, AIRGLM.KEY.EXP_DT);
        CEP.TRC(SCCGWA, AIRGLM.OPT_FLG);
        CEP.TRC(SCCGWA, AIRGLM.CNTY1);
        CEP.TRC(SCCGWA, AIRGLM.CNTY2);
        CEP.TRC(SCCGWA, AIRGLM.CNTY3);
        CEP.TRC(SCCGWA, AIRGLM.CKFLG);
        CEP.TRC(SCCGWA, AIRGLM.REAL_GL);
        CEP.TRC(SCCGWA, AIRGLM.MEMO_GL);
        CEP.TRC(SCCGWA, AIRGLM.UPD_TLR);
        CEP.TRC(SCCGWA, AIRGLM.UPD_DATE);
        CEP.TRC(SCCGWA, AIRGLM.UPD_TIME);
        CEP.TRC(SCCGWA, AIRGLM.SUP_TEL1);
        CEP.TRC(SCCGWA, AIRGLM.SUP_TEL2);
    }
    public void S000_CALL_BPZPQPDM() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-P-INQ-PRD-MODEL", BPCPQPDM);
        CEP.TRC(SCCGWA, BPCPQPDM.RC);
        if (BPCPQPDM.RC.RC_CODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, BPCPQPDM.RC);
            if (JIBS_tmp_str[0].equalsIgnoreCase(BPCMSG_ERROR_MSG.BP_PARM_NOTFND)) {
                WS_FND_FLG = 'N';
            } else {
                WS_MSG_ERR = IBS.CLS2CPY(SCCGWA, BPCPQPDM.RC);
                S000_ERR_MSG_PROC();
                if (pgmRtn) return;
            }
        }
    }
    public void S000_CALL_AIZPQITM() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "AI-P-INQ-ITM", AICPQITM);
        if (AICPQITM.RC.RTNCODE != 0) {
            WS_MSG_ERR = IBS.CLS2CPY(SCCGWA, AICPQITM.RC);
            S000_ERR_MSG_PROC();
            if (pgmRtn) return;
        }
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_MSG_ERR, WS_INFO);
    }
    public void B_MPAG() throws IOException,SQLException,Exception {
    if (!SCCGWA.COMM_AREA.BSP_FLG.equalsIgnoreCase("BSP") && !SCCGWA.COMM_AREA.CHNL.equalsIgnoreCase("BAT")) { //FROM #IFDEF ONL
        JIBS_tmp_str[9] = "SCZMPAG";
        Class<?>clazz = Class.forName(JIBS_tmp_str[9].trim());
        Object obj = clazz.newInstance();
        Method m = clazz.getDeclaredMethod("MP",new Class[]{SCCGWA.getClass(), SCCMPAG.getClass()});
        m.invoke(obj, SCCGWA, SCCMPAG);
        if (SCCGWA.COMM_AREA.EXCP_FLG == 'Y') {
            Z_RET();
            if (pgmRtn) return;
        }
    } else { //FROM #ELSE
    } //FROM #ENDIF
    }
    public void R000_SET_LK_MMT() throws IOException,SQLException,Exception {
        SCCCWA = (SCCCWA) SCCGWA.COMM_AREA.CWA_PTR;
        if (BPCPRMBR.TYP.equalsIgnoreCase("CITDTL")
            || BPCPRMBR.TYP.equalsIgnoreCase("CITDINF")
            || BPCPRMBR.TYP.equalsIgnoreCase("AITENTY")
            || BPCPRMBR.TYP.equalsIgnoreCase("AITGLM")) {
            BPCPRMBR.I = 12;
        } else {
            BPCPRMBR.I = 12;
        }
        if (SCCCWA.PARM_IN_USE[BPCPRMBR.I-1] == 1) {
            BPCPRMBR.DAT_PTR = SCCCWA.PARM_PTR1_AREA[BPCPRMBR.I-1].PARM_PTR1;
        } else {
            BPCPRMBR.DAT_PTR = SCCCWA.PARM_PTR2_AREA[BPCPRMBR.I-1].PARM_PTR2;
        }
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, BPCUGLM);
    if (SCCGWA.COMM_AREA.BSP_FLG.equalsIgnoreCase("BSP") || SCCGWA.COMM_AREA.CHNL.equalsIgnoreCase("BAT")) { //FROM #IFDEF BAT
        if (BPCUGLM.RC.RC_CODE != 0) {
            CEP.TRC(SCCGWA, "BPCUGLM = ");
            CEP.TRC(SCCGWA, BPCUGLM);
        }
    } //FROM #ENDIF
        pgmRtn = true;
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
