package com.hisun.SM;

public class SMB1790_AWA_1790 {
    public char FUNC = ' ';
    public short FUNC_NO = 0;
    public String PTYP = " ";
    public short PTYP_NO = 0;
    public String CODE = " ";
    public short CODE_NO = 0;
    public int EFFDATE = 0;
    public short EFFDATE_NO = 0;
    public int EXPDATE = 0;
    public short EXPDATE_NO = 0;
    public String DESC = " ";
    public short DESC_NO = 0;
    public String CDESC = " ";
    public short CDESC_NO = 0;
    public short LEN = 0;
    public short LEN_NO = 0;
    public String TR_MMO = " ";
    public short TR_MMO_NO = 0;
    public char STUS = ' ';
    public short STUS_NO = 0;
    public char SYS_LVL = ' ';
    public short SYS_LVL_NO = 0;
    public char RUN_MODE = ' ';
    public short RUN_MODE_NO = 0;
    public char LOG_IND = ' ';
    public short LOG_IND_NO = 0;
    public char REEN_IND = ' ';
    public short REEN_IND_NO = 0;
    public short CLS = 0;
    public short CLS_NO = 0;
    public char SELF_GRN = ' ';
    public short SELF_GRN_NO = 0;
    public String AUTH_LVL = " ";
    public short AUTH_LVL_NO = 0;
    public char APVL_IND = ' ';
    public short APVL_IND_NO = 0;
    public char ODM_PRN = ' ';
    public short ODM_PRN_NO = 0;
    public char HIS_REC = ' ';
    public short HIS_REC_NO = 0;
    public String ATTR_WOR = " ";
    public short ATTR_WOR_NO = 0;
    public char TRAN_IND = ' ';
    public short TRAN_IND_NO = 0;
    public char REVT_IND = ' ';
    public short REVT_IND_NO = 0;
    public String SUBS_TX = " ";
    public short SUBS_TX_NO = 0;
    public char AWA_IND = ' ';
    public short AWA_IND_NO = 0;
    public String INP_FMT = " ";
    public short INP_FMT_NO = 0;
    public String OUTP_FMT = " ";
    public short OUTP_FMT_NO = 0;
    public String OUTP_CNT = " ";
    public short OUTP_CNT_NO = 0;
    public String SPEC_CNT = " ";
    public short SPEC_CNT_NO = 0;
    public int PGM_CNT = 0;
    public short PGM_CNT_NO = 0;
    public SMB1790_PGM[] PGM = new SMB1790_PGM[5];
    public String WAITBSP1 = " ";
    public short WAITBSP1_NO = 0;
    public String WAITBSP2 = " ";
    public short WAITBSP2_NO = 0;
    public String WAITBSP3 = " ";
    public short WAITBSP3_NO = 0;
    public SMB1790_AWA_1790() {
        for (int i=0;i<5;i++) PGM[i] = new SMB1790_PGM();
    }
}
