package com.hisun.SM;

import com.hisun.BP.*;
import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;

import java.io.IOException;
import java.sql.SQLException;

public class SMOT1700 {
    String JIBS_tmp_str[] = new String[10];
    boolean pgmRtn = false;
    char K_ERROR = 'E';
    SMOT1700_WS_TEMP_VARIABLE WS_TEMP_VARIABLE = new SMOT1700_WS_TEMP_VARIABLE();
    String WS_TSQ_REC = " ";
    BPCXP19 BPCXP19 = new BPCXP19();
    BPCMSG_ERROR_MSG BPCMSG_ERROR_MSG = new BPCMSG_ERROR_MSG();
    SMCMSG_ERROR_MSG SMCMSG_ERROR_MSG = new SMCMSG_ERROR_MSG();
    SCCWOUT SCCWOUT = new SCCWOUT();
    BPCPRMM BPCPRMM = new BPCPRMM();
    BPRPRMT BPRPRMT = new BPRPRMT();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    SCCMPAG SCCMPAG = new SCCMPAG();
    SCCFMT SCCFMT = new SCCFMT();
    BPRBTR BPRBTR = new BPRBTR();
    SCCGWA SCCGWA;
    SMB1700_AWA_1700 SMB1700_AWA_1700;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROCESS();
        if (pgmRtn) return;
        B000_MAIN_PROCESS();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, "SMOT1700 return!");
        Z_RET();
        if (pgmRtn) return;
    }
    public void A000_INIT_PROCESS() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "SMB1700_AWA_1700>");
        SMB1700_AWA_1700 = (SMB1700_AWA_1700) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        IBS.init(SCCGWA, WS_TEMP_VARIABLE);
        IBS.init(SCCGWA, BPCPRMM);
        IBS.init(SCCGWA, BPRPRMT);
        BPCPRMM.RC.RC_APP = "SM";
        BPCPRMM.DAT_PTR = BPRPRMT;
    }
    public void B000_MAIN_PROCESS() throws IOException,SQLException,Exception {
        B100_CHECK_INPUT();
        if (pgmRtn) return;
        if (SMB1700_AWA_1700.FUNC == 'I') {
            B100_READ_PROCESS();
            if (pgmRtn) return;
        } else if (SMB1700_AWA_1700.FUNC == 'A') {
            B100_WRITE_PROCESS();
            if (pgmRtn) return;
        } else if (SMB1700_AWA_1700.FUNC == 'M') {
            B100_READU_PROCESS();
            if (pgmRtn) return;
            B100_REWRITE_PROCESS();
            if (pgmRtn) return;
        } else if (SMB1700_AWA_1700.FUNC == 'D') {
            B100_READ_PROCESS();
            if (pgmRtn) return;
            B100_DELETE_PROCESS();
            if (pgmRtn) return;
        } else {
            Z_RET();
            if (pgmRtn) return;
        }
        B200_OUTPUT_PROCESS();
        if (pgmRtn) return;
    }
    public void B100_CHECK_INPUT() throws IOException,SQLException,Exception {
        for (WS_TEMP_VARIABLE.WS_COUNT = 1; WS_TEMP_VARIABLE.WS_COUNT <= 15; WS_TEMP_VARIABLE.WS_COUNT += 1) {
            if ((SMB1700_AWA_1700.FILE_TAB[WS_TEMP_VARIABLE.WS_COUNT-1].SYSMODE != 'D' 
                && SMB1700_AWA_1700.FILE_TAB[WS_TEMP_VARIABLE.WS_COUNT-1].SYSMODE != 'B' 
                && SMB1700_AWA_1700.FILE_TAB[WS_TEMP_VARIABLE.WS_COUNT-1].SYSMODE != 'R' 
                && SMB1700_AWA_1700.FILE_TAB[WS_TEMP_VARIABLE.WS_COUNT-1].SYSMODE != 'N' 
                && SMB1700_AWA_1700.FILE_TAB[WS_TEMP_VARIABLE.WS_COUNT-1].SYSMODE != ' ')) {
                IBS.CPY2CLS(SCCGWA, SMCMSG_ERROR_MSG.SM_INPUT_ERROR, WS_TEMP_VARIABLE.WS_MSGID);
                WS_TEMP_VARIABLE.WS_FLD_NO = SMB1700_AWA_1700.FILE_TAB[WS_TEMP_VARIABLE.WS_COUNT-1].SYSMODE_NO;
                S000_ERR_MSG_PROC_CONTINUE();
                if (pgmRtn) return;
            }
            if ((SMB1700_AWA_1700.FILE_TAB[WS_TEMP_VARIABLE.WS_COUNT-1].STATUS != 'Y' 
                && SMB1700_AWA_1700.FILE_TAB[WS_TEMP_VARIABLE.WS_COUNT-1].STATUS != 'N' 
                && SMB1700_AWA_1700.FILE_TAB[WS_TEMP_VARIABLE.WS_COUNT-1].STATUS != 'E' 
                && SMB1700_AWA_1700.FILE_TAB[WS_TEMP_VARIABLE.WS_COUNT-1].STATUS != 'M' 
                && SMB1700_AWA_1700.FILE_TAB[WS_TEMP_VARIABLE.WS_COUNT-1].STATUS != 'D' 
                && SMB1700_AWA_1700.FILE_TAB[WS_TEMP_VARIABLE.WS_COUNT-1].STATUS != 'W' 
                && SMB1700_AWA_1700.FILE_TAB[WS_TEMP_VARIABLE.WS_COUNT-1].STATUS != 'O' 
                && SMB1700_AWA_1700.FILE_TAB[WS_TEMP_VARIABLE.WS_COUNT-1].STATUS != ' ')) {
                IBS.CPY2CLS(SCCGWA, SMCMSG_ERROR_MSG.SM_INPUT_ERROR, WS_TEMP_VARIABLE.WS_MSGID);
                WS_TEMP_VARIABLE.WS_FLD_NO = SMB1700_AWA_1700.FILE_TAB[WS_TEMP_VARIABLE.WS_COUNT-1].STATUS_NO;
                S000_ERR_MSG_PROC_CONTINUE();
                if (pgmRtn) return;
            }
        }
        R00_CHECK_ERROR();
        if (pgmRtn) return;
    }
    public void R00_CHECK_ERROR() throws IOException,SQLException,Exception {
        if (SCCGWA.COMM_AREA.MSG_PROC_AREA.MSG_TYPE == K_ERROR 
            && SCCGWA.COMM_AREA.MSG_PROC_AREA.MSG_ID.MSG_CODE == 0) {
            IBS.CPY2CLS(SCCGWA, BPCMSG_ERROR_MSG.BP_INPUT_ERROR, WS_TEMP_VARIABLE.WS_MSGID);
            WS_TEMP_VARIABLE.WS_FLD_NO = 0;
            S000_ERR_MSG_PROC();
            if (pgmRtn) return;
        }
    }
    public void B100_READ_PROCESS() throws IOException,SQLException,Exception {
        BPCPRMM.FUNC = '3';
        BPRPRMT.KEY.TYP = SMB1700_AWA_1700.PTYP;
        BPRPRMT.KEY.CD = SMB1700_AWA_1700.CODE;
        BPCPRMM.EFF_DT = SMB1700_AWA_1700.EFFDATE;
        S000_CALL_BPZPRMM();
        if (pgmRtn) return;
    }
    public void B100_READU_PROCESS() throws IOException,SQLException,Exception {
        BPCPRMM.FUNC = '4';
        BPRPRMT.KEY.TYP = SMB1700_AWA_1700.PTYP;
        BPRPRMT.KEY.CD = SMB1700_AWA_1700.CODE;
        BPCPRMM.EFF_DT = SMB1700_AWA_1700.EFFDATE;
        S000_CALL_BPZPRMM();
        if (pgmRtn) return;
    }
    public void B100_REWRITE_PROCESS() throws IOException,SQLException,Exception {
        BPCPRMM.FUNC = '2';
        BPRPRMT.KEY.TYP = SMB1700_AWA_1700.PTYP;
        BPRPRMT.KEY.CD = SMB1700_AWA_1700.CODE;
        BPCPRMM.EFF_DT = SMB1700_AWA_1700.EFFDATE;
        BPCPRMM.EXP_DT = SMB1700_AWA_1700.EXPDATE;
        BPRPRMT.DESC = SMB1700_AWA_1700.DESC;
        BPRPRMT.CDESC = SMB1700_AWA_1700.CDESC;
        IBS.init(SCCGWA, BPRBTR.DATA_TXT);
        for (WS_TEMP_VARIABLE.WS_COUNT = 1; WS_TEMP_VARIABLE.WS_COUNT <= 15; WS_TEMP_VARIABLE.WS_COUNT += 1) {
            BPRBTR.DATA_TXT.FILE_TBL[WS_TEMP_VARIABLE.WS_COUNT-1].AP_MMO = SMB1700_AWA_1700.FILE_TAB[WS_TEMP_VARIABLE.WS_COUNT-1].APMMO;
            BPRBTR.DATA_TXT.FILE_TBL[WS_TEMP_VARIABLE.WS_COUNT-1].FILE_NO = SMB1700_AWA_1700.FILE_TAB[WS_TEMP_VARIABLE.WS_COUNT-1].FILENO;
            BPRBTR.DATA_TXT.FILE_TBL[WS_TEMP_VARIABLE.WS_COUNT-1].SYS_MODE = SMB1700_AWA_1700.FILE_TAB[WS_TEMP_VARIABLE.WS_COUNT-1].SYSMODE;
            BPRBTR.DATA_TXT.FILE_TBL[WS_TEMP_VARIABLE.WS_COUNT-1].STATUS = SMB1700_AWA_1700.FILE_TAB[WS_TEMP_VARIABLE.WS_COUNT-1].STATUS;
            BPRBTR.DATA_TXT.FILE_TBL[WS_TEMP_VARIABLE.WS_COUNT-1].WAIT_BTR_NO = SMB1700_AWA_1700.FILE_TAB[WS_TEMP_VARIABLE.WS_COUNT-1].WAITBTR;
            BPRBTR.DATA_TXT.FILE_TBL[WS_TEMP_VARIABLE.WS_COUNT-1].OK_DATE = SMB1700_AWA_1700.FILE_TAB[WS_TEMP_VARIABLE.WS_COUNT-1].OKDATE;
        }
        JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, BPRBTR.DATA_TXT);
        IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], BPRPRMT.DAT_TXT);
        S000_CALL_BPZPRMM();
        if (pgmRtn) return;
    }
    public void B100_DELETE_PROCESS() throws IOException,SQLException,Exception {
        BPCPRMM.FUNC = '1';
        BPRPRMT.KEY.TYP = SMB1700_AWA_1700.PTYP;
        BPRPRMT.KEY.CD = SMB1700_AWA_1700.CODE;
        BPCPRMM.EFF_DT = SMB1700_AWA_1700.EFFDATE;
        S000_CALL_BPZPRMM();
        if (pgmRtn) return;
    }
    public void B100_WRITE_PROCESS() throws IOException,SQLException,Exception {
        BPCPRMM.FUNC = '0';
        BPRPRMT.KEY.TYP = SMB1700_AWA_1700.PTYP;
        BPRPRMT.KEY.CD = SMB1700_AWA_1700.CODE;
        BPCPRMM.EFF_DT = SMB1700_AWA_1700.EFFDATE;
        BPCPRMM.EXP_DT = SMB1700_AWA_1700.EXPDATE;
        BPRPRMT.DESC = SMB1700_AWA_1700.DESC;
        BPRPRMT.CDESC = SMB1700_AWA_1700.CDESC;
        IBS.init(SCCGWA, BPRBTR.DATA_TXT);
        for (WS_TEMP_VARIABLE.WS_COUNT = 1; WS_TEMP_VARIABLE.WS_COUNT <= 15; WS_TEMP_VARIABLE.WS_COUNT += 1) {
            BPRBTR.DATA_TXT.FILE_TBL[WS_TEMP_VARIABLE.WS_COUNT-1].AP_MMO = SMB1700_AWA_1700.FILE_TAB[WS_TEMP_VARIABLE.WS_COUNT-1].APMMO;
            BPRBTR.DATA_TXT.FILE_TBL[WS_TEMP_VARIABLE.WS_COUNT-1].FILE_NO = SMB1700_AWA_1700.FILE_TAB[WS_TEMP_VARIABLE.WS_COUNT-1].FILENO;
            BPRBTR.DATA_TXT.FILE_TBL[WS_TEMP_VARIABLE.WS_COUNT-1].SYS_MODE = SMB1700_AWA_1700.FILE_TAB[WS_TEMP_VARIABLE.WS_COUNT-1].SYSMODE;
            BPRBTR.DATA_TXT.FILE_TBL[WS_TEMP_VARIABLE.WS_COUNT-1].STATUS = SMB1700_AWA_1700.FILE_TAB[WS_TEMP_VARIABLE.WS_COUNT-1].STATUS;
            BPRBTR.DATA_TXT.FILE_TBL[WS_TEMP_VARIABLE.WS_COUNT-1].WAIT_BTR_NO = SMB1700_AWA_1700.FILE_TAB[WS_TEMP_VARIABLE.WS_COUNT-1].WAITBTR;
            BPRBTR.DATA_TXT.FILE_TBL[WS_TEMP_VARIABLE.WS_COUNT-1].OK_DATE = SMB1700_AWA_1700.FILE_TAB[WS_TEMP_VARIABLE.WS_COUNT-1].OKDATE;
        }
        JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, BPRBTR.DATA_TXT);
        IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], BPRPRMT.DAT_TXT);
        S000_CALL_BPZPRMM();
        if (pgmRtn) return;
    }
    public void B200_OUTPUT_PROCESS() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCXP19);
        IBS.init(SCCGWA, SCCFMT);
        BPCXP19.FUNC = SMB1700_AWA_1700.FUNC;
        BPCXP19.TYPE = BPRPRMT.KEY.TYP;
        BPCXP19.CODE = BPRPRMT.KEY.CD;
        BPCXP19.EFF_DATE = BPCPRMM.EFF_DT;
        BPCXP19.EXP_DATE = BPCPRMM.EXP_DT;
        BPCXP19.DESC = BPRPRMT.DESC;
        BPCXP19.CDESC = BPRPRMT.CDESC;
        BPCXP19.FLAG = 0X02;
        JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, BPRPRMT.DAT_TXT);
        IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], BPRBTR.DATA_TXT);
        for (WS_TEMP_VARIABLE.WS_COUNT = 1; WS_TEMP_VARIABLE.WS_COUNT <= 15; WS_TEMP_VARIABLE.WS_COUNT += 1) {
            BPCXP19.FILE_TBL[WS_TEMP_VARIABLE.WS_COUNT-1].AP_MMO = BPRBTR.DATA_TXT.FILE_TBL[WS_TEMP_VARIABLE.WS_COUNT-1].AP_MMO;
            BPCXP19.FILE_TBL[WS_TEMP_VARIABLE.WS_COUNT-1].FILE_NO = BPRBTR.DATA_TXT.FILE_TBL[WS_TEMP_VARIABLE.WS_COUNT-1].FILE_NO;
            BPCXP19.FILE_TBL[WS_TEMP_VARIABLE.WS_COUNT-1].SYS_MODE = BPRBTR.DATA_TXT.FILE_TBL[WS_TEMP_VARIABLE.WS_COUNT-1].SYS_MODE;
            BPCXP19.FILE_TBL[WS_TEMP_VARIABLE.WS_COUNT-1].STATUS = BPRBTR.DATA_TXT.FILE_TBL[WS_TEMP_VARIABLE.WS_COUNT-1].STATUS;
            BPCXP19.FILE_TBL[WS_TEMP_VARIABLE.WS_COUNT-1].WAIT_BTR_NO = BPRBTR.DATA_TXT.FILE_TBL[WS_TEMP_VARIABLE.WS_COUNT-1].WAIT_BTR_NO;
            BPCXP19.FILE_TBL[WS_TEMP_VARIABLE.WS_COUNT-1].OK_DATE = BPRBTR.DATA_TXT.FILE_TBL[WS_TEMP_VARIABLE.WS_COUNT-1].OK_DATE;
        }
        SCCFMT.FMTID = "BPP19";
        SCCFMT.DATA_PTR = BPCXP19;
        SCCFMT.DATA_LEN = 387;
        IBS.FMT(SCCGWA, SCCFMT);
    }
    public void S000_CALL_BPZPRMM() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-PARM-MAINTAIN", BPCPRMM);
        if (BPCPRMM.RC.RC_RTNCODE != 0) {
            WS_TEMP_VARIABLE.WS_MSGID.WS_MSG_AP = BPCPRMM.RC.RC_APP;
            WS_TEMP_VARIABLE.WS_MSGID.WS_MSG_CODE = BPCPRMM.RC.RC_RTNCODE;
            S000_ERR_MSG_PROC();
            if (pgmRtn) return;
        }
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, WS_TEMP_VARIABLE.WS_MSGID);
        CEP.ERR(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_FLD_NO);
    }
    public void S000_ERR_MSG_PROC_CONTINUE() throws IOException,SQLException,Exception {
        JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, WS_TEMP_VARIABLE.WS_MSGID);
        CEP.ERRC(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_FLD_NO);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        pgmRtn = true;
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
