package com.hisun.SM;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;

import java.io.IOException;
import java.sql.SQLException;

public class SMOT1455 {
    String JIBS_tmp_str[] = new String[10];
    SMOT1455_WS_TEMP_VARIABLE WS_TEMP_VARIABLE = new SMOT1455_WS_TEMP_VARIABLE();
    SMCMSG_ERROR_MSG SMCMSG_ERROR_MSG = new SMCMSG_ERROR_MSG();
    SCCMSG SCCMSG = new SCCMSG();
    SCCCALL SCCCALL = new SCCCALL();
    SMCSAWFW SMCSAWFW = new SMCSAWFW();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCGWA SCCGWA;
    SMB1450_AWA_1450 SMB1450_AWA_1450;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "SMOT1455 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "SMB1450_AWA_1450>");
        SMB1450_AWA_1450 = (SMB1450_AWA_1450) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        IBS.init(SCCGWA, WS_TEMP_VARIABLE);
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B001_CHECK_INPUT();
        B005_ADD_RECORD();
    }
    public void B001_CHECK_INPUT() throws IOException,SQLException,Exception {
        for (WS_TEMP_VARIABLE.WS_POS = 1; WS_TEMP_VARIABLE.WS_POS <= 9; WS_TEMP_VARIABLE.WS_POS += 1) {
            if (SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE == ' ' 
                && (SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].TQ_FLG != ' ' 
                || SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].TQ_STS.trim().length() > 0 
                || SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].CMP_NAME.trim().length() > 0 
                || SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].TRCODE.trim().length() > 0 
                || SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].MSG_FLG != ' ' 
                || SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].BK_FLG != ' ')) {
                CEP.TRC(SCCGWA, WS_TEMP_VARIABLE.WS_MSGID);
                IBS.CPY2CLS(SCCGWA, SMCMSG_ERROR_MSG.SM_FIELD_MUSTINPUT, WS_TEMP_VARIABLE.WS_MSGID);
                if (SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE == ' ') WS_TEMP_VARIABLE.WS_FLD_NO = 0;
                else WS_TEMP_VARIABLE.WS_FLD_NO = Short.parseShort(""+SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE);
                S000_ERR_MSG_PROC();
            }
        }
        for (WS_TEMP_VARIABLE.WS_POS = 1; WS_TEMP_VARIABLE.WS_POS <= 9; WS_TEMP_VARIABLE.WS_POS += 1) {
            if (SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE != ' ' 
                && SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].TQ_FLG == ' ') {
                IBS.CPY2CLS(SCCGWA, SMCMSG_ERROR_MSG.SM_FIELD_MUSTINPUT, WS_TEMP_VARIABLE.WS_MSGID);
                if (SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].TQ_FLG == ' ') WS_TEMP_VARIABLE.WS_FLD_NO = 0;
                else WS_TEMP_VARIABLE.WS_FLD_NO = Short.parseShort(""+SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].TQ_FLG);
                S000_ERR_MSG_PROC();
            }
        }
        for (WS_TEMP_VARIABLE.WS_POS = 1; WS_TEMP_VARIABLE.WS_POS <= 9; WS_TEMP_VARIABLE.WS_POS += 1) {
            if (SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE != ' ' 
                && SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].BK_FLG == ' ') {
                IBS.CPY2CLS(SCCGWA, SMCMSG_ERROR_MSG.SM_FIELD_MUSTINPUT, WS_TEMP_VARIABLE.WS_MSGID);
                if (SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].BK_FLG == ' ') WS_TEMP_VARIABLE.WS_FLD_NO = 0;
                else WS_TEMP_VARIABLE.WS_FLD_NO = Short.parseShort(""+SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].BK_FLG);
                S000_ERR_MSG_PROC();
            }
        }
        for (WS_TEMP_VARIABLE.WS_POS = 1; WS_TEMP_VARIABLE.WS_POS <= 9; WS_TEMP_VARIABLE.WS_POS += 1) {
            if (SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].TQ_FLG == 'Y' 
                && SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].TQ_STS.trim().length() == 0) {
                IBS.CPY2CLS(SCCGWA, SMCMSG_ERROR_MSG.SM_FIELD_MUSTINPUT, WS_TEMP_VARIABLE.WS_MSGID);
                WS_TEMP_VARIABLE.WS_FLD_NO = SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].TQ_STS_NO;
                S000_ERR_MSG_PROC();
            }
        }
        for (WS_TEMP_VARIABLE.WS_POS = 1; WS_TEMP_VARIABLE.WS_POS <= 9; WS_TEMP_VARIABLE.WS_POS += 1) {
            if (SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].TQ_FLG == 'N' 
                && SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].CMP_NAME.trim().length() == 0) {
                IBS.CPY2CLS(SCCGWA, SMCMSG_ERROR_MSG.SM_FIELD_MUSTINPUT, WS_TEMP_VARIABLE.WS_MSGID);
                WS_TEMP_VARIABLE.WS_FLD_NO = SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].CMP_NAME_NO;
                S000_ERR_MSG_PROC();
            }
        }
        for (WS_TEMP_VARIABLE.WS_POS = 2; WS_TEMP_VARIABLE.WS_POS <= 9; WS_TEMP_VARIABLE.WS_POS += 1) {
            WS_TEMP_VARIABLE.WS_CNT = (short) (WS_TEMP_VARIABLE.WS_POS - 1);
            if (SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE != ' ' 
                && SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_CNT-1].KEY_TYPE == ' ') {
                IBS.CPY2CLS(SCCGWA, SMCMSG_ERROR_MSG.SM_SHOULD_INPUT_FIRST, WS_TEMP_VARIABLE.WS_MSGID);
                WS_TEMP_VARIABLE.WS_FLD_NO = SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_CNT-1].KEY_TYPE_NO;
                S000_ERR_MSG_PROC();
            }
        }
        for (WS_TEMP_VARIABLE.WS_POS = 2; WS_TEMP_VARIABLE.WS_POS <= 9; WS_TEMP_VARIABLE.WS_POS += 1) {
            if (SMB1450_AWA_1450.DATA[1-1].KEY_TYPE == SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE 
                && SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE != ' ') {
                IBS.CPY2CLS(SCCGWA, SMCMSG_ERROR_MSG.SM_KEY_TYPE_ERROR, WS_TEMP_VARIABLE.WS_MSGID);
                WS_TEMP_VARIABLE.WS_FLD_NO = SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE_NO;
                S000_ERR_MSG_PROC();
            }
        }
        for (WS_TEMP_VARIABLE.WS_POS = 3; WS_TEMP_VARIABLE.WS_POS <= 9; WS_TEMP_VARIABLE.WS_POS += 1) {
            if (SMB1450_AWA_1450.DATA[2-1].KEY_TYPE == SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE 
                && SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE != ' ') {
                IBS.CPY2CLS(SCCGWA, SMCMSG_ERROR_MSG.SM_KEY_TYPE_ERROR, WS_TEMP_VARIABLE.WS_MSGID);
                WS_TEMP_VARIABLE.WS_FLD_NO = SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE_NO;
                S000_ERR_MSG_PROC();
            }
        }
        for (WS_TEMP_VARIABLE.WS_POS = 4; WS_TEMP_VARIABLE.WS_POS <= 9; WS_TEMP_VARIABLE.WS_POS += 1) {
            if (SMB1450_AWA_1450.DATA[3-1].KEY_TYPE == SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE 
                && SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE != ' ') {
                IBS.CPY2CLS(SCCGWA, SMCMSG_ERROR_MSG.SM_KEY_TYPE_ERROR, WS_TEMP_VARIABLE.WS_MSGID);
                WS_TEMP_VARIABLE.WS_FLD_NO = SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE_NO;
                S000_ERR_MSG_PROC();
            }
        }
        for (WS_TEMP_VARIABLE.WS_POS = 5; WS_TEMP_VARIABLE.WS_POS <= 9; WS_TEMP_VARIABLE.WS_POS += 1) {
            if (SMB1450_AWA_1450.DATA[4-1].KEY_TYPE == SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE 
                && SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE != ' ') {
                IBS.CPY2CLS(SCCGWA, SMCMSG_ERROR_MSG.SM_KEY_TYPE_ERROR, WS_TEMP_VARIABLE.WS_MSGID);
                WS_TEMP_VARIABLE.WS_FLD_NO = SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE_NO;
                S000_ERR_MSG_PROC();
            }
        }
        for (WS_TEMP_VARIABLE.WS_POS = 6; WS_TEMP_VARIABLE.WS_POS <= 9; WS_TEMP_VARIABLE.WS_POS += 1) {
            if (SMB1450_AWA_1450.DATA[5-1].KEY_TYPE == SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE 
                && SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE != ' ') {
                IBS.CPY2CLS(SCCGWA, SMCMSG_ERROR_MSG.SM_KEY_TYPE_ERROR, WS_TEMP_VARIABLE.WS_MSGID);
                WS_TEMP_VARIABLE.WS_FLD_NO = SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE_NO;
                S000_ERR_MSG_PROC();
            }
        }
        for (WS_TEMP_VARIABLE.WS_POS = 7; WS_TEMP_VARIABLE.WS_POS <= 9; WS_TEMP_VARIABLE.WS_POS += 1) {
            if (SMB1450_AWA_1450.DATA[6-1].KEY_TYPE == SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE 
                && SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE != ' ') {
                IBS.CPY2CLS(SCCGWA, SMCMSG_ERROR_MSG.SM_KEY_TYPE_ERROR, WS_TEMP_VARIABLE.WS_MSGID);
                WS_TEMP_VARIABLE.WS_FLD_NO = SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE_NO;
                S000_ERR_MSG_PROC();
            }
        }
        for (WS_TEMP_VARIABLE.WS_POS = 8; WS_TEMP_VARIABLE.WS_POS <= 9; WS_TEMP_VARIABLE.WS_POS += 1) {
            if (SMB1450_AWA_1450.DATA[7-1].KEY_TYPE == SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE 
                && SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE != ' ') {
                IBS.CPY2CLS(SCCGWA, SMCMSG_ERROR_MSG.SM_KEY_TYPE_ERROR, WS_TEMP_VARIABLE.WS_MSGID);
                WS_TEMP_VARIABLE.WS_FLD_NO = SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE_NO;
                S000_ERR_MSG_PROC();
            }
        }
        for (WS_TEMP_VARIABLE.WS_POS = 9; WS_TEMP_VARIABLE.WS_POS <= 9; WS_TEMP_VARIABLE.WS_POS += 1) {
            if (SMB1450_AWA_1450.DATA[8-1].KEY_TYPE == SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE 
                && SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE != ' ') {
                IBS.CPY2CLS(SCCGWA, SMCMSG_ERROR_MSG.SM_KEY_TYPE_ERROR, WS_TEMP_VARIABLE.WS_MSGID);
                WS_TEMP_VARIABLE.WS_FLD_NO = SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE_NO;
                S000_ERR_MSG_PROC();
            }
        }
    }
    public void B005_ADD_RECORD() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, SMCSAWFW);
        SMCSAWFW.CODE = SMB1450_AWA_1450.CODE;
        SMCSAWFW.Q_NAME = SMB1450_AWA_1450.Q_NAME;
        SMCSAWFW.Q_STS = SMB1450_AWA_1450.Q_STS;
        SMCSAWFW.REL_TYPE = SMB1450_AWA_1450.REL_TYPE;
        SMCSAWFW.Q_FMCODE = SMB1450_AWA_1450.Q_FMCODE;
        SMCSAWFW.QCODE = SMB1450_AWA_1450.QCODE;
        SMCSAWFW.OUT_FLG = SMB1450_AWA_1450.OUT_FLG;
        SMCSAWFW.UPD_FLG = SMB1450_AWA_1450.UPD_FLG;
        SMCSAWFW.STEP_NO = SMB1450_AWA_1450.STEP_NO;
        SMCSAWFW.APP_MMO = SMB1450_AWA_1450.APP_MMO;
        SMCSAWFW.SUB_BR = SMB1450_AWA_1450.SUB_BR;
        WS_TEMP_VARIABLE.WS_CNT = 0;
        for (WS_TEMP_VARIABLE.WS_POS = 1; WS_TEMP_VARIABLE.WS_POS <= 9; WS_TEMP_VARIABLE.WS_POS += 1) {
            if (SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE != ' ') {
                WS_TEMP_VARIABLE.WS_CNT = (short) (WS_TEMP_VARIABLE.WS_CNT + 1);
            }
            SMCSAWFW.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE = SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].KEY_TYPE;
            SMCSAWFW.DATA[WS_TEMP_VARIABLE.WS_POS-1].TQ_FLG = SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].TQ_FLG;
            SMCSAWFW.DATA[WS_TEMP_VARIABLE.WS_POS-1].TQ_STS = SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].TQ_STS;
            SMCSAWFW.DATA[WS_TEMP_VARIABLE.WS_POS-1].CMP_NAME = SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].CMP_NAME;
            SMCSAWFW.DATA[WS_TEMP_VARIABLE.WS_POS-1].TRCODE = SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].TRCODE;
            SMCSAWFW.DATA[WS_TEMP_VARIABLE.WS_POS-1].MSG_FLG = SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].MSG_FLG;
            SMCSAWFW.DATA[WS_TEMP_VARIABLE.WS_POS-1].BK_FLG = SMB1450_AWA_1450.DATA[WS_TEMP_VARIABLE.WS_POS-1].BK_FLG;
        }
        S000_CALL_SMZSAWFW();
    }
    public void S000_CALL_SMZSAWFW() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "SM-S-ADD-WFW", SMCSAWFW);
        if (SMCSAWFW.RC.RC_CODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, SMCSAWFW.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_MSGID);
            WS_TEMP_VARIABLE.WS_FLD_NO = SMB1450_AWA_1450.CODE_NO;
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, WS_TEMP_VARIABLE.WS_MSGID);
        CEP.ERR(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_FLD_NO);
    }
    public void S000_ERR_MSG_PROC_CONTINUE() throws IOException,SQLException,Exception {
        JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, WS_TEMP_VARIABLE.WS_MSGID);
        CEP.ERRC(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_FLD_NO);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
