package com.hisun.SM;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;

import java.io.IOException;
import java.sql.SQLException;

public class SMOT1371 {
    String K_OUTPUT_FMT = "SMM82";
    String CPN_DSTR_MAINTAIN = "SM-S_DSTR_MAINTAIN  ";
    String CPN_DDIC_MAINTAIN = "SM-S_DDIC_MAINTAIN  ";
    String WS_ERR_MSG = " ";
    short WS_FLD_NO = 0;
    int WS_I = 0;
    int WS_K = 0;
    int WS_SP_CNT = 0;
    String WS_FMT = " ";
    SMCMSG_ERROR_MSG SMCMSG_ERROR_MSG = new SMCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCFMT SCCFMT = new SCCFMT();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    SMCOSTRM SMCOSTRM = new SMCOSTRM();
    SMCODICM SMCODICM = new SMCODICM();
    SCCGWA SCCGWA;
    SMB1370_AWA_1370 SMB1370_AWA_1370;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "SMOT1371 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "SMB1370_AWA_1370>");
        SMB1370_AWA_1370 = (SMB1370_AWA_1370) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B010_CHECK_INPUT();
        B020_ADD_DSTR_PROC();
    }
    public void B010_CHECK_INPUT() throws IOException,SQLException,Exception {
        if (SMB1370_AWA_1370.ITM_DAT.trim().length() > 0) {
            IBS.init(SCCGWA, SMCODICM);
            SMCODICM.FUNC = 'I';
            SMCODICM.NAME = SMB1370_AWA_1370.ITM_DAT;
            S000_CALL_SMZDDICM();
        }
    }
    public void B020_ADD_DSTR_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, SMCOSTRM);
        SMCOSTRM.FUNC = 'A';
        SMCOSTRM.OUTPUT_FMT = K_OUTPUT_FMT;
        SMCOSTRM.NAME = SMB1370_AWA_1370.NAME;
        SMCOSTRM.ALIAS = SMB1370_AWA_1370.ALIAS;
        SMCOSTRM.EN_NAME = SMB1370_AWA_1370.EN_NAME;
        SMCOSTRM.CH_NAME = SMB1370_AWA_1370.CH_NAME;
        SMCOSTRM.TYPE = SMB1370_AWA_1370.TYPE;
        SMCOSTRM.DATA.DATA_LEN = 8850;
        SMCOSTRM.REDEFINES26.REDEFINES29.ITM_TEXT[1-1].ITM_NO = SMB1370_AWA_1370.ITM_NO;
        SMCOSTRM.REDEFINES26.DATA_TEXT1 = IBS.CLS2CPY(SCCGWA, SMCOSTRM.REDEFINES26.REDEFINES29);
        SMCOSTRM.REDEFINES26.REDEFINES29.ITM_TEXT[1-1].ITM_LVL = SMB1370_AWA_1370.ITM_LVL;
        SMCOSTRM.REDEFINES26.DATA_TEXT1 = IBS.CLS2CPY(SCCGWA, SMCOSTRM.REDEFINES26.REDEFINES29);
        SMCOSTRM.REDEFINES26.REDEFINES29.ITM_TEXT[1-1].ITM_NAME = SMB1370_AWA_1370.ITM_NAME;
        SMCOSTRM.REDEFINES26.DATA_TEXT1 = IBS.CLS2CPY(SCCGWA, SMCOSTRM.REDEFINES26.REDEFINES29);
        SMCOSTRM.REDEFINES26.REDEFINES29.ITM_TEXT[1-1].ITM_DAT = SMB1370_AWA_1370.ITM_DAT;
        SMCOSTRM.REDEFINES26.DATA_TEXT1 = IBS.CLS2CPY(SCCGWA, SMCOSTRM.REDEFINES26.REDEFINES29);
        SMCOSTRM.REDEFINES26.REDEFINES29.ITM_TEXT[1-1].ITM_IND = SMB1370_AWA_1370.ITM_IND;
        SMCOSTRM.REDEFINES26.DATA_TEXT1 = IBS.CLS2CPY(SCCGWA, SMCOSTRM.REDEFINES26.REDEFINES29);
        SMCOSTRM.REDEFINES26.REDEFINES29.ITM_TEXT[1-1].ITM_CYC = SMB1370_AWA_1370.ITM_CYC;
        SMCOSTRM.REDEFINES26.DATA_TEXT1 = IBS.CLS2CPY(SCCGWA, SMCOSTRM.REDEFINES26.REDEFINES29);
        SMCOSTRM.REDEFINES26.REDEFINES29.ITM_TEXT[1-1].ITM_RDID = SMB1370_AWA_1370.ITM_RDID;
        SMCOSTRM.REDEFINES26.DATA_TEXT1 = IBS.CLS2CPY(SCCGWA, SMCOSTRM.REDEFINES26.REDEFINES29);
        SMCOSTRM.REDEFINES26.REDEFINES29.ITM_TEXT[1-1].ITM_VALUE = SMB1370_AWA_1370.ITM_VAL;
        SMCOSTRM.REDEFINES26.DATA_TEXT1 = IBS.CLS2CPY(SCCGWA, SMCOSTRM.REDEFINES26.REDEFINES29);
        SMCOSTRM.REDEFINES26.REDEFINES29.ITM_TEXT[1-1].ITM_STYPE = SMB1370_AWA_1370.ITM_STYP;
        SMCOSTRM.REDEFINES26.DATA_TEXT1 = IBS.CLS2CPY(SCCGWA, SMCOSTRM.REDEFINES26.REDEFINES29);
        SMCOSTRM.UPD_DATE = SCCGWA.COMM_AREA.AC_DATE;
        SMCOSTRM.UPD_TLR = SCCGWA.COMM_AREA.TL_ID;
        S000_CALL_SMZDSTRM();
    }
    public void S000_CALL_SMZDDICM() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, CPN_DDIC_MAINTAIN, SMCODICM, true);
        if (SMCODICM.RC.RC_CODE != 0) {
            WS_ERR_MSG = IBS.CLS2CPY(SCCGWA, SMCODICM.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_SMZDSTRM() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, CPN_DSTR_MAINTAIN, SMCOSTRM);
        if (SMCOSTRM.RC.RC_CODE != 0) {
            WS_ERR_MSG = IBS.CLS2CPY(SCCGWA, SMCOSTRM.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG, WS_FLD_NO);
    }
    public void S000_ERR_MSG_PROC_CONTINUE() throws IOException,SQLException,Exception {
        CEP.ERRC(SCCGWA, WS_ERR_MSG, WS_FLD_NO);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
