package com.hisun.DD;

public class DDB5600_AWA_5600 {
    public String AC_NO = " ";
    public short AC_NO_NO = 0;
    public char TYPE = ' ';
    public short TYPE_NO = 0;
    public String REF_NO = " ";
    public short REF_NO_NO = 0;
    public char STS = ' ';
    public short STS_NO = 0;
    public String AC_NAME = " ";
    public short AC_NAME_NO = 0;
    public char ORG_TYP = ' ';
    public short ORG_TYP_NO = 0;
    public String ORG_NAME = " ";
    public short ORG_NAME_NO = 0;
    public String RLS_BOOK = " ";
    public short RLS_BOOK_NO = 0;
    public String RLS_RSN = " ";
    public short RLS_RSN_NO = 0;
    public int RLS_DATE = 0;
    public short RLS_DATE_NO = 0;
    public int RLS_BR = 0;
    public short RLS_BR_NO = 0;
    public String RLS_TL = " ";
    public short RLS_TL_NO = 0;
    public String RLS_AUTH = " ";
    public short RLS_AUTH_NO = 0;
    public String RLAW_NM1 = " ";
    public short RLAW_NM1_NO = 0;
    public String RLAW_NO1 = " ";
    public short RLAW_NO1_NO = 0;
    public String RLAW_NM2 = " ";
    public short RLAW_NM2_NO = 0;
    public String RLAW_NO2 = " ";
    public short RLAW_NO2_NO = 0;
    public String CCY = " ";
    public short CCY_NO = 0;
    public char CCY_TYP = ' ';
    public short CCY_TYP_NO = 0;
    public int AC_SEQ = 0;
    public short AC_SEQ_NO = 0;
}
