package com.hisun.DD;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;
import com.hisun.BP.*;

import java.io.IOException;
import java.sql.SQLException;

public class DDOT5122 {
    String WS_MSGID = " ";
    short WS_IDX = 0;
    String WS_ERR_MSG = " ";
    DDCMSG_ERROR_MSG DDCMSG_ERROR_MSG = new DDCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCMSG SCCMSG = new SCCMSG();
    SCCCALL SCCCALL = new SCCCALL();
    DDCSMTDF DDCSMTDF = new DDCSMTDF();
    BPCUINTI BPCUINTI = new BPCUINTI();
    SCCGWA SCCGWA;
    DDB5122_AWA_5122 DDB5122_AWA_5122;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "DDOT5122 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "DDB5122_AWA_5122>");
        DDB5122_AWA_5122 = (DDB5122_AWA_5122) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B010_CHECK_INPUT();
        B030_GET_LIST();
    }
    public void B010_CHECK_INPUT() throws IOException,SQLException,Exception {
        if (DDB5122_AWA_5122.I_OPT == ' ') {
            WS_MSGID = DDCMSG_ERROR_MSG.DD_MUST_INPUT;
            S000_ERR_MSG_PROC();
        }
        if (DDB5122_AWA_5122.I_DD_AC.trim().length() == 0) {
            WS_MSGID = DDCMSG_ERROR_MSG.DD_AC_NO_M_INPUT;
            S000_ERR_MSG_PROC();
        }
        if (DDB5122_AWA_5122.I_CCY.trim().length() == 0) {
            WS_MSGID = DDCMSG_ERROR_MSG.DD_CCY_M_INPUT;
            S000_ERR_MSG_PROC();
        }
        if (DDB5122_AWA_5122.I_FLG == ' ') {
            WS_MSGID = DDCMSG_ERROR_MSG.DD_CCY_M_INPUT;
            S000_ERR_MSG_PROC();
        }
    }
    public void B030_GET_LIST() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, DDB5122_AWA_5122);
        CEP.TRC(SCCGWA, DDB5122_AWA_5122.I_OPT);
        CEP.TRC(SCCGWA, DDB5122_AWA_5122.I_DD_AC);
        CEP.TRC(SCCGWA, DDB5122_AWA_5122.I_CCY);
        CEP.TRC(SCCGWA, DDB5122_AWA_5122.I_FLG);
        CEP.TRC(SCCGWA, DDB5122_AWA_5122.I_PROLNO);
        CEP.TRC(SCCGWA, DDB5122_AWA_5122.I_MTDT);
        CEP.TRC(SCCGWA, DDB5122_AWA_5122.I_STDT);
        CEP.TRC(SCCGWA, DDB5122_AWA_5122.I_EDDT);
        CEP.TRC(SCCGWA, DDB5122_AWA_5122.I_JXOPT);
        CEP.TRC(SCCGWA, DDB5122_AWA_5122.I_SEQ2);
        CEP.TRC(SCCGWA, DDB5122_AWA_5122.I_FCTYP);
        CEP.TRC(SCCGWA, DDB5122_AWA_5122.I_CJTYP);
        IBS.init(SCCGWA, DDCSMTDF);
        DDCSMTDF.OPT = DDB5122_AWA_5122.I_OPT;
        DDCSMTDF.AC = DDB5122_AWA_5122.I_DD_AC;
        DDCSMTDF.CCY = DDB5122_AWA_5122.I_CCY;
        DDCSMTDF.FLG = DDB5122_AWA_5122.I_FLG;
        DDCSMTDF.CI_CNM = DDB5122_AWA_5122.I_CI_CNM;
        DDCSMTDF.CI_ENM = DDB5122_AWA_5122.I_CI_ENM;
        DDCSMTDF.ADP_NO = DDB5122_AWA_5122.I_PROLNO;
        DDCSMTDF.ADP_DATE = DDB5122_AWA_5122.I_MTDT;
        DDCSMTDF.ADP_STRDATE = DDB5122_AWA_5122.I_STDT;
        DDCSMTDF.ADP_EXPDATE = DDB5122_AWA_5122.I_EDDT;
        DDCSMTDF.ADP_POST_PERIOD = DDB5122_AWA_5122.I_JXOPT;
        DDCSMTDF.ADP_POST_FEQ = DDB5122_AWA_5122.I_SEQ2;
        DDCSMTDF.TIR_TYPE = DDB5122_AWA_5122.I_FCTYP;
        DDCSMTDF.AGSP_FLG = DDB5122_AWA_5122.I_CJTYP;
        for (WS_IDX = 1; WS_IDX <= 5; WS_IDX += 1) {
            CEP.TRC(SCCGWA, WS_IDX);
            DDCSMTDF.TIR_DATA.TIR_INF[WS_IDX-1].TIR_AMT1 = DDB5122_AWA_5122.TIR_INF[WS_IDX-1].T_AMT1;
            CEP.TRC(SCCGWA, DDCSMTDF.TIR_DATA.TIR_INF[WS_IDX-1].TIR_AMT1);
            DDCSMTDF.TIR_DATA.TIR_INF[WS_IDX-1].TIR_RBAS1 = DDB5122_AWA_5122.TIR_INF[WS_IDX-1].T_RBAS1;
            CEP.TRC(SCCGWA, DDCSMTDF.TIR_DATA.TIR_INF[WS_IDX-1].TIR_RBAS1);
            DDCSMTDF.TIR_DATA.TIR_INF[WS_IDX-1].TIR_RCD1 = DDB5122_AWA_5122.TIR_INF[WS_IDX-1].T_RCD1;
            CEP.TRC(SCCGWA, DDCSMTDF.TIR_DATA.TIR_INF[WS_IDX-1].TIR_RCD1);
            DDCSMTDF.TIR_DATA.TIR_INF[WS_IDX-1].TIR_SPR_TYPE1 = DDB5122_AWA_5122.TIR_INF[WS_IDX-1].T_SPTYP1;
            CEP.TRC(SCCGWA, DDCSMTDF.TIR_DATA.TIR_INF[WS_IDX-1].TIR_SPR_TYPE1);
            DDCSMTDF.TIR_DATA.TIR_INF[WS_IDX-1].TIR_SPR1 = DDB5122_AWA_5122.TIR_INF[WS_IDX-1].T_SPR1;
            CEP.TRC(SCCGWA, DDCSMTDF.TIR_DATA.TIR_INF[WS_IDX-1].TIR_SPR1);
            DDCSMTDF.TIR_DATA.TIR_INF[WS_IDX-1].TIR_SPR_PCT1 = DDB5122_AWA_5122.TIR_INF[WS_IDX-1].T_SPR_P1;
            CEP.TRC(SCCGWA, DDCSMTDF.TIR_DATA.TIR_INF[WS_IDX-1].TIR_SPR_PCT1);
            DDCSMTDF.TIR_DATA.TIR_INF[WS_IDX-1].TIR_FIX_RATE1 = DDB5122_AWA_5122.TIR_INF[WS_IDX-1].T_FIX_R1;
            CEP.TRC(SCCGWA, DDCSMTDF.TIR_DATA.TIR_INF[WS_IDX-1].TIR_FIX_RATE1);
        }
        S000_CALL_DDZSMTDF();
    }
    public void S000_CHECK_TERM_AND_RATETYP() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, DDCSMTDF.TIR_DATA.TIR_INF[1-1].TIR_RBAS1);
        CEP.TRC(SCCGWA, DDCSMTDF.TIR_DATA.TIR_INF[1-1].TIR_RCD1);
        CEP.TRC(SCCGWA, DDB5122_AWA_5122.I_CCY);
        CEP.TRC(SCCGWA, DDCSMTDF.CCY);
        for (WS_IDX = 1; WS_IDX <= 5; WS_IDX += 1) {
            if (DDCSMTDF.TIR_DATA.TIR_INF[WS_IDX-1].TIR_RBAS1.trim().length() > 0 
                && DDCSMTDF.TIR_DATA.TIR_INF[WS_IDX-1].TIR_RCD1.trim().length() > 0) {
                IBS.init(SCCGWA, BPCUINTI);
                BPCUINTI.DT = SCCGWA.COMM_AREA.AC_DATE;
                BPCUINTI.CCY = DDCSMTDF.CCY;
                CEP.TRC(SCCGWA, DDCSMTDF.TIR_DATA.TIR_INF[WS_IDX-1].TIR_RBAS1);
                CEP.TRC(SCCGWA, DDCSMTDF.TIR_DATA.TIR_INF[WS_IDX-1].TIR_RCD1);
                BPCUINTI.BASE_TYP = DDCSMTDF.TIR_DATA.TIR_INF[WS_IDX-1].TIR_RBAS1;
                BPCUINTI.TENOR = DDCSMTDF.TIR_DATA.TIR_INF[WS_IDX-1].TIR_RCD1;
                S000_CALL_BPZUINTI();
            }
        }
    }
    public void S000_CALL_BPZUINTI() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-U-INTR-INQ", BPCUINTI);
        CEP.TRC(SCCGWA, BPCUINTI.RC);
        if (BPCUINTI.RC.RC_CODE != 0) {
            WS_ERR_MSG = IBS.CLS2CPY(SCCGWA, BPCUINTI.RC);
            S000_ERR_MSG_PROC_CONTINUE();
        }
    }
    public void S000_CALL_DDZSMTDF() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "DD-Z-DDZSMTDF", DDCSMTDF);
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_MSGID);
    }
    public void S000_ERR_MSG_PROC_CONTINUE() throws IOException,SQLException,Exception {
        CEP.ERRC(SCCGWA, WS_ERR_MSG);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
