package com.hisun.DD;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;
import com.hisun.BP.*;
import com.hisun.CI.*;

import java.io.IOException;
import java.sql.SQLException;

public class DDOT1100 {
    short WS_FLD_NO = 0;
    String WS_ERR_MSG = " ";
    DDCMSG_ERROR_MSG DDCMSG_ERROR_MSG = new DDCMSG_ERROR_MSG();
    SCCMSG SCCMSG = new SCCMSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    DDCSTRAC DDCSTRAC = new DDCSTRAC();
    BPCFFTXI BPCFFTXI = new BPCFFTXI();
    BPCTCALF BPCTCALF = new BPCTCALF();
    CICACCU CICACCU = new CICACCU();
    SCCGWA SCCGWA;
    DDB1100_AWA_1100 DDB1100_AWA_1100;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROCESS();
        B000_MAIN_PROCESS();
        CEP.TRC(SCCGWA, "DDOT1100 return!");
        Z_RET();
    }
    public void A000_INIT_PROCESS() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "DDB1100_AWA_1100>");
        DDB1100_AWA_1100 = (DDB1100_AWA_1100) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
    }
    public void B000_MAIN_PROCESS() throws IOException,SQLException,Exception {
        B100_CHECK_INPUT_DATA();
        B200_TRANS_DATA_PROC();
        B300_GET_FR_CI_TYP();
    }
    public void B300_GET_FR_CI_TYP() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, DDCSTRAC.O_DATA.CHG_AC);
        IBS.init(SCCGWA, CICACCU);
        CICACCU.DATA.AGR_NO = DDCSTRAC.O_DATA.CHG_AC;
        S000_CALL_CIZACCU();
        CEP.TRC(SCCGWA, CICACCU.DATA.CI_TYP);
    }
    public void B100_CHECK_INPUT_DATA() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.FR_BV_AM);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.FR_BV_TP);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.FR_CARD);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.FR_AC);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.FR_PSBK);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.CHQ_TYPE);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.CHQ_NO);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.CHQ_ISDT);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.FR_AC_CN);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.FR_AC_EN);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.FR_CCY);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.FR_CYTP);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.FR_AMT);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.TO_BV_AM);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.TO_BV_TP);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.TO_CARD);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.TO_AC);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.TO_CCY);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.TO_CYTP);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.TO_ACCN);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.TO_ACEN);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.TO_AMT);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.EX_RATE);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.TICK_NO);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.EX_TIME);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.VAL_DATE);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.TX_RMK);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.REMARKS);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.PAY_TYPE);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.PSWD);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.PAY_PSWD);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.CHK_PSW);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.TRK_DAT2);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.TRK_DAT3);
        if (DDB1100_AWA_1100.FR_AC.trim().length() == 0 
            && DDB1100_AWA_1100.FR_CARD.trim().length() == 0) {
            WS_ERR_MSG = DDCMSG_ERROR_MSG.DD_FRAC_NO_M_INPUT;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        if (DDB1100_AWA_1100.FR_CCY.trim().length() == 0) {
            WS_ERR_MSG = DDCMSG_ERROR_MSG.DD_CCY_M_INPUT;
            WS_FLD_NO = DDB1100_AWA_1100.FR_CCY_NO;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        if (DDB1100_AWA_1100.FR_AMT == 0) {
            WS_ERR_MSG = DDCMSG_ERROR_MSG.DD_TRF_AMT_M_INPUT;
            WS_FLD_NO = DDB1100_AWA_1100.FR_AMT_NO;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        if (DDB1100_AWA_1100.TO_AC.trim().length() == 0 
            && DDB1100_AWA_1100.TO_CARD.trim().length() == 0) {
            WS_ERR_MSG = DDCMSG_ERROR_MSG.DD_TOAC_NO_M_INPUT;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        S000_ERR_MSG_PROC_LAST();
    }
    public void B200_TRANS_DATA_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, DDCSTRAC);
        DDCSTRAC.FR_BV_AM = DDB1100_AWA_1100.FR_BV_AM;
        DDCSTRAC.FR_BV_TYPE = DDB1100_AWA_1100.FR_BV_TP;
        DDCSTRAC.FR_CARD = DDB1100_AWA_1100.FR_CARD;
        DDCSTRAC.FR_AC = DDB1100_AWA_1100.FR_AC;
        DDCSTRAC.FR_PSBK = DDB1100_AWA_1100.FR_PSBK;
        DDCSTRAC.CHQ_TYPE = DDB1100_AWA_1100.CHQ_TYPE;
        DDCSTRAC.CHQ_NO = DDB1100_AWA_1100.CHQ_NO;
        DDCSTRAC.CHQ_ISS_DATE = DDB1100_AWA_1100.CHQ_ISDT;
        DDCSTRAC.FR_AC_CNAME = DDB1100_AWA_1100.FR_AC_CN;
        DDCSTRAC.FR_AC_ENAME = DDB1100_AWA_1100.FR_AC_EN;
        DDCSTRAC.FR_CCY = DDB1100_AWA_1100.FR_CCY;
        DDCSTRAC.FR_CCY_TYPE = DDB1100_AWA_1100.FR_CYTP;
        DDCSTRAC.FR_AMT = DDB1100_AWA_1100.FR_AMT;
        DDCSTRAC.TO_BV_AM = DDB1100_AWA_1100.TO_BV_AM;
        DDCSTRAC.TO_BV_TYPE = DDB1100_AWA_1100.TO_BV_TP;
        DDCSTRAC.TO_CARD = DDB1100_AWA_1100.TO_CARD;
        DDCSTRAC.TO_AC = DDB1100_AWA_1100.TO_AC;
        DDCSTRAC.FR_CREV_NO = DDB1100_AWA_1100.FR_CREV;
        DDCSTRAC.TO_CREV_NO = DDB1100_AWA_1100.TO_CREV;
        DDCSTRAC.TO_CCY = DDB1100_AWA_1100.TO_CCY;
        DDCSTRAC.TO_CCY_TYPE = DDB1100_AWA_1100.TO_CYTP;
        DDCSTRAC.TO_AC_CNAME = DDB1100_AWA_1100.TO_ACCN;
        DDCSTRAC.TO_AC_ENAME = DDB1100_AWA_1100.TO_ACEN;
        DDCSTRAC.TO_AMT = DDB1100_AWA_1100.TO_AMT;
        DDCSTRAC.EX_RATE = DDB1100_AWA_1100.EX_RATE;
        DDCSTRAC.TICK_NO = DDB1100_AWA_1100.TICK_NO;
        DDCSTRAC.EX_TIME = DDB1100_AWA_1100.EX_TIME;
        DDCSTRAC.VAL_DATE = DDB1100_AWA_1100.VAL_DATE;
        DDCSTRAC.TX_RMK = DDB1100_AWA_1100.TX_RMK;
        DDCSTRAC.REMARKS = DDB1100_AWA_1100.REMARKS;
        DDCSTRAC.PAY_TYPE = DDB1100_AWA_1100.PAY_TYPE;
        DDCSTRAC.PSWD = DDB1100_AWA_1100.PSWD;
        DDCSTRAC.PAY_PSWD = DDB1100_AWA_1100.PAY_PSWD;
        DDCSTRAC.CHK_PSW = 'P';
        DDCSTRAC.FR_PSBK_SEQ = DDB1100_AWA_1100.FR_P_SEQ;
        DDCSTRAC.TO_PSBK_SEQ = DDB1100_AWA_1100.TO_P_SEQ;
        DDCSTRAC.CHK_PSW = DDB1100_AWA_1100.CHK_PSW;
        DDCSTRAC.TRK2_DAT = DDB1100_AWA_1100.TRK_DAT2;
        DDCSTRAC.TRK3_DAT = DDB1100_AWA_1100.TRK_DAT3;
        DDCSTRAC.DELAY_FLG = DDB1100_AWA_1100.DELY_FLG;
        DDCSTRAC.REP_TYP = DDB1100_AWA_1100.REG_TYP;
        DDCSTRAC.BASE_FLG = DDB1100_AWA_1100.BASE_FLG;
        DDCSTRAC.REP_FLG = DDB1100_AWA_1100.REG_FLG;
        DDCSTRAC.MAN_FLG = DDB1100_AWA_1100.MOD_FLG;
        DDCSTRAC.TR_AC = DDB1100_AWA_1100.TR_AC;
        DDCSTRAC.CI_TYP = DDB1100_AWA_1100.CI_TYP;
        DDCSTRAC.CI_ID_NO = DDB1100_AWA_1100.CI_ID_NO;
        DDCSTRAC.ORG_CD = DDB1100_AWA_1100.ORG_CD;
        DDCSTRAC.CI_NM = DDB1100_AWA_1100.CI_NM;
        DDCSTRAC.TO_CI_NM = DDB1100_AWA_1100.TO_CI_NM;
        DDCSTRAC.CCY = DDB1100_AWA_1100.CCY;
        DDCSTRAC.TR_AMT = DDB1100_AWA_1100.TR_AMT;
        DDCSTRAC.EX_RAT = DDB1100_AWA_1100.EX_RAT;
        DDCSTRAC.EX_AMT = DDB1100_AWA_1100.EX_AMT;
        DDCSTRAC.CHN_ACNO = DDB1100_AWA_1100.CHN_ACNO;
        DDCSTRAC.CASH_AMT = DDB1100_AWA_1100.CASH_AMT;
        DDCSTRAC.FOR_ACNO = DDB1100_AWA_1100.FOR_ACNO;
        DDCSTRAC.OTH_AMT = DDB1100_AWA_1100.OTH_AMT;
        DDCSTRAC.OTH_ACNO = DDB1100_AWA_1100.OTH_ACNO;
        DDCSTRAC.PAY_MTH = DDB1100_AWA_1100.PAY_MTH;
        DDCSTRAC.CN_F_CCY = DDB1100_AWA_1100.CN_F_CCY;
        DDCSTRAC.CN_F_AMT = DDB1100_AWA_1100.CN_F_AMT;
        DDCSTRAC.FO_F_CCY = DDB1100_AWA_1100.FO_F_CCY;
        DDCSTRAC.FO_F_AMT = DDB1100_AWA_1100.FO_F_AMT;
        DDCSTRAC.CNTY_CD = DDB1100_AWA_1100.CNTY_CD;
        DDCSTRAC.PAY_TYP = DDB1100_AWA_1100.PAY_TYP;
        DDCSTRAC.TX_CODE1 = DDB1100_AWA_1100.TX_CODE1;
        DDCSTRAC.AMT1 = DDB1100_AWA_1100.AMT1;
        DDCSTRAC.REMARKS1 = DDB1100_AWA_1100.REMARKS1;
        DDCSTRAC.TX_CODE2 = DDB1100_AWA_1100.TX_CODE2;
        DDCSTRAC.AMT2 = DDB1100_AWA_1100.AMT2;
        DDCSTRAC.REMARKS2 = DDB1100_AWA_1100.REMARKS2;
        DDCSTRAC.REF_FLG = DDB1100_AWA_1100.REF_FLG;
        DDCSTRAC.REF_NO = DDB1100_AWA_1100.REF_NO;
        DDCSTRAC.PAY_ATTR = DDB1100_AWA_1100.PAY_ATTR;
        DDCSTRAC.REF_CKNO = DDB1100_AWA_1100.REF_CKNO;
        DDCSTRAC.CHK_AMT = DDB1100_AWA_1100.CHK_AMT;
        DDCSTRAC.IMP_DATE = DDB1100_AWA_1100.IMP_DATE;
        DDCSTRAC.CONTR_NO = DDB1100_AWA_1100.CONTR_NO;
        DDCSTRAC.INV_NO = DDB1100_AWA_1100.INV_NO;
        DDCSTRAC.CUSM_CD = DDB1100_AWA_1100.CUSM_CD;
        DDCSTRAC.CUSM_NO = DDB1100_AWA_1100.CUSM_NO;
        DDCSTRAC.CUSM_CCY = DDB1100_AWA_1100.CUSM_CCY;
        DDCSTRAC.CUSM_AMT = DDB1100_AWA_1100.CUSM_AMT;
        DDCSTRAC.OFF_AMT = DDB1100_AWA_1100.OFF_AMT;
        DDCSTRAC.CUSM_CNM = DDB1100_AWA_1100.CUSM_CNM;
        DDCSTRAC.CUSM_TEL = DDB1100_AWA_1100.CUSM_TEL;
        DDCSTRAC.CUSM_DATE = DDB1100_AWA_1100.CUSM_DAT;
        DDCSTRAC.RLT_AC = DDB1100_AWA_1100.RLT_AC;
        DDCSTRAC.RLT_AC_NAME = DDB1100_AWA_1100.RLT_ACNM;
        DDCSTRAC.RLT_BANK = DDB1100_AWA_1100.TO_RLTCD;
        DDCSTRAC.RLT_BK_NM = DDB1100_AWA_1100.TO_RLTNM;
        DDCSTRAC.RLT_CI_TYP = DDB1100_AWA_1100.TO_CITYP;
        DDCSTRAC.AGE_FLG = DDB1100_AWA_1100.AGE_FLG;
        DDCSTRAC.AGE_CI_NM = DDB1100_AWA_1100.AGE_CINM;
        DDCSTRAC.AGE_ID_TYPE = DDB1100_AWA_1100.AGE_IDTY;
        DDCSTRAC.AGE_ID_NO = DDB1100_AWA_1100.AGE_IDNO;
        DDCSTRAC.AGE_CNTY = DDB1100_AWA_1100.AGE_CNTY;
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.FR_P_SEQ);
        CEP.TRC(SCCGWA, DDB1100_AWA_1100.TO_P_SEQ);
        CEP.TRC(SCCGWA, DDCSTRAC.FR_BV_AM);
        CEP.TRC(SCCGWA, DDCSTRAC.FR_BV_TYPE);
        CEP.TRC(SCCGWA, DDCSTRAC.FR_CARD);
        CEP.TRC(SCCGWA, DDCSTRAC.FR_AC);
        CEP.TRC(SCCGWA, DDCSTRAC.FR_PSBK);
        CEP.TRC(SCCGWA, DDCSTRAC.CHQ_TYPE);
        CEP.TRC(SCCGWA, DDCSTRAC.CHQ_NO);
        CEP.TRC(SCCGWA, DDCSTRAC.CHQ_ISS_DATE);
        CEP.TRC(SCCGWA, DDCSTRAC.FR_AC_CNAME);
        CEP.TRC(SCCGWA, DDCSTRAC.FR_AC_ENAME);
        CEP.TRC(SCCGWA, DDCSTRAC.FR_CCY);
        CEP.TRC(SCCGWA, DDCSTRAC.FR_CCY_TYPE);
        CEP.TRC(SCCGWA, DDCSTRAC.FR_AMT);
        CEP.TRC(SCCGWA, DDCSTRAC.TO_BV_AM);
        CEP.TRC(SCCGWA, DDCSTRAC.TO_BV_TYPE);
        CEP.TRC(SCCGWA, DDCSTRAC.TO_CARD);
        CEP.TRC(SCCGWA, DDCSTRAC.TO_AC);
        CEP.TRC(SCCGWA, DDCSTRAC.FR_CREV_NO);
        CEP.TRC(SCCGWA, DDCSTRAC.TO_CREV_NO);
        CEP.TRC(SCCGWA, DDCSTRAC.TO_CCY);
        CEP.TRC(SCCGWA, DDCSTRAC.TO_CCY_TYPE);
        CEP.TRC(SCCGWA, DDCSTRAC.TO_AC_CNAME);
        CEP.TRC(SCCGWA, DDCSTRAC.TO_AC_ENAME);
        CEP.TRC(SCCGWA, DDCSTRAC.TO_AMT);
        CEP.TRC(SCCGWA, DDCSTRAC.EX_RATE);
        CEP.TRC(SCCGWA, DDCSTRAC.TICK_NO);
        CEP.TRC(SCCGWA, DDCSTRAC.EX_TIME);
        CEP.TRC(SCCGWA, DDCSTRAC.VAL_DATE);
        CEP.TRC(SCCGWA, DDCSTRAC.TX_RMK);
        CEP.TRC(SCCGWA, DDCSTRAC.REMARKS);
        CEP.TRC(SCCGWA, DDCSTRAC.PAY_TYPE);
        CEP.TRC(SCCGWA, DDCSTRAC.PSWD);
        CEP.TRC(SCCGWA, DDCSTRAC.PAY_PSWD);
        CEP.TRC(SCCGWA, DDCSTRAC.FR_PSBK_SEQ);
        CEP.TRC(SCCGWA, DDCSTRAC.TO_PSBK_SEQ);
        CEP.TRC(SCCGWA, DDCSTRAC.CHK_PSW);
        CEP.TRC(SCCGWA, DDCSTRAC.TRK2_DAT);
        CEP.TRC(SCCGWA, DDCSTRAC.TRK2_DAT);
        CEP.TRC(SCCGWA, DDCSTRAC.DELAY_FLG);
        CEP.TRC(SCCGWA, DDCSTRAC.REP_TYP);
        CEP.TRC(SCCGWA, DDCSTRAC.BASE_FLG);
        CEP.TRC(SCCGWA, DDCSTRAC.REP_FLG);
        CEP.TRC(SCCGWA, DDCSTRAC.MAN_FLG);
        CEP.TRC(SCCGWA, DDCSTRAC.TR_AC);
        CEP.TRC(SCCGWA, DDCSTRAC.CI_TYP);
        CEP.TRC(SCCGWA, DDCSTRAC.CI_ID_NO);
        CEP.TRC(SCCGWA, DDCSTRAC.ORG_CD);
        CEP.TRC(SCCGWA, DDCSTRAC.CI_NM);
        CEP.TRC(SCCGWA, DDCSTRAC.TO_CI_NM);
        CEP.TRC(SCCGWA, DDCSTRAC.CCY);
        CEP.TRC(SCCGWA, DDCSTRAC.TR_AMT);
        CEP.TRC(SCCGWA, DDCSTRAC.EX_RATE);
        CEP.TRC(SCCGWA, DDCSTRAC.EX_AMT);
        CEP.TRC(SCCGWA, DDCSTRAC.CHN_ACNO);
        CEP.TRC(SCCGWA, DDCSTRAC.CASH_AMT);
        CEP.TRC(SCCGWA, DDCSTRAC.FOR_ACNO);
        CEP.TRC(SCCGWA, DDCSTRAC.OTH_AMT);
        CEP.TRC(SCCGWA, DDCSTRAC.OTH_ACNO);
        CEP.TRC(SCCGWA, DDCSTRAC.PAY_MTH);
        CEP.TRC(SCCGWA, DDCSTRAC.CN_F_CCY);
        CEP.TRC(SCCGWA, DDCSTRAC.CN_F_AMT);
        CEP.TRC(SCCGWA, DDCSTRAC.FO_F_CCY);
        CEP.TRC(SCCGWA, DDCSTRAC.FO_F_AMT);
        CEP.TRC(SCCGWA, DDCSTRAC.CNTY_CD);
        CEP.TRC(SCCGWA, DDCSTRAC.PAY_TYP);
        CEP.TRC(SCCGWA, DDCSTRAC.TX_CODE1);
        CEP.TRC(SCCGWA, DDCSTRAC.AMT1);
        CEP.TRC(SCCGWA, DDCSTRAC.REMARKS1);
        CEP.TRC(SCCGWA, DDCSTRAC.TX_CODE2);
        CEP.TRC(SCCGWA, DDCSTRAC.AMT2);
        CEP.TRC(SCCGWA, DDCSTRAC.REMARKS2);
        CEP.TRC(SCCGWA, DDCSTRAC.REF_FLG);
        CEP.TRC(SCCGWA, DDCSTRAC.REF_NO);
        CEP.TRC(SCCGWA, DDCSTRAC.PAY_ATTR);
        CEP.TRC(SCCGWA, DDCSTRAC.REF_CKNO);
        CEP.TRC(SCCGWA, DDCSTRAC.CHK_AMT);
        CEP.TRC(SCCGWA, DDCSTRAC.IMP_DATE);
        CEP.TRC(SCCGWA, DDCSTRAC.CONTR_NO);
        CEP.TRC(SCCGWA, DDCSTRAC.INV_NO);
        CEP.TRC(SCCGWA, DDCSTRAC.CUSM_CD);
        CEP.TRC(SCCGWA, DDCSTRAC.CUSM_NO);
        CEP.TRC(SCCGWA, DDCSTRAC.CUSM_CCY);
        CEP.TRC(SCCGWA, DDCSTRAC.CUSM_AMT);
        CEP.TRC(SCCGWA, DDCSTRAC.OFF_AMT);
        CEP.TRC(SCCGWA, DDCSTRAC.CUSM_CNM);
        CEP.TRC(SCCGWA, DDCSTRAC.CUSM_TEL);
        CEP.TRC(SCCGWA, DDCSTRAC.CUSM_DATE);
        CEP.TRC(SCCGWA, DDCSTRAC.RLT_AC);
        CEP.TRC(SCCGWA, DDCSTRAC.RLT_AC_NAME);
        CEP.TRC(SCCGWA, DDCSTRAC.RLT_BANK);
        CEP.TRC(SCCGWA, DDCSTRAC.RLT_BK_NM);
        CEP.TRC(SCCGWA, DDCSTRAC.RLT_CI_TYP);
        CEP.TRC(SCCGWA, DDCSTRAC.AGE_FLG);
        CEP.TRC(SCCGWA, DDCSTRAC.AGE_CI_NM);
        CEP.TRC(SCCGWA, DDCSTRAC.AGE_ID_TYPE);
        CEP.TRC(SCCGWA, DDCSTRAC.AGE_ID_NO);
        CEP.TRC(SCCGWA, DDCSTRAC.AGE_CNTY);
        S000_CALL_DDZSTRAC();
    }
    public void S000_SET_FEE_INFO() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCFFTXI);
        BPCFFTXI.TX_DATA.AUH_FLG = '0';
        BPCFFTXI.TX_DATA.CHG_AC_INFO.VALUE_DATE = SCCGWA.COMM_AREA.AC_DATE;
        BPCFFTXI.TX_DATA.CHG_AC_INFO.AC_TYP = '0';
        BPCFFTXI.TX_DATA.CHG_AC_INFO.CHG_AC = DDCSTRAC.O_DATA.CHG_AC;
        BPCFFTXI.TX_DATA.CHG_AC_INFO.CHQ_NO = DDB1100_AWA_1100.CHQ_NO;
        BPCFFTXI.TX_DATA.CHG_AC_INFO.PSBK_NO = DDB1100_AWA_1100.FR_PSBK;
        BPCFFTXI.TX_DATA.CHG_AC_INFO.CHG_CCY = DDB1100_AWA_1100.FR_CCY;
        BPCFFTXI.TX_DATA.CCY_TYPE = DDB1100_AWA_1100.FR_CYTP;
        BPCFFTXI.TX_DATA.SVR_CD = SCCGWA.COMM_AREA.SERV_CODE;
        BPCFFTXI.TX_DATA.CI_NO = DDCSTRAC.O_DATA.CI_NO;
        CEP.TRC(SCCGWA, BPCFFTXI.TX_DATA.CHG_AC_INFO.CHG_AC);
        CEP.TRC(SCCGWA, BPCFFTXI.TX_DATA.CHG_AC_INFO.CHG_CCY);
        CEP.TRC(SCCGWA, BPCFFTXI.TX_DATA.CCY_TYPE);
        CEP.TRC(SCCGWA, BPCFFTXI.TX_DATA.CI_NO);
        S000_CALL_BPZFFTXI();
    }
    public void S000_CALL_BPZFFTXI() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-F-F-TX-INFO", BPCFFTXI);
        if (BPCFFTXI.RC.RC_CODE != 0) {
            WS_ERR_MSG = IBS.CLS2CPY(SCCGWA, BPCFFTXI.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_FEE() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCTCALF);
        BPCTCALF.INPUT_AREA.FUNC_CODE = 'C';
        BPCTCALF.INPUT_AREA.PROD_CODE = DDCSTRAC.O_DATA.PROD_CD;
        BPCTCALF.INPUT_AREA.PROD_CODE1 = DDCSTRAC.O_DATA.PROD_CD;
        BPCTCALF.INPUT_AREA.TX_AMT = DDB1100_AWA_1100.FR_AMT;
        BPCTCALF.INPUT_AREA.TX_CCY = DDB1100_AWA_1100.FR_CCY;
        BPCTCALF.INPUT_AREA.TX_AC = DDB1100_AWA_1100.FR_AC;
        BPCTCALF.INPUT_AREA.TX_CI = DDCSTRAC.O_DATA.CI_NO;
        BPCTCALF.INPUT_AREA.TX_CNT = 1;
        CEP.TRC(SCCGWA, BPCTCALF.INPUT_AREA.PROD_CODE);
        CEP.TRC(SCCGWA, BPCTCALF.INPUT_AREA.TX_AMT);
        CEP.TRC(SCCGWA, BPCTCALF.INPUT_AREA.TX_CCY);
        CEP.TRC(SCCGWA, BPCTCALF.INPUT_AREA.TX_AC);
        CEP.TRC(SCCGWA, BPCTCALF.INPUT_AREA.TX_CI);
        S000_CALL_BPZFCALF();
    }
    public void S000_CALL_BPZFCALF() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-F-F-CAL-FEE", BPCTCALF);
        if (BPCTCALF.RC.RC_CODE != 0) {
            WS_ERR_MSG = IBS.CLS2CPY(SCCGWA, BPCTCALF.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_DDZSTRAC() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "DD-S-TR-AC", DDCSTRAC);
    }
    public void S000_CALL_CIZACCU() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "CI-INQ-ACCU", CICACCU);
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG);
    }
    public void S000_ERR_MSG_PROC_CONTINUE() throws IOException,SQLException,Exception {
        CEP.ERRC(SCCGWA, WS_ERR_MSG, WS_FLD_NO);
    }
    public void S000_ERR_MSG_PROC_LAST() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
