package com.hisun.DD;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;

import java.util.Date;
import java.text.SimpleDateFormat;

import java.io.IOException;
import java.sql.SQLException;

public class DDOT5846 {
    SimpleDateFormat JIBS_sdf;
    Date JIBS_date;
    short WS_FLD_NO = 0;
    String WS_ERR_MSG = " ";
    String WS_TS = " ";
    DDCMSG_ERROR_MSG DDCMSG_ERROR_MSG = new DDCMSG_ERROR_MSG();
    SCCMSG SCCMSG = new SCCMSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    DDCSCPLC DDCSCPLC = new DDCSCPLC();
    SCCGWA SCCGWA;
    DDB5846_AWA_5846 DDB5846_AWA_5846;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROCESS();
        B000_MAIN_PROCESS();
        CEP.TRC(SCCGWA, "DDOT5846 return!");
        Z_RET();
    }
    public void A000_INIT_PROCESS() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "DDB5846_AWA_5846>");
        DDB5846_AWA_5846 = (DDB5846_AWA_5846) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
    }
    public void B000_MAIN_PROCESS() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, "START  TIME:");
        JIBS_sdf = new SimpleDateFormat("yyyyMMddHHmmssSS");
        JIBS_date = new Date();
        WS_TS = JIBS_sdf.format(JIBS_date);
        CEP.TRC(SCCGWA, WS_TS);
        B100_CHECK_INPUT_DATA();
        B200_TRANS_DATA_PROC();
        CEP.TRC(SCCGWA, "END    TIME:");
        JIBS_sdf = new SimpleDateFormat("yyyyMMddHHmmssSS");
        JIBS_date = new Date();
        WS_TS = JIBS_sdf.format(JIBS_date);
        CEP.TRC(SCCGWA, WS_TS);
    }
    public void B100_CHECK_INPUT_DATA() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.FR_BV_AM);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.FR_BV_TP);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.FR_CARD);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.FR_AC);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.FR_PSBK);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.CHQ_TYPE);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.CHQ_NO);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.CHQ_ISDT);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.FR_CYCN);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.FR_CYEN);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.FR_CCY);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.FR_CYTP);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.FR_AMT);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.TO_BV_AM);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.TO_BV_TP);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.TO_CARD);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.TO_AC);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.FR_CREV);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.TO_CREV);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.TO_CCY);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.TO_CYTP);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.TO_ACCN);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.TO_ACEN);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.TO_AMT);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.EX_RATE);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.TICK_NO);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.EX_TIME);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.VAL_DATE);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.NRATV);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.REMARKS);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.PAY_TYPE);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.PSWD);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.PAY_PSWD);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.CHK_PSW);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.TRK_DAT2);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.TRK_DAT3);
        if (DDB5846_AWA_5846.FR_AC.trim().length() == 0 
            && DDB5846_AWA_5846.FR_CARD.trim().length() == 0) {
            WS_ERR_MSG = DDCMSG_ERROR_MSG.DD_FRAC_NO_M_INPUT;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        if (DDB5846_AWA_5846.FR_CCY.trim().length() == 0) {
            WS_ERR_MSG = DDCMSG_ERROR_MSG.DD_CCY_M_INPUT;
            WS_FLD_NO = DDB5846_AWA_5846.FR_CCY_NO;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        WS_ERR_MSG = DDCMSG_ERROR_MSG.DD_INPUT_DATA_ERR;
        S000_ERR_MSG_PROC_LAST();
    }
    public void B200_TRANS_DATA_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, DDCSCPLC);
        DDCSCPLC.FR_BV_AM = DDB5846_AWA_5846.FR_BV_AM;
        DDCSCPLC.FR_BV_TYPE = DDB5846_AWA_5846.FR_BV_TP;
        DDCSCPLC.FR_CARD = DDB5846_AWA_5846.FR_CARD;
        DDCSCPLC.FR_AC = DDB5846_AWA_5846.FR_AC;
        DDCSCPLC.FR_PSBK = DDB5846_AWA_5846.FR_PSBK;
        DDCSCPLC.CHQ_TYPE = DDB5846_AWA_5846.CHQ_TYPE;
        DDCSCPLC.CHQ_NO = DDB5846_AWA_5846.CHQ_NO;
        DDCSCPLC.CHQ_ISS_DATE = DDB5846_AWA_5846.CHQ_ISDT;
        DDCSCPLC.FR_AC_CNAME = DDB5846_AWA_5846.FR_CYCN;
        DDCSCPLC.FR_AC_ENAME = DDB5846_AWA_5846.FR_CYEN;
        DDCSCPLC.FR_CCY = DDB5846_AWA_5846.FR_CCY;
        DDCSCPLC.FR_CCY_TYPE = DDB5846_AWA_5846.FR_CYTP;
        DDCSCPLC.FR_AMT = DDB5846_AWA_5846.FR_AMT;
        DDCSCPLC.TO_BV_AM = DDB5846_AWA_5846.TO_BV_AM;
        DDCSCPLC.TO_BV_TYPE = DDB5846_AWA_5846.TO_BV_TP;
        DDCSCPLC.TO_CARD = DDB5846_AWA_5846.TO_CARD;
        DDCSCPLC.TO_AC = DDB5846_AWA_5846.TO_AC;
        DDCSCPLC.FR_CREV_NO = DDB5846_AWA_5846.FR_CREV;
        DDCSCPLC.TO_CREV_NO = DDB5846_AWA_5846.TO_CREV;
        DDCSCPLC.TO_CCY = DDB5846_AWA_5846.TO_CCY;
        DDCSCPLC.TO_CCY_TYPE = DDB5846_AWA_5846.TO_CYTP;
        DDCSCPLC.TO_AC_CNAME = DDB5846_AWA_5846.TO_ACCN;
        DDCSCPLC.TO_AC_ENAME = DDB5846_AWA_5846.TO_ACEN;
        DDCSCPLC.TO_AMT = DDB5846_AWA_5846.TO_AMT;
        DDCSCPLC.EX_RATE = DDB5846_AWA_5846.EX_RATE;
        DDCSCPLC.TICK_NO = DDB5846_AWA_5846.TICK_NO;
        DDCSCPLC.EX_TIME = DDB5846_AWA_5846.EX_TIME;
        DDCSCPLC.VAL_DATE = DDB5846_AWA_5846.VAL_DATE;
        DDCSCPLC.TX_RMK = DDB5846_AWA_5846.NRATV;
        DDCSCPLC.REMARKS = DDB5846_AWA_5846.REMARKS;
        DDCSCPLC.PAY_TYPE = DDB5846_AWA_5846.PAY_TYPE;
        DDCSCPLC.PSWD = DDB5846_AWA_5846.PSWD;
        DDCSCPLC.PAY_PSWD = DDB5846_AWA_5846.PAY_PSWD;
        DDCSCPLC.CHK_PSW = 'P';
        DDCSCPLC.FR_PSBK_SEQ = DDB5846_AWA_5846.FR_P_SEQ;
        DDCSCPLC.TO_PSBK_SEQ = DDB5846_AWA_5846.TO_P_SEQ;
        DDCSCPLC.CHK_PSW = DDB5846_AWA_5846.CHK_PSW;
        DDCSCPLC.TRK2_DAT = DDB5846_AWA_5846.TRK_DAT2;
        DDCSCPLC.TRK3_DAT = DDB5846_AWA_5846.TRK_DAT3;
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.FR_P_SEQ);
        CEP.TRC(SCCGWA, DDB5846_AWA_5846.TO_P_SEQ);
        CEP.TRC(SCCGWA, DDCSCPLC.FR_BV_AM);
        CEP.TRC(SCCGWA, DDCSCPLC.FR_BV_TYPE);
        CEP.TRC(SCCGWA, DDCSCPLC.FR_CARD);
        CEP.TRC(SCCGWA, DDCSCPLC.FR_AC);
        CEP.TRC(SCCGWA, DDCSCPLC.FR_PSBK);
        CEP.TRC(SCCGWA, DDCSCPLC.CHQ_TYPE);
        CEP.TRC(SCCGWA, DDCSCPLC.CHQ_NO);
        CEP.TRC(SCCGWA, DDCSCPLC.CHQ_ISS_DATE);
        CEP.TRC(SCCGWA, DDCSCPLC.FR_AC_CNAME);
        CEP.TRC(SCCGWA, DDCSCPLC.FR_AC_ENAME);
        CEP.TRC(SCCGWA, DDCSCPLC.FR_CCY);
        CEP.TRC(SCCGWA, DDCSCPLC.FR_CCY_TYPE);
        CEP.TRC(SCCGWA, DDCSCPLC.FR_AMT);
        CEP.TRC(SCCGWA, DDCSCPLC.TO_BV_AM);
        CEP.TRC(SCCGWA, DDCSCPLC.TO_BV_TYPE);
        CEP.TRC(SCCGWA, DDCSCPLC.TO_CARD);
        CEP.TRC(SCCGWA, DDCSCPLC.TO_AC);
        CEP.TRC(SCCGWA, DDCSCPLC.FR_CREV_NO);
        CEP.TRC(SCCGWA, DDCSCPLC.TO_CREV_NO);
        CEP.TRC(SCCGWA, DDCSCPLC.TO_CCY);
        CEP.TRC(SCCGWA, DDCSCPLC.TO_CCY_TYPE);
        CEP.TRC(SCCGWA, DDCSCPLC.TO_AC_CNAME);
        CEP.TRC(SCCGWA, DDCSCPLC.TO_AC_ENAME);
        CEP.TRC(SCCGWA, DDCSCPLC.TO_AMT);
        CEP.TRC(SCCGWA, DDCSCPLC.EX_RATE);
        CEP.TRC(SCCGWA, DDCSCPLC.TICK_NO);
        CEP.TRC(SCCGWA, DDCSCPLC.EX_TIME);
        CEP.TRC(SCCGWA, DDCSCPLC.VAL_DATE);
        CEP.TRC(SCCGWA, DDCSCPLC.TX_RMK);
        CEP.TRC(SCCGWA, DDCSCPLC.REMARKS);
        CEP.TRC(SCCGWA, DDCSCPLC.PAY_TYPE);
        CEP.TRC(SCCGWA, DDCSCPLC.PSWD);
        CEP.TRC(SCCGWA, DDCSCPLC.PAY_PSWD);
        CEP.TRC(SCCGWA, DDCSCPLC.CHK_PSW);
        CEP.TRC(SCCGWA, DDCSCPLC.TRK2_DAT);
        CEP.TRC(SCCGWA, DDCSCPLC.TRK3_DAT);
        S000_CALL_DDZSCPLC();
    }
    public void S000_CALL_DDZSCPLC() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "DD-S-CP-COLSE", DDCSCPLC);
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG);
    }
    public void S000_ERR_MSG_PROC_CONTINUE() throws IOException,SQLException,Exception {
        CEP.ERRC(SCCGWA, WS_ERR_MSG, WS_FLD_NO);
    }
    public void S000_ERR_MSG_PROC_LAST() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
