package com.hisun.DD;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;

import java.io.IOException;
import java.sql.SQLException;

public class DDOT1110 {
    short WS_FLD_NO = 0;
    String WS_ERR_MSG = " ";
    DDCMSG_ERROR_MSG DDCMSG_ERROR_MSG = new DDCMSG_ERROR_MSG();
    SCCMSG SCCMSG = new SCCMSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    DDCSZMQO DDCSZMQO = new DDCSZMQO();
    SCCGWA SCCGWA;
    DDB1110_AWA_1110 DDB1110_AWA_1110;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROCESS();
        B000_MAIN_PROCESS();
        CEP.TRC(SCCGWA, "DDOT1110 return!");
        Z_RET();
    }
    public void A000_INIT_PROCESS() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "DDB1110_AWA_1110>");
        DDB1110_AWA_1110 = (DDB1110_AWA_1110) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
    }
    public void B000_MAIN_PROCESS() throws IOException,SQLException,Exception {
        B100_CHECK_INPUT_DATA();
        B200_TRANS_DATA_PROC();
    }
    public void B100_CHECK_INPUT_DATA() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, DDB1110_AWA_1110.SOURCE);
        CEP.TRC(SCCGWA, DDB1110_AWA_1110.FR_BV_TP);
        CEP.TRC(SCCGWA, DDB1110_AWA_1110.FR_CARD);
        CEP.TRC(SCCGWA, DDB1110_AWA_1110.FR_ACNO);
        CEP.TRC(SCCGWA, DDB1110_AWA_1110.FR_ACNM);
        CEP.TRC(SCCGWA, DDB1110_AWA_1110.FR_ACBAL);
        CEP.TRC(SCCGWA, DDB1110_AWA_1110.FR_PBNO);
        CEP.TRC(SCCGWA, DDB1110_AWA_1110.CHQ_TYP);
        CEP.TRC(SCCGWA, DDB1110_AWA_1110.CHQ_NO);
        CEP.TRC(SCCGWA, DDB1110_AWA_1110.CHQ_ISDT);
        CEP.TRC(SCCGWA, DDB1110_AWA_1110.CHQ_PSW);
        CEP.TRC(SCCGWA, DDB1110_AWA_1110.FR_DRMTH);
        CEP.TRC(SCCGWA, DDB1110_AWA_1110.FR_PSWD);
        CEP.TRC(SCCGWA, DDB1110_AWA_1110.FR_CCY);
        CEP.TRC(SCCGWA, DDB1110_AWA_1110.FR_CYTP);
        CEP.TRC(SCCGWA, DDB1110_AWA_1110.TR_AMT);
        CEP.TRC(SCCGWA, DDB1110_AWA_1110.VAL_DT);
        CEP.TRC(SCCGWA, DDB1110_AWA_1110.DIRECT);
        CEP.TRC(SCCGWA, DDB1110_AWA_1110.TO_BV_TP);
        CEP.TRC(SCCGWA, DDB1110_AWA_1110.TO_CARD);
        CEP.TRC(SCCGWA, DDB1110_AWA_1110.TO_ACNO);
        CEP.TRC(SCCGWA, DDB1110_AWA_1110.TO_ACNM);
        CEP.TRC(SCCGWA, DDB1110_AWA_1110.TO_PBNO);
        CEP.TRC(SCCGWA, DDB1110_AWA_1110.TR_RSN);
        CEP.TRC(SCCGWA, DDB1110_AWA_1110.TR_DESC);
        CEP.TRC(SCCGWA, DDB1110_AWA_1110.TR_RMK);
        CEP.TRC(SCCGWA, DDB1110_AWA_1110.AGEN_FLG);
        CEP.TRC(SCCGWA, DDB1110_AWA_1110.TO_CCY);
        CEP.TRC(SCCGWA, DDB1110_AWA_1110.TO_CYTP);
        if (DDB1110_AWA_1110.FR_ACNO.trim().length() == 0 
            && DDB1110_AWA_1110.FR_CARD.trim().length() == 0) {
            CEP.ERR(SCCGWA, DDCMSG_ERROR_MSG.DD_FRAC_NO_M_INPUT);
        }
        if (DDB1110_AWA_1110.FR_CCY.trim().length() == 0) {
            CEP.ERR(SCCGWA, DDCMSG_ERROR_MSG.DD_CCY_M_INPUT);
        }
        if (DDB1110_AWA_1110.TR_AMT == 0) {
            CEP.ERR(SCCGWA, DDCMSG_ERROR_MSG.DD_TRF_AMT_M_INPUT);
        }
        if (DDB1110_AWA_1110.TO_ACNO.trim().length() == 0 
            && DDB1110_AWA_1110.TO_CARD.trim().length() == 0) {
            CEP.ERR(SCCGWA, DDCMSG_ERROR_MSG.DD_TOAC_NO_M_INPUT);
        }
    }
    public void B200_TRANS_DATA_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, DDCSZMQO);
        DDCSZMQO.SOURCE = DDB1110_AWA_1110.SOURCE;
        DDCSZMQO.FR_BV_TP = DDB1110_AWA_1110.FR_BV_TP;
        DDCSZMQO.FR_CARD = DDB1110_AWA_1110.FR_CARD;
        DDCSZMQO.FR_ACNO = DDB1110_AWA_1110.FR_ACNO;
        DDCSZMQO.FR_ACNM = DDB1110_AWA_1110.FR_ACNM;
        DDCSZMQO.FR_ACBAL = DDB1110_AWA_1110.FR_ACBAL;
        DDCSZMQO.FR_PBNO = DDB1110_AWA_1110.FR_PBNO;
        DDCSZMQO.CHQ_TYP = DDB1110_AWA_1110.CHQ_TYP;
        DDCSZMQO.CHQ_NO = DDB1110_AWA_1110.CHQ_NO;
        DDCSZMQO.CHQ_ISDT = DDB1110_AWA_1110.CHQ_ISDT;
        DDCSZMQO.CHQ_PSW = DDB1110_AWA_1110.CHQ_PSW;
        DDCSZMQO.FR_DRMTH = DDB1110_AWA_1110.FR_DRMTH;
        DDCSZMQO.FR_PSWD = DDB1110_AWA_1110.FR_PSWD;
        DDCSZMQO.FR_CCY = DDB1110_AWA_1110.FR_CCY;
        DDCSZMQO.FR_CYTP = DDB1110_AWA_1110.FR_CYTP;
        DDCSZMQO.TR_AMT = DDB1110_AWA_1110.TR_AMT;
        DDCSZMQO.VAL_DT = DDB1110_AWA_1110.VAL_DT;
        DDCSZMQO.DIRECT = DDB1110_AWA_1110.DIRECT;
        DDCSZMQO.TO_BV_TP = DDB1110_AWA_1110.TO_BV_TP;
        DDCSZMQO.TO_CARD = DDB1110_AWA_1110.TO_CARD;
        DDCSZMQO.TO_ACNO = DDB1110_AWA_1110.TO_ACNO;
        DDCSZMQO.TO_ACNM = DDB1110_AWA_1110.TO_ACNM;
        DDCSZMQO.TO_PBNO = DDB1110_AWA_1110.TO_PBNO;
        DDCSZMQO.TR_RSN = DDB1110_AWA_1110.TR_RSN;
        DDCSZMQO.TR_DESC = DDB1110_AWA_1110.TR_DESC;
        DDCSZMQO.TR_RMK = DDB1110_AWA_1110.TR_RMK;
        DDCSZMQO.AGEN_FLG = DDB1110_AWA_1110.AGEN_FLG;
        DDCSZMQO.TO_CCY = DDB1110_AWA_1110.TO_CCY;
        DDCSZMQO.TO_CYTP = DDB1110_AWA_1110.TO_CYTP;
        DDCSZMQO.ID_TYP = DDB1110_AWA_1110.ID_TYP;
        DDCSZMQO.ID_NO = DDB1110_AWA_1110.ID_NO;
        DDCSZMQO.CI_NM = DDB1110_AWA_1110.CI_NM;
        DDCSZMQO.PHONE = DDB1110_AWA_1110.PHONE;
        CEP.TRC(SCCGWA, DDCSZMQO.SOURCE);
        CEP.TRC(SCCGWA, DDCSZMQO.FR_BV_TP);
        CEP.TRC(SCCGWA, DDCSZMQO.FR_CARD);
        CEP.TRC(SCCGWA, DDCSZMQO.FR_ACNO);
        CEP.TRC(SCCGWA, DDCSZMQO.FR_ACNM);
        CEP.TRC(SCCGWA, DDCSZMQO.FR_ACBAL);
        CEP.TRC(SCCGWA, DDCSZMQO.FR_PBNO);
        CEP.TRC(SCCGWA, DDCSZMQO.CHQ_TYP);
        CEP.TRC(SCCGWA, DDCSZMQO.CHQ_NO);
        CEP.TRC(SCCGWA, DDCSZMQO.CHQ_ISDT);
        CEP.TRC(SCCGWA, DDCSZMQO.CHQ_PSW);
        CEP.TRC(SCCGWA, DDCSZMQO.FR_DRMTH);
        CEP.TRC(SCCGWA, DDCSZMQO.FR_PSWD);
        CEP.TRC(SCCGWA, DDCSZMQO.FR_CCY);
        CEP.TRC(SCCGWA, DDCSZMQO.FR_CYTP);
        CEP.TRC(SCCGWA, DDCSZMQO.TR_AMT);
        CEP.TRC(SCCGWA, DDCSZMQO.VAL_DT);
        CEP.TRC(SCCGWA, DDCSZMQO.DIRECT);
        CEP.TRC(SCCGWA, DDCSZMQO.TO_BV_TP);
        CEP.TRC(SCCGWA, DDCSZMQO.TO_CARD);
        CEP.TRC(SCCGWA, DDCSZMQO.TO_ACNO);
        CEP.TRC(SCCGWA, DDCSZMQO.TO_ACNM);
        CEP.TRC(SCCGWA, DDCSZMQO.TO_PBNO);
        CEP.TRC(SCCGWA, DDCSZMQO.TR_RSN);
        CEP.TRC(SCCGWA, DDCSZMQO.TR_DESC);
        CEP.TRC(SCCGWA, DDCSZMQO.TR_RMK);
        CEP.TRC(SCCGWA, DDCSZMQO.AGEN_FLG);
        CEP.TRC(SCCGWA, DDCSZMQO.TO_CCY);
        CEP.TRC(SCCGWA, DDCSZMQO.TO_CYTP);
        S000_CALL_DDZSZMQO();
    }
    public void S000_CALL_DDZSZMQO() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "DD-SVR-ZMQO", DDCSZMQO);
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
