package com.hisun.DD;

public class DDZSLNPY_WS_OUPUT_DATA {
    DDZSLNPY_WS_PAGE_INF WS_PAGE_INF = new DDZSLNPY_WS_PAGE_INF();
    DDZSLNPY_WS_OUTPUT_DATA_INF WS_OUTPUT_DATA_INF = new DDZSLNPY_WS_OUTPUT_DATA_INF();
}
