package com.hisun.DD;

import com.hisun.SC.*;
import com.hisun.DC.*;
import com.hisun.CI.*;
import com.hisun.BP.*;

import java.io.IOException;
import java.sql.SQLException;

public class DDZUZFMM {
    DBParm DDTCHQP_RD;
    DBParm DCTIAMST_RD;
    int JIBS_tmp_int;
    DBParm DCTSPAC_RD;
    String K_OBJ_SYSTEM = "ZFMM";
    String K_SERV_CODE = "ZFX104";
    String K_OBJ_SYSTEM_NCB = "ESBP";
    String K_SERV_CODE_NCB = "6001200000301";
    String WS_ERR_MSG = " ";
    short WS_FLD_NO = 0;
    String WS_P_AMOUNT_D = " ";
    DDZUZFMM_REDEFINES4 REDEFINES4 = new DDZUZFMM_REDEFINES4();
    DDZUZFMM_WS_DATA_TO_SCZTPCL WS_DATA_TO_SCZTPCL = new DDZUZFMM_WS_DATA_TO_SCZTPCL();
    char WS_CHQP_FLG = ' ';
    DDCMSG_ERROR_MSG DDCMSG_ERROR_MSG = new DDCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    SCCMPAG SCCMPAG = new SCCMPAG();
    SCCFMT SCCFMT = new SCCFMT();
    SCCTPCL SCCTPCL = new SCCTPCL();
    DDRCHQP DDRCHQP = new DDRCHQP();
    DCRSPAC DCRSPAC = new DCRSPAC();
    DCRIAMST DCRIAMST = new DCRIAMST();
    CICQACAC CICQACAC = new CICQACAC();
    SCCTSSC SCCTSSC = new SCCTSSC();
    BPRORGM BPRPORGM = new BPRORGM();
    BPCRORGM BPCRORGM = new BPCRORGM();
    int WS_CHQ_ISSU_DATE = 0;
    SCCGWA SCCGWA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    SCCGSCA_SC_AREA SCCGSCA_SC_AREA;
    SCCGAPV SCCGAPV;
    DDCUZFMM DDCUZFMM;
    public void MP(SCCGWA SCCGWA, DDCUZFMM DDCUZFMM) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        this.DDCUZFMM = DDCUZFMM;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "DDZUZFMM return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B010_CHECK_INPUT();
        B020_PROC_MAIN();
    }
    public void B010_CHECK_INPUT() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, DDCUZFMM.INPUT.AC_NO);
        CEP.TRC(SCCGWA, DDCUZFMM.STD_AC);
        CEP.TRC(SCCGWA, DDCUZFMM.INPUT.CHQ_TYP);
        CEP.TRC(SCCGWA, DDCUZFMM.INPUT.CHQ_ISSU_DATE);
        CEP.TRC(SCCGWA, DDCUZFMM.INPUT.CHQ_NO);
        CEP.TRC(SCCGWA, DDCUZFMM.INPUT.AMT);
        CEP.TRC(SCCGWA, DDCUZFMM.INPUT.CHQ_PSW);
        if (DDCUZFMM.STD_AC.trim().length() == 0) {
            WS_ERR_MSG = DDCMSG_ERROR_MSG.DD_AC_NO_M_INPUT;
            S000_ERR_MSG_PROC();
        }
        if (DDCUZFMM.INPUT.CHQ_TYP == ' ') {
            WS_ERR_MSG = DDCMSG_ERROR_MSG.DD_CHQ_TYP_M_INPUT;
            S000_ERR_MSG_PROC();
        }
        if (DDCUZFMM.INPUT.CHQ_ISSU_DATE == 0) {
            WS_ERR_MSG = DDCMSG_ERROR_MSG.DD_CHQ_ISSU_DT_M_INPUT;
            S000_ERR_MSG_PROC();
        }
        if (DDCUZFMM.INPUT.CHQ_NO.trim().length() == 0) {
            WS_ERR_MSG = DDCMSG_ERROR_MSG.DD_CHQ_MUST_INP;
            S000_ERR_MSG_PROC();
        }
        if (DDCUZFMM.INPUT.AMT == 0 
            && DDCUZFMM.INPUT.CHQ_PSW.trim().length() > 0) {
            WS_ERR_MSG = DDCMSG_ERROR_MSG.DD_AMT_MST_IPT;
            S000_ERR_MSG_PROC();
        }
    }
    public void B020_PROC_MAIN() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, DDRCHQP);
        IBS.init(SCCGWA, CICQACAC);
        CICQACAC.FUNC = 'R';
        CICQACAC.DATA.AGR_NO = DDCUZFMM.STD_AC;
        S000_CALL_CIZQACAC();
        CEP.TRC(SCCGWA, CICQACAC.O_DATA.O_ACAC_DATA.O_ACAC_NO);
        DDRCHQP.KEY.AC = CICQACAC.O_DATA.O_ACAC_DATA.O_ACAC_NO;
        WS_CHQ_ISSU_DATE = DDCUZFMM.INPUT.CHQ_ISSU_DATE;
        CEP.TRC(SCCGWA, DDRCHQP.KEY.AC);
        CEP.TRC(SCCGWA, WS_CHQ_ISSU_DATE);
        T000_FIRST_DDTCHQP_PROC();
        CEP.TRC(SCCGWA, DDRCHQP.KEY.STS);
        CEP.TRC(SCCGWA, DDRCHQP.KEY.STR_DT);
        if (WS_CHQP_FLG == 'Y') {
            DDCUZFMM.OUTPUT_DATE.CHK_RESULT = '4';
            if (DDCUZFMM.INPUT.CHQ_PSW.trim().length() > 0) {
                B030_CHK_INFORM_ZFMM_NCB();
            } else {
                CEP.ERR(SCCGWA, DDCMSG_ERROR_MSG.DD_CHQ_PAY_PSW_INPUT);
            }
        } else if (WS_CHQP_FLG == 'N') {
            WS_CHQP_FLG = ' ';
            T000_STARTBR_DDTCHQP_PROC();
            if (WS_CHQP_FLG == 'Y') {
                DDCUZFMM.OUTPUT_DATE.CHK_RESULT = '4';
                if (DDCUZFMM.INPUT.CHQ_PSW.trim().length() > 0) {
                    B030_CHK_INFORM_ZFMM_NCB();
                } else {
                    CEP.ERR(SCCGWA, DDCMSG_ERROR_MSG.DD_CHQ_PAY_PSW_INPUT);
                }
            } else {
                DDCUZFMM.OUTPUT_DATE.CHK_RESULT = '3';
            }
        } else {
            DDCUZFMM.OUTPUT_DATE.CHK_RESULT = '3';
        }
    }
    public void T000_FIRST_DDTCHQP_PROC() throws IOException,SQLException,Exception {
        DDTCHQP_RD = new DBParm();
        DDTCHQP_RD.TableName = "DDTCHQP";
        DDTCHQP_RD.where = "AC = :DDRCHQP.KEY.AC "
            + "AND STR_DT <= :WS_CHQ_ISSU_DATE "
            + "AND ( STS = '2' "
            + "OR STS = '5' )";
        DDTCHQP_RD.fst = true;
        DDTCHQP_RD.order = "STR_DT";
        IBS.READ(SCCGWA, DDRCHQP, this, DDTCHQP_RD);
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.DBIO_FLG);
        if (SCCGWA.COMM_AREA.DBIO_FLG == '0') {
            WS_CHQP_FLG = 'Y';
        } else if (SCCGWA.COMM_AREA.DBIO_FLG == '1') {
            WS_CHQP_FLG = 'N';
        } else {
            IBS.init(SCCGWA, SCCEXCP);
            SCCEXCP.MSG_TEXT.MSG_TEXT_D.TABLE_NAME = "DDTCHQP";
            SCCEXCP.MSG_TEXT.SYS_INFO = IBS.CLS2CPY(SCCGWA, SCCEXCP.MSG_TEXT.MSG_TEXT_D);
            SCCEXCP.MSG_TEXT.MSG_TEXT_D.DB_FUNC = "WRITE";
            B_DB_EXCP();
        }
    }
    public void T000_STARTBR_DDTCHQP_PROC() throws IOException,SQLException,Exception {
        DDTCHQP_RD = new DBParm();
        DDTCHQP_RD.TableName = "DDTCHQP";
        DDTCHQP_RD.where = "AC = :DDRCHQP.KEY.AC "
            + "AND STR_DT <= :WS_CHQ_ISSU_DATE "
            + "AND STOP_DT > :WS_CHQ_ISSU_DATE "
            + "AND ( STS = '6' "
            + "OR STS = '3' "
            + "OR STS = '4' )";
        DDTCHQP_RD.fst = true;
        IBS.READ(SCCGWA, DDRCHQP, this, DDTCHQP_RD);
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.DBIO_FLG);
        if (SCCGWA.COMM_AREA.DBIO_FLG == '0') {
            WS_CHQP_FLG = 'Y';
        } else {
            WS_CHQP_FLG = 'N';
        }
    }
    public void S000_CALL_CIZQACAC() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "CI-INQ-ACAC", CICQACAC);
        if (CICQACAC.RC.RC_CODE != 0) {
            WS_ERR_MSG = IBS.CLS2CPY(SCCGWA, CICQACAC.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void T000_READ_DCTIAMST() throws IOException,SQLException,Exception {
        DCTIAMST_RD = new DBParm();
        DCTIAMST_RD.TableName = "DCTIAMST";
        DCTIAMST_RD.col = "VIA_AC,VIA_FLG";
        IBS.READ(SCCGWA, DCRIAMST, DCTIAMST_RD);
    }
    public void B030_CHK_INFORM_ZFMM_NCB() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, SCCTPCL);
        SCCTPCL.SERV_AREA.OBJ_SYSTEM = K_OBJ_SYSTEM_NCB;
        SCCTPCL.SERV_AREA.SERV_CODE = K_SERV_CODE_NCB;
        SCCTPCL.SERV_AREA.SERV_TYPE = 'Y';
        SCCTPCL.INP_AREA.BD_PASSWORD_CHK.PC_TR_NO = "T001";
        SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PASSWORD_CHK);
        IBS.init(SCCGWA, BPRPORGM);
        BPRPORGM.KEY.IBS_AC_BK = SCCGWA.COMM_AREA.TR_BANK;
        BPRPORGM.KEY.BR = SCCGWA.COMM_AREA.BR_DP.TR_BRANCH;
        BPCRORGM.INFO.FUNC = 'R';
        BPCRORGM.INFO.POINTER = BPRPORGM;
        BPCRORGM.INFO.LEN = 1252;
        CEP.TRC(SCCGWA, BPRPORGM.KEY.IBS_AC_BK);
        CEP.TRC(SCCGWA, BPRPORGM.KEY.BR);
        S000_CALL_BPZRORGM();
        if (BPRPORGM.TYPE.equalsIgnoreCase("12")) {
            SCCTPCL.INP_AREA.BD_PASSWORD_CHK.PC_SUP_BR = BPRPORGM.SUPR_BR;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PASSWORD_CHK);
        }
        CEP.TRC(SCCGWA, BPRPORGM.TYPE);
        CEP.TRC(SCCGWA, BPRPORGM.SUPR_BR);
        if ((SCCGWA.COMM_AREA.CHNL.equalsIgnoreCase("101") 
            || SCCGWA.COMM_AREA.CHNL.equalsIgnoreCase("10101") 
            || SCCGWA.COMM_AREA.CHNL.equalsIgnoreCase("10102"))) {
            SCCTPCL.INP_AREA.BD_PASSWORD_CHK.PC_CHNL_FLG = "0";
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PASSWORD_CHK);
        } else {
            SCCTPCL.INP_AREA.BD_PASSWORD_CHK.PC_CHNL_FLG = "1";
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PASSWORD_CHK);
        }
        SCCTPCL.INP_AREA.BD_PASSWORD_CHK.PC_WKSTATION = "005";
        SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PASSWORD_CHK);
        SCCTPCL.INP_AREA.BD_PASSWORD_CHK.PC_TR_CD = "07";
        SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PASSWORD_CHK);
        if ("043999".trim().length() == 0) SCCTPCL.INP_AREA.BD_PASSWORD_CHK.PC_HQT_BANK = 0;
        else SCCTPCL.INP_AREA.BD_PASSWORD_CHK.PC_HQT_BANK = Integer.parseInt("043999");
        SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PASSWORD_CHK);
        SCCTPCL.INP_AREA.BD_PASSWORD_CHK.PC_PAY_AC_NO = DDCUZFMM.STD_AC;
        SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PASSWORD_CHK);
        CEP.TRC(SCCGWA, SCCTPCL.INP_AREA.BD_PASSWORD_CHK.PC_PAY_AC_NO);
        SCCTPCL.INP_AREA.BD_PASSWORD_CHK.PC_BV_TYP = "0000";
        SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PASSWORD_CHK);
        if (DDCUZFMM.INPUT.CHQ_TYP == '1' 
            || DDCUZFMM.INPUT.CHQ_TYP == '2' 
            || DDCUZFMM.INPUT.CHQ_TYP == '3') {
            if (SCCTPCL.INP_AREA.BD_PASSWORD_CHK.PC_BV_TYP == null) SCCTPCL.INP_AREA.BD_PASSWORD_CHK.PC_BV_TYP = "";
            JIBS_tmp_int = SCCTPCL.INP_AREA.BD_PASSWORD_CHK.PC_BV_TYP.length();
            for (int i=0;i<4-JIBS_tmp_int;i++) SCCTPCL.INP_AREA.BD_PASSWORD_CHK.PC_BV_TYP += " ";
            SCCTPCL.INP_AREA.BD_PASSWORD_CHK.PC_BV_TYP = SCCTPCL.INP_AREA.BD_PASSWORD_CHK.PC_BV_TYP.substring(0, 4 - 1) + "1" + SCCTPCL.INP_AREA.BD_PASSWORD_CHK.PC_BV_TYP.substring(4 + 1 - 1);
        }
        SCCTPCL.INP_AREA.BD_PASSWORD_CHK.PC_CHK_DT = DDCUZFMM.INPUT.CHQ_ISSU_DATE;
        SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PASSWORD_CHK);
        if (DDCUZFMM.INPUT.CHQ_NO == null) DDCUZFMM.INPUT.CHQ_NO = "";
        JIBS_tmp_int = DDCUZFMM.INPUT.CHQ_NO.length();
        for (int i=0;i<16-JIBS_tmp_int;i++) DDCUZFMM.INPUT.CHQ_NO += " ";
        SCCTPCL.INP_AREA.BD_PASSWORD_CHK.PC_BV_NO = DDCUZFMM.INPUT.CHQ_NO.substring(9 - 1, 9 + 8 - 1);
        SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PASSWORD_CHK);
        CEP.TRC(SCCGWA, SCCTPCL.INP_AREA.BD_PASSWORD_CHK.PC_BV_NO);
        SCCTPCL.INP_AREA.BD_PASSWORD_CHK.PC_AMT = DDCUZFMM.INPUT.AMT;
        SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PASSWORD_CHK);
        CEP.TRC(SCCGWA, SCCTPCL.INP_AREA.BD_PASSWORD_CHK.PC_AMT);
        SCCTPCL.INP_AREA.BD_PASSWORD_CHK.PC_PASSWORD = DDCUZFMM.INPUT.CHQ_PSW;
        SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PASSWORD_CHK);
        SCCTPCL.INP_AREA.SERV_DATA_LEN = 123;
        if (!SCCGWA.COMM_AREA.BSP_FLG.equalsIgnoreCase("BSP") 
            && !SCCGWA.COMM_AREA.CHNL.equalsIgnoreCase("BAT")) {
            S000_CALL_SCZTPCL();
            CEP.TRC(SCCGWA, SCCTPCL.INP_AREA.BD_PASSWORD_CHK.PC_CHECK_FLG);
            if (SCCTPCL.INP_AREA.BD_PASSWORD_CHK.PC_CHECK_FLG == 'N') {
                WS_ERR_MSG = DDCMSG_ERROR_MSG.DD_CHQ_PAY_PSW_ERR;
                S000_ERR_MSG_PROC();
            }
            if (SCCTPCL.INP_AREA.SERV_DATA == null) SCCTPCL.INP_AREA.SERV_DATA = "";
            JIBS_tmp_int = SCCTPCL.INP_AREA.SERV_DATA.length();
            for (int i=0;i<10700-JIBS_tmp_int;i++) SCCTPCL.INP_AREA.SERV_DATA += " ";
            SCCTPCL.INP_AREA.SERV_DATA = "Y" + SCCTPCL.INP_AREA.SERV_DATA.substring(1);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_CSIF_NOTICE);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_BVMS_INQ);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_BH_FILE_SEND);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_BH_FILE_ECIF);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_AC_CHG_INF);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_ACGL_GL0002);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_PASSWORD_CHK);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_SMS_INFO);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_ECIF_SG0001);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_CHG_NOTICE);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_ACGL_GL0001);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_ECIF_AC0001);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_LOAN_NOTICE);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.SN_SMS_NOTICE);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_ECIF_AC0002);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.CC_CHANGE_CARD);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.SC_SCF_NOTICE);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_ECIF_AC0003);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_IBIL_NOTICE);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_BROADCAST);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_CASH_CHG);
        }
        CEP.TRC(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA);
        if (SCCTPCL.INP_AREA.SERV_DATA == null) SCCTPCL.INP_AREA.SERV_DATA = "";
        JIBS_tmp_int = SCCTPCL.INP_AREA.SERV_DATA.length();
        for (int i=0;i<10700-JIBS_tmp_int;i++) SCCTPCL.INP_AREA.SERV_DATA += " ";
        CEP.TRC(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA.substring(0, 1));
        if (SCCTPCL.INP_AREA.SERV_DATA == null) SCCTPCL.INP_AREA.SERV_DATA = "";
        JIBS_tmp_int = SCCTPCL.INP_AREA.SERV_DATA.length();
        for (int i=0;i<10700-JIBS_tmp_int;i++) SCCTPCL.INP_AREA.SERV_DATA += " ";
        if (SCCTPCL.INP_AREA.SERV_DATA.substring(0, 1).equalsIgnoreCase("Y")) {
            DDCUZFMM.OUTPUT_DATE.CHK_RESULT = '1';
        } else {
            DDCUZFMM.OUTPUT_DATE.CHK_RESULT = '2';
        }
    }
    public void B030_CHK_INFORM_ZFMM() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, SCCTPCL);
        SCCTPCL.SERV_AREA.OBJ_SYSTEM = K_OBJ_SYSTEM;
        SCCTPCL.SERV_AREA.SERV_CODE = K_SERV_CODE;
        SCCTPCL.SERV_AREA.SERV_TYPE = 'Y';
        WS_DATA_TO_SCZTPCL.WS_AC_NO = DDCUZFMM.STD_AC;
        WS_DATA_TO_SCZTPCL.WS_TYPE = "" + DDCUZFMM.INPUT.CHQ_TYP;
        JIBS_tmp_int = WS_DATA_TO_SCZTPCL.WS_TYPE.length();
        for (int i=0;i<1-JIBS_tmp_int;i++) WS_DATA_TO_SCZTPCL.WS_TYPE = "0" + WS_DATA_TO_SCZTPCL.WS_TYPE;
        WS_DATA_TO_SCZTPCL.WS_ISSU_DATE = DDCUZFMM.INPUT.CHQ_ISSU_DATE;
        WS_DATA_TO_SCZTPCL.WS_CHQ_NO = DDCUZFMM.INPUT.CHQ_NO;
        WS_DATA_TO_SCZTPCL.WS_CHQ_AMT = DDCUZFMM.INPUT.AMT;
        WS_DATA_TO_SCZTPCL.WS_CHQ_PSW = DDCUZFMM.INPUT.CHQ_PSW;
        CEP.TRC(SCCGWA, WS_DATA_TO_SCZTPCL);
        SCCTPCL.INP_AREA.SERV_DATA_LEN = 104;
        SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, WS_DATA_TO_SCZTPCL);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_CSIF_NOTICE);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_BVMS_INQ);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_BH_FILE_SEND);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_BH_FILE_ECIF);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_AC_CHG_INF);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_ACGL_GL0002);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_PASSWORD_CHK);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_SMS_INFO);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_ECIF_SG0001);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_CHG_NOTICE);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_ACGL_GL0001);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_ECIF_AC0001);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_LOAN_NOTICE);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.SN_SMS_NOTICE);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_ECIF_AC0002);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.CC_CHANGE_CARD);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.SC_SCF_NOTICE);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_ECIF_AC0003);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_IBIL_NOTICE);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_BROADCAST);
        IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_CASH_CHG);
        if (!SCCGWA.COMM_AREA.BSP_FLG.equalsIgnoreCase("BSP") 
            && !SCCGWA.COMM_AREA.CHNL.equalsIgnoreCase("BAT")) {
            S000_CALL_SCZTPCL();
        }
        CEP.TRC(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA);
        if (SCCTPCL.INP_AREA.SERV_DATA == null) SCCTPCL.INP_AREA.SERV_DATA = "";
        JIBS_tmp_int = SCCTPCL.INP_AREA.SERV_DATA.length();
        for (int i=0;i<10700-JIBS_tmp_int;i++) SCCTPCL.INP_AREA.SERV_DATA += " ";
        CEP.TRC(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA.substring(0, 1));
        if (SCCTPCL.INP_AREA.SERV_DATA == null) SCCTPCL.INP_AREA.SERV_DATA = "";
        JIBS_tmp_int = SCCTPCL.INP_AREA.SERV_DATA.length();
        for (int i=0;i<10700-JIBS_tmp_int;i++) SCCTPCL.INP_AREA.SERV_DATA += " ";
        if (!SCCTPCL.INP_AREA.SERV_DATA.substring(0, 1).equalsIgnoreCase("Y")) {
            IBS.init(SCCGWA, SCCTPCL);
            IBS.init(SCCGWA, DCRSPAC);
            DCRSPAC.KEY.FREE_AC = DDCUZFMM.STD_AC;
            DCTSPAC_RD = new DBParm();
            DCTSPAC_RD.TableName = "DCTSPAC";
            DCTSPAC_RD.fst = true;
            IBS.READ(SCCGWA, DCRSPAC, DCTSPAC_RD);
            if (SCCGWA.COMM_AREA.DBIO_FLG == '0') {
                WS_DATA_TO_SCZTPCL.WS_AC_NO = DCRSPAC.STD_AC;
                CEP.TRC(SCCGWA, DCRSPAC.STD_AC);
                CEP.TRC(SCCGWA, WS_DATA_TO_SCZTPCL.WS_AC_NO);
            }
            SCCTPCL.SERV_AREA.OBJ_SYSTEM = K_OBJ_SYSTEM;
            SCCTPCL.SERV_AREA.SERV_CODE = K_SERV_CODE;
            SCCTPCL.SERV_AREA.SERV_TYPE = 'Y';
            WS_DATA_TO_SCZTPCL.WS_TYPE = "" + DDCUZFMM.INPUT.CHQ_TYP;
            JIBS_tmp_int = WS_DATA_TO_SCZTPCL.WS_TYPE.length();
            for (int i=0;i<1-JIBS_tmp_int;i++) WS_DATA_TO_SCZTPCL.WS_TYPE = "0" + WS_DATA_TO_SCZTPCL.WS_TYPE;
            WS_DATA_TO_SCZTPCL.WS_ISSU_DATE = DDCUZFMM.INPUT.CHQ_ISSU_DATE;
            WS_DATA_TO_SCZTPCL.WS_CHQ_NO = DDCUZFMM.INPUT.CHQ_NO;
            WS_DATA_TO_SCZTPCL.WS_CHQ_AMT = DDCUZFMM.INPUT.AMT;
            WS_DATA_TO_SCZTPCL.WS_CHQ_PSW = DDCUZFMM.INPUT.CHQ_PSW;
            CEP.TRC(SCCGWA, WS_DATA_TO_SCZTPCL);
            SCCTPCL.INP_AREA.SERV_DATA_LEN = 104;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, WS_DATA_TO_SCZTPCL);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_CSIF_NOTICE);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_BVMS_INQ);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_BH_FILE_SEND);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_BH_FILE_ECIF);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_AC_CHG_INF);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_ACGL_GL0002);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_PASSWORD_CHK);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_SMS_INFO);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_ECIF_SG0001);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_CHG_NOTICE);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_ACGL_GL0001);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_ECIF_AC0001);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_LOAN_NOTICE);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.SN_SMS_NOTICE);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_ECIF_AC0002);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.CC_CHANGE_CARD);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.SC_SCF_NOTICE);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_ECIF_AC0003);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_IBIL_NOTICE);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_BROADCAST);
            IBS.CPY2CLS(SCCGWA, SCCTPCL.INP_AREA.SERV_DATA, SCCTPCL.INP_AREA.BD_CASH_CHG);
            if (!SCCGWA.COMM_AREA.BSP_FLG.equalsIgnoreCase("BSP") 
                && !SCCGWA.COMM_AREA.CHNL.equalsIgnoreCase("BAT")) {
                S000_CALL_SCZTPCL();
            }
        }
        if (SCCTPCL.INP_AREA.SERV_DATA == null) SCCTPCL.INP_AREA.SERV_DATA = "";
        JIBS_tmp_int = SCCTPCL.INP_AREA.SERV_DATA.length();
        for (int i=0;i<10700-JIBS_tmp_int;i++) SCCTPCL.INP_AREA.SERV_DATA += " ";
        if (SCCTPCL.INP_AREA.SERV_DATA.substring(0, 1).equalsIgnoreCase("Y")) {
            DDCUZFMM.OUTPUT_DATE.CHK_RESULT = '1';
        } else {
            DDCUZFMM.OUTPUT_DATE.CHK_RESULT = '2';
        }
    }
    public void B030_CHK_ZFMM() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, SCCTSSC);
        SCCTSSC.FUNC = 'P';
        SCCTSSC.COMM_AREA_P.P_AREAID = "0001";
        SCCTSSC.COMM_AREA = IBS.CLS2CPY(SCCGWA, SCCTSSC.COMM_AREA_P);
        SCCTSSC.COMM_AREA_P.P_PAYACCT = DDCUZFMM.STD_AC;
        SCCTSSC.COMM_AREA = IBS.CLS2CPY(SCCGWA, SCCTSSC.COMM_AREA_P);
        if (DDCUZFMM.INPUT.CHQ_TYP == '1' 
            || DDCUZFMM.INPUT.CHQ_TYP == '2' 
            || DDCUZFMM.INPUT.CHQ_TYP == '3') {
            SCCTSSC.COMM_AREA_P.P_BILLKIND = "0031";
            SCCTSSC.COMM_AREA = IBS.CLS2CPY(SCCGWA, SCCTSSC.COMM_AREA_P);
        } else {
            SCCTSSC.COMM_AREA_P.P_BILLKIND = "0099";
            SCCTSSC.COMM_AREA = IBS.CLS2CPY(SCCGWA, SCCTSSC.COMM_AREA_P);
        }
        if (DDCUZFMM.INPUT.CHQ_NO == null) DDCUZFMM.INPUT.CHQ_NO = "";
        JIBS_tmp_int = DDCUZFMM.INPUT.CHQ_NO.length();
        for (int i=0;i<16-JIBS_tmp_int;i++) DDCUZFMM.INPUT.CHQ_NO += " ";
        SCCTSSC.COMM_AREA_P.P_BILLNO = DDCUZFMM.INPUT.CHQ_NO.substring(9 - 1, 9 + 8 - 1);
        SCCTSSC.COMM_AREA = IBS.CLS2CPY(SCCGWA, SCCTSSC.COMM_AREA_P);
        SCCTSSC.COMM_AREA_P.P_DATE = "" + DDCUZFMM.INPUT.CHQ_ISSU_DATE;
        JIBS_tmp_int = SCCTSSC.COMM_AREA_P.P_DATE.length();
        for (int i=0;i<8-JIBS_tmp_int;i++) SCCTSSC.COMM_AREA_P.P_DATE = "0" + SCCTSSC.COMM_AREA_P.P_DATE;
        SCCTSSC.COMM_AREA = IBS.CLS2CPY(SCCGWA, SCCTSSC.COMM_AREA_P);
        REDEFINES4.WS_P_AMOUNT = DDCUZFMM.INPUT.AMT;
        WS_P_AMOUNT_D = IBS.CLS2CPY(SCCGWA, REDEFINES4);
        if (SCCTSSC.COMM_AREA_P.P_AMOUNT == null) SCCTSSC.COMM_AREA_P.P_AMOUNT = "";
        JIBS_tmp_int = SCCTSSC.COMM_AREA_P.P_AMOUNT.length();
        for (int i=0;i<17-JIBS_tmp_int;i++) SCCTSSC.COMM_AREA_P.P_AMOUNT += " ";
        SCCTSSC.COMM_AREA_P.P_AMOUNT = "0" + SCCTSSC.COMM_AREA_P.P_AMOUNT.substring(1);
        if (SCCTSSC.COMM_AREA_P.P_AMOUNT == null) SCCTSSC.COMM_AREA_P.P_AMOUNT = "";
        JIBS_tmp_int = SCCTSSC.COMM_AREA_P.P_AMOUNT.length();
        for (int i=0;i<17-JIBS_tmp_int;i++) SCCTSSC.COMM_AREA_P.P_AMOUNT += " ";
        if (WS_P_AMOUNT_D == null) WS_P_AMOUNT_D = "";
        JIBS_tmp_int = WS_P_AMOUNT_D.length();
        for (int i=0;i<16-JIBS_tmp_int;i++) WS_P_AMOUNT_D += " ";
        SCCTSSC.COMM_AREA_P.P_AMOUNT = SCCTSSC.COMM_AREA_P.P_AMOUNT.substring(0, 2 - 1) + WS_P_AMOUNT_D + SCCTSSC.COMM_AREA_P.P_AMOUNT.substring(2 + 16 - 1);
        SCCTSSC.COMM_AREA_P.P_PAYCODE = DDCUZFMM.INPUT.CHQ_PSW;
        SCCTSSC.COMM_AREA = IBS.CLS2CPY(SCCGWA, SCCTSSC.COMM_AREA_P);
        CEP.TRC(SCCGWA, SCCTSSC);
        S000_CALL_SCZTSSC();
        if (SCCTSSC.RC != 0) {
            DDCUZFMM.OUTPUT_DATE.CHK_RESULT = '2';
        } else {
            DDCUZFMM.OUTPUT_DATE.CHK_RESULT = '1';
        }
    }
    public void S000_CALL_BPZRORGM() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-R-BRW-ORGM", BPCRORGM);
        CEP.TRC(SCCGWA, BPCRORGM.RETURN_INFO);
    }
    public void S000_CALL_SCZTPCL() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "SC-LINK-EXTSERV", SCCTPCL);
    }
    public void S000_CALL_SCZTSSC() throws IOException,SQLException,Exception {
        SCZTSSC SCZTSSC = new SCZTSSC();
        SCZTSSC.MP(SCCGWA, SCCTSSC);
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
    if (SCCGWA.COMM_AREA.BSP_FLG.equalsIgnoreCase("BSP") || SCCGWA.COMM_AREA.CHNL.equalsIgnoreCase("BAT")) { //FROM #IFDEF BAT
        if (DDCUZFMM.RC.RC_CODE != 0) {
            CEP.TRC(SCCGWA, "DDCUZFMM=");
            CEP.TRC(SCCGWA, DDCUZFMM);
        }
    } //FROM #ENDIF
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
