package com.hisun.AI;

public class AICOGRVS_DATA {
    public String RVS_NO = " ";
    public int RVS_SEQ = 0;
    public String AC = " ";
    public String CCY = " ";
    public char STS = ' ';
    public int TX_DT = 0;
    public int JYRQ = 0;
    public double AMT = 0;
    public char FILLER20 = 0X01;
    public String CI_NO = " ";
    public String TR_CODE = " ";
    public String TR_TELLER = " ";
    public int TR_BR = 0;
    public String SET_NO = " ";
    public short SET_SEQ = 0;
    public String APP = " ";
    public String CHNL_NO = " ";
    public String TX_SUP_TLR = " ";
    public String PART = " ";
    public char FILLER31 = 0X02;
    public String CPLX = " ";
    public String CPMX = " ";
    public char GZLB = ' ';
    public String GZKM = " ";
    public int SXH1 = 0;
    public char GZZL = ' ';
    public String HZFM = " ";
    public int HSJG = 0;
    public char JDBZ = ' ';
    public int KMZH = 0;
    public int QXRQ = 0;
    public String SJLX = " ";
    public String YWBH = " ";
    public int JYJG = 0;
    public String THEIR_AC = " ";
    public String PAY_MAN = " ";
    public char FILLER48 = 0X02;
    public int PAY_BR = 0;
}
