package com.hisun.AI;

public class AICSCMIB {
    public AICSCMIB_RC RC = new AICSCMIB_RC();
    public char FUNC = ' ';
    public char FUNC_N = ' ';
    public String GL_BOOK = " ";
    public int BR = 0;
    public String ITM = " ";
    public int SEQ = 0;
    public String ENG_NM = " ";
    public String CHS_NM = " ";
    public char STS = ' ';
    public char AC_TYP = ' ';
    public char CCY_LMT = ' ';
    public char BAL_DIR = ' ';
    public char BAL_RFLG = ' ';
    public char AMT_DIR = ' ';
    public char DTL_FLG = ' ';
    public char RVS_TYP = ' ';
    public char RVS_KND = ' ';
    public short RVS_EXP = 0;
    public char RVS_UNIT = ' ';
    public int AC_EXP = 0;
    public char MANUAL_FLG = ' ';
    public char ONL_FLG = ' ';
    public char CARD_FLG = ' ';
    public char HOT_FLG = ' ';
    public double DRLT_BAL = 0;
    public double CRLT_BAL = 0;
    public char BAL_CHK = ' ';
    public String APP1 = " ";
    public String APP2 = " ";
    public String APP3 = " ";
    public String APP4 = " ";
    public String APP5 = " ";
    public String APP6 = " ";
    public String APP7 = " ";
    public String APP8 = " ";
    public String APP9 = " ";
    public String APP10 = " ";
    public int EFF_DATE = 0;
    public int EXP_DATE = 0;
}
