package com.hisun.AI;

import java.io.IOException;
import java.sql.SQLException;

import com.hisun.BP.BPCEX;
import com.hisun.BP.BPCFAMTA;
import com.hisun.BP.BPCFCSTS;
import com.hisun.BP.BPCFRWDA;
import com.hisun.BP.BPCFTLAM;
import com.hisun.BP.BPCFTLCM;
import com.hisun.BP.BPCFTLRQ;
import com.hisun.BP.BPCOCLWD;
import com.hisun.BP.BPCOQPCD;
import com.hisun.BP.BPCOVABS;
import com.hisun.BP.BPCOVAWR;
import com.hisun.BP.BPCPARM;
import com.hisun.BP.BPCPEBAS;
import com.hisun.BP.BPCPORLO;
import com.hisun.BP.BPCPQBNK_DATA_INFO;
import com.hisun.BP.BPCPQORG;
import com.hisun.BP.BPCPQPRD;
import com.hisun.BP.BPCPRGST;
import com.hisun.BP.BPCPRMB;
import com.hisun.BP.BPCPRMM;
import com.hisun.BP.BPCPRMR;
import com.hisun.BP.BPCQBKPM;
import com.hisun.BP.BPCRMBPM;
import com.hisun.BP.BPCSGSEQ;
import com.hisun.BP.BPCUCNGM;
import com.hisun.BP.BPRACCT;
import com.hisun.BP.BPRCTL;
import com.hisun.BP.BPRPARM;
import com.hisun.BP.BPRPORGM;
import com.hisun.BP.BPRPRMT;
import com.hisun.BP.BPRTLT;
import com.hisun.BP.BPRTRT;
import com.hisun.BP.BPRVCHH;
import com.hisun.BP.BPRVCHT;
import com.hisun.BP.BPRVWA;
import com.hisun.CI.CICACCU;
import com.hisun.CI.CICCUST;
import com.hisun.DD.DDCUCRAC;
import com.hisun.DD.DDCUDRAC;
import com.hisun.IB.IBCPOSTA;
import com.hisun.IB.IBCQINF;
import com.hisun.SC.SCCAWAC;
import com.hisun.SC.SCCCALL;
import com.hisun.SC.SCCCLDT;
import com.hisun.SC.SCCEXCP;
import com.hisun.SC.SCCFMT;
import com.hisun.SC.SCCGBPA_BP_AREA;
import com.hisun.SC.SCCGCPT;
import com.hisun.SC.SCCGMSG;
import com.hisun.SC.SCCGSCA_SC_AREA;
import com.hisun.SC.SCCGWA;
import com.hisun.SC.SCCMPAG;
import com.hisun.SC.SCCMSG;
import com.hisun.SC.SCCPRMR;
import com.hisun.SC.SCCSUBS;

public class AIOMP01 {
    boolean pgmRtn = false;
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCMPAG SCCMPAG = new SCCMPAG();
    BPCPQORG BPCPQORG = new BPCPQORG();
    BPCPORLO BPCPORLO = new BPCPORLO();
    BPCFTLRQ BPCFTLRQ = new BPCFTLRQ();
    BPCPRGST BPCPRGST = new BPCPRGST();
    BPCFTLCM BPCFTLCM = new BPCFTLCM();
    String PGM_SCSOPARM = "SCSOPARM";
    String PGM_SCSOWOUT = "SCSOWOUT";
    String CPN_BP_P_INQ_PC = "BP-P-INQ-PC   ";
    String CPN_P_INQ_ORG = "BP-P-INQ-ORG    ";
    String PGM_SCSOAUTH = "SCSOAUTH";
    String CPN_F_TLR_ACCU_MGM = "BP-F-TLR-ACCU-MGM";
    String CPN_BP_EX = "BP-EX";
    String CPN_IB_IBSOPOST = "IB-IBSOPOST";
    String CPN_CI_CISOACCU = "CI-CISOACCU";
    String CPN_PBSOCCAC = "PB-PBSOCCAC";
    String CPN_PM_PMSOPRMT = "PM-PMSOPRMT";
    int K_DB2_802 = -802;
    String FILE_AIFPMT = "AIFPMT  ";
    String K_AIACT = "AIACT";
    String K_CASGL_CD = "CASGL";
    String K_ATHLV_CD = "ATHLV";
    String K_BRGAC_CD = "BRGAC";
    String K_MMO_DD = "DD";
    char K_TYPE = 'G';
    char K_ERROR = 'E';
    short K_FLD_CNT = 150;
    short K_MAX_IB = 05;
    short K_MAX_AC_CNT = 40;
    short K_MAX_ENTRY = 400;
    char K_AC_TYPE_IA = 'I';
    int K_MAX_BR = 50;
    int K_MAX_OUT_CNT = 500;
    int WS_ISSUING_BRANCH = 0;
    int WS_PRMT_LEN = 0;
    short WS_I = 0;
    short WS_J = 0;
    short WS_K = 0;
    short WS_Q = 0;
    String WS_VIL_TYP = "   ";
    String WS_VIL_TYP_TMP = "   ";
    AIOMP01_WS_MAT_REF WS_MAT_REF = new AIOMP01_WS_MAT_REF();
    AIOMP01_WS_IA_AC WS_IA_AC = new AIOMP01_WS_IA_AC();
    AIOMP01_WS_IDX WS_IDX = new AIOMP01_WS_IDX();
    char WS_FND_FLG = 'N';
    char WS_END_FLG = 'N';
    short WS_TSQ_LEN = 0;
    int WS_CNT = 0;
    short WS_VWA_CNT = 0;
    short WS_INT = 0;
    short WS_AC_IND = 0;
    int WS_BCH_INT = 0;
    short WS_MP_CNT = 0;
    int WS_TR_BRANCH = 0;
    short WS_BOOK_CNT = 0;
    short WS_ENTRY_MAX = 0;
    int WS_BCH = 0;
    int WS_SUB_NUM = 0;
    char WS_MATCH = ' ';
    int WS_UPDATE_TIME = 0;
    char WS_AUTO = ' ';
    char WS_DR_CR = ' ';
    char WS_CONTROL_TYPE = ' ';
    double WS_CONTROL_AMT = 0;
    char WS_LVL1 = ' ';
    char WS_LVL2 = ' ';
    char WS_LVL = ' ';
    char WS_LVL_X = ' ';
    String WS_AC_NO = " ";
    short WS_DD_COUNT_INT = 0;
    short WS_MST_COUNT_INT = 0;
    short WS_GRP_COUNT_INT = 0;
    String WS_ACTION_CODE = "  ";
    String WS_MSG_INOFF = "   ";
    double WS_AMT = 0;
    double WS_TMP_AMT = 0;
    String WS_TMP_INFO = " ";
    short WS_TMP_LEN = 0;
    short WS_NAME_LEN = 0;
    String WS_ACCT_CODE = " ";
    int WS_SAVE_TMP_NO = 0;
    double WS_ODE_TX_AMT = 0;
    int WS_TMP_BBR = 0;
    AIOMP01_WS_PRMT_DAT_TXT WS_PRMT_DAT_TXT = new AIOMP01_WS_PRMT_DAT_TXT();
    AIOMP01_REDEFINES65 REDEFINES65 = new AIOMP01_REDEFINES65();
    AIOMP01_WS_PRMT_DATA WS_PRMT_DATA = new AIOMP01_WS_PRMT_DATA();
    int WS_VALUE_DATE = 0;
    AIOMP01_REDEFINES77 REDEFINES77 = new AIOMP01_REDEFINES77();
    AIOMP01_WS_UPD_TIME WS_UPD_TIME = new AIOMP01_WS_UPD_TIME();
    double WS_LCE = 0;
    AIOMP01_WS_GROUP_NO WS_GROUP_NO = new AIOMP01_WS_GROUP_NO();
    AIOMP01_WS_PBDT_KEY WS_PBDT_KEY = new AIOMP01_WS_PBDT_KEY();
    AIOMP01_WS_REF WS_REF = new AIOMP01_WS_REF();
    AIOMP01_WS_ERR_INFO WS_ERR_INFO = new AIOMP01_WS_ERR_INFO();
    AIOMP01_WS_CTL_WORD WS_CTL_WORD = new AIOMP01_WS_CTL_WORD();
    AIOMP01_WS_T_CTL WS_T_CTL = new AIOMP01_WS_T_CTL();
    AIOMP01_REDEFINES115 REDEFINES115 = new AIOMP01_REDEFINES115();
    AIOMP01_WS_D_FLD WS_D_FLD = new AIOMP01_WS_D_FLD();
    AIOMP01_WS_OUT_ODE_291 WS_OUT_ODE_291 = new AIOMP01_WS_OUT_ODE_291();
    AIOMP01_WS_OUT_ODE_300 WS_OUT_ODE_300 = new AIOMP01_WS_OUT_ODE_300();
    AIOMP01_WS_OUT_ODE_302 WS_OUT_ODE_302 = new AIOMP01_WS_OUT_ODE_302();
    AIOMP01_WS_OUT_ODE_301 WS_OUT_ODE_301 = new AIOMP01_WS_OUT_ODE_301();
    AIOMP01_WS_OUT_ODE_293 WS_OUT_ODE_293 = new AIOMP01_WS_OUT_ODE_293();
    AIOMP01_WS_OUT_ODE_295 WS_OUT_ODE_295 = new AIOMP01_WS_OUT_ODE_295();
    AIOMP01_WS_OUT_ODE_296 WS_OUT_ODE_296 = new AIOMP01_WS_OUT_ODE_296();
    AIOMP01_WS_BOOK_PARM[] WS_BOOK_PARM = new AIOMP01_WS_BOOK_PARM[10];
    AIOMP01_WS_GL_INFO WS_GL_INFO = new AIOMP01_WS_GL_INFO();
    AIOMP01_WS_NEW_OLD WS_NEW_OLD = new AIOMP01_WS_NEW_OLD();
    int WS_DAT_01 = 0;
    AIOMP01_REDEFINES256 REDEFINES256 = new AIOMP01_REDEFINES256();
    int WS_DAT_02 = 0;
    AIOMP01_REDEFINES261 REDEFINES261 = new AIOMP01_REDEFINES261();
    AIOMP01_WS_TEMP_SUM WS_TEMP_SUM = new AIOMP01_WS_TEMP_SUM();
    AIOMP01_WS_TMP1_KEY WS_TMP1_KEY = new AIOMP01_WS_TMP1_KEY();
    AIOMP01_WS_TMP2_KEY WS_TMP2_KEY = new AIOMP01_WS_TMP2_KEY();
    AIOMP01_WS_TEMP_SAVE WS_TEMP_SAVE = new AIOMP01_WS_TEMP_SAVE();
    AIOMP01_WS_OUTPUT_3 WS_OUTPUT_3 = new AIOMP01_WS_OUTPUT_3();
    AIOMP01_WS_OUTPUT_4 WS_OUTPUT_4 = new AIOMP01_WS_OUTPUT_4();
    AIOMP01_WS_OUTPUT_WF WS_OUTPUT_WF = new AIOMP01_WS_OUTPUT_WF();
    AIOMP01_WS_OUTPUT_CI WS_OUTPUT_CI = new AIOMP01_WS_OUTPUT_CI();
    AIOMP01_WS_OUT_TMP_LIST WS_OUT_TMP_LIST = new AIOMP01_WS_OUT_TMP_LIST();
    AIOMP01_WS_OUTPUT_BAL WS_OUTPUT_BAL = new AIOMP01_WS_OUTPUT_BAL();
    AIOMP01_WS_OUTPUT_1 WS_OUTPUT_1 = new AIOMP01_WS_OUTPUT_1();
    AIOMP01_WS_OUTPUT_2 WS_OUTPUT_2 = new AIOMP01_WS_OUTPUT_2();
    AIOMP01_WS_OUTPUT_5 WS_OUTPUT_5 = new AIOMP01_WS_OUTPUT_5();
    int WS_CUR_CNT = 0;
    int WS_GRP_COUNT = 0;
    int WS_MST_COUNT = 0;
    int WS_ODE_COUNT = 0;
    int WS_DD_CNT = 0;
    int WS_TOT_COUNT = 0;
    int WS_BG_COUNT = 0;
    int WS_GL_COUNT = 0;
    char WS_TOT_TYPE = ' ';
    String WS_TOT_CUR = " ";
    char WS_TOT_INOFF = ' ';
    char WS_TOT_AC = ' ';
    int WS_TOT_CNT = 0;
    String WS_TMP_NAME = " ";
    double WS_TOT_SUM = 0;
    int WS_BEGDAT = 0;
    int WS_ENDDAT = 0;
    int WS_TR_BR = 0;
    AIOMP01_WS_CONSTANT WS_CONSTANT = new AIOMP01_WS_CONSTANT();
    String WS_PROD_AP = " ";
    BPRCTL BPRCTLD = new BPRCTL();
    SCCCLDT SCCCLDT = new SCCCLDT();
    BPCPRMR BPCPRMR = new BPCPRMR();
    SCCPRMR SCCPRMC = new SCCPRMR();
    BPRPRMT BPRPRMT = new BPRPRMT();
    SCCPAGE SCCPAGE = new SCCPAGE();
    SCCFMT SCCFMT = new SCCFMT();
    BPCOQPCD BPCOQPCD = new BPCOQPCD();
    BPCOCLWD BPCOCLWD = new BPCOCLWD();
    AICOL60_OPT_L60 AICOL60_OPT_L60 = new AICOL60_OPT_L60();
    AICX101 AICX101 = new AICX101();
    AICX102 AICX102 = new AICX102();
    AICX103 AICX103 = new AICX103();
    AICX104 AICX104 = new AICX104();
    AICX660 AICX660 = new AICX660();
    BPCEX BPCEX = new BPCEX();
    IBCQINF IBCQINF = new IBCQINF();
    BPCFTLAM BPCFTLAM = new BPCFTLAM();
    CICACCU CICACCU = new CICACCU();
    AICQMST AICQMST = new AICQMST();
    AICPQITM AICPQITM = new AICPQITM();
    AICCKPO AICCKPO = new AICCKPO();
    BPCSGSEQ BPCSGSEQ = new BPCSGSEQ();
    SCCSUBS SCCSUBS = new SCCSUBS();
    AIRPAI1 AIRPAI1 = new AIRPAI1();
    AIRPAI2 AIRPAI2 = new AIRPAI2();
    AIRGINF AIRGINF = new AIRGINF();
    AICRGINF AICRGINF = new AICRGINF();
    BPCQBKPM BPCQBKPM = new BPCQBKPM();
    BPCUCNGM BPCUCNGM = new BPCUCNGM();
    BPCPEBAS BPCPEBAS = new BPCPEBAS();
    BPCOVABS BPCOVABS = new BPCOVABS();
    BPCOVAWR BPCOVAWR = new BPCOVAWR();
    DDCICKCD DDCICKCD = new DDCICKCD();
    DDCUCRAC DDCUCRAC = new DDCUCRAC();
    DDCUDRAC DDCUDRAC = new DDCUDRAC();
    AICOCKVH AICOCKVH = new AICOCKVH();
    IBCPOSTA IBCPOSTA = new IBCPOSTA();
    BPRVWA BPROVWA = new BPRVWA();
    AICUUPIA AICUUPIA = new AICUUPIA();
    AICPQMIB AICPQMIB = new AICPQMIB();
    CICCUST CICCUST = new CICCUST();
    AICPUITM AICPUITM = new AICPUITM();
    AICMSG_ERROR_MSG AICMSG_ERROR_MSG = new AICMSG_ERROR_MSG();
    BPCPRMB BPCPRMB = new BPCPRMB();
    BPRPORGM BPRPORGM = new BPRPORGM();
    BPCFAMTA BPCFAMTA = new BPCFAMTA();
    BPCFCSTS BPCFCSTS = new BPCFCSTS();
    BPCFRWDA BPCFRWDA = new BPCFRWDA();
    BPCPQPRD BPCPQPRD = new BPCPQPRD();
    BPRACCT BPRACCT = new BPRACCT();
    BPCPARM BPCPARM = new BPCPARM();
    BPRPARM BPRPARM = new BPRPARM();
    BPCPRMM BPCPRMM = new BPCPRMM();
    BPCRMBPM BPCRMBPM = new BPCRMBPM();
    AIRGRP AIRGRP = new AIRGRP();
    AIRGRPT AIRGRPT = new AIRGRPT();
    AIRODE AIRODE = new AIRODE();
    AIRODET AIRODET = new AIRODET();
    AIRITM AIRITM = new AIRITM();
    AIRMST AIRMST = new AIRMST();
    AIRTMP AIRTMP = new AIRTMP();
    BPRVCHT BPRVCHT = new BPRVCHT();
    BPRVCHH BPRVCHH = new BPRVCHH();
    SCCGWA SCCGWA;
    SCCGSCA_SC_AREA SCCGSCA_SC_AREA;
    SCCGBPA_BP_AREA SCCGBPA_BP_AREA;
    SCCGCPT SCCGCPT;
    SCCGMSG SCCGMSG;
    BPCPQBNK_DATA_INFO BPCRBANK;
    BPRTRT BPRTRTT;
    BPRTLT BPRTLT;
    AIB0001_AWA_0001 AIB0001_AWA_0001;
    SCCAWAC SCCAWAC;
    BPRVWA BPRVWA;
    public AIOMP01() {
        for (int i=0;i<10;i++) WS_BOOK_PARM[i] = new AIOMP01_WS_BOOK_PARM();
    }
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A00_INIT_PROC();
        if (pgmRtn) return;
        B00_MAIN_PROC();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, "AIOMP01 return!");
        Z_RET();
        if (pgmRtn) return;
        JIBS_RETURN();
    }
    public void A00_INIT_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, SCCEXCP);
        CEP.TRC(SCCGWA, "1111");
        SCCGSCA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        CEP.TRC(SCCGWA, "1112");
        SCCGBPA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        SCCGCPT = (SCCGCPT) SCCGSCA_SC_AREA.CMPT_AREA_PTR;
        SCCGMSG = (SCCGMSG) SCCGSCA_SC_AREA.MSG_AREA_PTR;
        BPRTRTT = (BPRTRT) SCCGSCA_SC_AREA.TR_PARM_PTR;
        BPCRBANK = (BPCPQBNK_DATA_INFO) SCCGWA.COMM_AREA.BANK_AREA_PTR;
        CEP.TRC(SCCGWA, "1113");
        BPRTLT = (BPRTLT) SCCGWA.COMM_AREA.TLT_AREA_PTR;
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "AIB0001_AWA_0001>");
        AIB0001_AWA_0001 = (AIB0001_AWA_0001) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        SCCAWAC = new SCCAWAC();
        IBS.init(SCCGWA, SCCAWAC);
        IBS.CPY2CLS(SCCGWA, SCCGWA.COMM_AREA.AWAC_AREA_PTR, SCCAWAC);
        IBS.init(SCCGWA, AIRGRP);
        IBS.init(SCCGWA, AIRODE);
        IBS.init(SCCGWA, SCCMSG);
        SCCGSCA_SC_AREA.CURS_POS = 0;
        IBS.CPY2CLS(SCCGWA, BPRTRTT.DATA_TXT.PGM[SCCGWA.COMM_AREA.PGM_NO-1].PGM_CTL, WS_T_CTL);
        JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, WS_T_CTL);
        IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], REDEFINES115);
        CEP.TRC(SCCGWA, "1114");
    }
    public void B00_MAIN_PROC() throws IOException,SQLException,Exception {
        R00_SEARCH_D_TABLE();
        if (pgmRtn) return;
        WS_MP_CNT = (short) BPRCTLD.DATA_TXT.FLD_CNT;
        CEP.TRC(SCCGWA, BPRCTLD.DATA_TXT.FLD_CNT);
        for (WS_K = 1; WS_K <= WS_MP_CNT; WS_K += 1) {
            IBS.CPY2CLS(SCCGWA, BPRCTLD.DATA_TXT.FLD_TXT.FLD.get(WS_K-1).FLD_NAME, WS_D_FLD.WS_STEP);
            WS_D_FLD.WS_D_NAME = IBS.CLS2CPY(SCCGWA, WS_D_FLD.WS_STEP);
