package com.hisun.AI;

import java.io.IOException;
import java.sql.SQLException;

import com.hisun.BP.BPCEX;
import com.hisun.BP.BPCFTLRQ;
import com.hisun.BP.BPCOCKWD;
import com.hisun.BP.BPCOCLWD;
import com.hisun.BP.BPCOQPCD;
import com.hisun.BP.BPCPGDIN;
import com.hisun.BP.BPCPORLO;
import com.hisun.BP.BPCPORUP_DATA_INFO;
import com.hisun.BP.BPCPQBNK_DATA_INFO;
import com.hisun.BP.BPCPQORG;
import com.hisun.BP.BPCPRMB;
import com.hisun.BP.BPCQBKPM;
import com.hisun.BP.BPCQCCY;
import com.hisun.BP.BPCRCCY;
import com.hisun.BP.BPRCTL;
import com.hisun.BP.BPRPORGM;
import com.hisun.BP.BPRPRMT;
import com.hisun.BP.BPRTLT;
import com.hisun.BP.BPRTRT;
import com.hisun.SC.SCCAWAC;
import com.hisun.SC.SCCCALL;
import com.hisun.SC.SCCCKDT;
import com.hisun.SC.SCCEXCP;
import com.hisun.SC.SCCFMT;
import com.hisun.SC.SCCGBPA_BP_AREA;
import com.hisun.SC.SCCGCPT;
import com.hisun.SC.SCCGMSG;
import com.hisun.SC.SCCGSCA_SC_AREA;
import com.hisun.SC.SCCGWA;
import com.hisun.SC.SCCMPAG;
import com.hisun.SC.SCCMSG;
import com.hisun.SC.SCCPRMR;
import com.hisun.SC.SCCSUBS;

public class AIOMP04 {
    boolean pgmRtn = false;
    String BSL_RTC_FLAG = "SIT_GN_20150613_V1";
    SCCCALL SCCCALL = new SCCCALL();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCMSG SCCMSG = new SCCMSG();
    SCCMPAG SCCMPAG = new SCCMPAG();
    SCCFMT SCCFMT = new SCCFMT();
    BPCPQORG BPCPQORG = new BPCPQORG();
    String PGM_SCSSCKDT = "SCSSCKDT";
    String CPN_BP_PARM_READ = "BP-PARM-READ";
    String CPN_P_INQ_ORG_LOW = "BP-P-INQ-ORG-LOW";
    String K_D_TABLE = "D";
    String K_CCY_MACAO = "446";
    short K_OUTPUT_LIMIT = 510;
    int K_MAX_ROW = 12;
    String WS_ERR_MSG = " ";
    String WS_CCY = " ";
    int WS_BR = 0;
    int[] WS_OCCURS_BR = new int[1000];
    String WS_OCCURS_ATTR;
    long WS_CNT2 = 0;
    long WS_CNT3 = 0;
    char WS_FLG1 = ' ';
    char WS_FLG2 = ' ';
    char WS_FLG4 = ' ';
    char WS_FLG5 = ' ';
    int WS_PORLO_BR = 0;
    char WS_INQ_FLG = ' ';
    int WS_COUNT = 0;
    String WS_CUR = " ";
    long WS_CNT = 0;
    long WS_CNT1 = 0;
    long WS_REC_CNT = 0;
    int WS_RCD_SEQ = 0;
    int WS_RD_NUM = 0;
    short WS_RECORD_NUM = 0;
    short WS_SAVE_J = 0;
    int WS_REAL_DT = 0;
    short WS_I = 0;
    short WS_K = 0;
    short WS_J = 0;
    short WS_TOT_LEN = 0;
    short WS_TOT_LEN_1 = 0;
    short WS_TOT_LEN_2 = 0;
    String WS_COA_FLG = " ";
    short WS_INT_X = 0;
    String WS_ITM_BF = " ";
    String WS_ITM_AF = " ";
    int WS_ITM_LEN = 0;
    int WS_A_ITM_LEN = 0;
    String WS_ITM_NO = " ";
    char WS_FLG = ' ';
    char WS_FUNC = ' ';
    int WS_TMP_BR = 0;
    long WS_CNTA = 0;
    int WS_IDX = 0;
    int WS_DAT_03 = 0;
    AIOMP04_REDEFINES47 REDEFINES47 = new AIOMP04_REDEFINES47();
    int WS_DAT_04 = 0;
    AIOMP04_REDEFINES53 REDEFINES53 = new AIOMP04_REDEFINES53();
    AIOMP04_WS_ITM_LVL WS_ITM_LVL = new AIOMP04_WS_ITM_LVL();
    AIOMP04_WS_OLD_AC WS_OLD_AC = new AIOMP04_WS_OLD_AC();
    AIOMP04_WS_NEW_AC WS_NEW_AC = new AIOMP04_WS_NEW_AC();
    String WS_GL_BOOK = " ";
    String WS_COA_NO = " ";
    AIOMP04_WS_OP_1 WS_OP_1 = new AIOMP04_WS_OP_1();
    AIOMP04_WS_OP_2 WS_OP_2 = new AIOMP04_WS_OP_2();
    AIOMP04_WS_TRT_CTL WS_TRT_CTL = new AIOMP04_WS_TRT_CTL();
    AIOMP04_WS_FLD_NAME WS_FLD_NAME = new AIOMP04_WS_FLD_NAME();
    short WS_D_IDX = 0;
    AIOMP04_WS_D_FLD WS_D_FLD = new AIOMP04_WS_D_FLD();
    String WS_T_CTL = " ";
    AIOMP04_REDEFINES110 REDEFINES110 = new AIOMP04_REDEFINES110();
    AIOMP04_REDEFINES119 REDEFINES119 = new AIOMP04_REDEFINES119();
    String WS_M_CCY = " ";
    double WS_M_BKBAL = 0;
    double WS_M_LOCAL_BKBAL = 0;
    String WS_COANO = " ";
    int WS_ACCENTRE = 0;
    AIOMP04_WS_DAT_01 WS_DAT_01 = new AIOMP04_WS_DAT_01();
    int WS_DATE1 = 0;
    int WS_DATE2 = 0;
    int WS_DAT_02 = 0;
    AIOMP04_REDEFINES136 REDEFINES136 = new AIOMP04_REDEFINES136();
    AIOMP04_WS_YTR_DATE WS_YTR_DATE = new AIOMP04_WS_YTR_DATE();
    AIOMP04_WS_MTR_DATE WS_MTR_DATE = new AIOMP04_WS_MTR_DATE();
    char WS_AUTH_LVL_1_X = ' ';
    AIOMP04_REDEFINES148 REDEFINES148 = new AIOMP04_REDEFINES148();
    int WS_LAST_BR = 0;
    String WS_ENG_NM = " ";
    String WS_CHN_NM = " ";
    double WS_AMT_FR = 0;
    double WS_AMT_TO = 0;
    String WS_MIN_ITM = " ";
    String WS_MAX_ITM = " ";
    int WS_COUNT_NO = 0;
    AIOMP04_WS_CONSTANT WS_CONSTANT = new AIOMP04_WS_CONSTANT();
    char WS_AIRMST_FLG = ' ';
    char WS_AUTH_SEE_FLG = ' ';
    char WS_AIRITM_FLG = ' ';
    char WS_AIRHMST_FLG = ' ';
    char WS_TST_FLG = ' ';
    BPRCTL BPRCTLT = new BPRCTL();
    BPRCTL BPRCTLD = new BPRCTL();
    SCCCKDT SCCCKDT = new SCCCKDT();
    SCCPAGE SCCPAGE = new SCCPAGE();
    BPCFTLRQ BPCFTLRQ = new BPCFTLRQ();
    BPCOQPCD BPCOQPCD = new BPCOQPCD();
    BPCOCKWD BPCOCKWD = new BPCOCKWD();
    BPCEX BPCEX = new BPCEX();
    AICMSG_ERROR_MSG AICMSG_ERROR_MSG = new AICMSG_ERROR_MSG();
    BPCQBKPM BPCQBKPM = new BPCQBKPM();
    BPCOCLWD BPCOCLWD = new BPCOCLWD();
    BPCPGDIN BPCPGDIN = new BPCPGDIN();
    SCCSUBS SCCSUBS = new SCCSUBS();
    BPRPRMT BPRPRMT = new BPRPRMT();
    BPCPRMB BPCPRMB = new BPCPRMB();
    BPRPORGM BPRPORGM = new BPRPORGM();
    BPCQCCY BPCQCCY = new BPCQCCY();
    BPCRCCY BPCRCCY = new BPCRCCY();
    AICX501 AICX501 = new AICX501();
    AICX502 AICX502 = new AICX502();
    AICX503 AICX503 = new AICX503();
    AICX504 AICX504 = new AICX504();
    AICPQITM AICQITM = new AICPQITM();
    BPCPORLO BPCPORLO = new BPCPORLO();
    AICOZZYE AICOZZYE = new AICOZZYE();
    SCCPRMR SCCPRMR = new SCCPRMR();
    AIRMST AIRMST = new AIRMST();
    AIRITM AIRITM = new AIRITM();
    AIRHMST AIRHMST = new AIRHMST();
    SCCGWA SCCGWA;
    SCCGSCA_SC_AREA SCCGSCA_SC_AREA;
    SCCGBPA_BP_AREA SCCGBPA_BP_AREA;
    SCCGCPT SCCGCPT;
    SCCGMSG SCCGMSG;
    BPCPQBNK_DATA_INFO BPCRBANK;
    BPRTRT BPRTRTT;
    BPRTLT BPRTLT;
    AIB0004_AWA_0004 AIB0004_AWA_0004;
    SCCAWAC SCCAWAC;
    BPCPORUP_DATA_INFO BPCPORUP;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A00_INIT_PROC();
        if (pgmRtn) return;
        B00_MAIN_PROC();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, "AIOMP04 return!");
        Z_RET();
        if (pgmRtn) return;
        JIBS_RETURN();
    }
    public void A00_INIT_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, SCCEXCP);
        SCCGSCA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        SCCGBPA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        SCCGCPT = (SCCGCPT) SCCGSCA_SC_AREA.CMPT_AREA_PTR;
        SCCGMSG = (SCCGMSG) SCCGSCA_SC_AREA.MSG_AREA_PTR;
        BPRTRTT = (BPRTRT) SCCGSCA_SC_AREA.TR_PARM_PTR;
        BPCRBANK = (BPCPQBNK_DATA_INFO) SCCGWA.COMM_AREA.BANK_AREA_PTR;
        BPRTLT = (BPRTLT) SCCGWA.COMM_AREA.TLT_AREA_PTR;
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "AIB0004_AWA_0004>");
        AIB0004_AWA_0004 = (AIB0004_AWA_0004) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        SCCAWAC = new SCCAWAC();
        IBS.init(SCCGWA, SCCAWAC);
        IBS.CPY2CLS(SCCGWA, SCCGWA.COMM_AREA.AWAC_AREA_PTR, SCCAWAC);
        BPCPORUP = (BPCPORUP_DATA_INFO) SCCGWA.COMM_AREA.TR_BR_PTR;
        IBS.init(SCCGWA, SCCMSG);
        IBS.init(SCCGWA, AICX501);
        CEP.TRC(SCCGWA, BPRTRTT.DATA_TXT.PGM[SCCGWA.COMM_AREA.PGM_NO-1].PGM_CTL);
        WS_T_CTL = BPRTRTT.DATA_TXT.PGM[SCCGWA.COMM_AREA.PGM_NO-1].PGM_CTL;
        IBS.CPY2CLS(SCCGWA, WS_T_CTL, REDEFINES110);
        IBS.CPY2CLS(SCCGWA, WS_T_CTL, REDEFINES119);
        SCCGSCA_SC_AREA.CURS_POS = 0;
    }
    public void B00_MAIN_PROC() throws IOException,SQLException,Exception {
        B00_01_SEARCH_D_TABLE();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, BPRCTLD.DATA_TXT.FLD_CNT);
        for (WS_D_IDX = 1; WS_D_IDX <= BPRCTLD.DATA_TXT.FLD_CNT; WS_D_IDX += 1) {
            CEP.TRC(SCCGWA, BPRCTLD.DATA_TXT.FLD_TXT.FLD.get(WS_D_IDX-1).FLD_NAME);
            IBS.CPY2CLS(SCCGWA, BPRCTLD.DATA_TXT.FLD_TXT.FLD.get(WS_D_IDX-1).FLD_NAME, WS_D_FLD.WS_D_NAME);
