package com.hisun.AI;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;
import com.hisun.BP.*;
import com.hisun.CM.*;
import java.lang.reflect.Method;

import java.io.IOException;
import java.sql.SQLException;

public class AIOT8546 {
    int JIBS_tmp_int;
    DBParm BPTVCH01_RD;
    DBParm BPTVCH02_RD;
    String JIBS_tmp_str[] = new String[10];
    boolean pgmRtn = false;
    SCCCALL SCCCALL = new SCCCALL();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCMSG SCCMSG = new SCCMSG();
    SCCMPAG SCCMPAG = new SCCMPAG();
    SCCFMT SCCFMT = new SCCFMT();
    String K_OUT_FMT = "AIX01";
    int K_MAX_DAYS = 365;
    char K_D_TABLE = 'D';
    int K_BEGDATE = 0;
    int K_ENDDATE = 99991231;
    String PGM_SCSSCLDT = "SCSSCLDT";
    String PGM_SCSSCKDT = "SCSSCKDT";
    String CPN_P_INQ_ORG_LOW = "BP-P-INQ-ORG-LOW";
    short WS_I = 0;
    short WS_L = 0;
    short WS_J = 0;
    short WS_K = 0;
    String WS_ERR_MSG = " ";
    String WS_INFO = " ";
    String WS_ERR_INFO = " ";
    int WS_OP_CNT = 0;
    short WS_DAYS = 0;
    int WS_DATE_FR = 0;
    int WS_DATE_TO = 0;
    short WS_SENS_LVL1 = 0;
    String WS_LAST_ITM = " ";
    String WS_LAST_CHS_NM = " ";
    char WS_FUNC = ' ';
    int WS_CNTA = 0;
    char WS_LVL = ' ';
    char WS_LVL1 = ' ';
    int WS_IDX = 0;
    AIOT8546_WS_SUPR_GRP WS_SUPR_GRP = new AIOT8546_WS_SUPR_GRP();
    char WS_FLG = ' ';
    char WS_FLG1 = ' ';
    char WS_FLG2 = ' ';
    int WS_LAST_BR = 0;
    int WS_PORLO_BR = 0;
    short WS_AC_NUM = 0;
    short WS_AC_NUM1 = 0;
    int WS_DT_NUM = 0;
    int WS_DT_NUM1 = 0;
    char WS_INQ_FLG = ' ';
    AIOT8546_WS_GRP_NO_OUTPUT WS_GRP_NO_OUTPUT = new AIOT8546_WS_GRP_NO_OUTPUT();
    AIOT8546_WS_OUTPUT WS_OUTPUT = new AIOT8546_WS_OUTPUT();
    AIOT8546_WS_OUTPUT2 WS_OUTPUT2 = new AIOT8546_WS_OUTPUT2();
    AIOT8546_WS_FLD_NAME WS_FLD_NAME = new AIOT8546_WS_FLD_NAME();
    AIOT8546_WS_D_FLD WS_D_FLD = new AIOT8546_WS_D_FLD();
    String WS_T_CTL = " ";
    AIOT8546_REDEFINES77 REDEFINES77 = new AIOT8546_REDEFINES77();
    AIOT8546_REDEFINES86 REDEFINES86 = new AIOT8546_REDEFINES86();
    int WS_TBEGDAT = 0;
    int WS_TENDDAT = 0;
    int WS_VBEGDAT = 0;
    int WS_VENDDAT = 0;
    String WS_MINITM = " ";
    String WS_MAXITM = " ";
    int WS_BR_FR = 0;
    int WS_BR_TO = 0;
    double WS_END_AMT = 0;
    AIOT8546_WS_CONSTANT WS_CONSTANT = new AIOT8546_WS_CONSTANT();
    char WS_BPRVCHT_FLG = ' ';
    char WS_BPRVCHH_FLG = ' ';
    char WS_AITITM_FLG = ' ';
    char WS_REC2_INFO = ' ';
    BPRCTL BPRCTLT = new BPRCTL();
    BPRCTL BPRCTLD = new BPRCTL();
    SCCCKDT SCCCKDT = new SCCCKDT();
    SCCPAGE SCCPAGE = new SCCPAGE();
    BPCFTLRQ BPCFTLRQ = new BPCFTLRQ();
    BPCOQPCD BPCOQPCD = new BPCOQPCD();
    BPCOCLWD BPCOCLWD = new BPCOCLWD();
    BPCPQVCH BPCQVCH = new BPCPQVCH();
    BPRVCH01 BPRVCH01 = new BPRVCH01();
    BPRVCH02 BPRVCH02 = new BPRVCH02();
    AICMSG_ERROR_MSG AICMSG_ERROR_MSG = new AICMSG_ERROR_MSG();
    SCCCLDT SCCCLDT = new SCCCLDT();
    BPCPRMR BPCPRMR = new BPCPRMR();
    BPCSIC BPCSIC = new BPCSIC();
    SCCSUBS SCCSUBS = new SCCSUBS();
    BPRPRMT BPRPRMT = new BPRPRMT();
    BPCPRMB BPCPRMB = new BPCPRMB();
    BPCQCCY BPCQCCY = new BPCQCCY();
    BPCOQCAL BPCOQCAL = new BPCOQCAL();
    AICX506 AICX506 = new AICX506();
    AICX513 AICX513 = new AICX513();
    AICX538 AICX538 = new AICX538();
    AICPQITM AICPQITM = new AICPQITM();
    BPCPQORG BPCPQORG = new BPCPQORG();
    AICPCOA_COMMON9_VAR AICPCOA_COMMON9_VAR = new AICPCOA_COMMON9_VAR();
    BPCPORLO BPCPORLO = new BPCPORLO();
    SCCQJRN SCCQJRN = new SCCQJRN();
    BPRVCHT BPRVCHT = new BPRVCHT();
    BPRVCHH BPRVCHH = new BPRVCHH();
    AIRMST AIRMST = new AIRMST();
    AIRHMST AIRHMST = new AIRHMST();
    CMRPOSTC CMRPOSTC = new CMRPOSTC();
    SCCGWA SCCGWA;
    SCCGSCA_SC_AREA SCCGSCA_SC_AREA;
    SCCGBPA_BP_AREA SCCGBPA_BP_AREA;
    SCCGCPT SCCGCPT;
    SCCGMSG SCCGMSG;
    BPCPQBNK_DATA_INFO BPCRBANK;
    BPRTRT BPRTRTT;
    BPRTLT BPRTLT;
    AIB8546_AWA_8546 AIB8546_AWA_8546;
    SCCAWAC SCCAWAC;
    BPCPORUP_DATA_INFO BPCPORUP;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A00_INIT_PROC();
        if (pgmRtn) return;
        B00_MAIN_PROC();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, "AIOT8546 return!");
        Z_RET();
        if (pgmRtn) return;
    }
    public void A00_INIT_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, SCCEXCP);
        SCCGSCA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        SCCGBPA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        SCCGCPT = (SCCGCPT) SCCGSCA_SC_AREA.CMPT_AREA_PTR;
        SCCGMSG = (SCCGMSG) SCCGSCA_SC_AREA.MSG_AREA_PTR;
        BPRTRTT = (BPRTRT) SCCGSCA_SC_AREA.TR_PARM_PTR;
        BPCRBANK = (BPCPQBNK_DATA_INFO) SCCGWA.COMM_AREA.BANK_AREA_PTR;
        BPCPORUP = (BPCPORUP_DATA_INFO) SCCGWA.COMM_AREA.TR_BR_PTR;
        BPRTLT = (BPRTLT) SCCGWA.COMM_AREA.TLT_AREA_PTR;
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "AIB8546_AWA_8546>");
        AIB8546_AWA_8546 = (AIB8546_AWA_8546) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        SCCAWAC = new SCCAWAC();
        IBS.init(SCCGWA, SCCAWAC);
        IBS.CPY2CLS(SCCGWA, SCCGWA.COMM_AREA.AWAC_AREA_PTR, SCCAWAC);
        IBS.init(SCCGWA, SCCMSG);
        CEP.TRC(SCCGWA, BPRTRTT.DATA_TXT.PGM[SCCGWA.COMM_AREA.PGM_NO-1].PGM_CTL);
        WS_T_CTL = BPRTRTT.DATA_TXT.PGM[SCCGWA.COMM_AREA.PGM_NO-1].PGM_CTL;
        IBS.CPY2CLS(SCCGWA, WS_T_CTL, REDEFINES86);
        IBS.CPY2CLS(SCCGWA, WS_T_CTL, REDEFINES77);
        SCCGSCA_SC_AREA.CURS_POS = 0;
    }
    public void B00_MAIN_PROC() throws IOException,SQLException,Exception {
        B05_OUTPUT_DETAIL_INFO();
        if (pgmRtn) return;
    }
    public void B05_OUTPUT_DETAIL_INFO() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, AIB8546_AWA_8546.ACDATE);
        CEP.TRC(SCCGWA, AIB8546_AWA_8546.SEQ);
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.AC_DATE);
        IBS.init(SCCGWA, BPRVCH01);
        BPRVCH01.KEY.AC_DATE = AIB8546_AWA_8546.ACDATE;
        BPRVCH01.KEY.SET_SEQ = AIB8546_AWA_8546.SEQ;
        BPRVCH01.KEY.SET_NO = AIB8546_AWA_8546.SETNO;
        if (AIB8546_AWA_8546.SETNO == null) AIB8546_AWA_8546.SETNO = "";
        JIBS_tmp_int = AIB8546_AWA_8546.SETNO.length();
        for (int i=0;i<12-JIBS_tmp_int;i++) AIB8546_AWA_8546.SETNO += " ";
        if (AIB8546_AWA_8546.SETNO.substring(11 - 1, 11 + 2 - 1).trim().length() == 0) BPRVCH01.KEY.PART_NO = 0;
        else BPRVCH01.KEY.PART_NO = Integer.parseInt(AIB8546_AWA_8546.SETNO.substring(11 - 1, 11 + 2 - 1));
        T00_READ_BPTVCH01();
        if (pgmRtn) return;
        if (WS_CONSTANT.WS_DB2_REC_STATUS == 'F') {
            BPRVCHT.KEY.AC_DATE = BPRVCH01.KEY.AC_DATE;
            BPRVCHT.KEY.SET_NO = BPRVCH01.KEY.SET_NO;
            BPRVCHT.KEY.SET_SEQ = BPRVCH01.KEY.SET_SEQ;
            BPRVCHT.KEY.PART_NO = (short) BPRVCH01.KEY.PART_NO;
            BPRVCHT.AI_SEQ = BPRVCH01.KEY.AI_SEQ;
            BPRVCHT.JRN_NO = BPRVCH01.KEY.JRN_NO;
            BPRVCHT.AP_MMO = BPRVCH01.KEY.AP_MMO;
            BPRVCHT.TR_CODE = BPRVCH01.KEY.TR_CODE;
            BPRVCHT.TR_MMO = BPRVCH01.KEY.TR_MMO;
            BPRVCHT.TR_DATE = BPRVCH01.TR_DATE;
            BPRVCHT.TR_TIME = BPRVCH01.TR_TIME;
            BPRVCHT.TR_BK = BPRVCH01.TR_BK;
            BPRVCHT.TR_BR = BPRVCH01.TR_BR;
            BPRVCHT.TR_TELLER = BPRVCH01.TR_TELLER;
            BPRVCHT.TM_NO = BPRVCH01.TM_NO;
            BPRVCHT.CHNL_NO = BPRVCH01.CHNL_NO;
            BPRVCHT.EC_IND = BPRVCH01.EC_IND;
            BPRVCHT.ORG_DATE = BPRVCH01.ORG_DATE;
            BPRVCHT.ORG_VCHNO = BPRVCH01.ORG_VCHNO;
            BPRVCHT.GEN_TYPE = BPRVCH01.GEN_TYPE;
            BPRVCHT.TR_TYPE = BPRVCH01.TR_TYPE;
            BPRVCHT.ODE_FLG = BPRVCH01.ODE_FLG;
            BPRVCHT.ODE_GRP_NO = BPRVCH01.ODE_GRP_NO;
            BPRVCHT.OTH_TR_DATE = BPRVCH01.OTH_TR_DATE;
            BPRVCHT.OTHSYS_ID = BPRVCH01.OTHSYS_ID;
            BPRVCHT.OTHSYS_KEY = BPRVCH01.OTHSYS_KEY;
            BPRVCHT.ANS_CD1 = BPRVCH01.ANS_CD1;
            BPRVCHT.ANS_CD2 = BPRVCH01.ANS_CD2;
            BPRVCHT.ANS_CD3 = BPRVCH01.ANS_CD3;
            BPRVCHT.ANS_CD4 = BPRVCH01.ANS_CD4;
            BPRVCHT.ANS_CD5 = BPRVCH01.ANS_CD5;
            BPRVCHT.ANS_CD6 = BPRVCH01.ANS_CD6;
            BPRVCHT.ANS_CD7 = BPRVCH01.ANS_CD7;
            BPRVCHT.ANS_CD8 = BPRVCH01.ANS_CD8;
            BPRVCHT.ANS_CD9 = BPRVCH01.ANS_CD9;
            BPRVCHT.ANS_CD10 = BPRVCH01.ANS_CD10;
            BPRVCHT.BOOK_FLG = BPRVCH01.BOOK_FLG;
            BPRVCHT.BR = BPRVCH01.BR;
            BPRVCHT.ITM = BPRVCH01.ITM;
            BPRVCHT.CCY = BPRVCH01.CCY;
            BPRVCHT.SIGN = BPRVCH01.SIGN;
            BPRVCHT.AMT = BPRVCH01.AMT;
            BPRVCHT.VAL_DATE = BPRVCH01.VAL_DATE;
            BPRVCHT.CNTR_TYPE = BPRVCH01.CNTR_TYPE;
            BPRVCHT.PROD_CODE = BPRVCH01.PROD_CODE;
            BPRVCHT.AC_NO = BPRVCH01.AC_NO;
            BPRVCHT.MIB_AC = BPRVCH01.MIB_NO;
            BPRVCHT.EVENT_CODE = BPRVCH01.EVENT_CODE;
            BPRVCHT.GLMST = BPRVCH01.GLMST;
            BPRVCHT.CNTR_TYPE_REL = BPRVCH01.CNTR_TYPE_REL;
            BPRVCHT.PROD_CODE_REL = BPRVCH01.PROD_CODE_REL;
            BPRVCHT.AC_NO_REL = BPRVCH01.AC_NO_REL;
            BPRVCHT.EVENT_CODE_REL = BPRVCH01.EVENT_CODE_REL;
            BPRVCHT.GLMST_REL = BPRVCH01.GLMST_REL;
            BPRVCHT.CI_NO = BPRVCH01.CI_NO;
            BPRVCHT.REF_NO = BPRVCH01.REF_NO;
            BPRVCHT.RED_FLG = BPRVCH01.RED_FLG;
            BPRVCHT.CRVS_NO = BPRVCH01.CRVS_NO;
            BPRVCHT.CRVS_SEQ = BPRVCH01.CRVS_SEQ;
            BPRVCHT.ONL_GMIB_FLG = BPRVCH01.ONL_GMIB_FLG;
            BPRVCHT.ONL_GVCH_FLG = BPRVCH01.ONL_GVCH_FLG;
            BPRVCHT.PORTFO_CD = BPRVCH01.PORTFO_CD;
            BPRVCHT.TR_GUP = BPRVCH01.TR_GUP;
            BPRVCHT.CHQ_NO = BPRVCH01.CHQ_NO;
            BPRVCHT.POST_DATE = BPRVCH01.POST_DATE;
            BPRVCHT.POST_NARR = BPRVCH01.POST_NARR;
            BPRVCHT.NARR_CD = BPRVCH01.NARR_CD;
            BPRVCHT.DESC = BPRVCH01.VCH_DESC;
            BPRVCHT.EFF_DAYS = BPRVCH01.EFF_DAYS;
            BPRVCHT.PRINT_FLG = BPRVCH01.PRINT_FLG;
            BPRVCHT.SUSPENSE_FLG = BPRVCH01.SUSPENSE_FLG;
            BPRVCHT.SUSPENSE_RSN = BPRVCH01.SUSPENSE_RSN;
            BPRVCHT.PAY_MAN = BPRVCH01.PAY_MAN;
            BPRVCHT.PAY_BR = BPRVCH01.PAY_BR;
            BPRVCHT.THEIR_AC = BPRVCH01.THEIR_AC;
            BPRVCHT.THEIR_CCY = BPRVCH01.THEIR_CCY;
            BPRVCHT.THEIR_AMT = BPRVCH01.THEIR_AMT;
            BPRVCHT.THEIR_RAT = BPRVCH01.THEIR_RAT;
            BPRVCHT.SETTLE_DT = BPRVCH01.SETTLE_DT;
            BPRVCHT.TLR_ID = BPRVCH01.TLR_ID;
            BPRVCHT.TLR_BR = BPRVCH01.TLR_BR;
            BPRVCHT.OTH_MAKER = BPRVCH01.OTH_MAKER;
            BPRVCHT.OTH_CHECKER = BPRVCH01.OTH_CHECKER;
            BPRVCHT.FLR = BPRVCH01.FLR;
            BPRVCHT.RES_CENT = BPRVCH01.RES_CENT;
            BPRVCHT.LINE = BPRVCH01.LINE;
            BPRVCHT.INTER_CLEAR = BPRVCH01.INTER_CLEAR;
            BPRVCHT.RESERVE = BPRVCH01.RESERVE;
            BPRVCHT.REQSYS_ID = BPRVCH01.REQSYS_ID;
            BPRVCHT.REQSYS_DT = BPRVCH01.REQSYS_DT;
            BPRVCHT.REQSYS_KEY = BPRVCH01.REQSYS_KEY;
            BPRVCHT.UPDTBL_DATE = BPRVCH01.UPDTBL_DATE;
            BPRVCHT.TS = BPRVCH01.TS;
        } else {
            IBS.init(SCCGWA, BPRVCH02);
            BPRVCH02.KEY.AC_DATE = AIB8546_AWA_8546.ACDATE;
            BPRVCH02.KEY.SET_SEQ = AIB8546_AWA_8546.SEQ;
            BPRVCH02.KEY.SET_NO = AIB8546_AWA_8546.SETNO;
            if (AIB8546_AWA_8546.SETNO == null) AIB8546_AWA_8546.SETNO = "";
            JIBS_tmp_int = AIB8546_AWA_8546.SETNO.length();
            for (int i=0;i<12-JIBS_tmp_int;i++) AIB8546_AWA_8546.SETNO += " ";
            if (AIB8546_AWA_8546.SETNO.substring(11 - 1, 11 + 2 - 1).trim().length() == 0) BPRVCH02.KEY.PART_NO = 0;
            else BPRVCH02.KEY.PART_NO = Integer.parseInt(AIB8546_AWA_8546.SETNO.substring(11 - 1, 11 + 2 - 1));
            T00_READ_BPTVCH02();
            if (pgmRtn) return;
            BPRVCHT.KEY.AC_DATE = BPRVCH02.KEY.AC_DATE;
            BPRVCHT.KEY.SET_NO = BPRVCH02.KEY.SET_NO;
            BPRVCHT.KEY.SET_SEQ = BPRVCH02.KEY.SET_SEQ;
            BPRVCHT.KEY.PART_NO = (short) BPRVCH02.KEY.PART_NO;
            BPRVCHT.AI_SEQ = BPRVCH02.KEY.AI_SEQ;
            BPRVCHT.JRN_NO = BPRVCH02.KEY.JRN_NO;
            BPRVCHT.AP_MMO = BPRVCH02.KEY.AP_MMO;
            BPRVCHT.TR_CODE = BPRVCH02.KEY.TR_CODE;
            BPRVCHT.TR_MMO = BPRVCH02.KEY.TR_MMO;
            BPRVCHT.TR_DATE = BPRVCH02.TR_DATE;
            BPRVCHT.TR_TIME = BPRVCH02.TR_TIME;
            BPRVCHT.TR_BK = BPRVCH02.TR_BK;
            BPRVCHT.TR_BR = BPRVCH02.TR_BR;
            BPRVCHT.TR_TELLER = BPRVCH02.TR_TELLER;
            BPRVCHT.TM_NO = BPRVCH02.TM_NO;
            BPRVCHT.CHNL_NO = BPRVCH02.CHNL_NO;
            BPRVCHT.EC_IND = BPRVCH02.EC_IND;
            BPRVCHT.ORG_DATE = BPRVCH02.ORG_DATE;
            BPRVCHT.ORG_VCHNO = BPRVCH02.ORG_VCHNO;
            BPRVCHT.GEN_TYPE = BPRVCH02.GEN_TYPE;
            BPRVCHT.TR_TYPE = BPRVCH02.TR_TYPE;
            BPRVCHT.ODE_FLG = BPRVCH02.ODE_FLG;
            BPRVCHT.ODE_GRP_NO = BPRVCH02.ODE_GRP_NO;
            BPRVCHT.OTH_TR_DATE = BPRVCH02.OTH_TR_DATE;
            BPRVCHT.OTHSYS_ID = BPRVCH02.OTHSYS_ID;
            BPRVCHT.OTHSYS_KEY = BPRVCH02.OTHSYS_KEY;
            BPRVCHT.ANS_CD1 = BPRVCH02.ANS_CD1;
            BPRVCHT.ANS_CD2 = BPRVCH02.ANS_CD2;
            BPRVCHT.ANS_CD3 = BPRVCH02.ANS_CD3;
            BPRVCHT.ANS_CD4 = BPRVCH02.ANS_CD4;
            BPRVCHT.ANS_CD5 = BPRVCH02.ANS_CD5;
            BPRVCHT.ANS_CD6 = BPRVCH02.ANS_CD6;
            BPRVCHT.ANS_CD7 = BPRVCH02.ANS_CD7;
            BPRVCHT.ANS_CD8 = BPRVCH02.ANS_CD8;
            BPRVCHT.ANS_CD9 = BPRVCH02.ANS_CD9;
            BPRVCHT.ANS_CD10 = BPRVCH02.ANS_CD10;
            BPRVCHT.BOOK_FLG = BPRVCH02.BOOK_FLG;
            BPRVCHT.BR = BPRVCH02.BR;
            BPRVCHT.ITM = BPRVCH02.ITM;
            BPRVCHT.CCY = BPRVCH02.CCY;
            BPRVCHT.SIGN = BPRVCH02.SIGN;
            BPRVCHT.AMT = BPRVCH02.AMT;
            BPRVCHT.VAL_DATE = BPRVCH02.VAL_DATE;
            BPRVCHT.CNTR_TYPE = BPRVCH02.CNTR_TYPE;
            BPRVCHT.PROD_CODE = BPRVCH02.PROD_CODE;
            BPRVCHT.AC_NO = BPRVCH02.AC_NO;
            BPRVCHT.MIB_AC = BPRVCH02.MIB_NO;
            BPRVCHT.EVENT_CODE = BPRVCH02.EVENT_CODE;
            BPRVCHT.GLMST = BPRVCH02.GLMST;
            BPRVCHT.CNTR_TYPE_REL = BPRVCH02.CNTR_TYPE_REL;
            BPRVCHT.PROD_CODE_REL = BPRVCH02.PROD_CODE_REL;
            BPRVCHT.AC_NO_REL = BPRVCH02.AC_NO_REL;
            BPRVCHT.EVENT_CODE_REL = BPRVCH02.EVENT_CODE_REL;
            BPRVCHT.GLMST_REL = BPRVCH02.GLMST_REL;
            BPRVCHT.CI_NO = BPRVCH02.CI_NO;
            BPRVCHT.REF_NO = BPRVCH02.REF_NO;
            BPRVCHT.RED_FLG = BPRVCH02.RED_FLG;
            BPRVCHT.CRVS_NO = BPRVCH02.CRVS_NO;
            BPRVCHT.CRVS_SEQ = BPRVCH02.CRVS_SEQ;
            BPRVCHT.ONL_GMIB_FLG = BPRVCH02.ONL_GMIB_FLG;
            BPRVCHT.ONL_GVCH_FLG = BPRVCH02.ONL_GVCH_FLG;
            BPRVCHT.PORTFO_CD = BPRVCH02.PORTFO_CD;
            BPRVCHT.TR_GUP = BPRVCH02.TR_GUP;
            BPRVCHT.CHQ_NO = BPRVCH02.CHQ_NO;
            BPRVCHT.POST_DATE = BPRVCH02.POST_DATE;
            BPRVCHT.POST_NARR = BPRVCH02.POST_NARR;
            BPRVCHT.NARR_CD = BPRVCH02.NARR_CD;
            BPRVCHT.DESC = BPRVCH02.VCH_DESC;
            BPRVCHT.EFF_DAYS = BPRVCH02.EFF_DAYS;
            BPRVCHT.PRINT_FLG = BPRVCH02.PRINT_FLG;
            BPRVCHT.SUSPENSE_FLG = BPRVCH02.SUSPENSE_FLG;
            BPRVCHT.SUSPENSE_RSN = BPRVCH02.SUSPENSE_RSN;
            BPRVCHT.PAY_MAN = BPRVCH02.PAY_MAN;
            BPRVCHT.PAY_BR = BPRVCH02.PAY_BR;
            BPRVCHT.THEIR_AC = BPRVCH02.THEIR_AC;
            BPRVCHT.THEIR_CCY = BPRVCH02.THEIR_CCY;
            BPRVCHT.THEIR_AMT = BPRVCH02.THEIR_AMT;
            BPRVCHT.THEIR_RAT = BPRVCH02.THEIR_RAT;
            BPRVCHT.SETTLE_DT = BPRVCH02.SETTLE_DT;
            BPRVCHT.TLR_ID = BPRVCH02.TLR_ID;
            BPRVCHT.TLR_BR = BPRVCH02.TLR_BR;
            BPRVCHT.OTH_MAKER = BPRVCH02.OTH_MAKER;
            BPRVCHT.OTH_CHECKER = BPRVCH02.OTH_CHECKER;
            BPRVCHT.FLR = BPRVCH02.FLR;
            BPRVCHT.RES_CENT = BPRVCH02.RES_CENT;
            BPRVCHT.LINE = BPRVCH02.LINE;
            BPRVCHT.INTER_CLEAR = BPRVCH02.INTER_CLEAR;
            BPRVCHT.RESERVE = BPRVCH02.RESERVE;
            BPRVCHT.REQSYS_ID = BPRVCH02.REQSYS_ID;
            BPRVCHT.REQSYS_DT = BPRVCH02.REQSYS_DT;
            BPRVCHT.REQSYS_KEY = BPRVCH02.REQSYS_KEY;
            BPRVCHT.UPDTBL_DATE = BPRVCH02.UPDTBL_DATE;
            BPRVCHT.TS = BPRVCH02.TS;
        }
        R00_01_OUTPUT_INFO();
        if (pgmRtn) return;
    }
    public void R00_01_OUTPUT_INFO() throws IOException,SQLException,Exception {
        AICX506.Q_TR_DT = BPRVCHT.TR_DATE;
        AICX506.Q_TR_TM = BPRVCHT.TR_TIME;
        AICX506.Q_AC_DT = BPRVCHT.KEY.AC_DATE;
        AICX506.Q_VAL_DT = BPRVCHT.VAL_DATE;
        AICX506.Q_VCHNO = BPRVCHT.KEY.SET_NO;
        AICX506.Q_SEQ = BPRVCHT.KEY.SET_SEQ;
        AICX506.Q_JRNNO = BPRVCHT.JRN_NO;
        CEP.TRC(SCCGWA, AICX506.Q_JRNNO);
        AICX506.Q_TX_CD = BPRVCHT.TR_CODE;
        AICX506.Q_TYP = BPRVCHT.GEN_TYPE;
        AICX506.Q_TR_BR = BPRVCHT.TR_BR;
        AICX506.Q_BR = BPRVCHT.BR;
        AICX506.Q_ITM = BPRVCHT.ITM;
        AICX506.Q_CCY = BPRVCHT.CCY;
        AICX506.Q_DRCRFLG = BPRVCHT.SIGN;
        AICX506.Q_AMT = BPRVCHT.AMT;
        AICX506.Q_EC_IND = BPRVCHT.EC_IND;
        AICX506.Q_VCHRF_NO = BPRVCHT.AC_NO;
        AICX506.Q_BR_AC = BPRVCHT.MIB_AC;
        AICX506.Q_CI_NO = BPRVCHT.CI_NO;
        AICX506.Q_OPPO_NO = BPRVCHT.THEIR_AC;
        AICX506.Q_BSREF_NO = BPRVCHT.OTHSYS_KEY;
        AICX506.Q_PRDMO_CD = BPRVCHT.CNTR_TYPE;
        AICX506.Q_PROD_CD = BPRVCHT.PROD_CODE;
        AICX506.Q_EVEN_CD = BPRVCHT.EVENT_CODE;
        AICX506.Q_GL_MSTNO = BPRVCHT.GLMST;
        AICX506.Q_APP = BPRVCHT.AP_MMO;
        AICX506.Q_CHNL_NO = BPRVCHT.CHNL_NO;
        AICX506.Q_TLR_NO = BPRVCHT.TR_TELLER;
        AICX506.Q_TRM_NO = BPRVCHT.TM_NO;
        AICX506.Q_TRN_TYP = BPRVCHT.TR_TYPE;
        AICX506.Q_ODE_FLG = BPRVCHT.ODE_FLG;
        AICX506.Q_VCHGR_NO = BPRVCHT.ODE_GRP_NO;
        AICX506.Q_RED_FLG = BPRVCHT.RED_FLG;
        AICX506.Q_REF_NO = BPRVCHT.REF_NO;
        AICX506.Q_CREV_NO = BPRVCHT.CRVS_NO;
        AICX506.Q_CRVS_SEQ = BPRVCHT.CRVS_SEQ;
        AICX506.Q_TR_MMO = BPRVCHT.TR_MMO;
        AICX506.Q_NARR_CD = BPRVCHT.NARR_CD;
        if (BPRVCHT.ODE_GRP_NO == 0) {
            AICX506.Q_TXN_NARR = BPRVCHT.POST_NARR;
        } else {
            AICX506.Q_TXN_NARR = " ";
        }
        AICX506.Q_DESC = BPRVCHT.DESC;
        AICX506.Q_CLEAN_DT = BPRVCHT.SETTLE_DT;
        AICX506.Q_PORT_CD = BPRVCHT.PORTFO_CD;
        AICX506.Q_RES_CENT = BPRVCHT.RES_CENT;
        AICX506.Q_LINE = BPRVCHT.LINE;
        AICX506.Q_INSIDE = BPRVCHT.INTER_CLEAR;
        AICX506.Q_SPARE = BPRVCHT.RESERVE;
        AICX506.Q_TLR_BR = BPRVCHT.TLR_BR;
        AICX506.Q_TLR_ID = BPRVCHT.TLR_ID;
        S000_03_01_OUTPUT();
        if (pgmRtn) return;
    }
    public void S000_03_01_OUTPUT() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, SCCFMT);
        SCCFMT.FMTID = "AIX23";
        SCCFMT.DATA_PTR = AICX506;
        SCCFMT.DATA_LEN = 622;
        IBS.FMT(SCCGWA, SCCFMT);
    }
    public void S000_04_01_OUTPUT() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, SCCFMT);
        SCCFMT.FMTID = "AIX27";
        SCCFMT.DATA_PTR = WS_OUTPUT;
        SCCFMT.DATA_LEN = 76;
        IBS.FMT(SCCGWA, SCCFMT);
    }
    public void T00_READ_BPTVCH01() throws IOException,SQLException,Exception {
        BPTVCH01_RD = new DBParm();
        BPTVCH01_RD.TableName = "BPTVCH01";
        BPTVCH01_RD.where = "AC_DATE = :BPRVCH01.KEY.AC_DATE "
            + "AND SET_NO = :BPRVCH01.KEY.SET_NO "
            + "AND SET_SEQ = :BPRVCH01.KEY.SET_SEQ";
        IBS.READ(SCCGWA, BPRVCH01, this, BPTVCH01_RD);
        if (SCCGWA.COMM_AREA.DBIO_FLG == '0') {
            WS_CONSTANT.WS_DB2_REC_STATUS = 'F';
        } else if (SCCGWA.COMM_AREA.DBIO_FLG == '1') {
            WS_CONSTANT.WS_DB2_REC_STATUS = 'N';
        } else {
            SCCEXCP.MSG_TEXT.MSG_TEXT_D.TABLE_NAME = "BPRVCH01";
            SCCEXCP.MSG_TEXT.SYS_INFO = IBS.CLS2CPY(SCCGWA, SCCEXCP.MSG_TEXT.MSG_TEXT_D);
            B_DB_EXCP();
            if (pgmRtn) return;
        }
    }
    public void T00_READ_BPTVCH02() throws IOException,SQLException,Exception {
        BPTVCH02_RD = new DBParm();
        BPTVCH02_RD.TableName = "BPTVCH02";
        BPTVCH02_RD.where = "AC_DATE = :BPRVCH02.KEY.AC_DATE "
            + "AND SET_NO = :BPRVCH02.KEY.SET_NO "
            + "AND SET_SEQ = :BPRVCH02.KEY.SET_SEQ";
        IBS.READ(SCCGWA, BPRVCH02, this, BPTVCH02_RD);
        if (SCCGWA.COMM_AREA.DBIO_FLG == '0') {
            WS_CONSTANT.WS_DB2_REC_STATUS = 'F';
        } else if (SCCGWA.COMM_AREA.DBIO_FLG == '1') {
            WS_CONSTANT.WS_DB2_REC_STATUS = 'N';
        } else {
            SCCEXCP.MSG_TEXT.MSG_TEXT_D.TABLE_NAME = "BPRVCH02";
            SCCEXCP.MSG_TEXT.SYS_INFO = IBS.CLS2CPY(SCCGWA, SCCEXCP.MSG_TEXT.MSG_TEXT_D);
            B_DB_EXCP();
            if (pgmRtn) return;
        }
    }
    public void S000_CALL_BPZPQORG() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-P-INQ-ORG", BPCPQORG);
        if (BPCPQORG.RC.RC_CODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, BPCPQORG.RC);
            CEP.ERR(SCCGWA, JIBS_tmp_str[0]);
        }
    }
    public void S000_CALL_SCZQJRN() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "SC-INQ-HOSTJRN", SCCQJRN);
        CEP.TRC(SCCGWA, SCCQJRN.OUT_DATA.RTN_CODE);
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG, WS_INFO);
    }
    public void S00_CALL_BPZFTLRQ() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCFTLRQ);
        BPCFTLRQ.INFO.TLR = SCCGWA.COMM_AREA.TL_ID;
        IBS.CALLCPN(SCCGWA, "BP-F-TLR-INF-QUERY", BPCFTLRQ);
        if (BPCFTLRQ.RC.RC_CODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, BPCFTLRQ.RC);
            CEP.ERR(SCCGWA, JIBS_tmp_str[0]);
        }
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        pgmRtn = true;
        return;
    }
    public void B_MPAG() throws IOException,SQLException,Exception {
    if (!SCCGWA.COMM_AREA.BSP_FLG.equalsIgnoreCase("BSP") && !SCCGWA.COMM_AREA.CHNL.equalsIgnoreCase("BAT")) { //FROM #IFDEF ONL
        JIBS_tmp_str[9] = "SCZMPAG";
        Class<?>clazz = Class.forName(JIBS_tmp_str[9].trim());
        Object obj = clazz.newInstance();
        Method m = clazz.getDeclaredMethod("MP",new Class[]{SCCGWA.getClass(), SCCMPAG.getClass()});
        m.invoke(obj, SCCGWA, SCCMPAG);
        if (SCCGWA.COMM_AREA.EXCP_FLG == 'Y') {
            Z_RET();
            if (pgmRtn) return;
        }
    } else { //FROM #ELSE
    } //FROM #ENDIF
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
