package com.hisun.AI;

public class AIZPCKOP_WS_COMPUTE {
    int WS_CPU1_DATE = 0;
    AIZPCKOP_REDEFINES5 REDEFINES5 = new AIZPCKOP_REDEFINES5();
    int WS_CPU2_DATE = 0;
    AIZPCKOP_REDEFINES10 REDEFINES10 = new AIZPCKOP_REDEFINES10();
}
