package com.hisun.AI;

import java.io.IOException;
import java.sql.SQLException;

import com.hisun.BP.BPCPNHIS;
import com.hisun.BP.BPCPQGLM;
import com.hisun.BP.BPCPRMR;
import com.hisun.BP.BPCQBKPM;
import com.hisun.BP.BPCSGSEQ;
import com.hisun.BP.BPRANS;
import com.hisun.BP.BPRVCHT;
import com.hisun.BP.BPRVWA;
import com.hisun.SC.SCCBINF;
import com.hisun.SC.SCCCALL;
import com.hisun.SC.SCCCLDT;
import com.hisun.SC.SCCEXCP;
import com.hisun.SC.SCCFMT;
import com.hisun.SC.SCCGBPA_BP_AREA;
import com.hisun.SC.SCCGSCA_SC_AREA;
import com.hisun.SC.SCCGWA;
import com.hisun.SC.SCCMSG;

public class AIZPGLPO {
    boolean pgmRtn = false;
    String PGM_SCSSCLDT = "SCSSCLDT";
    String WS_ERR_MSG = " ";
    String WS_ERR_INFO = " ";
    short WS_FLD_NO = 0;
    String WS_TELLER_ID = " ";
    String WS_AUTH_ID = " ";
    int WS_VCH_CNT = 0;
    short WS_AC_IDX = 0;
    AIZPGLPO_WS_AUTO_MAT_DATA WS_AUTO_MAT_DATA = new AIZPGLPO_WS_AUTO_MAT_DATA();
    AIZPGLPO_WS_GROUP_NO WS_GROUP_NO = new AIZPGLPO_WS_GROUP_NO();
    short WS_I = 0;
    short[] WS_SORT_I = new short[1000];
    AIZPGLPO_WS_IDX WS_IDX = new AIZPGLPO_WS_IDX();
    AIZPGLPO_WS_TEMP WS_TEMP = new AIZPGLPO_WS_TEMP();
    AIZPGLPO_WS_TMP1_KEY WS_TMP1_KEY = new AIZPGLPO_WS_TMP1_KEY();
    AIZPGLPO_WS_TMP2_KEY WS_TMP2_KEY = new AIZPGLPO_WS_TMP2_KEY();
    long WS_BSP_BAT_NO = 0;
    short WS_SUB_AC_IDX = 0;
    int WS_BSP03_CNT = 0;
    String WS_COA_FLG = " ";
    String WS_SUS_ITM = " ";
    String WS_SUS_REASON = " ";
    String WS_DD_AC_NO = " ";
    String WS_TD_AC_NO = " ";
    int WS_MAX_SEQ = 0;
    String WS_PRD_CD = " ";
    int WS_GLMST_TMP = 0;
    int WS_BR_TMP = 0;
    AIZPGLPO_WS_OLD_DATA WS_OLD_DATA = new AIZPGLPO_WS_OLD_DATA();
    int WS_DAT_01 = 0;
    AIZPGLPO_REDEFINES57 REDEFINES57 = new AIZPGLPO_REDEFINES57();
    int WS_DAT_02 = 0;
    AIZPGLPO_REDEFINES62 REDEFINES62 = new AIZPGLPO_REDEFINES62();
    AIZPGLPO_WS_ITM_INFO WS_ITM_INFO = new AIZPGLPO_WS_ITM_INFO();
    char WS_LAST_DATE_FLAG = ' ';
    char WS_NEXT_DATE_FLAG = ' ';
    char WS_AUTO_GEN_FLG = ' ';
    char WS_AUTO_MATCH_FLG = ' ';
    char WS_VAL_DATE_FLG = ' ';
    char WS_MODE_TYPE = ' ';
    String WS_VCHT_GLBOOK = " ";
    String WS_VCHT_ITM = " ";
    int WS_VCHT_BR = 0;
    String WS_VCHT_CCY = " ";
    int WS_MST_CNT = 0;
    int WS_AC_DATE = 0;
    char WS_ODE_FLG = ' ';
    char WS_REWRITE_HIS_FLG = ' ';
    char WS_SUS_FLG = ' ';
    AIZPGLPO_WS_CONSTANT WS_CONSTANT = new AIZPGLPO_WS_CONSTANT();
    char WS_ITM_LVL_FLG = ' ';
    AICMSG_ERROR_MSG AICMSG_ERROR_MSG = new AICMSG_ERROR_MSG();
    SCCBINF SCCBINF = new SCCBINF();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    SCCFMT SCCFMT = new SCCFMT();
    SCCCLDT SCCCLDT = new SCCCLDT();
    BPRVCHT BPRVCHT = new BPRVCHT();
    BPCQBKPM BPCQBKPM = new BPCQBKPM();
    BPCPRMR BPCPRMR = new BPCPRMR();
    BPCPQGLM BPCPQGLM = new BPCPQGLM();
    SCCCBSTS SCCCBSTS = new SCCCBSTS();
    SCCRWBSP SCCRWBSP = new SCCRWBSP();
    AIRBSP03 AIRBSP03 = new AIRBSP03();
    SCCBSPS SCCBSPS = new SCCBSPS();
    AICOUGLB AICOUGLB = new AICOUGLB();
    BPCSGSEQ BPCSGSEQ = new BPCSGSEQ();
    BPCPNHIS BPCPNHIS = new BPCPNHIS();
    AICOVLOG AICOVLOG = new AICOVLOG();
    BPRVWA BPRVWA = new BPRVWA();
    BPRANS BPRANS = new BPRANS();
    AICITMA AICITMA = new AICITMA();
    AIRPAI7 AIRPAI7 = new AIRPAI7();
    AIRITM AIRITM = new AIRITM();
    AIRMST AIRMST = new AIRMST();
    AIRMST AIRNMST = new AIRMST();
    AIRMST AIROMST = new AIRMST();
    AIRHMST AIRHMST = new AIRHMST();
    AIRHIS AIRHIS = new AIRHIS();
    AIRITUS AIRITUS = new AIRITUS();
    AIRITAD AIRITAD = new AIRITAD();
    SCCGWA SCCGWA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA SCCGBPA_BP_AREA;
    BPRVWA BPRRVWA;
    BPRANS BPRRANS;
    AICITMA AICRITM;
    AICOGLPO AICOGLPO;
    public void MP(SCCGWA SCCGWA, AICOGLPO AICOGLPO) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        this.AICOGLPO = AICOGLPO;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        if (pgmRtn) return;
        B000_MAIN_PROC();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, "AIZPGLPO return!");
        Z_RET();
        if (pgmRtn) return;
        JIBS_RETURN();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        SCCGBPA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        BPRRVWA = (BPRVWA) AICOGLPO.VWA_PTR;
        AICRITM = (AICITMA) AICOGLPO.ITM_PTR;
        BPRRANS = (BPRANS) AICOGLPO.ANS_PTR;
        WS_AC_DATE = AICOGLPO.AC_DATE;
        CEP.TRC(SCCGWA, AICOGLPO.TR_CODE);
        CEP.TRC(SCCGWA, WS_AC_DATE);
        WS_MODE_TYPE = 'O';
        BPRVWA.BASIC_AREA.CNT = BPRRVWA.BASIC_AREA.CNT;
