package com.hisun.AI;

public class AIZSQSUS_WS_OUTPUT_VCH1 {
    int L3_IPT_DATE = 0;
    String L3_RVS_NO = " ";
    int L3_RVS_SEQ = 0;
    String L3_SET_NO = " ";
    short L3_SET_SEQ = 0;
    String L3_BOOK_FLG = " ";
    String L3_MIB_NO = " ";
    int L3_GRVS_BR = 0;
    String L3_BP_ITM = " ";
    int L3_HS_BR = 0;
    String L3_GRVS_ITM = " ";
    int L3_SEQ = 0;
    String L3_CCY = " ";
    char L3_SIGN = ' ';
    double L3_GRVS_AMT = 0;
    char AIZSQSUS_FILLER115 = 0X01;
    String L3_GRVS_DESC = " ";
    char AIZSQSUS_FILLER117 = 0X02;
    char L3_GRVS_STS = ' ';
    String L3_PROD_CODE = " ";
    String L3_CNTR_NO = " ";
    String L3_EVT_CD = " ";
    String L3_CI_NO = " ";
    char L3_RVS_TYP = ' ';
    char L3_RVS_KND = ' ';
    int L3_MIB_SEQ = 0;
    double L3_CRVS_AMT = 0;
    char AIZSQSUS_FILLER127 = 0X01;
    double L3_GRVS_BAL = 0;
    char AIZSQSUS_FILLER129 = 0X01;
    int L3_TX_DT = 0;
    int L3_VAL_DATE = 0;
    String L3_CNTR_TYP = " ";
    String L3_THEIR_AC = " ";
    int L3_GLMST = 0;
    String L3_TR_CODE = " ";
    int L3_TR_BR = 0;
    String L3_TR_TELLER = " ";
    String L3_TX_SUP_TLR = " ";
    String L3_AP_MMO = " ";
    String L3_CHNL_NO = " ";
    String L3_REF_NO = " ";
    String L3_DESC = " ";
    char AIZSQSUS_FILLER143 = 0X02;
}
