package com.hisun.AI;

public class AIZSRVS_WS_CRVS_OUT_DATA {
    String WS_C_O_RVS_NO = " ";
    int WS_C_O_RVS_SEQ = 0;
    String WS_C_O_AC = " ";
    String WS_C_O_CCY = " ";
    char WS_C_O_STS = ' ';
    int WS_C_O_TX_DT = 0;
    int WS_C_O_JYRQ = 0;
    double WS_C_O_AMT = 0;
    char AIZSRVS_FILLER90 = 0X01;
    String WS_C_O_CI_NO = " ";
    String WS_C_O_TR_CODE = " ";
    String WS_C_O_TR_TELLER = " ";
    int WS_C_O_TR_BR = 0;
    String WS_C_O_SET_NO = " ";
    short WS_C_O_SET_SEQ = 0;
    String WS_C_O_APP = " ";
    String WS_C_O_CHNL_NO = " ";
    String WS_C_O_TX_SUP_TLR = " ";
    String WS_C_O_PART = " ";
    char AIZSRVS_FILLER101 = 0X02;
    String WS_C_O_CPLX = " ";
    String WS_C_O_CPMX = " ";
    char WS_C_O_GZLB = ' ';
    String WS_C_O_XZKM = " ";
    int WS_C_O_SXH1 = 0;
    char WS_C_O_GZZL = ' ';
    String WS_C_O_HZFM = " ";
    int WS_C_O_HSJG = 0;
    char WS_C_O_JDBZ = ' ';
    int WS_C_O_KMZH = 0;
    int WS_C_O_QXRQ = 0;
    String WS_C_O_SJLX = " ";
    String WS_C_O_YWBH = " ";
    int WS_C_O_JYJG = 0;
    String WS_C_O_THEIR_AC = " ";
    String WS_C_O_PAY_MAN = " ";
    char AIZSRVS_FILLER118 = 0X02;
    int WS_C_O_PAY_BR = 0;
    String WS_C_O_BILL_NO = " ";
}
