package com.hisun.PS;

public class PSB1100_AWA_1100 {
    public String AREA_NO = " ";
    public short AREA_NO_NO = 0;
    public int EXG_DT = 0;
    public short EXG_DT_NO = 0;
    public short EXG_TMS = 0;
    public short EXG_TMS_NO = 0;
    public char AC_TYP = ' ';
    public short AC_TYP_NO = 0;
    public String CREV_NO = " ";
    public short CREV_NO_NO = 0;
    public String OUR_ACNO = " ";
    public short OUR_ACNO_NO = 0;
    public String PAY_PSWD = " ";
    public short PAY_PSWD_NO = 0;
    public String OUR_ACNM = " ";
    public short OUR_ACNM_NO = 0;
    public String EXG_CCY = " ";
    public short EXG_CCY_NO = 0;
    public char CASH_ID = ' ';
    public short CASH_ID_NO = 0;
    public double EXG_AMT = 0;
    public short EXG_AMT_NO = 0;
    public String VOUCH_CD = " ";
    public short VOUCH_CD_NO = 0;
    public String CERT_NO = " ";
    public short CERT_NO_NO = 0;
    public String EXG_NO = " ";
    public short EXG_NO_NO = 0;
    public String EX_INSNM = " ";
    public short EX_INSNM_NO = 0;
    public String OTH_ACNO = " ";
    public short OTH_ACNO_NO = 0;
    public String OTH_ACNM = " ";
    public short OTH_ACNM_NO = 0;
    public String RMK = " ";
    public short RMK_NO = 0;
    public int QF_DT = 0;
    public short QF_DT_NO = 0;
}
