package com.hisun.PS;

public class PSB2100_AWA_2100 {
    public String AREA_NO = " ";
    public short AREA_NO_NO = 0;
    public int EXG_DT = 0;
    public short EXG_DT_NO = 0;
    public short EXG_TMS = 0;
    public short EXG_TMS_NO = 0;
    public String OUR_ACNO = " ";
    public short OUR_ACNO_NO = 0;
    public String OUR_ACNM = " ";
    public short OUR_ACNM_NO = 0;
    public String VOUCH_CD = " ";
    public short VOUCH_CD_NO = 0;
    public String CERT_NO = " ";
    public short CERT_NO_NO = 0;
    public String T_EXG_NO = " ";
    public short T_EXG_NO_NO = 0;
    public String EX_INSNM = " ";
    public short EX_INSNM_NO = 0;
    public String OTH_ACNO = " ";
    public short OTH_ACNO_NO = 0;
    public String OTH_ACNM = " ";
    public short OTH_ACNM_NO = 0;
    public String EXG_CCY = " ";
    public short EXG_CCY_NO = 0;
    public char CASH_ID = ' ';
    public short CASH_ID_NO = 0;
    public double EXG_AMT = 0;
    public short EXG_AMT_NO = 0;
    public String RMK = " ";
    public short RMK_NO = 0;
    public char RTN_FLG = ' ';
    public short RTN_FLG_NO = 0;
    public String R_RSN_CD = " ";
    public short R_RSN_CD_NO = 0;
    public String RSN_DSC = " ";
    public short RSN_DSC_NO = 0;
}
