package com.hisun.PS;

import com.hisun.SC.*;
import com.hisun.BP.*;

import java.io.IOException;
import java.sql.SQLException;

public class PSOT4220 {
    String EXG_BK_NO = "001";
    String EXG_AREA_NO = "000001";
    String OUTPUT_FMT = "PS420";
    String U_PSZBSP01 = "PS-REB-BSP-01";
    char ERROR = 'E';
    PSOT4220_WS_VARIABLES WS_VARIABLES = new PSOT4220_WS_VARIABLES();
    PSCMSG_ERROR_MSG ERROR_MSG = new PSCMSG_ERROR_MSG();
    PSCBSP01 PSCBSP01 = new PSCBSP01();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCFMT SCCFMT = new SCCFMT();
    SCCMSG SCCMSG = new SCCMSG();
    SCCCKDT SCCCKDT = new SCCCKDT();
    PSROBLL PSROBLL = new PSROBLL();
    PSRIBLL PSRIBLL = new PSRIBLL();
    PSRPBIN PSRPBIN = new PSRPBIN();
    PSREINF PSREINF = new PSREINF();
    SCCGWA SCCGWA;
    SCCGAPV SCCGAPV;
    SCCBATH SCCBATH;
    BPREWA BPREWA;
    SCCGSCA_SC_AREA SC_AREA;
    SCCGBPA_BP_AREA BP_AREA;
    PSCB4220 PSCB4220;
    public void MP(SCCGWA SCCGWA, PSCB4220 PSCB4220) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        this.PSCB4220 = PSCB4220;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B200_CLR_PNT_PROC();
        CEP.TRC(SCCGWA, "PSOT4220 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        IBS.init(SCCGWA, WS_VARIABLES);
    }
    public void B200_CLR_PNT_PROC() throws IOException,SQLException,Exception {
        B210_CLR_PNT_PROC();
    }
    public void B210_CLR_PNT_PROC() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, "111");
        IBS.init(SCCGWA, PSCBSP01);
        CEP.TRC(SCCGWA, "222");
        PSCB4220.U_EXG_NO = "0000000000002";
        CEP.TRC(SCCGWA, PSCB4220.U_EXG_NO);
        CEP.TRC(SCCGWA, PSCB4220.EXG_CCY);
        CEP.TRC(SCCGWA, PSCB4220.REPT_DT);
        CEP.TRC(SCCGWA, PSCB4220.REPT_TMS);
        CEP.TRC(SCCGWA, PSCB4220.RT_DT);
        CEP.TRC(SCCGWA, PSCB4220.RT_TMS);
        CEP.TRC(SCCGWA, PSCB4220.TX_JRNNO);
        CEP.TRC(SCCGWA, PSCB4220.OUR_ACNO);
        CEP.TRC(SCCGWA, PSCB4220.OUR_ACNM);
        CEP.TRC(SCCGWA, PSCB4220.CASH_ID);
        CEP.TRC(SCCGWA, PSCB4220.T_EXG_NO);
        CEP.TRC(SCCGWA, PSCB4220.EXG_DC);
        CEP.TRC(SCCGWA, PSCB4220.VOUCH_CD);
        CEP.TRC(SCCGWA, PSCB4220.CERT_NO);
        CEP.TRC(SCCGWA, PSCB4220.CERT_DT);
        CEP.TRC(SCCGWA, PSCB4220.ISS_BKNO);
        CEP.TRC(SCCGWA, PSCB4220.EXP_DT);
        CEP.TRC(SCCGWA, PSCB4220.ISS_AMT);
        CEP.TRC(SCCGWA, PSCB4220.EXG_AMT);
        CEP.TRC(SCCGWA, PSCB4220.OTH_ACNO);
        CEP.TRC(SCCGWA, PSCB4220.OTH_ACNM);
        PSCBSP01.BK_NO = SCCGWA.COMM_AREA.TR_BANK;
        PSCBSP01.EXG_AREA_NO = EXG_AREA_NO;
        PSCBSP01.OUR_EXG_NO = PSCB4220.U_EXG_NO;
        PSCBSP01.EXG_CCY = PSCB4220.EXG_CCY;
        PSCBSP01.EXG_REPT_DT = PSCB4220.REPT_DT;
        PSCBSP01.EXG_REPT_TMS = PSCB4220.REPT_TMS;
        PSCBSP01.EXG_RT_DT = PSCB4220.RT_DT;
        PSCBSP01.EXG_RT_TMS = PSCB4220.RT_TMS;
        PSCBSP01.TX_JRNNO = PSCB4220.TX_JRNNO;
        CEP.TRC(SCCGWA, "333");
        PSCBSP01.OUR_ACNO = PSCB4220.OUR_ACNO;
        PSCBSP01.OUR_ACNM = PSCB4220.OUR_ACNM;
        PSCBSP01.CASH_ID = PSCB4220.CASH_ID;
        PSCBSP01.OTH_EXG_NO = PSCB4220.T_EXG_NO;
        PSCBSP01.EXG_DC = PSCB4220.EXG_DC;
        PSCBSP01.EXG_VOUCH_CD = PSCB4220.VOUCH_CD;
        PSCBSP01.EXG_CERT_NO = PSCB4220.CERT_NO;
        PSCBSP01.CERT_DT = PSCB4220.CERT_DT;
        PSCBSP01.ISS_BKNO = PSCB4220.ISS_BKNO;
        PSCBSP01.EXP_DT = PSCB4220.EXP_DT;
        PSCBSP01.ISS_AMT = PSCB4220.ISS_AMT;
        PSCBSP01.EXG_AMT = PSCB4220.EXG_AMT;
        PSCBSP01.OTH_ACNO = PSCB4220.OTH_ACNO;
        PSCBSP01.OTH_ACNM = PSCB4220.OTH_ACNM;
        CEP.TRC(SCCGWA, PSCB4220.U_EXG_NO);
        CEP.TRC(SCCGWA, PSCB4220.EXG_CCY);
        CEP.TRC(SCCGWA, PSCB4220.REPT_DT);
        CEP.TRC(SCCGWA, PSCB4220.REPT_TMS);
        CEP.TRC(SCCGWA, PSCB4220.RT_DT);
        CEP.TRC(SCCGWA, PSCB4220.RT_TMS);
        CEP.TRC(SCCGWA, PSCB4220.TX_JRNNO);
        CEP.TRC(SCCGWA, PSCB4220.OUR_ACNO);
        CEP.TRC(SCCGWA, PSCB4220.OUR_ACNM);
        CEP.TRC(SCCGWA, PSCB4220.CASH_ID);
        CEP.TRC(SCCGWA, PSCB4220.T_EXG_NO);
        CEP.TRC(SCCGWA, PSCB4220.EXG_DC);
        CEP.TRC(SCCGWA, PSCB4220.VOUCH_CD);
        CEP.TRC(SCCGWA, PSCB4220.CERT_NO);
        CEP.TRC(SCCGWA, PSCB4220.CERT_DT);
        CEP.TRC(SCCGWA, PSCB4220.ISS_BKNO);
        CEP.TRC(SCCGWA, PSCB4220.EXP_DT);
        CEP.TRC(SCCGWA, PSCB4220.ISS_AMT);
        CEP.TRC(SCCGWA, PSCB4220.EXG_AMT);
        CEP.TRC(SCCGWA, PSCB4220.OTH_ACNO);
        CEP.TRC(SCCGWA, PSCB4220.OTH_ACNM);
        S000_CALL_PSZBSP01();
    }
    public void S000_CALL_PSZBSP01() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, U_PSZBSP01, PSCBSP01);
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_VARIABLES.ERR_MSG);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
