package com.hisun.PS;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;
import com.hisun.BP.*;

import java.io.IOException;
import java.sql.SQLException;

public class PSOT2200 {
    int JIBS_tmp_int;
    String K_EXG_BK_NO = "001";
    String K_OUTPUT_FMT = "PS220";
    String CPN_U_PSZINDTP = "PS-P-INDT-PROC";
    char K_ERROR = 'E';
    String PGM_SCSSCKDT = "SCSSCKDT";
    String WS_ERR_MSG = " ";
    short WS_FLD_NO = 0;
    PSOT2200_WS_FMT WS_FMT = new PSOT2200_WS_FMT();
    PSCMSG_ERROR_MSG PSCMSG_ERROR_MSG = new PSCMSG_ERROR_MSG();
    PSCINDTP PSCINDTP = new PSCINDTP();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCFMT SCCFMT = new SCCFMT();
    SCCMSG SCCMSG = new SCCMSG();
    SCCCKDT SCCCKDT = new SCCCKDT();
    BPCPQORG BPCPQORG = new BPCPQORG();
    PSROBLL PSROBLL = new PSROBLL();
    PSRIBLL PSRIBLL = new PSRIBLL();
    PSRPBIN PSRPBIN = new PSRPBIN();
    PSREINF PSREINF = new PSREINF();
    SCCGWA SCCGWA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    PSB2200_AWA_2200 PSB2200_AWA_2200;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B200_CLR_PNT_PROC();
        B300_OUTPUT_PROC();
        CEP.TRC(SCCGWA, "PSOT2200 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "PSB2200_AWA_2200>");
        PSB2200_AWA_2200 = (PSB2200_AWA_2200) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
    }
    public void B200_CLR_PNT_PROC() throws IOException,SQLException,Exception {
        B210_CLR_PNT_PROC();
    }
    public void B210_CLR_PNT_PROC() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, PSB2200_AWA_2200.EXG_DT);
        CEP.TRC(SCCGWA, PSB2200_AWA_2200.EXG_TMS);
        CEP.TRC(SCCGWA, PSB2200_AWA_2200.OUR_ACNO);
        CEP.TRC(SCCGWA, PSB2200_AWA_2200.OUR_ACNM);
        CEP.TRC(SCCGWA, PSB2200_AWA_2200.EXG_CCY);
        CEP.TRC(SCCGWA, PSB2200_AWA_2200.CASH_ID);
        CEP.TRC(SCCGWA, PSB2200_AWA_2200.EXG_AMT);
        CEP.TRC(SCCGWA, PSB2200_AWA_2200.VOUCH_CD);
        CEP.TRC(SCCGWA, PSB2200_AWA_2200.CERT_NO);
        CEP.TRC(SCCGWA, PSB2200_AWA_2200.ISS_BKNO);
        CEP.TRC(SCCGWA, PSB2200_AWA_2200.ENCRY_NO);
        CEP.TRC(SCCGWA, PSB2200_AWA_2200.ISS_AMT);
        CEP.TRC(SCCGWA, PSB2200_AWA_2200.M_AMT);
        CEP.TRC(SCCGWA, PSB2200_AWA_2200.CERT_DT);
        CEP.TRC(SCCGWA, PSB2200_AWA_2200.EXP_DT);
        CEP.TRC(SCCGWA, PSB2200_AWA_2200.T_EXG_NO);
        CEP.TRC(SCCGWA, PSB2200_AWA_2200.EX_INSNM);
        CEP.TRC(SCCGWA, PSB2200_AWA_2200.OTH_ACNO);
        CEP.TRC(SCCGWA, PSB2200_AWA_2200.OTH_ACNM);
        CEP.TRC(SCCGWA, PSB2200_AWA_2200.RMK);
        CEP.TRC(SCCGWA, PSB2200_AWA_2200.RTN_FLG);
        CEP.TRC(SCCGWA, PSB2200_AWA_2200.R_RSN_CD);
        CEP.TRC(SCCGWA, PSB2200_AWA_2200.RSN_DSC);
        IBS.init(SCCGWA, PSCINDTP);
        IBS.init(SCCGWA, BPCPQORG);
        PSCINDTP.BK_NO = SCCGWA.COMM_AREA.TR_BANK;
        BPCPQORG.BR = SCCGWA.COMM_AREA.BR_DP.TR_BRANCH;
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.BR_DP.TR_BRANCH);
        S000_CALL_BPZPQORG();
        WS_FMT.WS_EXG_AREA_NO = "" + BPCPQORG.BRANCH_BR;
        JIBS_tmp_int = WS_FMT.WS_EXG_AREA_NO.length();
        for (int i=0;i<6-JIBS_tmp_int;i++) WS_FMT.WS_EXG_AREA_NO = "0" + WS_FMT.WS_EXG_AREA_NO;
        PSCINDTP.EXG_AREA_NO = WS_FMT.WS_EXG_AREA_NO;
        CEP.TRC(SCCGWA, BPCPQORG.BRANCH_BR);
        PSCINDTP.EXG_DT = PSB2200_AWA_2200.EXG_DT;
        PSCINDTP.EXG_TMS = PSB2200_AWA_2200.EXG_TMS;
        CEP.TRC(SCCGWA, PSB2200_AWA_2200.OUR_ACNO);
        PSCINDTP.OUR_ACNO = PSB2200_AWA_2200.OUR_ACNO;
        PSCINDTP.OUR_ACNM = PSB2200_AWA_2200.OUR_ACNM;
        CEP.TRC(SCCGWA, PSB2200_AWA_2200.OUR_ACNM);
        PSCINDTP.EXG_CCY = PSB2200_AWA_2200.EXG_CCY;
        PSCINDTP.CASH_ID = PSB2200_AWA_2200.CASH_ID;
        PSCINDTP.EXG_AMT = PSB2200_AWA_2200.EXG_AMT;
        PSCINDTP.EXG_VOUCH_CD = PSB2200_AWA_2200.VOUCH_CD;
        PSCINDTP.EXG_CERT_NO = PSB2200_AWA_2200.CERT_NO;
        PSCINDTP.ISS_BKNO = PSB2200_AWA_2200.ISS_BKNO;
        PSCINDTP.ENCRY_NO = PSB2200_AWA_2200.ENCRY_NO;
        PSCINDTP.ISS_AMT = PSB2200_AWA_2200.ISS_AMT;
        PSCINDTP.M_AMT = PSB2200_AWA_2200.M_AMT;
        PSCINDTP.CERT_DT = PSB2200_AWA_2200.CERT_DT;
        CEP.TRC(SCCGWA, PSCINDTP.CERT_DT);
        PSCINDTP.EXP_DT = PSB2200_AWA_2200.EXP_DT;
        CEP.TRC(SCCGWA, PSCINDTP.EXP_DT);
        PSCINDTP.OTH_EXG_NO = PSB2200_AWA_2200.T_EXG_NO;
        PSCINDTP.PBKA_EX_INSNM = PSB2200_AWA_2200.EX_INSNM;
        PSCINDTP.OTH_ACNO = PSB2200_AWA_2200.OTH_ACNO;
        PSCINDTP.OTH_ACNM = PSB2200_AWA_2200.OTH_ACNM;
        PSCINDTP.RMK = PSB2200_AWA_2200.RMK;
        PSCINDTP.RTN_FLG = PSB2200_AWA_2200.RTN_FLG;
        PSCINDTP.RET_RSN_CD = PSB2200_AWA_2200.R_RSN_CD;
        PSCINDTP.RET_RSN_DSC = PSB2200_AWA_2200.RSN_DSC;
        PSCINDTP.PAY_PSWD = PSB2200_AWA_2200.PAY_PSWD;
        S000_CALL_PSZINDTP();
    }
    public void B300_OUTPUT_PROC() throws IOException,SQLException,Exception {
        WS_FMT.WS_EXG_DT = PSB2200_AWA_2200.EXG_DT;
        WS_FMT.WS_EXG_TMS = PSB2200_AWA_2200.EXG_TMS;
        WS_FMT.WS_OUR_ACNO = PSB2200_AWA_2200.OUR_ACNO;
        WS_FMT.WS_OUR_ACNM = PSB2200_AWA_2200.OUR_ACNM;
        WS_FMT.WS_EXG_CCY = PSB2200_AWA_2200.EXG_CCY;
        WS_FMT.WS_CASH_ID = PSB2200_AWA_2200.CASH_ID;
        WS_FMT.WS_EXG_AMT = PSB2200_AWA_2200.EXG_AMT;
        WS_FMT.WS_EXG_VOUCH_CD = PSB2200_AWA_2200.VOUCH_CD;
        WS_FMT.WS_EXG_CERT_NO = PSB2200_AWA_2200.CERT_NO;
        WS_FMT.WS_ISS_BKNO = PSB2200_AWA_2200.ISS_BKNO;
        WS_FMT.WS_ENCRY_NO = PSB2200_AWA_2200.ENCRY_NO;
        WS_FMT.WS_ISS_AMT = PSB2200_AWA_2200.ISS_AMT;
        WS_FMT.WS_M_AMT = PSB2200_AWA_2200.M_AMT;
        WS_FMT.WS_CERT_DT = PSB2200_AWA_2200.CERT_DT;
        WS_FMT.WS_EXP_DT = PSB2200_AWA_2200.EXP_DT;
        WS_FMT.WS_OTH_EXG_NO = PSB2200_AWA_2200.T_EXG_NO;
        WS_FMT.WS_PBKA_EX_INSNM = PSB2200_AWA_2200.EX_INSNM;
        WS_FMT.WS_OTH_ACNO = PSB2200_AWA_2200.OTH_ACNO;
        WS_FMT.WS_OTH_ACNM = PSB2200_AWA_2200.OTH_ACNM;
        WS_FMT.WS_RMK = PSB2200_AWA_2200.RMK;
        WS_FMT.WS_RTN_FLG = PSB2200_AWA_2200.RTN_FLG;
        WS_FMT.WS_RET_RSN_CD = PSB2200_AWA_2200.R_RSN_CD;
        WS_FMT.WS_RET_RSN_DSC = PSB2200_AWA_2200.RSN_DSC;
        IBS.init(SCCGWA, SCCFMT);
        SCCFMT.FMTID = K_OUTPUT_FMT;
        SCCFMT.DATA_PTR = WS_FMT;
        SCCFMT.DATA_LEN = 1237;
        IBS.FMT(SCCGWA, SCCFMT);
    }
    public void S000_CALL_PSZINDTP() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, CPN_U_PSZINDTP, PSCINDTP);
    }
    public void S000_CALL_BPZPQORG() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-P-INQ-ORG", BPCPQORG);
        if (BPCPQORG.RC.RC_CODE != 0) {
            WS_ERR_MSG = IBS.CLS2CPY(SCCGWA, BPCPQORG.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
