package com.hisun.PS;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;
import com.hisun.BP.*;

import java.io.IOException;
import java.sql.SQLException;

public class PSOT3100 {
    int JIBS_tmp_int;
    String K_EXG_BK_NO = "001";
    String K_OUTPUT_FMT = "PS310";
    String CPN_U_PSZECLRP = "PS-P-CLR-PROC";
    char K_ERROR = 'E';
    String WS_ERR_MSG = " ";
    short WS_FLD_NO = 0;
    PSOT3100_WS_FMT WS_FMT = new PSOT3100_WS_FMT();
    PSCMSG_ERROR_MSG PSCMSG_ERROR_MSG = new PSCMSG_ERROR_MSG();
    PSCECLRP PSCECLRP = new PSCECLRP();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCFMT SCCFMT = new SCCFMT();
    SCCMSG SCCMSG = new SCCMSG();
    SCCCKDT SCCCKDT = new SCCCKDT();
    BPCPQORG BPCPQORG = new BPCPQORG();
    PSROBLL PSROBLL = new PSROBLL();
    PSRIBLL PSRIBLL = new PSRIBLL();
    PSRPBIN PSRPBIN = new PSRPBIN();
    PSREINF PSREINF = new PSREINF();
    SCCGWA SCCGWA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    PSB3100_AWA_3100 PSB3100_AWA_3100;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B200_CLR_PNT_PROC();
        B300_OUTPUT_PROC();
        CEP.TRC(SCCGWA, "PSOT3100 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "PSB3100_AWA_3100>");
        PSB3100_AWA_3100 = (PSB3100_AWA_3100) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
    }
    public void B200_CLR_PNT_PROC() throws IOException,SQLException,Exception {
        B210_CLR_PNT_PROC();
    }
    public void B210_CLR_PNT_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, PSCECLRP);
        IBS.init(SCCGWA, BPCPQORG);
        PSCECLRP.BK_NO = SCCGWA.COMM_AREA.TR_BANK;
        BPCPQORG.BR = SCCGWA.COMM_AREA.BR_DP.TR_BRANCH;
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.BR_DP.TR_BRANCH);
        S000_CALL_BPZPQORG();
        WS_FMT.WS_EXG_AREA_NO = "" + BPCPQORG.BRANCH_BR;
        JIBS_tmp_int = WS_FMT.WS_EXG_AREA_NO.length();
        for (int i=0;i<6-JIBS_tmp_int;i++) WS_FMT.WS_EXG_AREA_NO = "0" + WS_FMT.WS_EXG_AREA_NO;
        PSCECLRP.EXG_AREA_NO = WS_FMT.WS_EXG_AREA_NO;
        CEP.TRC(SCCGWA, BPCPQORG.BRANCH_BR);
        PSCECLRP.OUR_EXG_NO = PSB3100_AWA_3100.EXG_NO;
        PSCECLRP.EXG_DT = PSB3100_AWA_3100.EXG_DT;
        PSCECLRP.EXG_TMS = PSB3100_AWA_3100.EXG_TMS;
        PSCECLRP.EXG_CCY = PSB3100_AWA_3100.EXG_CCY;
        PSCECLRP.PB_IBCR_AMT = PSB3100_AWA_3100.PIC_AMT;
        CEP.TRC(SCCGWA, "REN TI CHU DAI");
        CEP.TRC(SCCGWA, PSB3100_AWA_3100.PIC_AMT);
        CEP.TRC(SCCGWA, PSB3100_AWA_3100.PIC_CONT);
        PSCECLRP.PB_IBCR_COUNT = PSB3100_AWA_3100.PIC_CONT;
        PSCECLRP.PB_IBDR_AMT = PSB3100_AWA_3100.PID_AMT;
        CEP.TRC(SCCGWA, "REN TI CHU JIE");
        CEP.TRC(SCCGWA, PSB3100_AWA_3100.PID_AMT);
        CEP.TRC(SCCGWA, PSB3100_AWA_3100.PID_CONT);
        PSCECLRP.PB_IBDR_COUNT = PSB3100_AWA_3100.PID_CONT;
        PSCECLRP.PB_OBCR_AMT = PSB3100_AWA_3100.PBC_AMT;
        CEP.TRC(SCCGWA, "REN  TI HUI DAI");
        CEP.TRC(SCCGWA, PSB3100_AWA_3100.PBC_AMT);
        CEP.TRC(SCCGWA, PSB3100_AWA_3100.PBC_CONT);
        PSCECLRP.PB_OBCR_COUNT = PSB3100_AWA_3100.PBC_CONT;
        PSCECLRP.PB_OBDR_AMT = PSB3100_AWA_3100.PBD_AMT;
        CEP.TRC(SCCGWA, "REN  TI HUI JIE");
        CEP.TRC(SCCGWA, PSB3100_AWA_3100.PBD_AMT);
        CEP.TRC(SCCGWA, PSB3100_AWA_3100.PBD_CONT);
        PSCECLRP.PB_OBDR_COUNT = PSB3100_AWA_3100.PBD_CONT;
        CEP.TRC(SCCGWA, "WO  TI CHU DAI");
        CEP.TRC(SCCGWA, PSB3100_AWA_3100.OIC_AMT);
        CEP.TRC(SCCGWA, PSB3100_AWA_3100.OIC_CONT);
        PSCECLRP.OUR_IBCR_AMT = PSB3100_AWA_3100.OIC_AMT;
        PSCECLRP.OUR_IBCR_COUNT = PSB3100_AWA_3100.OIC_CONT;
        CEP.TRC(SCCGWA, "WO  TI  CHU JIE");
        CEP.TRC(SCCGWA, PSB3100_AWA_3100.OID_AMT);
        CEP.TRC(SCCGWA, PSB3100_AWA_3100.OID_CONT);
        PSCECLRP.OUR_IBDR_AMT = PSB3100_AWA_3100.OID_AMT;
        PSCECLRP.OUR_IBDR_COUNT = PSB3100_AWA_3100.OID_CONT;
        CEP.TRC(SCCGWA, "WO  TI  HUI  DAI");
        CEP.TRC(SCCGWA, PSB3100_AWA_3100.OOC_AMT);
        CEP.TRC(SCCGWA, PSB3100_AWA_3100.OOC_CONT);
        PSCECLRP.OUR_OBCR_AMT = PSB3100_AWA_3100.OOC_AMT;
        PSCECLRP.OUR_OBCR_COUNT = PSB3100_AWA_3100.OOC_CONT;
        CEP.TRC(SCCGWA, "WO  TI HUI JIE");
        CEP.TRC(SCCGWA, PSB3100_AWA_3100.OOD_AMT);
        CEP.TRC(SCCGWA, PSB3100_AWA_3100.OOD_CONT);
        PSCECLRP.OUR_OBDR_AMT = PSB3100_AWA_3100.OOD_AMT;
        PSCECLRP.OUR_OBDR_COUNT = PSB3100_AWA_3100.OOD_CONT;
        S000_CALL_PSZECLRP();
    }
    public void B300_OUTPUT_PROC() throws IOException,SQLException,Exception {
        WS_FMT.WS_OUR_EXG_NO = PSB3100_AWA_3100.EXG_NO;
        WS_FMT.WS_EXG_DT = PSB3100_AWA_3100.EXG_DT;
        WS_FMT.WS_EXG_TMS = PSB3100_AWA_3100.EXG_TMS;
        WS_FMT.WS_EXG_CCY = PSB3100_AWA_3100.EXG_CCY;
        WS_FMT.WS_PB_IBCR_AMT = PSB3100_AWA_3100.PIC_AMT;
        WS_FMT.WS_PB_IBCR_COUNT = PSB3100_AWA_3100.PIC_CONT;
        WS_FMT.WS_PB_IBDR_AMT = PSB3100_AWA_3100.PID_AMT;
        WS_FMT.WS_PB_IBDR_COUNT = PSB3100_AWA_3100.PID_CONT;
        WS_FMT.WS_PB_OBCR_AMT = PSB3100_AWA_3100.PBC_AMT;
        WS_FMT.WS_PB_OBCR_COUNT = PSB3100_AWA_3100.PBC_CONT;
        WS_FMT.WS_PB_OBDR_AMT = PSB3100_AWA_3100.PBD_AMT;
        WS_FMT.WS_PB_OBDR_COUNT = PSB3100_AWA_3100.PBD_CONT;
        WS_FMT.WS_OUR_IBCR_AMT = PSB3100_AWA_3100.OIC_AMT;
        WS_FMT.WS_OUR_IBCR_COUNT = PSB3100_AWA_3100.OIC_CONT;
        WS_FMT.WS_OUR_IBDR_AMT = PSB3100_AWA_3100.OID_AMT;
        WS_FMT.WS_OUR_IBDR_COUNT = PSB3100_AWA_3100.OID_CONT;
        WS_FMT.WS_OUR_OBCR_AMT = PSB3100_AWA_3100.OOC_AMT;
        WS_FMT.WS_OUR_OBCR_COUNT = PSB3100_AWA_3100.OOC_CONT;
        WS_FMT.WS_OUR_OBDR_AMT = PSB3100_AWA_3100.OOD_AMT;
        WS_FMT.WS_OUR_OBDR_COUNT = PSB3100_AWA_3100.OOD_CONT;
        IBS.init(SCCGWA, SCCFMT);
        SCCFMT.FMTID = K_OUTPUT_FMT;
        SCCFMT.DATA_PTR = WS_FMT;
        SCCFMT.DATA_LEN = 184;
        IBS.FMT(SCCGWA, SCCFMT);
    }
    public void S000_CALL_PSZECLRP() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, CPN_U_PSZECLRP, PSCECLRP);
    }
    public void S000_CALL_BPZPQORG() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-P-INQ-ORG", BPCPQORG);
        if (BPCPQORG.RC.RC_CODE != 0) {
            WS_ERR_MSG = IBS.CLS2CPY(SCCGWA, BPCPQORG.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
