package com.hisun.PS;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;
import com.hisun.BP.*;

import java.io.IOException;
import java.sql.SQLException;

public class PSOT1300 {
    int JIBS_tmp_int;
    String K_EXG_BK_NO = "001";
    String K_OUTPUT_FMT = "PS130";
    String CPN_U_PSCRTCRP = "PS-P-ROTCR-PROC";
    char K_ERROR = 'E';
    String PGM_SCSSCKDT = "SCSSCKDT";
    String WS_ERR_MSG = " ";
    short WS_FLD_NO = 0;
    PSOT1300_WS_FMT WS_FMT = new PSOT1300_WS_FMT();
    PSCMSG_ERROR_MSG PSCMSG_ERROR_MSG = new PSCMSG_ERROR_MSG();
    PSCOTDTP PSCOTDTP = new PSCOTDTP();
    PSCRTCRP PSCRTCRP = new PSCRTCRP();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCFMT SCCFMT = new SCCFMT();
    SCCMSG SCCMSG = new SCCMSG();
    SCCCKDT SCCCKDT = new SCCCKDT();
    BPCPQORG BPCPQORG = new BPCPQORG();
    PSROBLL PSROBLL = new PSROBLL();
    PSRIBLL PSRIBLL = new PSRIBLL();
    PSRPBIN PSRPBIN = new PSRPBIN();
    PSREINF PSREINF = new PSREINF();
    SCCGWA SCCGWA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    PSB1300_AWA_1300 PSB1300_AWA_1300;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B200_CLR_PNT_PROC();
        B300_OUTPUT_PROC();
        CEP.TRC(SCCGWA, "PSOT1300 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "PSB1300_AWA_1300>");
        PSB1300_AWA_1300 = (PSB1300_AWA_1300) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
    }
    public void B200_CLR_PNT_PROC() throws IOException,SQLException,Exception {
        B210_CLR_PNT_PROC();
    }
    public void B210_CLR_PNT_PROC() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, PSB1300_AWA_1300.AREA_NO);
        CEP.TRC(SCCGWA, PSB1300_AWA_1300.RT_DT);
        CEP.TRC(SCCGWA, PSB1300_AWA_1300.RT_TMS);
        CEP.TRC(SCCGWA, PSB1300_AWA_1300.EXG_NO);
        CEP.TRC(SCCGWA, PSB1300_AWA_1300.OUR_ACNO);
        CEP.TRC(SCCGWA, PSB1300_AWA_1300.OUR_ACNM);
        CEP.TRC(SCCGWA, PSB1300_AWA_1300.EXG_CCY);
        CEP.TRC(SCCGWA, PSB1300_AWA_1300.CASH_ID);
        CEP.TRC(SCCGWA, PSB1300_AWA_1300.EXG_AMT);
        CEP.TRC(SCCGWA, PSB1300_AWA_1300.VOUCH_CD);
        CEP.TRC(SCCGWA, PSB1300_AWA_1300.CERT_NO);
        CEP.TRC(SCCGWA, PSB1300_AWA_1300.O_EXG_NO);
        CEP.TRC(SCCGWA, PSB1300_AWA_1300.EX_INSNM);
        CEP.TRC(SCCGWA, PSB1300_AWA_1300.OTH_ACNO);
        CEP.TRC(SCCGWA, PSB1300_AWA_1300.OTH_ACNM);
        CEP.TRC(SCCGWA, PSB1300_AWA_1300.RMK);
        CEP.TRC(SCCGWA, PSB1300_AWA_1300.R_RSN_CD);
        CEP.TRC(SCCGWA, PSB1300_AWA_1300.RSN_DSC);
        CEP.TRC(SCCGWA, PSB1300_AWA_1300.TX_JRNNO);
        IBS.init(SCCGWA, PSCRTCRP);
        IBS.init(SCCGWA, BPCPQORG);
        PSCRTCRP.BK_NO = SCCGWA.COMM_AREA.TR_BANK;
        BPCPQORG.BR = SCCGWA.COMM_AREA.BR_DP.TR_BRANCH;
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.BR_DP.TR_BRANCH);
        S000_CALL_BPZPQORG();
        WS_FMT.WS_EXG_AREA_NO = "" + BPCPQORG.BRANCH_BR;
        JIBS_tmp_int = WS_FMT.WS_EXG_AREA_NO.length();
        for (int i=0;i<6-JIBS_tmp_int;i++) WS_FMT.WS_EXG_AREA_NO = "0" + WS_FMT.WS_EXG_AREA_NO;
        PSCRTCRP.EXG_AREA_NO = WS_FMT.WS_EXG_AREA_NO;
        CEP.TRC(SCCGWA, BPCPQORG.BRANCH_BR);
        PSCRTCRP.EXG_RT_DT = PSB1300_AWA_1300.RT_DT;
        PSCRTCRP.EXG_RT_TMS = PSB1300_AWA_1300.RT_TMS;
        PSCRTCRP.OUR_EXG_NO = PSB1300_AWA_1300.EXG_NO;
        PSCRTCRP.OUR_ACNO = PSB1300_AWA_1300.OUR_ACNO;
        PSCRTCRP.OUR_ACNM = PSB1300_AWA_1300.OUR_ACNM;
        CEP.TRC(SCCGWA, PSCRTCRP.OUR_ACNM);
        PSCRTCRP.EXG_CCY = PSB1300_AWA_1300.EXG_CCY;
        PSCRTCRP.CASH_ID = PSB1300_AWA_1300.CASH_ID;
        PSCRTCRP.EXG_AMT = PSB1300_AWA_1300.EXG_AMT;
        if (!PSB1300_AWA_1300.VOUCH_CD.equalsIgnoreCase("98")) {
            CEP.TRC(SCCGWA, PSB1300_AWA_1300.VOUCH_CD);
            PSCRTCRP.EXG_VOUCH_CD = PSB1300_AWA_1300.VOUCH_CD;
        } else {
            CEP.TRC(SCCGWA, PSB1300_AWA_1300.VOUCH_CD);
            WS_ERR_MSG = PSCMSG_ERROR_MSG.VOUCH_CD;
            S000_ERR_MSG_PROC();
        }
        PSCRTCRP.EXG_CERT_NO = PSB1300_AWA_1300.CERT_NO;
        PSCRTCRP.OTH_EXG_NO = PSB1300_AWA_1300.O_EXG_NO;
        PSCRTCRP.PBKA_EX_INSNM = PSB1300_AWA_1300.EX_INSNM;
        PSCRTCRP.OTH_ACNO = PSB1300_AWA_1300.OTH_ACNO;
        PSCRTCRP.OTH_ACNM = PSB1300_AWA_1300.OTH_ACNM;
        PSCRTCRP.RMK = PSB1300_AWA_1300.RMK;
        PSCRTCRP.RET_RSN_CD = PSB1300_AWA_1300.R_RSN_CD;
        PSCRTCRP.RET_RSN_DSC = PSB1300_AWA_1300.RSN_DSC;
        PSCRTCRP.TX_JRNNO = PSB1300_AWA_1300.TX_JRNNO;
        PSCRTCRP.EXG_DC = 'C';
        S000_CALL_PSZRTCRP();
    }
    public void B300_OUTPUT_PROC() throws IOException,SQLException,Exception {
        WS_FMT.WS_EXG_RT_DT = PSB1300_AWA_1300.RT_DT;
        WS_FMT.WS_EXG_RT_TMS = PSB1300_AWA_1300.RT_TMS;
        WS_FMT.WS_OUR_EXG_NO = PSB1300_AWA_1300.EXG_NO;
        WS_FMT.WS_OUR_ACNO = PSB1300_AWA_1300.OUR_ACNO;
        WS_FMT.WS_OUR_ACNM = PSB1300_AWA_1300.OUR_ACNM;
        WS_FMT.WS_EXG_CCY = PSB1300_AWA_1300.EXG_CCY;
        WS_FMT.WS_CASH_ID = PSB1300_AWA_1300.CASH_ID;
        WS_FMT.WS_EXG_AMT = PSB1300_AWA_1300.EXG_AMT;
        WS_FMT.WS_EXG_VOUCH_CD = PSB1300_AWA_1300.VOUCH_CD;
        WS_FMT.WS_EXG_CERT_NO = PSB1300_AWA_1300.CERT_NO;
        WS_FMT.WS_OTH_EXG_NO = PSB1300_AWA_1300.O_EXG_NO;
        WS_FMT.WS_PBKA_EX_INSNM = PSB1300_AWA_1300.EX_INSNM;
        WS_FMT.WS_OTH_ACNO = PSB1300_AWA_1300.OTH_ACNO;
        WS_FMT.WS_OTH_ACNM = PSB1300_AWA_1300.OTH_ACNM;
        WS_FMT.WS_RMK = PSB1300_AWA_1300.RMK;
        WS_FMT.WS_RET_RSN_CD = PSB1300_AWA_1300.R_RSN_CD;
        WS_FMT.WS_RET_RSN_DSC = PSB1300_AWA_1300.RSN_DSC;
        WS_FMT.WS_TX_JRNNO = PSB1300_AWA_1300.TX_JRNNO;
        IBS.init(SCCGWA, SCCFMT);
        SCCFMT.FMTID = K_OUTPUT_FMT;
        SCCFMT.DATA_PTR = WS_FMT;
        SCCFMT.DATA_LEN = 1070;
        IBS.FMT(SCCGWA, SCCFMT);
    }
    public void S000_CALL_PSZRTCRP() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, CPN_U_PSCRTCRP, PSCRTCRP);
    }
    public void S000_CALL_BPZPQORG() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-P-INQ-ORG", BPCPQORG);
        if (BPCPQORG.RC.RC_CODE != 0) {
            WS_ERR_MSG = IBS.CLS2CPY(SCCGWA, BPCPQORG.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
