package com.hisun.PS;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;
import com.hisun.BP.*;

import java.io.IOException;
import java.sql.SQLException;

public class PSOT2100 {
    int JIBS_tmp_int;
    String K_EXG_BK_NO = "001";
    String K_OUTPUT_FMT = "PS210";
    String CPN_U_PSZINCRP = "PS-P-INCR-PROC";
    char K_ERROR = 'E';
    String PGM_SCSSCKDT = "SCSSCKDT";
    String WS_ERR_MSG = " ";
    short WS_FLD_NO = 0;
    PSOT2100_WS_FMT WS_FMT = new PSOT2100_WS_FMT();
    PSCMSG_ERROR_MSG PSCMSG_ERROR_MSG = new PSCMSG_ERROR_MSG();
    PSCINCRP PSCINCRP = new PSCINCRP();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCFMT SCCFMT = new SCCFMT();
    SCCMSG SCCMSG = new SCCMSG();
    SCCCKDT SCCCKDT = new SCCCKDT();
    BPCPQORG BPCPQORG = new BPCPQORG();
    PSROBLL PSROBLL = new PSROBLL();
    PSRIBLL PSRIBLL = new PSRIBLL();
    PSRPBIN PSRPBIN = new PSRPBIN();
    PSREINF PSREINF = new PSREINF();
    SCCGWA SCCGWA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    PSB2100_AWA_2100 PSB2100_AWA_2100;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B200_CLR_PNT_PROC();
        B300_OUTPUT_PROC();
        CEP.TRC(SCCGWA, "PSOT2100 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "PSB2100_AWA_2100>");
        PSB2100_AWA_2100 = (PSB2100_AWA_2100) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
    }
    public void B200_CLR_PNT_PROC() throws IOException,SQLException,Exception {
        B210_CLR_PNT_PROC();
    }
    public void B210_CLR_PNT_PROC() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.TR_BANK);
        CEP.TRC(SCCGWA, PSB2100_AWA_2100.EXG_DT);
        CEP.TRC(SCCGWA, PSB2100_AWA_2100.EXG_TMS);
        CEP.TRC(SCCGWA, PSB2100_AWA_2100.OUR_ACNO);
        CEP.TRC(SCCGWA, PSB2100_AWA_2100.OUR_ACNM);
        CEP.TRC(SCCGWA, PSB2100_AWA_2100.VOUCH_CD);
        CEP.TRC(SCCGWA, PSB2100_AWA_2100.CERT_NO);
        CEP.TRC(SCCGWA, PSB2100_AWA_2100.T_EXG_NO);
        CEP.TRC(SCCGWA, PSB2100_AWA_2100.EX_INSNM);
        CEP.TRC(SCCGWA, PSB2100_AWA_2100.OTH_ACNO);
        CEP.TRC(SCCGWA, PSB2100_AWA_2100.OTH_ACNM);
        CEP.TRC(SCCGWA, PSB2100_AWA_2100.EXG_CCY);
        CEP.TRC(SCCGWA, PSB2100_AWA_2100.CASH_ID);
        CEP.TRC(SCCGWA, PSB2100_AWA_2100.EXG_AMT);
        CEP.TRC(SCCGWA, PSB2100_AWA_2100.RMK);
        CEP.TRC(SCCGWA, PSB2100_AWA_2100.RTN_FLG);
        CEP.TRC(SCCGWA, PSB2100_AWA_2100.R_RSN_CD);
        CEP.TRC(SCCGWA, PSB2100_AWA_2100.RSN_DSC);
        IBS.init(SCCGWA, PSCINCRP);
        IBS.init(SCCGWA, BPCPQORG);
        PSCINCRP.BK_NO = SCCGWA.COMM_AREA.TR_BANK;
        BPCPQORG.BR = SCCGWA.COMM_AREA.BR_DP.TR_BRANCH;
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.BR_DP.TR_BRANCH);
        S000_CALL_BPZPQORG();
        WS_FMT.WS_EXG_AREA_NO = "" + BPCPQORG.BRANCH_BR;
        JIBS_tmp_int = WS_FMT.WS_EXG_AREA_NO.length();
        for (int i=0;i<6-JIBS_tmp_int;i++) WS_FMT.WS_EXG_AREA_NO = "0" + WS_FMT.WS_EXG_AREA_NO;
        PSCINCRP.EXG_AREA_NO = WS_FMT.WS_EXG_AREA_NO;
        CEP.TRC(SCCGWA, BPCPQORG.BRANCH_BR);
        PSCINCRP.EXG_DT = PSB2100_AWA_2100.EXG_DT;
        PSCINCRP.EXG_TMS = PSB2100_AWA_2100.EXG_TMS;
        PSCINCRP.OUR_ACNO = PSB2100_AWA_2100.OUR_ACNO;
        PSCINCRP.OUR_ACNM = PSB2100_AWA_2100.OUR_ACNM;
        PSCINCRP.EXG_VOUCH_CD = PSB2100_AWA_2100.VOUCH_CD;
        PSCINCRP.EXG_CERT_NO = PSB2100_AWA_2100.CERT_NO;
        PSCINCRP.OTH_EXG_NO = PSB2100_AWA_2100.T_EXG_NO;
        PSCINCRP.PBKA_EX_INSNM = PSB2100_AWA_2100.EX_INSNM;
        PSCINCRP.OTH_ACNO = PSB2100_AWA_2100.OTH_ACNO;
        PSCINCRP.OTH_ACNM = PSB2100_AWA_2100.OTH_ACNM;
        PSCINCRP.EXG_CCY = PSB2100_AWA_2100.EXG_CCY;
        PSCINCRP.CASH_ID = PSB2100_AWA_2100.CASH_ID;
        PSCINCRP.EXG_AMT = PSB2100_AWA_2100.EXG_AMT;
        PSCINCRP.RMK = PSB2100_AWA_2100.RMK;
        PSCINCRP.RTN_FLG = PSB2100_AWA_2100.RTN_FLG;
        PSCINCRP.RET_RSN_CD = PSB2100_AWA_2100.R_RSN_CD;
        CEP.TRC(SCCGWA, PSCINCRP.RET_RSN_CD);
        PSCINCRP.RET_RSN_DSC = PSB2100_AWA_2100.RSN_DSC;
        S000_CALL_PSZINCRP();
    }
    public void B300_OUTPUT_PROC() throws IOException,SQLException,Exception {
        WS_FMT.WS_EXG_DT = PSB2100_AWA_2100.EXG_DT;
        WS_FMT.WS_EXG_TMS = PSB2100_AWA_2100.EXG_TMS;
        WS_FMT.WS_OUR_ACNO = PSB2100_AWA_2100.OUR_ACNO;
        WS_FMT.WS_OUR_ACNM = PSB2100_AWA_2100.OUR_ACNM;
        WS_FMT.WS_EXG_VOUCH_CD = PSB2100_AWA_2100.VOUCH_CD;
        WS_FMT.WS_EXG_CERT_NO = PSB2100_AWA_2100.CERT_NO;
        WS_FMT.WS_OTH_EXG_NO = PSB2100_AWA_2100.T_EXG_NO;
        WS_FMT.WS_PBKA_EX_INSNM = PSB2100_AWA_2100.EX_INSNM;
        WS_FMT.WS_OTH_ACNO = PSB2100_AWA_2100.OTH_ACNO;
        WS_FMT.WS_OTH_ACNM = PSB2100_AWA_2100.OTH_ACNM;
        WS_FMT.WS_EXG_CCY = PSB2100_AWA_2100.EXG_CCY;
        WS_FMT.WS_CASH_ID = PSB2100_AWA_2100.CASH_ID;
        WS_FMT.WS_EXG_AMT = PSB2100_AWA_2100.EXG_AMT;
        WS_FMT.WS_RMK = PSB2100_AWA_2100.RMK;
        WS_FMT.WS_RTN_FLG = PSB2100_AWA_2100.RTN_FLG;
        WS_FMT.WS_RET_RSN_CD = PSB2100_AWA_2100.R_RSN_CD;
        WS_FMT.WS_RET_RSN_DSC = PSB2100_AWA_2100.RSN_DSC;
        IBS.init(SCCGWA, SCCFMT);
        SCCFMT.FMTID = K_OUTPUT_FMT;
        SCCFMT.DATA_PTR = WS_FMT;
        SCCFMT.DATA_LEN = 1159;
        IBS.FMT(SCCGWA, SCCFMT);
    }
    public void S000_CALL_PSZINCRP() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, CPN_U_PSZINCRP, PSCINCRP);
        CEP.TRC(SCCGWA, PSCINCRP.RC);
        if (PSCINCRP.RC.RC_CODE != 0) {
            WS_ERR_MSG = IBS.CLS2CPY(SCCGWA, PSCINCRP.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_BPZPQORG() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-P-INQ-ORG", BPCPQORG);
        if (BPCPQORG.RC.RC_CODE != 0) {
            WS_ERR_MSG = IBS.CLS2CPY(SCCGWA, BPCPQORG.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
