package com.hisun.PS;

public class PSROBLL {
    public PSROBLL_KEY KEY = new PSROBLL_KEY();
    public String OUR_EXG_NO = " ";
    public String EXG_CCY = " ";
    public String OTH_EXG_NO = " ";
    public char EXG_DC = ' ';
    public String EXG_VOUCH_CD = " ";
    public String EXG_CERT_NO = " ";
    public char EXG_REC_STS = ' ';
    public double EXG_AMT = 0;
    public int EXG_TX_BR = 0;
    public String OUR_ACNO = " ";
    public String OUR_ACNM = " ";
    public String OTH_ACNO = " ";
    public String OTH_ACNM = " ";
    public String R_BILL_TYP = " ";
    public int CERT_DT = 0;
    public long ISS_BKNO = 0;
    public int EXP_DT = 0;
    public double ISS_AMT = 0;
    public String ENCRY_NO = " ";
    public char CT_FLG = ' ';
    public String CREV_NO = " ";
    public char CASH_ID = ' ';
    public int SHL_EXG_DT = 0;
    public short SHL_EXG_TMS = 0;
    public int ACT_EXG_DT = 0;
    public short ACT_EXG_TMS = 0;
    public String RT_CODE = " ";
    public String OUT_DATA = " ";
    public char EXG_REPT_FLG = ' ';
    public String RMK = " ";
    public long RET_JRN_NO = 0;
    public String RET_RSN_CD = " ";
    public String RET_RSN_DSC = " ";
    public String BILL_HLD_AC = " ";
    public String BILL_HLD_ACNM = " ";
    public String STR_CHNL = " ";
    public String STR_JRN = " ";
    public int CRT_DATE = 0;
    public String CRT_TLR = " ";
    public int UPDTBL_DATE = 0;
    public String UPDTBL_TLR = " ";
    public String TS = " ";
}
