package com.hisun.PS;

import java.io.IOException;
import java.sql.SQLException;

import com.hisun.BP.BPCPOEWA;
import com.hisun.SC.SCCCALL;
import com.hisun.SC.SCCCLDT;
import com.hisun.SC.SCCEXCP;
import com.hisun.SC.SCCFMT;
import com.hisun.SC.SCCGSCA_SC_AREA;
import com.hisun.SC.SCCGWA;
import com.hisun.SC.SCCMPAG;
import com.hisun.SC.SCCMSG;

public class PSZRQRYP {
    boolean pgmRtn = false;
    String K_EXG_BK_NO = "001";
    String WS_ERR_MSG = " ";
    String WS_ERR_INFO = " ";
    int WS_ISS_BR_MSG = 0;
    short WS_NUM = 0;
    short WS_A = 0;
    char WS_READ_TRAN = ' ';
    char WS_TBL_FLAG = ' ';
    double WS_SUM_AMT = 0;
    PSZRQRYP_WS_OUT_DATA WS_OUT_DATA = new PSZRQRYP_WS_OUT_DATA();
    PSZRQRYP_WS_TEMP WS_TEMP = new PSZRQRYP_WS_TEMP();
    SCCMPAG SCCMPAG = new SCCMPAG();
    PSCMSG_ERROR_MSG PSCMSG_ERROR_MSG = new PSCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    SCCCLDT SCCCLDT = new SCCCLDT();
    SCCFMT SCCFMT = new SCCFMT();
    BPCPOEWA BPCPOEWA = new BPCPOEWA();
    PSROBLL PSROBLL = new PSROBLL();
    PSRIBLL PSRIBLL = new PSRIBLL();
    PSRPBIN PSRPBIN = new PSRPBIN();
    PSREINF PSREINF = new PSREINF();
    int WS_I_EXG_B_DT = 0;
    int WS_I_EXG_E_DT = 0;
    String WS_I_EXG_BK_NO = " ";
    String WS_I_EXG_AREA_NO = " ";
    short WS_I_EXG_TMS = 0;
    int WS_I_ACT_EXG_DT = 0;
    short WS_I_ACT_EXG_TMS = 0;
    String WS_I_EXG_CCY = " ";
    char WS_I_EXG_DC = ' ';
    String WS_I_EXG_CERT_NO = " ";
    String WS_I_BIG_CERT_NO = " ";
    String WS_I_OUR_EXG_NO = " ";
    String WS_I_OTH_EXG_NO = " ";
    String WS_I_OUR_ACNO = " ";
    String WS_BIG_OUR_ACNO = " ";
    String WS_I_OTH_ACNO = " ";
    String WS_BIG_OTH_ACNO = " ";
    int WS_I_EXG_TX_BR = 0;
    int WS_RCD_SEQ = 0;
    int WS_CNT = 0;
    double WS_AMT = 0;
    String K_OUTPUT_FMT1 = "PS810";
    int K_SCR_ROW_NO = 10;
    SCCGWA SCCGWA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
