package com.hisun.PS;

public class PSZSRCVE_WS_PARM {
    PSZSRCVE_WS_HOST_FNAME_INFO WS_HOST_FNAME_INFO = new PSZSRCVE_WS_HOST_FNAME_INFO();
    PSZSRCVE_WS_TRS_INFO WS_TRS_INFO = new PSZSRCVE_WS_TRS_INFO();
    PSZSRCVE_WS_TRI_INFO WS_TRI_INFO = new PSZSRCVE_WS_TRI_INFO();
    PSZSRCVE_WS_BUS_TYPE_INFO WS_BUS_TYPE_INFO = new PSZSRCVE_WS_BUS_TYPE_INFO();
}
