package com.hisun.LN;

public class LNB4010_AWA_4010 {
    public String CTA_NO = " ";
    public short CTA_NO_NO = 0;
    public int BR = 0;
    public short BR_NO = 0;
    public String CI_NO = " ";
    public short CI_NO_NO = 0;
    public String CI_CNM = " ";
    public short CI_CNM_NO = 0;
    public String PROD_CD = " ";
    public short PROD_CD_NO = 0;
    public String PROD_DE = " ";
    public short PROD_DE_NO = 0;
    public String PD_DESC = " ";
    public short PD_DESC_NO = 0;
    public String CCY = " ";
    public short CCY_NO = 0;
    public double LN_PRIN = 0;
    public short LN_PRIN_NO = 0;
    public double LN_BAL = 0;
    public short LN_BAL_NO = 0;
    public int TR_VALDT = 0;
    public short TR_VALDT_NO = 0;
    public String BK_CINO = " ";
    public short BK_CINO_NO = 0;
    public String BK_NAME = " ";
    public short BK_NAME_NO = 0;
    public String BK_CNTY = " ";
    public short BK_CNTY_NO = 0;
    public int PAGE_ROW = 0;
    public short PAGE_ROW_NO = 0;
    public int PAGE_NUM = 0;
    public short PAGE_NUM_NO = 0;
    public int TR_ENDDT = 0;
    public short TR_ENDDT_NO = 0;
    public char ERR_FLG = ' ';
    public short ERR_FLG_NO = 0;
}
