package com.hisun.LN;

public class LNB7080_AWA_7080 {
    public char FUNC = ' ';
    public short FUNC_NO = 0;
    public String DESC = " ";
    public short DESC_NO = 0;
    public String CDESC = " ";
    public short CDESC_NO = 0;
    public int EFFDATE = 0;
    public short EFFDATE_NO = 0;
    public int EXPDATE = 0;
    public short EXPDATE_NO = 0;
    public String PROD_CD = " ";
    public short PROD_CD_NO = 0;
    public String PRDMO_CD = " ";
    public short PRDMO_CD_NO = 0;
    public char PROD_S = ' ';
    public short PROD_S_NO = 0;
    public String PROD_TYP = " ";
    public short PROD_TYP_NO = 0;
    public LNB7080_CCY_INF[] CCY_INF = new LNB7080_CCY_INF[2];
    public String MAX_DD = " ";
    public short MAX_DD_NO = 0;
    public String MIN_DD = " ";
    public short MIN_DD_NO = 0;
    public char CIN_TYP = ' ';
    public short CIN_TYP_NO = 0;
    public char CM_TYP = ' ';
    public short CM_TYP_NO = 0;
    public LNB7080_BSRT_TYP[] BSRT_TYP = new LNB7080_BSRT_TYP[2];
    public char RT_TYP = ' ';
    public short RT_TYP_NO = 0;
    public LNB7080_RT_TERM[] RT_TERM = new LNB7080_RT_TERM[2];
    public LNB7080_RAT_MTH[] RAT_MTH = new LNB7080_RAT_MTH[2];
    public char CFT_FLG = ' ';
    public short CFT_FLG_NO = 0;
    public LNB7080_RT_P_U[] RT_P_U = new LNB7080_RT_P_U[2];
    public short RT_PERD = 0;
    public short RT_PERD_NO = 0;
    public LNB7080_RT_MTH[] RT_MTH = new LNB7080_RT_MTH[2];
    public LNB7080_REPY_MTH[] REPY_MTH = new LNB7080_REPY_MTH[2];
    public char REPY_CO1 = ' ';
    public short REPY_CO1_NO = 0;
    public String REPY_CT1 = " ";
    public short REPY_CT1_NO = 0;
    public char REPY_CO2 = ' ';
    public short REPY_CO2_NO = 0;
    public String REPY_CT2 = " ";
    public short REPY_CT2_NO = 0;
    public char REPY_CO3 = ' ';
    public short REPY_CO3_NO = 0;
    public String REPY_CT3 = " ";
    public short REPY_CT3_NO = 0;
    public short REPY_PRT = 0;
    public short REPY_PRT_NO = 0;
    public char BLN_FLG = ' ';
    public short BLN_FLG_NO = 0;
    public double BLN_PP = 0;
    public short BLN_PP_NO = 0;
    public char VCT_FLG = ' ';
    public short VCT_FLG_NO = 0;
    public int GRA_D = 0;
    public short GRA_D_NO = 0;
    public char PGRAMT = ' ';
    public short PGRAMT_NO = 0;
    public char CGRAMT = ' ';
    public short CGRAMT_NO = 0;
    public char MAR_FLG = ' ';
    public short MAR_FLG_NO = 0;
    public char MAR_MTH = ' ';
    public short MAR_MTH_NO = 0;
    public LNB7080_AWA_7080() {
        for (int i=0;i<2;i++) CCY_INF[i] = new LNB7080_CCY_INF();
        for (int i=0;i<2;i++) BSRT_TYP[i] = new LNB7080_BSRT_TYP();
        for (int i=0;i<2;i++) RT_TERM[i] = new LNB7080_RT_TERM();
        for (int i=0;i<2;i++) RAT_MTH[i] = new LNB7080_RAT_MTH();
        for (int i=0;i<2;i++) RT_P_U[i] = new LNB7080_RT_P_U();
        for (int i=0;i<2;i++) RT_MTH[i] = new LNB7080_RT_MTH();
        for (int i=0;i<2;i++) REPY_MTH[i] = new LNB7080_REPY_MTH();
    }
}
