package com.hisun.LN;

public class LNCCONT_REC_DATA {
    public LNCCONT_KEY KEY = new LNCCONT_KEY();
    public String CONTRACT_TYPE = " ";
    public char SYS_FLG = ' ';
    public char CTL_FLG = ' ';
    public String FATHER_CONTRACT = " ";
    public char CTA_STS = ' ';
    public String PROD_CD = " ";
    public String DRAWDOWN_MTH = " ";
    public String CCY = " ";
    public double LN_TOT_AMT = 0;
    public int START_DATE = 0;
    public int MAT_DATE = 0;
    public int BOOK_BR = 0;
    public int DOMI_BR = 0;
    public short OVER_TIME = 0;
    public double EXCHANGE_RATE = 0;
    public double EQUIVALENT = 0;
    public int LAST_F_VAL_DATE = 0;
    public int TRAN_DTE = 0;
    public long TRAN_JRN = 0;
    public double ORIG_TOT_AMT = 0;
    public int ORI_MAT_DATE = 0;
    public int LAST_TX_DT = 0;
    public int LAST_TX_SEQ = 0;
    public String REL_CONTRACT = " ";
    public String REQ_FRM_NO = " ";
    public String REMARK1 = " ";
    public String CUSTM1 = " ";
    public String CUSTM2 = " ";
    public String CUSTM3 = " ";
    public String BAR_CD = " ";
    public String UNIT_CD = " ";
    public int CRT_DATE = 0;
    public String CRT_TLR = " ";
    public int UPDTBL_DATE = 0;
    public String UPDTBL_TLR = " ";
    public String TS = " ";
}
