package com.hisun.LN;

public class LNCHADVC {
    public LNCHADVC_BASIC_INFO BASIC_INFO = new LNCHADVC_BASIC_INFO();
    public LNCHADVC_STL_INSTRCT1 STL_INSTRCT1 = new LNCHADVC_STL_INSTRCT1();
    public LNCHADVC_STL_INSTRCT2 STL_INSTRCT2 = new LNCHADVC_STL_INSTRCT2();
    public LNCHADVC_HKD_CHATS_RTGS HKD_CHATS_RTGS = new LNCHADVC_HKD_CHATS_RTGS();
    public LNCHADVC_USD_CHATS_RTGS USD_CHATS_RTGS = new LNCHADVC_USD_CHATS_RTGS();
    public LNCHADVC_SWIFT SWIFT = new LNCHADVC_SWIFT();
}
