package com.hisun.LN;

public class LNCIDES_SORT_AREA {
    public LNCIDES_MST_PROD_INFO MST_PROD_INFO = new LNCIDES_MST_PROD_INFO();
    public LNCIDES_ICTL_ADDI ICTL_ADDI = new LNCIDES_ICTL_ADDI();
    public LNCIDES_LOAN_NORMAL_INFO LOAN_NORMAL_INFO = new LNCIDES_LOAN_NORMAL_INFO();
    public LNCIDES_LOAN_F_IPLN_REAL LOAN_F_IPLN_REAL = new LNCIDES_LOAN_F_IPLN_REAL();
    public LNCIDES_LOAN_F_IPLN_WORK LOAN_F_IPLN_WORK = new LNCIDES_LOAN_F_IPLN_WORK();
    public String FILLER92 = " ";
    public LNCIDES_LOAN_ON_DUE_INFO LOAN_ON_DUE_INFO = new LNCIDES_LOAN_ON_DUE_INFO();
    public char LOAN_STS = ' ';
    public String FILLER97 = " ";
}
