package com.hisun.LN;

public class LNCIGECR {
    public LNCIGECR_RC RC = new LNCIGECR_RC();
    public LNCIGECR_INPUT_INFO INPUT_INFO = new LNCIGECR_INPUT_INFO();
    public LNCIGECR_OUTPOUT_INFO OUTPOUT_INFO = new LNCIGECR_OUTPOUT_INFO();
}
