package com.hisun.LN;

public class LNCIPST_AMT_INFO {
    public LNCIPST_AMT_NORMAL_INFO AMT_NORMAL_INFO = new LNCIPST_AMT_NORMAL_INFO();
    public LNCIPST_AMT_NON_STOP_INFO AMT_NON_STOP_INFO = new LNCIPST_AMT_NON_STOP_INFO();
}
