package com.hisun.LN;

public class LNCPPMQ {
    public LNCPPMQ_RC RC = new LNCPPMQ_RC();
    public LNCPPMQ_KEY KEY = new LNCPPMQ_KEY();
    public LNCPPMQ_DATA_EFF_DEFINE DATA_EFF_DEFINE = new LNCPPMQ_DATA_EFF_DEFINE();
    public LNCPPMQ_DATA_MDL DATA_MDL = new LNCPPMQ_DATA_MDL();
    public LNCPPMQ_DATA_CMT DATA_CMT = new LNCPPMQ_DATA_CMT();
    public LNCPPMQ_DATA_TXT DATA_TXT = new LNCPPMQ_DATA_TXT();
    public LNCPPMQ_DATA_CONT_SPC DATA_CONT_SPC = new LNCPPMQ_DATA_CONT_SPC();
    public String VOUCH_TYP = " ";
}
