package com.hisun.LN;

public class LNCPPMQ_DATA_EFF_DEFINE {
    public LNCPPMQ_DATA_MDL_DEFINE DATA_MDL_DEFINE = new LNCPPMQ_DATA_MDL_DEFINE();
    public LNCPPMQ_DATA_CMT_DEFINE DATA_CMT_DEFINE = new LNCPPMQ_DATA_CMT_DEFINE();
    public LNCPPMQ_DATA_TXT_DEFINE DATA_TXT_DEFINE = new LNCPPMQ_DATA_TXT_DEFINE();
}
