package com.hisun.LN;

public class LNCQRCVD_BODY {
    public String CONTRACT_NO = " ";
    public int SUB_CTA_NO = 0;
    public char AMT_TYP = ' ';
    public short TERM = 0;
    public int SUBS_PROJ_NO = 0;
    public int VAL_DT = 0;
    public int DUE_DT = 0;
    public char TERM_STS = ' ';
    public int OVD_DT = 0;
    public char REPY_STS = ' ';
    public String P_REC_AMT = " ";
    public String P_PAY_AMT = " ";
    public String P_WAV_AMT = " ";
    public String I_REC_AMT = " ";
    public String I_PAY_AMT = " ";
    public String I_WAV_AMT = " ";
    public String F_REC_AMT = " ";
    public String F_PAY_AMT = " ";
    public String F_WAV_AMT = " ";
    public String O_REC_AMT = " ";
    public String O_PAY_AMT = " ";
    public String O_WAV_AMT = " ";
    public String O_LST_CAL_AMT = " ";
    public String O_LST_PST_AMT = " ";
    public String L_REC_AMT = " ";
    public String L_PAY_AMT = " ";
    public String L_WAV_AMT = " ";
    public String L_LST_CAL_AMT = " ";
    public String L_LST_PST_AMT = " ";
    public int PI_STOP_DT = 0;
    public String ALL_IN_RATE = " ";
    public char REC_FLG = ' ';
    public short CLR_TYP = 0;
    public int CRT_DATE = 0;
    public String CRT_TLR = " ";
    public int UPDTBL_DATE = 0;
    public String UPDTBL_TLR = " ";
    public String TS = " ";
}
