package com.hisun.LN;

public class LNCURTN_REC_DATA {
    public LNCURTN_KEY KEY = new LNCURTN_KEY();
    public char RATE_FLG = ' ';
    public char FLT_FLG = ' ';
    public char CHN_TYP = ' ';
    public short FLT_DAY = 0;
    public short FLT_GAP_PERD = 0;
    public char FIRST_FLT_FLG = ' ';
    public int FST_FLT_DT = 0;
    public char VARIATION_METHOD = ' ';
    public String INT_RATE_TYPE1 = " ";
    public String INT_RATE_CLAS1 = " ";
    public double BASE_RATE1 = 0;
    public double RATE_VARIATION1 = 0;
    public double RATE_PECT1 = 0;
    public char COMPARISON_METHOD = ' ';
    public double MAX_RATE = 0;
    public double MIN_RATE = 0;
    public String INT_RATE_TYPE2 = " ";
    public String INT_RATE_CLAS2 = " ";
    public double BASE_RATE2 = 0;
    public double RATE_VARIATION2 = 0;
    public double RATE_PECT2 = 0;
    public String INT_RATE_TYPE3 = " ";
    public String INT_RATE_CLAS3 = " ";
    public double BASE_RATE3 = 0;
    public double RATE_VARIATION3 = 0;
    public double RATE_PECT3 = 0;
    public double COST_OF_FUND_RATE = 0;
    public String INTEREST_BASE_MEMO = " ";
    public String PREMIUM_RATE_TYPE = " ";
    public String PREMIUM_RATE_CLAS = " ";
    public double PREMIUM_RATE = 0;
    public double ADD_ON_RATE = 0;
    public double ALL_IN_RATE = 0;
    public int CRT_DATE = 0;
    public String CRT_TLR = " ";
    public int UPDTBL_DATE = 0;
    public String UPDTBL_TLR = " ";
    public String SUP1 = " ";
    public String SUP2 = " ";
    public String TS = " ";
}
