package com.hisun.LN;

import com.hisun.SM.*;
import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;

import java.io.IOException;
import java.sql.SQLException;

public class LNOT7091 {
    String JIBS_tmp_str[] = new String[10];
    char K_ERROR = 'E';
    LNOT7091_WS_TEMP_VARIABLE WS_TEMP_VARIABLE = new LNOT7091_WS_TEMP_VARIABLE();
    LNCXP09 LNCXP09 = new LNCXP09();
    SMCMSG_ERROR_MSG SMCMSG_ERROR_MSG = new SMCMSG_ERROR_MSG();
    SCCWOUT SCCWOUT = new SCCWOUT();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    SCCMPAG SCCMPAG = new SCCMPAG();
    SCCFMT SCCFMT = new SCCFMT();
    LNCCMTPM LNCCMTPM = new LNCCMTPM();
    SCCGWA SCCGWA;
    LNB7090_AWA_7090 LNB7090_AWA_7090;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROCESS();
        B000_MAIN_PROCESS();
        CEP.TRC(SCCGWA, "LNOT7091 return!");
        Z_RET();
    }
    public void A000_INIT_PROCESS() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "LNB7090_AWA_7090>");
        LNB7090_AWA_7090 = (LNB7090_AWA_7090) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
    }
    public void B000_MAIN_PROCESS() throws IOException,SQLException,Exception {
        B100_CHECK_INPUT();
        B200_CALL_LNZCMTPM();
        B300_OUTPUT_PROCESS();
    }
    public void B100_CHECK_INPUT() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, LNB7090_AWA_7090.FUNC);
        CEP.TRC(SCCGWA, LNB7090_AWA_7090.PTYP);
        CEP.TRC(SCCGWA, LNB7090_AWA_7090.CODE);
        CEP.TRC(SCCGWA, LNB7090_AWA_7090.EFFDATE);
        CEP.TRC(SCCGWA, LNB7090_AWA_7090.EXPDATE);
        CEP.TRC(SCCGWA, LNB7090_AWA_7090.DESC);
        CEP.TRC(SCCGWA, LNB7090_AWA_7090.CDESC);
        CEP.TRC(SCCGWA, LNB7090_AWA_7090.PRODMO);
        CEP.TRC(SCCGWA, LNB7090_AWA_7090.PROD_MOD);
        CEP.TRC(SCCGWA, LNB7090_AWA_7090.BAL_FLG);
        CEP.TRC(SCCGWA, LNB7090_AWA_7090.PROD_CLS);
        CEP.TRC(SCCGWA, LNB7090_AWA_7090.SYS_FLG);
        CEP.TRC(SCCGWA, LNB7090_AWA_7090.OVER_FLG);
        CEP.TRC(SCCGWA, LNB7090_AWA_7090.ADV_FLG);
        CEP.TRC(SCCGWA, LNB7090_AWA_7090.ADV_CODE);
        if (LNB7090_AWA_7090.FUNC != 'I' 
            && LNB7090_AWA_7090.FUNC != 'A' 
            && LNB7090_AWA_7090.FUNC != 'M' 
            && LNB7090_AWA_7090.FUNC != 'D') {
            IBS.CPY2CLS(SCCGWA, SMCMSG_ERROR_MSG.SM_INPUT_ERROR, WS_TEMP_VARIABLE.WS_MSGID);
            IBS.CPY2CLS(SCCGWA, SMCMSG_ERROR_MSG.SM_INPUT_ERROR, LNCCMTPM.RC);
            WS_TEMP_VARIABLE.WS_FLD_NO = LNB7090_AWA_7090.FUNC_NO;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        R00_CHECK_ERROR();
    }
    public void B200_CALL_LNZCMTPM() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCCMTPM);
        CEP.TRC(SCCGWA, LNB7090_AWA_7090.PTYP);
        CEP.TRC(SCCGWA, LNB7090_AWA_7090.CODE);
        LNCCMTPM.FUNC = LNB7090_AWA_7090.FUNC;
        LNCCMTPM.KEY.TYPE = LNB7090_AWA_7090.PTYP;
        LNCCMTPM.KEY.CODE = LNB7090_AWA_7090.CODE;
        LNCCMTPM.EFF_DATE = LNB7090_AWA_7090.EFFDATE;
        LNCCMTPM.EXP_DATE = LNB7090_AWA_7090.EXPDATE;
        LNCCMTPM.DESC = LNB7090_AWA_7090.DESC;
        LNCCMTPM.CDESC = LNB7090_AWA_7090.CDESC;
        LNCCMTPM.DATA_TXT.PRODMO = LNB7090_AWA_7090.PRODMO;
        LNCCMTPM.DATA_TXT.PROD_MOD = LNB7090_AWA_7090.PROD_MOD;
        LNCCMTPM.DATA_TXT.BAL_FLG = LNB7090_AWA_7090.BAL_FLG;
        LNCCMTPM.DATA_TXT.PROD_CLS = LNB7090_AWA_7090.PROD_CLS;
        LNCCMTPM.DATA_TXT.SYS_FLG = LNB7090_AWA_7090.SYS_FLG;
        LNCCMTPM.DATA_TXT.OVER_FLG = LNB7090_AWA_7090.OVER_FLG;
        LNCCMTPM.DATA_TXT.AUTO_DISB = LNB7090_AWA_7090.ADV_FLG;
        LNCCMTPM.DATA_TXT.ADV_CODE = LNB7090_AWA_7090.ADV_CODE;
        CEP.TRC(SCCGWA, LNB7090_AWA_7090.ADV_UNT);
        CEP.TRC(SCCGWA, LNB7090_AWA_7090.ADV_PERD);
        CEP.TRC(SCCGWA, LNCCMTPM.DATA_TXT.SYS_FLG);
        CEP.TRC(SCCGWA, LNCCMTPM.DATA_TXT.OVER_FLG);
        CEP.TRC(SCCGWA, LNCCMTPM.DATA_TXT.AUTO_DISB);
        CEP.TRC(SCCGWA, LNCCMTPM.DATA_TXT.ADV_CODE);
        LNCCMTPM.DATA_LEN = 23;
        S000_CALL_LNZCMTPM();
    }
    public void B300_OUTPUT_PROCESS() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCXP09);
        IBS.init(SCCGWA, SCCFMT);
        LNCXP09.FUNC = LNCCMTPM.FUNC;
        LNCXP09.TYPE = LNCCMTPM.KEY.TYPE;
        LNCXP09.CODE = LNCCMTPM.KEY.CODE;
        LNCXP09.DESC = LNCCMTPM.DESC;
        LNCXP09.CDESC = LNCCMTPM.CDESC;
        LNCXP09.EFF_DATE = LNCCMTPM.EFF_DATE;
        LNCXP09.EXP_DATE = LNCCMTPM.EXP_DATE;
        LNCXP09.PRODMO = LNCCMTPM.DATA_TXT.PRODMO;
        LNCXP09.PROD_MOD = LNCCMTPM.DATA_TXT.PROD_MOD;
        LNCXP09.BAL_FLG = LNCCMTPM.DATA_TXT.BAL_FLG;
        LNCXP09.PROD_CLS = LNCCMTPM.DATA_TXT.PROD_CLS;
        LNCXP09.SYS_FLG = LNCCMTPM.DATA_TXT.SYS_FLG;
        LNCXP09.OVER_FLG = LNCCMTPM.DATA_TXT.OVER_FLG;
        LNCXP09.ADV_FLG = LNCCMTPM.DATA_TXT.AUTO_DISB;
        LNCXP09.ADV_CODE = LNCCMTPM.DATA_TXT.ADV_CODE;
        CEP.TRC(SCCGWA, LNCCMTPM.DATA_TXT.AUTO_DISB);
        CEP.TRC(SCCGWA, LNCCMTPM.DATA_TXT.ADV_CODE);
        CEP.TRC(SCCGWA, LNCXP09.FUNC);
        CEP.TRC(SCCGWA, LNCXP09.TYPE);
        CEP.TRC(SCCGWA, LNCXP09.CODE);
        CEP.TRC(SCCGWA, LNCXP09.DESC);
        CEP.TRC(SCCGWA, LNCXP09.CDESC);
        CEP.TRC(SCCGWA, LNCXP09.EFF_DATE);
        CEP.TRC(SCCGWA, LNCXP09.EXP_DATE);
        CEP.TRC(SCCGWA, LNCXP09.VAL_LEN);
        CEP.TRC(SCCGWA, LNCXP09.PRODMO);
        CEP.TRC(SCCGWA, LNCXP09.PROD_MOD);
        CEP.TRC(SCCGWA, LNCXP09.BAL_FLG);
        CEP.TRC(SCCGWA, LNCXP09.PROD_CLS);
        CEP.TRC(SCCGWA, LNCXP09.OVER_FLG);
        CEP.TRC(SCCGWA, LNCXP09.ADV_FLG);
        CEP.TRC(SCCGWA, LNCXP09.ADV_CODE);
        SCCFMT.FMTID = "LNP09";
        SCCFMT.DATA_PTR = LNCXP09;
        SCCFMT.DATA_LEN = 141;
        IBS.FMT(SCCGWA, SCCFMT);
    }
    public void R00_CHECK_ERROR() throws IOException,SQLException,Exception {
        if (SCCGWA.COMM_AREA.MSG_PROC_AREA.MSG_TYPE == K_ERROR 
            && SCCGWA.COMM_AREA.MSG_PROC_AREA.MSG_ID.MSG_CODE == 0) {
            IBS.CPY2CLS(SCCGWA, SMCMSG_ERROR_MSG.SM_INPUT_ERROR, WS_TEMP_VARIABLE.WS_MSGID);
            WS_TEMP_VARIABLE.WS_FLD_NO = 0;
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_LNZCMTPM() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, LNCCMTPM);
        IBS.CALLCPN(SCCGWA, "LN-PRM-CMTPM-MAINT", LNCCMTPM);
        CEP.TRC(SCCGWA, LNCCMTPM);
        if (LNCCMTPM.RC.RC_RTNCODE != 0) {
            WS_TEMP_VARIABLE.WS_MSGID.WS_MSG_AP = LNCCMTPM.RC.RC_APP;
            WS_TEMP_VARIABLE.WS_MSGID.WS_MSG_CODE = LNCCMTPM.RC.RC_RTNCODE;
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, WS_TEMP_VARIABLE.WS_MSGID);
        CEP.ERR(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_FLD_NO);
    }
    public void S000_ERR_MSG_PROC_CONTINUE() throws IOException,SQLException,Exception {
        JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, WS_TEMP_VARIABLE.WS_MSGID);
        CEP.ERRC(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_FLD_NO);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
