package com.hisun.LN;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;

import java.io.IOException;
import java.sql.SQLException;

public class LNOT2139 {
    int JIBS_tmp_int;
    char K_ERROR = 'E';
    String WS_ERR_MSG = " ";
    short WS_FLD_NO = 0;
    char WS_PROD_IND = ' ';
    LNCMSG_ERROR_MSG LNCMSG_ERROR_MSG = new LNCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    SCCMPAG SCCMPAG = new SCCMPAG();
    SCCFMT SCCFMT = new SCCFMT();
    LNCSGMST LNCSGMST = new LNCSGMST();
    LNCSSTBL LNCSSTBL = new LNCSSTBL();
    SCCGWA SCCGWA;
    LNB2130_AWA_2130 LNB2130_AWA_2130;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    SCCGSCA_SC_AREA SCCGSCA_SC_AREA;
    SCCGAPV SCCGAPV;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "LNOT2139 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "LNB2130_AWA_2130>");
        LNB2130_AWA_2130 = (LNB2130_AWA_2130) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        SCCGSCA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        SCCGAPV = (SCCGAPV) SCCGSCA_SC_AREA.APVL_AREA_PTR;
        LNCSGMST.RC.RC_MMO = "LN";
        LNCSGMST.RC.RC_CODE = 0;
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B010_CHECK_INPUT();
        B020_PROC_MAIN();
    }
    public void B010_CHECK_INPUT() throws IOException,SQLException,Exception {
        if (SCCGWA.COMM_AREA.MSG_PROC_AREA.MSG_TYPE == K_ERROR 
            && SCCGWA.COMM_AREA.MSG_PROC_AREA.MSG_ID.MSG_CODE == 0) {
            WS_ERR_MSG = LNCMSG_ERROR_MSG.LN_ERR_MUST_INPUT;
            WS_FLD_NO = 0;
            S000_ERR_MSG_PROC();
        }
        IBS.init(SCCGWA, LNCSSTBL);
        LNCSSTBL.CON_NO = LNB2130_AWA_2130.CONT_NO;
        LNCSSTBL.TR_CODE = "" + SCCGWA.COMM_AREA.TR_ID.TR_CODE;
        JIBS_tmp_int = LNCSSTBL.TR_CODE.length();
        for (int i=0;i<4-JIBS_tmp_int;i++) LNCSSTBL.TR_CODE = "0" + LNCSSTBL.TR_CODE;
        CEP.TRC(SCCGWA, LNCSSTBL.TR_CODE);
        S000_CALL_LNZSSTBL();
    }
    public void B020_PROC_MAIN() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, LNB2130_AWA_2130.CCY);
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.AC_DATE);
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.JRN_NO);
        IBS.init(SCCGWA, LNCSGMST);
        IBS.init(SCCGWA, LNCSGMST.RC);
        LNCSGMST.FUNC = ' ';
        LNCSGMST.GMST_OPT = ' ';
        IBS.init(SCCGWA, LNCSGMST.DATA);
        IBS.init(SCCGWA, LNCSGMST.DIARY);
        LNCSGMST.ROLE_TYPE = ' ';
        LNCSGMST.CNT = 0;
        LNCSGMST.DATA.DRAW_NO = LNB2130_AWA_2130.PAPER_NO;
        LNCSGMST.DATA.TC_NAM = LNB2130_AWA_2130.TC_NAM;
        LNCSGMST.DATA.KEY.CONT_NO = LNB2130_AWA_2130.CONT_NO;
        LNCSGMST.DATA.KEY.SUB_CONT_NO = "" + 0;
        JIBS_tmp_int = LNCSGMST.DATA.KEY.SUB_CONT_NO.length();
        for (int i=0;i<0-JIBS_tmp_int;i++) LNCSGMST.DATA.KEY.SUB_CONT_NO = "0" + LNCSGMST.DATA.KEY.SUB_CONT_NO;
        LNCSGMST.DATA.CMMT_NO = LNB2130_AWA_2130.CMMT_NO;
        LNCSGMST.DATA.PAPER_NO = LNB2130_AWA_2130.DRAW_NO;
        LNCSGMST.DATA.BOOK_BR = LNB2130_AWA_2130.BOOK_BR;
        LNCSGMST.DATA.DOMI_BR = LNB2130_AWA_2130.DOMI_BR;
        LNCSGMST.DATA.CI_NO = LNB2130_AWA_2130.CI_NO;
        LNCSGMST.DATA.CI_ATTR = 'Y';
        LNCSGMST.DATA.PROD_CD = LNB2130_AWA_2130.PROD_CD;
        LNCSGMST.DATA.PROD_NM = LNB2130_AWA_2130.PROD_NM;
        LNCSGMST.DATA.STR_DT = LNB2130_AWA_2130.STR_DT;
        LNCSGMST.DATA.MAT_DT = LNB2130_AWA_2130.MAT_DT;
        LNCSGMST.DATA.CCY = LNB2130_AWA_2130.CCY;
        CEP.TRC(SCCGWA, LNB2130_AWA_2130.CCY);
        CEP.TRC(SCCGWA, LNCSGMST.DATA.CCY);
        LNCSGMST.DATA.PRIN = LNB2130_AWA_2130.PRIN;
        LNCSGMST.DATA.EX_RATE = LNB2130_AWA_2130.EX_RATE;
        LNCSGMST.DATA.EQU_AMT = LNB2130_AWA_2130.EQU_AMT;
        LNCSGMST.DATA.FINA_FLG = LNB2130_AWA_2130.FINA_FLG;
        LNCSGMST.DATA.GAUR_TY = LNB2130_AWA_2130.GAUR_TY;
        LNCSGMST.DATA.IS_AREA = LNB2130_AWA_2130.IS_AREA;
        LNCSGMST.DATA.PAY_AC = LNB2130_AWA_2130.PAY_AC;
        LNCSGMST.DATA.P_AC_NM = LNB2130_AWA_2130.P_AC_NM;
        LNCSGMST.DATA.RMK1 = LNB2130_AWA_2130.RMK1;
        LNCSGMST.DATA.BEN_NM = LNB2130_AWA_2130.BEN_NAM;
        LNCSGMST.DATA.BEN_AC = LNB2130_AWA_2130.BEN_AC;
        LNCSGMST.DATA.B_AC_NM = LNB2130_AWA_2130.B_AC_NM;
        LNCSGMST.DATA.LC_NO = LNB2130_AWA_2130.LC_NO;
        LNCSGMST.DATA.M_NO = LNB2130_AWA_2130.M_NO;
        LNCSGMST.DATA.M_SEQ = LNB2130_AWA_2130.M_SEQ;
        LNCSGMST.DATA.PRAT_FLG = LNB2130_AWA_2130.PRAT_FLG;
        LNCSGMST.DATA.FLT_MTH = LNB2130_AWA_2130.FLT_MTH;
        LNCSGMST.DATA.PEN_RATT = LNB2130_AWA_2130.PEN_RATT;
        LNCSGMST.DATA.PEN_RATC = LNB2130_AWA_2130.PEN_RATC;
        LNCSGMST.DATA.PEN_SPR = LNB2130_AWA_2130.PEN_SPR;
        LNCSGMST.DATA.PEN_PCT = LNB2130_AWA_2130.PEN_PCT;
        LNCSGMST.DATA.PEN_IRAT = LNB2130_AWA_2130.PEN_IRAT;
        LNCSGMST.DATA.SYN_N = LNB2130_AWA_2130.SYN_N;
        LNCSGMST.DATA.LRAT_FLG = LNB2130_AWA_2130.LRAT_FLG;
        LNCSGMST.DATA.LFLT_MTH = LNB2130_AWA_2130.LFLT_MTH;
        LNCSGMST.DATA.L_RATT = LNB2130_AWA_2130.L_RATT;
        LNCSGMST.DATA.L_RATC = LNB2130_AWA_2130.L_RATC;
        LNCSGMST.DATA.L_SPR = LNB2130_AWA_2130.L_SPR;
        LNCSGMST.DATA.L_PCT = LNB2130_AWA_2130.L_PCT;
        LNCSGMST.DATA.L_IRAT = LNB2130_AWA_2130.L_IRAT;
        LNCSGMST.DATA.VCH_FLG = LNB2130_AWA_2130.VCH_FLG;
        LNCSGMST.FUNC = 'D';
        S000_CALL_LNZSGMST();
    }
    public void S000_CALL_LNZSSTBL() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-CHECK-CI-STS", LNCSSTBL);
        if (LNCSSTBL.RC.RC_CODE != 0) {
            WS_ERR_MSG = IBS.CLS2CPY(SCCGWA, LNCSSTBL.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_LNZSGMST() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-S-GUARANTEE-MAIN", LNCSGMST);
        if (LNCSGMST.RC.RC_CODE != 0) {
            WS_ERR_MSG = IBS.CLS2CPY(SCCGWA, LNCSGMST.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG);
    }
    public void S000_ERR_MSG_PROC_CONTINUE() throws IOException,SQLException,Exception {
        CEP.ERRC(SCCGWA, WS_ERR_MSG, WS_FLD_NO);
    }
    public void S000_ERR_MSG_PROC_LAST() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
