package com.hisun.LN;

public class LNOT6080_WS_TR_DATA {
    String WS_ICTL_STSW = " ";
    short WS_ICTL_P_CUR_TERM = 0;
    short WS_ICTL_IC_CUR_TERM = 0;
    int WS_CONT_VAL_DATE = 0;
    int WS_CONT_TX_DT = 0;
    int WS_CONT_TX_SEQ = 0;
    char WS_CONT_CTA_STS = ' ';
    int WS_TMP_TOT_NUM = 0;
    LNOT6080_WS_BALLM_AMT_TMP_AREA WS_BALLM_AMT_TMP_AREA = new LNOT6080_WS_BALLM_AMT_TMP_AREA();
    LNOT6080_WS_CONT WS_CONT = new LNOT6080_WS_CONT();
    LNOT6080_WS_RCVD_DATA WS_RCVD_DATA = new LNOT6080_WS_RCVD_DATA();
    LNOT6080_WS_PLPI_DATA WS_PLPI_DATA = new LNOT6080_WS_PLPI_DATA();
}
