package com.hisun.LN;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;

import java.io.IOException;
import java.sql.SQLException;

public class LNOT2279 {
    String WS_ERR_MSG = " ";
    short WS_FLD_NO = 0;
    String WS_ERR_INFO = " ";
    LNCMSG_ERROR_MSG LNCMSG_ERROR_MSG = new LNCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    LNCSDPO LNCSDPO = new LNCSDPO();
    SCCGWA SCCGWA;
    LNB2270_AWA_2270 LNB2270_AWA_2270;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "LNOT2279 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "LNB2270_AWA_2270>");
        LNB2270_AWA_2270 = (LNB2270_AWA_2270) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        IBS.init(SCCGWA, LNCSDPO);
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, LNB2270_AWA_2270.CTA_NO);
        CEP.TRC(SCCGWA, LNB2270_AWA_2270.BR);
        CEP.TRC(SCCGWA, LNB2270_AWA_2270.CI_NO);
        CEP.TRC(SCCGWA, LNB2270_AWA_2270.CI_CNM);
        CEP.TRC(SCCGWA, LNB2270_AWA_2270.PROD_CD);
        CEP.TRC(SCCGWA, LNB2270_AWA_2270.PROD_DE);
        CEP.TRC(SCCGWA, LNB2270_AWA_2270.DW_MTH);
        CEP.TRC(SCCGWA, LNB2270_AWA_2270.TR_VALDT);
        CEP.TRC(SCCGWA, LNB2270_AWA_2270.CCY);
        CEP.TRC(SCCGWA, LNB2270_AWA_2270.LON_PRIN);
        CEP.TRC(SCCGWA, LNB2270_AWA_2270.LON_BAL);
        CEP.TRC(SCCGWA, LNB2270_AWA_2270.I_INT);
        CEP.TRC(SCCGWA, LNB2270_AWA_2270.O_INT);
        CEP.TRC(SCCGWA, LNB2270_AWA_2270.DB_NO);
        CEP.TRC(SCCGWA, LNB2270_AWA_2270.DB_NAME);
        CEP.TRC(SCCGWA, LNB2270_AWA_2270.TOT_AMT);
        CEP.TRC(SCCGWA, LNB2270_AWA_2270.SETT_FLG);
        CEP.TRC(SCCGWA, LNB2270_AWA_2270.LOSS_AMT);
        CEP.TRC(SCCGWA, LNB2270_AWA_2270.PY_P_AMT);
        CEP.TRC(SCCGWA, LNB2270_AWA_2270.PY_I_INT);
        CEP.TRC(SCCGWA, LNB2270_AWA_2270.PY_O_INT);
        CEP.TRC(SCCGWA, LNB2270_AWA_2270.PY_AC);
        CEP.TRC(SCCGWA, LNB2270_AWA_2270.RVS_NO);
        B010_CHECK_INPUT();
        B030_CALL_REAPY_SERVICE();
    }
    public void B010_CHECK_INPUT() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, LNB2270_AWA_2270.CTA_NO);
        if (LNB2270_AWA_2270.CTA_NO.trim().length() == 0) {
            WS_ERR_MSG = LNCMSG_ERROR_MSG.LN_ERR_MUST_INPUT;
            WS_FLD_NO = LNB2270_AWA_2270.CTA_NO_NO;
            WS_ERR_INFO = "AWA-CTA-NO";
            S000_ERR_MSG_PROC_CONTINUE();
        }
        CEP.TRC(SCCGWA, LNB2270_AWA_2270.TR_VALDT);
        LNB2270_AWA_2270.TR_VALDT = SCCGWA.COMM_AREA.AC_DATE;
        S000_ERR_MSG_PROC_LAST();
    }
    public void B030_CALL_REAPY_SERVICE() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCSDPO);
        LNCSDPO.TXN_INFO.TXN_DT = GWA_BP_AREA.CANCEL_AREA.CAN_AC_DATE;
        LNCSDPO.TXN_INFO.JRNNO = GWA_BP_AREA.CANCEL_AREA.CAN_JRN_NO;
        LNCSDPO.COMM_DATA.CTA_NO = LNB2270_AWA_2270.CTA_NO;
        LNCSDPO.COMM_DATA.BR = LNB2270_AWA_2270.BR;
        LNCSDPO.COMM_DATA.CI_NO = LNB2270_AWA_2270.CI_NO;
        LNCSDPO.COMM_DATA.CI_CNM = LNB2270_AWA_2270.CI_CNM;
        LNCSDPO.COMM_DATA.PROD_CD = LNB2270_AWA_2270.PROD_CD;
        LNCSDPO.COMM_DATA.PROD_DE = LNB2270_AWA_2270.PROD_DE;
        LNCSDPO.COMM_DATA.DW_MTH = LNB2270_AWA_2270.DW_MTH;
        LNCSDPO.COMM_DATA.TR_VALDT = LNB2270_AWA_2270.TR_VALDT;
        LNCSDPO.COMM_DATA.CCY = LNB2270_AWA_2270.CCY;
        LNCSDPO.COMM_DATA.LON_PRIN = LNB2270_AWA_2270.LON_PRIN;
        LNCSDPO.COMM_DATA.LON_BAL = LNB2270_AWA_2270.LON_BAL;
        LNCSDPO.COMM_DATA.I_INT = LNB2270_AWA_2270.I_INT;
        LNCSDPO.COMM_DATA.O_INT = LNB2270_AWA_2270.O_INT;
        LNCSDPO.COMM_DATA.DB_NO = LNB2270_AWA_2270.DB_NO;
        LNCSDPO.COMM_DATA.DB_NAME = LNB2270_AWA_2270.DB_NAME;
        LNCSDPO.COMM_DATA.TOT_AMT = LNB2270_AWA_2270.TOT_AMT;
        LNCSDPO.COMM_DATA.SETT_FLG = LNB2270_AWA_2270.SETT_FLG;
        LNCSDPO.COMM_DATA.LOSS_AMT = LNB2270_AWA_2270.LOSS_AMT;
        LNCSDPO.COMM_DATA.PY_P_AMT = LNB2270_AWA_2270.PY_P_AMT;
        LNCSDPO.COMM_DATA.PY_I_INT = LNB2270_AWA_2270.PY_I_INT;
        LNCSDPO.COMM_DATA.PY_O_INT = LNB2270_AWA_2270.PY_O_INT;
        LNCSDPO.COMM_DATA.PY_AC = LNB2270_AWA_2270.PY_AC;
        LNCSDPO.COMM_DATA.RVS_NO = LNB2270_AWA_2270.RVS_NO;
        S000_CALL_LNZSDPO();
    }
    public void S000_CALL_LNZSDPO() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-SRV-D-REPAY", LNCSDPO);
        if (LNCSDPO.RC.RC_RTNCODE != 0) {
            WS_ERR_MSG = IBS.CLS2CPY(SCCGWA, LNCSDPO.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_ERR_MSG_PROC_CONTINUE() throws IOException,SQLException,Exception {
        CEP.ERRC(SCCGWA, WS_ERR_MSG, WS_FLD_NO);
    }
    public void S000_ERR_MSG_PROC_LAST() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG);
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
