package com.hisun.LN;

import java.io.IOException;
import java.sql.SQLException;

import com.hisun.CI.CICCUST;
import com.hisun.CI.CICQACRI;
import com.hisun.SC.SCCCALL;
import com.hisun.SC.SCCEXCP;
import com.hisun.SC.SCCGBPA_BP_AREA;
import com.hisun.SC.SCCGSCA_SC_AREA;
import com.hisun.SC.SCCGWA;
import com.hisun.SC.SCCMSG;
import com.hisun.SC.SCCTPCL;

public class LNOT4109 {
    boolean pgmRtn = false;
    String WS_ERR_MSG = " ";
    short WS_FLD_NO = 0;
    int WS_K = 0;
    int WS_I = 0;
    short WS_FIX_TERM = 0;
    char WS_INT_MODE_FLAG = ' ';
    char WS_SYN_FLG_FLAG = ' ';
    char WS_FEE_FLG = ' ';
    double WS_AMT = 0;
    LNCMSG_ERROR_MSG LNCMSG_ERROR_MSG = new LNCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    LNCSERRP LNCSEPRS = new LNCSERRP();
    LNRAPRD LNRAPRD = new LNRAPRD();
    LNRAGRE LNRAGRE = new LNRAGRE();
    LNRICTL LNRICTL = new LNRICTL();
    SCCTPCL SCCTPCL = new SCCTPCL();
    CICQACRI CICQACRI = new CICQACRI();
    CICCUST CICCUST = new CICCUST();
    SCCGWA SCCGWA;
    LNB4100_AWA_4100 LNB4100_AWA_4100;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        if (pgmRtn) return;
        B000_MAIN_PROC();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, "LNOT4109 return!");
        Z_RET();
        if (pgmRtn) return;
        JIBS_RETURN();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "LNB4100_AWA_4100>");
        LNB4100_AWA_4100 = (LNB4100_AWA_4100) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B010_CHECK_INPUT();
        if (pgmRtn) return;
        if (SCCGWA.COMM_AREA.CANCEL_IND == 'Y') {
            B020_EARLY_PAY_PROC();
            if (pgmRtn) return;
        } else {
            B020_EARLY_PAY_PROC();
            if (pgmRtn) return;
        }
    }
    public void B010_CHECK_INPUT() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.CTA_NO);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.BR);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.CI_NO);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.CI_CNM);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.PROD_CD);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.PROD_DE);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.CCY);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.PRINCIPA);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.BALANCE);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.TR_VAL_D);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.TOT_P_AM);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.INT_MODE);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.PC_RATE);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.TOT_I_AM);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.PC_AMT);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.TOT_AMT);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.HRG_AMT);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.SYN_FLG);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.EE_TERM);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.CHK_NO);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.CLN_CUT);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.TR_MMO);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.MLT_STL);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.CLN_CUT);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.PART_INF[1-1].JOIN_BR);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.PART_INF[2-1].JOIN_BR);
        if (LNB4100_AWA_4100.CTA_NO.trim().length() == 0) {
            WS_ERR_MSG = LNCMSG_ERROR_MSG.LN_ERR_MUST_INPUT;
            WS_FLD_NO = LNB4100_AWA_4100.CTA_NO_NO;
            S000_ERR_MSG_PROC_CONTINUE();
            if (pgmRtn) return;
        }
        if (LNB4100_AWA_4100.TR_VAL_D == 0) {
            WS_ERR_MSG = LNCMSG_ERROR_MSG.LN_ERR_MUST_INPUT;
            WS_FLD_NO = LNB4100_AWA_4100.TR_VAL_D_NO;
            S000_ERR_MSG_PROC_CONTINUE();
            if (pgmRtn) return;
        }
        CEP.TRC(SCCGWA, " ");
        WS_INT_MODE_FLAG = LNB4100_AWA_4100.INT_MODE;
        if ((WS_INT_MODE_FLAG != '0' 
            && WS_INT_MODE_FLAG != '1' 
            && WS_INT_MODE_FLAG != '2')) {
            WS_ERR_MSG = LNCMSG_ERROR_MSG.LN_ERR_MUST_INPUT;
            S000_ERR_MSG_PROC();
            if (pgmRtn) return;
        }
        CEP.TRC(SCCGWA, " ");
        if (LNB4100_AWA_4100.SYN_FLG != ' ') {
            WS_SYN_FLG_FLAG = LNB4100_AWA_4100.SYN_FLG;
            if ((WS_SYN_FLG_FLAG != '1' 
                && WS_SYN_FLG_FLAG != '2' 
                && WS_SYN_FLG_FLAG != '3')) {
                WS_ERR_MSG = LNCMSG_ERROR_MSG.LN_ERR_MUST_INPUT;
                S000_ERR_MSG_PROC();
                if (pgmRtn) return;
            }
            CEP.TRC(SCCGWA, " ");
            if (LNB4100_AWA_4100.SYN_FLG == '3' 
                && LNB4100_AWA_4100.EE_TERM.compareTo(0) <= 0) {
                WS_ERR_MSG = LNCMSG_ERROR_MSG.ERR_LN_TERM;
                S000_ERR_MSG_PROC();
                if (pgmRtn) return;
            }
        }
        if (LNB4100_AWA_4100.CLN_CUT != ' ' 
            && LNB4100_AWA_4100.CLN_CUT != '0' 
            && LNB4100_AWA_4100.CLN_CUT != '1' 
            && LNB4100_AWA_4100.CLN_CUT != '2' 
            && LNB4100_AWA_4100.CLN_CUT != '3' 
            && LNB4100_AWA_4100.CLN_CUT != '9') {
            WS_ERR_MSG = LNCMSG_ERROR_MSG.LN_ERR_MUST_INPUT;
            S000_ERR_MSG_PROC();
            if (pgmRtn) return;
        }
        CEP.TRC(SCCGWA, " ");
        WS_FEE_FLG = 'N';
        for (WS_I = 1; WS_I <= 5; WS_I += 1) {
            CEP.TRC(SCCGWA, LNB4100_AWA_4100.FEE_INF[WS_I-1].FEE_CODE);
            CEP.TRC(SCCGWA, LNB4100_AWA_4100.FEE_INF[WS_I-1].FEE_AMT);
            if (LNB4100_AWA_4100.FEE_INF[WS_I-1].FEE_CODE.trim().length() > 0 
                && LNB4100_AWA_4100.FEE_INF[WS_I-1].FEE_AMT == 0) {
                WS_ERR_MSG = LNCMSG_ERROR_MSG.LN_ERR_MUST_INPUT;
                S000_ERR_MSG_PROC();
                if (pgmRtn) return;
            }
            if (LNB4100_AWA_4100.FEE_INF[WS_I-1].FEE_CODE.trim().length() > 0) {
                WS_FEE_FLG = 'Y';
            }
        }
        CEP.TRC(SCCGWA, " ");
        if (WS_FEE_FLG == 'Y' 
            && (!LNB4100_AWA_4100.FEE_ACT.equalsIgnoreCase("01") 
            && !LNB4100_AWA_4100.FEE_ACT.equalsIgnoreCase("02") 
            && !LNB4100_AWA_4100.FEE_ACT.equalsIgnoreCase("03") 
            && !LNB4100_AWA_4100.FEE_ACT.equalsIgnoreCase("04") 
            && !LNB4100_AWA_4100.FEE_ACT.equalsIgnoreCase("05") 
            && !LNB4100_AWA_4100.FEE_ACT.equalsIgnoreCase("06") 
            && !LNB4100_AWA_4100.FEE_ACT.equalsIgnoreCase("07"))) {
            WS_ERR_MSG = LNCMSG_ERROR_MSG.LN_ERR_MUST_INPUT;
            S000_ERR_MSG_PROC();
            if (pgmRtn) return;
        }
        CEP.TRC(SCCGWA, " ");
        if (WS_FEE_FLG == 'Y' 
            && LNB4100_AWA_4100.FEE_AC.trim().length() == 0) {
            WS_ERR_MSG = LNCMSG_ERROR_MSG.LN_ERR_FEEAC_NEED;
            S000_ERR_MSG_PROC();
            if (pgmRtn) return;
        }
        CEP.TRC(SCCGWA, " ");
        CEP.TRC(SCCGWA, "111");
        WS_AMT = LNB4100_AWA_4100.MULT_AC[1-1].PAY_AMT + LNB4100_AWA_4100.MULT_AC[2-1].PAY_AMT + LNB4100_AWA_4100.MULT_AC[3-1].PAY_AMT + LNB4100_AWA_4100.MULT_AC[4-1].PAY_AMT + LNB4100_AWA_4100.MULT_AC[5-1].PAY_AMT;
        if (WS_AMT > LNB4100_AWA_4100.TOT_AMT) {
            CEP.ERR(SCCGWA, LNCMSG_ERROR_MSG.LN_LESS_AMT);
        }
        CEP.TRC(SCCGWA, "WS-AMT");
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.MULT_AC[1-1].PAY_AMT);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.MULT_AC[2-1].PAY_AMT);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.MULT_AC[3-1].PAY_AMT);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.MULT_AC[4-1].PAY_AMT);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.MULT_AC[5-1].PAY_AMT);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.TOT_AMT);
    }
    public void B020_EARLY_PAY_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCSEPRS);
        LNCSEPRS.CTA = LNB4100_AWA_4100.CTA_NO;
        LNCSEPRS.TR_VAL_DTE = LNB4100_AWA_4100.TR_VAL_D;
        LNCSEPRS.TOT_P_AMT = LNB4100_AWA_4100.TOT_P_AM;
        LNCSEPRS.INT_MODE = LNB4100_AWA_4100.INT_MODE;
        LNCSEPRS.PC_RATE = LNB4100_AWA_4100.PC_RATE;
        LNCSEPRS.TOT_I_AMT = LNB4100_AWA_4100.TOT_I_AM;
        LNCSEPRS.PC_AMT = LNB4100_AWA_4100.PC_AMT;
        LNCSEPRS.TOT_AMT = LNB4100_AWA_4100.TOT_AMT;
        CEP.TRC(SCCGWA, LNCSEPRS.TOT_AMT);
        LNCSEPRS.HRG_AMT = LNB4100_AWA_4100.HRG_AMT;
        LNCSEPRS.SYN_FLG = LNB4100_AWA_4100.SYN_FLG;
        if (LNB4100_AWA_4100.EE_TERM.trim().length() == 0) LNCSEPRS.S_TERM = 0;
        else LNCSEPRS.S_TERM = Short.parseShort(LNB4100_AWA_4100.EE_TERM);
        LNCSEPRS.RAT_MTH = LNB4100_AWA_4100.RAT_MTH;
        LNCSEPRS.INT_F_UN = LNB4100_AWA_4100.INT_F_UN;
        LNCSEPRS.INT_F_PD = LNB4100_AWA_4100.INT_F_PD;
        LNCSEPRS.FLT_IPER = LNB4100_AWA_4100.FLT_IPER;
        LNCSEPRS.FLT_ADJF = LNB4100_AWA_4100.FLT_ADJF;
        LNCSEPRS.FT_FLG = LNB4100_AWA_4100.FT_FLG;
        LNCSEPRS.FT_DAY = LNB4100_AWA_4100.FT_DAY;
        LNCSEPRS.FT_F_DAY = LNB4100_AWA_4100.FT_F_DAY;
        LNCSEPRS.FLT_MTH = LNB4100_AWA_4100.FT_MTH;
        LNCSEPRS.RATE_TYP = LNB4100_AWA_4100.RATE_TYP;
        LNCSEPRS.RATE_PD = LNB4100_AWA_4100.RATE_PD;
        LNCSEPRS.RATE_VAR = LNB4100_AWA_4100.RATE_VAR;
        LNCSEPRS.RATE_PCT = LNB4100_AWA_4100.RATE_PCT;
        LNCSEPRS.RATE_INT = LNB4100_AWA_4100.RATE_INT;
        LNCSEPRS.INT_RATE = LNB4100_AWA_4100.INT_RATE;
        LNCSEPRS.PEN_RRAT = LNB4100_AWA_4100.PEN_RRAT;
        LNCSEPRS.PEN_TYP = LNB4100_AWA_4100.PEN_TYP;
        LNCSEPRS.PEN_RATT = LNB4100_AWA_4100.PEN_RATT;
        LNCSEPRS.PEN_RATC = LNB4100_AWA_4100.PEN_RATC;
        LNCSEPRS.PEN_SPR = LNB4100_AWA_4100.PEN_SPR;
        LNCSEPRS.PEN_PCT = LNB4100_AWA_4100.PEN_PCT;
        LNCSEPRS.PEN_IRAT = LNB4100_AWA_4100.PEN_IRAT;
        LNCSEPRS.INT_MTH = LNB4100_AWA_4100.INT_MTH;
        LNCSEPRS.CPND_USE = LNB4100_AWA_4100.CPND_USE;
        LNCSEPRS.CPND_RTY = LNB4100_AWA_4100.CPND_RTY;
        LNCSEPRS.CPND_TYP = LNB4100_AWA_4100.CPND_TYP;
        LNCSEPRS.CPNDRATT = LNB4100_AWA_4100.CPNDRATT;
        LNCSEPRS.CPNDRATC = LNB4100_AWA_4100.CPNDRATC;
        LNCSEPRS.CPND_SPR = LNB4100_AWA_4100.CPND_SPR;
        LNCSEPRS.CPND_PCT = LNB4100_AWA_4100.CPND_PCT;
        LNCSEPRS.CPNDRATE = LNB4100_AWA_4100.CPNDRATE;
        LNCSEPRS.ABUS_RAT = LNB4100_AWA_4100.ABUS_RAT;
        LNCSEPRS.ABUS_TYP = LNB4100_AWA_4100.ABUS_TYP;
        LNCSEPRS.ABUSRATT = LNB4100_AWA_4100.ABUSRATT;
        LNCSEPRS.ABUSRATC = LNB4100_AWA_4100.ABUSRATC;
        LNCSEPRS.ABUSSPR = LNB4100_AWA_4100.ABUSSPR;
        LNCSEPRS.ABUSPCT = LNB4100_AWA_4100.ABUSPCT;
        LNCSEPRS.ABUSIRAT = LNB4100_AWA_4100.ABUSIRAT;
        LNCSEPRS.RPSP_NO = LNB4100_AWA_4100.CHK_NO;
        LNCSEPRS.METH = LNB4100_AWA_4100.CLN_CUT;
        if (SCCGWA.COMM_AREA.BSP_FLG.equalsIgnoreCase("BSP") 
            || SCCGWA.COMM_AREA.CHNL.equalsIgnoreCase("BAT")) {
            LNCSEPRS.TR_MMO = "12010003";
        } else {
            LNCSEPRS.TR_MMO = "12010002";
        }
        LNCSEPRS.MLT_STL = LNB4100_AWA_4100.MLT_STL;
        for (WS_K = 1; WS_K <= 5; WS_K += 1) {
            LNCSEPRS.ACAMT[WS_K-1].STL_MTH2 = LNB4100_AWA_4100.MULT_AC[WS_K-1].STL_MTH;
            LNCSEPRS.ACAMT[WS_K-1].CHQ_NO2 = LNB4100_AWA_4100.MULT_AC[WS_K-1].CHQ_NO;
            LNCSEPRS.ACAMT[WS_K-1].PAY_PSWD = LNB4100_AWA_4100.MULT_AC[WS_K-1].PAY_PSWD;
            LNCSEPRS.ACAMT[WS_K-1].CHQ_TYPE = LNB4100_AWA_4100.MULT_AC[WS_K-1].CHQ_TYPE;
            LNCSEPRS.ACAMT[WS_K-1].ISS_DATE = LNB4100_AWA_4100.MULT_AC[WS_K-1].ISS_DATE;
            LNCSEPRS.ACAMT[WS_K-1].DEP_AC2 = LNB4100_AWA_4100.MULT_AC[WS_K-1].DEP_AC;
            LNCSEPRS.ACAMT[WS_K-1].CCY_TYP = LNB4100_AWA_4100.MULT_AC[WS_K-1].CCY_TYP;
            LNCSEPRS.ACAMT[WS_K-1].AC_FLG2 = LNB4100_AWA_4100.MULT_AC[WS_K-1].AC_FLG;
            LNCSEPRS.ACAMT[WS_K-1].CI_CNM2 = LNB4100_AWA_4100.MULT_AC[WS_K-1].AC_CNM;
            LNCSEPRS.ACAMT[WS_K-1].PAY_AMT2 = LNB4100_AWA_4100.MULT_AC[WS_K-1].PAY_AMT;
            LNCSEPRS.ACAMT[WS_K-1].RVS_NO2 = LNB4100_AWA_4100.MULT_AC[WS_K-1].RVS_NO;
            LNCSEPRS.ACAMT[WS_K-1].REC_CCY2 = LNB4100_AWA_4100.CCY;
            LNCSEPRS.ACAMT[WS_K-1].AMT_FRM2 = LNB4100_AWA_4100.MULT_AC[WS_K-1].AMT_FRM;
            LNCSEPRS.FEE_INFO[WS_K-1].FEE_CD = LNB4100_AWA_4100.FEE_INF[WS_K-1].FEE_CODE;
            CEP.TRC(SCCGWA, LNCSEPRS.FEE_INFO[WS_K-1].FEE_CD);
            LNCSEPRS.FEE_INFO[WS_K-1].FEE_AMT = LNB4100_AWA_4100.FEE_INF[WS_K-1].FEE_AMT;
        }
        LNCSEPRS.FEE_TYP = LNB4100_AWA_4100.FEE_ACT;
        LNCSEPRS.FEE_AC = LNB4100_AWA_4100.FEE_AC;
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.FEE_ACT);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.FEE_AC);
        CEP.TRC(SCCGWA, LNCSEPRS.FEE_AC);
        CEP.TRC(SCCGWA, LNCSEPRS.FEE_TYP);
        CEP.TRC(SCCGWA, LNCSEPRS.FEE_AC);
        for (WS_K = 1; WS_K <= 10; WS_K += 1) {
            LNCSEPRS.SYLOAN_INFO[WS_K-1].SYLOAN_SEQ = "" + LNB4100_AWA_4100.PART_INF[WS_K-1].JOIN_NO;
            JIBS_tmp_int = LNCSEPRS.SYLOAN_INFO[WS_K-1].SYLOAN_SEQ.length();
            for (int i=0;i<8-JIBS_tmp_int;i++) LNCSEPRS.SYLOAN_INFO[WS_K-1].SYLOAN_SEQ = "0" + LNCSEPRS.SYLOAN_INFO[WS_K-1].SYLOAN_SEQ;
            LNCSEPRS.SYLOAN_INFO[WS_K-1].SYLOAN_BR = LNB4100_AWA_4100.PART_INF[WS_K-1].JOIN_BR;
            LNCSEPRS.SYLOAN_INFO[WS_K-1].SYLOAN_NAME = LNB4100_AWA_4100.PART_INF[WS_K-1].JOIN_NM;
            LNCSEPRS.SYLOAN_INFO[WS_K-1].SYLOAN_FLG = LNB4100_AWA_4100.PART_INF[WS_K-1].I_O_FLG;
            LNCSEPRS.SYLOAN_INFO[WS_K-1].SYLOAN_TYP = LNB4100_AWA_4100.PART_INF[WS_K-1].RLA_TYP;
            LNCSEPRS.SYLOAN_INFO[WS_K-1].SYLOAN_P = LNB4100_AWA_4100.PART_INF[WS_K-1].PY_P_AMT;
            LNCSEPRS.SYLOAN_INFO[WS_K-1].SYLOAN_I = LNB4100_AWA_4100.PART_INF[WS_K-1].PY_I_AMT;
            LNCSEPRS.SYLOAN_INFO[WS_K-1].SYLOAN_W = LNB4100_AWA_4100.PART_INF[WS_K-1].PY_PC_AT;
        }
        S000_CALL_LNZSEPRS();
        if (pgmRtn) return;
    }
    public void B030_UPDATE_WAIWEI_INFO() throws IOException,SQLException,Exception {
        if (LNCSEPRS.TOT_P_AMT > 0 
            && !SCCGWA.COMM_AREA.BSP_FLG.equalsIgnoreCase("BSP") 
            && !SCCGWA.COMM_AREA.CHNL.equalsIgnoreCase("BAT")) {
            IBS.init(SCCGWA, LNRAGRE);
            LNRAGRE.KEY.CONTRACT_NO = LNB4100_AWA_4100.CTA_NO;
            LNRAPRD.KEY.CONTRACT_NO = LNB4100_AWA_4100.CTA_NO;
            LNRICTL.KEY.CONTRACT_NO = LNB4100_AWA_4100.CTA_NO;
            T000_READ_LNTAGRE();
            if (pgmRtn) return;
            T000_READ_LNTAPRD();
            if (pgmRtn) return;
            T000_READ_LNTICTL();
            if (pgmRtn) return;
            IBS.init(SCCGWA, SCCTPCL);
            SCCTPCL.SERV_AREA.OBJ_SYSTEM = "ESBP";
            SCCTPCL.SERV_AREA.SERV_CODE = "3002200000902";
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_SEQ = "" + SCCGWA.COMM_AREA.JRN_NO;
            JIBS_tmp_int = SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_SEQ.length();
            for (int i=0;i<12-JIBS_tmp_int;i++) SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_SEQ = "0" + SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_SEQ;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_CTRNO = LNRAGRE.PAPER_NO;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_DBLNO = LNRAGRE.DRAW_NO;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_CCY = LNB4100_AWA_4100.CCY;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_AMT = LNB4100_AWA_4100.TOT_P_AM;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_CHNL = SCCGWA.COMM_AREA.REQ_SYSTEM;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_TYP = LNB4100_AWA_4100.PROD_CD;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_INT = 999;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            if (LNRAPRD.PAY_MTH == '1') {
                SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_PAYTYP = "RPT-03";
                SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            } else if (LNRAPRD.PAY_MTH == '2') {
                SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_PAYTYP = "RPT-04";
                SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            } else if (LNRAPRD.PAY_MTH == '4') {
                SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_PAYTYP = "RPT-01";
                SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            }
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_CYCLE = 0;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_FAMT1 = 0;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_FAMT2 = 0;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_YRATE = LNRICTL.CUR_RAT;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_PAYDT = SCCGWA.COMM_AREA.AC_DATE;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_AC = LNCSEPRS.ACAMT[1-1].RVS_NO2;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            IBS.init(SCCGWA, CICQACRI);
            CICQACRI.DATA.AGR_NO = LNRAGRE.PAPER_NO;
            CEP.TRC(SCCGWA, LNCSEPRS.ACAMT[1-1].RVS_NO2);
            CEP.TRC(SCCGWA, CICQACRI.DATA.AGR_NO);
            CICQACRI.FUNC = 'A';
            S000_CALL_CIZQACRI();
            if (pgmRtn) return;
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_ACNM = CICQACRI.O_DATA.O_AC_CNM;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_BKNM = "" + CICQACRI.O_DATA.O_OWNER_BK;
            JIBS_tmp_int = SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_BKNM.length();
            for (int i=0;i<6-JIBS_tmp_int;i++) SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_BKNM = "0" + SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_BKNM;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_BK = CICQACRI.O_DATA.O_OWNER_BK;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            IBS.init(SCCGWA, CICCUST);
            CICCUST.FUNC = 'A';
            CICCUST.DATA.AGR_NO = LNRAGRE.PAPER_NO;
            S000_CALL_CIZCUST();
            if (pgmRtn) return;
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_CUSTNM = CICCUST.O_DATA.O_CI_NM;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_IDTYP = CICCUST.O_DATA.O_ID_TYPE;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_ID = CICCUST.O_DATA.O_ID_NO;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.SERV_AREA.SERV_TYPE = 'N';
            SCCTPCL.INP_AREA.SERV_DATA_LEN = 1079;
            S000_CALL_SCZTPCL();
            if (pgmRtn) return;
        }
    }
    public void S000_CALL_LNZSEPRS() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-SVR-EARLYPAY-RVS", LNCSEPRS);
        if (LNCSEPRS.RC.RC_RTNCODE != 0) {
