package com.hisun.LN;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;
import com.hisun.CI.*;

import java.io.IOException;
import java.sql.SQLException;

public class LNOT4100 {
    int JIBS_tmp_int;
    DBParm LNTAGRE_RD;
    DBParm LNTAPRD_RD;
    DBParm LNTICTL_RD;
    String WS_ERR_MSG = " ";
    short WS_FLD_NO = 0;
    int WS_K = 0;
    int WS_I = 0;
    short WS_FIX_TERM = 0;
    int WS_DUE_DT = 0;
    char WS_INT_MODE_FLAG = ' ';
    char WS_SYN_FLG_FLAG = ' ';
    char WS_FEE_FLG = ' ';
    double WS_AMT = 0;
    LNCMSG_ERROR_MSG LNCMSG_ERROR_MSG = new LNCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    LNCSERRP LNCSERRP = new LNCSERRP();
    LNRAPRD LNRAPRD = new LNRAPRD();
    LNRAGRE LNRAGRE = new LNRAGRE();
    LNRICTL LNRICTL = new LNRICTL();
    SCCTPCL SCCTPCL = new SCCTPCL();
    CICQACRI CICQACRI = new CICQACRI();
    CICCUST CICCUST = new CICCUST();
    SCCWRMSG SCCWRMSG = new SCCWRMSG();
    SCCGWA SCCGWA;
    LNB4100_AWA_4100 LNB4100_AWA_4100;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "LNOT4100 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "LNB4100_AWA_4100>");
        LNB4100_AWA_4100 = (LNB4100_AWA_4100) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B010_CHECK_INPUT();
        if (SCCGWA.COMM_AREA.CANCEL_IND == 'Y') {
            B020_EARLY_PAY_PROC();
        } else {
            B020_EARLY_PAY_PROC();
        }
        LNRICTL.KEY.CONTRACT_NO = LNB4100_AWA_4100.CTA_NO;
        T000_READ_LNTICTL();
        if (LNRICTL.CTL_STSW == null) LNRICTL.CTL_STSW = "";
        JIBS_tmp_int = LNRICTL.CTL_STSW.length();
        for (int i=0;i<128-JIBS_tmp_int;i++) LNRICTL.CTL_STSW += " ";
        CEP.TRC(SCCGWA, LNRICTL.CTL_STSW.substring(4 - 1, 4 + 1 - 1));
        if (LNRICTL.CTL_STSW == null) LNRICTL.CTL_STSW = "";
        JIBS_tmp_int = LNRICTL.CTL_STSW.length();
        for (int i=0;i<128-JIBS_tmp_int;i++) LNRICTL.CTL_STSW += " ";
        if (LNRICTL.CTL_STSW.substring(4 - 1, 4 + 1 - 1).equalsIgnoreCase("1")) {
            R000_SEND_MESSAGE();
        }
    }
    public void B010_CHECK_INPUT() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.CTA_NO);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.BR);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.CI_NO);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.CI_CNM);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.PROD_CD);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.PROD_DE);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.CCY);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.PRINCIPA);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.BALANCE);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.TR_VAL_D);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.TOT_P_AM);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.INT_MODE);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.PC_RATE);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.TOT_I_AM);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.PC_AMT);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.TOT_AMT);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.HRG_AMT);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.SYN_FLG);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.EE_TERM);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.CHK_NO);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.CLN_CUT);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.TR_MMO);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.MLT_STL);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.CLN_CUT);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.PART_INF[1-1].JOIN_BR);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.PART_INF[2-1].JOIN_BR);
        if (LNB4100_AWA_4100.CTA_NO.trim().length() == 0) {
            WS_ERR_MSG = LNCMSG_ERROR_MSG.LN_LN_AC_NOT_INPUT;
            WS_FLD_NO = LNB4100_AWA_4100.CTA_NO_NO;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        if (LNB4100_AWA_4100.TR_VAL_D == 0) {
            WS_ERR_MSG = LNCMSG_ERROR_MSG.LN_PAY_P_TOT_ZERO;
            WS_FLD_NO = LNB4100_AWA_4100.TR_VAL_D_NO;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        CEP.TRC(SCCGWA, " ");
        WS_INT_MODE_FLAG = LNB4100_AWA_4100.INT_MODE;
        if ((WS_INT_MODE_FLAG != '0' 
            && WS_INT_MODE_FLAG != '1' 
            && WS_INT_MODE_FLAG != '2')) {
            WS_ERR_MSG = LNCMSG_ERROR_MSG.LN_ERR_MUST_INPUT;
            S000_ERR_MSG_PROC();
        }
        CEP.TRC(SCCGWA, " ");
        if (LNB4100_AWA_4100.SYN_FLG != ' ') {
            WS_SYN_FLG_FLAG = LNB4100_AWA_4100.SYN_FLG;
            if ((WS_SYN_FLG_FLAG != '1' 
                && WS_SYN_FLG_FLAG != '2' 
                && WS_SYN_FLG_FLAG != '3')) {
                WS_ERR_MSG = LNCMSG_ERROR_MSG.LN_ERR_MUST_INPUT;
                S000_ERR_MSG_PROC();
            }
            CEP.TRC(SCCGWA, " ");
            if (LNB4100_AWA_4100.SYN_FLG == '3' 
                && LNB4100_AWA_4100.EE_TERM.compareTo(0) <= 0) {
                WS_ERR_MSG = LNCMSG_ERROR_MSG.ERR_LN_TERM;
                S000_ERR_MSG_PROC();
            }
        }
        if (LNB4100_AWA_4100.CLN_CUT != ' ' 
            && LNB4100_AWA_4100.CLN_CUT != '0' 
            && LNB4100_AWA_4100.CLN_CUT != '1' 
            && LNB4100_AWA_4100.CLN_CUT != '2' 
            && LNB4100_AWA_4100.CLN_CUT != '3' 
            && LNB4100_AWA_4100.CLN_CUT != '9') {
            WS_ERR_MSG = LNCMSG_ERROR_MSG.LN_ERR_MUST_INPUT;
            S000_ERR_MSG_PROC();
        }
        CEP.TRC(SCCGWA, " ");
        WS_FEE_FLG = 'N';
        for (WS_I = 1; WS_I <= 5; WS_I += 1) {
            CEP.TRC(SCCGWA, LNB4100_AWA_4100.FEE_INF[WS_I-1].FEE_CODE);
            CEP.TRC(SCCGWA, LNB4100_AWA_4100.FEE_INF[WS_I-1].FEE_AMT);
            if (LNB4100_AWA_4100.FEE_INF[WS_I-1].FEE_CODE.trim().length() > 0 
                && LNB4100_AWA_4100.FEE_INF[WS_I-1].FEE_AMT == 0) {
                WS_ERR_MSG = LNCMSG_ERROR_MSG.LN_ERR_MUST_INPUT;
                S000_ERR_MSG_PROC();
            }
            if (LNB4100_AWA_4100.FEE_INF[WS_I-1].FEE_CODE.trim().length() > 0) {
                WS_FEE_FLG = 'Y';
            }
        }
        CEP.TRC(SCCGWA, " ");
        if (WS_FEE_FLG == 'Y' 
            && (!LNB4100_AWA_4100.FEE_ACT.equalsIgnoreCase("01") 
            && !LNB4100_AWA_4100.FEE_ACT.equalsIgnoreCase("02") 
            && !LNB4100_AWA_4100.FEE_ACT.equalsIgnoreCase("03") 
            && !LNB4100_AWA_4100.FEE_ACT.equalsIgnoreCase("04") 
            && !LNB4100_AWA_4100.FEE_ACT.equalsIgnoreCase("05") 
            && !LNB4100_AWA_4100.FEE_ACT.equalsIgnoreCase("06") 
            && !LNB4100_AWA_4100.FEE_ACT.equalsIgnoreCase("07"))) {
            WS_ERR_MSG = LNCMSG_ERROR_MSG.LN_ERR_MUST_INPUT;
            S000_ERR_MSG_PROC();
        }
        CEP.TRC(SCCGWA, "扣费账户类型");
        if (WS_FEE_FLG == 'Y' 
            && LNB4100_AWA_4100.FEE_AC.trim().length() == 0) {
            WS_ERR_MSG = LNCMSG_ERROR_MSG.LN_ERR_FEEAC_NEED;
            S000_ERR_MSG_PROC();
        }
        CEP.TRC(SCCGWA, " ");
        CEP.TRC(SCCGWA, "111");
        WS_AMT = LNB4100_AWA_4100.MULT_AC[1-1].PAY_AMT + LNB4100_AWA_4100.MULT_AC[2-1].PAY_AMT + LNB4100_AWA_4100.MULT_AC[3-1].PAY_AMT + LNB4100_AWA_4100.MULT_AC[4-1].PAY_AMT + LNB4100_AWA_4100.MULT_AC[5-1].PAY_AMT;
        if (WS_AMT > LNB4100_AWA_4100.TOT_AMT) {
            CEP.ERR(SCCGWA, LNCMSG_ERROR_MSG.LN_LESS_AMT);
        }
        CEP.TRC(SCCGWA, "WS-AMT");
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.MULT_AC[1-1].PAY_AMT);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.MULT_AC[2-1].PAY_AMT);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.MULT_AC[3-1].PAY_AMT);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.MULT_AC[4-1].PAY_AMT);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.MULT_AC[5-1].PAY_AMT);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.TOT_AMT);
    }
    public void B020_EARLY_PAY_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCSERRP);
        LNCSERRP.CTA = LNB4100_AWA_4100.CTA_NO;
        LNCSERRP.TR_VAL_DTE = LNB4100_AWA_4100.TR_VAL_D;
        LNCSERRP.TOT_P_AMT = LNB4100_AWA_4100.TOT_P_AM;
        LNCSERRP.INT_MODE = LNB4100_AWA_4100.INT_MODE;
        LNCSERRP.PC_RATE = LNB4100_AWA_4100.PC_RATE;
        LNCSERRP.TOT_I_AMT = LNB4100_AWA_4100.TOT_I_AM;
        LNCSERRP.PC_AMT = LNB4100_AWA_4100.PC_AMT;
        LNCSERRP.TOT_AMT = LNB4100_AWA_4100.TOT_AMT;
        CEP.TRC(SCCGWA, LNCSERRP.TOT_AMT);
        LNCSERRP.HRG_AMT = LNB4100_AWA_4100.HRG_AMT;
        LNCSERRP.SYN_FLG = LNB4100_AWA_4100.SYN_FLG;
        if (LNB4100_AWA_4100.EE_TERM.trim().length() == 0) LNCSERRP.S_TERM = 0;
        else LNCSERRP.S_TERM = Short.parseShort(LNB4100_AWA_4100.EE_TERM);
        LNCSERRP.RAT_MTH = LNB4100_AWA_4100.RAT_MTH;
        LNCSERRP.INT_F_UN = LNB4100_AWA_4100.INT_F_UN;
        LNCSERRP.INT_F_PD = LNB4100_AWA_4100.INT_F_PD;
        LNCSERRP.FLT_IPER = LNB4100_AWA_4100.FLT_IPER;
        LNCSERRP.FLT_ADJF = LNB4100_AWA_4100.FLT_ADJF;
        LNCSERRP.FT_FLG = LNB4100_AWA_4100.FT_FLG;
        LNCSERRP.FT_DAY = LNB4100_AWA_4100.FT_DAY;
        LNCSERRP.FT_F_DAY = LNB4100_AWA_4100.FT_F_DAY;
        LNCSERRP.FLT_MTH = LNB4100_AWA_4100.FT_MTH;
        LNCSERRP.RATE_TYP = LNB4100_AWA_4100.RATE_TYP;
        LNCSERRP.RATE_PD = LNB4100_AWA_4100.RATE_PD;
        LNCSERRP.RATE_VAR = LNB4100_AWA_4100.RATE_VAR;
        LNCSERRP.RATE_PCT = LNB4100_AWA_4100.RATE_PCT;
        LNCSERRP.RATE_INT = LNB4100_AWA_4100.RATE_INT;
        LNCSERRP.INT_RATE = LNB4100_AWA_4100.INT_RATE;
        LNCSERRP.PEN_RRAT = LNB4100_AWA_4100.PEN_RRAT;
        LNCSERRP.PEN_TYP = LNB4100_AWA_4100.PEN_TYP;
        LNCSERRP.PEN_RATT = LNB4100_AWA_4100.PEN_RATT;
        LNCSERRP.PEN_RATC = LNB4100_AWA_4100.PEN_RATC;
        LNCSERRP.PEN_SPR = LNB4100_AWA_4100.PEN_SPR;
        LNCSERRP.PEN_PCT = LNB4100_AWA_4100.PEN_PCT;
        LNCSERRP.PEN_IRAT = LNB4100_AWA_4100.PEN_IRAT;
        LNCSERRP.INT_MTH = LNB4100_AWA_4100.INT_MTH;
        LNCSERRP.CPND_USE = LNB4100_AWA_4100.CPND_USE;
        LNCSERRP.CPND_RTY = LNB4100_AWA_4100.CPND_RTY;
        LNCSERRP.CPND_TYP = LNB4100_AWA_4100.CPND_TYP;
        LNCSERRP.CPNDRATT = LNB4100_AWA_4100.CPNDRATT;
        LNCSERRP.CPNDRATC = LNB4100_AWA_4100.CPNDRATC;
        LNCSERRP.CPND_SPR = LNB4100_AWA_4100.CPND_SPR;
        LNCSERRP.CPND_PCT = LNB4100_AWA_4100.CPND_PCT;
        LNCSERRP.CPNDRATE = LNB4100_AWA_4100.CPNDRATE;
        LNCSERRP.ABUS_RAT = LNB4100_AWA_4100.ABUS_RAT;
        LNCSERRP.ABUS_TYP = LNB4100_AWA_4100.ABUS_TYP;
        LNCSERRP.ABUSRATT = LNB4100_AWA_4100.ABUSRATT;
        LNCSERRP.ABUSRATC = LNB4100_AWA_4100.ABUSRATC;
        LNCSERRP.ABUSSPR = LNB4100_AWA_4100.ABUSSPR;
        LNCSERRP.ABUSPCT = LNB4100_AWA_4100.ABUSPCT;
        LNCSERRP.ABUSIRAT = LNB4100_AWA_4100.ABUSIRAT;
        LNCSERRP.RPSP_NO = LNB4100_AWA_4100.CHK_NO;
        LNCSERRP.METH = LNB4100_AWA_4100.CLN_CUT;
        if (SCCGWA.COMM_AREA.BSP_FLG.equalsIgnoreCase("BSP") 
            || SCCGWA.COMM_AREA.CHNL.equalsIgnoreCase("BAT")) {
            LNCSERRP.TR_MMO = "12010003";
        } else {
            LNCSERRP.TR_MMO = "12010002";
        }
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.MLT_STL);
        LNCSERRP.MLT_STL = LNB4100_AWA_4100.MLT_STL;
        for (WS_K = 1; WS_K <= 5; WS_K += 1) {
            LNCSERRP.ACAMT[WS_K-1].STL_MTH2 = LNB4100_AWA_4100.MULT_AC[WS_K-1].STL_MTH;
            LNCSERRP.ACAMT[WS_K-1].CHQ_NO2 = LNB4100_AWA_4100.MULT_AC[WS_K-1].CHQ_NO;
            LNCSERRP.ACAMT[WS_K-1].PAY_PSWD = LNB4100_AWA_4100.MULT_AC[WS_K-1].PAY_PSWD;
            LNCSERRP.ACAMT[WS_K-1].CHQ_TYPE = LNB4100_AWA_4100.MULT_AC[WS_K-1].CHQ_TYPE;
            LNCSERRP.ACAMT[WS_K-1].ISS_DATE = LNB4100_AWA_4100.MULT_AC[WS_K-1].ISS_DATE;
            LNCSERRP.ACAMT[WS_K-1].DEP_AC2 = LNB4100_AWA_4100.MULT_AC[WS_K-1].DEP_AC;
            LNCSERRP.ACAMT[WS_K-1].CCY_TYP = LNB4100_AWA_4100.MULT_AC[WS_K-1].CCY_TYP;
            LNCSERRP.ACAMT[WS_K-1].AC_FLG2 = LNB4100_AWA_4100.MULT_AC[WS_K-1].AC_FLG;
            LNCSERRP.ACAMT[WS_K-1].CI_CNM2 = LNB4100_AWA_4100.MULT_AC[WS_K-1].AC_CNM;
            LNCSERRP.ACAMT[WS_K-1].PAY_AMT2 = LNB4100_AWA_4100.MULT_AC[WS_K-1].PAY_AMT;
            LNCSERRP.ACAMT[WS_K-1].RVS_NO2 = LNB4100_AWA_4100.MULT_AC[WS_K-1].RVS_NO;
            LNCSERRP.ACAMT[WS_K-1].REC_CCY2 = LNB4100_AWA_4100.CCY;
            LNCSERRP.ACAMT[WS_K-1].AMT_FRM2 = LNB4100_AWA_4100.MULT_AC[WS_K-1].AMT_FRM;
            LNCSERRP.FEE_INFO[WS_K-1].FEE_CD = LNB4100_AWA_4100.FEE_INF[WS_K-1].FEE_CODE;
            CEP.TRC(SCCGWA, LNCSERRP.FEE_INFO[WS_K-1].FEE_CD);
            LNCSERRP.FEE_INFO[WS_K-1].FEE_AMT = LNB4100_AWA_4100.FEE_INF[WS_K-1].FEE_AMT;
        }
        LNCSERRP.FEE_TYP = LNB4100_AWA_4100.FEE_ACT;
        LNCSERRP.FEE_AC = LNB4100_AWA_4100.FEE_AC;
        LNCSERRP.FEE_TYPC = LNB4100_AWA_4100.FEE_TYP;
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.FEE_ACT);
        CEP.TRC(SCCGWA, LNB4100_AWA_4100.FEE_AC);
        CEP.TRC(SCCGWA, LNCSERRP.FEE_AC);
        CEP.TRC(SCCGWA, LNCSERRP.FEE_TYP);
        CEP.TRC(SCCGWA, LNCSERRP.FEE_AC);
        for (WS_K = 1; WS_K <= 10; WS_K += 1) {
            LNCSERRP.SYLOAN_INFO[WS_K-1].SYLOAN_SEQ = "" + LNB4100_AWA_4100.PART_INF[WS_K-1].JOIN_NO;
            JIBS_tmp_int = LNCSERRP.SYLOAN_INFO[WS_K-1].SYLOAN_SEQ.length();
            for (int i=0;i<8-JIBS_tmp_int;i++) LNCSERRP.SYLOAN_INFO[WS_K-1].SYLOAN_SEQ = "0" + LNCSERRP.SYLOAN_INFO[WS_K-1].SYLOAN_SEQ;
            LNCSERRP.SYLOAN_INFO[WS_K-1].SYLOAN_BR = LNB4100_AWA_4100.PART_INF[WS_K-1].JOIN_BR;
            LNCSERRP.SYLOAN_INFO[WS_K-1].SYLOAN_NAME = LNB4100_AWA_4100.PART_INF[WS_K-1].JOIN_NM;
            LNCSERRP.SYLOAN_INFO[WS_K-1].SYLOAN_FLG = LNB4100_AWA_4100.PART_INF[WS_K-1].I_O_FLG;
            LNCSERRP.SYLOAN_INFO[WS_K-1].SYLOAN_TYP = LNB4100_AWA_4100.PART_INF[WS_K-1].RLA_TYP;
            LNCSERRP.SYLOAN_INFO[WS_K-1].SYLOAN_P = LNB4100_AWA_4100.PART_INF[WS_K-1].PY_P_AMT;
            LNCSERRP.SYLOAN_INFO[WS_K-1].SYLOAN_I = LNB4100_AWA_4100.PART_INF[WS_K-1].PY_I_AMT;
            LNCSERRP.SYLOAN_INFO[WS_K-1].SYLOAN_W = LNB4100_AWA_4100.PART_INF[WS_K-1].PY_PC_AT;
        }
        S000_CALL_LNZSERRP();
    }
    public void B030_UPDATE_WAIWEI_INFO() throws IOException,SQLException,Exception {
        if (LNCSERRP.TOT_P_AMT > 0 
            && !SCCGWA.COMM_AREA.BSP_FLG.equalsIgnoreCase("BSP") 
            && !SCCGWA.COMM_AREA.CHNL.equalsIgnoreCase("BAT")) {
            IBS.init(SCCGWA, LNRAGRE);
            LNRAGRE.KEY.CONTRACT_NO = LNB4100_AWA_4100.CTA_NO;
            LNRAPRD.KEY.CONTRACT_NO = LNB4100_AWA_4100.CTA_NO;
            LNRICTL.KEY.CONTRACT_NO = LNB4100_AWA_4100.CTA_NO;
            T000_READ_LNTAGRE();
            T000_READ_LNTAPRD();
            T000_READ_LNTICTL();
            IBS.init(SCCGWA, SCCTPCL);
            SCCTPCL.SERV_AREA.OBJ_SYSTEM = "ESBP";
            SCCTPCL.SERV_AREA.SERV_CODE = "3002200000902";
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_SEQ = "" + SCCGWA.COMM_AREA.JRN_NO;
            JIBS_tmp_int = SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_SEQ.length();
            for (int i=0;i<12-JIBS_tmp_int;i++) SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_SEQ = "0" + SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_SEQ;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_CTRNO = LNRAGRE.PAPER_NO;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_DBLNO = LNRAGRE.DRAW_NO;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_CCY = LNB4100_AWA_4100.CCY;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_AMT = LNB4100_AWA_4100.TOT_P_AM;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_CHNL = SCCGWA.COMM_AREA.REQ_SYSTEM;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_TYP = LNB4100_AWA_4100.PROD_CD;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_INT = 999;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            if (LNRAPRD.PAY_MTH == '1') {
                SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_PAYTYP = "RPT-03";
                SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            } else if (LNRAPRD.PAY_MTH == '2') {
                SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_PAYTYP = "RPT-04";
                SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            } else if (LNRAPRD.PAY_MTH == '4') {
                SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_PAYTYP = "RPT-01";
                SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            }
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_CYCLE = 0;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_FAMT1 = 0;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_FAMT2 = 0;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_YRATE = LNRICTL.CUR_RAT;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_PAYDT = SCCGWA.COMM_AREA.AC_DATE;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_AC = LNCSERRP.ACAMT[1-1].RVS_NO2;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            IBS.init(SCCGWA, CICQACRI);
            CICQACRI.DATA.AGR_NO = LNRAGRE.PAPER_NO;
            CEP.TRC(SCCGWA, LNCSERRP.ACAMT[1-1].RVS_NO2);
            CEP.TRC(SCCGWA, CICQACRI.DATA.AGR_NO);
            CICQACRI.FUNC = 'A';
            S000_CALL_CIZQACRI();
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_ACNM = CICQACRI.O_DATA.O_AC_CNM;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_BKNM = "" + CICQACRI.O_DATA.O_OWNER_BK;
            JIBS_tmp_int = SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_BKNM.length();
            for (int i=0;i<6-JIBS_tmp_int;i++) SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_BKNM = "0" + SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_BKNM;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_BK = CICQACRI.O_DATA.O_OWNER_BK;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            IBS.init(SCCGWA, CICCUST);
            CICCUST.FUNC = 'A';
            CICCUST.DATA.AGR_NO = LNRAGRE.PAPER_NO;
            S000_CALL_CIZCUST();
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_CUSTNM = CICCUST.O_DATA.O_CI_NM;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_IDTYP = CICCUST.O_DATA.O_ID_TYPE;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.INP_AREA.BD_PAYB_NOTICE.PAYB_ID = CICCUST.O_DATA.O_ID_NO;
            SCCTPCL.INP_AREA.SERV_DATA = IBS.CLS2CPY(SCCGWA, SCCTPCL.INP_AREA.BD_PAYB_NOTICE);
            SCCTPCL.SERV_AREA.SERV_TYPE = 'N';
            SCCTPCL.INP_AREA.SERV_DATA_LEN = 1079;
            S000_CALL_SCZTPCL();
        }
    }
    public void R000_SEND_MESSAGE() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, SCCWRMSG);
        SCCWRMSG.DATE = SCCGWA.COMM_AREA.AC_DATE;
        SCCWRMSG.JRNNO = "" + SCCGWA.COMM_AREA.JRN_NO;
        JIBS_tmp_int = SCCWRMSG.JRNNO.length();
        for (int i=0;i<12-JIBS_tmp_int;i++) SCCWRMSG.JRNNO = "0" + SCCWRMSG.JRNNO;
        SCCWRMSG.AP_CODE = "28";
        SCCWRMSG.CI_NO = LNB4100_AWA_4100.CI_NO;
        SCCWRMSG.AC = LNB4100_AWA_4100.CTA_NO;
        R000_CALL_SCZWRMSG();
    }
    public void S000_CALL_LNZSERRP() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-SVR-EARLY-REPAY", LNCSERRP);
        if (LNCSERRP.RC.RC_RTNCODE != 0) {
            WS_ERR_MSG = IBS.CLS2CPY(SCCGWA, LNCSERRP.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void T000_READ_LNTAGRE() throws IOException,SQLException,Exception {
        LNTAGRE_RD = new DBParm();
        LNTAGRE_RD.TableName = "LNTAGRE";
        LNTAGRE_RD.where = "CONTRACT_NO = :LNRAGRE.KEY.CONTRACT_NO";
        IBS.READ(SCCGWA, LNRAGRE, this, LNTAGRE_RD);
    }
    public void T000_READ_LNTAPRD() throws IOException,SQLException,Exception {
        LNTAPRD_RD = new DBParm();
        LNTAPRD_RD.TableName = "LNTAPRD";
        LNTAPRD_RD.where = "CONTRACT_NO = :LNRAPRD.KEY.CONTRACT_NO";
        IBS.READ(SCCGWA, LNRAPRD, this, LNTAPRD_RD);
    }
    public void T000_READ_LNTICTL() throws IOException,SQLException,Exception {
        LNTICTL_RD = new DBParm();
        LNTICTL_RD.TableName = "LNTICTL";
        IBS.READ(SCCGWA, LNRICTL, LNTICTL_RD);
    }
    public void S000_CALL_SCZTPCL() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "SC-LINK-EXTSERV", SCCTPCL);
    }
    public void S000_CALL_CIZCUST() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "CI-INQ-CUST", CICCUST, true);
        CEP.TRC(SCCGWA, CICQACRI.RC.RC_CODE);
        if (CICCUST.RC.RC_CODE != 0) {
            CEP.ERR(SCCGWA, CICCUST.RC);
        }
    }
    public void S000_CALL_CIZQACRI() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "CI-INQ-ACR-INF", CICQACRI);
        CEP.TRC(SCCGWA, CICQACRI.RC.RC_CODE);
        if (CICQACRI.RC.RC_CODE != 0) {
            CEP.ERR(SCCGWA, CICQACRI.RC);
        }
    }
    public void R000_CALL_SCZWRMSG() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "SC-SCZWRMSG-MMSG", SCCWRMSG, true);
    }
    public void S000_ERR_MSG_PROC_CONTINUE() throws IOException,SQLException,Exception {
        CEP.ERRC(SCCGWA, WS_ERR_MSG, WS_FLD_NO);
    }
    public void S000_ERR_MSG_PROC_LAST() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG);
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
