package com.hisun.LN;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;

import java.io.IOException;
import java.sql.SQLException;

public class LNOT4061 {
    String WS_ERR_MSG = " ";
    short WS_FLD_NO = 0;
    LNCMSG_ERROR_MSG LNCMSG_ERROR_MSG = new LNCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCFMT SCCFMT = new SCCFMT();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    LNCSINTA LNCSINTA = new LNCSINTA();
    LNCP60 LNCP60 = new LNCP60();
    SCCGWA SCCGWA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    LNB4060_AWA_4060 LNB4060_AWA_4060;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "LNOT4061 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "LNB4060_AWA_4060>");
        LNB4060_AWA_4060 = (LNB4060_AWA_4060) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B010_CHECK_INPUT();
        B020_BROWSE_BAS_INFO();
        B030_OUTPUT_PROCESS();
    }
    public void B010_CHECK_INPUT() throws IOException,SQLException,Exception {
    }
    public void B020_BROWSE_BAS_INFO() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, LNB4060_AWA_4060.FUNC);
        CEP.TRC(SCCGWA, LNB4060_AWA_4060.CTA_NO);
        CEP.TRC(SCCGWA, LNB4060_AWA_4060.CI_NO);
        CEP.TRC(SCCGWA, LNB4060_AWA_4060.CI_ENMS);
        CEP.TRC(SCCGWA, LNB4060_AWA_4060.CI_CNM);
        CEP.TRC(SCCGWA, LNB4060_AWA_4060.PRIN);
        CEP.TRC(SCCGWA, LNB4060_AWA_4060.OSBAL);
        CEP.TRC(SCCGWA, LNB4060_AWA_4060.CCY);
        CEP.TRC(SCCGWA, LNB4060_AWA_4060.STS);
        CEP.TRC(SCCGWA, LNB4060_AWA_4060.PAY_TYP);
        CEP.TRC(SCCGWA, LNB4060_AWA_4060.PAY_TERM);
        CEP.TRC(SCCGWA, LNB4060_AWA_4060.VAL_DT);
        CEP.TRC(SCCGWA, LNB4060_AWA_4060.DUE_DT);
        CEP.TRC(SCCGWA, LNB4060_AWA_4060.INT);
        CEP.TRC(SCCGWA, LNB4060_AWA_4060.ADJ_AMT);
        CEP.TRC(SCCGWA, LNB4060_AWA_4060.ADJ_AMTS);
        CEP.TRC(SCCGWA, LNB4060_AWA_4060.RSN);
        IBS.init(SCCGWA, LNCSINTA);
        LNCSINTA.FUNC = LNB4060_AWA_4060.FUNC;
        LNCSINTA.CTA_NO = LNB4060_AWA_4060.CTA_NO;
        LNCSINTA.PAY_TYP = LNB4060_AWA_4060.PAY_TYP;
        LNCSINTA.PAY_TERM = LNB4060_AWA_4060.PAY_TERM;
        LNCSINTA.CI_NO = LNB4060_AWA_4060.CI_NO;
        LNCSINTA.CI_ENMS = LNB4060_AWA_4060.CI_ENMS;
        LNCSINTA.CITY_CD = LNB4060_AWA_4060.CITY_CD;
        LNCSINTA.CI_ENM = LNB4060_AWA_4060.CI_ENM;
        LNCSINTA.PRIN = LNB4060_AWA_4060.PRIN;
        LNCSINTA.OSBAL = LNB4060_AWA_4060.OSBAL;
        LNCSINTA.CCY = LNB4060_AWA_4060.CCY;
        LNCSINTA.STS = LNB4060_AWA_4060.STS;
        if (LNB4060_AWA_4060.VAL_DT == 0 
            && LNB4060_AWA_4060.PAY_TERM == 0) {
            LNCSINTA.VAL_DT = SCCGWA.COMM_AREA.AC_DATE;
            CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.AC_DATE);
        }
        S000_CALL_LNZSINTA();
    }
    public void B030_OUTPUT_PROCESS() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCP60);
        IBS.init(SCCGWA, SCCFMT);
        LNCP60.CTA_NO = LNCSINTA.CTA_NO;
        LNCP60.CI_NO = LNCSINTA.CI_NO;
        LNCP60.CI_ENMS = LNCSINTA.CI_ENMS;
        LNCP60.PRIN = LNCSINTA.PRIN;
        LNCP60.OSBAL = LNCSINTA.OSBAL;
        LNCP60.CCY = LNCSINTA.CCY;
        LNCP60.STS = LNCSINTA.STS;
        CEP.TRC(SCCGWA, "AAAAAAAAAAAA");
        CEP.TRC(SCCGWA, LNB4060_AWA_4060.PAY_TYP);
        CEP.TRC(SCCGWA, LNB4060_AWA_4060.PAY_TERM);
        CEP.TRC(SCCGWA, LNB4060_AWA_4060.VAL_DT);
        CEP.TRC(SCCGWA, LNB4060_AWA_4060.DUE_DT);
        CEP.TRC(SCCGWA, LNB4060_AWA_4060.INT);
        CEP.TRC(SCCGWA, LNB4060_AWA_4060.ADJ_AMT);
        CEP.TRC(SCCGWA, "BBBBBBBBBBBB");
        CEP.TRC(SCCGWA, LNCSINTA.PAY_TYP);
        CEP.TRC(SCCGWA, LNCSINTA.PAY_TERM);
        CEP.TRC(SCCGWA, LNCSINTA.VAL_DT);
        CEP.TRC(SCCGWA, LNCSINTA.DUE_DT);
        CEP.TRC(SCCGWA, LNCSINTA.INT);
        CEP.TRC(SCCGWA, LNCSINTA.ADJ_AMT);
        CEP.TRC(SCCGWA, "BAAAAAAAAAAA");
        CEP.TRC(SCCGWA, "CAAAAAAAAAAA");
        LNCP60.PAY_TYP = LNCSINTA.PAY_TYP;
        LNCP60.PAY_TERM = LNCSINTA.PAY_TERM;
        LNCP60.VAL_DT = LNCSINTA.VAL_DT;
        LNCP60.DUE_DT = LNCSINTA.DUE_DT;
        LNCP60.INT = LNCSINTA.INT;
        LNCP60.ADJ_AMT = LNCSINTA.ADJ_AMT;
        LNCP60.ADJ_AMTS = LNCSINTA.ADJ_AMTS;
        LNCP60.RSN = LNCSINTA.RSN;
        LNCP60.D_PRIN = LNCSINTA.D_PRIN;
        LNCP60.D_INT = LNCSINTA.D_INT;
        CEP.TRC(SCCGWA, LNCP60.CTA_NO);
        CEP.TRC(SCCGWA, LNCP60.CI_NO);
        CEP.TRC(SCCGWA, LNCP60.PRIN);
        CEP.TRC(SCCGWA, LNCP60.OSBAL);
        CEP.TRC(SCCGWA, LNCP60.CCY);
        CEP.TRC(SCCGWA, LNCP60.STS);
        CEP.TRC(SCCGWA, LNCP60.PAY_TYP);
        CEP.TRC(SCCGWA, LNCP60.PAY_TERM);
        CEP.TRC(SCCGWA, LNCP60.VAL_DT);
        CEP.TRC(SCCGWA, LNCP60.DUE_DT);
        CEP.TRC(SCCGWA, LNCP60.INT);
        CEP.TRC(SCCGWA, LNCP60.ADJ_AMT);
        CEP.TRC(SCCGWA, LNCP60.ADJ_AMTS);
        CEP.TRC(SCCGWA, LNCP60.RSN);
        CEP.TRC(SCCGWA, LNCP60.D_PRIN);
        CEP.TRC(SCCGWA, LNCP60.D_INT);
        SCCFMT.FMTID = "LNP61";
        SCCFMT.DATA_PTR = LNCP60;
        SCCFMT.DATA_LEN = 660;
        IBS.FMT(SCCGWA, SCCFMT);
    }
    public void S000_CALL_LNZSINTA() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-SVR-ADJ-INTA", LNCSINTA);
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG, WS_FLD_NO);
    }
    public void S000_ERR_MSG_PROC_CONTINUE() throws IOException,SQLException,Exception {
        CEP.ERRC(SCCGWA, WS_ERR_MSG, WS_FLD_NO);
    }
    public void S000_ERR_MSG_PROC_LAST() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
