package com.hisun.LN;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;

import java.io.IOException;
import java.sql.SQLException;

public class LNOT8160 {
    String WS_ERR_MSG = " ";
    short WS_FLD_NO = 0;
    LNOT8160_WS_OUT_PUT WS_OUT_PUT = new LNOT8160_WS_OUT_PUT();
    LNCMSG_ERROR_MSG LNCMSG_ERROR_MSG = new LNCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCFMT SCCFMT = new SCCFMT();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    LNCSINTA LNCSINTA = new LNCSINTA();
    SCCGWA SCCGWA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    LNB8160_AWA_8160 LNB8160_AWA_8160;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "LNOT8160 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "LNB8160_AWA_8160>");
        LNB8160_AWA_8160 = (LNB8160_AWA_8160) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B010_CHECK_INPUT();
        B020_BROWSE_BAS_INFO();
        B030_OUTPUT_PROCESS();
    }
    public void B010_CHECK_INPUT() throws IOException,SQLException,Exception {
    }
    public void B020_BROWSE_BAS_INFO() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, LNB8160_AWA_8160.FUNC);
        CEP.TRC(SCCGWA, LNB8160_AWA_8160.CTA_NO);
        CEP.TRC(SCCGWA, LNB8160_AWA_8160.CI_NO);
        CEP.TRC(SCCGWA, LNB8160_AWA_8160.CI_ENMS);
        CEP.TRC(SCCGWA, LNB8160_AWA_8160.CI_CNM);
        CEP.TRC(SCCGWA, LNB8160_AWA_8160.PRIN);
        CEP.TRC(SCCGWA, LNB8160_AWA_8160.OSBAL);
        CEP.TRC(SCCGWA, LNB8160_AWA_8160.CCY);
        CEP.TRC(SCCGWA, LNB8160_AWA_8160.STS);
        CEP.TRC(SCCGWA, LNB8160_AWA_8160.ADJ_PTYP);
        CEP.TRC(SCCGWA, LNB8160_AWA_8160.ADJ_PTEM);
        CEP.TRC(SCCGWA, LNB8160_AWA_8160.ADJ_VDT);
        CEP.TRC(SCCGWA, LNB8160_AWA_8160.ADJ_DDT);
        CEP.TRC(SCCGWA, LNB8160_AWA_8160.ADJ_INT);
        CEP.TRC(SCCGWA, LNB8160_AWA_8160.ADJ_AMT);
        CEP.TRC(SCCGWA, LNB8160_AWA_8160.ADJ_AMTS);
        CEP.TRC(SCCGWA, LNB8160_AWA_8160.ADJ_RSN);
        IBS.init(SCCGWA, LNCSINTA);
        LNCSINTA.FUNC = LNB8160_AWA_8160.FUNC;
        LNCSINTA.CTA_NO = LNB8160_AWA_8160.CTA_NO;
        LNCSINTA.PAY_TYP = LNB8160_AWA_8160.ADJ_PTYP;
        LNCSINTA.PAY_TERM = LNB8160_AWA_8160.ADJ_PTEM;
        LNCSINTA.CI_NO = LNB8160_AWA_8160.CI_NO;
        LNCSINTA.CI_ENMS = LNB8160_AWA_8160.CI_ENMS;
        LNCSINTA.CITY_CD = LNB8160_AWA_8160.CITY_CD;
        LNCSINTA.CI_ENM = LNB8160_AWA_8160.CI_ENM;
        LNCSINTA.PRIN = LNB8160_AWA_8160.PRIN;
        LNCSINTA.OSBAL = LNB8160_AWA_8160.OSBAL;
        LNCSINTA.CCY = LNB8160_AWA_8160.CCY;
        LNCSINTA.STS = LNB8160_AWA_8160.STS;
        if (LNB8160_AWA_8160.ADJ_VDT == 0 
            && LNB8160_AWA_8160.ADJ_PTEM == 0) {
            LNCSINTA.VAL_DT = SCCGWA.COMM_AREA.AC_DATE;
            CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.AC_DATE);
        }
        S000_CALL_LNZSINTA();
    }
    public void B030_OUTPUT_PROCESS() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, SCCFMT);
        WS_OUT_PUT.WS_CTA_NO = LNCSINTA.CTA_NO;
        WS_OUT_PUT.WS_CI_NO = LNCSINTA.CI_NO;
        WS_OUT_PUT.WS_CI_ENMS = LNCSINTA.CI_ENMS;
        WS_OUT_PUT.WS_PRIN = LNCSINTA.PRIN;
        WS_OUT_PUT.WS_OSBAL = LNCSINTA.OSBAL;
        WS_OUT_PUT.WS_CCY = LNCSINTA.CCY;
        WS_OUT_PUT.WS_STS = LNCSINTA.STS;
        CEP.TRC(SCCGWA, "AAAAAAAAAAAA");
        CEP.TRC(SCCGWA, LNB8160_AWA_8160.ADJ_PTYP);
        CEP.TRC(SCCGWA, LNB8160_AWA_8160.ADJ_PTEM);
        CEP.TRC(SCCGWA, LNB8160_AWA_8160.ADJ_VDT);
        CEP.TRC(SCCGWA, LNB8160_AWA_8160.ADJ_DDT);
        CEP.TRC(SCCGWA, LNB8160_AWA_8160.ADJ_INT);
        CEP.TRC(SCCGWA, LNB8160_AWA_8160.ADJ_AMT);
        CEP.TRC(SCCGWA, "BBBBBBBBBBBB");
        CEP.TRC(SCCGWA, LNCSINTA.PAY_TYP);
        CEP.TRC(SCCGWA, LNCSINTA.PAY_TERM);
        CEP.TRC(SCCGWA, LNCSINTA.VAL_DT);
        CEP.TRC(SCCGWA, LNCSINTA.DUE_DT);
        CEP.TRC(SCCGWA, LNCSINTA.INT);
        CEP.TRC(SCCGWA, LNCSINTA.ADJ_AMT);
        CEP.TRC(SCCGWA, "BAAAAAAAAAAA");
        CEP.TRC(SCCGWA, "CAAAAAAAAAAA");
        WS_OUT_PUT.WS_ADJ_PTYP = LNCSINTA.PAY_TYP;
        WS_OUT_PUT.WS_ADJ_PTEM = LNCSINTA.PAY_TERM;
        WS_OUT_PUT.WS_ADJ_VDT = LNCSINTA.VAL_DT;
        WS_OUT_PUT.WS_ADJ_DDT = LNCSINTA.DUE_DT;
        WS_OUT_PUT.WS_ADJ_INT = LNCSINTA.INT;
        WS_OUT_PUT.WS_ADJ_AMT = LNCSINTA.ADJ_AMT;
        WS_OUT_PUT.WS_ADJ_AMTS = LNCSINTA.ADJ_AMTS;
        WS_OUT_PUT.WS_ADJ_RSN = LNCSINTA.RSN;
        SCCFMT.FMTID = "LN816";
        SCCFMT.DATA_PTR = WS_OUT_PUT;
        SCCFMT.DATA_LEN = 558;
        CEP.TRC(SCCGWA, SCCFMT.DATA_LEN);
        IBS.FMT(SCCGWA, SCCFMT);
    }
    public void S000_CALL_LNZSINTA() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-SVR-ADJ-INTA", LNCSINTA);
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG, WS_FLD_NO);
    }
    public void S000_ERR_MSG_PROC_CONTINUE() throws IOException,SQLException,Exception {
        CEP.ERRC(SCCGWA, WS_ERR_MSG, WS_FLD_NO);
    }
    public void S000_ERR_MSG_PROC_LAST() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
