package com.hisun.LN;

import com.hisun.SC.*;
import com.hisun.BP.*;
import com.hisun.CI.*;

import java.io.IOException;
import java.sql.SQLException;

public class LNOT2171 {
    String JIBS_tmp_str[] = new String[10];
    DBParm LNTAGRE_RD;
    char K_NORMAL_CONT = '0';
    String K_OUTPUT_FMT_2171 = "LNC11";
    LNOT2171_WS_TEMP_VARIABLE WS_TEMP_VARIABLE = new LNOT2171_WS_TEMP_VARIABLE();
    String WS_TEMP_CMMT_NO = " ";
    char WS_CI_TYP = ' ';
    char WS_PRODC_MOD = ' ';
    char WS_CAP_FROM = ' ';
    short WS_CNT = 0;
    LNCMSG_ERROR_MSG LNCMSG_ERROR_MSG = new LNCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    SCCMPAG SCCMPAG = new SCCMPAG();
    SCCFMT SCCFMT = new SCCFMT();
    LNCPPMQ LNCPPMQ = new LNCPPMQ();
    LNRAGRE LNRAGRE = new LNRAGRE();
    LNCIGECR LNCIGECR = new LNCIGECR();
    BPCPFHIS BPCPFHIS = new BPCPFHIS();
    CICACCU CICACCU = new CICACCU();
    LNCSPADD LNCSPADD = new LNCSPADD();
    SCCGWA SCCGWA;
    LNCI2171 LNCAWA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    SCCGAPV SCCGAPV;
    SCCGMSG SCCGMSG;
    BPCPQBNK_DATA_INFO BPCRBANK;
    public void MP(SCCGWA SCCGWA, LNCI2171 LNCAWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        this.LNCAWA = LNCAWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROCESS();
        B000_MAIN_PROCESS();
        CEP.TRC(SCCGWA, "LNOT2171 return!");
        Z_RET();
    }
    public void A000_INIT_PROCESS() throws IOException,SQLException,Exception {
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        LNCAWA = new LNCI2171();
        IBS.init(SCCGWA, LNCAWA);
        IBS.CPY2CLS(SCCGWA, GWA_SC_AREA.INP_OUTP_AREA.INP_AREA_PTR, LNCAWA);
    }
    public void B000_MAIN_PROCESS() throws IOException,SQLException,Exception {
        if (SCCGWA.COMM_AREA.CANCEL_IND == 'Y') {
            B200_LNZSPADD_PROCESS();
            if (LNCAWA.START_DT <= SCCGWA.COMM_AREA.AC_DATE) {
                B300_FINANCE_HIS();
            }
        } else {
            B000_CHECK_INPUT();
            B100_GET_INITIALIZE_DATA();
            IBS.init(SCCGWA, LNRAGRE);
            LNRAGRE.DRAW_NO = LNCAWA.DRAW_NO;
            T000_READ_AGRE_CONT();
            IBS.init(SCCGWA, LNCIGECR);
            LNCIGECR.INPUT_INFO.CI_NO = LNCAWA.CI_NO;
            LNCIGECR.INPUT_INFO.DRAW_NO = LNCAWA.DRAW_NO;
            LNCIGECR.INPUT_INFO.PAPER_NO = LNCAWA.PAPER_NO;
            LNCIGECR.INPUT_INFO.CTA_FROM = K_NORMAL_CONT;
            S000_CALL_LNZIGECR();
            CEP.TRC(SCCGWA, LNCIGECR.OUTPOUT_INFO.CONTRACT_NO);
            CEP.TRC(SCCGWA, LNCIGECR.OUTPOUT_INFO.CMMT_NO);
            LNCAWA.CONT_NO = LNCIGECR.OUTPOUT_INFO.CONTRACT_NO;
            WS_TEMP_CMMT_NO = LNCIGECR.OUTPOUT_INFO.CMMT_NO;
            CEP.TRC(SCCGWA, WS_TEMP_CMMT_NO);
            B200_LNZSPADD_PROCESS();
            if (LNCAWA.START_DT <= SCCGWA.COMM_AREA.AC_DATE) {
                B300_FINANCE_HIS();
            }
        }
    }
    public void B000_CHECK_INPUT() throws IOException,SQLException,Exception {
        if (LNCAWA.DRAW_NO.trim().length() == 0) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_E_INPUT_PAPER_NO, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (LNCAWA.DOMI_BR == 0) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_BK_BR_M_INPUT, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (LNCAWA.PROD_TYP.trim().length() == 0) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_PRDCD_M_INPUT, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (LNCAWA.START_DT == 0) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_START_DT_M_INPUT, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (LNCAWA.MATU_DT == 0) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_MUST_I_MATU_DT, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (LNCAWA.CCY.trim().length() == 0) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_MUST_I_CTA_CCY, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (LNCAWA.CONT_AMT <= 0) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_CONT_AMT_MUST_INPUT, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (LNCAWA.DRAW_AC.trim().length() == 0) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_DRAW_AC_M_INPUT, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (LNCAWA.SRC_AC.trim().length() == 0) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_SRC_AC_M_INPUT, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (LNCAWA.PAY_AC.trim().length() == 0) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_PAY_AC_M_INPUT, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (LNCAWA.GJPRJNO == ' ') {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_GJ_PRJNO_I, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (LNCAWA.CPND_USE == 'Y' 
            && LNCAWA.PEN_RATT == ' ') {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_PEN_RATT_M_INPUT, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (LNCAWA.CPND_USE == 'Y' 
            && LNCAWA.PEN_IRAT == 0) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_PEN_IRA_M_INPUT, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (LNCAWA.CPND_USE == 'Y' 
            && (LNCAWA.CPNDRATT != ' ' 
            || LNCAWA.CPND_IRA != 0)) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_CPND_INF_CANNOT_I, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
    }
    public void B100_GET_INITIALIZE_DATA() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, LNCAWA.DOMI_BR);
        if (LNCAWA.BOOK_CRE == 0) {
            LNCAWA.BOOK_CRE = LNCAWA.DOMI_BR;
            CEP.TRC(SCCGWA, LNCAWA.DOMI_BR);
        }
        CEP.TRC(SCCGWA, LNCAWA.CI_NO);
        if (LNCAWA.CI_NO.trim().length() == 0) {
            IBS.init(SCCGWA, CICACCU);
            CICACCU.DATA.ENTY_TYP = '1';
            CICACCU.DATA.AGR_NO = LNCAWA.PAY_AC;
            S000_CALL_CIZACCU();
            CEP.TRC(SCCGWA, CICACCU.DATA.CI_NO);
            LNCAWA.CI_NO = CICACCU.DATA.CI_NO;
            WS_CI_TYP = CICACCU.DATA.CI_TYP;
        }
        CEP.TRC(SCCGWA, LNCAWA.DW_BK_TP);
        if (LNCAWA.DW_BK_TP == ' ') {
            LNCAWA.DW_BK_TP = '0';
        }
        CEP.TRC(SCCGWA, LNCAWA.PA_BK_TP);
        if (LNCAWA.PA_BK_TP == ' ') {
            LNCAWA.PA_BK_TP = '0';
        }
        if (LNCAWA.DW_BK_TP == '1') {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_BKTP_INP, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (LNCAWA.PA_BK_TP == '1') {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_BKTP_INP, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        CEP.TRC(SCCGWA, LNCAWA.PROD_TYP);
        CEP.TRC(SCCGWA, LNCAWA.VCH_FLG);
        IBS.init(SCCGWA, LNCPPMQ);
        LNCPPMQ.KEY.REQ_INSTRUCT.REQ_MODULE_PARM = 'N';
        LNCPPMQ.KEY.REQ_INSTRUCT.REQ_COMMIT_PARM = 'N';
        LNCPPMQ.KEY.REQ_INSTRUCT.REQ_CONTRACT_PARM = 'Y';
        LNCPPMQ.KEY.KEY_METH = 'P';
        LNCPPMQ.KEY.KEY_VALUE.LEVEL = 'D';
        LNCPPMQ.KEY.KEY_VALUE.PROD_CD = LNCAWA.PROD_TYP;
        S000_CALL_LNZPPMQ();
        WS_PRODC_MOD = LNCPPMQ.DATA_TXT.PROD_MOD;
        WS_CAP_FROM = LNCPPMQ.DATA_TXT.CAP_FROM;
        CEP.TRC(SCCGWA, WS_CI_TYP);
        CEP.TRC(SCCGWA, WS_PRODC_MOD);
        CEP.TRC(SCCGWA, LNCPPMQ.DATA_TXT.CAP_FROM);
        if (WS_CI_TYP == '1' 
            && WS_PRODC_MOD != 'R') {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_PROD_CI_TYP, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (WS_CI_TYP == '2' 
            && WS_PRODC_MOD != 'C') {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_PROD_CI_TYP, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (WS_CI_TYP == '3' 
            && WS_PRODC_MOD != 'F') {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_PROD_CI_TYP, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (WS_CAP_FROM != '2') {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_CAP_FROM, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        CEP.TRC(SCCGWA, LNCPPMQ.DATA_TXT.PROD_CLS);
        if (!LNCPPMQ.DATA_TXT.PROD_CLS.equalsIgnoreCase("P017")) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_RPOD_NOT_GJJ, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
    }
    public void B200_LNZSPADD_PROCESS() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCSPADD);
        LNCSPADD.COMM_DATA.PAPER_NO = LNCAWA.PAPER_NO;
        LNCSPADD.COMM_DATA.DRAW_NO = LNCAWA.DRAW_NO;
        LNCSPADD.COMM_DATA.CONT_NO = LNCAWA.CONT_NO;
        LNCSPADD.COMM_DATA.BOOK_CRE = LNCAWA.BOOK_CRE;
        LNCSPADD.COMM_DATA.DOMI_BR = LNCAWA.DOMI_BR;
        LNCSPADD.COMM_DATA.CI_NO = LNCAWA.CI_NO;
        LNCSPADD.COMM_DATA.PROD_TYP = LNCAWA.PROD_TYP;
        LNCSPADD.COMM_DATA.VCH_FLG = LNCAWA.VCH_FLG;
        LNCSPADD.COMM_DATA.START_DT = LNCAWA.START_DT;
        LNCSPADD.COMM_DATA.MATU_DT = LNCAWA.MATU_DT;
        LNCSPADD.COMM_DATA.CCY = LNCAWA.CCY;
        LNCSPADD.COMM_DATA.CONT_AMT = LNCAWA.CONT_AMT;
        LNCSPADD.COMM_DATA.REPY_MTH = LNCAWA.REPY_MTH;
        LNCSPADD.COMM_DATA.INST_MTH = LNCAWA.INST_MTH;
        LNCSPADD.COMM_DATA.PAYI_PERD = LNCAWA.PAYI_PER;
        LNCSPADD.COMM_DATA.CAL_PERU = LNCAWA.CAL_PERU;
        LNCSPADD.COMM_DATA.CAL_PERD = LNCAWA.CAL_PERD;
        LNCSPADD.COMM_DATA.PAY_DTYP = LNCAWA.PAY_DTYP;
        LNCSPADD.COMM_DATA.CAL_DAY = LNCAWA.CAL_DAY;
        LNCSPADD.COMM_DATA.CAL_FSDT = LNCAWA.CAL_FSDT;
        LNCSPADD.COMM_DATA.PYP_CIRC = LNCAWA.PYP_CIRC;
        LNCSPADD.COMM_DATA.PYP_PERU = LNCAWA.PYP_PERU;
        LNCSPADD.COMM_DATA.PYP_PERD = LNCAWA.PYP_PERD;
        LNCSPADD.COMM_DATA.DW_BK_TP = LNCAWA.DW_BK_TP;
        LNCSPADD.COMM_DATA.DRAW_ACT = LNCAWA.DRAW_ACT;
        LNCSPADD.COMM_DATA.DRAW_AC = LNCAWA.DRAW_AC;
        LNCSPADD.COMM_DATA.DRAW_SEQ = LNCAWA.DRAW_SEQ;
        LNCSPADD.COMM_DATA.PA_BK_TP = LNCAWA.PA_BK_TP;
        LNCSPADD.COMM_DATA.PAY_AC_T = LNCAWA.PAY_AC_T;
        LNCSPADD.COMM_DATA.PAY_AC = LNCAWA.PAY_AC;
        LNCSPADD.COMM_DATA.SRC_AC = LNCAWA.SRC_AC;
        LNCSPADD.COMM_DATA.GJPRJNO = LNCAWA.GJPRJNO;
        LNCSPADD.COMM_DATA.GUAR_AC = LNCAWA.GUAR_AC;
        LNCSPADD.COMM_DATA.GUAR_AMT = LNCAWA.GUAR_AMT;
        LNCSPADD.COMM_DATA.KFS_AC = LNCAWA.KFS_AC;
        LNCSPADD.COMM_DATA.INT_D_BA = LNCAWA.INT_D_BA;
        LNCSPADD.COMM_DATA.IRAT_TP1 = LNCAWA.IRAT_TP1;
        LNCSPADD.COMM_DATA.IN_RATE = LNCAWA.IN_RATE;
        LNCSPADD.COMM_DATA.PEN_RATT = LNCAWA.PEN_RATT;
        LNCSPADD.COMM_DATA.PEN_IRAT = LNCAWA.PEN_IRAT;
        LNCSPADD.COMM_DATA.CPND_USE = LNCAWA.CPND_USE;
        LNCSPADD.COMM_DATA.CPNDRATT = LNCAWA.CPNDRATT;
        LNCSPADD.COMM_DATA.CPND_IRA = LNCAWA.CPND_IRA;
        LNCSPADD.COMM_DATA.ABUSRATT = LNCAWA.ABUSRATT;
        LNCSPADD.COMM_DATA.ABUSIRAT = LNCAWA.ABUSIRAT;
        LNCSPADD.COMM_DATA.GUAPREF = LNCAWA.GUAPREF;
        LNCSPADD.COMM_DATA.GUARDUAP = LNCAWA.GUARDUAP;
        LNCSPADD.COMM_DATA.GUARPSEQ = LNCAWA.GUARPSEQ;
        LNCSPADD.COMM_DATA.OLC_PERU = LNCAWA.OLC_PERU;
        LNCSPADD.COMM_DATA.OLC_PERD = LNCAWA.OLC_PERD;
        LNCSPADD.COMM_DATA.TR_MMO = LNCAWA.TR_MMO;
        LNCSPADD.COMM_DATA.REMARK1 = LNCAWA.REMARK1;
        for (WS_CNT = 1; WS_CNT <= 5; WS_CNT += 1) {
            LNCSPADD.COMM_DATA.FEE_DATA[WS_CNT-1].FEE_CODE = LNCAWA.FEE_INFO[WS_CNT-1].FEE_CODE;
            LNCSPADD.COMM_DATA.FEE_DATA[WS_CNT-1].FEE_AMT = LNCAWA.FEE_INFO[WS_CNT-1].FEE_AMT;
        }
        LNCSPADD.COMM_DATA.FEE_ACT = LNCAWA.FEE_ACT;
        LNCSPADD.COMM_DATA.FEE_AC = LNCAWA.FEE_AC;
        LNCSPADD.COMM_DATA.YHS_AC = LNCAWA.YHS_AC;
        LNCSPADD.COMM_DATA.YHS_AMT = LNCAWA.YHS_AMT;
        LNCSPADD.COMM_DATA.CUSTM1 = LNCAWA.CUSTM1;
        LNCSPADD.COMM_DATA.CUSTM2 = LNCAWA.CUSTM2;
        LNCSPADD.COMM_DATA.CUSTM3 = LNCAWA.CUSTM3;
        LNCSPADD.COMM_DATA.BAR_CD = LNCAWA.BAR_CD;
        LNCSPADD.COMM_DATA.UNIT_CD = LNCAWA.UNIT_CD;
        S000_CALL_LNZSPADD();
    }
    public void B300_FINANCE_HIS() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCPFHIS);
        BPCPFHIS.DATA.TX_DRCR_FLG = 'D';
        BPCPFHIS.DATA.PRINT_IND = 'Y';
        BPCPFHIS.DATA.JRNNO = SCCGWA.COMM_AREA.JRN_NO;
        BPCPFHIS.DATA.AC_DT = SCCGWA.COMM_AREA.AC_DATE;
        BPCPFHIS.DATA.VCHNO = SCCGWA.COMM_AREA.VCH_NO;
        BPCPFHIS.DATA.REF_NO = LNCAWA.CONT_NO;
        BPCPFHIS.DATA.AC = LNCAWA.PAPER_NO;
        BPCPFHIS.DATA.ACO_AC = LNCAWA.CONT_NO;
        BPCPFHIS.DATA.CI_NO = LNCAWA.CI_NO;
        BPCPFHIS.DATA.TX_VAL_DT = LNCAWA.START_DT;
        BPCPFHIS.DATA.TX_CCY = LNCAWA.CCY;
        BPCPFHIS.DATA.TX_AMT = LNCAWA.CONT_AMT;
        BPCPFHIS.DATA.PROD_CD = LNCAWA.PROD_TYP;
        CEP.TRC(SCCGWA, LNCAWA.TR_MMO);
        LNCAWA.TR_MMO = "12010001";
        BPCPFHIS.DATA.TX_MMO = LNCAWA.TR_MMO;
        CEP.TRC(SCCGWA, BPCPFHIS.DATA.TX_MMO);
        CEP.TRC(SCCGWA, LNCAWA.DRAW_AC);
        BPCPFHIS.DATA.RLT_AC = LNCAWA.DRAW_AC;
        CEP.TRC(SCCGWA, BPCPFHIS.DATA.RLT_AC);
        S000_CALL_BPZPFHIS();
    }
    public void S000_CALL_LNZPPMQ() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-FUN-PRD-PRM-INQ", LNCPPMQ);
        if (LNCPPMQ.RC.RC_RTNCODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, LNCPPMQ.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_BPZPFHIS() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-PROC-FHIS", BPCPFHIS);
        if (BPCPFHIS.RC.RC_CODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, BPCPFHIS.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
    }
    public void T000_READ_AGRE_CONT() throws IOException,SQLException,Exception {
        LNTAGRE_RD = new DBParm();
        LNTAGRE_RD.TableName = "LNTAGRE";
        LNTAGRE_RD.where = "DRAW_NO = :LNRAGRE.DRAW_NO "
            + "AND CONTRACT_LVL = 'D'";
        LNTAGRE_RD.fst = true;
        LNTAGRE_RD.order = "PAPER_NO DESC";
        IBS.READ(SCCGWA, LNRAGRE, this, LNTAGRE_RD);
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.DBIO_FLG);
        if (SCCGWA.COMM_AREA.DBIO_FLG == '0') {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_DRAW_DUPKEY, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_LNZIGECR() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-I-GENERATE-CNTRNO", LNCIGECR);
        if (LNCIGECR.RC.RC_CODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, LNCIGECR.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_CIZACCU() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "CI-INQ-ACCU", CICACCU);
        if (CICACCU.RC.RC_CODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, CICACCU.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_LNZSPADD() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-SVR-SPCLN-ADD", LNCSPADD);
        if (LNCSPADD.RC.RC_RTNCODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, LNCSPADD.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, WS_TEMP_VARIABLE.WS_MSGID);
        CEP.ERR(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_FLD_NO);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
