package com.hisun.LN;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;
import com.hisun.BP.*;
import com.hisun.CI.*;

import java.io.IOException;
import java.sql.SQLException;

public class LNOT2300 {
    String JIBS_tmp_str[] = new String[10];
    DBParm LNTAGRE_RD;
    char K_NORMAL_CONT = '0';
    String K_OUTPUT_FMT_2000 = "LN230";
    char K_CKPD_INQ = '0';
    LNOT2300_WS_TEMP_VARIABLE WS_TEMP_VARIABLE = new LNOT2300_WS_TEMP_VARIABLE();
    String WS_TEMP_CMMT_NO = " ";
    char WS_CI_TYP = ' ';
    char WS_PRODC_MOD = ' ';
    char WS_CAP_FROM = ' ';
    short WS_CNT = 0;
    LNCMSG_ERROR_MSG LNCMSG_ERROR_MSG = new LNCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    SCCMPAG SCCMPAG = new SCCMPAG();
    SCCFMT SCCFMT = new SCCFMT();
    LNCSCKPD LNCSCKPD = new LNCSCKPD();
    LNRAGRE LNRAGRE = new LNRAGRE();
    LNCIGECR LNCIGECR = new LNCIGECR();
    BPCPFHIS BPCPFHIS = new BPCPFHIS();
    CICACCU CICACCU = new CICACCU();
    LNCSPADD LNCSPADD = new LNCSPADD();
    LNCO2300 LNCO2300 = new LNCO2300();
    BPCQCCY BPCQCCY = new BPCQCCY();
    SCCGWA SCCGWA;
    LNB2300_AWA_2300 LNB2300_AWA_2300;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    SCCGAPV SCCGAPV;
    SCCGMSG SCCGMSG;
    BPCPQBNK_DATA_INFO BPCRBANK;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROCESS();
        B000_MAIN_PROCESS();
        CEP.TRC(SCCGWA, "LNOT2300 return!");
        Z_RET();
    }
    public void A000_INIT_PROCESS() throws IOException,SQLException,Exception {
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "LNB2300_AWA_2300>");
        LNB2300_AWA_2300 = (LNB2300_AWA_2300) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
    }
    public void B000_MAIN_PROCESS() throws IOException,SQLException,Exception {
        if (SCCGWA.COMM_AREA.CANCEL_IND == 'Y') {
            B200_LNZSPADD_PROCESS();
            if (LNB2300_AWA_2300.START_DT <= SCCGWA.COMM_AREA.AC_DATE) {
                B300_FINANCE_HIS();
            }
        } else {
            B000_CHECK_INPUT();
            B100_GET_INITIALIZE_DATA();
            IBS.init(SCCGWA, LNRAGRE);
            LNRAGRE.DRAW_NO = LNB2300_AWA_2300.DRAW_NO;
            T000_READ_AGRE_CONT();
            IBS.init(SCCGWA, LNCIGECR);
            LNCIGECR.INPUT_INFO.CI_NO = LNB2300_AWA_2300.CI_NO;
            LNCIGECR.INPUT_INFO.DRAW_NO = LNB2300_AWA_2300.DRAW_NO;
            LNCIGECR.INPUT_INFO.PAPER_NO = LNB2300_AWA_2300.PAPER_NO;
            LNCIGECR.INPUT_INFO.CTA_FROM = K_NORMAL_CONT;
            S000_CALL_LNZIGECR();
            CEP.TRC(SCCGWA, LNCIGECR.OUTPOUT_INFO.CONTRACT_NO);
            CEP.TRC(SCCGWA, LNCIGECR.OUTPOUT_INFO.CMMT_NO);
            LNB2300_AWA_2300.CONT_NO = LNCIGECR.OUTPOUT_INFO.CONTRACT_NO;
            WS_TEMP_CMMT_NO = LNCIGECR.OUTPOUT_INFO.CMMT_NO;
            CEP.TRC(SCCGWA, WS_TEMP_CMMT_NO);
            B200_LNZSPADD_PROCESS();
            if (LNB2300_AWA_2300.START_DT <= SCCGWA.COMM_AREA.AC_DATE) {
                B300_FINANCE_HIS();
            }
        }
    }
    public void B000_CHECK_INPUT() throws IOException,SQLException,Exception {
        if (LNB2300_AWA_2300.DRAW_NO.trim().length() == 0) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_E_INPUT_PAPER_NO, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (LNB2300_AWA_2300.DOMI_BR == 0) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_BK_BR_M_INPUT, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (LNB2300_AWA_2300.PROD_TYP.trim().length() == 0) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_PRDCD_M_INPUT, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (LNB2300_AWA_2300.START_DT == 0) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_START_DT_M_INPUT, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (LNB2300_AWA_2300.MATU_DT == 0) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_MUST_I_MATU_DT, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (LNB2300_AWA_2300.INT_D_BA.trim().length() == 0) {
            IBS.init(SCCGWA, BPCQCCY);
            BPCQCCY.DATA.CCY = LNB2300_AWA_2300.CCY;
            S000_CALL_BPZQCCY();
            LNB2300_AWA_2300.INT_D_BA = BPCQCCY.DATA.CALR_STD;
        }
        CEP.TRC(SCCGWA, LNB2300_AWA_2300.INT_D_BA);
        if (!LNB2300_AWA_2300.INT_D_BA.equalsIgnoreCase("01") 
            && !LNB2300_AWA_2300.INT_D_BA.equalsIgnoreCase("02") 
            && !LNB2300_AWA_2300.INT_D_BA.equalsIgnoreCase("03") 
            && !LNB2300_AWA_2300.INT_D_BA.equalsIgnoreCase("04") 
            && !LNB2300_AWA_2300.INT_D_BA.equalsIgnoreCase("05")) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_INT_D_BA, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (LNB2300_AWA_2300.CCY.trim().length() == 0) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_MUST_I_CTA_CCY, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (LNB2300_AWA_2300.CONT_AMT <= 0) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_CONT_AMT_MUST_INPUT, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (LNB2300_AWA_2300.DRAW_AC.trim().length() == 0) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_DRAW_AC_M_INPUT, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (LNB2300_AWA_2300.PAY_AC.trim().length() == 0) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_PAY_AC_M_INPUT, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (LNB2300_AWA_2300.GJPRJNO == ' ') {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_GJ_PRJNO_I, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (LNB2300_AWA_2300.CPND_USE == 'Y' 
            && LNB2300_AWA_2300.PEN_RATT == ' ') {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_PEN_RATT_M_INPUT, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (LNB2300_AWA_2300.CPND_USE == 'Y' 
            && LNB2300_AWA_2300.PEN_IRAT == 0) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_PEN_IRA_M_INPUT, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (LNB2300_AWA_2300.CPND_USE == 'Y' 
            && (LNB2300_AWA_2300.CPNDRATT != ' ' 
            || LNB2300_AWA_2300.CPND_IRA != 0)) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_CPND_INF_CANNOT_I, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
    }
    public void B100_GET_INITIALIZE_DATA() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, LNB2300_AWA_2300.DOMI_BR);
        if (LNB2300_AWA_2300.BOOK_CRE == 0) {
            LNB2300_AWA_2300.BOOK_CRE = LNB2300_AWA_2300.DOMI_BR;
            CEP.TRC(SCCGWA, LNB2300_AWA_2300.DOMI_BR);
        }
        CEP.TRC(SCCGWA, LNB2300_AWA_2300.CI_NO);
        if (LNB2300_AWA_2300.CI_NO.trim().length() == 0) {
            IBS.init(SCCGWA, CICACCU);
            CICACCU.DATA.ENTY_TYP = '1';
            CICACCU.DATA.AGR_NO = LNB2300_AWA_2300.PAY_AC;
            S000_CALL_CIZACCU();
            CEP.TRC(SCCGWA, CICACCU.DATA.CI_NO);
            LNB2300_AWA_2300.CI_NO = CICACCU.DATA.CI_NO;
            WS_CI_TYP = CICACCU.DATA.CI_TYP;
        }
        CEP.TRC(SCCGWA, LNB2300_AWA_2300.DW_BK_TP);
        if (LNB2300_AWA_2300.DW_BK_TP == ' ') {
            LNB2300_AWA_2300.DW_BK_TP = '0';
        }
        CEP.TRC(SCCGWA, LNB2300_AWA_2300.PA_BK_TP);
        if (LNB2300_AWA_2300.PA_BK_TP == ' ') {
            LNB2300_AWA_2300.PA_BK_TP = '0';
        }
        if (LNB2300_AWA_2300.DW_BK_TP == '1') {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_BKTP_INP, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (LNB2300_AWA_2300.PA_BK_TP == '1') {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_BKTP_INP, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        CEP.TRC(SCCGWA, LNB2300_AWA_2300.PROD_TYP);
        IBS.init(SCCGWA, LNCSCKPD);
        LNCSCKPD.FUNC = K_CKPD_INQ;
        LNCSCKPD.PROD_CD = LNB2300_AWA_2300.PROD_TYP;
        S000_CALL_LNZSCKPD();
        CEP.TRC(SCCGWA, WS_CI_TYP);
        CEP.TRC(SCCGWA, WS_PRODC_MOD);
        if (WS_CI_TYP == '1' 
            && WS_PRODC_MOD != 'R') {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_PROD_CI_TYP, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (WS_CI_TYP == '2' 
            && WS_PRODC_MOD != 'C') {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_PROD_CI_TYP, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
        if (WS_CI_TYP == '3' 
            && WS_PRODC_MOD != 'F') {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_PROD_CI_TYP, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
    }
    public void B200_LNZSPADD_PROCESS() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCSPADD);
        LNCSPADD.COMM_DATA.PAPER_NO = LNB2300_AWA_2300.PAPER_NO;
        LNCSPADD.COMM_DATA.DRAW_NO = LNB2300_AWA_2300.DRAW_NO;
        LNCSPADD.COMM_DATA.CONT_NO = LNB2300_AWA_2300.CONT_NO;
        LNCSPADD.COMM_DATA.BOOK_CRE = LNB2300_AWA_2300.BOOK_CRE;
        LNCSPADD.COMM_DATA.DOMI_BR = LNB2300_AWA_2300.DOMI_BR;
        LNCSPADD.COMM_DATA.CI_NO = LNB2300_AWA_2300.CI_NO;
        LNCSPADD.COMM_DATA.PROD_TYP = LNB2300_AWA_2300.PROD_TYP;
        LNCSPADD.COMM_DATA.START_DT = LNB2300_AWA_2300.START_DT;
        LNCSPADD.COMM_DATA.MATU_DT = LNB2300_AWA_2300.MATU_DT;
        LNCSPADD.COMM_DATA.CCY = LNB2300_AWA_2300.CCY;
        LNCSPADD.COMM_DATA.CONT_AMT = LNB2300_AWA_2300.CONT_AMT;
        LNCSPADD.COMM_DATA.REPY_MTH = LNB2300_AWA_2300.REPY_MTH;
        LNCSPADD.COMM_DATA.INST_MTH = LNB2300_AWA_2300.INST_MTH;
        LNCSPADD.COMM_DATA.PAYI_PERD = LNB2300_AWA_2300.PAYI_PER;
        LNCSPADD.COMM_DATA.CAL_PERU = LNB2300_AWA_2300.CAL_PERU;
        LNCSPADD.COMM_DATA.CAL_PERD = LNB2300_AWA_2300.CAL_PERD;
        LNCSPADD.COMM_DATA.PAY_DTYP = LNB2300_AWA_2300.PAY_DTYP;
        LNCSPADD.COMM_DATA.CAL_DAY = LNB2300_AWA_2300.CAL_DAY;
        LNCSPADD.COMM_DATA.CAL_FSDT = LNB2300_AWA_2300.CAL_FSDT;
        LNCSPADD.COMM_DATA.PYP_CIRC = LNB2300_AWA_2300.PYP_CIRC;
        LNCSPADD.COMM_DATA.PYP_PERU = LNB2300_AWA_2300.PYP_PERU;
        LNCSPADD.COMM_DATA.PYP_PERD = LNB2300_AWA_2300.PYP_PERD;
        LNCSPADD.COMM_DATA.DW_BK_TP = LNB2300_AWA_2300.DW_BK_TP;
        LNCSPADD.COMM_DATA.DRAW_ACT = LNB2300_AWA_2300.DRAW_ACT;
        LNCSPADD.COMM_DATA.DRAW_AC = LNB2300_AWA_2300.DRAW_AC;
        LNCSPADD.COMM_DATA.DRAW_SEQ = LNB2300_AWA_2300.DRAW_SEQ;
        LNCSPADD.COMM_DATA.PA_BK_TP = LNB2300_AWA_2300.PA_BK_TP;
        LNCSPADD.COMM_DATA.PAY_AC_T = LNB2300_AWA_2300.PAY_AC_T;
        LNCSPADD.COMM_DATA.PAY_AC = LNB2300_AWA_2300.PAY_AC;
        LNCSPADD.COMM_DATA.GJPRJNO = LNB2300_AWA_2300.GJPRJNO;
        LNCSPADD.COMM_DATA.GUAR_AC = LNB2300_AWA_2300.GUAR_AC;
        LNCSPADD.COMM_DATA.GUAR_AMT = LNB2300_AWA_2300.GUAR_AMT;
        LNCSPADD.COMM_DATA.KFS_AC = LNB2300_AWA_2300.KFS_AC;
        LNCSPADD.COMM_DATA.INT_D_BA = LNB2300_AWA_2300.INT_D_BA;
        LNCSPADD.COMM_DATA.IRAT_TP1 = LNB2300_AWA_2300.IRAT_TP1;
        LNCSPADD.COMM_DATA.IN_RATE = LNB2300_AWA_2300.IN_RATE;
        LNCSPADD.COMM_DATA.PEN_RATT = LNB2300_AWA_2300.PEN_RATT;
        LNCSPADD.COMM_DATA.PEN_IRAT = LNB2300_AWA_2300.PEN_IRAT;
        LNCSPADD.COMM_DATA.CPND_USE = LNB2300_AWA_2300.CPND_USE;
        LNCSPADD.COMM_DATA.CPNDRATT = LNB2300_AWA_2300.CPNDRATT;
        LNCSPADD.COMM_DATA.CPND_IRA = LNB2300_AWA_2300.CPND_IRA;
        LNCSPADD.COMM_DATA.ABUSRATT = LNB2300_AWA_2300.ABUSRATT;
        LNCSPADD.COMM_DATA.ABUSIRAT = LNB2300_AWA_2300.ABUSIRAT;
        LNCSPADD.COMM_DATA.GUAPREF = LNB2300_AWA_2300.GUAPREF;
        LNCSPADD.COMM_DATA.GUARDUAP = LNB2300_AWA_2300.GUARDUAP;
        LNCSPADD.COMM_DATA.GUARPSEQ = LNB2300_AWA_2300.GUARPSEQ;
        LNCSPADD.COMM_DATA.OLC_PERU = LNB2300_AWA_2300.OLC_PERU;
        LNCSPADD.COMM_DATA.OLC_PERD = LNB2300_AWA_2300.OLC_PERD;
        LNCSPADD.COMM_DATA.TR_MMO = LNB2300_AWA_2300.TR_MMO;
        LNCSPADD.COMM_DATA.REMARK1 = LNB2300_AWA_2300.REMARK1;
        for (WS_CNT = 1; WS_CNT <= 5; WS_CNT += 1) {
            LNCSPADD.COMM_DATA.FEE_DATA[WS_CNT-1].FEE_CODE = LNB2300_AWA_2300.FEE_INF[WS_CNT-1].FEE_CODE;
            LNCSPADD.COMM_DATA.FEE_DATA[WS_CNT-1].FEE_AMT = LNB2300_AWA_2300.FEE_INF[WS_CNT-1].FEE_AMT;
        }
        LNCSPADD.COMM_DATA.FEE_ACT = LNB2300_AWA_2300.FEE_ACT;
        LNCSPADD.COMM_DATA.FEE_AC = LNB2300_AWA_2300.FEE_AC;
        LNCSPADD.COMM_DATA.YHS_AMT = LNB2300_AWA_2300.YHS_AMT;
        LNCSPADD.COMM_DATA.CUSTM1 = LNB2300_AWA_2300.CUSTM1;
        LNCSPADD.COMM_DATA.CUSTM2 = LNB2300_AWA_2300.CUSTM2;
        LNCSPADD.COMM_DATA.CUSTM3 = LNB2300_AWA_2300.CUSTM3;
        LNCSPADD.COMM_DATA.BAR_CD = LNB2300_AWA_2300.BAR_CD;
        LNCSPADD.COMM_DATA.UNIT_CD = LNB2300_AWA_2300.UNIT_CD;
        S000_CALL_LNZSPADD();
    }
    public void B300_FINANCE_HIS() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCPFHIS);
        BPCPFHIS.DATA.TX_DRCR_FLG = 'D';
        BPCPFHIS.DATA.PRINT_IND = 'Y';
        BPCPFHIS.DATA.JRNNO = SCCGWA.COMM_AREA.JRN_NO;
        BPCPFHIS.DATA.AC_DT = SCCGWA.COMM_AREA.AC_DATE;
        BPCPFHIS.DATA.VCHNO = SCCGWA.COMM_AREA.VCH_NO;
        BPCPFHIS.DATA.REF_NO = LNB2300_AWA_2300.CONT_NO;
        BPCPFHIS.DATA.AC = LNB2300_AWA_2300.PAPER_NO;
        BPCPFHIS.DATA.ACO_AC = LNB2300_AWA_2300.CONT_NO;
        BPCPFHIS.DATA.CI_NO = LNB2300_AWA_2300.CI_NO;
        BPCPFHIS.DATA.TX_VAL_DT = LNB2300_AWA_2300.START_DT;
        BPCPFHIS.DATA.TX_CCY = LNB2300_AWA_2300.CCY;
        BPCPFHIS.DATA.TX_AMT = LNB2300_AWA_2300.CONT_AMT;
        BPCPFHIS.DATA.PROD_CD = LNB2300_AWA_2300.PROD_TYP;
        CEP.TRC(SCCGWA, LNB2300_AWA_2300.TR_MMO);
        LNB2300_AWA_2300.TR_MMO = "12010001";
        BPCPFHIS.DATA.TX_MMO = LNB2300_AWA_2300.TR_MMO;
        CEP.TRC(SCCGWA, BPCPFHIS.DATA.TX_MMO);
        CEP.TRC(SCCGWA, LNB2300_AWA_2300.DRAW_AC);
        BPCPFHIS.DATA.RLT_AC = LNB2300_AWA_2300.DRAW_AC;
        CEP.TRC(SCCGWA, BPCPFHIS.DATA.RLT_AC);
        S000_CALL_BPZPFHIS();
    }
    public void S000_CALL_LNZSCKPD() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-S-CHK-PROD", LNCSCKPD);
    }
    public void S000_CALL_BPZQCCY() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-INQUIRE-CCY", BPCQCCY);
        if (BPCQCCY.RC.RTNCODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, BPCQCCY.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_BPZPFHIS() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-PROC-FHIS", BPCPFHIS);
        if (BPCPFHIS.RC.RC_CODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, BPCPFHIS.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
    }
    public void T000_READ_AGRE_CONT() throws IOException,SQLException,Exception {
        LNTAGRE_RD = new DBParm();
        LNTAGRE_RD.TableName = "LNTAGRE";
        LNTAGRE_RD.where = "DRAW_NO = :LNRAGRE.DRAW_NO";
        LNTAGRE_RD.fst = true;
        LNTAGRE_RD.order = "PAPER_NO DESC";
        IBS.READ(SCCGWA, LNRAGRE, this, LNTAGRE_RD);
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.DBIO_FLG);
        if (SCCGWA.COMM_AREA.DBIO_FLG == '0') {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_DRAW_DUPKEY, WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_LNZIGECR() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-I-GENERATE-CNTRNO", LNCIGECR);
        if (LNCIGECR.RC.RC_CODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, LNCIGECR.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_CIZACCU() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "CI-INQ-ACCU", CICACCU);
        if (CICACCU.RC.RC_CODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, CICACCU.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_LNZSPADD() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-SVR-SPCLN-ADD", LNCSPADD);
        if (LNCSPADD.RC.RC_RTNCODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, LNCSPADD.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_MSGID);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, WS_TEMP_VARIABLE.WS_MSGID);
        CEP.ERR(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_FLD_NO);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
