package com.hisun.LN;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;
import com.hisun.BP.*;

import java.io.IOException;
import java.sql.SQLException;

public class LNOT9209 {
    String K_OUTPUT_FMT = "LNC92";
    String K_HIS_REMARKS = "REDISCOUNT DRAWDOWN CONTRACT DELETION";
    LNOT9209_WS_TEMP_VARIABLE WS_TEMP_VARIABLE = new LNOT9209_WS_TEMP_VARIABLE();
    LNCMSG_ERROR_MSG LNCMSG_ERROR_MSG = new LNCMSG_ERROR_MSG();
    SCCWOUT SCCWOUT = new SCCWOUT();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    SCCMPAG SCCMPAG = new SCCMPAG();
    SCCFMT SCCFMT = new SCCFMT();
    LNCSRDSC LNCSRDSC = new LNCSRDSC();
    LNCORDSC LNCORDSC = new LNCORDSC();
    BPCPFHIS BPCPFHIS = new BPCPFHIS();
    BPCPOEWA BPCPOEWA = new BPCPOEWA();
    LNCSSTBL LNCSSTBL = new LNCSSTBL();
    SCCGWA SCCGWA;
    LNB9200_AWA_9200 LNB9200_AWA_9200;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGAPV SCCGAPV;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROCESS();
        B000_MAIN_PROCESS();
        CEP.TRC(SCCGWA, "LNOT9209 return!");
        Z_RET();
    }
    public void A000_INIT_PROCESS() throws IOException,SQLException,Exception {
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        SCCGAPV = (SCCGAPV) GWA_SC_AREA.APVL_AREA_PTR;
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "LNB9200_AWA_9200>");
        LNB9200_AWA_9200 = (LNB9200_AWA_9200) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        CEP.TRC(SCCGWA, GWA_BP_AREA.CANCEL_AREA.CAN_AC_DATE);
        CEP.TRC(SCCGWA, GWA_BP_AREA.CANCEL_AREA.CAN_JRN_NO);
        CEP.TRC(SCCGWA, LNB9200_AWA_9200.CONT_NO);
    }
    public void B000_MAIN_PROCESS() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.AC_DATE);
        B100_SERVER_PROC();
        B200_OUTPUT_PROCESS();
        B300_FINANCE_HIS();
        B222_CR_PROC();
    }
    public void B100_SERVER_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCSRDSC);
        LNCSRDSC.COMM_DATA.CONTRACT_NO = LNB9200_AWA_9200.CONT_NO;
        LNCSRDSC.COMM_DATA.BOOK_BR = LNB9200_AWA_9200.BOOK_CRE;
        LNCSRDSC.COMM_DATA.CI_NO = LNB9200_AWA_9200.CI_NO;
        LNCSRDSC.COMM_DATA.PROD_CD = LNB9200_AWA_9200.PROD_CD;
        if (LNB9200_AWA_9200.DSC_TYP == '1') {
            LNCSRDSC.COMM_DATA.DSC_TYP = '2';
        } else {
            LNCSRDSC.COMM_DATA.DSC_TYP = '3';
        }
        LNCSRDSC.COMM_DATA.DSC_METH = LNB9200_AWA_9200.DSC_METH;
        LNCSRDSC.COMM_DATA.CCY = LNB9200_AWA_9200.CCY;
        LNCSRDSC.COMM_DATA.AMT = LNB9200_AWA_9200.AMT;
        LNCSRDSC.COMM_DATA.VAL_DT = LNB9200_AWA_9200.DSC_DT;
        LNCSRDSC.COMM_DATA.BB_SDT = LNB9200_AWA_9200.BB_SDT;
        LNCSRDSC.COMM_DATA.DUE_DT = LNB9200_AWA_9200.MATU_DT;
        LNCSRDSC.COMM_DATA.BILL_FRM = LNB9200_AWA_9200.BILL_FRM;
        LNCSRDSC.COMM_DATA.SETL_FLG = LNB9200_AWA_9200.SETL_FLG;
        LNCSRDSC.COMM_DATA.DSC_NINR = LNB9200_AWA_9200.DSC_NINR;
        LNCSRDSC.COMM_DATA.DSC_OINR = LNB9200_AWA_9200.DSC_OINR;
        LNCSRDSC.COMM_DATA.DSC_INTA = LNB9200_AWA_9200.DSC_INTA;
        LNCSRDSC.COMM_DATA.DRFT_NO = LNB9200_AWA_9200.DRFT_NO;
        LNCSRDSC.COMM_DATA.DRFT_TYP = LNB9200_AWA_9200.DRFT_TYP;
        LNCSRDSC.COMM_DATA.DRFT_BOT = LNB9200_AWA_9200.DRFT_BOT;
        LNCSRDSC.COMM_DATA.DRFT_FLG = LNB9200_AWA_9200.DRFT_FLG;
        LNCSRDSC.COMM_DATA.DRFT_AMT = LNB9200_AWA_9200.DRFT_AMT;
        LNCSRDSC.COMM_DATA.DRFT_SDT = LNB9200_AWA_9200.DRFT_SDT;
        LNCSRDSC.COMM_DATA.DRFT_EDT = LNB9200_AWA_9200.DRFT_EDT;
        LNCSRDSC.COMM_DATA.DRFT_NM = LNB9200_AWA_9200.DRFT_NM;
        LNCSRDSC.COMM_DATA.DRFT_AC = LNB9200_AWA_9200.DRFT_AC;
        LNCSRDSC.COMM_DATA.DRFT_DNO = LNB9200_AWA_9200.DRFT_DNO;
        LNCSRDSC.COMM_DATA.DRFT_DNM = LNB9200_AWA_9200.DRFT_DNM;
        LNCSRDSC.COMM_DATA.DRFT_ANO = LNB9200_AWA_9200.DRFT_ANO;
        LNCSRDSC.COMM_DATA.DRFT_ANM = LNB9200_AWA_9200.DRFT_ANM;
        LNB9200_AWA_9200.DRAW_ACT = "02";
        LNCSRDSC.COMM_DATA.DRAW_ACT = LNB9200_AWA_9200.DRAW_ACT;
        LNCSRDSC.COMM_DATA.DRAW_AC = LNB9200_AWA_9200.DRAW_AC;
        LNCSRDSC.COMM_DATA.PAYI_MEH = LNB9200_AWA_9200.PAYI_MEH;
        LNCSRDSC.COMM_DATA.PAYI_PCT = LNB9200_AWA_9200.PAYI_PCT;
        if (LNB9200_AWA_9200.PAYI_MEH == '2' 
            || LNB9200_AWA_9200.PAYI_MEH == '4') {
            LNB9200_AWA_9200.PAYI_AMT = LNB9200_AWA_9200.DSC_INTA;
        }
        if (LNB9200_AWA_9200.PAYI_MEH == '3' 
            && LNB9200_AWA_9200.PAYI_AMT == 0) {
            LNB9200_AWA_9200.PAYI_AMT = LNB9200_AWA_9200.DSC_INTA * LNB9200_AWA_9200.PAYI_PCT / 100;
        }
        CEP.TRC(SCCGWA, LNB9200_AWA_9200.PAYI_AMT);
        LNCSRDSC.COMM_DATA.PAYI_AMT = LNB9200_AWA_9200.PAYI_AMT;
        LNCSRDSC.COMM_DATA.PAYI_ACT = LNB9200_AWA_9200.PAYI_ACT;
        LNCSRDSC.COMM_DATA.PAYI_AC = LNB9200_AWA_9200.PAYI_AC;
        LNCSRDSC.COMM_DATA.REMARK = LNB9200_AWA_9200.REMARK;
        LNCSRDSC.COMM_DATA.LMT_SYS = LNB9200_AWA_9200.LMT_SYS;
        LNCSRDSC.COMM_DATA.RVS_NO = LNB9200_AWA_9200.RVS_NO;
        S000_CALL_LNZSRDSC();
    }
    public void B200_OUTPUT_PROCESS() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCORDSC);
        LNCORDSC.CONTRACT_NO = LNB9200_AWA_9200.CONT_NO;
        LNCORDSC.BOOK_BR = LNB9200_AWA_9200.BOOK_CRE;
        LNCORDSC.CI_NO = LNB9200_AWA_9200.CI_NO;
        LNCORDSC.CI_CNM = LNB9200_AWA_9200.CI_CNM;
        LNCORDSC.PROD_CD = LNB9200_AWA_9200.PROD_CD;
        LNCORDSC.PROD_NM = LNB9200_AWA_9200.PROD_NM;
        LNCORDSC.DSC_TYP = LNB9200_AWA_9200.DSC_TYP;
        LNCORDSC.DSC_METH = LNB9200_AWA_9200.DSC_METH;
        LNCORDSC.CCY = LNB9200_AWA_9200.CCY;
        LNCORDSC.AMT = LNB9200_AWA_9200.AMT;
        LNCORDSC.VAL_DT = LNB9200_AWA_9200.DSC_DT;
        LNCORDSC.BB_SDT = LNB9200_AWA_9200.BB_SDT;
        LNCORDSC.DUE_DT = LNB9200_AWA_9200.MATU_DT;
        LNCORDSC.BILL_FRM = LNB9200_AWA_9200.BILL_FRM;
        LNCORDSC.SETL_FLG = LNB9200_AWA_9200.SETL_FLG;
        LNCORDSC.DSC_NINR = LNB9200_AWA_9200.DSC_NINR;
        LNCORDSC.DSC_OINR = LNB9200_AWA_9200.DSC_OINR;
        LNCORDSC.DSC_INTA = LNB9200_AWA_9200.DSC_INTA;
        LNCORDSC.DRFT_NO = LNB9200_AWA_9200.DRFT_NO;
        LNCORDSC.DRFT_TYP = LNB9200_AWA_9200.DRFT_TYP;
        LNCORDSC.DRFT_BOT = LNB9200_AWA_9200.DRFT_BOT;
        LNCORDSC.DRFT_FLG = LNB9200_AWA_9200.DRFT_FLG;
        LNCORDSC.DRFT_AMT = LNB9200_AWA_9200.DRFT_AMT;
        LNCORDSC.DRFT_SDT = LNB9200_AWA_9200.DRFT_SDT;
        LNCORDSC.DRFT_EDT = LNB9200_AWA_9200.DRFT_EDT;
        LNCORDSC.DRFT_NM = LNB9200_AWA_9200.DRFT_NM;
        LNCORDSC.DRFT_AC = LNB9200_AWA_9200.DRFT_AC;
        LNCORDSC.DRFT_DNO = LNB9200_AWA_9200.DRFT_DNO;
        LNCORDSC.DRFT_DNM = LNB9200_AWA_9200.DRFT_DNM;
        LNCORDSC.DRFT_ANO = LNB9200_AWA_9200.DRFT_ANO;
        LNCORDSC.DRFT_ANM = LNB9200_AWA_9200.DRFT_ANM;
        LNCORDSC.PAYI_MEH = LNB9200_AWA_9200.PAYI_MEH;
        LNCORDSC.PAYI_PCT = LNB9200_AWA_9200.PAYI_PCT;
        LNCORDSC.PAYI_AMT = LNCSRDSC.COMM_DATA.PAYI_AMT;
        LNCORDSC.PAYI_ACT = LNB9200_AWA_9200.PAYI_ACT;
        LNCORDSC.PAYI_AC = LNB9200_AWA_9200.PAYI_AC;
        LNCORDSC.PAYI_NM = LNB9200_AWA_9200.PAYI_ACN;
        LNCORDSC.REMARK = LNB9200_AWA_9200.REMARK;
        IBS.init(SCCGWA, SCCFMT);
        SCCFMT.FMTID = K_OUTPUT_FMT;
        SCCFMT.DATA_PTR = LNCORDSC;
        SCCFMT.DATA_LEN = 2314;
        IBS.FMT(SCCGWA, SCCFMT);
    }
    public void B300_FINANCE_HIS() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCPFHIS);
        BPCPFHIS.DATA.TX_DRCR_FLG = 'D';
        BPCPFHIS.DATA.PRINT_IND = 'Y';
        BPCPFHIS.DATA.JRNNO = SCCGWA.COMM_AREA.JRN_NO;
        BPCPFHIS.DATA.AC_DT = SCCGWA.COMM_AREA.AC_DATE;
        BPCPFHIS.DATA.VCHNO = SCCGWA.COMM_AREA.VCH_NO;
        BPCPFHIS.DATA.REF_NO = LNCSRDSC.COMM_DATA.CONTRACT_NO;
        BPCPFHIS.DATA.AC = LNCSRDSC.COMM_DATA.CONTRACT_NO;
        BPCPFHIS.DATA.CI_NO = LNCSRDSC.COMM_DATA.CI_NO;
        BPCPFHIS.DATA.TX_VAL_DT = LNCSRDSC.COMM_DATA.VAL_DT;
        BPCPFHIS.DATA.TX_CCY = LNCSRDSC.COMM_DATA.CCY;
        BPCPFHIS.DATA.TX_AMT = LNCSRDSC.COMM_DATA.AMT;
        BPCPFHIS.DATA.PROD_CD = LNCSRDSC.COMM_DATA.PROD_CD;
        BPCPFHIS.DATA.REMARK = K_HIS_REMARKS;
        BPCPFHIS.DATA.FMT_CODE = K_OUTPUT_FMT;
        BPCPFHIS.DATA.FMT_LEN = 2314;
        BPCPFHIS.DATA.FMT_DATA = IBS.CLS2CPY(SCCGWA, LNCORDSC);
        BPCPFHIS.DATA.TX_MMO = "X7Y";
        S000_CALL_BPZPFHIS();
    }
    public void S000_CALL_LNZSSTBL() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-CHECK-CI-STS", LNCSSTBL);
        if (LNCSSTBL.RC.RC_CODE != 0) {
            WS_TEMP_VARIABLE.WS_MSGID = IBS.CLS2CPY(SCCGWA, LNCSSTBL.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_LNZSRDSC() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-SVR-REDISCOUNT", LNCSRDSC);
        if (LNCSRDSC.RC.RC_RTNCODE != 0) {
            WS_TEMP_VARIABLE.WS_MSGID = IBS.CLS2CPY(SCCGWA, LNCSRDSC.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_BPZPFHIS() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-PROC-FHIS", BPCPFHIS);
        if (BPCPFHIS.RC.RC_CODE != 0) {
            WS_TEMP_VARIABLE.WS_MSGID = IBS.CLS2CPY(SCCGWA, BPCPFHIS.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void B222_CR_PROC() throws IOException,SQLException,Exception {
        for (WS_TEMP_VARIABLE.WS_I = 1; LNB9200_AWA_9200.AC_ARRAY[WS_TEMP_VARIABLE.WS_I-1].EVENT_CD.trim().length() != 0 
            && WS_TEMP_VARIABLE.WS_I <= 5; WS_TEMP_VARIABLE.WS_I += 1) {
            IBS.init(SCCGWA, BPCPOEWA);
            BPCPOEWA.DATA.CNTR_TYPE = "CLYY";
            BPCPOEWA.DATA.PROD_CODE = LNB9200_AWA_9200.AC_ARRAY[WS_TEMP_VARIABLE.WS_I-1].PROD_CDO;
            BPCPOEWA.DATA.EVENT_CODE = LNB9200_AWA_9200.AC_ARRAY[WS_TEMP_VARIABLE.WS_I-1].EVENT_CD;
            BPCPOEWA.DATA.BR_OLD = SCCGWA.COMM_AREA.BR_DP.TR_BRANCH;
            BPCPOEWA.DATA.CCY_INFO[1-1].CCY = LNB9200_AWA_9200.CCY;
            BPCPOEWA.DATA.AMT_INFO[1-1].AMT = LNB9200_AWA_9200.DRFT_AMT;
            BPCPOEWA.DATA.VALUE_DATE = SCCGWA.COMM_AREA.AC_DATE;
            BPCPOEWA.DATA.CI_NO = LNB9200_AWA_9200.CI_NO;
            BPCPOEWA.DATA.RVS_NO = LNB9200_AWA_9200.RVS_NO;
            BPCPOEWA.DATA.SETTLE_DT = SCCGWA.COMM_AREA.CLEAR_DATE;
            S000_CALL_BPZPOEWA();
        }
    }
    public void S000_CALL_BPZPOEWA() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BP-P-WRT-ONL-EWA", BPCPOEWA);
        if (BPCPOEWA.RC.RC_CODE != 0) {
            WS_TEMP_VARIABLE.WS_MSGID = IBS.CLS2CPY(SCCGWA, BPCPOEWA.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_TEMP_VARIABLE.WS_MSGID, WS_TEMP_VARIABLE.WS_FLD_NO);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
