package com.hisun.LN;

import com.hisun.SM.*;
import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;

import java.io.IOException;
import java.sql.SQLException;

public class LNOT7040 {
    String JIBS_tmp_str[] = new String[10];
    char K_ERROR = 'E';
    LNOT7040_WS_TEMP_VARIABLE WS_TEMP_VARIABLE = new LNOT7040_WS_TEMP_VARIABLE();
    short WS_I = 0;
    LNCX704 LNCX704 = new LNCX704();
    SMCMSG_ERROR_MSG SMCMSG_ERROR_MSG = new SMCMSG_ERROR_MSG();
    SCCWOUT SCCWOUT = new SCCWOUT();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    SCCMPAG SCCMPAG = new SCCMPAG();
    SCCFMT SCCFMT = new SCCFMT();
    LNCCNTIM LNCCNTIM = new LNCCNTIM();
    SCCGWA SCCGWA;
    LNB7040_AWA_7040 LNB7040_AWA_7040;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROCESS();
        B000_MAIN_PROCESS();
        CEP.TRC(SCCGWA, "LNOT7040 return!");
        Z_RET();
    }
    public void A000_INIT_PROCESS() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "LNB7040_AWA_7040>");
        LNB7040_AWA_7040 = (LNB7040_AWA_7040) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
    }
    public void B000_MAIN_PROCESS() throws IOException,SQLException,Exception {
        B100_CHECK_INPUT();
        B200_CALL_LNZCNTIM();
        B300_OUTPUT_PROCESS();
    }
    public void B100_CHECK_INPUT() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, LNB7040_AWA_7040.FUNC);
        CEP.TRC(SCCGWA, LNB7040_AWA_7040.PTYP);
        CEP.TRC(SCCGWA, LNB7040_AWA_7040.CODE);
        CEP.TRC(SCCGWA, LNB7040_AWA_7040.DESC);
        CEP.TRC(SCCGWA, LNB7040_AWA_7040.CDESC);
        CEP.TRC(SCCGWA, LNB7040_AWA_7040.EFFDATE);
        CEP.TRC(SCCGWA, LNB7040_AWA_7040.EXPDATE);
        CEP.TRC(SCCGWA, LNB7040_AWA_7040.LEN);
        CEP.TRC(SCCGWA, LNB7040_AWA_7040.CTNR_DAT[1-1].CTNR_TYP);
        CEP.TRC(SCCGWA, LNB7040_AWA_7040.CTNR_DAT[1-1].CTNR_GRP);
        CEP.TRC(SCCGWA, LNB7040_AWA_7040.CTNR_DAT[1-1].CTNR_SEQ);
        CEP.TRC(SCCGWA, LNB7040_AWA_7040.CTNR_DAT[1-1].LOG_REL);
        CEP.TRC(SCCGWA, LNB7040_AWA_7040.CTNR_DAT[2-1].CTNR_TYP);
        CEP.TRC(SCCGWA, LNB7040_AWA_7040.CTNR_DAT[2-1].CTNR_GRP);
        CEP.TRC(SCCGWA, LNB7040_AWA_7040.CTNR_DAT[2-1].CTNR_SEQ);
        CEP.TRC(SCCGWA, LNB7040_AWA_7040.CTNR_DAT[2-1].LOG_REL);
        CEP.TRC(SCCGWA, LNB7040_AWA_7040.CTNR_DAT[3-1].CTNR_TYP);
        CEP.TRC(SCCGWA, LNB7040_AWA_7040.CTNR_DAT[3-1].CTNR_GRP);
        CEP.TRC(SCCGWA, LNB7040_AWA_7040.CTNR_DAT[3-1].CTNR_SEQ);
        CEP.TRC(SCCGWA, LNB7040_AWA_7040.CTNR_DAT[3-1].LOG_REL);
        if (LNB7040_AWA_7040.FUNC != 'I' 
            && LNB7040_AWA_7040.FUNC != 'A' 
            && LNB7040_AWA_7040.FUNC != 'M' 
            && LNB7040_AWA_7040.FUNC != 'D') {
            IBS.CPY2CLS(SCCGWA, SMCMSG_ERROR_MSG.SM_INPUT_ERROR, WS_TEMP_VARIABLE.WS_MSGID);
            IBS.CPY2CLS(SCCGWA, SMCMSG_ERROR_MSG.SM_INPUT_ERROR, LNCCNTIM.RC);
            WS_TEMP_VARIABLE.WS_FLD_NO = LNB7040_AWA_7040.FUNC_NO;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        R00_CHECK_ERROR();
    }
    public void R00_CHECK_ERROR() throws IOException,SQLException,Exception {
        if (SCCGWA.COMM_AREA.MSG_PROC_AREA.MSG_TYPE == K_ERROR 
            && SCCGWA.COMM_AREA.MSG_PROC_AREA.MSG_ID.MSG_CODE == 0) {
            IBS.CPY2CLS(SCCGWA, SMCMSG_ERROR_MSG.SM_INPUT_ERROR, WS_TEMP_VARIABLE.WS_MSGID);
            WS_TEMP_VARIABLE.WS_FLD_NO = 0;
            S000_ERR_MSG_PROC();
        }
    }
    public void B200_CALL_LNZCNTIM() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCCNTIM);
        LNCCNTIM.FUNC = LNB7040_AWA_7040.FUNC;
        LNCCNTIM.KEY.TYP = LNB7040_AWA_7040.PTYP;
        LNCCNTIM.KEY.CD = LNB7040_AWA_7040.CODE;
        LNCCNTIM.EFF_DATE = LNB7040_AWA_7040.EFFDATE;
        LNCCNTIM.EXP_DATE = LNB7040_AWA_7040.EXPDATE;
        LNCCNTIM.DESC = LNB7040_AWA_7040.DESC;
        LNCCNTIM.CDESC = LNB7040_AWA_7040.CDESC;
        for (WS_I = 1; WS_I <= 10; WS_I += 1) {
            LNCCNTIM.DATA_TXT.CTNR_DATA[WS_I-1].CTNR_ID.CTNR_TYP = LNB7040_AWA_7040.CTNR_DAT[WS_I-1].CTNR_TYP;
            LNCCNTIM.DATA_TXT.CTNR_DATA[WS_I-1].CTNR_ID.CTNR_GROP = LNB7040_AWA_7040.CTNR_DAT[WS_I-1].CTNR_GRP;
            LNCCNTIM.DATA_TXT.CTNR_DATA[WS_I-1].CTNR_ID.CTNR_SEQ = LNB7040_AWA_7040.CTNR_DAT[WS_I-1].CTNR_SEQ;
            LNCCNTIM.DATA_TXT.CTNR_DATA[WS_I-1].LOG_REL = LNB7040_AWA_7040.CTNR_DAT[WS_I-1].LOG_REL;
        }
        S000_CALL_LNZCNTIM();
    }
    public void B300_OUTPUT_PROCESS() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCX704);
        IBS.init(SCCGWA, SCCFMT);
        LNCX704.FUNC = LNCCNTIM.FUNC;
        LNCX704.TYPE = LNCCNTIM.KEY.TYP;
        LNCX704.CODE = LNCCNTIM.KEY.CD;
        LNCX704.DESC = LNCCNTIM.DESC;
        LNCX704.CDESC = LNCCNTIM.CDESC;
        LNCX704.EFF_DATE = LNCCNTIM.EFF_DATE;
        LNCX704.EXP_DATE = LNCCNTIM.EXP_DATE;
        for (WS_I = 1; WS_I <= 10; WS_I += 1) {
            LNCX704.CNTIM_CTNR_DATA[WS_I-1].CNTIM_CTNR_TYP = LNCCNTIM.DATA_TXT.CTNR_DATA[WS_I-1].CTNR_ID.CTNR_TYP;
            LNCX704.CNTIM_CTNR_DATA[WS_I-1].CNTIM_CTNR_GROP = LNCCNTIM.DATA_TXT.CTNR_DATA[WS_I-1].CTNR_ID.CTNR_GROP;
            LNCX704.CNTIM_CTNR_DATA[WS_I-1].CNTIM_CTNR_SEQ = LNCCNTIM.DATA_TXT.CTNR_DATA[WS_I-1].CTNR_ID.CTNR_SEQ;
            LNCX704.CNTIM_CTNR_DATA[WS_I-1].CNTIM_LOG_REL = LNCCNTIM.DATA_TXT.CTNR_DATA[WS_I-1].LOG_REL;
        }
        SCCFMT.FMTID = "LN704";
        SCCFMT.DATA_PTR = LNCX704;
        SCCFMT.DATA_LEN = 198;
        IBS.FMT(SCCGWA, SCCFMT);
    }
    public void S000_CALL_LNZCNTIM() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, LNCCNTIM);
        IBS.CALLCPN(SCCGWA, "LN-PRM-CNTI-MAINT", LNCCNTIM);
        CEP.TRC(SCCGWA, LNCCNTIM);
        if (LNCCNTIM.RC.RC_RTNCODE != 0) {
            WS_TEMP_VARIABLE.WS_MSGID.WS_MSG_AP = LNCCNTIM.RC.RC_APP;
            WS_TEMP_VARIABLE.WS_MSGID.WS_MSG_CODE = LNCCNTIM.RC.RC_RTNCODE;
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, WS_TEMP_VARIABLE.WS_MSGID);
        CEP.ERR(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_FLD_NO);
    }
    public void S000_ERR_MSG_PROC_CONTINUE() throws IOException,SQLException,Exception {
        JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, WS_TEMP_VARIABLE.WS_MSGID);
        CEP.ERRC(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_FLD_NO);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
