package com.hisun.LN;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;
import com.hisun.CI.*;
import com.hisun.BP.*;

import java.io.IOException;
import java.sql.SQLException;

public class LNOT5100 {
    String WS_MSGID = " ";
    short WS_FLD_NO = 0;
    String K_HIS_REMARKS = "REMARK INTEREST";
    String K_PROD_CD = "REM INT";
    String K_HIS_CPB_NM1 = "REM INT";
    String K_HIS_RMKS = "REM INT";
    LNCMSG_ERROR_MSG LNCMSG_ERROR_MSG = new LNCMSG_ERROR_MSG();
    SCCWOUT SCCWOUT = new SCCWOUT();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    SCCMPAG SCCMPAG = new SCCMPAG();
    SCCFMT SCCFMT = new SCCFMT();
    LNCOWLAD LNCOWLAD = new LNCOWLAD();
    LNCSREMI LNCSREMI = new LNCSREMI();
    CICCUST CICCUST = new CICCUST();
    CICACCU CICACCU = new CICACCU();
    CICSSTC CICSSTC = new CICSSTC();
    BPCPFHIS BPCPFHIS = new BPCPFHIS();
    LNCSSETL LNCSSETL = new LNCSSETL();
    SCCGWA SCCGWA;
    LNB5100_AWA_5100 LNB5100_AWA_5100;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    SCCGAPV SCCGAPV;
    SCCGMSG SCCGMSG;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "LNOT5100 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "LNB5100_AWA_5100>");
        LNB5100_AWA_5100 = (LNB5100_AWA_5100) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        SCCGMSG = (SCCGMSG) GWA_SC_AREA.MSG_AREA_PTR;
        SCCGAPV = (SCCGAPV) GWA_SC_AREA.APVL_AREA_PTR;
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B010_CHECK_INPUT();
        B020_TRANCHE_MAIN_PROC();
    }
    public void B010_CHECK_INPUT() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, LNB5100_AWA_5100);
        CEP.TRC(SCCGWA, LNB5100_AWA_5100.CONT_NO);
        if (LNB5100_AWA_5100.CONT_NO.trim().length() == 0) {
            WS_MSGID = LNCMSG_ERROR_MSG.LN_CONT_NO_MUST_INPUT;
            if (LNB5100_AWA_5100.CONT_NO.trim().length() == 0) WS_FLD_NO = 0;
            else WS_FLD_NO = Short.parseShort(LNB5100_AWA_5100.CONT_NO);
            S000_ERR_MSG_PROC();
        }
        if (LNB5100_AWA_5100.FUN_CD == ' ') {
            WS_MSGID = LNCMSG_ERROR_MSG.LN_CONT_TYPE_MUST_INPUT;
            if (LNB5100_AWA_5100.FUN_CD == ' ') WS_FLD_NO = 0;
            else WS_FLD_NO = Short.parseShort(""+LNB5100_AWA_5100.FUN_CD);
            S000_ERR_MSG_PROC();
        }
    }
    public void B020_TRANCHE_MAIN_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCSSETL);
        LNCSSETL.CONTRACT_ATTR = LNB5100_AWA_5100.FUN_CD;
        LNCSSETL.CONTRACT_NO = LNB5100_AWA_5100.CONT_NO;
        LNCSSETL.CCY = LNB5100_AWA_5100.CCY;
        LNCSSETL.MWHD_AC_FLG = LNB5100_AWA_5100.MWHD_FLG;
        LNCSSETL.AC_TYP = LNB5100_AWA_5100.AC_TYP;
        LNCSSETL.AC = LNB5100_AWA_5100.AC_NO;
        LNCSSETL.CCY_TYP = LNB5100_AWA_5100.CCY_TYP;
        LNCSSETL.AC_FLG = LNB5100_AWA_5100.AC_FLG;
        LNCSSETL.PART_BK = LNB5100_AWA_5100.PART_BK;
        LNCSSETL.CI_TYPE = LNB5100_AWA_5100.CI_TYPE;
        LNCSSETL.SETTLE_TYPE = LNB5100_AWA_5100.STL_TYP;
        LNCSSETL.AC_NM = LNB5100_AWA_5100.AC_NM;
        LNCSSETL.REMARK = LNB5100_AWA_5100.REMARK;
        LNCSSETL.AC_DATA[1-1].STL_ACTYP = LNB5100_AWA_5100.AC_DATA[1-1].S_ACTYP;
        LNCSSETL.AC_DATA[1-1].STL_AC = LNB5100_AWA_5100.AC_DATA[1-1].S_AC;
        LNCSSETL.AC_DATA[1-1].STL_PAR_BK = LNB5100_AWA_5100.AC_DATA[1-1].S_PAR_BK;
        LNCSSETL.AC_DATA[1-1].STL_CI_TP = LNB5100_AWA_5100.AC_DATA[1-1].S_CI_TP;
        LNCSSETL.AC_DATA[1-1].STL_STL_TP = LNB5100_AWA_5100.AC_DATA[1-1].S_STL_TP;
        LNCSSETL.AC_DATA[1-1].STL_CCY_TYP = LNB5100_AWA_5100.AC_DATA[1-1].S_C_TYP;
        LNCSSETL.AC_DATA[1-1].STL_AC_FLG = LNB5100_AWA_5100.AC_DATA[1-1].S_AC_FLG;
        LNCSSETL.AC_DATA[1-1].STL_AC_NM = LNB5100_AWA_5100.AC_DATA[1-1].S_AC_NM;
        CEP.TRC(SCCGWA, LNCSSETL.AC_DATA[1-1].STL_ACTYP);
        CEP.TRC(SCCGWA, LNCSSETL.AC_DATA[1-1].STL_AC);
        CEP.TRC(SCCGWA, LNCSSETL.AC_DATA[1-1].STL_PAR_BK);
        CEP.TRC(SCCGWA, LNCSSETL.AC_DATA[1-1].STL_CI_TP);
        CEP.TRC(SCCGWA, LNCSSETL.AC_DATA[1-1].STL_STL_TP);
        CEP.TRC(SCCGWA, LNCSSETL.AC_DATA[1-1].STL_CCY_TYP);
        CEP.TRC(SCCGWA, LNCSSETL.AC_DATA[1-1].STL_AC_FLG);
        CEP.TRC(SCCGWA, LNCSSETL.AC_DATA[1-1].STL_AC_NM);
        LNCSSETL.AC_DATA[2-1].STL_ACTYP = LNB5100_AWA_5100.AC_DATA[2-1].S_ACTYP;
        LNCSSETL.AC_DATA[2-1].STL_AC = LNB5100_AWA_5100.AC_DATA[2-1].S_AC;
        LNCSSETL.AC_DATA[2-1].STL_PAR_BK = LNB5100_AWA_5100.AC_DATA[2-1].S_PAR_BK;
        LNCSSETL.AC_DATA[2-1].STL_CI_TP = LNB5100_AWA_5100.AC_DATA[2-1].S_CI_TP;
        LNCSSETL.AC_DATA[2-1].STL_STL_TP = LNB5100_AWA_5100.AC_DATA[2-1].S_STL_TP;
        LNCSSETL.AC_DATA[2-1].STL_CCY_TYP = LNB5100_AWA_5100.AC_DATA[2-1].S_C_TYP;
        LNCSSETL.AC_DATA[2-1].STL_AC_FLG = LNB5100_AWA_5100.AC_DATA[2-1].S_AC_FLG;
        LNCSSETL.AC_DATA[2-1].STL_AC_NM = LNB5100_AWA_5100.AC_DATA[2-1].S_AC_NM;
        LNCSSETL.AC_DATA[3-1].STL_ACTYP = LNB5100_AWA_5100.AC_DATA[3-1].S_ACTYP;
        LNCSSETL.AC_DATA[3-1].STL_AC = LNB5100_AWA_5100.AC_DATA[3-1].S_AC;
        LNCSSETL.AC_DATA[3-1].STL_PAR_BK = LNB5100_AWA_5100.AC_DATA[3-1].S_PAR_BK;
        LNCSSETL.AC_DATA[3-1].STL_CI_TP = LNB5100_AWA_5100.AC_DATA[3-1].S_CI_TP;
        LNCSSETL.AC_DATA[3-1].STL_STL_TP = LNB5100_AWA_5100.AC_DATA[3-1].S_STL_TP;
        LNCSSETL.AC_DATA[3-1].STL_CCY_TYP = LNB5100_AWA_5100.AC_DATA[3-1].S_C_TYP;
        LNCSSETL.AC_DATA[3-1].STL_AC_FLG = LNB5100_AWA_5100.AC_DATA[3-1].S_AC_FLG;
        LNCSSETL.AC_DATA[3-1].STL_AC_NM = LNB5100_AWA_5100.AC_DATA[3-1].S_AC_NM;
        LNCSSETL.AC_DATA[4-1].STL_ACTYP = LNB5100_AWA_5100.AC_DATA[4-1].S_ACTYP;
        LNCSSETL.AC_DATA[4-1].STL_AC = LNB5100_AWA_5100.AC_DATA[4-1].S_AC;
        LNCSSETL.AC_DATA[4-1].STL_PAR_BK = LNB5100_AWA_5100.AC_DATA[4-1].S_PAR_BK;
        LNCSSETL.AC_DATA[4-1].STL_CI_TP = LNB5100_AWA_5100.AC_DATA[4-1].S_CI_TP;
        LNCSSETL.AC_DATA[4-1].STL_STL_TP = LNB5100_AWA_5100.AC_DATA[4-1].S_STL_TP;
        LNCSSETL.AC_DATA[4-1].STL_CCY_TYP = LNB5100_AWA_5100.AC_DATA[4-1].S_C_TYP;
        LNCSSETL.AC_DATA[4-1].STL_AC_FLG = LNB5100_AWA_5100.AC_DATA[4-1].S_AC_FLG;
        LNCSSETL.AC_DATA[4-1].STL_AC_NM = LNB5100_AWA_5100.AC_DATA[4-1].S_AC_NM;
        S000_CALL_LNZSSETL();
    }
    public void S000_CALL_LNZSSETL() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-SRV-LNZSSETL", LNCSSETL);
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_MSGID, WS_FLD_NO);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
