package com.hisun.LN;

import com.hisun.SC.*;
import com.hisun.CI.*;

import java.io.IOException;
import java.sql.SQLException;

public class LNOT4210 {
    brParm LNTTRAN_BR = new brParm();
    LNOT4210_WS_VARIABLES WS_VARIABLES = new LNOT4210_WS_VARIABLES();
    LNOT4210_WS_OUT_RECODE WS_OUT_RECODE = new LNOT4210_WS_OUT_RECODE();
    LNCMSG_ERROR_MSG ERROR_MSG = new LNCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    LNRTRAN LNRTRAN = new LNRTRAN();
    SCCFMT SCCFMT = new SCCFMT();
    LNC4210 LNC4210 = new LNC4210();
    CICACCU CICACCU = new CICACCU();
    SCCGWA SCCGWA;
    LNCI4210 LNCI4210;
    LNB4210_AWA_4210 AWA_4210;
    SCCGSCA_SC_AREA SC_AREA;
    SCCGBPA_BP_AREA BP_AREA;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "LNOT4210 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        AWA_4210 = new LNB4210_AWA_4210();
        IBS.init(SCCGWA, AWA_4210);
        IBS.CPY2CLS(SCCGWA, SCCGWA.COMM_AREA.AWA_AREA_PTR, AWA_4210);
        BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        IBS.init(SCCGWA, WS_VARIABLES);
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B100_CHECK_INPUT();
        B200_DETAIL_ENQUIRY();
    }
    public void B100_CHECK_INPUT() throws IOException,SQLException,Exception {
        if (AWA_4210.TR_VALDT == 0) {
            WS_VARIABLES.ERR_MSG = ERROR_MSG.M_TR_VALDT_MUST_INPUT;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        if (AWA_4210.TR_DTE == 0) {
            WS_VARIABLES.ERR_MSG = ERROR_MSG.M_TR_DTE_MUST_INPUT;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        if (AWA_4210.TR_JRNNO == 0) {
            WS_VARIABLES.ERR_MSG = ERROR_MSG.M_TR_JRNNO_MUST_INPUT;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        if (AWA_4210.DUE_DT == 0) {
            WS_VARIABLES.ERR_MSG = ERROR_MSG.M_DUE_DT_MUST_INPUT;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        if (AWA_4210.TR_BR == 0) {
            WS_VARIABLES.ERR_MSG = ERROR_MSG.M_TR_BR_MUST_NPUT;
            S000_ERR_MSG_PROC_CONTINUE();
        }
    }
    public void B200_DETAIL_ENQUIRY() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNC4210);
        LNC4210.COMM_DATA.TRAN_INFO.DEL_FLG = AWA_4210.DEL_FLG;
        LNC4210.COMM_DATA.TRAN_INFO.TR_VALDT = AWA_4210.TR_VALDT;
        LNC4210.COMM_DATA.TRAN_INFO.TR_DTE = AWA_4210.TR_DTE;
        LNC4210.COMM_DATA.TRAN_INFO.TR_JRNNO = AWA_4210.TR_JRNNO;
        LNC4210.COMM_DATA.TRAN_INFO.TXN_TERM = AWA_4210.TXN_TERM;
        LNC4210.COMM_DATA.TRAN_INFO.DUE_DT = AWA_4210.DUE_DT;
        LNC4210.COMM_DATA.TRAN_INFO.P_AMT = AWA_4210.P_AMT;
        LNC4210.COMM_DATA.TRAN_INFO.I_AMT = AWA_4210.I_AMT;
        LNC4210.COMM_DATA.TRAN_INFO.O_AMT = AWA_4210.O_AMT;
        LNC4210.COMM_DATA.TRAN_INFO.L_AMT = AWA_4210.L_AMT;
        LNC4210.COMM_DATA.TRAN_INFO.PC_AMT = AWA_4210.PC_AMT;
        LNC4210.COMM_DATA.TRAN_INFO.F_AMT = AWA_4210.F_AMT;
        LNC4210.COMM_DATA.TRAN_INFO.OS_BAL = AWA_4210.OS_BAL;
        LNC4210.COMM_DATA.TRAN_INFO.REQ_FRM_NO = AWA_4210.REQ_SYS;
        LNC4210.COMM_DATA.TRAN_INFO.PAY_METH = AWA_4210.PAY_METH;
        LNC4210.COMM_DATA.TRAN_INFO.TR_BR = AWA_4210.TR_BR;
        B210_STARTREAD();
        B211_READNEXT_LNTTRAN();
        B220_OUTPUT();
    }
    public void B210_STARTREAD() throws IOException,SQLException,Exception {
        WS_VARIABLES.DEL_FLG = LNC4210.COMM_DATA.TRAN_INFO.DEL_FLG;
        CEP.TRC(SCCGWA, WS_VARIABLES.DEL_FLG);
        WS_VARIABLES.TR_VALDT = LNC4210.COMM_DATA.TRAN_INFO.TR_VALDT;
        CEP.TRC(SCCGWA, WS_VARIABLES.TR_VALDT);
        WS_VARIABLES.TR_DTE = LNC4210.COMM_DATA.TRAN_INFO.TR_DTE;
        CEP.TRC(SCCGWA, WS_VARIABLES.TR_DTE);
        WS_VARIABLES.TR_JRNNO = LNC4210.COMM_DATA.TRAN_INFO.TR_JRNNO;
        CEP.TRC(SCCGWA, WS_VARIABLES.TR_JRNNO);
        WS_VARIABLES.TXN_TERM = LNC4210.COMM_DATA.TRAN_INFO.TXN_TERM;
        CEP.TRC(SCCGWA, WS_VARIABLES.TXN_TERM);
        WS_VARIABLES.DUE_DT = LNC4210.COMM_DATA.TRAN_INFO.DUE_DT;
        CEP.TRC(SCCGWA, WS_VARIABLES.DUE_DT);
        WS_VARIABLES.P_AMT = LNC4210.COMM_DATA.TRAN_INFO.P_AMT;
        CEP.TRC(SCCGWA, WS_VARIABLES.P_AMT);
        WS_VARIABLES.I_AMT = LNC4210.COMM_DATA.TRAN_INFO.I_AMT;
        CEP.TRC(SCCGWA, WS_VARIABLES.I_AMT);
        WS_VARIABLES.O_AMT = LNC4210.COMM_DATA.TRAN_INFO.O_AMT;
        CEP.TRC(SCCGWA, WS_VARIABLES.O_AMT);
        WS_VARIABLES.L_AMT = LNC4210.COMM_DATA.TRAN_INFO.L_AMT;
        CEP.TRC(SCCGWA, WS_VARIABLES.L_AMT);
        WS_VARIABLES.PC_AMT = LNC4210.COMM_DATA.TRAN_INFO.PC_AMT;
        CEP.TRC(SCCGWA, WS_VARIABLES.PC_AMT);
        WS_VARIABLES.F_AMT = LNC4210.COMM_DATA.TRAN_INFO.F_AMT;
        CEP.TRC(SCCGWA, WS_VARIABLES.F_AMT);
        WS_VARIABLES.OS_BAL = LNC4210.COMM_DATA.TRAN_INFO.OS_BAL;
        CEP.TRC(SCCGWA, WS_VARIABLES.OS_BAL);
        WS_VARIABLES.REQ_FRM_NO = LNC4210.COMM_DATA.TRAN_INFO.REQ_FRM_NO;
        CEP.TRC(SCCGWA, WS_VARIABLES.REQ_FRM_NO);
        WS_VARIABLES.PAY_METH = LNC4210.COMM_DATA.TRAN_INFO.PAY_METH;
        CEP.TRC(SCCGWA, WS_VARIABLES.PAY_METH);
        WS_VARIABLES.TR_BR = LNC4210.COMM_DATA.TRAN_INFO.TR_BR;
        CEP.TRC(SCCGWA, WS_VARIABLES.TR_BR);
        CEP.TRC(SCCGWA, WS_VARIABLES.TR_VALDT);
        CEP.TRC(SCCGWA, WS_VARIABLES.TR_DTE);
        CEP.TRC(SCCGWA, WS_VARIABLES.TR_JRNNO);
        CEP.TRC(SCCGWA, WS_VARIABLES.DUE_DT);
        CEP.TRC(SCCGWA, WS_VARIABLES.TR_BR);
        LNTTRAN_BR.rp = new DBParm();
        LNTTRAN_BR.rp.TableName = "LNTTRAN";
        LNTTRAN_BR.rp.where = "TR_VAL_DTE = :WS_VARIABLES.TR_VALDT "
            + "AND TR_DATE = :WS_VARIABLES.TR_DTE "
            + "AND TR_JRN_NO = :WS_VARIABLES.TR_JRNNO "
            + "AND DUE_DT = :WS_VARIABLES.DUE_DT "
            + "AND TR_BR = :WS_VARIABLES.TR_BR";
        IBS.STARTBR(SCCGWA, LNRTRAN, this, LNTTRAN_BR);
        CEP.TRC(SCCGWA, LNRTRAN.PAY_AC1);
        CEP.TRC(SCCGWA, LNRTRAN.PAY_AC2);
    }
    public void B211_READNEXT_LNTTRAN() throws IOException,SQLException,Exception {
        IBS.READNEXT(SCCGWA, LNRTRAN, this, LNTTRAN_BR);
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.DBIO_FLG);
    }
    public void B220_OUTPUT() throws IOException,SQLException,Exception {
        WS_VARIABLES.PAY_AC1 = LNRTRAN.PAY_AC1;
        WS_VARIABLES.PAY_AC2 = LNRTRAN.PAY_AC2;
        WS_VARIABLES.PAY_AC3 = LNRTRAN.PAY_AC3;
        WS_VARIABLES.PAY_AC4 = LNRTRAN.PAY_AC4;
        WS_VARIABLES.PAY_AC5 = LNRTRAN.PAY_AC5;
        B222_GET_DD_INFO();
        WS_OUT_RECODE.WS_OUT_HEAD.O_DEL_FLG = WS_VARIABLES.DEL_FLG;
        WS_OUT_RECODE.WS_OUT_HEAD.O_TR_VALDT = WS_VARIABLES.TR_VALDT;
        WS_OUT_RECODE.WS_OUT_HEAD.O_TR_DTE = WS_VARIABLES.TR_DTE;
        WS_OUT_RECODE.WS_OUT_HEAD.O_TR_JRNNO = WS_VARIABLES.TR_JRNNO;
        WS_OUT_RECODE.WS_OUT_HEAD.O_DUE_DT = WS_VARIABLES.DUE_DT;
        WS_OUT_RECODE.WS_OUT_HEAD.O_TXN_TERM = WS_VARIABLES.TXN_TERM;
        WS_OUT_RECODE.WS_OUT_HEAD.O_P_AMT = WS_VARIABLES.P_AMT;
        WS_OUT_RECODE.WS_OUT_HEAD.O_I_AMT = WS_VARIABLES.I_AMT;
        WS_OUT_RECODE.WS_OUT_HEAD.O_O_AMT = WS_VARIABLES.O_AMT;
        WS_OUT_RECODE.WS_OUT_HEAD.O_L_AMT = WS_VARIABLES.L_AMT;
        WS_OUT_RECODE.WS_OUT_HEAD.O_PC_AMT = WS_VARIABLES.PC_AMT;
        WS_OUT_RECODE.WS_OUT_HEAD.O_F_AMT = WS_VARIABLES.F_AMT;
        WS_OUT_RECODE.WS_OUT_HEAD.O_OS_BAL = WS_VARIABLES.OS_BAL;
        WS_OUT_RECODE.WS_OUT_HEAD.O_REQ_FRM_NO = WS_VARIABLES.REQ_FRM_NO;
        WS_OUT_RECODE.WS_OUT_HEAD.O_PAY_METH = WS_VARIABLES.PAY_METH;
        WS_OUT_RECODE.WS_OUT_HEAD.O_TR_BR = WS_VARIABLES.TR_BR;
        WS_OUT_RECODE.WS_OUT_HEAD.O_AC_FLG1 = LNRTRAN.AC_FLG1;
        WS_OUT_RECODE.WS_OUT_HEAD.O_AC_TYP1 = LNRTRAN.AC_TYP1;
        WS_OUT_RECODE.WS_OUT_HEAD.O_PAY_AC1 = LNRTRAN.PAY_AC1;
        WS_OUT_RECODE.WS_OUT_HEAD.O_PAY_AC_NAM1 = WS_VARIABLES.PAY_AC_NAM1;
        WS_OUT_RECODE.WS_OUT_HEAD.O_AC_FLG2 = LNRTRAN.AC_FLG2;
        WS_OUT_RECODE.WS_OUT_HEAD.O_AC_TYP2 = LNRTRAN.AC_TYP2;
        WS_OUT_RECODE.WS_OUT_HEAD.O_PAY_AC2 = LNRTRAN.PAY_AC2;
        WS_OUT_RECODE.WS_OUT_HEAD.O_PAY_AC_NAM2 = WS_VARIABLES.PAY_AC_NAM2;
        WS_OUT_RECODE.WS_OUT_HEAD.O_AC_FLG3 = LNRTRAN.AC_FLG3;
        WS_OUT_RECODE.WS_OUT_HEAD.O_AC_TYP3 = LNRTRAN.AC_TYP3;
        WS_OUT_RECODE.WS_OUT_HEAD.O_PAY_AC3 = LNRTRAN.PAY_AC3;
        WS_OUT_RECODE.WS_OUT_HEAD.O_PAY_AC_NAM3 = WS_VARIABLES.PAY_AC_NAM3;
        WS_OUT_RECODE.WS_OUT_HEAD.O_AC_FLG4 = LNRTRAN.AC_FLG4;
        WS_OUT_RECODE.WS_OUT_HEAD.O_AC_TYP4 = LNRTRAN.AC_TYP4;
        WS_OUT_RECODE.WS_OUT_HEAD.O_PAY_AC4 = LNRTRAN.PAY_AC4;
        WS_OUT_RECODE.WS_OUT_HEAD.O_PAY_AC_NAM4 = WS_VARIABLES.PAY_AC_NAM4;
        WS_OUT_RECODE.WS_OUT_HEAD.O_AC_FLG5 = LNRTRAN.AC_FLG5;
        WS_OUT_RECODE.WS_OUT_HEAD.O_AC_TYP5 = LNRTRAN.AC_TYP5;
        WS_OUT_RECODE.WS_OUT_HEAD.O_PAY_AC5 = LNRTRAN.PAY_AC5;
        WS_OUT_RECODE.WS_OUT_HEAD.O_PAY_AC_NAM5 = WS_VARIABLES.PAY_AC_NAM5;
        IBS.init(SCCGWA, SCCFMT);
        SCCFMT.FMTID = "LN421";
        SCCFMT.DATA_PTR = WS_OUT_RECODE;
        CEP.TRC(SCCGWA, "20180524TEST");
        SCCFMT.DATA_LEN = 1610;
        IBS.FMT(SCCGWA, SCCFMT);
    }
    public void B222_GET_DD_INFO() throws IOException,SQLException,Exception {
        WS_VARIABLES.AC_NO1 = WS_VARIABLES.PAY_AC1;
        WS_VARIABLES.AC_NO2 = WS_VARIABLES.PAY_AC2;
        WS_VARIABLES.AC_NO3 = WS_VARIABLES.PAY_AC3;
        WS_VARIABLES.AC_NO4 = WS_VARIABLES.PAY_AC4;
        WS_VARIABLES.AC_NO5 = WS_VARIABLES.PAY_AC5;
        IBS.init(SCCGWA, CICACCU);
        CICACCU.DATA.AGR_NO = WS_VARIABLES.AC_NO1;
        CICACCU.DATA.ENTY_TYP = '1';
        if (CICACCU.DATA.AGR_NO.trim().length() > 0) {
            S000_CALL_CIZACCU();
            WS_VARIABLES.PAY_AC_NAM1 = CICACCU.DATA.CI_CNM;
        }
        IBS.init(SCCGWA, CICACCU);
        CICACCU.DATA.AGR_NO = WS_VARIABLES.AC_NO2;
        CICACCU.DATA.ENTY_TYP = '1';
        if (CICACCU.DATA.AGR_NO.trim().length() > 0) {
            S000_CALL_CIZACCU();
            WS_VARIABLES.PAY_AC_NAM2 = CICACCU.DATA.CI_CNM;
        }
        IBS.init(SCCGWA, CICACCU);
        CICACCU.DATA.AGR_NO = WS_VARIABLES.AC_NO3;
        CICACCU.DATA.ENTY_TYP = '1';
        if (CICACCU.DATA.AGR_NO.trim().length() > 0) {
            S000_CALL_CIZACCU();
            WS_VARIABLES.PAY_AC_NAM3 = CICACCU.DATA.CI_CNM;
        }
        IBS.init(SCCGWA, CICACCU);
        CICACCU.DATA.AGR_NO = WS_VARIABLES.AC_NO4;
        CICACCU.DATA.ENTY_TYP = '1';
        if (CICACCU.DATA.AGR_NO.trim().length() > 0) {
            S000_CALL_CIZACCU();
            WS_VARIABLES.PAY_AC_NAM4 = CICACCU.DATA.CI_CNM;
        }
        IBS.init(SCCGWA, CICACCU);
        CICACCU.DATA.AGR_NO = WS_VARIABLES.AC_NO5;
        CICACCU.DATA.ENTY_TYP = '1';
        if (CICACCU.DATA.AGR_NO.trim().length() > 0) {
            S000_CALL_CIZACCU();
            WS_VARIABLES.PAY_AC_NAM5 = CICACCU.DATA.CI_CNM;
        }
    }
    public void S000_CALL_CIZACCU() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "CI-INQ-ACCU", CICACCU);
    }
    public void S000_ERR_MSG_PROC_CONTINUE() throws IOException,SQLException,Exception {
        CEP.ERRC(SCCGWA, WS_VARIABLES.ERR_MSG);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
