package com.hisun.LN;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;
import com.hisun.CI.*;
import com.hisun.BP.*;

import java.io.IOException;
import java.sql.SQLException;

public class LNOT9122 {
    String JIBS_NumStr;
    String WS_MSGID = " ";
    String WS_ERR_INFO = " ";
    short WS_FLD_NO = 0;
    LNOT9122_WS_OUT_COMM_DATA WS_OUT_COMM_DATA = new LNOT9122_WS_OUT_COMM_DATA();
    LNCMSG_ERROR_MSG LNCMSG_ERROR_MSG = new LNCMSG_ERROR_MSG();
    SCCWOUT SCCWOUT = new SCCWOUT();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    SCCMPAG SCCMPAG = new SCCMPAG();
    SCCFMT SCCFMT = new SCCFMT();
    LNCOWLAD LNCOWLAD = new LNCOWLAD();
    LNCSDDRW LNCSDDRW = new LNCSDDRW();
    CICCUST CICCUST = new CICCUST();
    CICACCU CICACCU = new CICACCU();
    CICSSTC CICSSTC = new CICSSTC();
    BPCPFHIS BPCPFHIS = new BPCPFHIS();
    LNCIHDCK LNCIHDCK = new LNCIHDCK();
    LNRCONT LNRCONT = new LNRCONT();
    LNCRCONT LNCRCONT = new LNCRCONT();
    LNCPPMQ LNCPPMQ = new LNCPPMQ();
    SCCGWA SCCGWA;
    LNB9121_AWA_9121 LNB9121_AWA_9121;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    SCCGAPV SCCGAPV;
    SCCGMSG SCCGMSG;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "LNOT9122 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "LNB9121_AWA_9121>");
        LNB9121_AWA_9121 = (LNB9121_AWA_9121) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        SCCGMSG = (SCCGMSG) GWA_SC_AREA.MSG_AREA_PTR;
        SCCGAPV = (SCCGAPV) GWA_SC_AREA.APVL_AREA_PTR;
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B010_CHECK_INPUT();
        B030_CHECK_HOLIDAY();
        B020_TRANCHE_MAIN_PROC();
        B030_OUTPUT_PROC();
    }
    public void B010_CHECK_INPUT() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, LNB9121_AWA_9121);
        CEP.TRC(SCCGWA, LNB9121_AWA_9121.PAPER_NO);
        CEP.TRC(SCCGWA, LNB9121_AWA_9121.PAPER_DS);
        CEP.TRC(SCCGWA, LNB9121_AWA_9121.DRAW_NO);
        CEP.TRC(SCCGWA, LNB9121_AWA_9121.CONT_NO);
        CEP.TRC(SCCGWA, LNB9121_AWA_9121.BOOK_CRE);
        CEP.TRC(SCCGWA, LNB9121_AWA_9121.DOMI_BR);
        CEP.TRC(SCCGWA, LNB9121_AWA_9121.CI_NO);
        CEP.TRC(SCCGWA, LNB9121_AWA_9121.CI_CNM);
        CEP.TRC(SCCGWA, LNB9121_AWA_9121.PROD_TYP);
        CEP.TRC(SCCGWA, LNB9121_AWA_9121.PROD_NM);
        CEP.TRC(SCCGWA, LNB9121_AWA_9121.CCY);
        CEP.TRC(SCCGWA, LNB9121_AWA_9121.CONT_AMT);
        CEP.TRC(SCCGWA, LNB9121_AWA_9121.START_DT);
        CEP.TRC(SCCGWA, LNB9121_AWA_9121.MATU_DT);
        CEP.TRC(SCCGWA, LNB9121_AWA_9121.GUA_SEQ);
        CEP.TRC(SCCGWA, LNB9121_AWA_9121.GUARDUAP);
        CEP.TRC(SCCGWA, LNB9121_AWA_9121.GUARPSEQ);
        CEP.TRC(SCCGWA, LNB9121_AWA_9121.GRA_DAYA);
        CEP.TRC(SCCGWA, LNB9121_AWA_9121.GRA_PDFL);
        CEP.TRC(SCCGWA, LNB9121_AWA_9121.GRA_OI_T);
        CEP.TRC(SCCGWA, LNB9121_AWA_9121.GRA_LI_T);
        CEP.TRC(SCCGWA, LNB9121_AWA_9121.AUAL_TYP);
        CEP.TRC(SCCGWA, LNB9121_AWA_9121.INT_D_BA);
        CEP.TRC(SCCGWA, LNB9121_AWA_9121.REMARK1);
        if (LNB9121_AWA_9121.CONT_NO.trim().length() == 0) {
            WS_MSGID = LNCMSG_ERROR_MSG.LN_CONT_NO_MUST_INPUT;
            if (LNB9121_AWA_9121.CONT_NO.trim().length() == 0) WS_FLD_NO = 0;
            else WS_FLD_NO = Short.parseShort(LNB9121_AWA_9121.CONT_NO);
            S000_ERR_MSG_PROC_CONTINUE();
        }
        if (LNB9121_AWA_9121.START_DT == 0) {
            WS_MSGID = LNCMSG_ERROR_MSG.LN_ERR_START_DT_M_INPUT;
            WS_FLD_NO = (short) LNB9121_AWA_9121.START_DT;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        if (LNB9121_AWA_9121.MATU_DT == 0) {
            WS_MSGID = LNCMSG_ERROR_MSG.LN_ERR_DUE_DT_MUST_I;
            WS_FLD_NO = (short) LNB9121_AWA_9121.MATU_DT;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        if (LNB9121_AWA_9121.MATU_DT > 20991231) {
            WS_MSGID = LNCMSG_ERROR_MSG.LN_ERR_DT_MAX;
            WS_FLD_NO = (short) LNB9121_AWA_9121.MATU_DT;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        if (SCCGWA.COMM_AREA.MSG_PROC_AREA.MSG_TYPE == K_ERROR) {
            WS_MSGID = LNCMSG_ERROR_MSG.LN_ERR_INPUT;
            S000_ERR_MSG_PROC_LAST();
        }
        R00_CHECK_ERROR();
    }
    public void R00_CHECK_ERROR() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.MSG_PROC_AREA.MSG_TYPE);
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.MSG_PROC_AREA.MSG_ID.MSG_CODE);
        if (SCCGWA.COMM_AREA.MSG_PROC_AREA.MSG_TYPE == K_ERROR 
            && SCCGWA.COMM_AREA.MSG_PROC_AREA.MSG_ID.MSG_CODE == 0) {
            WS_MSGID = LNCMSG_ERROR_MSG.LN_ERR_MUST_INPUT;
            WS_FLD_NO = 0;
            S000_ERR_MSG_PROC();
        }
    }
    public void B020_TRANCHE_MAIN_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCSDDRW);
        LNCSDDRW.COMM_DATA.PAPER_NO = LNB9121_AWA_9121.PAPER_NO;
        LNCSDDRW.COMM_DATA.PAPER_DS = LNB9121_AWA_9121.PAPER_DS;
        LNCSDDRW.COMM_DATA.DRAW_NO = LNB9121_AWA_9121.DRAW_NO;
        LNCSDDRW.COMM_DATA.CONT_NO = LNB9121_AWA_9121.CONT_NO;
        LNCSDDRW.COMM_DATA.BOOK_BR = LNB9121_AWA_9121.BOOK_CRE;
        LNCSDDRW.COMM_DATA.DOMI_BR = LNB9121_AWA_9121.DOMI_BR;
        LNCSDDRW.COMM_DATA.CI_NO = LNB9121_AWA_9121.CI_NO;
        LNCSDDRW.COMM_DATA.CI_CNM = LNB9121_AWA_9121.CI_CNM;
        LNCSDDRW.COMM_DATA.PROD_TYP = LNB9121_AWA_9121.PROD_TYP;
        LNCSDDRW.COMM_DATA.PROD_NM = LNB9121_AWA_9121.PROD_NM;
        LNCSDDRW.COMM_DATA.CCY = LNB9121_AWA_9121.CCY;
        LNCSDDRW.COMM_DATA.CONT_AMT = LNB9121_AWA_9121.CONT_AMT;
        LNCSDDRW.COMM_DATA.START_DT = LNB9121_AWA_9121.START_DT;
        LNCSDDRW.COMM_DATA.MATU_DT = LNB9121_AWA_9121.MATU_DT;
        CEP.TRC(SCCGWA, LNB9121_AWA_9121.GUA_SEQ);
        LNCSDDRW.COMM_DATA.GUA_SEQ = LNB9121_AWA_9121.GUA_SEQ;
        LNCSDDRW.COMM_DATA.GUARDUAP = LNB9121_AWA_9121.GUARDUAP;
        LNCSDDRW.COMM_DATA.GUARPSEQ = LNB9121_AWA_9121.GUARPSEQ;
        LNCSDDRW.COMM_DATA.GRA_DAYA = LNB9121_AWA_9121.GRA_DAYA;
        LNCSDDRW.COMM_DATA.GRA_PDFL = LNB9121_AWA_9121.GRA_PDFL;
        LNCSDDRW.COMM_DATA.GRA_OI_T = LNB9121_AWA_9121.GRA_OI_T;
        LNCSDDRW.COMM_DATA.GRA_LI_T = LNB9121_AWA_9121.GRA_LI_T;
        LNCSDDRW.COMM_DATA.PRE_RATE = LNB9121_AWA_9121.PRE_RATE;
        LNCSDDRW.COMM_DATA.AUAL_TYP = LNB9121_AWA_9121.AUAL_TYP;
        LNCSDDRW.COMM_DATA.INT_D_BA = LNB9121_AWA_9121.INT_D_BA;
        LNCSDDRW.COMM_DATA.OLC_PERD = LNB9121_AWA_9121.OLC_PERD;
        JIBS_NumStr = "" + LNB9121_AWA_9121.OLC_PERD;
        LNCSDDRW.COMM_DATA.OLC_PERU = JIBS_NumStr.charAt(0);
        LNCSDDRW.COMM_DATA.REMARK1 = LNB9121_AWA_9121.REMARK1;
        LNCSDDRW.FUNC = 'U';
        S000_CALL_LNZSDDRW();
    }
    public void B030_CHECK_HOLIDAY() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNRCONT);
        IBS.init(SCCGWA, LNCRCONT);
        LNCRCONT.FUNC = 'I';
        LNRCONT.KEY.CONTRACT_NO = LNB9121_AWA_9121.CONT_NO;
        S000_CALL_LNZRCONT();
        IBS.init(SCCGWA, LNCPPMQ);
        LNCPPMQ.KEY.REQ_INSTRUCT.REQ_MODULE_PARM = 'N';
        LNCPPMQ.KEY.REQ_INSTRUCT.REQ_COMMIT_PARM = 'N';
        LNCPPMQ.KEY.REQ_INSTRUCT.REQ_CONTRACT_PARM = 'Y';
        LNCPPMQ.KEY.KEY_METH = 'C';
        LNCPPMQ.KEY.KEY_VALUE.LEVEL = 'D';
        LNCPPMQ.KEY.KEY_VALUE.CONTRACT_NO = LNB9121_AWA_9121.CONT_NO;
        S000_CALL_LNZPPMQ();
        CEP.TRC(SCCGWA, LNCPPMQ.DATA_TXT.HOL_FLAG);
        if (LNCPPMQ.DATA_TXT.HOL_FLAG == 'Y') {
            IBS.init(SCCGWA, LNCIHDCK);
            LNCIHDCK.INPUT_INFO.CONTRACT_NO = LNB9121_AWA_9121.CONT_NO;
            LNCIHDCK.INPUT_INFO.INPUT_DATE = LNB9121_AWA_9121.START_DT;
            LNCIHDCK.INPUT_INFO.CONTRACT_CCY = LNRCONT.CCY;
            LNCIHDCK.INPUT_INFO.BR = LNRCONT.BOOK_BR;
            LNCIHDCK.INPUT_INFO.RTN_WORKDAY = 'N';
            CEP.TRC(SCCGWA, LNCIHDCK.INPUT_INFO.CONTRACT_CCY);
            LNCIHDCK.INPUT_INFO.WARN_AUTH = 'A';
            S000_CALL_LNZIHDCK();
            IBS.init(SCCGWA, LNCIHDCK);
            LNCIHDCK.INPUT_INFO.CONTRACT_NO = LNB9121_AWA_9121.CONT_NO;
            LNCIHDCK.INPUT_INFO.INPUT_DATE = LNB9121_AWA_9121.MATU_DT;
            LNCIHDCK.INPUT_INFO.CONTRACT_CCY = LNRCONT.CCY;
            LNCIHDCK.INPUT_INFO.BR = LNRCONT.BOOK_BR;
            LNCIHDCK.INPUT_INFO.RTN_WORKDAY = 'N';
            CEP.TRC(SCCGWA, LNCIHDCK.INPUT_INFO.CONTRACT_CCY);
            LNCIHDCK.INPUT_INFO.WARN_AUTH = 'A';
            S000_CALL_LNZIHDCK();
        }
    }
    public void S000_CALL_LNZIHDCK() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-I-HOLDAY-CHK", LNCIHDCK);
    }
    public void S000_CALL_LNZSDDRW() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-SRV-LNZSDDRW", LNCSDDRW);
        if (LNCSDDRW.RC.RC_CODE != 0) {
            WS_MSGID = IBS.CLS2CPY(SCCGWA, LNCSDDRW.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void B030_OUTPUT_PROC() throws IOException,SQLException,Exception {
        WS_OUT_COMM_DATA.WS_OUT_CONT_NO = LNCSDDRW.COMM_DATA.CONT_NO;
        WS_OUT_COMM_DATA.WS_OUT_PAPER_NO = LNCSDDRW.COMM_DATA.PAPER_NO;
        WS_OUT_COMM_DATA.WS_OUT_PAPER_DS = LNCSDDRW.COMM_DATA.PAPER_DS;
        WS_OUT_COMM_DATA.WS_OUT_DRAW_NO = LNCSDDRW.COMM_DATA.DRAW_NO;
        WS_OUT_COMM_DATA.WS_OUT_BOOK_BR = LNCSDDRW.COMM_DATA.BOOK_BR;
        WS_OUT_COMM_DATA.WS_OUT_DOMI_BR = LNCSDDRW.COMM_DATA.DOMI_BR;
        WS_OUT_COMM_DATA.WS_OUT_CI_NO = LNCSDDRW.COMM_DATA.CI_NO;
        WS_OUT_COMM_DATA.WS_OUT_CI_CNM = LNCSDDRW.COMM_DATA.CI_CNM;
        WS_OUT_COMM_DATA.WS_OUT_PROD_TYP = LNCSDDRW.COMM_DATA.PROD_TYP;
        WS_OUT_COMM_DATA.WS_OUT_PROD_NM = LNCSDDRW.COMM_DATA.PROD_NM;
        WS_OUT_COMM_DATA.WS_OUT_CCY = LNCSDDRW.COMM_DATA.CCY;
        WS_OUT_COMM_DATA.WS_OUT_CONT_AMT = LNCSDDRW.COMM_DATA.CONT_AMT;
        WS_OUT_COMM_DATA.WS_OUT_START_DT = LNCSDDRW.COMM_DATA.START_DT;
        WS_OUT_COMM_DATA.WS_OUT_MATU_DT = LNCSDDRW.COMM_DATA.MATU_DT;
        WS_OUT_COMM_DATA.WS_OUT_GUA_SEQ = LNCSDDRW.COMM_DATA.GUA_SEQ;
        WS_OUT_COMM_DATA.WS_OUT_GUARDUAP = LNCSDDRW.COMM_DATA.GUARDUAP;
        WS_OUT_COMM_DATA.WS_OUT_GUARPSEQ = LNCSDDRW.COMM_DATA.GUARPSEQ;
        WS_OUT_COMM_DATA.WS_OUT_GRA_DAYA = LNCSDDRW.COMM_DATA.GRA_DAYA;
        WS_OUT_COMM_DATA.WS_OUT_GRA_PDFL = LNCSDDRW.COMM_DATA.GRA_PDFL;
        WS_OUT_COMM_DATA.WS_OUT_GRA_OI_T = LNCSDDRW.COMM_DATA.GRA_OI_T;
        WS_OUT_COMM_DATA.WS_OUT_GRA_LI_T = LNCSDDRW.COMM_DATA.GRA_LI_T;
        WS_OUT_COMM_DATA.WS_OUT_PRE_RATE = LNCSDDRW.COMM_DATA.PRE_RATE;
        WS_OUT_COMM_DATA.WS_OUT_AUAL_TYP = LNCSDDRW.COMM_DATA.AUAL_TYP;
        WS_OUT_COMM_DATA.WS_OUT_INT_D_BA = LNCSDDRW.COMM_DATA.INT_D_BA;
        WS_OUT_COMM_DATA.WS_OUT_OLC_PERD = LNCSDDRW.COMM_DATA.OLC_PERD;
        WS_OUT_COMM_DATA.WS_OUT_OLC_PERU = LNCSDDRW.COMM_DATA.OLC_PERU;
        WS_OUT_COMM_DATA.WS_OUT_REMARK1 = LNCSDDRW.COMM_DATA.REMARK1;
        CEP.TRC(SCCGWA, WS_OUT_COMM_DATA.WS_OUT_CONT_NO);
        CEP.TRC(SCCGWA, WS_OUT_COMM_DATA.WS_OUT_PAPER_NO);
        CEP.TRC(SCCGWA, WS_OUT_COMM_DATA.WS_OUT_PAPER_DS);
        CEP.TRC(SCCGWA, WS_OUT_COMM_DATA.WS_OUT_DRAW_NO);
        CEP.TRC(SCCGWA, WS_OUT_COMM_DATA.WS_OUT_CONT_NO);
        CEP.TRC(SCCGWA, WS_OUT_COMM_DATA.WS_OUT_BOOK_BR);
        CEP.TRC(SCCGWA, WS_OUT_COMM_DATA.WS_OUT_DOMI_BR);
        CEP.TRC(SCCGWA, WS_OUT_COMM_DATA.WS_OUT_CI_NO);
        CEP.TRC(SCCGWA, WS_OUT_COMM_DATA.WS_OUT_CI_CNM);
        CEP.TRC(SCCGWA, WS_OUT_COMM_DATA.WS_OUT_PROD_TYP);
        CEP.TRC(SCCGWA, WS_OUT_COMM_DATA.WS_OUT_PROD_NM);
        CEP.TRC(SCCGWA, WS_OUT_COMM_DATA.WS_OUT_CCY);
        CEP.TRC(SCCGWA, WS_OUT_COMM_DATA.WS_OUT_CONT_AMT);
        CEP.TRC(SCCGWA, WS_OUT_COMM_DATA.WS_OUT_START_DT);
        CEP.TRC(SCCGWA, WS_OUT_COMM_DATA.WS_OUT_MATU_DT);
        CEP.TRC(SCCGWA, WS_OUT_COMM_DATA.WS_OUT_GUA_SEQ);
        CEP.TRC(SCCGWA, WS_OUT_COMM_DATA.WS_OUT_GUARDUAP);
        CEP.TRC(SCCGWA, WS_OUT_COMM_DATA.WS_OUT_GUARPSEQ);
        CEP.TRC(SCCGWA, WS_OUT_COMM_DATA.WS_OUT_GRA_DAYA);
        CEP.TRC(SCCGWA, WS_OUT_COMM_DATA.WS_OUT_GRA_PDFL);
        CEP.TRC(SCCGWA, WS_OUT_COMM_DATA.WS_OUT_GRA_OI_T);
        CEP.TRC(SCCGWA, WS_OUT_COMM_DATA.WS_OUT_GRA_LI_T);
        CEP.TRC(SCCGWA, WS_OUT_COMM_DATA.WS_OUT_AUAL_TYP);
        CEP.TRC(SCCGWA, WS_OUT_COMM_DATA.WS_OUT_INT_D_BA);
        CEP.TRC(SCCGWA, WS_OUT_COMM_DATA.WS_OUT_REMARK1);
        IBS.init(SCCGWA, SCCFMT);
        SCCFMT.FMTID = "LNT83";
        SCCFMT.DATA_PTR = WS_OUT_COMM_DATA;
        SCCFMT.DATA_LEN = 954;
        IBS.FMT(SCCGWA, SCCFMT);
    }
    public void S000_CALL_LNZRCONT() throws IOException,SQLException,Exception {
        LNCRCONT.REC_PTR = LNRCONT;
        LNCRCONT.REC_LEN = 416;
        IBS.CALLCPN(SCCGWA, "LN-RSC-LNTCONT", LNCRCONT);
        if (LNCRCONT.RC.RC_CODE != 0) {
            WS_MSGID = IBS.CLS2CPY(SCCGWA, LNCRCONT.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_LNZPPMQ() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-FUN-PRD-PRM-INQ", LNCPPMQ);
        if (LNCPPMQ.RC.RC_RTNCODE != 0) {
            WS_MSGID = IBS.CLS2CPY(SCCGWA, LNCPPMQ.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_MSGID, WS_ERR_INFO, WS_FLD_NO);
    }
    public void S000_ERR_MSG_PROC_CONTINUE() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, WS_MSGID);
        CEP.ERRC(SCCGWA, WS_MSGID, WS_ERR_INFO, WS_FLD_NO);
    }
    public void S000_ERR_MSG_PROC_LAST() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_MSGID);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
