package com.hisun.LN;

import java.io.IOException;
import java.sql.SQLException;

import com.hisun.SC.SCCCALL;
import com.hisun.SC.SCCEXCP;
import com.hisun.SC.SCCGBPA_BP_AREA;
import com.hisun.SC.SCCGSCA_SC_AREA;
import com.hisun.SC.SCCGWA;
import com.hisun.SC.SCCMSG;

public class LNZ4100 {
    boolean pgmRtn = false;
    String WS_ERR_MSG = " ";
    short WS_FLD_NO = 0;
    int WS_K = 0;
    int WS_I = 0;
    short WS_FIX_TERM = 0;
    char WS_INT_MODE_FLAG = ' ';
    char WS_SYN_FLG_FLAG = ' ';
    char WS_FEE_FLG = ' ';
    LNCMSG_ERROR_MSG LNCMSG_ERROR_MSG = new LNCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    LNCSERRP LNCSPRRP = new LNCSERRP();
    LNCI4100 LNCI4100;
    SCCGWA SCCGWA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    public void MP(SCCGWA SCCGWA, LNCI4100 LNCI4100) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        this.LNCI4100 = LNCI4100;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        if (pgmRtn) return;
        B000_MAIN_PROC();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, "LNZ4100 return!");
        Z_RET();
        if (pgmRtn) return;
        JIBS_RETURN();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B020_EARLY_PAY_PROC();
        if (pgmRtn) return;
    }
    public void B020_EARLY_PAY_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCSPRRP);
        LNCSPRRP.CTA = LNCI4100.CTA_NO;
        LNCSPRRP.TR_VAL_DTE = LNCI4100.TR_VAL_D;
        LNCSPRRP.TOT_P_AMT = LNCI4100.TOT_P_AM;
        LNCSPRRP.INT_MODE = LNCI4100.INT_MODE;
        LNCSPRRP.PC_RATE = LNCI4100.PC_RATE;
        LNCSPRRP.TOT_I_AMT = LNCI4100.TOT_I_AM;
        LNCSPRRP.PC_AMT = LNCI4100.PC_AMT;
        LNCSPRRP.TOT_AMT = LNCI4100.TOT_AMT;
        LNCSPRRP.HRG_AMT = LNCI4100.HRG_AMT;
        LNCSPRRP.SYN_FLG = LNCI4100.SYN_FLG;
        if (LNCI4100.EE_TERM.trim().length() == 0) LNCSPRRP.S_TERM = 0;
        else LNCSPRRP.S_TERM = Short.parseShort(LNCI4100.EE_TERM);
        LNCSPRRP.RAT_MTH = LNCI4100.RAT_MTH;
        LNCSPRRP.INT_F_UN = LNCI4100.INT_F_UN;
        LNCSPRRP.INT_F_PD = LNCI4100.INT_F_PD;
        LNCSPRRP.FLT_IPER = LNCI4100.FLT_IPER;
        LNCSPRRP.FLT_ADJF = LNCI4100.FLT_ADJF;
        LNCSPRRP.FT_FLG = LNCI4100.FT_FLG;
        LNCSPRRP.FT_DAY = LNCI4100.FT_DAY;
        LNCSPRRP.FT_F_DAY = LNCI4100.FT_F_DAY;
        LNCSPRRP.FLT_MTH = LNCI4100.FT_MTH;
        LNCSPRRP.RATE_TYP = LNCI4100.RATE_TYP;
        LNCSPRRP.RATE_PD = LNCI4100.RATE_PD;
        LNCSPRRP.RATE_VAR = LNCI4100.RATE_VAR;
        LNCSPRRP.RATE_PCT = LNCI4100.RATE_PCT;
        LNCSPRRP.RATE_INT = LNCI4100.RATE_INT;
        LNCSPRRP.INT_RATE = LNCI4100.INT_RATE;
        LNCSPRRP.PEN_RRAT = LNCI4100.PEN_RRAT;
        LNCSPRRP.PEN_TYP = LNCI4100.PEN_TYP;
        LNCSPRRP.PEN_RATT = LNCI4100.PEN_RATT;
        LNCSPRRP.PEN_RATC = LNCI4100.PEN_RATC;
        LNCSPRRP.PEN_SPR = LNCI4100.PEN_SPR;
        LNCSPRRP.PEN_PCT = LNCI4100.PEN_PCT;
        LNCSPRRP.PEN_IRAT = LNCI4100.PEN_IRAT;
        LNCSPRRP.INT_MTH = LNCI4100.INT_MTH;
        LNCSPRRP.CPND_USE = LNCI4100.CPND_USE;
        LNCSPRRP.CPND_RTY = LNCI4100.CPND_RTY;
        LNCSPRRP.CPND_TYP = LNCI4100.CPND_TYP;
        LNCSPRRP.CPNDRATT = LNCI4100.CPNDRATT;
        LNCSPRRP.CPNDRATC = LNCI4100.CPNDRATC;
        LNCSPRRP.CPND_SPR = LNCI4100.CPND_SPR;
        LNCSPRRP.CPND_PCT = LNCI4100.CPND_PCT;
        LNCSPRRP.CPNDRATE = LNCI4100.CPNDRATE;
        LNCSPRRP.ABUS_RAT = LNCI4100.ABUS_RAT;
        LNCSPRRP.ABUS_TYP = LNCI4100.ABUS_TYP;
        LNCSPRRP.ABUSRATT = LNCI4100.ABUSRATT;
        LNCSPRRP.ABUSRATC = LNCI4100.ABUSRATC;
        LNCSPRRP.ABUSSPR = LNCI4100.ABUSSPR;
        LNCSPRRP.ABUSPCT = LNCI4100.ABUSPCT;
        LNCSPRRP.ABUSIRAT = LNCI4100.ABUSIRAT;
        LNCSPRRP.RPSP_NO = LNCI4100.CHK_NO;
        LNCSPRRP.METH = LNCI4100.CLN_CUT;
        if (SCCGWA.COMM_AREA.BSP_FLG.equalsIgnoreCase("BSP") 
            || SCCGWA.COMM_AREA.CHNL.equalsIgnoreCase("BAT")) {
            LNCSPRRP.TR_MMO = "12010003";
        } else {
            LNCSPRRP.TR_MMO = "12010002";
        }
        LNCSPRRP.MLT_STL = LNCI4100.MLT_STL;
        for (WS_K = 1; WS_K <= 5; WS_K += 1) {
            LNCSPRRP.ACAMT[WS_K-1].STL_MTH2 = LNCI4100.MULT_AC[WS_K-1].STL_MTH01;
            LNCSPRRP.ACAMT[WS_K-1].CHQ_NO2 = LNCI4100.MULT_AC[WS_K-1].CHQ_NO01;
            LNCSPRRP.ACAMT[WS_K-1].PAY_PSWD = LNCI4100.MULT_AC[WS_K-1].PAY_PSWD01;
            LNCSPRRP.ACAMT[WS_K-1].CHQ_TYPE = LNCI4100.MULT_AC[WS_K-1].CHQ_TYPE01;
            LNCSPRRP.ACAMT[WS_K-1].ISS_DATE = LNCI4100.MULT_AC[WS_K-1].ISS_DATE01;
            LNCSPRRP.ACAMT[WS_K-1].DEP_AC2 = LNCI4100.MULT_AC[WS_K-1].DEP_AC01;
            LNCSPRRP.ACAMT[WS_K-1].AC_FLG2 = LNCI4100.MULT_AC[WS_K-1].AC_FLG01;
            LNCSPRRP.ACAMT[WS_K-1].CI_CNM2 = LNCI4100.MULT_AC[WS_K-1].AC_CNM01;
            LNCSPRRP.ACAMT[WS_K-1].PAY_AMT2 = LNCI4100.MULT_AC[WS_K-1].PAY_AMT01;
            LNCSPRRP.ACAMT[WS_K-1].RVS_NO2 = LNCI4100.MULT_AC[WS_K-1].RVS_NO01;
            LNCSPRRP.ACAMT[WS_K-1].REC_CCY2 = LNCI4100.CCY;
            LNCSPRRP.ACAMT[WS_K-1].AMT_FRM2 = LNCI4100.MULT_AC[WS_K-1].AMT_FRM01;
            LNCSPRRP.FEE_INFO[WS_K-1].FEE_CD = LNCI4100.FEE_INF[WS_K-1].FEE_CODE01;
            LNCSPRRP.FEE_INFO[WS_K-1].FEE_AMT = LNCI4100.FEE_INF[WS_K-1].FEE_AMT01;
        }
        LNCSPRRP.FEE_TYP = LNCI4100.FEE_ACT;
        LNCSPRRP.FEE_AC = LNCI4100.FEE_AC;
        for (WS_K = 1; WS_K <= 10; WS_K += 1) {
            LNCSPRRP.SYLOAN_INFO[WS_K-1].SYLOAN_SEQ = "" + LNCI4100.PART_INF[WS_K-1].JOIN_NO01;
            JIBS_tmp_int = LNCSPRRP.SYLOAN_INFO[WS_K-1].SYLOAN_SEQ.length();
            for (int i=0;i<8-JIBS_tmp_int;i++) LNCSPRRP.SYLOAN_INFO[WS_K-1].SYLOAN_SEQ = "0" + LNCSPRRP.SYLOAN_INFO[WS_K-1].SYLOAN_SEQ;
            LNCSPRRP.SYLOAN_INFO[WS_K-1].SYLOAN_BR = LNCI4100.PART_INF[WS_K-1].JOIN_BR01;
            LNCSPRRP.SYLOAN_INFO[WS_K-1].SYLOAN_NAME = LNCI4100.PART_INF[WS_K-1].JOIN_NM01;
            LNCSPRRP.SYLOAN_INFO[WS_K-1].SYLOAN_FLG = LNCI4100.PART_INF[WS_K-1].I_O_FLG01;
            LNCSPRRP.SYLOAN_INFO[WS_K-1].SYLOAN_TYP = LNCI4100.PART_INF[WS_K-1].RLA_TYP01;
            LNCSPRRP.SYLOAN_INFO[WS_K-1].SYLOAN_P = LNCI4100.PART_INF[WS_K-1].PY_P_AMT01;
            LNCSPRRP.SYLOAN_INFO[WS_K-1].SYLOAN_I = LNCI4100.PART_INF[WS_K-1].PY_I_AMT01;
            LNCSPRRP.SYLOAN_INFO[WS_K-1].SYLOAN_W = LNCI4100.PART_INF[WS_K-1].PY_PC_AT01;
        }
        S000_CALL_LNZSPRRP();
        if (pgmRtn) return;
    }
    public void S000_CALL_LNZSPRRP() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-P-SPRRP", LNCSPRRP);
        if (LNCSPRRP.RC.RC_RTNCODE != 0) {
