package com.hisun.LN;

public class LNZENSCH_WS_OUT_RECODE {
    LNZENSCH_WS_OUT_HEAD WS_OUT_HEAD = new LNZENSCH_WS_OUT_HEAD();
    LNZENSCH_WS_OUT_INFO[] WS_OUT_INFO = new LNZENSCH_WS_OUT_INFO[25];
    LNZENSCH_WS_SCHT_VAR_AREA WS_SCHT_VAR_AREA = new LNZENSCH_WS_SCHT_VAR_AREA();
    public LNZENSCH_WS_OUT_RECODE() {
        for (int i=0;i<25;i++) WS_OUT_INFO[i] = new LNZENSCH_WS_OUT_INFO();
    }
}
