package com.hisun.LN;

public class LNZIGVCY_WS_TAX_DATAS {
    LNZIGVCY_WS_BEFTAX_DATA WS_BEFTAX_DATA = new LNZIGVCY_WS_BEFTAX_DATA();
    LNZIGVCY_WS_AFTTAX_DATA WS_AFTTAX_DATA = new LNZIGVCY_WS_AFTTAX_DATA();
    LNZIGVCY_WS_TRNTAX_DATA WS_TRNTAX_DATA = new LNZIGVCY_WS_TRNTAX_DATA();
}
