package com.hisun.LN;

public class LNZIPST_WS_ADJ_BK_AMT_INFO {
    LNZIPST_WS_ADJ_BK_AMT_NORMAL_INFO WS_ADJ_BK_AMT_NORMAL_INFO = new LNZIPST_WS_ADJ_BK_AMT_NORMAL_INFO();
    LNZIPST_WS_ADJ_BK_AMT_NON_STOP_INFO WS_ADJ_BK_AMT_NON_STOP_INFO = new LNZIPST_WS_ADJ_BK_AMT_NON_STOP_INFO();
}
