package com.hisun.LN;

import com.hisun.SC.*;

import java.io.IOException;
import java.sql.SQLException;

public class LNZRBALL {
    DBParm LNTBALZ_RD;
    boolean pgmRtn = false;
    LNRBALZ LNRBALZ = new LNRBALZ();
    LNCMSG_ERROR_MSG LNCMSG_ERROR_MSG = new LNCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    LNRBALL LNRBALL = new LNRBALL();
    SCCGWA SCCGWA;
    LNCRBALL LNCRBALL;
    LNRBALL LNRBALLA;
    public void MP(SCCGWA SCCGWA, LNCRBALL LNCRBALL) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        this.LNCRBALL = LNCRBALL;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        if (pgmRtn) return;
        B000_MAIN_PROC();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, "LNZRBALL return!");
        Z_RET();
        if (pgmRtn) return;
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        LNRBALLA = (LNRBALL) LNCRBALL.REC_PTR;
        LNCRBALL.RETURN_INFO = 'F';
        IBS.init(SCCGWA, LNRBALL);
        IBS.CLONE(SCCGWA, LNRBALLA, LNRBALL);
        LNCRBALL.RC.RC_MMO = "LN";
        LNCRBALL.RC.RC_CODE = 0;
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        if (LNCRBALL.FUNC == 'I') {
            B010_QUERY_RECORD_PROC();
            if (pgmRtn) return;
        } else if (LNCRBALL.FUNC == 'A') {
            B020_ADD_RECORD_PROC();
            if (pgmRtn) return;
        } else if (LNCRBALL.FUNC == 'R') {
            B030_READUPD_RECORD_PROC();
            if (pgmRtn) return;
        } else if (LNCRBALL.FUNC == 'U') {
            B040_UPDATE_RECORD_PROC();
            if (pgmRtn) return;
        } else if (LNCRBALL.FUNC == 'D') {
            B050_DELETE_RECORD_PROC();
            if (pgmRtn) return;
        } else {
            IBS.init(SCCGWA, SCCEXCP);
            SCCEXCP.MSG_TEXT.KEY_OR_OTHER = "INVALID FUNC(" + LNCRBALL.FUNC + ")";
            CEP.EXCP(SCCGWA, SCCEXCP.MSG_TEXT.KEY_OR_OTHER);
        }
        IBS.CLONE(SCCGWA, LNRBALL, LNRBALLA);
    }
    public void B010_QUERY_RECORD_PROC() throws IOException,SQLException,Exception {
        T000_READ_REC_PROC();
        if (pgmRtn) return;
    }
    public void B020_ADD_RECORD_PROC() throws IOException,SQLException,Exception {
        T000_WRITE_REC_PROC();
        if (pgmRtn) return;
    }
    public void B030_READUPD_RECORD_PROC() throws IOException,SQLException,Exception {
        T000_READ_UPDATE_PROC();
        if (pgmRtn) return;
    }
    public void B040_UPDATE_RECORD_PROC() throws IOException,SQLException,Exception {
        T000_REWRITE_REC_PROC();
        if (pgmRtn) return;
    }
    public void B050_DELETE_RECORD_PROC() throws IOException,SQLException,Exception {
        T000_DELETE_REC_PROC();
        if (pgmRtn) return;
    }
    public void T000_READ_REC_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNRBALZ);
        LNRBALZ.KEY.CONTRACT_NO = LNRBALL.KEY.CONTRACT_NO;
        LNRBALZ.KEY.SUB_CTA_NO = LNRBALL.KEY.SUB_CTA_NO;
        LNTBALZ_RD = new DBParm();
        LNTBALZ_RD.TableName = "LNTBALZ";
        IBS.READ(SCCGWA, LNRBALZ, LNTBALZ_RD);
        if (SCCGWA.COMM_AREA.DBIO_FLG == '1') {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_BALL_NOTFND, LNCRBALL.RC);
            LNCRBALL.RETURN_INFO = 'N';
            Z_RET();
            if (pgmRtn) return;
        }
        S000_BALZ_TO_BALL();
        if (pgmRtn) return;
    }
    public void S000_BALZ_TO_BALL() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNRBALL);
        LNRBALL.KEY.CONTRACT_NO = LNRBALZ.KEY.CONTRACT_NO;
        LNRBALL.KEY.SUB_CTA_NO = LNRBALZ.KEY.SUB_CTA_NO;
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[01-1].LOAN_BAL = LNRBALZ.LOAN_BALL01;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[02-1].LOAN_BAL = LNRBALZ.LOAN_BALL02;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[03-1].LOAN_BAL = LNRBALZ.LOAN_BALL03;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[04-1].LOAN_BAL = LNRBALZ.LOAN_BALL04;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[05-1].LOAN_BAL = LNRBALZ.LOAN_BALL05;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[06-1].LOAN_BAL = LNRBALZ.LOAN_BALL06;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[07-1].LOAN_BAL = LNRBALZ.LOAN_BALL07;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[08-1].LOAN_BAL = LNRBALZ.LOAN_BALL08;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[09-1].LOAN_BAL = LNRBALZ.LOAN_BALL09;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[10-1].LOAN_BAL = LNRBALZ.LOAN_BALL10;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[11-1].LOAN_BAL = LNRBALZ.LOAN_BALL11;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[12-1].LOAN_BAL = LNRBALZ.LOAN_BALL12;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[13-1].LOAN_BAL = LNRBALZ.LOAN_BALL13;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[14-1].LOAN_BAL = LNRBALZ.LOAN_BALL14;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[15-1].LOAN_BAL = LNRBALZ.LOAN_BALL15;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[16-1].LOAN_BAL = LNRBALZ.LOAN_BALL16;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[17-1].LOAN_BAL = LNRBALZ.LOAN_BALL17;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[18-1].LOAN_BAL = LNRBALZ.LOAN_BALL18;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[19-1].LOAN_BAL = LNRBALZ.LOAN_BALL19;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[20-1].LOAN_BAL = LNRBALZ.LOAN_BALL20;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[21-1].LOAN_BAL = LNRBALZ.LOAN_BALL21;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[22-1].LOAN_BAL = LNRBALZ.LOAN_BALL22;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[23-1].LOAN_BAL = LNRBALZ.LOAN_BALL23;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[24-1].LOAN_BAL = LNRBALZ.LOAN_BALL24;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[25-1].LOAN_BAL = LNRBALZ.LOAN_BALL25;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[26-1].LOAN_BAL = LNRBALZ.LOAN_BALL26;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[27-1].LOAN_BAL = LNRBALZ.LOAN_BALL27;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[28-1].LOAN_BAL = LNRBALZ.LOAN_BALL28;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[29-1].LOAN_BAL = LNRBALZ.LOAN_BALL29;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[30-1].LOAN_BAL = LNRBALZ.LOAN_BALL30;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[31-1].LOAN_BAL = LNRBALZ.LOAN_BALL31;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[32-1].LOAN_BAL = LNRBALZ.LOAN_BALL32;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[33-1].LOAN_BAL = LNRBALZ.LOAN_BALL33;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[34-1].LOAN_BAL = LNRBALZ.LOAN_BALL34;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[35-1].LOAN_BAL = LNRBALZ.LOAN_BALL35;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[36-1].LOAN_BAL = LNRBALZ.LOAN_BALL36;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[37-1].LOAN_BAL = LNRBALZ.LOAN_BALL37;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[38-1].LOAN_BAL = LNRBALZ.LOAN_BALL38;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[39-1].LOAN_BAL = LNRBALZ.LOAN_BALL39;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[40-1].LOAN_BAL = LNRBALZ.LOAN_BALL40;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[41-1].LOAN_BAL = LNRBALZ.LOAN_BALL41;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[42-1].LOAN_BAL = LNRBALZ.LOAN_BALL42;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[43-1].LOAN_BAL = LNRBALZ.LOAN_BALL43;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[44-1].LOAN_BAL = LNRBALZ.LOAN_BALL44;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[45-1].LOAN_BAL = LNRBALZ.LOAN_BALL45;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[46-1].LOAN_BAL = LNRBALZ.LOAN_BALL46;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[47-1].LOAN_BAL = LNRBALZ.LOAN_BALL47;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[48-1].LOAN_BAL = LNRBALZ.LOAN_BALL48;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[49-1].LOAN_BAL = LNRBALZ.LOAN_BALL49;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[50-1].LOAN_BAL = LNRBALZ.LOAN_BALL50;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[51-1].LOAN_BAL = LNRBALZ.LOAN_BALL51;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[52-1].LOAN_BAL = LNRBALZ.LOAN_BALL52;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[53-1].LOAN_BAL = LNRBALZ.LOAN_BALL53;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[54-1].LOAN_BAL = LNRBALZ.LOAN_BALL54;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[55-1].LOAN_BAL = LNRBALZ.LOAN_BALL55;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[56-1].LOAN_BAL = LNRBALZ.LOAN_BALL56;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[57-1].LOAN_BAL = LNRBALZ.LOAN_BALL57;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[58-1].LOAN_BAL = LNRBALZ.LOAN_BALL58;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[59-1].LOAN_BAL = LNRBALZ.LOAN_BALL59;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[60-1].LOAN_BAL = LNRBALZ.LOAN_BALL60;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[61-1].LOAN_BAL = LNRBALZ.LOAN_BALL61;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[62-1].LOAN_BAL = LNRBALZ.LOAN_BALL62;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[63-1].LOAN_BAL = LNRBALZ.LOAN_BALL63;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[64-1].LOAN_BAL = LNRBALZ.LOAN_BALL64;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[65-1].LOAN_BAL = LNRBALZ.LOAN_BALL65;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[66-1].LOAN_BAL = LNRBALZ.LOAN_BALL66;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[67-1].LOAN_BAL = LNRBALZ.LOAN_BALL67;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[68-1].LOAN_BAL = LNRBALZ.LOAN_BALL68;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[69-1].LOAN_BAL = LNRBALZ.LOAN_BALL69;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[70-1].LOAN_BAL = LNRBALZ.LOAN_BALL70;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[71-1].LOAN_BAL = LNRBALZ.LOAN_BALL71;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[72-1].LOAN_BAL = LNRBALZ.LOAN_BALL72;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[73-1].LOAN_BAL = LNRBALZ.LOAN_BALL73;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[74-1].LOAN_BAL = LNRBALZ.LOAN_BALL74;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[75-1].LOAN_BAL = LNRBALZ.LOAN_BALL75;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[76-1].LOAN_BAL = LNRBALZ.LOAN_BALL76;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[77-1].LOAN_BAL = LNRBALZ.LOAN_BALL77;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[78-1].LOAN_BAL = LNRBALZ.LOAN_BALL78;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[79-1].LOAN_BAL = LNRBALZ.LOAN_BALL79;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[80-1].LOAN_BAL = LNRBALZ.LOAN_BALL80;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[81-1].LOAN_BAL = LNRBALZ.LOAN_BALL81;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[82-1].LOAN_BAL = LNRBALZ.LOAN_BALL82;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[83-1].LOAN_BAL = LNRBALZ.LOAN_BALL83;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[84-1].LOAN_BAL = LNRBALZ.LOAN_BALL84;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[85-1].LOAN_BAL = LNRBALZ.LOAN_BALL85;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[86-1].LOAN_BAL = LNRBALZ.LOAN_BALL86;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[87-1].LOAN_BAL = LNRBALZ.LOAN_BALL87;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[88-1].LOAN_BAL = LNRBALZ.LOAN_BALL88;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[89-1].LOAN_BAL = LNRBALZ.LOAN_BALL89;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[90-1].LOAN_BAL = LNRBALZ.LOAN_BALL90;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[91-1].LOAN_BAL = LNRBALZ.LOAN_BALL91;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[92-1].LOAN_BAL = LNRBALZ.LOAN_BALL92;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[93-1].LOAN_BAL = LNRBALZ.LOAN_BALL93;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[94-1].LOAN_BAL = LNRBALZ.LOAN_BALL94;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[95-1].LOAN_BAL = LNRBALZ.LOAN_BALL95;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[96-1].LOAN_BAL = LNRBALZ.LOAN_BALL96;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[97-1].LOAN_BAL = LNRBALZ.LOAN_BALL97;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[98-1].LOAN_BAL = LNRBALZ.LOAN_BALL98;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[99-1].LOAN_BAL = LNRBALZ.LOAN_BALL99;
        LNRBALL.REDEFINES7.LOAN_CONT_AREA_TEXT1 = IBS.CLS2CPY(SCCGWA, LNRBALL.REDEFINES7.REDEFINES9);
        LNRBALL.CRT_DATE = LNRBALZ.CRT_DATE;
        LNRBALL.CRT_TLR = LNRBALZ.CRT_TLR;
        LNRBALL.UPDTBL_DATE = LNRBALZ.UPDTBL_DATE;
        LNRBALL.UPDTBL_TLR = LNRBALZ.UPDTBL_TLR;
        LNRBALL.TS = LNRBALZ.TS;
    }
    public void T000_WRITE_REC_PROC() throws IOException,SQLException,Exception {
        S000_BALL_TO_BALZ();
        if (pgmRtn) return;
        LNRBALZ.CRT_DATE = SCCGWA.COMM_AREA.AC_DATE;
        LNRBALZ.CRT_TLR = SCCGWA.COMM_AREA.TL_ID;
        LNRBALZ.UPDTBL_DATE = SCCGWA.COMM_AREA.AC_DATE;
        LNRBALZ.UPDTBL_TLR = SCCGWA.COMM_AREA.TL_ID;
        LNTBALZ_RD = new DBParm();
        LNTBALZ_RD.TableName = "LNTBALZ";
        LNTBALZ_RD.errhdl = true;
        IBS.WRITE(SCCGWA, LNRBALZ, LNTBALZ_RD);
        if (SCCGWA.COMM_AREA.DBIO_FLG == '2') {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_DUPKEY, LNCRBALL.RC);
            LNCRBALL.RETURN_INFO = 'D';
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void S000_BALL_TO_BALZ() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNRBALZ);
        LNRBALZ.KEY.CONTRACT_NO = LNRBALL.KEY.CONTRACT_NO;
        LNRBALZ.KEY.SUB_CTA_NO = LNRBALL.KEY.SUB_CTA_NO;
        LNRBALZ.LOAN_BALL01 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[01-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL02 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[02-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL03 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[03-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL04 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[04-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL05 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[05-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL06 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[06-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL07 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[07-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL08 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[08-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL09 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[09-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL10 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[10-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL11 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[11-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL12 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[12-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL13 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[13-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL14 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[14-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL15 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[15-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL16 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[16-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL17 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[17-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL18 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[18-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL19 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[19-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL20 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[20-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL21 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[21-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL22 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[22-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL23 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[23-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL24 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[24-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL25 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[25-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL26 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[26-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL27 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[27-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL28 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[28-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL29 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[29-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL30 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[30-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL31 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[31-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL32 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[32-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL33 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[33-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL34 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[34-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL35 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[35-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL36 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[36-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL37 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[37-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL38 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[38-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL39 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[39-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL40 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[40-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL41 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[41-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL42 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[42-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL43 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[43-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL44 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[44-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL45 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[45-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL46 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[46-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL47 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[47-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL48 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[48-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL49 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[49-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL50 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[50-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL51 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[51-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL52 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[52-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL53 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[53-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL54 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[54-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL55 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[55-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL56 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[56-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL57 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[57-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL58 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[58-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL59 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[59-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL60 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[60-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL61 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[61-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL62 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[62-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL63 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[63-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL64 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[64-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL65 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[65-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL66 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[66-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL67 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[67-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL68 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[68-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL69 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[69-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL70 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[70-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL71 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[71-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL72 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[72-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL73 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[73-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL74 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[74-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL75 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[75-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL76 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[76-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL77 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[77-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL78 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[78-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL79 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[79-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL80 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[80-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL81 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[81-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL82 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[82-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL83 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[83-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL84 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[84-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL85 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[85-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL86 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[86-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL87 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[87-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL88 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[88-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL89 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[89-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL90 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[90-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL91 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[91-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL92 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[92-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL93 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[93-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL94 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[94-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL95 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[95-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL96 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[96-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL97 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[97-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL98 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[98-1].LOAN_BAL;
        LNRBALZ.LOAN_BALL99 = LNRBALL.REDEFINES7.REDEFINES9.LOAN_CONT[99-1].LOAN_BAL;
        LNRBALZ.TS = LNRBALL.TS;
    }
    public void T000_READ_UPDATE_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNRBALZ);
        LNRBALZ.KEY.CONTRACT_NO = LNRBALL.KEY.CONTRACT_NO;
        LNRBALZ.KEY.SUB_CTA_NO = LNRBALL.KEY.SUB_CTA_NO;
        LNTBALZ_RD = new DBParm();
        LNTBALZ_RD.TableName = "LNTBALZ";
        LNTBALZ_RD.upd = true;
        IBS.READ(SCCGWA, LNRBALZ, LNTBALZ_RD);
        if (SCCGWA.COMM_AREA.DBIO_FLG == '1') {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_BALL_NOTFND, LNCRBALL.RC);
            LNCRBALL.RETURN_INFO = 'N';
            Z_RET();
            if (pgmRtn) return;
        }
        S000_BALZ_TO_BALL();
        if (pgmRtn) return;
    }
    public void T000_REWRITE_REC_PROC() throws IOException,SQLException,Exception {
        S000_BALL_TO_BALZ();
        if (pgmRtn) return;
        LNRBALZ.UPDTBL_DATE = SCCGWA.COMM_AREA.AC_DATE;
        LNRBALZ.UPDTBL_TLR = SCCGWA.COMM_AREA.TL_ID;
        LNTBALZ_RD = new DBParm();
        LNTBALZ_RD.TableName = "LNTBALZ";
        IBS.REWRITE(SCCGWA, LNRBALZ, LNTBALZ_RD);
    }
    public void T000_DELETE_REC_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNRBALZ);
        LNRBALZ.KEY.CONTRACT_NO = LNRBALL.KEY.CONTRACT_NO;
        LNRBALZ.KEY.SUB_CTA_NO = LNRBALL.KEY.SUB_CTA_NO;
        LNTBALZ_RD = new DBParm();
        LNTBALZ_RD.TableName = "LNTBALZ";
        IBS.DELETE(SCCGWA, LNRBALZ, LNTBALZ_RD);
        if (SCCGWA.COMM_AREA.DBIO_FLG == '1') {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_BALL_NOTFND, LNCRBALL.RC);
            LNCRBALL.RETURN_INFO = 'N';
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        pgmRtn = true;
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
