package com.hisun.LN;

import com.hisun.SC.*;
import com.hisun.IB.*;
import com.hisun.AI.*;
import com.hisun.DD.*;
import com.hisun.BP.*;

import java.io.IOException;
import java.sql.SQLException;

public class LNZSPDQ {
    int JIBS_tmp_int;
    String JIBS_tmp_str[] = new String[10];
    brParm LNTRCVD_BR = new brParm();
    DBParm LNTCTPY_RD;
    brParm LNTSETL_BR = new brParm();
    brParm LNTINTA_BR = new brParm();
    DBParm LNTRCVD_RD;
    DBParm LNTPARS_RD;
    boolean pgmRtn = false;
    String SCSSCLDT = "SCSSCLDT";
    short PAGE_ROW = 10;
    char CKPD_INQ = '0';
    LNZSPDQ_WS_VARIABLES WS_VARIABLES = new LNZSPDQ_WS_VARIABLES();
    LNZSPDQ_WS_OUT_RECODE WS_OUT_RECODE = new LNZSPDQ_WS_OUT_RECODE();
    LNZSPDQ_WS_RCV_DATAS WS_RCV_DATAS = new LNZSPDQ_WS_RCV_DATAS();
    LNZSPDQ_WS_COND_FLG WS_COND_FLG = new LNZSPDQ_WS_COND_FLG();
    LNRRCVD LNRRCVD = new LNRRCVD();
    LNCMSG_ERROR_MSG ERROR_MSG = new LNCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCFMT SCCFMT = new SCCFMT();
    LNCRCVDM LNCRCVDM = new LNCRCVDM();
    LNCLCCM LNCLCCM = new LNCLCCM();
    SCCCLDT SCCCLDT = new SCCCLDT();
    LNCICUT LNCICUT = new LNCICUT();
    LNRCTPY LNRCTPY = new LNRCTPY();
    LNCAPRDM LNCAPRDM = new LNCAPRDM();
    IBCQINF IBCQINF = new IBCQINF();
    AICPQMIB AICPQMIB = new AICPQMIB();
    LNCCNEX LNCCNEX = new LNCCNEX();
    LNRSETL LNRSETL = new LNRSETL();
    LNCCLNQ LNCCLNQ = new LNCCLNQ();
    DDCIQBAL DDCIQBAL = new DDCIQBAL();
    LNRWOFF LNRWOFF = new LNRWOFF();
    LNCRWOFF LNCRWOFF = new LNCRWOFF();
    LNRPARS LNRPARS = new LNRPARS();
    LNCIPAMT LNCIPAMT = new LNCIPAMT();
    LNCSCKPD LNCSCKPD = new LNCSCKPD();
    LNRINTA LNRINTA = new LNRINTA();
    LNCICTLM LNCICTLM = new LNCICTLM();
    LNCICTLM_WS_DB_VARS WS_DB_VARS = new LNCICTLM_WS_DB_VARS();
    SCCGWA SCCGWA;
    LNCSPDQ LNCSPDQ;
    BPCPQBNK_DATA_INFO DATA_INFO;
    public void MP(SCCGWA SCCGWA, LNCSPDQ LNCSPDQ) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        this.LNCSPDQ = LNCSPDQ;
        CEP.TRC(SCCGWA);
        A00_INIT_PROC();
        if (pgmRtn) return;
        B00_MAIN_PROC();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, "LNZSPDQ return!");
        Z_RET();
        if (pgmRtn) return;
    }
    public void A00_INIT_PROC() throws IOException,SQLException,Exception {
        DATA_INFO = (BPCPQBNK_DATA_INFO) SCCGWA.COMM_AREA.BANK_AREA_PTR;
        IBS.init(SCCGWA, WS_VARIABLES);
        IBS.init(SCCGWA, WS_COND_FLG);
        IBS.init(SCCGWA, WS_OUT_RECODE);
        IBS.init(SCCGWA, LNCSPDQ.COMM_DATA.TOT_AMTS);
        LNCSPDQ.RC.RC_APP = "LN";
        LNCSPDQ.RC.RC_RTNCODE = 0;
        WS_RCV_DATAS.CNT = 0;
    }
    public void B00_MAIN_PROC() throws IOException,SQLException,Exception {
        B000_CHECK();
        if (pgmRtn) return;
        B000_MAIN_PROC();
        if (pgmRtn) return;
    }
    public void B000_CHECK() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, LNCSPDQ.COMM_DATA.CTA_INFO.CTA_NO);
        CEP.TRC(SCCGWA, LNCSPDQ.COMM_DATA.TR_VAL_DATE);
        if (LNCSPDQ.COMM_DATA.CTA_INFO.CTA_NO.trim().length() == 0) {
            IBS.CPY2CLS(SCCGWA, ERROR_MSG.LN_ERR_MUST_INPUT, LNCSPDQ.RC);
            Z_RET();
            if (pgmRtn) return;
        }
        if (LNCSPDQ.COMM_DATA.TR_VAL_DATE == 0) {
            LNCSPDQ.COMM_DATA.TR_VAL_DATE = SCCGWA.COMM_AREA.AC_DATE;
        }
        if (SCCGWA.COMM_AREA.TR_ID.TR_CODE == 0134000 
            || SCCGWA.COMM_AREA.TR_ID.TR_CODE == 0134010) {
            LNRRCVD.KEY.CONTRACT_NO = LNCSPDQ.COMM_DATA.CTA_INFO.CTA_NO;
            WS_COND_FLG.STS = 'N';
            T000_STARTBR_LNTRCVD();
            if (pgmRtn) return;
            T000_READNEXT_LNTRCVD();
            if (pgmRtn) return;
            while (SCCGWA.COMM_AREA.DBIO_FLG != '1') {
                if (LNRRCVD.TERM_STS == '1') {
                    WS_COND_FLG.STS = 'O';
                }
                T000_READNEXT_LNTRCVD();
                if (pgmRtn) return;
            }
            T000_ENDBR_LNTRCVD();
            if (pgmRtn) return;
            if (WS_COND_FLG.STS == 'N') {
                IBS.CPY2CLS(SCCGWA, ERROR_MSG.LN_CONT_NOTO, LNCSPDQ.RC);
            }
        }
        IBS.init(SCCGWA, LNCICTLM);
        LNCICTLM.FUNC = '3';
        LNCICTLM.REC_DATA.KEY.CONTRACT_NO = LNCSPDQ.COMM_DATA.CTA_INFO.CTA_NO;
        LNCICTLM.REC_DATA.KEY.SUB_CTA_NO = 0;
        S000_CALL_LNZICTLM();
        if (pgmRtn) return;
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        if (LNCSPDQ.FUNC_CODE != 'E') {
            B300_BROWSE_INIT();
            if (pgmRtn) return;
        }
        B100_GET_LOAN_INF();
        if (pgmRtn) return;
        if (WS_VARIABLES.CTL_STSW == null) WS_VARIABLES.CTL_STSW = "";
        JIBS_tmp_int = WS_VARIABLES.CTL_STSW.length();
        for (int i=0;i<128-JIBS_tmp_int;i++) WS_VARIABLES.CTL_STSW += " ";
        if (!WS_VARIABLES.CTL_STSW.substring(4 - 1, 4 + 1 - 1).equalsIgnoreCase("1")) {
            B200_GET_RCVD_INF();
            if (pgmRtn) return;
        }
        if (WS_VARIABLES.CTL_STSW == null) WS_VARIABLES.CTL_STSW = "";
        JIBS_tmp_int = WS_VARIABLES.CTL_STSW.length();
        for (int i=0;i<128-JIBS_tmp_int;i++) WS_VARIABLES.CTL_STSW += " ";
        if (LNCSPDQ.FUNC_CODE != 'E' 
            && !WS_VARIABLES.CTL_STSW.substring(4 - 1, 4 + 1 - 1).equalsIgnoreCase("1")) {
            B150_GET_CTA_BAL();
            if (pgmRtn) return;
            B300_PRINT_RESULTS();
            if (pgmRtn) return;
        }
    }
    public void B300_BROWSE_INIT() throws IOException,SQLException,Exception {
        if (LNCSPDQ.COMM_DATA.PAGE_NUM == 0) {
            WS_VARIABLES.CURR_PAGE = 1;
        } else {
            WS_VARIABLES.CURR_PAGE = (short) LNCSPDQ.COMM_DATA.PAGE_NUM;
        }
        WS_OUT_RECODE.WS_OUT_HEAD.O_CURR_PAGE = WS_VARIABLES.CURR_PAGE;
        WS_VARIABLES.LAST_PAGE = 'N';
        if (LNCSPDQ.COMM_DATA.PAGE_ROW == 0) {
            WS_VARIABLES.PAGE_ROW = PAGE_ROW;
        } else {
            if (LNCSPDQ.COMM_DATA.PAGE_ROW > PAGE_ROW) {
                IBS.CPY2CLS(SCCGWA, ERROR_MSG.LN_ERR_PAGE_ROW, LNCSPDQ.RC);
                Z_RET();
                if (pgmRtn) return;
            } else {
                WS_VARIABLES.PAGE_ROW = (short) LNCSPDQ.COMM_DATA.PAGE_ROW;
            }
        }
        WS_VARIABLES.NEXT_START_NUM = ( ( WS_VARIABLES.CURR_PAGE - 1 ) * WS_VARIABLES.PAGE_ROW ) + 1;
        CEP.TRC(SCCGWA, WS_VARIABLES.NEXT_START_NUM);
    }
    public void B100_GET_LOAN_INF() throws IOException,SQLException,Exception {
        B110_GET_LOAN_INF();
        if (pgmRtn) return;
        B130_GET_PROD_INF();
        if (pgmRtn) return;
        B160_GET_APRD_INF();
        if (pgmRtn) return;
    }
    public void B110_GET_LOAN_INF() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCCLNQ);
        LNCCLNQ.DATA.CONT_NO = LNCSPDQ.COMM_DATA.CTA_INFO.CTA_NO;
        LNCCLNQ.DATA.SUB_CONT_NO = "" + 0;
        JIBS_tmp_int = LNCCLNQ.DATA.SUB_CONT_NO.length();
        for (int i=0;i<0-JIBS_tmp_int;i++) LNCCLNQ.DATA.SUB_CONT_NO = "0" + LNCCLNQ.DATA.SUB_CONT_NO;
        if (SCCGWA.COMM_AREA.CHNL.equalsIgnoreCase("BAT")) {
            LNCCLNQ.FUNC = '1';
        } else {
            LNCCLNQ.PROD_FLG = 'Y';
            LNCCLNQ.FUNC = '3';
        }
        S000_CALL_LNZICLNQ();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, LNCCLNQ.DATA.PROD_CD);
        LNCSPDQ.COMM_DATA.CTA_INFO.BR = LNCCLNQ.DATA.DOMI_BR;
        LNCSPDQ.COMM_DATA.CTA_INFO.CCY = LNCCLNQ.DATA.CCY;
        LNCSPDQ.COMM_DATA.CTA_INFO.PROD_CD = LNCCLNQ.DATA.PROD_CD;
        LNCSPDQ.COMM_DATA.CTA_INFO.PD_DESC = LNCSCKPD.PROD_NM;
        LNCSPDQ.COMM_DATA.CTA_INFO.CI_NO = LNCCLNQ.DATA.CI_NO;
        LNCSPDQ.COMM_DATA.CTA_INFO.CI_CNM = LNCCLNQ.DATA.CI_CNAME;
        LNCSPDQ.COMM_DATA.CTA_INFO.LON_PRIN = LNCCLNQ.DATA.PRIN;
        LNCSPDQ.COMM_DATA.CTA_INFO.LON_BAL = LNCCLNQ.DATA.TOT_BAL;
        LNCSPDQ.COMM_DATA.CTA_INFO.LN_STS = LNCCLNQ.DATA.STS;
        LNCSPDQ.LOAN_INFO.FX_RAT = LNCCLNQ.DATA.EXCHANGE_RATE;
        LNCSPDQ.LOAN_INFO.LON_MATD = LNCCLNQ.DATA.DUE_DT;
        LNCSPDQ.LOAN_INFO.PROD_MOD = LNCCLNQ.DATA.CONT_TYPE;
        WS_VARIABLES.CTL_STSW = LNCCLNQ.DATA.CTL_STSW;
        LNCSPDQ.COMM_DATA.CTA_INFO.PD_DESC = LNCCLNQ.DATA.PROD_NAME;
        WS_VARIABLES.CUR_RAT = LNCCLNQ.DATA.CUR_RAT;
        WS_VARIABLES.CUR_PO_RAT = LNCCLNQ.DATA.CUR_PO_RAT;
        WS_OUT_RECODE.WS_CMMT_INF.O_START_DT = LNCCLNQ.DATA.VAL_DT;
        WS_OUT_RECODE.WS_CMMT_INF.O_END_DT = LNCCLNQ.DATA.DUE_DT;
    }
    public void B120_GET_ICTL_INF() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, LNCSPDQ.COMM_DATA.TR_VAL_DATE);
        CEP.TRC(SCCGWA, LNCCLNQ.DATA.LAST_F_VAL_DATE);
        if (LNCSPDQ.COMM_DATA.TR_VAL_DATE < LNCCLNQ.DATA.LAST_F_VAL_DATE) {
            IBS.CPY2CLS(SCCGWA, ERROR_MSG.LN_ERR_VALDT_GTR_LSTDT, LNCSPDQ.RC);
            Z_RET();
            if (pgmRtn) return;
        }
        if (WS_VARIABLES.CTL_STSW == null) WS_VARIABLES.CTL_STSW = "";
        JIBS_tmp_int = WS_VARIABLES.CTL_STSW.length();
        for (int i=0;i<128-JIBS_tmp_int;i++) WS_VARIABLES.CTL_STSW += " ";
        if (WS_VARIABLES.CTL_STSW == null) WS_VARIABLES.CTL_STSW = "";
        JIBS_tmp_int = WS_VARIABLES.CTL_STSW.length();
        for (int i=0;i<128-JIBS_tmp_int;i++) WS_VARIABLES.CTL_STSW += " ";
        if (WS_VARIABLES.CTL_STSW.substring(51 - 1, 51 + 1 - 1).equalsIgnoreCase("1") 
            || WS_VARIABLES.CTL_STSW.substring(53 - 1, 53 + 1 - 1).equalsIgnoreCase("1")) {
            IBS.CPY2CLS(SCCGWA, ERROR_MSG.LN_NOT_SUP_DIST, LNCSPDQ.RC);
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void B130_GET_PROD_INF() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCSCKPD);
        LNCSCKPD.FUNC = CKPD_INQ;
        LNCSCKPD.PROD_CD = LNCSPDQ.COMM_DATA.CTA_INFO.PROD_CD;
        CEP.TRC(SCCGWA, LNCSPDQ.COMM_DATA.CTA_INFO.PROD_CD);
        S000_CALL_LNZSCKPD();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, LNCSPDQ.COMM_DATA.CTA_INFO.PROD_CD);
        CEP.TRC(SCCGWA, LNCSCKPD.PROD_NM);
    }
    public void B160_GET_APRD_INF() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCAPRDM);
        LNCAPRDM.FUNC = '3';
        LNCAPRDM.REC_DATA.KEY.CONTRACT_NO = LNCSPDQ.COMM_DATA.CTA_INFO.CTA_NO;
        S000_CALL_LNZAPRDM();
        if (pgmRtn) return;
    }
    public void B150_GET_CTA_BAL() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCCNEX);
        LNCCNEX.COMM_DATA.INQ_CODE = "INQOVDP";
        LNCCNEX.COMM_DATA.LN_AC = LNCSPDQ.COMM_DATA.CTA_INFO.CTA_NO;
        LNCCNEX.COMM_DATA.SUF_NO = LNCSPDQ.COMM_DATA.CTA_INFO.CTA_SEQ;
        S000_CALL_LNZCNEX();
        if (pgmRtn) return;
        LNCSPDQ.COMM_DATA.CTA_INFO.O_P_BAL = LNCCNEX.COMM_DATA.INQ_AMT;
        CEP.TRC(SCCGWA, LNCSPDQ.COMM_DATA.CTA_INFO.O_P_BAL);
        LNCSPDQ.COMM_DATA.CTA_INFO.P_P_BAL = LNCSPDQ.COMM_DATA.CTA_INFO.LON_BAL - LNCSPDQ.COMM_DATA.CTA_INFO.O_P_BAL;
        if (WS_VARIABLES.CTL_STSW == null) WS_VARIABLES.CTL_STSW = "";
        JIBS_tmp_int = WS_VARIABLES.CTL_STSW.length();
        for (int i=0;i<128-JIBS_tmp_int;i++) WS_VARIABLES.CTL_STSW += " ";
        if (WS_VARIABLES.CTL_STSW == null) WS_VARIABLES.CTL_STSW = "";
        JIBS_tmp_int = WS_VARIABLES.CTL_STSW.length();
        for (int i=0;i<128-JIBS_tmp_int;i++) WS_VARIABLES.CTL_STSW += " ";
        if (WS_VARIABLES.CTL_STSW.substring(38 - 1, 38 + 1 - 1).equalsIgnoreCase("1") 
            && WS_VARIABLES.CTL_STSW.substring(44 - 1, 44 + 1 - 1).equalsIgnoreCase("1")) {
            IBS.init(SCCGWA, LNRCTPY);
            LNRCTPY.KEY.CONTRACT_NO = LNCSPDQ.COMM_DATA.CTA_INFO.CTA_NO;
            T000_READ_LNTCTPY();
            if (pgmRtn) return;
            LNCSPDQ.COMM_DATA.TOT_AMTS.T_I_AMT = LNRCTPY.I_REC_AMT - LNRCTPY.I_PAY_AMT;
            LNCSPDQ.COMM_DATA.TOT_AMTS.T_O_AMT = LNRCTPY.O_REC_AMT - LNRCTPY.O_PAY_AMT;
            LNCSPDQ.COMM_DATA.TOT_AMTS.T_L_AMT = LNRCTPY.L_REC_AMT - LNRCTPY.L_PAY_AMT;
        }
    }
    public void B200_GET_RCVD_INF() throws IOException,SQLException,Exception {
        B210_GET_ARREARS_DETAIL();
        if (pgmRtn) return;
        B230_GET_ARREARS_SUM();
        if (pgmRtn) return;
    }
    public void B210_GET_ARREARS_DETAIL() throws IOException,SQLException,Exception {
        WS_COND_FLG.FOUND_FLG = 'N';
        WS_VARIABLES.I = 0;
        T01_STARTBR_LNTRCVD();
        if (pgmRtn) return;
        T01_READNEXT_LNTRCVD();
        if (pgmRtn) return;
        WS_VARIABLES.DATE = 0;
        CEP.TRC(SCCGWA, WS_COND_FLG.FOUND_FLG);
        while (WS_COND_FLG.FOUND_FLG != 'N' 
            && WS_RCV_DATAS.CNT < 1500) {
            if (LNRRCVD.P_REC_AMT == 0 
                && LNRRCVD.I_REC_AMT == 0 
                && LNRRCVD.O_REC_AMT == 0 
                && LNRRCVD.L_REC_AMT == 0 
                && LNRRCVD.F_REC_AMT == 0) {
            } else {
                if (LNRRCVD.DUE_DT != WS_VARIABLES.DATE) {
                    WS_VARIABLES.DATE = LNRRCVD.DUE_DT;
                    WS_VARIABLES.I += 1;
                    WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].REC_P_AMT = 0;
                    WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].REC_I_AMT = 0;
                    WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].REC_O_AMT = 0;
                    WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].REC_L_AMT = 0;
                    WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].PAY_P_AMT = 0;
                    WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].PAY_I_AMT = 0;
                    WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].PAY_O_AMT = 0;
                    WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].PAY_L_AMT = 0;
                    WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].P_AMT = 0;
                    WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].I_AMT = 0;
                    WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].O_AMT = 0;
                    WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].L_AMT = 0;
                    WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].SUM = 0;
                    WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].AC_MGT_AMT = 0;
                    WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].HRG_AMT = 0;
                    WS_RCV_DATAS.CNT = WS_VARIABLES.I;
                }
                B210_TERM_RCVD_PROC();
                if (pgmRtn) return;
            }
            T01_READNEXT_LNTRCVD();
            if (pgmRtn) return;
        }
        T01_ENDBR_LNTRCVD();
        if (pgmRtn) return;
    }
    public void B210_TERM_RCVD_PROC() throws IOException,SQLException,Exception {
        WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].DUEDT = LNRRCVD.DUE_DT;
        WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].OVEDT = LNRRCVD.OVD_DT;
        WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].REC_P_AMT += LNRRCVD.P_REC_AMT;
        WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].PAY_P_AMT += LNRRCVD.P_PAY_AMT;
        WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].P_AMT += LNRRCVD.P_REC_AMT;
        WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].P_AMT -= LNRRCVD.P_PAY_AMT;
        WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].P_AMT -= LNRRCVD.P_WAV_AMT;
        WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].REC_I_AMT += LNRRCVD.I_REC_AMT;
        WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].REC_I_AMT -= LNRRCVD.I_WAV_AMT;
        WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].PAY_I_AMT += LNRRCVD.I_PAY_AMT;
        WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].I_AMT += LNRRCVD.I_REC_AMT;
        WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].I_AMT -= LNRRCVD.I_PAY_AMT;
        WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].I_AMT -= LNRRCVD.I_WAV_AMT;
        if (LNRRCVD.KEY.SUBS_PROJ_NO == 0) {
            B212_LC_COMP();
            if (pgmRtn) return;
            CEP.TRC(SCCGWA, LNCLCCM.COMM_DATA.O_AMT);
            CEP.TRC(SCCGWA, LNCLCCM.COMM_DATA.L_AMT);
            WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].O_AMT += LNCLCCM.COMM_DATA.O_AMT;
            WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].REC_O_AMT += LNCLCCM.COMM_DATA.O_AMT;
            WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].L_AMT += LNCLCCM.COMM_DATA.L_AMT;
            WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].REC_L_AMT += LNCLCCM.COMM_DATA.L_AMT;
            CEP.TRC(SCCGWA, WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].O_AMT);
            CEP.TRC(SCCGWA, WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].L_AMT);
        }
        if (LNRRCVD.KEY.AMT_TYP == 'P' 
            || LNRRCVD.KEY.AMT_TYP == 'C') {
            WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].PAY_O_AMT += LNRRCVD.O_PAY_AMT;
            WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].REC_O_AMT = WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].REC_O_AMT + LNRRCVD.O_PAY_AMT;
        }
        WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].PAY_L_AMT += LNRRCVD.L_PAY_AMT;
        WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].REC_L_AMT = WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].REC_L_AMT + LNRRCVD.L_PAY_AMT;
        CEP.TRC(SCCGWA, LNCAPRDM.REC_DATA.CHG_DB_FLG);
        if (WS_VARIABLES.CTL_STSW == null) WS_VARIABLES.CTL_STSW = "";
        JIBS_tmp_int = WS_VARIABLES.CTL_STSW.length();
        for (int i=0;i<128-JIBS_tmp_int;i++) WS_VARIABLES.CTL_STSW += " ";
        if (WS_VARIABLES.CTL_STSW == null) WS_VARIABLES.CTL_STSW = "";
        JIBS_tmp_int = WS_VARIABLES.CTL_STSW.length();
        for (int i=0;i<128-JIBS_tmp_int;i++) WS_VARIABLES.CTL_STSW += " ";
        if ((WS_VARIABLES.CTL_STSW.substring(19 - 1, 19 + 1 - 1).equalsIgnoreCase("1") 
            && LNCAPRDM.REC_DATA.CHG_DB_FLG == '3') 
            || WS_VARIABLES.CTL_STSW.substring(54 - 1, 54 + 1 - 1).equalsIgnoreCase("1")) {
            WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].HRG_AMT += LNRRCVD.F_REC_AMT;
            WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].HRG_AMT -= LNRRCVD.F_PAY_AMT;
            WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].HRG_AMT -= LNRRCVD.F_WAV_AMT;
        }
        WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].SUM = WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].P_AMT;
        WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].SUM += WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].I_AMT;
        WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].SUM += WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].O_AMT;
        WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].SUM += WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].L_AMT;
        CEP.TRC(SCCGWA, WS_VARIABLES.I);
        CEP.TRC(SCCGWA, WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].P_AMT);
        CEP.TRC(SCCGWA, WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].I_AMT);
        CEP.TRC(SCCGWA, WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].O_AMT);
        CEP.TRC(SCCGWA, WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].L_AMT);
        CEP.TRC(SCCGWA, WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].SUM);
        CEP.TRC(SCCGWA, WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].HRG_AMT);
    }
    public void B212_LC_COMP() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCLCCM);
        LNCLCCM.COMM_DATA.FUNC_CODE = 'I';
        LNCLCCM.COMM_DATA.LN_AC = LNCSPDQ.COMM_DATA.CTA_INFO.CTA_NO;
        LNCLCCM.COMM_DATA.SUF_NO = LNCSPDQ.COMM_DATA.CTA_INFO.CTA_SEQ;
        LNCLCCM.COMM_DATA.TYPE = LNRRCVD.KEY.AMT_TYP;
        LNCLCCM.COMM_DATA.TERM = LNRRCVD.KEY.TERM;
        LNCLCCM.COMM_DATA.END_DATE = LNCSPDQ.COMM_DATA.TR_VAL_DATE;
        S000_CALL_LNZLCCM();
        if (pgmRtn) return;
    }
    public void B230_GET_ARREARS_SUM() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, WS_RCV_DATAS.CNT);
        IBS.init(SCCGWA, LNCSPDQ.ARREAR_DATAS);
        LNCSPDQ.ARREAR_DATAS.LOAN_STSW = WS_VARIABLES.CTL_STSW;
        for (WS_VARIABLES.I = 1; WS_VARIABLES.I <= WS_RCV_DATAS.CNT; WS_VARIABLES.I += 1) {
            if (WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].DUEDT != 0) {
                CEP.TRC(SCCGWA, WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].P_AMT);
                CEP.TRC(SCCGWA, WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].I_AMT);
                CEP.TRC(SCCGWA, WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].O_AMT);
                CEP.TRC(SCCGWA, WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].L_AMT);
                CEP.TRC(SCCGWA, WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].SUM);
                CEP.TRC(SCCGWA, WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].AC_MGT_AMT);
                CEP.TRC(SCCGWA, WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].HRG_AMT);
                LNCSPDQ.COMM_DATA.TOT_AMTS.TOT_P_AMT += WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].P_AMT;
                LNCSPDQ.COMM_DATA.TOT_AMTS.TOT_I_AMT += WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].I_AMT;
                CEP.TRC(SCCGWA, LNCSPDQ.COMM_DATA.TOT_AMTS.TOT_O_AMT);
                LNCSPDQ.COMM_DATA.TOT_AMTS.TOT_O_AMT += WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].O_AMT;
                CEP.TRC(SCCGWA, LNCSPDQ.COMM_DATA.TOT_AMTS.TOT_O_AMT);
                CEP.TRC(SCCGWA, LNCSPDQ.COMM_DATA.TOT_AMTS.TOT_L_AMT);
                LNCSPDQ.COMM_DATA.TOT_AMTS.TOT_L_AMT += WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].L_AMT;
                CEP.TRC(SCCGWA, LNCSPDQ.COMM_DATA.TOT_AMTS.TOT_L_AMT);
                LNCSPDQ.COMM_DATA.TOT_AMTS.TOT_AMT += WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].SUM;
                CEP.TRC(SCCGWA, LNCSPDQ.COMM_DATA.TOT_AMTS.TOT_AMT);
                LNCSPDQ.COMM_DATA.TOT_AMTS.TAC_MGT_AMT += WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].AC_MGT_AMT;
                LNCSPDQ.COMM_DATA.TOT_AMTS.THRG_AMT += WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].HRG_AMT;
                if (WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].P_AMT != 0) {
                    if (WS_VARIABLES.PIA_FST_DT == 0) {
                        WS_VARIABLES.PIA_FST_DT = WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].OVEDT;
                    }
                    WS_VARIABLES.PIA_LST_DT = WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].OVEDT;
                }
                if (WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].I_AMT != 0) {
                    if (WS_VARIABLES.IIA_FST_DT == 0) {
                        WS_VARIABLES.IIA_FST_DT = WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].OVEDT;
                    }
                    WS_VARIABLES.IIA_LST_DT = WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].OVEDT;
                }
            }
        }
        CEP.TRC(SCCGWA, "NOW DISPLAY TOTAL AMT");
        CEP.TRC(SCCGWA, LNCSPDQ.COMM_DATA.TOT_AMTS.TOT_P_AMT);
        CEP.TRC(SCCGWA, LNCSPDQ.COMM_DATA.TOT_AMTS.TOT_I_AMT);
        CEP.TRC(SCCGWA, LNCSPDQ.COMM_DATA.TOT_AMTS.TOT_O_AMT);
        CEP.TRC(SCCGWA, LNCSPDQ.COMM_DATA.TOT_AMTS.TOT_L_AMT);
        CEP.TRC(SCCGWA, LNCSPDQ.COMM_DATA.TOT_AMTS.TOT_AMT);
        if (WS_VARIABLES.PIA_FST_DT != 0 
            && WS_VARIABLES.PIA_FST_DT < LNCSPDQ.COMM_DATA.TR_VAL_DATE) {
            WS_VARIABLES.DATE = WS_VARIABLES.PIA_FST_DT;
            R000_CALC_ARREARS_DAYS();
            if (pgmRtn) return;
            LNCSPDQ.ARREAR_DATAS.PIA_DAYS = WS_VARIABLES.DAYS;
            LNCSPDQ.COMM_DATA.TOT_AMTS.P_O_DT = WS_VARIABLES.DAYS;
        }
        if (WS_VARIABLES.IIA_FST_DT != 0 
            && WS_VARIABLES.IIA_FST_DT < LNCSPDQ.COMM_DATA.TR_VAL_DATE) {
            WS_VARIABLES.DATE = WS_VARIABLES.IIA_FST_DT;
            R000_CALC_ARREARS_DAYS();
            if (pgmRtn) return;
            LNCSPDQ.ARREAR_DATAS.IIA_DAYS = WS_VARIABLES.DAYS;
            LNCSPDQ.COMM_DATA.TOT_AMTS.I_L_DT = WS_VARIABLES.DAYS;
        }
        LNCSPDQ.ARREAR_DATAS.PIA_AMT = LNCSPDQ.COMM_DATA.TOT_AMTS.TOT_P_AMT;
        LNCSPDQ.ARREAR_DATAS.IIA_AMT = LNCSPDQ.COMM_DATA.TOT_AMTS.TOT_I_AMT;
        LNCSPDQ.ARREAR_DATAS.IPIA_AMT = LNCSPDQ.COMM_DATA.TOT_AMTS.TOT_O_AMT;
        LNCSPDQ.ARREAR_DATAS.IIIA_AMT = LNCSPDQ.COMM_DATA.TOT_AMTS.TOT_L_AMT;
        B231_CALC_ACCRUAL_INTEREST();
        if (pgmRtn) return;
    }
    public void B231_CALC_ACCRUAL_INTEREST() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCICUT);
        LNCICUT.COMM_DATA.FUNC_CODE = 'I';
        LNCICUT.COMM_DATA.LN_AC = LNCSPDQ.COMM_DATA.CTA_INFO.CTA_NO;
        LNCICUT.COMM_DATA.SUF_NO = LNCSPDQ.COMM_DATA.CTA_INFO.CTA_SEQ;
        LNCICUT.COMM_DATA.TYPE = 'I';
        if (LNCSPDQ.COMM_DATA.TR_BEG_DATE != 0) {
            LNCICUT.COMM_DATA.BEG_DATE = LNCSPDQ.COMM_DATA.TR_BEG_DATE;
        } else {
            if (WS_VARIABLES.IIA_LST_DT != 0) {
                LNCICUT.COMM_DATA.BEG_DATE = WS_VARIABLES.IIA_LST_DT;
            } else {
                if (LNCSPDQ.COMM_DATA.TR_VAL_DATE < LNCCLNQ.DATA.IC_CAL_VAL_DT) {
                    T000_READ_LNTRCVD();
                    if (pgmRtn) return;
                    if (WS_COND_FLG.RCVD_FOUND_FLG == 'Y' 
                        && LNCSPDQ.COMM_DATA.TR_VAL_DATE < SCCGWA.COMM_AREA.AC_DATE) {
                        LNCICUT.COMM_DATA.BEG_DATE = LNRRCVD.VAL_DT;
                    } else {
                        LNCICUT.COMM_DATA.BEG_DATE = LNCCLNQ.DATA.IC_CAL_VAL_DT;
                    }
                } else {
                    LNCICUT.COMM_DATA.BEG_DATE = LNCCLNQ.DATA.IC_CAL_VAL_DT;
                }
            }
            if (LNCSPDQ.COMM_DATA.TR_VAL_DATE >= LNCCLNQ.DATA.INT_CUT_DT) {
                LNCICUT.COMM_DATA.BEG_DATE = LNCCLNQ.DATA.INT_CUT_DT;
            }
        }
        LNCICUT.COMM_DATA.END_DATE = LNCSPDQ.COMM_DATA.TR_VAL_DATE;
        if (LNCSPDQ.COMM_DATA.TR_VAL_DATE > LNCCLNQ.DATA.DUE_DT) {
            LNCICUT.COMM_DATA.END_DATE = LNCCLNQ.DATA.DUE_DT;
        }
        if (LNCICUT.COMM_DATA.BEG_DATE < LNCICUT.COMM_DATA.END_DATE 
            && LNCICUT.COMM_DATA.END_DATE <= LNCCLNQ.DATA.DUE_DT 
            && LNCAPRDM.REC_DATA.PAY_MTH != '0') {
            S000_CALL_LNZICUT();
            if (pgmRtn) return;
            T000_STARTBR_LNTINTA();
            if (pgmRtn) return;
            T000_READNEXT_LNTINTA();
            if (pgmRtn) return;
            while (SCCGWA.COMM_AREA.DBIO_FLG != '1') {
                WS_VARIABLES.LON_ACRINT = LNRINTA.ADJ_AMT + WS_VARIABLES.LON_ACRINT;
                T000_READNEXT_LNTINTA();
                if (pgmRtn) return;
            }
            T000_ENDBR_LNTINTA();
            if (pgmRtn) return;
        }
        WS_VARIABLES.LON_ACRINT = LNCICUT.COMM_DATA.INT_AMT + WS_VARIABLES.LON_ACRINT;
        LNCSPDQ.LOAN_INFO.LON_ACRINT = WS_VARIABLES.LON_ACRINT;
        LNCSPDQ.COMM_DATA.CTA_INFO.D_I_AMT = WS_VARIABLES.LON_ACRINT;
        CEP.TRC(SCCGWA, LNCSPDQ.COMM_DATA.CTA_INFO.D_I_AMT);
        CEP.TRC(SCCGWA, LNCSPDQ.LOAN_INFO.LON_ACRINT);
    }
    public void B300_PRINT_RESULTS() throws IOException,SQLException,Exception {
        B300_GET_AC_INFO();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, WS_VARIABLES.NEXT_START_NUM);
        CEP.TRC(SCCGWA, WS_RCV_DATAS.CNT);
        if (WS_RCV_DATAS.CNT != 0 
            && WS_VARIABLES.NEXT_START_NUM <= WS_RCV_DATAS.CNT) {
            WS_VARIABLES.IDXA = 0;
            for (WS_VARIABLES.I = WS_VARIABLES.NEXT_START_NUM; (WS_VARIABLES.IDXA != WS_VARIABLES.PAGE_ROW 
                && WS_VARIABLES.I <= WS_RCV_DATAS.CNT); WS_VARIABLES.I += 1) {
                CEP.TRC(SCCGWA, "111111");
                CEP.TRC(SCCGWA, WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].DUEDT);
                CEP.TRC(SCCGWA, WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].P_AMT);
                CEP.TRC(SCCGWA, WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].I_AMT);
                CEP.TRC(SCCGWA, WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].O_AMT);
                CEP.TRC(SCCGWA, WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].L_AMT);
                CEP.TRC(SCCGWA, WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].SUM);
                CEP.TRC(SCCGWA, WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].AC_MGT_AMT);
                CEP.TRC(SCCGWA, WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].HRG_AMT);
                WS_VARIABLES.IDXA += 1;
                WS_OUT_RECODE.WS_OUT_INFO[WS_VARIABLES.IDXA-1].O_DUE_DT = WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].DUEDT;
                WS_OUT_RECODE.WS_OUT_INFO[WS_VARIABLES.IDXA-1].O_REC_P_AMT = WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].REC_P_AMT;
                WS_OUT_RECODE.WS_OUT_INFO[WS_VARIABLES.IDXA-1].O_REC_I_AMT = WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].REC_I_AMT;
                WS_OUT_RECODE.WS_OUT_INFO[WS_VARIABLES.IDXA-1].O_REC_O_AMT = WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].REC_O_AMT;
                WS_OUT_RECODE.WS_OUT_INFO[WS_VARIABLES.IDXA-1].O_REC_L_AMT = WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].REC_L_AMT;
                WS_OUT_RECODE.WS_OUT_INFO[WS_VARIABLES.IDXA-1].O_PAY_P_AMT = WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].PAY_P_AMT;
                WS_OUT_RECODE.WS_OUT_INFO[WS_VARIABLES.IDXA-1].O_PAY_I_AMT = WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].PAY_I_AMT;
                WS_OUT_RECODE.WS_OUT_INFO[WS_VARIABLES.IDXA-1].O_PAY_O_AMT = WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].PAY_O_AMT;
                WS_OUT_RECODE.WS_OUT_INFO[WS_VARIABLES.IDXA-1].O_PAY_L_AMT = WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].PAY_L_AMT;
                WS_OUT_RECODE.WS_OUT_INFO[WS_VARIABLES.IDXA-1].O_P_AMT = WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].P_AMT;
                WS_OUT_RECODE.WS_OUT_INFO[WS_VARIABLES.IDXA-1].O_I_AMT = WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].I_AMT;
                WS_OUT_RECODE.WS_OUT_INFO[WS_VARIABLES.IDXA-1].O_O_AMT = WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].O_AMT;
                WS_OUT_RECODE.WS_OUT_INFO[WS_VARIABLES.IDXA-1].O_L_AMT = WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].L_AMT;
                WS_OUT_RECODE.WS_OUT_INFO[WS_VARIABLES.IDXA-1].O_SUM = WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].SUM;
                WS_OUT_RECODE.WS_OUT_INFO[WS_VARIABLES.IDXA-1].O_AC_MGT_AMT = WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].AC_MGT_AMT;
                WS_OUT_RECODE.WS_OUT_INFO[WS_VARIABLES.IDXA-1].O_HRG_AMT = WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].HRG_AMT;
                CEP.TRC(SCCGWA, WS_OUT_RECODE.WS_OUT_INFO[WS_VARIABLES.IDXA-1].O_REC_O_AMT);
            }
            WS_VARIABLES.TOTAL_NUM = WS_RCV_DATAS.CNT;
            WS_VARIABLES.BAL_CNT = WS_VARIABLES.TOTAL_NUM % WS_VARIABLES.PAGE_ROW;
            WS_VARIABLES.TOTAL_PAGE = (short) ((WS_VARIABLES.TOTAL_NUM - WS_VARIABLES.BAL_CNT) / WS_VARIABLES.PAGE_ROW);
            if (WS_VARIABLES.BAL_CNT != 0) {
                WS_VARIABLES.TOTAL_PAGE += 1;
            }
            if (WS_VARIABLES.CURR_PAGE == WS_VARIABLES.TOTAL_PAGE) {
                WS_VARIABLES.LAST_PAGE = 'Y';
                if (WS_VARIABLES.BAL_CNT != 0) {
                    WS_VARIABLES.PAGE_ROW = (short) WS_VARIABLES.BAL_CNT;
                }
            }
        } else {
            WS_VARIABLES.TOTAL_PAGE = 0;
            WS_VARIABLES.TOTAL_NUM = 0;
            WS_VARIABLES.LAST_PAGE = 'Y';
            WS_VARIABLES.PAGE_ROW = 0;
            WS_OUT_RECODE.WS_OUT_HEAD.O_CURR_PAGE = 0;
        }
        WS_OUT_RECODE.WS_OUT_HEAD.O_TOTAL_PAGE = WS_VARIABLES.TOTAL_PAGE;
        WS_OUT_RECODE.WS_OUT_HEAD.O_TOTAL_NUM = WS_VARIABLES.TOTAL_NUM;
        WS_OUT_RECODE.WS_OUT_HEAD.O_LAST_PAGE = WS_VARIABLES.LAST_PAGE;
        WS_OUT_RECODE.WS_OUT_HEAD.O_CURR_PAGE_ROW = WS_VARIABLES.PAGE_ROW;
        CEP.TRC(SCCGWA, WS_OUT_RECODE.WS_OUT_HEAD.O_TOTAL_PAGE);
        CEP.TRC(SCCGWA, WS_OUT_RECODE.WS_OUT_HEAD.O_TOTAL_NUM);
        CEP.TRC(SCCGWA, WS_OUT_RECODE.WS_OUT_HEAD.O_CURR_PAGE);
        CEP.TRC(SCCGWA, WS_OUT_RECODE.WS_OUT_HEAD.O_LAST_PAGE);
        CEP.TRC(SCCGWA, WS_OUT_RECODE.WS_OUT_HEAD.O_CURR_PAGE_ROW);
        if (WS_VARIABLES.CTL_STSW == null) WS_VARIABLES.CTL_STSW = "";
        JIBS_tmp_int = WS_VARIABLES.CTL_STSW.length();
        for (int i=0;i<128-JIBS_tmp_int;i++) WS_VARIABLES.CTL_STSW += " ";
        if (WS_VARIABLES.CTL_STSW == null) WS_VARIABLES.CTL_STSW = "";
        JIBS_tmp_int = WS_VARIABLES.CTL_STSW.length();
        for (int i=0;i<128-JIBS_tmp_int;i++) WS_VARIABLES.CTL_STSW += " ";
        if (WS_VARIABLES.CTL_STSW.substring(12 - 1, 12 + 1 - 1).equalsIgnoreCase("1") 
            || WS_VARIABLES.CTL_STSW.substring(13 - 1, 13 + 1 - 1).equalsIgnoreCase("1")) {
            IBS.init(SCCGWA, LNCIPAMT);
            LNCIPAMT.CTA_NO = LNCSPDQ.COMM_DATA.CTA_INFO.CTA_NO;
            LNCIPAMT.P_AMT = LNCSPDQ.COMM_DATA.TOT_AMTS.TOT_P_AMT;
            LNCIPAMT.I_AMT = LNCSPDQ.COMM_DATA.TOT_AMTS.TOT_I_AMT;
            LNCIPAMT.O_AMT = LNCSPDQ.COMM_DATA.TOT_AMTS.TOT_O_AMT;
            LNCIPAMT.L_AMT = LNCSPDQ.COMM_DATA.TOT_AMTS.TOT_L_AMT;
            S000_CALL_LNZIPAMT();
            if (pgmRtn) return;
            for (WS_VARIABLES.I = 1; WS_VARIABLES.I <= 10 
                && LNCIPAMT.PART_DATA[WS_VARIABLES.I-1].PART_CTA_NO.trim().length() != 0; WS_VARIABLES.I += 1) {
                WS_OUT_RECODE.WS_PARS_INFO[WS_VARIABLES.I-1].SUB_C_NO1 = LNCIPAMT.PART_DATA[WS_VARIABLES.I-1].PART_CTA_NO;
                WS_OUT_RECODE.WS_PARS_INFO[WS_VARIABLES.I-1].BR1 = LNCIPAMT.PART_DATA[WS_VARIABLES.I-1].PART_BR;
                WS_OUT_RECODE.WS_PARS_INFO[WS_VARIABLES.I-1].SEQ_NO1 = LNCIPAMT.PART_DATA[WS_VARIABLES.I-1].PART_NO;
                WS_OUT_RECODE.WS_PARS_INFO[WS_VARIABLES.I-1].I_O_FLG1 = LNCIPAMT.INNER_OUT_FLG;
                WS_OUT_RECODE.WS_PARS_INFO[WS_VARIABLES.I-1].LCL_BR1 = LNCIPAMT.PART_DATA[WS_VARIABLES.I-1].LOCAL_BANK_FLAG;
                WS_OUT_RECODE.WS_PARS_INFO[WS_VARIABLES.I-1].ADJ_FLG1 = LNCIPAMT.PART_DATA[WS_VARIABLES.I-1].ADJ_BANK_FLAG;
                WS_OUT_RECODE.WS_PARS_INFO[WS_VARIABLES.I-1].REL_TYP1 = LNCIPAMT.PART_DATA[WS_VARIABLES.I-1].REL_TYPE;
                WS_OUT_RECODE.WS_PARS_INFO[WS_VARIABLES.I-1].PY_P_AMT1 = LNCIPAMT.PART_DATA[WS_VARIABLES.I-1].PART_P_AMT;
                WS_OUT_RECODE.WS_PARS_INFO[WS_VARIABLES.I-1].PY_I_AMT1 = LNCIPAMT.PART_DATA[WS_VARIABLES.I-1].PART_I_AMT;
                WS_OUT_RECODE.WS_PARS_INFO[WS_VARIABLES.I-1].PY_O_AMT1 = LNCIPAMT.PART_DATA[WS_VARIABLES.I-1].PART_O_AMT;
                WS_OUT_RECODE.WS_PARS_INFO[WS_VARIABLES.I-1].PY_L_AMT1 = LNCIPAMT.PART_DATA[WS_VARIABLES.I-1].PART_L_AMT;
            }
        }
        R000_OUTPUT_WRITE();
        if (pgmRtn) return;
    }
    public void B300_GET_AC_INFO() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNRSETL);
        LNRSETL.KEY.CONTRACT_NO = LNCSPDQ.COMM_DATA.CTA_INFO.CTA_NO;
        LNRSETL.KEY.CI_TYPE = 'B';
        LNRSETL.KEY.SETTLE_TYPE = '2';
        WS_DB_VARS.SEQ_NO = 0;
        T000_STARTBR_FOR_SEQ_PROC();
        if (pgmRtn) return;
        T000_READNEXT_SETL_PROC();
        if (pgmRtn) return;
        for (WS_VARIABLES.IDXA = 1; WS_VARIABLES.IDXA <= 5 
            && WS_COND_FLG.SETL_FOUND_FLG != 'N'; WS_VARIABLES.IDXA += 1) {
            WS_VARIABLES.WS_AC_INFO[WS_VARIABLES.IDXA-1].AC_TYP = LNRSETL.AC_TYP;
            WS_VARIABLES.WS_AC_INFO[WS_VARIABLES.IDXA-1].PAY_AC = LNRSETL.AC;
            WS_VARIABLES.WS_AC_INFO[WS_VARIABLES.IDXA-1].PAY_CCY = LNRSETL.KEY.CCY;
            WS_VARIABLES.WS_AC_INFO[WS_VARIABLES.IDXA-1].PAY_TYP = LNRSETL.CCY_TYP;
            if (WS_VARIABLES.WS_AC_INFO[WS_VARIABLES.IDXA-1].AC_TYP.equalsIgnoreCase("01")
                || WS_VARIABLES.WS_AC_INFO[WS_VARIABLES.IDXA-1].AC_TYP.equalsIgnoreCase("05")
                || WS_VARIABLES.WS_AC_INFO[WS_VARIABLES.IDXA-1].AC_TYP.equalsIgnoreCase("06")) {
                B910_GET_DD_AVABAL();
                if (pgmRtn) return;
            } else if (WS_VARIABLES.WS_AC_INFO[WS_VARIABLES.IDXA-1].AC_TYP.equalsIgnoreCase("02")) {
                B920_GET_SUSP_AC_AVABAL();
                if (pgmRtn) return;
            } else if (WS_VARIABLES.WS_AC_INFO[WS_VARIABLES.IDXA-1].AC_TYP.equalsIgnoreCase("03")) {
                B930_GET_NOS_AC_AVABAL();
                if (pgmRtn) return;
            } else {
            }
            T000_READNEXT_SETL_PROC();
            if (pgmRtn) return;
        }
        T000_ENDBR_SETL_PROC();
        if (pgmRtn) return;
    }
    public void B910_GET_DD_AVABAL() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, DDCIQBAL);
        DDCIQBAL.DATA.AC = WS_VARIABLES.WS_AC_INFO[WS_VARIABLES.IDXA-1].PAY_AC;
        DDCIQBAL.DATA.CCY = WS_VARIABLES.WS_AC_INFO[WS_VARIABLES.IDXA-1].PAY_CCY;
        DDCIQBAL.DATA.CCY_TYPE = WS_VARIABLES.WS_AC_INFO[WS_VARIABLES.IDXA-1].PAY_TYP;
        S000_CALL_DDZIQBAL();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, DDCIQBAL.DATA.AC);
        WS_VARIABLES.WS_AC_INFO[WS_VARIABLES.IDXA-1].PAY_AC_BAL = DDCIQBAL.DATA.AVL_BAL;
    }
    public void B920_GET_SUSP_AC_AVABAL() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, AICPQMIB);
        AICPQMIB.INPUT_DATA.AC = WS_VARIABLES.WS_AC_INFO[WS_VARIABLES.IDXA-1].PAY_AC;
        AICPQMIB.INPUT_DATA.CCY = WS_VARIABLES.WS_AC_INFO[WS_VARIABLES.IDXA-1].PAY_CCY;
        S000_CALL_AIZPQMIB();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, AICPQMIB.OUTPUT_DATA.CBAL);
        WS_VARIABLES.WS_AC_INFO[WS_VARIABLES.IDXA-1].PAY_AC_BAL = AICPQMIB.OUTPUT_DATA.CBAL;
    }
    public void B930_GET_NOS_AC_AVABAL() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, IBCQINF);
        IBCQINF.INPUT_DATA.NOSTRO_CD = WS_VARIABLES.WS_AC_INFO[WS_VARIABLES.IDXA-1].PAY_AC;
        IBCQINF.INPUT_DATA.CCY = WS_VARIABLES.WS_AC_INFO[WS_VARIABLES.IDXA-1].PAY_CCY;
        S000_CALL_IBZQINF();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, IBCQINF.OUTPUT_DATA.VALUE_BAL);
        WS_VARIABLES.WS_AC_INFO[WS_VARIABLES.IDXA-1].PAY_AC_BAL = IBCQINF.OUTPUT_DATA.VALUE_BAL;
    }
    public void R000_OUTPUT_WRITE() throws IOException,SQLException,Exception {
        WS_OUT_RECODE.WS_OUT_HEAD.O_CTA_NO = LNCSPDQ.COMM_DATA.CTA_INFO.CTA_NO;
        WS_OUT_RECODE.WS_OUT_HEAD.O_LN_STS = LNCSPDQ.COMM_DATA.CTA_INFO.LN_STS;
        WS_OUT_RECODE.WS_OUT_HEAD.O_BR = LNCSPDQ.COMM_DATA.CTA_INFO.BR;
        WS_OUT_RECODE.WS_OUT_HEAD.O_CI_NO = LNCSPDQ.COMM_DATA.CTA_INFO.CI_NO;
        WS_OUT_RECODE.WS_OUT_HEAD.O_CI_CNM = LNCSPDQ.COMM_DATA.CTA_INFO.CI_CNM;
        WS_OUT_RECODE.WS_OUT_HEAD.O_PROD_CD = LNCSPDQ.COMM_DATA.CTA_INFO.PROD_CD;
        WS_OUT_RECODE.WS_OUT_HEAD.O_PD_DESC = LNCSCKPD.PROD_NM;
        WS_OUT_RECODE.WS_OUT_HEAD.O_CCY = LNCSPDQ.COMM_DATA.CTA_INFO.CCY;
        WS_OUT_RECODE.WS_OUT_HEAD.O_LON_PRIN = LNCSPDQ.COMM_DATA.CTA_INFO.LON_PRIN;
        WS_OUT_RECODE.WS_OUT_HEAD.O_LON_BAL = LNCSPDQ.COMM_DATA.CTA_INFO.LON_BAL;
        WS_OUT_RECODE.WS_OUT_HEAD.O_P_P_BAL = LNCSPDQ.COMM_DATA.CTA_INFO.P_P_BAL;
        WS_OUT_RECODE.WS_OUT_HEAD.O_O_P_BAL = LNCSPDQ.COMM_DATA.CTA_INFO.O_P_BAL;
        WS_OUT_RECODE.WS_OUT_HEAD.O_CUR_RAT = WS_VARIABLES.CUR_RAT;
        WS_OUT_RECODE.WS_OUT_HEAD.O_CUR_PO_RAT = WS_VARIABLES.CUR_PO_RAT;
        WS_OUT_RECODE.WS_OUT_HEAD.O_D_I_AMT = LNCSPDQ.COMM_DATA.CTA_INFO.D_I_AMT;
        WS_OUT_RECODE.WS_OUT_HEAD.O_TR_VAL_DATE = LNCSPDQ.COMM_DATA.TR_VAL_DATE;
        WS_OUT_RECODE.WS_OUT_HEAD.O_TOT_AMT = LNCSPDQ.COMM_DATA.TOT_AMTS.TOT_AMT;
        WS_OUT_RECODE.WS_OUT_HEAD.O_TOT_P_AMT = LNCSPDQ.COMM_DATA.TOT_AMTS.TOT_P_AMT;
        WS_OUT_RECODE.WS_OUT_HEAD.O_TOT_I_AMT = LNCSPDQ.COMM_DATA.TOT_AMTS.TOT_I_AMT;
        WS_OUT_RECODE.WS_OUT_HEAD.O_TOT_O_AMT = LNCSPDQ.COMM_DATA.TOT_AMTS.TOT_O_AMT;
        WS_OUT_RECODE.WS_OUT_HEAD.O_TOT_L_AMT = LNCSPDQ.COMM_DATA.TOT_AMTS.TOT_L_AMT;
        WS_OUT_RECODE.WS_OUT_HEAD.O_P_O_DT = LNCSPDQ.COMM_DATA.TOT_AMTS.P_O_DT;
        WS_OUT_RECODE.WS_OUT_HEAD.O_I_L_DT = LNCSPDQ.COMM_DATA.TOT_AMTS.I_L_DT;
        WS_OUT_RECODE.WS_OUT_HEAD.O_TAC_MGT_AMT = LNCSPDQ.COMM_DATA.TOT_AMTS.TAC_MGT_AMT;
        WS_OUT_RECODE.WS_OUT_HEAD.O_THRG_AMT = LNCSPDQ.COMM_DATA.TOT_AMTS.THRG_AMT;
        WS_OUT_RECODE.WS_OUT_HEAD.O_T_I_AMT = LNCSPDQ.COMM_DATA.TOT_AMTS.T_I_AMT;
        WS_OUT_RECODE.WS_OUT_HEAD.O_T_O_AMT = LNCSPDQ.COMM_DATA.TOT_AMTS.T_O_AMT;
        WS_OUT_RECODE.WS_OUT_HEAD.O_T_L_AMT = LNCSPDQ.COMM_DATA.TOT_AMTS.T_L_AMT;
        WS_OUT_RECODE.WS_OUT_HEAD.WS_O_PARTI_INFO.O_PARTI_CINO = LNCSPDQ.COMM_DATA.PARTI_INFO.PARTI_CINO;
        WS_OUT_RECODE.WS_OUT_HEAD.WS_O_PARTI_INFO.O_PARTI_NAME = LNCSPDQ.COMM_DATA.PARTI_INFO.PARTI_NAME;
        WS_OUT_RECODE.WS_OUT_HEAD.WS_O_PARTI_INFO.O_PARTI_CNTY = LNCSPDQ.COMM_DATA.PARTI_INFO.PARTI_CNTY;
        WS_OUT_RECODE.WS_OUT_HEAD.O_THRG_AMT = LNCSPDQ.COMM_DATA.TOT_AMTS.THRG_AMT;
        for (WS_VARIABLES.IDXA = 1; WS_VARIABLES.IDXA <= 5 
            && WS_VARIABLES.WS_AC_INFO[WS_VARIABLES.IDXA-1].PAY_AC.trim().length() != 0; WS_VARIABLES.IDXA += 1) {
            WS_OUT_RECODE.WS_OUT_HEAD.WS_O_AC_INFO[WS_VARIABLES.IDXA-1].O_AC_TYP = WS_VARIABLES.WS_AC_INFO[WS_VARIABLES.IDXA-1].AC_TYP;
            WS_OUT_RECODE.WS_OUT_HEAD.WS_O_AC_INFO[WS_VARIABLES.IDXA-1].O_PAY_AC = WS_VARIABLES.WS_AC_INFO[WS_VARIABLES.IDXA-1].PAY_AC;
            WS_OUT_RECODE.WS_OUT_HEAD.WS_O_AC_INFO[WS_VARIABLES.IDXA-1].O_PAY_AC_BAL = WS_VARIABLES.WS_AC_INFO[WS_VARIABLES.IDXA-1].PAY_AC_BAL;
        }
        IBS.init(SCCGWA, SCCFMT);
        JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, SCCGWA.COMM_AREA.TR_ID);
        if (JIBS_tmp_str[0].equalsIgnoreCase("0134010")) {
            if ((!SCCGWA.COMM_AREA.CHNL.equalsIgnoreCase("101") 
                && !SCCGWA.COMM_AREA.CHNL.equalsIgnoreCase("10101") 
                && !SCCGWA.COMM_AREA.CHNL.equalsIgnoreCase("10102")) 
                || LNCSPDQ.ERR_FLG == 'N') {
                if (WS_OUT_RECODE.WS_OUT_HEAD.O_TOT_AMT == 0) {
                    IBS.CPY2CLS(SCCGWA, ERROR_MSG.NOT_CUR_TOCUR, LNCSPDQ.RC);
                    Z_RET();
                    if (pgmRtn) return;
                }
            }
            SCCFMT.FMTID = "LN401";
        }
        SCCFMT.DATA_PTR = WS_OUT_RECODE;
        SCCFMT.DATA_LEN = 9750;
        IBS.FMT(SCCGWA, SCCFMT);
    }
    public void R000_CALC_ARREARS_DAYS() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, SCCCLDT);
        SCCCLDT.DATE1 = WS_VARIABLES.DATE;
        SCCCLDT.DATE2 = LNCSPDQ.COMM_DATA.TR_VAL_DATE;
        S000_CALL_SCCCLDT();
        if (pgmRtn) return;
        WS_VARIABLES.DAYS = SCCCLDT.DAYS;
    }
    public void T01_STARTBR_LNTRCVD() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNRRCVD);
        LNRRCVD.KEY.CONTRACT_NO = LNCSPDQ.COMM_DATA.CTA_INFO.CTA_NO;
        if (LNCSPDQ.COMM_DATA.CTA_INFO.CTA_SEQ.trim().length() == 0) LNRRCVD.KEY.SUB_CTA_NO = 0;
        else LNRRCVD.KEY.SUB_CTA_NO = Integer.parseInt(LNCSPDQ.COMM_DATA.CTA_INFO.CTA_SEQ);
        LNRRCVD.REPY_STS = '2';
        LNRRCVD.DUE_DT = LNCSPDQ.COMM_DATA.TR_VAL_DATE;
        LNRRCVD.KEY.SUBS_PROJ_NO = 0;
        CEP.TRC(SCCGWA, LNRRCVD.KEY.CONTRACT_NO);
        CEP.TRC(SCCGWA, LNRRCVD.KEY.SUB_CTA_NO);
        CEP.TRC(SCCGWA, LNRRCVD.REPY_STS);
        CEP.TRC(SCCGWA, LNRRCVD.DUE_DT);
        LNTRCVD_BR.rp = new DBParm();
        LNTRCVD_BR.rp.TableName = "LNTRCVD";
        LNTRCVD_BR.rp.where = "CONTRACT_NO = :LNRRCVD.KEY.CONTRACT_NO "
            + "AND SUB_CTA_NO = :LNRRCVD.KEY.SUB_CTA_NO "
            + "AND DUE_DT <= :LNRRCVD.DUE_DT "
            + "AND SUBS_PROJ_NO = :LNRRCVD.KEY.SUBS_PROJ_NO "
            + "AND REPY_STS < > :LNRRCVD.REPY_STS";
        LNTRCVD_BR.rp.order = "DUE_DT , AMT_TYP";
        IBS.STARTBR(SCCGWA, LNRRCVD, this, LNTRCVD_BR);
    }
    public void T01_READNEXT_LNTRCVD() throws IOException,SQLException,Exception {
        WS_COND_FLG.FOUND_FLG = ' ';
        IBS.READNEXT(SCCGWA, LNRRCVD, this, LNTRCVD_BR);
        CEP.TRC(SCCGWA, LNRRCVD.KEY.SUB_CTA_NO);
        CEP.TRC(SCCGWA, LNRRCVD.DUE_DT);
        CEP.TRC(SCCGWA, LNRRCVD.KEY.AMT_TYP);
        if (SCCGWA.COMM_AREA.DBIO_FLG == '0') {
            WS_COND_FLG.FOUND_FLG = 'Y';
        } else {
            WS_COND_FLG.FOUND_FLG = 'N';
        }
    }
    public void T01_ENDBR_LNTRCVD() throws IOException,SQLException,Exception {
        IBS.ENDBR(SCCGWA, LNTRCVD_BR);
    }
    public void B320_GET_WOF_AMT() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCCNEX);
        LNCCNEX.COMM_DATA.INQ_CODE = "INQUDUP";
        LNCCNEX.COMM_DATA.LN_AC = LNCSPDQ.COMM_DATA.CTA_INFO.CTA_NO;
        LNCCNEX.COMM_DATA.SUF_NO = "" + 0;
        JIBS_tmp_int = LNCCNEX.COMM_DATA.SUF_NO.length();
        for (int i=0;i<0-JIBS_tmp_int;i++) LNCCNEX.COMM_DATA.SUF_NO = "0" + LNCCNEX.COMM_DATA.SUF_NO;
        S000_CALL_LNZCNEX();
        if (pgmRtn) return;
        WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].P_AMT += LNCCNEX.COMM_DATA.INQ_AMT;
        CEP.TRC(SCCGWA, WS_RCV_DATAS.WS_RCV_DATA[WS_VARIABLES.I-1].P_AMT);
    }
    public void T000_READ_LNTCTPY() throws IOException,SQLException,Exception {
        LNTCTPY_RD = new DBParm();
        LNTCTPY_RD.TableName = "LNTCTPY";
        LNTCTPY_RD.where = "CONTRACT_NO = :LNRCTPY.KEY.CONTRACT_NO "
            + "AND TR_TYP = '1'";
        LNTCTPY_RD.fst = true;
        LNTCTPY_RD.order = "TRAN_DATE DESC";
        IBS.READ(SCCGWA, LNRCTPY, this, LNTCTPY_RD);
        if (SCCGWA.COMM_AREA.DBIO_FLG == '1') {
            IBS.CPY2CLS(SCCGWA, ERROR_MSG.LN_ERR_CTPY_NOTFND, LNCSPDQ.RC);
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void S000_CALL_LNZAPRDM() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-SRC-APRD-MAINT", LNCAPRDM);
        if (LNCAPRDM.RC.RC_RTNCODE != 0) {
            IBS.CPY2CLS(SCCGWA, LNCAPRDM.RC.RC_APP, LNCSPDQ.RC);
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void S000_CALL_SCCCLDT() throws IOException,SQLException,Exception {
        SCSSCLDT SCSSCLDT1 = new SCSSCLDT();
        SCSSCLDT1.MP(SCCGWA, SCCCLDT);
        if (SCCCLDT.RC != 0) {
            LNCSPDQ.RC.RC_APP = "SC";
            LNCSPDQ.RC.RC_RTNCODE = SCCCLDT.RC;
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void S000_CALL_LNZRWOFF() throws IOException,SQLException,Exception {
        LNCRWOFF.REC_PTR = LNRWOFF;
        LNCRWOFF.REC_LEN = 49742;
        IBS.CALLCPN(SCCGWA, "LN-RSC-LNTWOFF", LNCRWOFF);
        if (LNCRWOFF.RC.RC_CODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, LNCRWOFF.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], LNCSPDQ.RC);
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void S000_CALL_LNZLCCM() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-FUN-LC-CMP", LNCLCCM);
        CEP.TRC(SCCGWA, LNCLCCM.COMM_DATA.LC_AMT);
        if (LNCLCCM.RC.RC_RTNCODE != 0) {
            LNCSPDQ.RC.RC_APP = LNCLCCM.RC.RC_APP;
            LNCSPDQ.RC.RC_RTNCODE = LNCLCCM.RC.RC_RTNCODE;
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void S000_CALL_LNZICUT() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-FUN-INT-CUT", LNCICUT);
        if (LNCICUT.RC.RC_RTNCODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, LNCICUT.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], LNCSPDQ.RC);
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void S000_CALL_IBZQINF() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "IB-IBZQINF", IBCQINF);
    }
    public void S000_CALL_AIZPQMIB() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "AI-P-INQ-MIB", AICPQMIB);
    }
    public void S000_CALL_DDZIQBAL() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "DD-I-INQ-CCY-BAL", DDCIQBAL, true);
    }
    public void T000_STARTBR_FOR_SEQ_PROC() throws IOException,SQLException,Exception {
        LNTSETL_BR.rp = new DBParm();
        LNTSETL_BR.rp.TableName = "LNTSETL";
        LNTSETL_BR.rp.where = "CONTRACT_NO = :LNRSETL.KEY.CONTRACT_NO "
            + "AND CI_TYPE = :LNRSETL.KEY.CI_TYPE "
            + "AND SETTLE_TYPE = :LNRSETL.KEY.SETTLE_TYPE "
            + "AND SEQ_NO >= :WS_DB_VARS.SEQ_NO";
        LNTSETL_BR.rp.order = "SEQ_NO";
        IBS.STARTBR(SCCGWA, LNRSETL, this, LNTSETL_BR);
    }
    public void T000_READNEXT_SETL_PROC() throws IOException,SQLException,Exception {
        IBS.READNEXT(SCCGWA, LNRSETL, this, LNTSETL_BR);
        if (SCCGWA.COMM_AREA.DBIO_FLG == '0') {
            WS_COND_FLG.SETL_FOUND_FLG = 'Y';
        } else {
            WS_COND_FLG.SETL_FOUND_FLG = 'N';
        }
    }
    public void T000_ENDBR_SETL_PROC() throws IOException,SQLException,Exception {
        IBS.ENDBR(SCCGWA, LNTSETL_BR);
    }
    public void S000_CALL_LNZICLNQ() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-FUNC-LN-INFO", LNCCLNQ);
        if (LNCCLNQ.RC.RC_CODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, LNCCLNQ.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], LNCSPDQ.RC);
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void S000_CALL_LNZCNEX() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-FUN-CONT-EXHIBIT", LNCCNEX);
        if (LNCCNEX.RC.RC_RTNCODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, LNCCNEX.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], LNCSPDQ.RC);
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void S000_CALL_LNZICTLM() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-SRC-ICTL-MAINT", LNCICTLM);
        if (LNCICTLM.RC.RC_RTNCODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, LNCICTLM.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], LNCSPDQ.RC);
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void S000_CALL_LNZIPAMT() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-INQ-PAR-AMT", LNCIPAMT);
        if (LNCIPAMT.RC.RC_CODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, LNCIPAMT.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], LNCSPDQ.RC);
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void S000_CALL_LNZSCKPD() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-S-CHK-PROD", LNCSCKPD);
    }
    public void T000_STARTBR_LNTRCVD() throws IOException,SQLException,Exception {
        LNTRCVD_BR.rp = new DBParm();
        LNTRCVD_BR.rp.TableName = "LNTRCVD";
        LNTRCVD_BR.rp.where = "CONTRACT_NO = :LNRRCVD.KEY.CONTRACT_NO";
        IBS.STARTBR(SCCGWA, LNRRCVD, this, LNTRCVD_BR);
    }
    public void T000_READNEXT_LNTRCVD() throws IOException,SQLException,Exception {
        IBS.READNEXT(SCCGWA, LNRRCVD, this, LNTRCVD_BR);
    }
    public void T000_ENDBR_LNTRCVD() throws IOException,SQLException,Exception {
        IBS.ENDBR(SCCGWA, LNTRCVD_BR);
    }
    public void T000_STARTBR_LNTINTA() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNRINTA);
        LNRINTA.KEY.CONTRACT_NO = LNCSPDQ.COMM_DATA.CTA_INFO.CTA_NO;
        if (LNCSPDQ.COMM_DATA.CTA_INFO.CTA_SEQ.trim().length() == 0) LNRINTA.KEY.SUB_CTA_NO = 0;
        else LNRINTA.KEY.SUB_CTA_NO = Integer.parseInt(LNCSPDQ.COMM_DATA.CTA_INFO.CTA_SEQ);
        LNRINTA.KEY.REPY_MTH = 'I';
        LNRINTA.KEY.ADJ_SEQ = 0;
        WS_DB_VARS.BEG_DT = LNCICUT.COMM_DATA.BEG_DATE;
        WS_DB_VARS.END_DT = LNCICUT.COMM_DATA.END_DATE;
        LNTINTA_BR.rp = new DBParm();
        LNTINTA_BR.rp.TableName = "LNTINTA";
        LNTINTA_BR.rp.where = "CONTRACT_NO = :LNRINTA.KEY.CONTRACT_NO "
            + "AND SUB_CTA_NO = :LNRINTA.KEY.SUB_CTA_NO "
            + "AND REPY_MTH = :LNRINTA.KEY.REPY_MTH "
            + "AND ADJ_SEQ > :LNRINTA.KEY.ADJ_SEQ "
            + "AND ADJ_VAL_DT > :WS_DB_VARS.BEG_DT "
            + "AND ADJ_VAL_DT < :WS_DB_VARS.END_DT";
        IBS.STARTBR(SCCGWA, LNRINTA, this, LNTINTA_BR);
    }
    public void T000_READNEXT_LNTINTA() throws IOException,SQLException,Exception {
        IBS.READNEXT(SCCGWA, LNRINTA, this, LNTINTA_BR);
    }
    public void T000_ENDBR_LNTINTA() throws IOException,SQLException,Exception {
        IBS.ENDBR(SCCGWA, LNTINTA_BR);
    }
    public void T000_READ_LNTRCVD() throws IOException,SQLException,Exception {
        WS_COND_FLG.RCVD_FOUND_FLG = 'N';
        IBS.init(SCCGWA, LNRRCVD);
        LNRRCVD.KEY.CONTRACT_NO = LNCSPDQ.COMM_DATA.CTA_INFO.CTA_NO;
        LNRRCVD.KEY.SUB_CTA_NO = 0;
        WS_DB_VARS.VAT_DT = LNCSPDQ.COMM_DATA.TR_VAL_DATE;
        LNTRCVD_RD = new DBParm();
        LNTRCVD_RD.TableName = "LNTRCVD";
        LNTRCVD_RD.where = "CONTRACT_NO = :LNRRCVD.KEY.CONTRACT_NO "
            + "AND SUB_CTA_NO = :LNRRCVD.KEY.SUB_CTA_NO "
            + "AND ( AMT_TYP = 'C' "
            + "OR AMT_TYP = 'I' ) "
            + "AND VAL_DT <= :WS_DB_VARS.VAT_DT "
            + "AND DUE_DT > :WS_DB_VARS.VAT_DT";
        LNTRCVD_RD.fst = true;
        IBS.READ(SCCGWA, LNRRCVD, this, LNTRCVD_RD);
        if (SCCGWA.COMM_AREA.DBIO_FLG == '0') {
            WS_COND_FLG.RCVD_FOUND_FLG = 'Y';
        }
    }
    public void T000_READ_LNTPARS() throws IOException,SQLException,Exception {
        LNTPARS_RD = new DBParm();
        LNTPARS_RD.TableName = "LNTPARS";
        LNTPARS_RD.where = "CONTRACT_NO = :LNRPARS.KEY.CONTRACT_NO "
            + "AND STATUS = :LNRPARS.STATUS "
            + "AND ADJ_BANK_FLAG = :LNRPARS.ADJ_BANK_FLAG";
        LNTPARS_RD.fst = true;
        IBS.READ(SCCGWA, LNRPARS, this, LNTPARS_RD);
        if (SCCGWA.COMM_AREA.DBIO_FLG == '0') {
        } else if (SCCGWA.COMM_AREA.DBIO_FLG == '1') {
            IBS.CPY2CLS(SCCGWA, ERROR_MSG.LN_ADJ_BANK_NOT_EXIST, LNCSPDQ.RC);
            Z_RET();
            if (pgmRtn) return;
        } else {
            IBS.CPY2CLS(SCCGWA, ERROR_MSG.LN_ERR_SYS_ERR, LNCSPDQ.RC);
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void Z_RET() throws IOException,SQLException,Exception {
    if (SCCGWA.COMM_AREA.BSP_FLG.equalsIgnoreCase("BSP") || SCCGWA.COMM_AREA.CHNL.equalsIgnoreCase("BAT")) { //FROM #IFDEF BAT
        if (LNCSPDQ.RC.RC_RTNCODE != 0) {
            CEP.TRC(SCCGWA, "LNCSPDQ=");
            CEP.TRC(SCCGWA, LNCSPDQ);
        }
    } //FROM #ENDIF
        pgmRtn = true;
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
