package com.hisun.LN;

public class LNZSCSTS_WS_LOAN_CONT_AREA {
    short WS_LOAN_CONT_AREA_LEN1 = 0;
    String WS_LOAN_CONT_AREA_TEXT1 = " ";
    LNZSCSTS_REDEFINES12 REDEFINES12 = new LNZSCSTS_REDEFINES12();
}
