package com.hisun.LN;

import java.io.IOException;
import java.sql.SQLException;

import com.hisun.BP.BPCPFHIS;
import com.hisun.SC.SCCCALL;
import com.hisun.SC.SCCEXCP;
import com.hisun.SC.SCCFMT;
import com.hisun.SC.SCCGWA;
import com.hisun.SC.SCCMSG;

public class LNZSSYND {
    boolean pgmRtn = false;
    String K_FMT_CD = "LN210";
    String K_MMO_NORMAL = "12010001";
    String K_MMO_CANCEL = "12018888";
    short WS_I = 0;
    short WS_FEE_CNT = 0;
    short WS_LOC_BANK_NUM = 0;
    String WS_TR_MMO = " ";
    short WS_IDX = 0;
    double WS_TOT_AMT = 0;
    double WS_WC_AMT = 0;
    short WS_ADJ_SEQ = 0;
    LNZSSYND_WS_OUT_DATA WS_OUT_DATA = new LNZSSYND_WS_OUT_DATA();
    LNCMSG_ERROR_MSG LNCMSG_ERROR_MSG = new LNCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCFMT SCCFMT = new SCCFMT();
    SCCMSG SCCMSG = new SCCMSG();
    LNCIGECR LNCIGECR = new LNCIGECR();
    LNCPPMQ LNCPPMQ = new LNCPPMQ();
    LNCSWLAD LNCSLNCR = new LNCSWLAD();
    LNCSWLAD LNCSLDRW = new LNCSWLAD();
    LNCICAL LNCICAL = new LNCICAL();
    LNCSLCRP LNCSLCRP = new LNCSLCRP();
    BPCPFHIS BPCPFHIS = new BPCPFHIS();
    LNRAGRE LNRAGRE = new LNRAGRE();
    LNCO2100 LNCO2100 = new LNCO2100();
    LNRICTL LNRICTL = new LNRICTL();
    SCCGWA SCCGWA;
    LNCSSYND LNCSSYND;
    public void MP(SCCGWA SCCGWA, LNCSSYND LNCSSYND) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        this.LNCSSYND = LNCSSYND;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        if (pgmRtn) return;
        B000_MAIN_PROC();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, "LNZSSYND return!");
        Z_RET();
        if (pgmRtn) return;
        JIBS_RETURN();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        LNCSSYND.RC.RC_MMO = "LN";
        LNCSSYND.RC.RC_CODE = 0;
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        if (SCCGWA.COMM_AREA.CANCEL_IND != 'Y') {
            B100_CTEATE_CONT_NO();
            if (pgmRtn) return;
        }
        R000_MAKE_LNCSLNCR_DATA();
        if (pgmRtn) return;
        B200_CTEATE_LOAN_INF();
        if (pgmRtn) return;
        B300_MAKE_PARTBK_LOAN();
        if (pgmRtn) return;
        B400_MAKE_LOAN_PROC();
        if (pgmRtn) return;
        if (SCCGWA.COMM_AREA.CANCEL_IND != 'Y') {
            if (LNCSSYND.DATA.CAL_FSDT == SCCGWA.COMM_AREA.AC_DATE) {
                B500_INTEREST_SETL_PROC();
                if (pgmRtn) return;
            }
            B600_FMT_OUT_PROC();
            if (pgmRtn) return;
        }
    }
    public void B100_CTEATE_CONT_NO() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCIGECR);
        LNCIGECR.INPUT_INFO.DRAW_NO = LNCSSYND.DATA.DRAW_NO;
        LNCIGECR.INPUT_INFO.PAPER_NO = LNCSSYND.DATA.PAPER_NO;
        LNCIGECR.INPUT_INFO.CI_NO = LNCSSYND.DATA.CI_NO;
        LNCIGECR.INPUT_INFO.CTA_FROM = '0';
        LNCIGECR.INPUT_INFO.BOOK_BR = LNCSSYND.DATA.BOOK_BR;
        LNCIGECR.INPUT_INFO.CCY = LNCSSYND.DATA.CCY;
        S000_CALL_LNZIGECR();
        if (pgmRtn) return;
        LNCSSYND.DATA.CONT_NO = LNCIGECR.OUTPOUT_INFO.CMMT_NO;
    }
    public void B200_CTEATE_LOAN_INF() throws IOException,SQLException,Exception {
        S000_CALL_LNZSLNCR();
        if (pgmRtn) return;
        if (SCCGWA.COMM_AREA.CANCEL_IND != 'Y') {
            IBS.init(SCCGWA, LNRICTL);
            LNRICTL.KEY.CONTRACT_NO = LNCSSYND.DATA.CONT_NO;
            LNRICTL.KEY.SUB_CTA_NO = 0;
            T000_READUPD_LNTICTL();
            if (pgmRtn) return;
            for (WS_I = 1; WS_I <= 10; WS_I += 1) {
                if (LNCSSYND.DATA.PART_INF[WS_I-1].LOC_BANK == 'Y') {
                    WS_LOC_BANK_NUM += 1;
                }
            }
            if (WS_LOC_BANK_NUM > 0) {
                if (LNRICTL.CTL_STSW == null) LNRICTL.CTL_STSW = "";
                JIBS_tmp_int = LNRICTL.CTL_STSW.length();
                for (int i=0;i<128-JIBS_tmp_int;i++) LNRICTL.CTL_STSW += " ";
                LNRICTL.CTL_STSW = LNRICTL.CTL_STSW.substring(0, 14 - 1) + "1" + LNRICTL.CTL_STSW.substring(14 + 1 - 1);
            }
            if (LNCSSYND.DATA.SYN_TYP == 'O') {
                if (LNRICTL.CTL_STSW == null) LNRICTL.CTL_STSW = "";
                JIBS_tmp_int = LNRICTL.CTL_STSW.length();
                for (int i=0;i<128-JIBS_tmp_int;i++) LNRICTL.CTL_STSW += " ";
                LNRICTL.CTL_STSW = LNRICTL.CTL_STSW.substring(0, 12 - 1) + "1" + LNRICTL.CTL_STSW.substring(12 + 1 - 1);
            } else {
                if (LNRICTL.CTL_STSW == null) LNRICTL.CTL_STSW = "";
                JIBS_tmp_int = LNRICTL.CTL_STSW.length();
                for (int i=0;i<128-JIBS_tmp_int;i++) LNRICTL.CTL_STSW += " ";
                LNRICTL.CTL_STSW = LNRICTL.CTL_STSW.substring(0, 13 - 1) + "1" + LNRICTL.CTL_STSW.substring(13 + 1 - 1);
            }
            T000_REWRITE_LNTICTL();
            if (pgmRtn) return;
        }
    }
    public void B300_MAKE_PARTBK_LOAN() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCSLCRP);
        LNCSLCRP.DRAW_NO = LNCSSYND.DATA.DRAW_NO;
        LNCSLCRP.CONT_NO = LNCSSYND.DATA.CONT_NO;
        LNCSLCRP.PRODMO = LNCSSYND.OTHER_DATA.PRODMO;
        LNCSLCRP.PROD_TYP = LNCSSYND.DATA.PROD_TYP;
        LNCSLCRP.CONT_AMT = LNCSSYND.DATA.CONT_AMT;
        LNCSLCRP.BOOK_BR = LNCSSYND.DATA.BOOK_BR;
        LNCSLCRP.CCY = LNCSSYND.DATA.CCY;
        LNCSLCRP.START_DT = LNCSSYND.DATA.START_DT;
        LNCSLCRP.ATO_DFLG = LNCSSYND.DATA.ATO_DFLG;
        LNCSLCRP.SYN_TYP = LNCSSYND.DATA.SYN_TYP;
        CEP.TRC(SCCGWA, LNCSSYND.DATA.PART_INF[1-1].PART_NO);
        CEP.TRC(SCCGWA, LNCSSYND.DATA.PART_INF[2-1].PART_NO);
        CEP.TRC(SCCGWA, LNCSSYND.DATA.PART_INF[3-1].PART_NO);
        CEP.TRC(SCCGWA, LNCSSYND.DATA.PART_INF[4-1].PART_NO);
        CEP.TRC(SCCGWA, LNCSSYND.DATA.PART_INF[1-1].PART_PCT);
        CEP.TRC(SCCGWA, LNCSSYND.DATA.PART_INF[2-1].PART_PCT);
        CEP.TRC(SCCGWA, LNCSSYND.DATA.PART_INF[3-1].PART_PCT);
        CEP.TRC(SCCGWA, LNCSSYND.DATA.PART_INF[4-1].PART_PCT);
        CEP.TRC(SCCGWA, LNCSSYND.DATA.PART_INF[1-1].PART_AMT);
        CEP.TRC(SCCGWA, LNCSSYND.DATA.PART_INF[2-1].PART_AMT);
        CEP.TRC(SCCGWA, LNCSSYND.DATA.PART_INF[3-1].PART_AMT);
        CEP.TRC(SCCGWA, LNCSSYND.DATA.PART_INF[4-1].PART_AMT);
        for (WS_I = 1; WS_I <= 10; WS_I += 1) {
            LNCSLCRP.PART_INF[WS_I-1].PART_NO = LNCSSYND.DATA.PART_INF[WS_I-1].PART_NO;
            LNCSLCRP.PART_INF[WS_I-1].BR = LNCSSYND.DATA.PART_INF[WS_I-1].BR;
            LNCSLCRP.PART_INF[WS_I-1].PART_NM = LNCSSYND.DATA.PART_INF[WS_I-1].PART_NM;
            LNCSLCRP.PART_INF[WS_I-1].LOC_BANK = LNCSSYND.DATA.PART_INF[WS_I-1].LOC_BANK;
            LNCSLCRP.PART_INF[WS_I-1].ADJ_FLG = LNCSSYND.DATA.PART_INF[WS_I-1].ADJ_FLG;
            LNCSLCRP.PART_INF[WS_I-1].REL_TYPE = LNCSSYND.DATA.PART_INF[WS_I-1].REL_TYPE;
            LNCSLCRP.PART_INF[WS_I-1].YHS_FLG = LNCSSYND.DATA.PART_INF[WS_I-1].YHS_FLG;
            LNCSLCRP.PART_INF[WS_I-1].YHS_AC = LNCSSYND.DATA.PART_INF[WS_I-1].YHS_AC;
            LNCSLCRP.PART_INF[WS_I-1].PART_PCT = LNCSSYND.DATA.PART_INF[WS_I-1].PART_PCT;
            LNCSLCRP.PART_INF[WS_I-1].PART_AMT = LNCSSYND.DATA.PART_INF[WS_I-1].PART_AMT;
            LNCSLCRP.PART_INF[WS_I-1].PART_ACT = LNCSSYND.DATA.PART_INF[WS_I-1].PART_ACT;
            LNCSLCRP.PART_INF[WS_I-1].PART_AC = LNCSSYND.DATA.PART_INF[WS_I-1].PART_AC;
        }
        CEP.TRC(SCCGWA, LNCSLCRP.PART_INF[1-1].PART_NO);
        CEP.TRC(SCCGWA, LNCSLCRP.PART_INF[2-1].PART_NO);
        CEP.TRC(SCCGWA, LNCSLCRP.PART_INF[3-1].PART_NO);
        CEP.TRC(SCCGWA, LNCSLCRP.PART_INF[4-1].PART_NO);
        CEP.TRC(SCCGWA, LNCSLCRP.PART_INF[1-1].PART_PCT);
        CEP.TRC(SCCGWA, LNCSLCRP.PART_INF[2-1].PART_PCT);
        CEP.TRC(SCCGWA, LNCSLCRP.PART_INF[3-1].PART_PCT);
        CEP.TRC(SCCGWA, LNCSLCRP.PART_INF[4-1].PART_PCT);
        CEP.TRC(SCCGWA, LNCSLCRP.PART_INF[1-1].PART_AMT);
        CEP.TRC(SCCGWA, LNCSLCRP.PART_INF[2-1].PART_AMT);
        CEP.TRC(SCCGWA, LNCSLCRP.PART_INF[3-1].PART_AMT);
        CEP.TRC(SCCGWA, LNCSLCRP.PART_INF[4-1].PART_AMT);
        S000_CALL_LNZSLCRP();
        if (pgmRtn) return;
    }
    public void B400_MAKE_LOAN_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCSLDRW);
        IBS.CLONE(SCCGWA, LNCSLNCR, LNCSLDRW);
        S000_CALL_LNZSLDRW();
        if (pgmRtn) return;
    }
    public void B500_INTEREST_SETL_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCICAL);
        LNCICAL.COMM_DATA.FUNC_CODE = 'U';
        LNCICAL.COMM_DATA.LN_AC = LNCSSYND.DATA.CONT_NO;
        LNCICAL.COMM_DATA.SUF_NO = "" + 0;
        JIBS_tmp_int = LNCICAL.COMM_DATA.SUF_NO.length();
        for (int i=0;i<0-JIBS_tmp_int;i++) LNCICAL.COMM_DATA.SUF_NO = "0" + LNCICAL.COMM_DATA.SUF_NO;
        LNCICAL.COMM_DATA.VAL_DATE = SCCGWA.COMM_AREA.AC_DATE;
        LNCICAL.COMM_DATA.FUNC_TYPE = ' ';
        S000_CALL_LNZICAL();
        if (pgmRtn) return;
    }
    public void B600_FMT_OUT_PROC() throws IOException,SQLException,Exception {
        R000_MAKE_OUTPUT_DATA();
        if (pgmRtn) return;
        IBS.init(SCCGWA, SCCFMT);
        SCCFMT.FMTID = K_FMT_CD;
        SCCFMT.DATA_PTR = LNCO2100;
        SCCFMT.DATA_LEN = 5022;
        IBS.FMT(SCCGWA, SCCFMT);
    }
    public void B700_FINANCE_HIS_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BPCPFHIS);
        BPCPFHIS.DATA.TX_DRCR_FLG = 'D';
        BPCPFHIS.DATA.PRINT_IND = 'Y';
        BPCPFHIS.DATA.JRNNO = SCCGWA.COMM_AREA.JRN_NO;
        BPCPFHIS.DATA.AC_DT = SCCGWA.COMM_AREA.AC_DATE;
        BPCPFHIS.DATA.VCHNO = SCCGWA.COMM_AREA.VCH_NO;
        BPCPFHIS.DATA.REF_NO = LNCSSYND.DATA.PAPER_NO;
        BPCPFHIS.DATA.AC = LNCSSYND.DATA.CONT_NO;
        BPCPFHIS.DATA.CI_NO = LNCSSYND.DATA.CI_NO;
        BPCPFHIS.DATA.TX_VAL_DT = LNCSSYND.DATA.START_DT;
        BPCPFHIS.DATA.TX_CCY = LNCSSYND.DATA.CCY;
        BPCPFHIS.DATA.TX_AMT = LNCSSYND.DATA.CONT_AMT;
        BPCPFHIS.DATA.PROD_CD = LNCSSYND.DATA.PROD_TYP;
        if (SCCGWA.COMM_AREA.CANCEL_IND == 'Y') {
            BPCPFHIS.DATA.TX_MMO = K_MMO_CANCEL;
        } else {
            BPCPFHIS.DATA.TX_MMO = K_MMO_NORMAL;
        }
        BPCPFHIS.DATA.RLT_AC = LNCSSYND.DATA.DRAW_AC;
        BPCPFHIS.DATA.FMT_CODE = K_FMT_CD;
        BPCPFHIS.DATA.FMT_LEN = 5022;
        BPCPFHIS.DATA.FMT_DATA = IBS.CLS2CPY(SCCGWA, LNCO2100);
        S000_CALL_BPZPFHIS();
        if (pgmRtn) return;
    }
    public void R000_MAKE_LNCSLNCR_DATA() throws IOException,SQLException,Exception {
        C000_COMP_BH_AMT();
        if (pgmRtn) return;
        for (WS_I = 1; LNCSSYND.DATA.PART_INF[WS_I-1].REL_TYPE != 'M'; WS_I += 1) {
            if (WS_I > 5) {
                IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_NOT_FIND_SUB, LNCSSYND.RC);
                Z_RET();
                if (pgmRtn) return;
            }
        }
        IBS.init(SCCGWA, LNCSLNCR);
        IBS.init(SCCGWA, LNRAGRE);
        LNRAGRE.PAPER_NO = LNCSSYND.DATA.PAPER_NO;
        LNRAGRE.DRAW_NO = LNCSSYND.DATA.DRAW_NO;
        T000_READ_LNTAGRE();
        if (pgmRtn) return;
        LNCSSYND.DATA.CONT_NO = LNRAGRE.KEY.CONTRACT_NO;
        LNCSLNCR.COMM_DATA.PAPER_NO = LNCSSYND.DATA.PAPER_NO;
        LNCSLNCR.COMM_DATA.DRAWR_NO = LNCSSYND.DATA.DRAW_NO;
        LNCSLNCR.COMM_DATA.CTA_NO = LNCSSYND.DATA.CONT_NO;
        LNCSLNCR.COMM_DATA.BOOK_BR = LNCSSYND.DATA.BOOK_BR;
        LNCSLNCR.COMM_DATA.DOMI_BR = LNCSSYND.DATA.BOOK_BR;
        LNCSLNCR.COMM_DATA.CI_NO = LNCSSYND.DATA.CI_NO;
        LNCSLNCR.COMM_DATA.PROD_CD = LNCSSYND.DATA.PROD_TYP;
        LNCSLNCR.COMM_DATA.VAL_DT = LNCSSYND.DATA.START_DT;
        LNCSLNCR.COMM_DATA.INT_PER_STRT = LNCSSYND.DATA.START_DT;
        LNCSLNCR.COMM_DATA.ACTV_DT = LNCSSYND.DATA.START_DT;
        LNCSLNCR.COMM_DATA.DUE_DT = LNCSSYND.DATA.MATU_DT;
        LNCSLNCR.COMM_DATA.CCY = LNCSSYND.DATA.CCY;
        LNCSLNCR.COMM_DATA.CCY_TYP = LNCSSYND.DATA.CCY_TYP;
        LNCSLNCR.COMM_DATA.CONT_AMT = LNCSSYND.DATA.CONT_AMT;
        if (LNCSSYND.DATA.PART_INF[WS_I-1].ADJ_FLG == 'Y') {
            LNCSLNCR.COMM_DATA.PRINCIPAL = WS_WC_AMT;
        } else {
            LNCSLNCR.COMM_DATA.PRINCIPAL = LNCSSYND.DATA.CONT_AMT * LNCSSYND.DATA.PART_INF[WS_I-1].PART_PCT / 100;
            bigD = new BigDecimal(LNCSLNCR.COMM_DATA.PRINCIPAL);
            LNCSLNCR.COMM_DATA.PRINCIPAL = bigD.setScale(2, RoundingMode.HALF_UP).doubleValue();
        }
        CEP.TRC(SCCGWA, LNCSLNCR.COMM_DATA.PRINCIPAL);
        LNCSLNCR.COMM_DATA.REPY_MTH = LNCSSYND.DATA.REPY_MTH;
        LNCSLNCR.COMM_DATA.INST_MTH = LNCSSYND.DATA.INST_MTH;
        LNCSLNCR.COMM_DATA.PAYI_PERD = LNCSSYND.DATA.PAYI_PER;
        LNCSLNCR.COMM_DATA.CAL_PERD_UNIT = LNCSSYND.DATA.CAL_PERU;
        LNCSLNCR.COMM_DATA.CAL_PERD = LNCSSYND.DATA.CAL_PERD;
        LNCSLNCR.COMM_DATA.CAL_PAY_DAY_TYP = LNCSSYND.DATA.PAY_DTYP;
        LNCSLNCR.COMM_DATA.CAL_PAY_DAY = LNCSSYND.DATA.CAL_DAY;
        LNCSLNCR.COMM_DATA.CAL_FST_DT = LNCSSYND.DATA.CAL_FSDT;
        LNCSLNCR.COMM_DATA.PYP_CIRC = LNCSSYND.DATA.PYP_CIRC;
        LNCSLNCR.COMM_DATA.PAYP_PERU = LNCSSYND.DATA.PYP_PERU;
        LNCSLNCR.COMM_DATA.PAYP_PERD = LNCSSYND.DATA.PYP_PERD;
        LNCSLNCR.COMM_DATA.SP_LNFLG = LNCSSYND.DATA.SP_LNFLG;
        LNCSLNCR.COMM_DATA.PHS_FLG = LNCSSYND.DATA.PHS_FLG;
        LNCSLNCR.COMM_DATA.PHS_NUM = LNCSSYND.DATA.PHS_NUM;
        for (WS_I = 1; WS_I <= 5; WS_I += 1) {
            LNCSLNCR.COMM_DATA.PHS_DATA[WS_I-1].PHS_TOT_TERM = LNCSSYND.DATA.PHS_INF[WS_I-1].PHS_TTRM;
            LNCSLNCR.COMM_DATA.PHS_DATA[WS_I-1].PHS_PERU = LNCSSYND.DATA.PHS_INF[WS_I-1].PHS_PERU;
            LNCSLNCR.COMM_DATA.PHS_DATA[WS_I-1].PHS_PERD = LNCSSYND.DATA.PHS_INF[WS_I-1].PHS_PERD;
            LNCSLNCR.COMM_DATA.PHS_DATA[WS_I-1].PHS_PRIN_AMT = LNCSSYND.DATA.PHS_INF[WS_I-1].PHS_PAMT;
            LNCSLNCR.COMM_DATA.PHS_DATA[WS_I-1].PHS_INST_MTH = LNCSSYND.DATA.PHS_INF[WS_I-1].PHS_ISMT;
        }
        LNCSLNCR.COMM_DATA.OCAL_PERD_UNIT = LNCSSYND.DATA.OLC_PERU;
        LNCSLNCR.COMM_DATA.OCAL_PERD = LNCSSYND.DATA.OLC_PERD;
        LNCSLNCR.COMM_DATA.DRAW_AC_TYP = LNCSSYND.DATA.DRAW_ACT;
        LNCSLNCR.COMM_DATA.DRAW_AC = LNCSSYND.DATA.DRAW_AC;
        LNCSLNCR.COMM_DATA.DRAW_BK_TP = LNCSSYND.DATA.DW_BK_TP;
        LNCSLNCR.COMM_DATA.DRAW_SEQ = LNCSSYND.DATA.DRAW_SEQ;
        LNCSLNCR.COMM_DATA.PAY_AC_TYP = LNCSSYND.DATA.PAY_AC_T;
        LNCSLNCR.COMM_DATA.PAY_AC = LNCSSYND.DATA.PAY_AC;
        LNCSLNCR.COMM_DATA.PAY_BK_TP = LNCSSYND.DATA.PA_BK_TP;
        LNCSLNCR.COMM_DATA.FS_CL_MTH = LNCSSYND.DATA.FS_CLMTH;
        LNCSLNCR.COMM_DATA.FS_CL_AMT = LNCSSYND.DATA.FS_CLAMT;
        LNCSLNCR.COMM_DATA.PAYI_ACT = LNCSSYND.DATA.PAYI_ACT;
        LNCSLNCR.COMM_DATA.PAYI_AC = LNCSSYND.DATA.PAYI_AC;
        LNCSLNCR.COMM_DATA.PAYI_SEQ = LNCSSYND.DATA.PAYI_SEQ;
        LNCSLNCR.COMM_DATA.AUTO_DFLG = LNCSSYND.DATA.ATO_DFLG;
        if (LNCSSYND.DATA.ATO_DFLG == 'Y') {
            LNCSSYND.DATA.ATO_AMT = LNCSLNCR.COMM_DATA.PRINCIPAL;
        }
        LNCSLNCR.COMM_DATA.AUTO_AMT = LNCSSYND.DATA.ATO_AMT;
        LNCSLNCR.COMM_DATA.ATO_ACT = LNCSSYND.DATA.ATO_ACT;
        LNCSLNCR.COMM_DATA.ATO_AC = LNCSSYND.DATA.ATO_AC;
        LNCSLNCR.COMM_DATA.GRA_TYP = LNCSSYND.DATA.GRA_TYP;
        LNCSLNCR.COMM_DATA.GRA_DAYS_ACC = LNCSSYND.DATA.GRA_DAYA;
        LNCSLNCR.COMM_DATA.P_GRA_MTH = LNCSSYND.DATA.P_GRA_MT;
        LNCSLNCR.COMM_DATA.I_GRA_MTH = LNCSSYND.DATA.C_GRA_MT;
        LNCSLNCR.COMM_DATA.INT_DAY_BASIS = LNCSSYND.DATA.INT_D_BA;
        LNCSLNCR.COMM_DATA.PSEQ_CD = LNCSSYND.DATA.PSEQ_CD;
        LNCSLNCR.COMM_DATA.PREP_CHR = LNCSSYND.DATA.PREP_CHR;
        LNCSLNCR.COMM_DATA.HAND_CHG_RATE = LNCSSYND.DATA.HAND_CHR;
        LNCSLNCR.COMM_DATA.HAND_CHG_MTH = LNCSSYND.DATA.HAND_CHM;
        LNCSLNCR.COMM_DATA.GUAP_REF = LNCSSYND.DATA.GUAPREF;
        LNCSLNCR.COMM_DATA.GUAR_PAY_SEQ = LNCSSYND.DATA.GUARPSEQ;
        for (WS_I = 1; WS_I <= 5; WS_I += 1) {
            LNCSLNCR.COMM_DATA.FEE_DATE[WS_I-1].FEE_CODE = LNCSSYND.DATA.FEE_INF[WS_I-1].FEE_CODE;
            LNCSLNCR.COMM_DATA.FEE_DATE[WS_I-1].FEE_AMT = LNCSSYND.DATA.FEE_INF[WS_I-1].FEE_AMT;
            if (LNCSSYND.DATA.FEE_INF[WS_I-1].FEE_CODE.trim().length() > 0) {
                WS_FEE_CNT += 1;
            }
        }
        LNCSLNCR.COMM_DATA.FEE_CNT = WS_FEE_CNT;
        LNCSLNCR.COMM_DATA.FEE_AC_TYP = LNCSSYND.DATA.FEE_ACT;
        LNCSLNCR.COMM_DATA.FEE_AC = LNCSSYND.DATA.FEE_AC;
        LNCSLNCR.COMM_DATA.TR_MMO = LNCSSYND.DATA.TR_MMO;
        LNCSLNCR.COMM_DATA.REMARK1 = LNCSSYND.DATA.REMARK;
        LNCSLNCR.COMM_DATA.CUSTM1 = LNCSSYND.DATA.CUSTM1;
        LNCSLNCR.COMM_DATA.CUSTM2 = LNCSSYND.DATA.CUSTM2;
        LNCSLNCR.COMM_DATA.CUSTM3 = LNCSSYND.DATA.CUSTM3;
        LNCSLNCR.COMM_DATA.BAR_CD = LNCSSYND.DATA.BAR_CD;
        LNCSLNCR.COMM_DATA.UNIT_CD = LNCSSYND.DATA.UNIT_CD;
        IBS.init(SCCGWA, LNCPPMQ);
        LNCPPMQ.KEY.REQ_INSTRUCT.REQ_MODULE_PARM = 'N';
        LNCPPMQ.KEY.REQ_INSTRUCT.REQ_COMMIT_PARM = 'N';
        LNCPPMQ.KEY.REQ_INSTRUCT.REQ_CONTRACT_PARM = 'Y';
        LNCPPMQ.KEY.KEY_METH = 'P';
        LNCPPMQ.KEY.KEY_VALUE.LEVEL = 'D';
        LNCPPMQ.KEY.KEY_VALUE.PROD_CD = LNCSSYND.DATA.PROD_TYP;
        if (LNCPPMQ.DATA_TXT.ACCRUAL_TYPE == ' ') {
            LNCSLNCR.COMM_DATA.ACCRUAL_TYPE = '0';
        }
        LNCSLNCR.COMM_DATA.FLT_MTH = '0';
        LNCSLNCR.COMM_DATA.VRTU_FLG = 'Y';
        if ("0".trim().length() == 0) LNCSLNCR.COMM_DATA.PAYP_GRACE = 0;
        else LNCSLNCR.COMM_DATA.PAYP_GRACE = Short.parseShort("0");
        if (LNCSSYND.DATA.PAY_DTYP == '2') {
            if ("1".trim().length() == 0) LNCSLNCR.COMM_DATA.CAL_PAY_DAY_TERM = 0;
            else LNCSLNCR.COMM_DATA.CAL_PAY_DAY_TERM = Short.parseShort("1");
        }
        LNCSLNCR.COMM_DATA.FLT_MTH = LNCSSYND.DATA.RAT_MTH;
        LNCSLNCR.COMM_DATA.FLT_PERD_UNIT = LNCSSYND.DATA.FLPD_UN;
        LNCSLNCR.COMM_DATA.FLT_PERD = LNCSSYND.DATA.INT_FLPD;
        LNCSLNCR.COMM_DATA.FLT_IPER = LNCSSYND.DATA.FLT_IPER;
        LNCSLNCR.COMM_DATA.FLT_ADJF = LNCSSYND.DATA.FLT_ADJF;
        LNCSLNCR.COMM_DATA.FIRST_FLT_FLG = LNCSSYND.DATA.FLT_FLG;
        LNCSLNCR.COMM_DATA.FIRST_FIX_DATE = (short) LNCSSYND.DATA.FLT_DAY;
        LNCSLNCR.COMM_DATA.FIRST_FLT_DT = LNCSSYND.DATA.FST_DAY;
        LNCSLNCR.COMM_DATA.NFLT_METHOD = LNCSSYND.DATA.FLT_MTH;
        LNCSLNCR.COMM_DATA.INT_RATE_TYPE = LNCSSYND.DATA.RAT_TYP;
        LNCSLNCR.COMM_DATA.INT_RATE_CLAS = LNCSSYND.DATA.RAT_PD;
        LNCSLNCR.COMM_DATA.RATE_VAR = LNCSSYND.DATA.RAT_VAR;
        LNCSLNCR.COMM_DATA.RATE_PCT = LNCSSYND.DATA.RAT_PCT;
        LNCSLNCR.COMM_DATA.RAT_INT = LNCSSYND.DATA.RAT_INT;
        LNCSLNCR.COMM_DATA.ALL_IN_RATE = LNCSSYND.DATA.IN_RATE;
        LNCSLNCR.COMM_DATA.PEN_RRAT = LNCSSYND.DATA.PEN_RRAT;
        LNCSLNCR.COMM_DATA.PEN_TYPE = LNCSSYND.DATA.PEN_TYP;
        LNCSLNCR.COMM_DATA.PEN_RATT = LNCSSYND.DATA.PEN_RATT;
        LNCSLNCR.COMM_DATA.PEN_RATC = LNCSSYND.DATA.PEN_RATC;
        LNCSLNCR.COMM_DATA.PEN_SPR = LNCSSYND.DATA.PEN_SPR;
        LNCSLNCR.COMM_DATA.PEN_PCT = LNCSSYND.DATA.PEN_PCT;
        LNCSLNCR.COMM_DATA.PEN_IRAT = LNCSSYND.DATA.PEN_IRAT;
        LNCSLNCR.COMM_DATA.INT_MTH = LNCSSYND.DATA.INT_MTH;
        LNCSLNCR.COMM_DATA.CPND_USE = LNCSSYND.DATA.CPND_USE;
        LNCSLNCR.COMM_DATA.CPND_RTYPE = LNCSSYND.DATA.CPND_RTY;
        LNCSLNCR.COMM_DATA.CPND_TYP = LNCSSYND.DATA.CPND_TYP;
        LNCSLNCR.COMM_DATA.CPND_RATT = LNCSSYND.DATA.CPNDRATT;
        LNCSLNCR.COMM_DATA.CPND_RATC = LNCSSYND.DATA.CPNDRATC;
        LNCSLNCR.COMM_DATA.CPND_SPR = LNCSSYND.DATA.CPND_SPR;
        LNCSLNCR.COMM_DATA.CPND_PCT = LNCSSYND.DATA.CPND_PCT;
        LNCSLNCR.COMM_DATA.CPND_IRATE = LNCSSYND.DATA.CPNDRATE;
    }
    public void R000_MAKE_OUT_DATA() throws IOException,SQLException,Exception {
        WS_OUT_DATA.WS_OUT_PAPER_NO = LNCSLDRW.COMM_DATA.DRAWR_NO;
        WS_OUT_DATA.WS_OUT_DRAW_NO = LNCSLDRW.COMM_DATA.PAPER_NO;
        WS_OUT_DATA.WS_OUT_CONT_NO = LNCSLDRW.COMM_DATA.CTA_NO;
        WS_OUT_DATA.WS_OUT_BOOK_BR = LNCSLDRW.COMM_DATA.BOOK_BR;
        WS_OUT_DATA.WS_OUT_DOMI_BR = LNCSLDRW.COMM_DATA.DOMI_BR;
        WS_OUT_DATA.WS_OUT_CI_NO = LNCSLDRW.COMM_DATA.CI_NO;
        WS_OUT_DATA.WS_OUT_PROD_TYP = LNCSLDRW.COMM_DATA.PROD_CD;
        WS_OUT_DATA.WS_OUT_VCH_FLG = LNCSLDRW.COMM_DATA.VCH_FLG;
        WS_OUT_DATA.WS_OUT_START_DT = LNCSLDRW.COMM_DATA.VAL_DT;
        WS_OUT_DATA.WS_OUT_MATU_DT = LNCSLDRW.COMM_DATA.DUE_DT;
        WS_OUT_DATA.WS_OUT_CCY = LNCSLDRW.COMM_DATA.CCY;
        WS_OUT_DATA.WS_OUT_CONT_AMT = LNCSLDRW.COMM_DATA.CONT_AMT;
        WS_OUT_DATA.WS_OUT_CONT_AMT = LNCSLDRW.COMM_DATA.PRINCIPAL;
        WS_OUT_DATA.WS_OUT_REPY_MTH = LNCSLDRW.COMM_DATA.REPY_MTH;
        WS_OUT_DATA.WS_OUT_INST_MTH = LNCSLDRW.COMM_DATA.INST_MTH;
        WS_OUT_DATA.WS_OUT_PAYI_PER = LNCSLDRW.COMM_DATA.PAYI_PERD;
        WS_OUT_DATA.WS_OUT_CAL_PERU = LNCSLDRW.COMM_DATA.CAL_PERD_UNIT;
        WS_OUT_DATA.WS_OUT_CAL_PERD = LNCSLDRW.COMM_DATA.CAL_PERD;
        WS_OUT_DATA.WS_OUT_PAY_DTYP = LNCSLDRW.COMM_DATA.CAL_PAY_DAY_TYP;
        WS_OUT_DATA.WS_OUT_CAL_DAY = LNCSLDRW.COMM_DATA.CAL_PAY_DAY;
        WS_OUT_DATA.WS_OUT_CAL_FSDT = LNCSLDRW.COMM_DATA.CAL_FST_DT;
        WS_OUT_DATA.WS_OUT_PYP_CIRC = LNCSLDRW.COMM_DATA.PYP_CIRC;
        WS_OUT_DATA.WS_OUT_PYP_PERU = LNCSLDRW.COMM_DATA.PAYP_PERU;
        WS_OUT_DATA.WS_OUT_PYP_PERD = LNCSLDRW.COMM_DATA.PAYP_PERD;
        WS_OUT_DATA.WS_OUT_SP_LNFLG = LNCSLDRW.COMM_DATA.SP_LNFLG;
        WS_OUT_DATA.WS_OUT_PHS_FLG = LNCSLDRW.COMM_DATA.PHS_FLG;
        WS_OUT_DATA.WS_OUT_PHS_NUM = LNCSLDRW.COMM_DATA.PHS_NUM;
        for (WS_I = 1; WS_I <= 5; WS_I += 1) {
            WS_OUT_DATA.WS_OUT_PHS_INF[WS_I-1].WS_OUT_PHS_TTRM = LNCSLDRW.COMM_DATA.PHS_DATA[WS_I-1].PHS_TOT_TERM;
            WS_OUT_DATA.WS_OUT_PHS_INF[WS_I-1].WS_OUT_PHS_PERU = LNCSLDRW.COMM_DATA.PHS_DATA[WS_I-1].PHS_PERU;
            WS_OUT_DATA.WS_OUT_PHS_INF[WS_I-1].WS_OUT_PHS_PERD = LNCSLDRW.COMM_DATA.PHS_DATA[WS_I-1].PHS_PERD;
            WS_OUT_DATA.WS_OUT_PHS_INF[WS_I-1].WS_OUT_PHS_PAMT = LNCSLDRW.COMM_DATA.PHS_DATA[WS_I-1].PHS_PRIN_AMT;
            WS_OUT_DATA.WS_OUT_PHS_INF[WS_I-1].WS_OUT_PHS_ISMT = LNCSLDRW.COMM_DATA.PHS_DATA[WS_I-1].PHS_INST_MTH;
        }
        WS_OUT_DATA.WS_OUT_OLC_PERU = LNCSLDRW.COMM_DATA.OCAL_PERD_UNIT;
        WS_OUT_DATA.WS_OUT_OLC_PERD = LNCSLDRW.COMM_DATA.OCAL_PERD;
        WS_OUT_DATA.WS_OUT_DRAW_ACT = LNCSLDRW.COMM_DATA.DRAW_AC_TYP;
        WS_OUT_DATA.WS_OUT_DRAW_AC = LNCSLDRW.COMM_DATA.DRAW_AC;
        WS_OUT_DATA.WS_OUT_DW_BK_TP = LNCSLDRW.COMM_DATA.DRAW_BK_TP;
        WS_OUT_DATA.WS_OUT_DRAW_SEQ = LNCSLDRW.COMM_DATA.DRAW_SEQ;
        WS_OUT_DATA.WS_OUT_PAY_AC_T = LNCSLDRW.COMM_DATA.PAY_AC_TYP;
        WS_OUT_DATA.WS_OUT_PAY_AC = LNCSLDRW.COMM_DATA.PAY_AC;
        WS_OUT_DATA.WS_OUT_PA_BK_TP = LNCSLDRW.COMM_DATA.PAY_BK_TP;
        WS_OUT_DATA.WS_OUT_FS_CLMTH = LNCSLDRW.COMM_DATA.FS_CL_MTH;
        WS_OUT_DATA.WS_OUT_FS_CLAMT = LNCSLDRW.COMM_DATA.FS_CL_AMT;
        WS_OUT_DATA.WS_OUT_PAYI_ACT = LNCSLDRW.COMM_DATA.PAYI_ACT;
        WS_OUT_DATA.WS_OUT_PAYI_AC = LNCSLDRW.COMM_DATA.PAYI_AC;
        WS_OUT_DATA.WS_OUT_PAYI_SEQ = LNCSLDRW.COMM_DATA.PAYI_SEQ;
        WS_OUT_DATA.WS_OUT_ATO_DFLG = LNCSLDRW.COMM_DATA.AUTO_DFLG;
        WS_OUT_DATA.WS_OUT_ATO_AMT = LNCSLDRW.COMM_DATA.AUTO_AMT;
        WS_OUT_DATA.WS_OUT_ATO_ACT = LNCSLDRW.COMM_DATA.ATO_ACT;
        WS_OUT_DATA.WS_OUT_ATO_AC = LNCSLDRW.COMM_DATA.ATO_AC;
        WS_OUT_DATA.WS_OUT_GRA_TYP = LNCSLDRW.COMM_DATA.GRA_TYP;
        WS_OUT_DATA.WS_OUT_GRA_DAYA = LNCSLDRW.COMM_DATA.GRA_DAYS_ACC;
        WS_OUT_DATA.WS_OUT_P_GRA_MT = LNCSLDRW.COMM_DATA.P_GRA_MTH;
        WS_OUT_DATA.WS_OUT_C_GRA_MT = LNCSLDRW.COMM_DATA.I_GRA_MTH;
        WS_OUT_DATA.WS_OUT_INT_D_BA = LNCSLDRW.COMM_DATA.INT_DAY_BASIS;
        WS_OUT_DATA.WS_OUT_PSEQ_CD = LNCSLDRW.COMM_DATA.PSEQ_CD;
        WS_OUT_DATA.WS_OUT_HAND_CHR = LNCSLDRW.COMM_DATA.HAND_CHG_RATE;
        WS_OUT_DATA.WS_OUT_HAND_CHM = LNCSLDRW.COMM_DATA.HAND_CHG_MTH;
        WS_OUT_DATA.WS_OUT_GUAPREF = LNCSLDRW.COMM_DATA.GUAP_REF;
        WS_OUT_DATA.WS_OUT_GUARPSEQ = LNCSLDRW.COMM_DATA.GUAR_PAY_SEQ;
        WS_OUT_DATA.WS_OUT_HLD_NO = LNCSLDRW.COMM_DATA.REF_NO;
        for (WS_I = 1; WS_I <= 5; WS_I += 1) {
            WS_OUT_DATA.WS_OUT_FEE_INF[WS_I-1].WS_OUT_FEE_CODE = LNCSLDRW.COMM_DATA.FEE_DATE[WS_I-1].FEE_CODE;
            WS_OUT_DATA.WS_OUT_FEE_INF[WS_I-1].WS_OUT_FEE_AMT = LNCSLDRW.COMM_DATA.FEE_DATE[WS_I-1].FEE_AMT;
        }
        WS_OUT_DATA.WS_OUT_FEE_ACT = LNCSLDRW.COMM_DATA.FEE_AC_TYP;
        WS_OUT_DATA.WS_OUT_FEE_AC = LNCSLDRW.COMM_DATA.FEE_AC;
        WS_OUT_DATA.WS_OUT_TR_MMO = LNCSLDRW.COMM_DATA.TR_MMO;
        WS_OUT_DATA.WS_OUT_REMARK = LNCSLDRW.COMM_DATA.REMARK1;
        WS_OUT_DATA.WS_OUT_CUSTM1 = LNCSLDRW.COMM_DATA.CUSTM1;
        WS_OUT_DATA.WS_OUT_CUSTM2 = LNCSLDRW.COMM_DATA.CUSTM2;
        WS_OUT_DATA.WS_OUT_CUSTM3 = LNCSLDRW.COMM_DATA.CUSTM3;
        WS_OUT_DATA.WS_OUT_BAR_CD = LNCSLDRW.COMM_DATA.BAR_CD;
        WS_OUT_DATA.WS_OUT_UNIT_CD = LNCSLDRW.COMM_DATA.UNIT_CD;
        for (WS_I = 1; WS_I <= 10; WS_I += 1) {
            WS_OUT_DATA.WS_OUT_PART_INF[WS_I-1].WS_OUT_PART_NO = LNCSLCRP.PART_INF[WS_I-1].PART_NO;
            WS_OUT_DATA.WS_OUT_PART_INF[WS_I-1].WS_OUT_BR = LNCSLCRP.PART_INF[WS_I-1].BR;
            WS_OUT_DATA.WS_OUT_PART_INF[WS_I-1].WS_OUT_PART_NM = LNCSLCRP.PART_INF[WS_I-1].PART_NM;
            WS_OUT_DATA.WS_OUT_PART_INF[WS_I-1].WS_OUT_LOC_BANK = LNCSLCRP.PART_INF[WS_I-1].LOC_BANK;
            WS_OUT_DATA.WS_OUT_PART_INF[WS_I-1].WS_OUT_ADJ_FLG = LNCSLCRP.PART_INF[WS_I-1].ADJ_FLG;
            WS_OUT_DATA.WS_OUT_PART_INF[WS_I-1].WS_OUT_REL_TYPE = LNCSLCRP.PART_INF[WS_I-1].REL_TYPE;
            WS_OUT_DATA.WS_OUT_PART_INF[WS_I-1].WS_OUT_YHS_FLG = LNCSLCRP.PART_INF[WS_I-1].YHS_FLG;
            WS_OUT_DATA.WS_OUT_PART_INF[WS_I-1].WS_OUT_YHS_AC = LNCSLCRP.PART_INF[WS_I-1].YHS_AC;
            WS_OUT_DATA.WS_OUT_PART_INF[WS_I-1].WS_OUT_PART_PCT = LNCSLCRP.PART_INF[WS_I-1].PART_PCT;
            WS_OUT_DATA.WS_OUT_PART_INF[WS_I-1].WS_OUT_PART_AMT = LNCSLCRP.PART_INF[WS_I-1].PART_AMT;
            WS_OUT_DATA.WS_OUT_PART_INF[WS_I-1].WS_OUT_PART_ACT = LNCSLCRP.PART_INF[WS_I-1].PART_ACT;
            WS_OUT_DATA.WS_OUT_PART_INF[WS_I-1].WS_OUT_PART_AC = LNCSLCRP.PART_INF[WS_I-1].PART_AC;
        }
    }
    public void R000_MAKE_OUTPUT_DATA() throws IOException,SQLException,Exception {
        LNCO2100.PAPER_NO = LNCSSYND.DATA.PAPER_NO;
        LNCO2100.DRAW_NO = LNCSSYND.DATA.DRAW_NO;
        LNCO2100.CONT_NO = LNCSLDRW.COMM_DATA.CTA_NO;
        LNCO2100.BOOK_CRE = LNCSLDRW.COMM_DATA.BOOK_BR;
        LNCO2100.DOMI_BR = LNCSLDRW.COMM_DATA.DOMI_BR;
        LNCO2100.CI_NO = LNCSLDRW.COMM_DATA.CI_NO;
        LNCO2100.PROD_TYP = LNCSLDRW.COMM_DATA.PROD_CD;
        LNCO2100.START_DT = LNCSLDRW.COMM_DATA.VAL_DT;
        LNCO2100.START_DT = LNCSLDRW.COMM_DATA.INT_PER_STRT;
        LNCO2100.START_DT = LNCSLDRW.COMM_DATA.ACTV_DT;
        LNCO2100.MATU_DT = LNCSLDRW.COMM_DATA.DUE_DT;
        LNCO2100.CCY = LNCSLDRW.COMM_DATA.CCY;
        LNCO2100.CCY_TYP = LNCSLDRW.COMM_DATA.CCY_TYP;
        LNCO2100.CONT_AMT = LNCSLNCR.COMM_DATA.PRINCIPAL;
        LNCO2100.RAT_MTH = LNCSLDRW.COMM_DATA.FLT_MTH;
        LNCO2100.FLPD_UN = LNCSLDRW.COMM_DATA.FLT_PERD_UNIT;
        LNCO2100.INT_FLPD = LNCSLDRW.COMM_DATA.FLT_PERD;
        LNCO2100.FLT_IPER = LNCSLDRW.COMM_DATA.FLT_IPER;
        LNCO2100.FLT_ADJF = LNCSLDRW.COMM_DATA.FLT_ADJF;
        LNCO2100.FLT_FLG = LNCSLDRW.COMM_DATA.FIRST_FLT_FLG;
        LNCO2100.FLT_DAY = LNCSLDRW.COMM_DATA.FIRST_FIX_DATE;
        LNCO2100.FST_DAY = LNCSLDRW.COMM_DATA.FIRST_FLT_DT;
        LNCO2100.FLT_MTH = LNCSLDRW.COMM_DATA.NFLT_METHOD;
        LNCO2100.RAT_TYP = LNCSLDRW.COMM_DATA.INT_RATE_TYPE;
        LNCO2100.RAT_PD = LNCSLDRW.COMM_DATA.INT_RATE_CLAS;
        LNCO2100.RAT_VAR = LNCSLDRW.COMM_DATA.RATE_VAR;
        LNCO2100.RAT_PCT = LNCSLDRW.COMM_DATA.RATE_PCT;
        LNCO2100.RAT_INT = LNCSLDRW.COMM_DATA.RAT_INT;
        LNCO2100.IN_RATE = LNCSLDRW.COMM_DATA.ALL_IN_RATE;
        LNCO2100.PEN_RRAT = LNCSLDRW.COMM_DATA.PEN_RRAT;
        LNCO2100.PEN_TYP = LNCSLDRW.COMM_DATA.PEN_TYPE;
        LNCO2100.PEN_RATT = LNCSLDRW.COMM_DATA.PEN_RATT;
        LNCO2100.PEN_RATC = LNCSLDRW.COMM_DATA.PEN_RATC;
        LNCO2100.PEN_SPR = LNCSLDRW.COMM_DATA.PEN_SPR;
        LNCO2100.PEN_PCT = LNCSLDRW.COMM_DATA.PEN_PCT;
        LNCO2100.PEN_IRAT = LNCSLDRW.COMM_DATA.PEN_IRAT;
        LNCO2100.CPND_USE = LNCSLDRW.COMM_DATA.CPND_USE;
        LNCO2100.INT_MTH = LNCSLDRW.COMM_DATA.INT_MTH;
        LNCO2100.CPND_RTY = LNCSLDRW.COMM_DATA.CPND_RTYPE;
        LNCO2100.CPND_TYP = LNCSLDRW.COMM_DATA.CPND_TYP;
        LNCO2100.CPNDRATT = LNCSLDRW.COMM_DATA.CPND_RATT;
        LNCO2100.CPNDRATC = LNCSLDRW.COMM_DATA.CPND_RATC;
        LNCO2100.CPND_SPR = LNCSLDRW.COMM_DATA.CPND_SPR;
        LNCO2100.CPND_PCT = LNCSLDRW.COMM_DATA.CPND_PCT;
        LNCO2100.CPNDRATE = LNCSLDRW.COMM_DATA.CPND_IRATE;
        LNCO2100.ABUS_RAT = LNCSLDRW.COMM_DATA.ABUS_RAT_TYP;
        LNCO2100.ABUSRATT = LNCSLDRW.COMM_DATA.ABUS_FLT_TYP;
        LNCO2100.ABUS_TYP = LNCSLDRW.COMM_DATA.ABUS_RATTYPE;
        LNCO2100.ABUSRATC = LNCSLDRW.COMM_DATA.ABUS_RAT_TERM;
        LNCO2100.ABUSSPR = LNCSLDRW.COMM_DATA.ABUS_SPR;
        LNCO2100.ABUSPCT = LNCSLDRW.COMM_DATA.ABUS_PCT;
        LNCO2100.ABUSIRAT = LNCSLDRW.COMM_DATA.ABUS_IRAT;
        LNCO2100.REPY_MTH = LNCSLDRW.COMM_DATA.REPY_MTH;
        LNCO2100.INST_MTH = LNCSLDRW.COMM_DATA.INST_MTH;
        LNCO2100.PAYI_PER = LNCSLDRW.COMM_DATA.PAYI_PERD;
        LNCO2100.CAL_PERU = LNCSLDRW.COMM_DATA.CAL_PERD_UNIT;
        LNCO2100.CAL_PERD = LNCSLDRW.COMM_DATA.CAL_PERD;
        LNCO2100.PAY_DTYP = LNCSLDRW.COMM_DATA.CAL_PAY_DAY_TYP;
        LNCO2100.CAL_DAY = LNCSLDRW.COMM_DATA.CAL_PAY_DAY;
        LNCO2100.CAL_FSDT = LNCSLDRW.COMM_DATA.CAL_FST_DT;
        LNCO2100.PYP_CIRC = LNCSLDRW.COMM_DATA.PYP_CIRC;
        LNCO2100.PYP_PERU = LNCSLDRW.COMM_DATA.PAYP_PERU;
        LNCO2100.PYP_PERD = LNCSLDRW.COMM_DATA.PAYP_PERD;
        LNCO2100.SP_LNFLG = LNCSLDRW.COMM_DATA.SP_LNFLG;
        LNCO2100.PHS_FLG = LNCSLDRW.COMM_DATA.PHS_FLG;
        LNCO2100.PHS_NUM = LNCSLDRW.COMM_DATA.PHS_NUM;
        WS_I = 1;
        while (WS_I <= 5) {
            LNCO2100.PHS_INF[WS_I-1].PHS_TTRM = LNCSLDRW.COMM_DATA.PHS_DATA[WS_I-1].PHS_TOT_TERM;
            LNCO2100.PHS_INF[WS_I-1].PHS_PERU = LNCSLDRW.COMM_DATA.PHS_DATA[WS_I-1].PHS_PERU;
            LNCO2100.PHS_INF[WS_I-1].PHS_PERD = LNCSLDRW.COMM_DATA.PHS_DATA[WS_I-1].PHS_PERD;
            LNCO2100.PHS_INF[WS_I-1].PHS_PAMT = LNCSLDRW.COMM_DATA.PHS_DATA[WS_I-1].PHS_PRIN_AMT;
            LNCO2100.PHS_INF[WS_I-1].PHS_ISMT = LNCSLDRW.COMM_DATA.PHS_DATA[WS_I-1].PHS_INST_MTH;
            WS_I += 1;
        }
        LNCO2100.OLC_PERU = LNCSLDRW.COMM_DATA.OCAL_PERD_UNIT;
        LNCO2100.OLC_PERD = LNCSLDRW.COMM_DATA.OCAL_PERD;
        LNCO2100.DRAW_ACT = LNCSLDRW.COMM_DATA.DRAW_AC_TYP;
        LNCO2100.DRAW_AC = LNCSLDRW.COMM_DATA.DRAW_AC;
        LNCO2100.DW_BK_TP = LNCSLDRW.COMM_DATA.DRAW_BK_TP;
        LNCO2100.DRAW_SEQ = LNCSLDRW.COMM_DATA.DRAW_SEQ;
        LNCO2100.PAY_AC_T = LNCSLDRW.COMM_DATA.PAY_AC_TYP;
        LNCO2100.PAY_AC = LNCSLDRW.COMM_DATA.PAY_AC;
        LNCO2100.PA_BK_TP = LNCSLDRW.COMM_DATA.PAY_BK_TP;
        LNCO2100.FS_CLMTH = LNCSLDRW.COMM_DATA.FS_CL_MTH;
        LNCO2100.FS_CLAMT = LNCSLDRW.COMM_DATA.FS_CL_AMT;
        LNCO2100.PAYI_ACT = LNCSLDRW.COMM_DATA.PAYI_ACT;
        LNCO2100.PAYI_AC = LNCSLDRW.COMM_DATA.PAYI_AC;
        LNCO2100.PAYI_SEQ = LNCSLDRW.COMM_DATA.PAYI_SEQ;
        LNCO2100.ATO_DFLG = LNCSLDRW.COMM_DATA.AUTO_DFLG;
        LNCO2100.ATO_AMT = LNCSLDRW.COMM_DATA.AUTO_AMT;
        LNCO2100.ATO_ACT = LNCSLDRW.COMM_DATA.ATO_ACT;
        LNCO2100.ATO_AC = LNCSLDRW.COMM_DATA.ATO_AC;
        LNCO2100.GRA_TYP = LNCSLDRW.COMM_DATA.GRA_TYP;
        LNCO2100.GRA_DAYA = LNCSLDRW.COMM_DATA.GRA_DAYS_ACC;
        LNCO2100.P_GRA_MT = LNCSLDRW.COMM_DATA.P_GRA_MTH;
        LNCO2100.C_GRA_MT = LNCSLDRW.COMM_DATA.I_GRA_MTH;
        LNCO2100.INT_D_BA = LNCSLDRW.COMM_DATA.INT_DAY_BASIS;
        LNCO2100.PSEQ_CD = LNCSLDRW.COMM_DATA.PSEQ_CD;
        LNCO2100.PREP_CHR = LNCSLDRW.COMM_DATA.PREP_CHR;
        LNCO2100.HAND_CHR = LNCSLDRW.COMM_DATA.HAND_CHG_RATE;
        LNCO2100.HAND_CHM = LNCSLDRW.COMM_DATA.HAND_MTH;
        LNCO2100.GUAPREF = LNCSLDRW.COMM_DATA.GUAP_REF;
        LNCO2100.GUARDUAP = LNCSLDRW.COMM_DATA.GUAR_DUE_AP;
        LNCO2100.GUARPSEQ = LNCSLDRW.COMM_DATA.GUAR_PAY_SEQ;
        WS_FEE_CNT = 1;
        while (WS_FEE_CNT <= 5) {
            LNCO2100.FEE_INF[WS_FEE_CNT-1].FEE_CODE = LNCSLDRW.COMM_DATA.FEE_DATE[WS_FEE_CNT-1].FEE_CODE;
            LNCO2100.FEE_INF[WS_FEE_CNT-1].FEE_AMT = LNCSLDRW.COMM_DATA.FEE_DATE[WS_FEE_CNT-1].FEE_AMT;
            WS_FEE_CNT += 1;
        }
        LNCO2100.FEE_ACT = LNCSLDRW.COMM_DATA.FEE_AC_TYP;
        LNCO2100.FEE_AC = LNCSLDRW.COMM_DATA.FEE_AC;
        LNCO2100.TR_MMO = LNCSLDRW.COMM_DATA.TR_MMO;
        LNCO2100.REMARK = LNCSLDRW.COMM_DATA.REMARK1;
        LNCO2100.CUSTM1 = LNCSLDRW.COMM_DATA.CUSTM1;
        LNCO2100.CUSTM2 = LNCSLDRW.COMM_DATA.CUSTM2;
        LNCO2100.CUSTM3 = LNCSLDRW.COMM_DATA.CUSTM3;
        LNCO2100.BAR_CD = LNCSLDRW.COMM_DATA.BAR_CD;
        LNCO2100.UNIT_CD = LNCSLDRW.COMM_DATA.UNIT_CD;
        WS_I = 0;
        for (WS_I = 1; WS_I <= 10; WS_I += 1) {
            LNCO2100.PART_INF[WS_I-1].PART_NO = LNCSLCRP.PART_INF[WS_I-1].PART_NO;
            LNCO2100.PART_INF[WS_I-1].BR = LNCSLCRP.PART_INF[WS_I-1].BR;
            LNCO2100.PART_INF[WS_I-1].PART_NM = LNCSLCRP.PART_INF[WS_I-1].PART_NM;
            LNCO2100.PART_INF[WS_I-1].LOC_BANK = LNCSLCRP.PART_INF[WS_I-1].LOC_BANK;
            LNCO2100.PART_INF[WS_I-1].ADJ_FLG = LNCSLCRP.PART_INF[WS_I-1].ADJ_FLG;
            LNCO2100.PART_INF[WS_I-1].REL_TYPE = LNCSLCRP.PART_INF[WS_I-1].REL_TYPE;
            LNCO2100.PART_INF[WS_I-1].YHS_FLG = LNCSLCRP.PART_INF[WS_I-1].YHS_FLG;
            LNCO2100.PART_INF[WS_I-1].YHS_AC = LNCSLCRP.PART_INF[WS_I-1].YHS_AC;
            LNCO2100.PART_INF[WS_I-1].PART_PCT = LNCSLCRP.PART_INF[WS_I-1].PART_PCT;
            LNCO2100.PART_INF[WS_I-1].PART_AMT = LNCSLCRP.PART_INF[WS_I-1].PART_AMT;
            LNCO2100.PART_INF[WS_I-1].PART_ACT = LNCSLCRP.PART_INF[WS_I-1].PART_ACT;
            LNCO2100.PART_INF[WS_I-1].PART_AC = LNCSLCRP.PART_INF[WS_I-1].PART_AC;
        }
    }
    public void S000_CALL_LNZPPMQ() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-FUN-PRD-PRM-INQ", LNCPPMQ);
        if (LNCPPMQ.RC.RC_RTNCODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, LNCPPMQ.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], LNCSSYND.RC);
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void S000_CALL_LNZIGECR() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-I-GENERATE-CNTRNO", LNCIGECR);
        if (LNCIGECR.RC.RC_CODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, LNCIGECR.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], LNCSSYND.RC);
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void S000_CALL_LNZSLNCR() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-SVR-LOAN-CREATION", LNCSLNCR);
        if (LNCSLNCR.RC.RC_RTNCODE != 0) {
