package com.hisun.LN;

import com.hisun.SC.*;

import java.lang.reflect.Method;

import java.io.IOException;
import java.sql.SQLException;

public class LNZSBP01 {
    String JIBS_tmp_str[] = new String[10];
    DBParm LNTFWDH_RD;
    boolean pgmRtn = false;
    int WS_IDX = 0;
    int WS_FEE_CNT = 0;
    LNZSBP01_WS_MSGID WS_MSGID = new LNZSBP01_WS_MSGID();
    short WS_FLD_NO = 0;
    char WS_UPDATE_FLG = ' ';
    char WS_FOUND_FLG = ' ';
    LNRBSP01 LNRBSP01 = new LNRBSP01();
    LNCMSG_ERROR_MSG LNCMSG_ERROR_MSG = new LNCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCFMT SCCFMT = new SCCFMT();
    SCCMPAG SCCMPAG = new SCCMPAG();
    SCCMSG SCCMSG = new SCCMSG();
    LNCSWLAD LNCSWLAD = new LNCSWLAD();
    LNRFWDH LNRFWDH = new LNRFWDH();
    SCCGWA SCCGWA;
    LNCSWLAD LNCBSP01;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    SCCBATH SCCBATH;
    public void MP(SCCGWA SCCGWA, LNCSWLAD LNCBSP01) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        this.LNCBSP01 = LNCBSP01;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        if (pgmRtn) return;
        B000_MAIN_PROC();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, "LNZSBP01 return!");
        Z_RET();
        if (pgmRtn) return;
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        SCCBATH = (SCCBATH) SCCGWA.COMM_AREA.BAT_AREA_PTR;
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCSWLAD);
        IBS.init(SCCGWA, LNRFWDH);
        LNCSWLAD.COMM_DATA.PAPER_NO = LNCBSP01.COMM_DATA.PAPER_NO;
        LNCSWLAD.COMM_DATA.DRAWR_NO = LNCBSP01.COMM_DATA.DRAWR_NO;
        LNCSWLAD.COMM_DATA.CTA_NO = LNCBSP01.COMM_DATA.CTA_NO;
        LNCSWLAD.COMM_DATA.BOOK_BR = LNCBSP01.COMM_DATA.BOOK_BR;
        LNCSWLAD.COMM_DATA.DOMI_BR = LNCBSP01.COMM_DATA.DOMI_BR;
        LNCSWLAD.COMM_DATA.CI_NO = LNCBSP01.COMM_DATA.CI_NO;
        LNCSWLAD.COMM_DATA.PROD_CD = LNCBSP01.COMM_DATA.PROD_CD;
        LNCSWLAD.COMM_DATA.VAL_DT = LNCBSP01.COMM_DATA.VAL_DT;
        LNCSWLAD.COMM_DATA.INT_PER_STRT = LNCBSP01.COMM_DATA.INT_PER_STRT;
        LNCSWLAD.COMM_DATA.ACTV_DT = LNCBSP01.COMM_DATA.ACTV_DT;
        LNCSWLAD.COMM_DATA.DUE_DT = LNCBSP01.COMM_DATA.DUE_DT;
        LNCSWLAD.COMM_DATA.CCY = LNCBSP01.COMM_DATA.CCY;
        LNCSWLAD.COMM_DATA.CCY_TYP = LNCBSP01.COMM_DATA.CCY_TYP;
        LNCSWLAD.COMM_DATA.CONT_AMT = LNCBSP01.COMM_DATA.CONT_AMT;
        LNCSWLAD.COMM_DATA.PRINCIPAL = LNCBSP01.COMM_DATA.PRINCIPAL;
        LNCSWLAD.COMM_DATA.FLT_MTH = LNCBSP01.COMM_DATA.FLT_MTH;
        LNCSWLAD.COMM_DATA.FLT_PERD_UNIT = LNCBSP01.COMM_DATA.FLT_PERD_UNIT;
        LNCSWLAD.COMM_DATA.FLT_PERD = LNCBSP01.COMM_DATA.FLT_PERD;
        LNCSWLAD.COMM_DATA.FLT_IPER = LNCBSP01.COMM_DATA.FLT_IPER;
        LNCSWLAD.COMM_DATA.FLT_ADJF = LNCBSP01.COMM_DATA.FLT_ADJF;
        LNCSWLAD.COMM_DATA.FIRST_FLT_FLG = LNCBSP01.COMM_DATA.FIRST_FLT_FLG;
        LNCSWLAD.COMM_DATA.FIRST_FIX_DATE = LNCBSP01.COMM_DATA.FIRST_FIX_DATE;
        LNCSWLAD.COMM_DATA.FIRST_FLT_DT = LNCBSP01.COMM_DATA.FIRST_FLT_DT;
        LNCSWLAD.COMM_DATA.NFLT_METHOD = LNCBSP01.COMM_DATA.NFLT_METHOD;
        LNCSWLAD.COMM_DATA.INT_RATE_TYPE = LNCBSP01.COMM_DATA.INT_RATE_TYPE;
        LNCSWLAD.COMM_DATA.INT_RATE_CLAS = LNCBSP01.COMM_DATA.INT_RATE_CLAS;
        LNCSWLAD.COMM_DATA.RATE_VAR = LNCBSP01.COMM_DATA.RATE_VAR;
        LNCSWLAD.COMM_DATA.RATE_PCT = LNCBSP01.COMM_DATA.RATE_PCT;
        LNCSWLAD.COMM_DATA.RAT_INT = LNCBSP01.COMM_DATA.RAT_INT;
        LNCSWLAD.COMM_DATA.ALL_IN_RATE = LNCBSP01.COMM_DATA.ALL_IN_RATE;
        LNCSWLAD.COMM_DATA.PEN_RRAT = LNCBSP01.COMM_DATA.PEN_RRAT;
        LNCSWLAD.COMM_DATA.PEN_TYPE = LNCBSP01.COMM_DATA.PEN_TYPE;
        LNCSWLAD.COMM_DATA.PEN_RATT = LNCBSP01.COMM_DATA.PEN_RATT;
        LNCSWLAD.COMM_DATA.PEN_RATC = LNCBSP01.COMM_DATA.PEN_RATC;
        LNCSWLAD.COMM_DATA.PEN_SPR = LNCBSP01.COMM_DATA.PEN_SPR;
        LNCSWLAD.COMM_DATA.PEN_PCT = LNCBSP01.COMM_DATA.PEN_PCT;
        LNCSWLAD.COMM_DATA.PEN_IRAT = LNCBSP01.COMM_DATA.PEN_IRAT;
        LNCSWLAD.COMM_DATA.CPND_USE = LNCBSP01.COMM_DATA.CPND_USE;
        LNCSWLAD.COMM_DATA.INT_MTH = LNCBSP01.COMM_DATA.INT_MTH;
        LNCSWLAD.COMM_DATA.CPND_RTYPE = LNCBSP01.COMM_DATA.CPND_RTYPE;
        LNCSWLAD.COMM_DATA.CPND_TYP = LNCBSP01.COMM_DATA.CPND_TYP;
        LNCSWLAD.COMM_DATA.CPND_RATT = LNCBSP01.COMM_DATA.CPND_RATT;
        LNCSWLAD.COMM_DATA.CPND_RATC = LNCBSP01.COMM_DATA.CPND_RATC;
        LNCSWLAD.COMM_DATA.CPND_SPR = LNCBSP01.COMM_DATA.CPND_SPR;
        LNCSWLAD.COMM_DATA.CPND_PCT = LNCBSP01.COMM_DATA.CPND_PCT;
        LNCSWLAD.COMM_DATA.CPND_IRATE = LNCBSP01.COMM_DATA.CPND_IRATE;
        LNCSWLAD.COMM_DATA.ABUS_RAT_TYP = LNCBSP01.COMM_DATA.ABUS_RAT_TYP;
        LNCSWLAD.COMM_DATA.ABUS_FLT_TYP = LNCBSP01.COMM_DATA.ABUS_FLT_TYP;
        LNCSWLAD.COMM_DATA.ABUS_RATTYPE = LNCBSP01.COMM_DATA.ABUS_RATTYPE;
        LNCSWLAD.COMM_DATA.ABUS_RAT_TERM = LNCBSP01.COMM_DATA.ABUS_RAT_TERM;
        LNCSWLAD.COMM_DATA.ABUS_SPR = LNCBSP01.COMM_DATA.ABUS_SPR;
        LNCSWLAD.COMM_DATA.ABUS_PCT = LNCBSP01.COMM_DATA.ABUS_PCT;
        LNCSWLAD.COMM_DATA.ABUS_IRAT = LNCBSP01.COMM_DATA.ABUS_IRAT;
        LNCSWLAD.COMM_DATA.REPY_MTH = LNCBSP01.COMM_DATA.REPY_MTH;
        LNCSWLAD.COMM_DATA.INST_MTH = LNCBSP01.COMM_DATA.INST_MTH;
        LNCSWLAD.COMM_DATA.PAYI_PERD = LNCBSP01.COMM_DATA.PAYI_PERD;
        LNCSWLAD.COMM_DATA.CAL_PERD_UNIT = LNCBSP01.COMM_DATA.CAL_PERD_UNIT;
        LNCSWLAD.COMM_DATA.CAL_PERD = LNCBSP01.COMM_DATA.CAL_PERD;
        LNCSWLAD.COMM_DATA.CAL_PAY_DAY_TYP = LNCBSP01.COMM_DATA.CAL_PAY_DAY_TYP;
        LNCSWLAD.COMM_DATA.CAL_PAY_DAY = LNCBSP01.COMM_DATA.CAL_PAY_DAY;
        LNCSWLAD.COMM_DATA.CAL_FST_DT = LNCBSP01.COMM_DATA.CAL_FST_DT;
        LNCSWLAD.COMM_DATA.PYP_CIRC = LNCBSP01.COMM_DATA.PYP_CIRC;
        LNCSWLAD.COMM_DATA.PAYP_PERU = LNCBSP01.COMM_DATA.PAYP_PERU;
        LNCSWLAD.COMM_DATA.PAYP_PERD = LNCBSP01.COMM_DATA.PAYP_PERD;
        LNCSWLAD.COMM_DATA.SP_LNFLG = LNCBSP01.COMM_DATA.SP_LNFLG;
        LNCSWLAD.COMM_DATA.PHS_FLG = LNCBSP01.COMM_DATA.PHS_FLG;
        LNCSWLAD.COMM_DATA.PHS_NUM = LNCBSP01.COMM_DATA.PHS_NUM;
        for (WS_IDX = 1; WS_IDX <= 5; WS_IDX += 1) {
            LNCSWLAD.COMM_DATA.PHS_DATA[WS_IDX-1].PHS_TOT_TERM = LNCBSP01.COMM_DATA.PHS_DATA[WS_IDX-1].PHS_TOT_TERM;
            LNCSWLAD.COMM_DATA.PHS_DATA[WS_IDX-1].PHS_PERU = LNCBSP01.COMM_DATA.PHS_DATA[WS_IDX-1].PHS_PERU;
            LNCSWLAD.COMM_DATA.PHS_DATA[WS_IDX-1].PHS_PERD = LNCBSP01.COMM_DATA.PHS_DATA[WS_IDX-1].PHS_PERD;
            LNCSWLAD.COMM_DATA.PHS_DATA[WS_IDX-1].PHS_PRIN_AMT = LNCBSP01.COMM_DATA.PHS_DATA[WS_IDX-1].PHS_PRIN_AMT;
            LNCSWLAD.COMM_DATA.PHS_DATA[WS_IDX-1].PHS_INST_MTH = LNCBSP01.COMM_DATA.PHS_DATA[WS_IDX-1].PHS_INST_MTH;
        }
        LNCSWLAD.COMM_DATA.OCAL_PERD_UNIT = LNCBSP01.COMM_DATA.OCAL_PERD_UNIT;
        LNCSWLAD.COMM_DATA.OCAL_PERD = LNCBSP01.COMM_DATA.OCAL_PERD;
        LNCSWLAD.COMM_DATA.DRAW_AC_TYP = LNCBSP01.COMM_DATA.DRAW_AC_TYP;
        LNCSWLAD.COMM_DATA.DRAW_AC = LNCBSP01.COMM_DATA.DRAW_AC;
        LNCSWLAD.COMM_DATA.DRAW_BK_TP = LNCBSP01.COMM_DATA.DRAW_BK_TP;
        LNCSWLAD.COMM_DATA.DRAW_SEQ = LNCBSP01.COMM_DATA.DRAW_SEQ;
        LNCSWLAD.COMM_DATA.PAY_AC_TYP = LNCBSP01.COMM_DATA.PAY_AC_TYP;
        LNCSWLAD.COMM_DATA.PAY_AC = LNCBSP01.COMM_DATA.PAY_AC;
        LNCSWLAD.COMM_DATA.PAY_BK_TP = LNCBSP01.COMM_DATA.PAY_BK_TP;
        LNCSWLAD.COMM_DATA.FS_CL_MTH = LNCBSP01.COMM_DATA.FS_CL_MTH;
        LNCSWLAD.COMM_DATA.FS_CL_AMT = LNCBSP01.COMM_DATA.FS_CL_AMT;
        LNCSWLAD.COMM_DATA.PAYI_ACT = LNCBSP01.COMM_DATA.PAYI_ACT;
        LNCSWLAD.COMM_DATA.PAYI_AC = LNCBSP01.COMM_DATA.PAYI_AC;
        LNCSWLAD.COMM_DATA.PAYI_SEQ = LNCBSP01.COMM_DATA.PAYI_SEQ;
        LNCSWLAD.COMM_DATA.AUTO_DFLG = LNCBSP01.COMM_DATA.AUTO_DFLG;
        LNCSWLAD.COMM_DATA.AUTO_DSEQ = LNCBSP01.COMM_DATA.AUTO_DSEQ;
        LNCSWLAD.COMM_DATA.AUTO_AMT = LNCBSP01.COMM_DATA.AUTO_AMT;
        LNCSWLAD.COMM_DATA.ATO_ACT = LNCBSP01.COMM_DATA.ATO_ACT;
        LNCSWLAD.COMM_DATA.ATO_AC = LNCBSP01.COMM_DATA.ATO_AC;
        LNCSWLAD.COMM_DATA.GRA_TYP = LNCBSP01.COMM_DATA.GRA_TYP;
        LNCSWLAD.COMM_DATA.GRA_DAYS_ACC = LNCBSP01.COMM_DATA.GRA_DAYS_ACC;
        LNCSWLAD.COMM_DATA.P_GRA_MTH = LNCBSP01.COMM_DATA.P_GRA_MTH;
        LNCSWLAD.COMM_DATA.I_GRA_MTH = LNCBSP01.COMM_DATA.I_GRA_MTH;
        LNCSWLAD.COMM_DATA.INT_DAY_BASIS = LNCBSP01.COMM_DATA.INT_DAY_BASIS;
        LNCSWLAD.COMM_DATA.PSEQ_CD = LNCBSP01.COMM_DATA.PSEQ_CD;
        LNCSWLAD.COMM_DATA.PREP_CHR = LNCBSP01.COMM_DATA.PREP_CHR;
        LNCSWLAD.COMM_DATA.HAND_CHG_RATE = LNCBSP01.COMM_DATA.HAND_CHG_RATE;
        LNCSWLAD.COMM_DATA.HAND_MTH = LNCBSP01.COMM_DATA.HAND_MTH;
        LNCSWLAD.COMM_DATA.GUAP_REF = LNCBSP01.COMM_DATA.GUAP_REF;
        LNCSWLAD.COMM_DATA.GUAR_DUE_AP = LNCBSP01.COMM_DATA.GUAR_DUE_AP;
        LNCSWLAD.COMM_DATA.GUAR_PAY_SEQ = LNCBSP01.COMM_DATA.GUAR_PAY_SEQ;
        WS_IDX = 1;
        for (WS_IDX = 1; WS_IDX <= 5; WS_IDX += 1) {
            LNCSWLAD.COMM_DATA.FEE_DATE[WS_IDX-1].FEE_CODE = LNCBSP01.COMM_DATA.FEE_DATE[WS_IDX-1].FEE_CODE;
            LNCSWLAD.COMM_DATA.FEE_DATE[WS_IDX-1].FEE_AMT = LNCBSP01.COMM_DATA.FEE_DATE[WS_IDX-1].FEE_AMT;
            if (LNCBSP01.COMM_DATA.FEE_DATE[WS_IDX-1].FEE_CODE.trim().length() > 0) {
                WS_FEE_CNT += 1;
            }
        }
        LNCSWLAD.COMM_DATA.FEE_CNT = (short) WS_FEE_CNT;
        LNCSWLAD.COMM_DATA.FEE_AC_TYP = LNCBSP01.COMM_DATA.FEE_AC_TYP;
        LNCSWLAD.COMM_DATA.FEE_AC = LNCBSP01.COMM_DATA.FEE_AC;
        LNCSWLAD.COMM_DATA.TR_MMO = LNCBSP01.COMM_DATA.TR_MMO;
        LNCSWLAD.COMM_DATA.REMARK1 = LNCBSP01.COMM_DATA.REMARK1;
        LNCSWLAD.COMM_DATA.CUSTM1 = LNCBSP01.COMM_DATA.CUSTM1;
        LNCSWLAD.COMM_DATA.CUSTM2 = LNCBSP01.COMM_DATA.CUSTM2;
        LNCSWLAD.COMM_DATA.CUSTM3 = LNCBSP01.COMM_DATA.CUSTM3;
        LNCSWLAD.COMM_DATA.BAR_CD = LNCBSP01.COMM_DATA.BAR_CD;
        LNCSWLAD.COMM_DATA.UNIT_CD = LNCBSP01.COMM_DATA.UNIT_CD;
        LNCSWLAD.COMM_DATA.YHS_FLG = LNCBSP01.COMM_DATA.YHS_FLG;
        LNCSWLAD.COMM_DATA.YHS_AC = LNCBSP01.COMM_DATA.YHS_AC;
        LNCSWLAD.COMM_DATA.PRO_AMT = LNCBSP01.COMM_DATA.PRO_AMT;
        LNCSWLAD.COMM_DATA.PRO_AC = LNCBSP01.COMM_DATA.PRO_AC;
        LNCSWLAD.COMM_DATA.FUND_AC_CONSIGN = LNCBSP01.COMM_DATA.FUND_AC_CONSIGN;
        LNCSWLAD.COMM_DATA.SETTLE_AC_CONSIGN = LNCBSP01.COMM_DATA.SETTLE_AC_CONSIGN;
        LNCSWLAD.COMM_DATA.SETL_AC_CONS_INT = LNCBSP01.COMM_DATA.SETL_AC_CONS_INT;
        LNCSWLAD.COMM_DATA.GJ_PROJ_NO = LNCBSP01.COMM_DATA.GJ_PROJ_NO;
        LNCSWLAD.COMM_DATA.PROJ_NO = LNCBSP01.COMM_DATA.PROJ_NO;
        LNCSWLAD.COMM_DATA.SUBS_TTRM = LNCBSP01.COMM_DATA.SUBS_TTRM;
        LNCSWLAD.COMM_DATA.SUBS_BTRM = LNCBSP01.COMM_DATA.SUBS_BTRM;
        S000_CALL_LNZSWLAD();
        if (pgmRtn) return;
        LNRFWDH.TRAN_STS = '2';
        T000_REWRITE_LNTFWDH();
        if (pgmRtn) return;
    }
    public void S000_CALL_LNZSWLAD() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-SVR-WLLOAN-ADD2DD", LNCSWLAD);
        if (LNCSWLAD.RC.RC_RTNCODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, LNCSWLAD.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], WS_MSGID);
            CEP.TRC(SCCGWA, WS_MSGID);
            S000_ERR_MSG_PROC();
            if (pgmRtn) return;
        }
    }
    public void T000_REWRITE_LNTFWDH() throws IOException,SQLException,Exception {
        LNTFWDH_RD = new DBParm();
        LNTFWDH_RD.TableName = "LNTFWDH";
        LNTFWDH_RD.col = "TRAN_STS";
        LNTFWDH_RD.where = "CONTRACT_NO = :LNCBSP01.COMM_DATA.PAPER_NO "
            + "AND RECEIPT_NO = :LNCBSP01.COMM_DATA.DRAWR_NO";
        IBS.REWRITE(SCCGWA, LNRFWDH, this, LNTFWDH_RD);
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, WS_MSGID);
        CEP.ERR(SCCGWA, JIBS_tmp_str[0], WS_FLD_NO);
    }
    public void B_MPAG() throws IOException,SQLException,Exception {
    if (!SCCGWA.COMM_AREA.BSP_FLG.equalsIgnoreCase("BSP") && !SCCGWA.COMM_AREA.CHNL.equalsIgnoreCase("BAT")) { //FROM #IFDEF ONL
        JIBS_tmp_str[9] = "SCZMPAG";
        Class<?>clazz = Class.forName(JIBS_tmp_str[9].trim());
        Object obj = clazz.newInstance();
        Method m = clazz.getDeclaredMethod("MP",new Class[]{SCCGWA.getClass(), SCCMPAG.getClass()});
        m.invoke(obj, SCCGWA, SCCMPAG);
        if (SCCGWA.COMM_AREA.EXCP_FLG == 'Y') {
            Z_RET();
            if (pgmRtn) return;
        }
    } else { //FROM #ELSE
    } //FROM #ENDIF
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        pgmRtn = true;
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
