package com.hisun.LN;

public class LNZSPRRP_WS_LOAN_CONT_AREA {
    short WS_LOAN_CONT_AREA_LEN1 = 0;
    String WS_LOAN_CONT_AREA_TEXT1 = " ";
    LNZSPRRP_REDEFINES88 REDEFINES88 = new LNZSPRRP_REDEFINES88();
}
