package com.hisun.LN;

public class LNZSPLTN_WS_TRAN_DATA {
    LNZSPLTN_WS_TRANSF_AMT WS_TRANSF_AMT = new LNZSPLTN_WS_TRANSF_AMT();
    LNZSPLTN_WS_TF_OUT_INT WS_TF_OUT_INT = new LNZSPLTN_WS_TF_OUT_INT();
    LNZSPLTN_WS_OWN_INT WS_OWN_INT = new LNZSPLTN_WS_OWN_INT();
    LNZSPLTN_WS_CTPY_INT WS_CTPY_INT = new LNZSPLTN_WS_CTPY_INT();
    LNZSPLTN_WS_PAY_INT WS_PAY_INT = new LNZSPLTN_WS_PAY_INT();
    LNZSPLTN_WS_INT_BAL WS_INT_BAL = new LNZSPLTN_WS_INT_BAL();
}
