package com.hisun.LN;

import java.io.IOException;
import java.sql.SQLException;

import com.hisun.AI.AICPQMIB;
import com.hisun.BP.BPCACLCM;
import com.hisun.BP.BPCACLDD;
import com.hisun.BP.BPCCGCT;
import com.hisun.BP.BPCOQPCD;
import com.hisun.BP.BPCPEBAS;
import com.hisun.BP.BPCPNHIS;
import com.hisun.BP.BPCPOEWA;
import com.hisun.BP.BPCPQAMO;
import com.hisun.BP.BPCPQORG;
import com.hisun.BP.BPCPQPRD;
import com.hisun.BP.BPCPRGST;
import com.hisun.BP.BPCQCCY;
import com.hisun.BP.BPCQCNGL;
import com.hisun.BP.BPCSOCAC;
import com.hisun.BP.BPCUCNGM;
import com.hisun.BP.BPCUMPRT;
import com.hisun.CI.CICACCU;
import com.hisun.CI.CICCUST;
import com.hisun.CI.CICMACR;
import com.hisun.CI.CICQACRI;
import com.hisun.DC.DCCUCINF;
import com.hisun.DD.DDCIMMST;
import com.hisun.DD.DDCUDRAC;
import com.hisun.GD.GDCIQLDR;
import com.hisun.IB.IBCQINF;
import com.hisun.SC.SCCCALL;
import com.hisun.SC.SCCCKDT;
import com.hisun.SC.SCCCLDT;
import com.hisun.SC.SCCEXCP;
import com.hisun.SC.SCCGAPV;
import com.hisun.SC.SCCGBPA_BP_AREA;
import com.hisun.SC.SCCGSCA_SC_AREA;
import com.hisun.SC.SCCGWA;
import com.hisun.SC.SCCMSG;

public class LNZSLNCR {
    boolean pgmRtn = false;
    String K_CLDD = "CLDD";
    String K_CLCM = "CLCM";
    String CPN_CI_CIZCUST = "CI-INQ-CUST";
    char K_INTEREST_PLAN = 'I';
    char K_PRINCIPAL_PLAN = 'P';
    char K_INT_PLAN = 'I';
    String K_CLDD_REMARKS = "AUTOGEN FOR CLDD";
    String K_HIS_RMKS = "ACCRUAL DRAWDOWN CONTRACT CREATE";
    char K_REPY_MTH_INST = '4';
    String PGM_SCSSCLDT = "SCSSCLDT";
    String PGM_SCSSCKDT = "SCSSCKDT";
    String K_AP_MMO = "LN";
    char K_FLT_CONT = '1';
    char K_FLT_DWDT = '2';
    char K_FLT_DWFT_DT = '3';
    char K_FLT_FIX_TYP = '4';
    short K_FLT_DT1 = 41;
    short K_FLT_DT2 = 42;
    char K_FIX_REPAY = '0';
    char K_FIX_RATE = '0';
    char K_PRE_INT = 'Y';
    char K_COMPANY = '2';
    char K_PERSONAL = '1';
    int K_EMTP_DATE = 0;
    char K_PAYMTH_03 = '3';
    char K_PAYMTH_04 = '4';
    char K_PAYMTH_05 = '5';
    char K_PAYMTH_01 = '1';
    char K_OUR_BANK = '0';
    String K_DD_AC = "01";
    String K_INTERNAL = "02";
    String K_IB_AC = "03";
    String K_DC_AC = "05";
    String K_EB_AC = "06";
    String K_CQ_AC = "07";
    char K_PAY_OUT = 'O';
    char K_NEXT_TERM = '2';
    char K_BALLON_LOAN = '1';
    String K_PPMQ_PROD_CLS_ADV = "P004";
    String K_PPMQ_PROD_CLS_GJ = "P017";
    int K_MAX_DT = 20991231;
    String K_TR_CODE = "2000";
    char K_CKPD_INQ = '0';
    String WS_ERR_MSG = " ";
    String WS_CI_CNM = " ";
    String WS_CI_CSNM = " ";
    String WS_CI_ENM = " ";
    String WS_CI_ESNM = " ";
    char WS_CCY_ID = ' ';
    int WS_I = 0;
    int WS_CNT = 0;
    int WS_LEN = 0;
    int WS_IDX = 0;
    int WS_IDX2 = 0;
    int WS_DATE_1 = 0;
    char WS_CMMT_RVL_FLG = ' ';
    char WS_INCLUDE_LAST_DAY = ' ';
    int WS_AVAIL_START_DATE = 0;
    int WS_AVAIL_END_DATE = 0;
    double WS_AVAIL_AMT = 0;
    double WS_AVAIL_AMT_OLD = 0;
    String WS_LN_ERR = " ";
    LNZSLNCR_WS_MSGID WS_MSGID = new LNZSLNCR_WS_MSGID();
    short WS_FLD_NO = 0;
    LNZSLNCR_WS_DD_NARRATIVE WS_DD_NARRATIVE = new LNZSLNCR_WS_DD_NARRATIVE();
    String WS_PAY_AC = " ";
    String WS_PROD_CD = " ";
    String WS_CONTRACT_NO = " ";
    int WS_BOOK_BR = 0;
    int WS_LOAN_BR = 0;
    String WS_CTA_CCY = " ";
    char WS_CI_ATTR = ' ';
    String WS_CI_NO = " ";
    String WS_BANK_PORTFOLIO = " ";
    int WS_DT = 0;
    int WS_DT1 = 0;
    String WS_FUND_ACC_CINO = " ";
    String WS_SETTLE_ACC_CINO = " ";
    String WS_SETL_INT_CINO = " ";
    double WS_TOT_PRIN_AMT = 0;
    int WS_STR_DT = 0;
    int WS_END_DT = 0;
    int WS_CHK_DAYS = 0;
    int WS_TERM_DAYS = 0;
    int WS_YYYYMMDD = 0;
    LNZSLNCR_REDEFINES49 REDEFINES49 = new LNZSLNCR_REDEFINES49();
    double WS_YYYY_1 = 0;
    short WS_YYYY_2 = 0;
    short WS_INST_T_TERM = 0;
    short WS_TEM_INDENT1 = 0;
    short WS_TEM_INDENT2 = 0;
    String WS_CHECK_AC_TYP = " ";
    String WS_CHECK_AC = " ";
    short WS_PHS = 0;
    short WS_TERM = 0;
    short WS_MAX_PHS = 0;
    char WS_CAL_PERU = ' ';
    int WS_CLDT_CAL = 0;
    int WS_WEEK_LAST_DAY = 0;
    int WS_PHS_COMP_DAYS = 0;
    int WS_COMP_GRACE_DAYS = 0;
    double WS_AMT = 0;
    double WS_CONT_AMT = 0;
    short WS_CAL_DAY = 0;
    int WS_CAL_DATE = 0;
    int WS_CAL_DAT1 = 0;
    int WS_CAL_DAT2 = 0;
    short WS_INST_TERM = 0;
    short WS_TOT_TERM = 0;
    int WS_II = 0;
    String WS_RC_MMO = " ";
    short WS_RC_CODE = 0;
    LNZSLNCR_WS_READ_FLGS WS_READ_FLGS = new LNZSLNCR_WS_READ_FLGS();
    char WS_UPDATE_FLG = ' ';
    char WS_FOUND_FLG = ' ';
    char WS_EOM_FLG = ' ';
    char WS_PHS_TERM_FLG = ' ';
    LNCMSG_ERROR_MSG LNCMSG_ERROR_MSG = new LNCMSG_ERROR_MSG();
    SCCMSG SCCMSG = new SCCMSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    LNCULNC LNCULNC = new LNCULNC();
    LNCURTN LNCSRTN = new LNCURTN();
    LNCURTL LNCSRTL = new LNCURTL();
    LNCIBONM LNCIBONM = new LNCIBONM();
    LNCRSETL LNCRSETL = new LNCRSETL();
    LNRSETL LNRSETL = new LNRSETL();
    LNRCONT LNRCONT = new LNRCONT();
    LNRLOAN LNRLOAN = new LNRLOAN();
    LNRICTL LNRICTL = new LNRICTL();
    LNRSUBS LNRSUBS = new LNRSUBS();
    LNRRELA LNRRELA = new LNRRELA();
    LNRLONR_KEY LNRLONR_KEY = new LNRLONR_KEY();
    LNCRLOAN LNCRLOAN = new LNCRLOAN();
    LNCRICTL LNCRICTL = new LNCRICTL();
    LNCAPRDM LNCAPRDM = new LNCAPRDM();
    LNCICTLM LNCICTLM = new LNCICTLM();
    LNCRCONT LNCRCONT = new LNCRCONT();
    LNCIGVCH LNCIGVCH = new LNCIGVCH();
    BPCPEBAS BPCPEBAS = new BPCPEBAS();
    LNCICIQ LNCICIQ = new LNCICIQ();
    BPCPOEWA BPCPOEWA = new BPCPOEWA();
    DDCUDRAC DDCUDRAC = new DDCUDRAC();
    LNCICUT LNCICUT = new LNCICUT();
    LNCIHDCK LNCIHDCK = new LNCIHDCK();
    BPCCGCT BPCCGCT = new BPCCGCT();
    BPCPQORG BPCPQORG = new BPCPQORG();
    BPCUCNGM BPCUCNGM = new BPCUCNGM();
    BPCQCNGL BPCQCNGL = new BPCQCNGL();
    BPCACLDD BPCACLDD = new BPCACLDD();
    BPCACLCM BPCACLCM = new BPCACLCM();
    BPCPQPRD BPCPQPRD = new BPCPQPRD();
    BPCOQPCD BPCOQPCD = new BPCOQPCD();
    BPCPQAMO BPCPQAMO = new BPCPQAMO();
    BPCPNHIS BPCPNHIS = new BPCPNHIS();
    BPCUMPRT BPCUMPRT = new BPCUMPRT();
    CICMACR CICMACR = new CICMACR();
    CICCUST CICCUST = new CICCUST();
    LNCADSCH LNCADSCH = new LNCADSCH();
    SCCCLDT SCCCLDT = new SCCCLDT();
    CICACCU CICACCU = new CICACCU();
    CIRBAS CIRBAS = new CIRBAS();
    CIRNAM CIRNAM = new CIRNAM();
    LNCRFUND LNCRFUND = new LNCRFUND();
    LNRFUND LNRFUND = new LNRFUND();
    GDCIQLDR GDCIQLDR = new GDCIQLDR();
    BPCQCCY BPCQCCY = new BPCQCCY();
    AICPQMIB AICPQMIB = new AICPQMIB();
    DDCIMMST DDCIMMST = new DDCIMMST();
    IBCQINF IBCQINF = new IBCQINF();
    DCCUCINF DCCUCINF = new DCCUCINF();
    SCCCKDT SCCCKDT = new SCCCKDT();
    LNCSCALT LNCSCALT = new LNCSCALT();
    LNRAGRE LNRAGRE = new LNRAGRE();
    LNCSSTBL LNCSSTBL = new LNCSSTBL();
    BPCPRGST BPCPRGST = new BPCPRGST();
    LNCFFSDT LNCFFSDT = new LNCFFSDT();
    CICSACAC CICSACAC = new CICSACAC();
    CICSACR CICSACR = new CICSACR();
    CICQACRI CICQACRI = new CICQACRI();
    BPCSOCAC BPCSOCAC = new BPCSOCAC();
    LNCSCKPD LNCSCKPD = new LNCSCKPD();
    LNCPCFTA LNCPCFTA = new LNCPCFTA();
    SCCGWA SCCGWA;
    LNCSWLAD LNCSLNCR;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    SCCGAPV SCCGAPV;
    public void MP(SCCGWA SCCGWA, LNCSWLAD LNCSLNCR) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        this.LNCSLNCR = LNCSLNCR;
        CEP.TRC(SCCGWA);
        A00_INIT_PROC();
        if (pgmRtn) return;
        B00_MAIN_PROC();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, "LNZSLNCR return!");
        Z_RET();
        if (pgmRtn) return;
        JIBS_RETURN();
    }
    public void A00_INIT_PROC() throws IOException,SQLException,Exception {
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        CEP.TRC(SCCGWA, "11");
        SCCGAPV = (SCCGAPV) GWA_SC_AREA.APVL_AREA_PTR;
        LNCSLNCR.RC.RC_APP = "LN";
        LNCSLNCR.RC.RC_RTNCODE = 0;
        if (LNCSLNCR.COMM_DATA.REPY_MTH == '6') {
            LNCSLNCR.COMM_DATA.REPY_MTH = '2';
            LNCSLNCR.COMM_DATA.BREP_MTH = '6';
        }
        CEP.TRC(SCCGWA, LNCSLNCR.COMM_DATA.CTA_NO);
        CEP.TRC(SCCGWA, LNCSLNCR.COMM_DATA.FUND_AC_CONSIGN);
        CEP.TRC(SCCGWA, LNCSLNCR.COMM_DATA.HAND_CHG_RATE);
        CEP.TRC(SCCGWA, LNCSLNCR.COMM_DATA.HAND_CHG_MTH);
        CEP.TRC(SCCGWA, GWA_SC_AREA.MULTI_PAGE_AREA.PAGE_IND);
    }
    public void B00_MAIN_PROC() throws IOException,SQLException,Exception {
        if (SCCGWA.COMM_AREA.CANCEL_IND == 'Y') {
            B000_GET_DATA();
            if (pgmRtn) return;
            B000_MAIN_PROC();
            if (pgmRtn) return;
        } else {
            B000_CHECK();
            if (pgmRtn) return;
            B000_MAIN_PROC();
            if (pgmRtn) return;
        }
        CEP.TRC(SCCGWA, GWA_SC_AREA.MULTI_PAGE_AREA.PAGE_IND);
    }
    public void B000_GET_DATA() throws IOException,SQLException,Exception {
        if (LNCSLNCR.COMM_DATA.GJ_PROJ_NO != 0) {
            LNCRFUND.FUNC = 'I';
            LNRFUND.KEY.PROJ_NO = LNCSLNCR.COMM_DATA.GJ_PROJ_NO;
            S000_CALL_LNZRFUND();
            if (pgmRtn) return;
            CEP.TRC(SCCGWA, LNRFUND.FUND_AC);
            LNCSLNCR.COMM_DATA.FUND_AC_CONSIGN = LNRFUND.FUND_AC;
            LNCSLNCR.COMM_DATA.SETTLE_AC_CONSIGN = LNRFUND.PAY_P_AC;
            LNCSLNCR.COMM_DATA.SETL_AC_CONS_INT = LNRFUND.PAY_I_AC;
            LNCSLNCR.COMM_DATA.PAY_TRANS_FLG = LNRFUND.PAY_FLG;
            LNCSLNCR.COMM_DATA.TRANS_FREQ = LNRFUND.TRANS_FREQ;
        }
    }
    public void B000_CHECK() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCSCKPD);
        LNCSCKPD.FUNC = K_CKPD_INQ;
        LNCSCKPD.PROD_CD = LNCSLNCR.COMM_DATA.PROD_CD;
        CEP.TRC(SCCGWA, LNCSLNCR.COMM_DATA.PROD_CD);
        S000_CALL_LNZSCKPD();
        if (pgmRtn) return;
        if (LNCSLNCR.COMM_DATA.PAPER_NO.trim().length() == 0) {
