package com.hisun.LN;

public class LNZSPREQ_WS_LOAN_CONT_AREA {
    short WS_LOAN_CONT_AREA_LEN1 = 0;
    String WS_LOAN_CONT_AREA_TEXT1 = " ";
    LNZSPREQ_REDEFINES43 REDEFINES43 = new LNZSPREQ_REDEFINES43();
}
