package com.hisun.LN;

public class LNZSCLRR_WS_LOAN_CONT_AREA {
    short WS_LOAN_CONT_AREA_LEN1 = 0;
    String WS_LOAN_CONT_AREA_TEXT1 = " ";
    LNZSCLRR_REDEFINES91 REDEFINES91 = new LNZSCLRR_REDEFINES91();
}
