package com.hisun.LN;

import java.io.IOException;
import java.sql.SQLException;

import com.hisun.BP.BPCFTLPM;
import com.hisun.BP.BPCQCCY;
import com.hisun.SC.SCCCALL;
import com.hisun.SC.SCCCLDT;
import com.hisun.SC.SCCEXCP;
import com.hisun.SC.SCCFMT;
import com.hisun.SC.SCCGWA;
import com.hisun.SC.SCCMSG;

public class LNZSTMPP {
    boolean pgmRtn = false;
    String K_FMT_CD_1 = "BPX01";
    String K_FMT_CD_2 = "LN331";
    String PGM_SCSSCLDT = "SCSSCLDT";
    char K_ADD = 'A';
    char K_INQUIRY = 'I';
    char K_DELETE = 'D';
    char K_MODIFY = 'M';
    char K_UPDATE = 'U';
    char K_CANCEL = 'C';
    short K_PAGE_ROW = 20;
    LNZSTMPP_WS_ERR_MSG WS_ERR_MSG = new LNZSTMPP_WS_ERR_MSG();
    int WS_I = 0;
    short WS_J = 0;
    short WS_K = 0;
    int WS_L = 0;
    double WS_TOT_SCH_AMT = 0;
    short WS_TOT_SCH_TERM = 0;
    short WS_PHS_TOT_TERM = 0;
    short WS_MOD_TOT_TERM = 0;
    double WS_TOT_AMT = 0;
    double WS_REL_TOT_AMT = 0;
    double WS_REM_AMT = 0;
    int WS_BEG_DATE = 0;
    int WS_END_DATE = 0;
    short WS_PRE_TOT_TENORS = 0;
    short WS_TOT_TENORS = 0;
    double WS_TOT_PRIN = 0;
    short WS_TENORS = 0;
    short WS_CUR_PHS_TENORS = 0;
    int WS_SCH_DT = 0;
    int WS_SCH_STRT_DT = 0;
    int WS_SCH_END_DT = 0;
    String WS_FORM_CODE = " ";
    double WS_N_RATE = 0;
    double WS_REPAID_AMT = 0;
    double WS_REM_PRIN = 0;
    double WS_PRIN_AMT = 0;
    String WS_CONTRACT_NO = " ";
    LNZSTMPP_WS_PRM_KEY WS_PRM_KEY = new LNZSTMPP_WS_PRM_KEY();
    LNZSTMPP_WS_PAY_MTH_AREA[] WS_PAY_MTH_AREA = new LNZSTMPP_WS_PAY_MTH_AREA[4];
    LNZSTMPP_WS_INST_MTH_AREA[] WS_INST_MTH_AREA = new LNZSTMPP_WS_INST_MTH_AREA[3];
    short WS_PHS_NO = 0;
    short WS_PHS_NO1 = 0;
    short WS_PERD = 0;
    char WS_PERD_UNIT = ' ';
    double WS_N_BAL = 0;
    double WS_O_BAL = 0;
    double WS_TOT_BAL = 0;
    LNZSTMPP_WS_DATE WS_DATE = new LNZSTMPP_WS_DATE();
    LNZSTMPP_WS_OUT_HEAD WS_OUT_HEAD = new LNZSTMPP_WS_OUT_HEAD();
    List<LNZSTMPP_WS_OUT_INFO> WS_OUT_INFO = new ArrayList<LNZSTMPP_WS_OUT_INFO>();
    char WS_UPDATE_FLG = ' ';
    char WS_FND_FLG = ' ';
    char WS_ITEM_FND_FLG = ' ';
    LNRTMPP LNRTMPP = new LNRTMPP();
    LNRCONT LNRCONT = new LNRCONT();
    LNRPLPI LNRPLPI = new LNRPLPI();
    LNCMSG_ERROR_MSG LNCMSG_ERROR_MSG = new LNCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCFMT SCCFMT = new SCCFMT();
    SCCMSG SCCMSG = new SCCMSG();
    LNCRTMPP LNCRTMPP = new LNCRTMPP();
    LNRICTL LNRICTL = new LNRICTL();
    LNCOTMPP LNCOTMPP = new LNCOTMPP();
    LNCTMPPB LNCTMPPB = new LNCTMPPB();
    LNCLOANM LNCLOANM = new LNCLOANM();
    LNCRCONT LNCRCONT = new LNCRCONT();
    LNCICTLM LNCICTLM = new LNCICTLM();
    LNCILCM LNCILCM = new LNCILCM();
    LNCRATQ LNCRATQ = new LNCRATQ();
    SCCCLDT SCCCLDT = new SCCCLDT();
    BPCFTLPM BPCFTLPM = new BPCFTLPM();
    LNCAPRDM LNCAPRDM = new LNCAPRDM();
    LNCICUT LNCICUT = new LNCICUT();
    LNCSLNQ LNCSLNQ = new LNCSLNQ();
    LNCCTLPM LNCCTLPM = new LNCCTLPM();
    BPCQCCY BPCQCCY = new BPCQCCY();
    LNCSCALT LNCSCALT = new LNCSCALT();
    LNCCNEX LNCCNEX = new LNCCNEX();
    int WS_START_NUM = 0;
    SCCGWA SCCGWA;
    LNCSTMPP LNCSTMPP;
    public LNZSTMPP() {
        for (int i=0;i<4;i++) WS_PAY_MTH_AREA[i] = new LNZSTMPP_WS_PAY_MTH_AREA();
        for (int i=0;i<3;i++) WS_INST_MTH_AREA[i] = new LNZSTMPP_WS_INST_MTH_AREA();
    }
    public void MP(SCCGWA SCCGWA, LNCSTMPP LNCSTMPP) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        this.LNCSTMPP = LNCSTMPP;
        CEP.TRC(SCCGWA);
        A00_INIT_PROC();
        if (pgmRtn) return;
        B00_MAIN_PROC();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, "LNZSTMPP return!");
        Z_RET();
        if (pgmRtn) return;
        JIBS_RETURN();
    }
    public void A00_INIT_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCRTMPP);
        IBS.init(SCCGWA, LNCOTMPP);
    }
