package com.hisun.LN;

import com.hisun.SC.*;
import com.hisun.BP.*;
import com.hisun.CI.*;

import java.io.IOException;
import java.sql.SQLException;

public class LNZULNC {
    String JIBS_tmp_str[] = new String[10];
    int JIBS_tmp_int;
    DBParm LNTAGRE_RD;
    DBParm LNTSETL_RD;
    boolean pgmRtn = false;
    String PGM_SCSSCLDT = "SCSSCLDT";
    char K_NORMAL_CONT = '0';
    char K_CUSH_CONT = '1';
    char K_BALLON_LOAN = '1';
    char K_PAYMTH_03 = '3';
    char K_PAYMTH_05 = '5';
    String K_CLDD = "CLDD";
    char K_CKPD_INQ = '0';
    char K_CDUEAUTO_FLG1 = '1';
    char K_CDUEAUTO_FLG2 = '2';
    char K_CDUEAUTO_FLG3 = '3';
    char K_CDUEAUTO_FLG4 = '4';
    char K_ACCRUAL_TYPE0 = '0';
    char K_ACCRUAL_TYPE1 = '1';
    char K_ACCRUAL_TYPE2 = '2';
    char WS_CCY_ID = ' ';
    int WS_I = 0;
    String WS_FORM_CODE = " ";
    double WS_N_RATE = 0;
    double WS_TOT_PRIN_AMT = 0;
    double WS_PRIN_AMT = 0;
    char WS_INST_MTH = ' ';
    char WS_REP_OPT = ' ';
    double WS_INST_AMT = 0;
    short WS_INST_TERM = 0;
    short WS_INST_PERD = 0;
    char WS_INST_PERD_UNIT = ' ';
    short WS_TMP_INST_TERM = 0;
    short WS_PHS_NO = 0;
    double WS_INT_IRA = 0;
    double WS_PEN_IRA = 0;
    double WS_CPND_IRA = 0;
    double WS_ABUS_IRA = 0;
    LNZULNC_WS_LOAN_CONT_AREA WS_LOAN_CONT_AREA = new LNZULNC_WS_LOAN_CONT_AREA();
    LNZULNC_WS_PRM_KEY WS_PRM_KEY = new LNZULNC_WS_PRM_KEY();
    LNZULNC_WS_CHECK_INFO WS_CHECK_INFO = new LNZULNC_WS_CHECK_INFO();
    char WS_UPDATE_FLG = ' ';
    char WS_FOUND_FLG = ' ';
    LNRLOAN LNRLOAN = new LNRLOAN();
    LNCMSG_ERROR_MSG LNCMSG_ERROR_MSG = new LNCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCCLDT SCCCLDT = new SCCCLDT();
    LNCAPRDM LNCAPRDM = new LNCAPRDM();
    LNCCONTM LNCCONTM = new LNCCONTM();
    LNCLOANM LNCLOANM = new LNCLOANM();
    LNCICTLM LNCICTLM = new LNCICTLM();
    LNCRATNM LNCRATNM = new LNCRATNM();
    LNCRATLM LNCRATLM = new LNCRATLM();
    LNCBALLM LNCBALLM = new LNCBALLM();
    LNCPLPIM LNCPLPIM = new LNCPLPIM();
    LNRAGRE LNRAGRE = new LNRAGRE();
    LNRSETL LNRSETL = new LNRSETL();
    LNCILCM LNCILCM = new LNCILCM();
    LNCPAIPM LNCPAIPM = new LNCPAIPM();
    LNCRATG LNCRATG = new LNCRATG();
    BPCCGAC BPCCGAC = new BPCCGAC();
    BPCACLDD BPCACLDD = new BPCACLDD();
    BPCPQPRD BPCPQPRD = new BPCPQPRD();
    LNCCMTPM LNCCMTPM = new LNCCMTPM();
    BPCSCGWY BPCSCGWY = new BPCSCGWY();
    CICQACRI CICQACRI = new CICQACRI();
    CICACCU CICACCU = new CICACCU();
    LNRAPRD LNRAPRD = new LNRAPRD();
    LNCRATHM LNCRATHM = new LNCRATHM();
    LNRRATH LNRRATH = new LNRRATH();
    LNCSRATE LNCSRATE = new LNCSRATE();
    LNCSCKPD LNCSCKPD = new LNCSCKPD();
    SCCTPCL SCCTPCL = new SCCTPCL();
    SCCGWA SCCGWA;
    LNCULNC LNCULNC;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    SCCGAPV SCCGAPV;
    public void MP(SCCGWA SCCGWA, LNCULNC LNCULNC) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        this.LNCULNC = LNCULNC;
        CEP.TRC(SCCGWA);
        A00_INIT_PROC();
        if (pgmRtn) return;
        B00_MAIN_PROC();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, "LNZULNC return!");
        Z_RET();
        if (pgmRtn) return;
    }
    public void A00_INIT_PROC() throws IOException,SQLException,Exception {
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        SCCGAPV = (SCCGAPV) GWA_SC_AREA.APVL_AREA_PTR;
        LNCULNC.RC.RC_APP = "LN";
        LNCULNC.RC.RC_RTNCODE = 0;
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.CONTRACT_NO);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.INT_DAY_BAS);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.ACCRUAL_TYPE);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.HOLIDAY_METH);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.HOLIDAY_OVER);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.LN_TOT_AMT);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.VAL_DT);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.DUE_DT);
    }
    public void B00_MAIN_PROC() throws IOException,SQLException,Exception {
        B000_CHECK();
        if (pgmRtn) return;
        B000_MAIN_PROC();
        if (pgmRtn) return;
    }
    public void B000_CHECK() throws IOException,SQLException,Exception {
        if (LNCULNC.COMM_DATA.VAL_DT > LNCULNC.COMM_DATA.DUE_DT) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_VALDT_GRT_DUEDT, LNCULNC.RC);
            Z_RET();
            if (pgmRtn) return;
        }
        if (LNCULNC.COMM_DATA.FST_CAL_DT == 0) {
            LNCULNC.COMM_DATA.FST_CAL_DT = LNCULNC.COMM_DATA.DUE_DT;
        }
        if (LNCULNC.COMM_DATA.FST_CAL_DT < LNCULNC.COMM_DATA.VAL_DT) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_DATE, LNCULNC.RC);
            Z_RET();
            if (pgmRtn) return;
        }
        if (LNCULNC.COMM_DATA.FST_FLT_DT < LNCULNC.COMM_DATA.VAL_DT) {
            if (LNCULNC.COMM_DATA.FLT_MTH == '1') {
                LNCULNC.COMM_DATA.FST_FLT_DT = LNCULNC.COMM_DATA.VAL_DT;
            } else {
                if (LNCULNC.COMM_DATA.FLT_MTH == '2') {
                    LNCULNC.COMM_DATA.FST_FLT_DT = LNCULNC.COMM_DATA.VAL_DT;
                } else {
                    LNCULNC.COMM_DATA.FST_FLT_DT = LNCULNC.COMM_DATA.FST_CAL_DT;
                }
            }
        }
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.INST_TERM);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.INST_AMT);
        if (LNCULNC.COMM_DATA.PAY_MTH == '4' 
            && LNCULNC.COMM_DATA.INST_TERM == 0 
            && LNCULNC.COMM_DATA.INST_AMT == 0) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_LN5776, LNCULNC.RC);
            Z_RET();
            if (pgmRtn) return;
        }
        if (LNCULNC.COMM_DATA.BAS_DATE_DT == 0) {
            LNCULNC.COMM_DATA.BAS_DATE_DT = LNCULNC.COMM_DATA.VAL_DT;
        }
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B300_GET_PRDT_PARM();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.SUF_NO);
        if (LNCULNC.COMM_DATA.SUF_NO == 0) {
            B400_ADD_APRD_PROCESS();
            if (pgmRtn) return;
            B500_ADD_LOAN_PROCESS();
            if (pgmRtn) return;
        }
        B600_ADD_ICTL_PROCESS();
        if (pgmRtn) return;
        B700_ADD_BALL_PROCESS();
        if (pgmRtn) return;
        B800_ADD_RATH_PROC();
        if (pgmRtn) return;
        if (LNCAPRDM.REC_DATA.PAY_MTH == '4') {
            B900_ADD_PAIP_PROCESS();
            if (pgmRtn) return;
        } else {
        }
    }
    public void B300_GET_PRDT_PARM() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCSCKPD);
        LNCSCKPD.FUNC = K_CKPD_INQ;
        LNCSCKPD.PROD_CD = LNCULNC.COMM_DATA.PROD_CD;
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.PROD_CD);
        S000_CALL_LNZSCKPD();
        if (pgmRtn) return;
    }
    public void B400_ADD_APRD_PROCESS() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCAPRDM);
        CEP.TRC(SCCGWA, LNCAPRDM.REC_DATA.CAL_PERD);
        CEP.TRC(SCCGWA, LNCAPRDM.REC_DATA.PAYP_PERD);
        B410_MOVE_CTLPM_PARM();
        if (pgmRtn) return;
        B420_MOVE_LOANAC_PARM();
        if (pgmRtn) return;
        LNCAPRDM.FUNC = '0';
        S000_CALL_LNZAPRDM();
        if (pgmRtn) return;
    }
    public void B410_MOVE_CTLPM_PARM() throws IOException,SQLException,Exception {
        LNCAPRDM.REC_DATA.KEY.CONTRACT_NO = LNCULNC.COMM_DATA.CONTRACT_NO;
        LNCAPRDM.REC_DATA.PAY_MTH = LNCULNC.COMM_DATA.PAY_MTH;
        LNCAPRDM.REC_DATA.DUE_AUTO_FLG = K_CDUEAUTO_FLG4;
        LNCAPRDM.REC_DATA.ACCRUAL_TYPE = K_ACCRUAL_TYPE0;
    }
    public void B420_MOVE_LOANAC_PARM() throws IOException,SQLException,Exception {
        LNCAPRDM.REC_DATA.PAY_MTH = LNCULNC.COMM_DATA.PAY_MTH;
        LNCAPRDM.REC_DATA.BPAY_MTH = LNCULNC.COMM_DATA.BREP_MTH;
        LNCAPRDM.REC_DATA.INST_MTH = LNCULNC.COMM_DATA.INST_MTH;
        LNCAPRDM.REC_DATA.CAL_PERD = LNCULNC.COMM_DATA.CAL_PERD;
        LNCAPRDM.REC_DATA.CAL_PERD_UNIT = LNCULNC.COMM_DATA.CAL_PERD_UNIT;
        LNCAPRDM.REC_DATA.BCAL_PERD = LNCULNC.COMM_DATA.PAYI_PERD;
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.PAY_MTH);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.CAL_PERD);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.CAL_PERD_UNIT);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.PAYP_PERD);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.PAYP_PERU);
        if (LNCULNC.COMM_DATA.PAY_MTH == '4' 
            && (LNCULNC.COMM_DATA.PAYP_PERU == ' ' 
            || LNCULNC.COMM_DATA.PAYP_PERD == 0)) {
            LNCULNC.COMM_DATA.PYP_CIRC = LNCULNC.COMM_DATA.PAYI_PERD;
            LNCULNC.COMM_DATA.PAYP_PERD = LNCULNC.COMM_DATA.CAL_PERD;
            LNCULNC.COMM_DATA.PAYP_PERU = LNCULNC.COMM_DATA.CAL_PERD_UNIT;
        }
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.PAYP_PERD);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.PAYP_PERU);
        LNCAPRDM.REC_DATA.PAYP_PERD_UNIT = LNCULNC.COMM_DATA.PAYP_PERU;
        LNCAPRDM.REC_DATA.PAYP_PERD = LNCULNC.COMM_DATA.PAYP_PERD;
        CEP.TRC(SCCGWA, "POCPOCPOCPOC");
        LNCAPRDM.REC_DATA.W_I_FLG = LNCULNC.COMM_DATA.W_I_FLG;
        LNCAPRDM.REC_DATA.W_I_PERD_UNIT = LNCULNC.COMM_DATA.W_I_PERU;
        LNCAPRDM.REC_DATA.W_I_PERD = LNCULNC.COMM_DATA.W_I_PERD;
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.W_I_FLG);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.W_I_PERU);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.W_I_PERD);
        CEP.TRC(SCCGWA, LNCAPRDM.REC_DATA.W_I_FLG);
        CEP.TRC(SCCGWA, LNCAPRDM.REC_DATA.W_I_PERD_UNIT);
        CEP.TRC(SCCGWA, LNCAPRDM.REC_DATA.W_I_PERD);
        CEP.TRC(SCCGWA, LNCAPRDM.REC_DATA.PAYP_PERD);
        CEP.TRC(SCCGWA, LNCAPRDM.REC_DATA.PAYP_PERD_UNIT);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.PAYP_GRACE);
        LNCAPRDM.REC_DATA.BPAYP_PERD = LNCULNC.COMM_DATA.PYP_CIRC;
        LNCAPRDM.REC_DATA.P_GRACE_TERM = LNCULNC.COMM_DATA.PAYP_GRACE;
        if (LNCULNC.COMM_DATA.CAL_PAY_DAY_TYP == ' ') {
            LNCULNC.COMM_DATA.CAL_PAY_DAY_TYP = '1';
            JIBS_tmp_str[0] = "" + LNCULNC.COMM_DATA.VAL_DT;
            JIBS_tmp_int = JIBS_tmp_str[0].length();
            for (int i=0;i<8-JIBS_tmp_int;i++) JIBS_tmp_str[0] = "0"+JIBS_tmp_str[0];
            if (JIBS_tmp_str[0].substring(7 - 1, 7 + 2 - 1).trim().length() == 0) LNCULNC.COMM_DATA.CAL_PAY_DAY = 0;
            else LNCULNC.COMM_DATA.CAL_PAY_DAY = Short.parseShort(JIBS_tmp_str[0].substring(7 - 1, 7 + 2 - 1));
        }
        LNCAPRDM.REC_DATA.PAY_DAY = LNCULNC.COMM_DATA.CAL_PAY_DAY;
        LNCAPRDM.REC_DATA.PAY_DD_TYPE = LNCULNC.COMM_DATA.CAL_PAY_DAY_TYP;
        if (LNCAPRDM.REC_DATA.PAY_DD_TYPE == '2' 
            && (LNCULNC.COMM_DATA.PAYI_PERD == '2' 
            || LNCULNC.COMM_DATA.PAYI_PERD == '3') 
            && LNCAPRDM.REC_DATA.PAY_DAY > 7) {
            LNCAPRDM.REC_DATA.PAY_DAY = 1;
        }
        CEP.TRC(SCCGWA, LNCAPRDM.REC_DATA.PAY_DAY);
        CEP.TRC(SCCGWA, LNCAPRDM.REC_DATA.PAY_DD_TYPE);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.CAL_PAY_DAY_TERM);
        LNCAPRDM.REC_DATA.PAY_DD_LTERM = LNCULNC.COMM_DATA.CAL_PAY_DAY_TERM;
        LNCAPRDM.REC_DATA.FST_PAY_FLG = LNCULNC.COMM_DATA.CAL_FST_FLG;
        LNCAPRDM.REC_DATA.ACCRUAL_TYPE = LNCULNC.COMM_DATA.ACCRUAL_TYPE;
        LNCAPRDM.REC_DATA.INT_DBAS_STD = LNCULNC.COMM_DATA.INT_DAY_BAS;
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.GRA_DAYS_ACC);
        LNCAPRDM.REC_DATA.PRIN_DOG = LNCULNC.COMM_DATA.GRA_DAYS_ACC;
        LNCAPRDM.REC_DATA.DOG_PSTD_FLG = 'N';
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.P_GRA_MTH);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.I_GRA_MTH);
        LNCAPRDM.REC_DATA.PRIN_DOG_MTH = LNCULNC.COMM_DATA.P_GRA_MTH;
        LNCAPRDM.REC_DATA.INT_DOG_MTH = LNCULNC.COMM_DATA.I_GRA_MTH;
        LNCAPRDM.REC_DATA.RCMP_INT = LNCULNC.COMM_DATA.INT_MTH;
        if (LNCULNC.COMM_DATA.INT_MTH == '0') {
            LNCAPRDM.REC_DATA.RCMP_INT = 'N';
        }
        if (LNCULNC.COMM_DATA.INT_MTH == '1') {
            LNCAPRDM.REC_DATA.RCMP_INT = 'Y';
        }
        LNCAPRDM.REC_DATA.DUE_AUTO_FLG = LNCULNC.COMM_DATA.PAY_AUTO_FLG;
        LNCAPRDM.REC_DATA.GDA_AUTO_DB = LNCULNC.COMM_DATA.GUAR_DUE_AP;
        LNCAPRDM.REC_DATA.GDA_DB_SEQ = LNCULNC.COMM_DATA.GUAR_PAY_SEQ;
        LNCAPRDM.REC_DATA.PREP_CHG_RATE = LNCULNC.COMM_DATA.PREP_CHR;
        LNCAPRDM.REC_DATA.ORAT_SAME = LNCULNC.COMM_DATA.CPND_USE;
        LNCAPRDM.REC_DATA.GDA_APRE = LNCULNC.COMM_DATA.GUAP_REF;
        LNCAPRDM.REC_DATA.GDA_AUTO_DB = LNCULNC.COMM_DATA.GUAR_DUE_AP;
        LNCAPRDM.REC_DATA.GDA_DB_SEQ = LNCULNC.COMM_DATA.GUAR_PAY_SEQ;
        LNCAPRDM.REC_DATA.CHG_DB_FLG = LNCULNC.COMM_DATA.HAND_CHG_MTH;
        LNCAPRDM.REC_DATA.CHG_TERM_FLG = LNCULNC.COMM_DATA.PFE_MTH;
        LNCAPRDM.REC_DATA.HAND_CHG_RATE = LNCULNC.COMM_DATA.HAND_CHG_RATE;
        LNCAPRDM.REC_DATA.HAND_CHG_OPCT = LNCULNC.COMM_DATA.HAND_OVR_PCT;
        LNCAPRDM.REC_DATA.HAND_CHG_AMT = LNCULNC.COMM_DATA.PERD_PENT;
        LNCAPRDM.REC_DATA.ACCT_MGT_RATE = LNCULNC.COMM_DATA.AC_MNG_CHRG;
        LNCAPRDM.REC_DATA.OCAL_PERD = LNCULNC.COMM_DATA.OCAL_PERD;
        LNCAPRDM.REC_DATA.OCAL_PERD_UNIT = LNCULNC.COMM_DATA.OCAL_PERD_UNIT;
        LNCAPRDM.REC_DATA.SPEC_LN_FLG = LNCULNC.COMM_DATA.SP_FLG;
        LNCAPRDM.REC_DATA.SPEC_AC_FLG = LNCULNC.COMM_DATA.SPEC_AC_FLG;
        LNCAPRDM.REC_DATA.PAY_SEQ = LNCULNC.COMM_DATA.PAY_SEQ;
        LNCAPRDM.REC_DATA.GRACE_TYP = LNCULNC.COMM_DATA.GRA_TYP;
    }
    public void B500_ADD_LOAN_PROCESS() throws IOException,SQLException,Exception {
        B510_ADD_CONT_PROCESS();
        if (pgmRtn) return;
        B520_ADD_LOAN_PROCESS();
        if (pgmRtn) return;
    }
    public void B510_ADD_CONT_PROCESS() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCCONTM);
        LNCCONTM.FUNC = '0';
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.TRCHCMMT_NO);
        LNCCONTM.REC_DATA.KEY.CONTRACT_NO = LNCULNC.COMM_DATA.CONTRACT_NO;
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.CNTR_NO);
        LNCCONTM.REC_DATA.FATHER_CONTRACT = LNCULNC.COMM_DATA.CNTR_NO;
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.TR_ID);
        LNCCONTM.REC_DATA.CONTRACT_TYPE = "CLDD";
        CEP.TRC(SCCGWA, LNCCONTM.REC_DATA.CONTRACT_TYPE);
        LNCCONTM.REC_DATA.CTA_STS = '0';
        LNCCONTM.REC_DATA.PROD_CD = LNCULNC.COMM_DATA.PROD_CD;
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.VOU_MTH);
        LNCCONTM.REC_DATA.DRAWDOWN_MTH = LNCULNC.COMM_DATA.VOU_MTH;
        CEP.TRC(SCCGWA, LNCCONTM.REC_DATA.PROD_CD);
        CEP.TRC(SCCGWA, LNCCONTM.REC_DATA.DRAWDOWN_MTH);
        LNCCONTM.REC_DATA.CCY = LNCULNC.COMM_DATA.CCY;
        LNCCONTM.REC_DATA.LN_TOT_AMT = LNCULNC.COMM_DATA.ORIG_TOT_AMT;
        LNCCONTM.REC_DATA.ORIG_TOT_AMT = LNCULNC.COMM_DATA.ORIG_TOT_AMT;
        LNCCONTM.REC_DATA.START_DATE = LNCULNC.COMM_DATA.VAL_DT;
        LNCCONTM.REC_DATA.MAT_DATE = LNCULNC.COMM_DATA.DUE_DT;
        LNCCONTM.REC_DATA.ORI_MAT_DATE = LNCULNC.COMM_DATA.DUE_DT;
        LNCCONTM.REC_DATA.BOOK_BR = LNCULNC.COMM_DATA.BOOK_BR;
        LNCCONTM.REC_DATA.DOMI_BR = LNCULNC.COMM_DATA.DOMI_BR;
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.EXCH_RATE);
        LNCCONTM.REC_DATA.EXCHANGE_RATE = LNCULNC.COMM_DATA.EXCH_RATE;
        LNCCONTM.REC_DATA.EQUIVALENT = LNCULNC.COMM_DATA.EQU;
        LNCCONTM.REC_DATA.REMARK1 = LNCULNC.COMM_DATA.REMARK1;
        LNCCONTM.REC_DATA.REL_CONTRACT = LNCULNC.COMM_DATA.CONSIGN_CMMIT;
        LNCCONTM.REC_DATA.LAST_TX_DT = SCCGWA.COMM_AREA.AC_DATE;
        LNCCONTM.REC_DATA.TRAN_DTE = SCCGWA.COMM_AREA.AC_DATE;
        LNCCONTM.REC_DATA.TRAN_JRN = SCCGWA.COMM_AREA.JRN_NO;
        LNCCONTM.REC_DATA.LAST_F_VAL_DATE = 0;
        LNCCONTM.REC_DATA.LAST_TX_SEQ = 0;
        LNCCONTM.REC_DATA.REL_CONTRACT = LNCULNC.COMM_DATA.CONSIGN_CMMIT;
        LNCCONTM.REC_DATA.REQ_FRM_NO = SCCGWA.COMM_AREA.REQ_SYSTEM;
        S000_CALL_LNZCONTM();
        if (pgmRtn) return;
    }
    public void B520_ADD_LOAN_PROCESS() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCLOANM);
        LNCLOANM.FUNC = '0';
        LNCLOANM.REC_DATA.KEY.CONTRACT_NO = LNCULNC.COMM_DATA.CONTRACT_NO;
        LNCLOANM.REC_DATA.BRAT_EFF_DT = LNCULNC.COMM_DATA.VAL_DT;
        LNCLOANM.REC_DATA.ORAT_EFF_DT = LNCULNC.COMM_DATA.VAL_DT;
        LNCLOANM.REC_DATA.LRAT_EFF_DT = LNCULNC.COMM_DATA.VAL_DT;
        LNCLOANM.REC_DATA.PRAT_EFF_DT = LNCULNC.COMM_DATA.VAL_DT;
        LNCLOANM.REC_DATA.FST_CAL_DT = LNCULNC.COMM_DATA.FST_CAL_DT;
        if (LNCULNC.COMM_DATA.W_I_FLG == 'Y') {
            B521_W_I_DUE_DATE_PROCESS();
            if (pgmRtn) return;
        } else {
        }
        if (LNCULNC.COMM_DATA.PAY_MTH == K_PAYMTH_03 
            || (LNCULNC.COMM_DATA.PAY_MTH == K_PAYMTH_05 
            && LNCULNC.COMM_DATA.PAYP_PERU != ' ' 
            && LNCULNC.COMM_DATA.PAYP_PERD != 0)) {
            LNCLOANM.REC_DATA.FST_PAYP_DT = LNCULNC.COMM_DATA.FST_CAL_PRIN;
        } else {
            LNCLOANM.REC_DATA.FST_PAYP_DT = LNCULNC.COMM_DATA.DUE_DT;
        }
        LNCLOANM.REC_DATA.AUTO_AMT = LNCULNC.COMM_DATA.AUTO_AMT;
        LNCLOANM.REC_DATA.CTL_TYPE = LNCULNC.COMM_DATA.ADV_TYP.charAt(0);
        LNCLOANM.REC_DATA.PD_PROJ_NO = LNCULNC.COMM_DATA.GJ_PROJ_NO;
        S000_CALL_LNZLOANM();
        if (pgmRtn) return;
    }
    public void B521_W_I_DUE_DATE_PROCESS() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, SCCCLDT);
        SCCCLDT.DATE1 = LNCULNC.COMM_DATA.VAL_DT;
        if (LNCULNC.COMM_DATA.W_I_PERU == 'Y') {
            SCCCLDT.MTHS = (short) (LNCULNC.COMM_DATA.W_I_PERD * 12);
        } else {
            if (LNCULNC.COMM_DATA.W_I_PERU == 'M') {
                SCCCLDT.MTHS = LNCULNC.COMM_DATA.W_I_PERD;
            } else {
                SCCCLDT.DAYS = LNCULNC.COMM_DATA.W_I_PERD;
            }
        }
        CEP.TRC(SCCGWA, SCCCLDT.DATE1);
        CEP.TRC(SCCGWA, SCCCLDT.MTHS);
        CEP.TRC(SCCGWA, SCCCLDT.DAYS);
        S000_CALL_SCSSCLDT();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, SCCCLDT.DATE2);
        LNCLOANM.REC_DATA.STOP_VAL_DT = LNCULNC.COMM_DATA.VAL_DT;
        LNCLOANM.REC_DATA.STOP_INT_DATE = LNCULNC.COMM_DATA.VAL_DT;
        LNCLOANM.REC_DATA.STOP_DUE_DT = SCCCLDT.DATE2;
    }
    public void B600_ADD_ICTL_PROCESS() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, "1111111");
        CEP.TRC(SCCGWA, LNCICTLM.REC_DATA.CUR_RAT);
        IBS.init(SCCGWA, LNCICTLM);
        LNCICTLM.FUNC = '0';
        LNCICTLM.REC_DATA.KEY.CONTRACT_NO = LNCULNC.COMM_DATA.CONTRACT_NO;
        LNCICTLM.REC_DATA.KEY.SUB_CTA_NO = LNCULNC.COMM_DATA.SUF_NO;
        LNCICTLM.REC_DATA.CTL_STSW = "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
        if (LNCICTLM.REC_DATA.CTL_STSW == null) LNCICTLM.REC_DATA.CTL_STSW = "";
        JIBS_tmp_int = LNCICTLM.REC_DATA.CTL_STSW.length();
        for (int i=0;i<128-JIBS_tmp_int;i++) LNCICTLM.REC_DATA.CTL_STSW += " ";
        LNCICTLM.REC_DATA.CTL_STSW = "1" + LNCICTLM.REC_DATA.CTL_STSW.substring(1);
        if (LNCSCKPD.PROD_CLS.equalsIgnoreCase("P005")) {
            if (LNCICTLM.REC_DATA.CTL_STSW == null) LNCICTLM.REC_DATA.CTL_STSW = "";
            JIBS_tmp_int = LNCICTLM.REC_DATA.CTL_STSW.length();
            for (int i=0;i<128-JIBS_tmp_int;i++) LNCICTLM.REC_DATA.CTL_STSW += " ";
            LNCICTLM.REC_DATA.CTL_STSW = LNCICTLM.REC_DATA.CTL_STSW.substring(0, 19 - 1) + "1" + LNCICTLM.REC_DATA.CTL_STSW.substring(19 + 1 - 1);
            if (LNCICTLM.REC_DATA.CTL_STSW == null) LNCICTLM.REC_DATA.CTL_STSW = "";
            JIBS_tmp_int = LNCICTLM.REC_DATA.CTL_STSW.length();
            for (int i=0;i<128-JIBS_tmp_int;i++) LNCICTLM.REC_DATA.CTL_STSW += " ";
            LNCICTLM.REC_DATA.CTL_STSW = LNCICTLM.REC_DATA.CTL_STSW.substring(0, 71 - 1) + "1" + LNCICTLM.REC_DATA.CTL_STSW.substring(71 + 1 - 1);
        }
        if (LNCULNC.COMM_DATA.VAL_DT < SCCGWA.COMM_AREA.AC_DATE) {
            if (LNCICTLM.REC_DATA.CTL_STSW == null) LNCICTLM.REC_DATA.CTL_STSW = "";
            JIBS_tmp_int = LNCICTLM.REC_DATA.CTL_STSW.length();
            for (int i=0;i<128-JIBS_tmp_int;i++) LNCICTLM.REC_DATA.CTL_STSW += " ";
            LNCICTLM.REC_DATA.CTL_STSW = LNCICTLM.REC_DATA.CTL_STSW.substring(0, 5 - 1) + "1" + LNCICTLM.REC_DATA.CTL_STSW.substring(5 + 1 - 1);
        }
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.B_PRJ_NO);
        if (LNCULNC.COMM_DATA.B_PRJ_NO != 0) {
            if (LNCICTLM.REC_DATA.CTL_STSW == null) LNCICTLM.REC_DATA.CTL_STSW = "";
            JIBS_tmp_int = LNCICTLM.REC_DATA.CTL_STSW.length();
            for (int i=0;i<128-JIBS_tmp_int;i++) LNCICTLM.REC_DATA.CTL_STSW += " ";
            LNCICTLM.REC_DATA.CTL_STSW = LNCICTLM.REC_DATA.CTL_STSW.substring(0, 54 - 1) + "1" + LNCICTLM.REC_DATA.CTL_STSW.substring(54 + 1 - 1);
        }
        if (LNCULNC.COMM_DATA.AUTO_DFLG == 'Y') {
            if (LNCICTLM.REC_DATA.CTL_STSW == null) LNCICTLM.REC_DATA.CTL_STSW = "";
            JIBS_tmp_int = LNCICTLM.REC_DATA.CTL_STSW.length();
            for (int i=0;i<128-JIBS_tmp_int;i++) LNCICTLM.REC_DATA.CTL_STSW += " ";
            LNCICTLM.REC_DATA.CTL_STSW = LNCICTLM.REC_DATA.CTL_STSW.substring(0, 42 - 1) + "1" + LNCICTLM.REC_DATA.CTL_STSW.substring(42 + 1 - 1);
        }
        LNCICTLM.REC_DATA.P_CUR_TERM = 1;
        LNCICTLM.REC_DATA.IC_CUR_TERM = 1;
        LNCICTLM.REC_DATA.SUBS_CUR_TERM = 0;
        LNCICTLM.REC_DATA.SUBS_LAST_REPY_DT = 0;
        LNCICTLM.REC_DATA.IC_CAL_PHS_NO = 1;
        LNCICTLM.REC_DATA.IC_CMP_PHS_NO = 1;
        LNCICTLM.REC_DATA.IC_CMP_TERM = 1;
        LNCICTLM.REC_DATA.IC_CMP_VAL_DT = LNCULNC.COMM_DATA.INT_PER_STRT;
        LNCICTLM.REC_DATA.IC_CMP_DUE_DT = LNCULNC.COMM_DATA.FST_CAL_DT;
        LNCICTLM.REC_DATA.IC_CAL_TERM = 1;
        LNCICTLM.REC_DATA.IC_CAL_VAL_DT = LNCULNC.COMM_DATA.INT_PER_STRT;
        LNCICTLM.REC_DATA.IC_CAL_DUE_DT = LNCULNC.COMM_DATA.FST_CAL_DT;
        LNCICTLM.REC_DATA.P_CMP_TERM = 1;
        if (LNCULNC.COMM_DATA.PAY_MTH == K_PAYMTH_03 
            || (LNCULNC.COMM_DATA.PAY_MTH == K_PAYMTH_05 
            && LNCULNC.COMM_DATA.PAYP_PERU != ' ' 
            && LNCULNC.COMM_DATA.PAYP_PERD != 0)) {
            LNCICTLM.REC_DATA.P_CMP_DUE_DT = LNCULNC.COMM_DATA.FST_CAL_PRIN;
        } else {
            LNCICTLM.REC_DATA.P_CMP_DUE_DT = LNCULNC.COMM_DATA.DUE_DT;
        }
        JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, SCCGWA.COMM_AREA.TR_ID);
        if (JIBS_tmp_str[0].equalsIgnoreCase("0132260")) {
            if (LNCICTLM.REC_DATA.CTL_STSW == null) LNCICTLM.REC_DATA.CTL_STSW = "";
            JIBS_tmp_int = LNCICTLM.REC_DATA.CTL_STSW.length();
            for (int i=0;i<128-JIBS_tmp_int;i++) LNCICTLM.REC_DATA.CTL_STSW += " ";
            LNCICTLM.REC_DATA.CTL_STSW = LNCICTLM.REC_DATA.CTL_STSW.substring(0, 70 - 1) + "1" + LNCICTLM.REC_DATA.CTL_STSW.substring(70 + 1 - 1);
            if (LNCICTLM.REC_DATA.CTL_STSW == null) LNCICTLM.REC_DATA.CTL_STSW = "";
            JIBS_tmp_int = LNCICTLM.REC_DATA.CTL_STSW.length();
            for (int i=0;i<128-JIBS_tmp_int;i++) LNCICTLM.REC_DATA.CTL_STSW += " ";
            LNCICTLM.REC_DATA.CTL_STSW = LNCICTLM.REC_DATA.CTL_STSW.substring(0, 51 - 1) + "1" + LNCICTLM.REC_DATA.CTL_STSW.substring(51 + 1 - 1);
        }
        LNCICTLM.REC_DATA.P_CAL_TERM = 1;
        if (LNCULNC.COMM_DATA.PAY_MTH == K_PAYMTH_03 
            || (LNCULNC.COMM_DATA.PAY_MTH == K_PAYMTH_05 
            && LNCULNC.COMM_DATA.PAYP_PERU != ' ' 
            && LNCULNC.COMM_DATA.PAYP_PERD != 0)) {
            LNCICTLM.REC_DATA.P_CAL_DUE_DT = LNCULNC.COMM_DATA.FST_CAL_PRIN;
        } else {
            LNCICTLM.REC_DATA.P_CAL_DUE_DT = LNCULNC.COMM_DATA.DUE_DT;
        }
        LNCICTLM.REC_DATA.NEXT_ACCU_DT = 0;
        LNCICTLM.REC_DATA.INT_CUT_DT = LNCULNC.COMM_DATA.VAL_DT;
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.VAL_DT);
        CEP.TRC(SCCGWA, LNCICTLM.REC_DATA.INT_CUT_DT);
        CEP.TRC(SCCGWA, "222222");
        CEP.TRC(SCCGWA, LNCICTLM.REC_DATA.CUR_RAT);
        S000_CALL_LNZICTLM();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, "333333");
        CEP.TRC(SCCGWA, LNCICTLM.REC_DATA.CUR_RAT);
    }
    public void B800_ADD_RATH_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCSRATE);
        LNCSRATE.FUNC_TYP = 'A';
        LNCSRATE.SPE_DEAL_FLG = '1';
        LNCSRATE.DATA.CONTRACT_NO = LNCULNC.COMM_DATA.CONTRACT_NO;
        LNCSRATE.DATA.SUB_CTA_NO = 0;
        LNCSRATE.DATA.RAT_CHG_DT = LNCULNC.COMM_DATA.INT_PER_STRT;
        LNCSRATE.DATA.RATE_KIND_N = 'Y';
        LNCSRATE.DATA.RATE_KIND_O = 'Y';
        LNCSRATE.DATA.RATE_KIND_L = 'Y';
        LNCSRATE.DATA.RATE_KIND_P = 'Y';
        LNCSRATE.DATA.MTH = LNCULNC.COMM_DATA.FLT_MTH;
        LNCSRATE.DATA.FLT_MTH_N = LNCULNC.COMM_DATA.NFLT_METHOD;
        LNCSRATE.DATA.RATE_TYP_N = LNCULNC.COMM_DATA.INT_RATE_TYPE;
        CEP.TRC(SCCGWA, LNCSRATE.DATA.RATE_TYP_N);
        LNCSRATE.DATA.RATEPERD_N = LNCULNC.COMM_DATA.INT_RATE_CLAS;
        LNCSRATE.DATA.RATE_VAR_N = LNCULNC.COMM_DATA.RATE_VAR;
        LNCSRATE.DATA.RATE_PCT_N = LNCULNC.COMM_DATA.RATE_PCT;
        LNCSRATE.DATA.RATE_INT_N = LNCULNC.COMM_DATA.RAT_INT;
        LNCSRATE.DATA.INT_RAT_N = LNCULNC.COMM_DATA.ALL_IN_RATE;
        LNCSRATE.DATA.PEN_RRAT_O = LNCULNC.COMM_DATA.PEN_RRAT;
        LNCSRATE.DATA.PEN_TYP_O = LNCULNC.COMM_DATA.PEN_TYPE;
        LNCSRATE.DATA.PEN_RATT_O = LNCULNC.COMM_DATA.PEN_RATT;
        LNCSRATE.DATA.PEN_RATC_O = LNCULNC.COMM_DATA.PEN_RATC;
        LNCSRATE.DATA.PEN_SPR_O = LNCULNC.COMM_DATA.PEN_SPR;
        LNCSRATE.DATA.PEN_PCT_O = LNCULNC.COMM_DATA.PEN_PCT;
        LNCSRATE.DATA.INT_RAT_O = LNCULNC.COMM_DATA.PEN_IRAT;
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.PEN_IRAT);
        LNCSRATE.DATA.INT_MTH = LNCSCKPD.CM_TYP;
        LNCSRATE.DATA.CPND_USE = LNCULNC.COMM_DATA.CPND_USE;
        LNCSRATE.DATA.CPND_RTY_L = LNCULNC.COMM_DATA.CPND_RTYPE;
        LNCSRATE.DATA.CPND_TYP_L = LNCULNC.COMM_DATA.CPND_TYP;
        LNCSRATE.DATA.CPNDRATT_L = LNCULNC.COMM_DATA.CPND_RATT;
        LNCSRATE.DATA.CPNDRATC_L = LNCULNC.COMM_DATA.CPND_RATC;
        LNCSRATE.DATA.CPND_SPR_L = LNCULNC.COMM_DATA.CPND_SPR;
        LNCSRATE.DATA.CPND_PCT_L = LNCULNC.COMM_DATA.CPND_PCT;
        LNCSRATE.DATA.INT_RAT_L = LNCULNC.COMM_DATA.CPND_IRATE;
        LNCSRATE.DATA.ABUS_RAT_P = LNCULNC.COMM_DATA.ABUS_RAT_TYP;
        LNCSRATE.DATA.ABUS_TYP_P = LNCULNC.COMM_DATA.ABUS_FLT_TYP;
        LNCSRATE.DATA.ABUSRATT_P = LNCULNC.COMM_DATA.ABUS_RATTYPE;
        LNCSRATE.DATA.ABUSRATC_P = LNCULNC.COMM_DATA.ABUS_RAT_TERM;
        LNCSRATE.DATA.ABUSSPR_P = LNCULNC.COMM_DATA.ABUS_SPR;
        LNCSRATE.DATA.ABUSPCT_P = LNCULNC.COMM_DATA.ABUS_PCT;
        LNCSRATE.DATA.INT_RAT_P = LNCULNC.COMM_DATA.ABUS_IRAT;
        LNCSRATE.DATA.FST_FLT_DT = LNCULNC.COMM_DATA.FST_FLT_DT;
        LNCSRATE.DATA.NEXT_FLT_DT = LNCULNC.COMM_DATA.FST_FLT_DT;
        LNCSRATE.DATA.FLT_PERD_UNIT = LNCULNC.COMM_DATA.FLT_PERD_UNIT;
        LNCSRATE.DATA.FIRST_FLT_FLG = LNCULNC.COMM_DATA.FIRST_FLT_FLG;
        LNCSRATE.DATA.FLT_PERD = LNCULNC.COMM_DATA.FLT_PERD;
        LNCSRATE.DATA.FLT_DAY = LNCULNC.COMM_DATA.FLT_DAY;
        S000_CALL_LNZSRATE();
        if (pgmRtn) return;
        WS_N_RATE = LNCSRATE.DATA.INT_RAT_N;
    }
    public void B700_ADD_BALL_PROCESS() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCBALLM);
        CEP.TRC(SCCGWA, WS_LOAN_CONT_AREA);
        LNCBALLM.FUNC = '0';
        LNCBALLM.REC_DATA.KEY.CONTRACT_NO = LNCULNC.COMM_DATA.CONTRACT_NO;
        LNCBALLM.REC_DATA.KEY.SUB_CTA_NO = LNCULNC.COMM_DATA.SUF_NO;
        WS_LOAN_CONT_AREA.WS_LOAN_CONT_AREA_LEN1 = 1584;
        JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, WS_LOAN_CONT_AREA);
        IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], LNCBALLM.REC_DATA.LOAN_CONT_AREA);
        JIBS_tmp_str[1] = IBS.CLS2CPY(SCCGWA, LNCBALLM.REC_DATA.LOAN_CONT_AREA);
        IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[1], LNCBALLM.REC_DATA.REDEFINES18);
        S000_CALL_LNZBALLM();
        if (pgmRtn) return;
    }
    public void B900_ADD_PAIP_PROCESS() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, LNCAPRDM.REC_DATA.PAY_MTH);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.INST_MTH);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.PHS_FLG);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.REP_OPT);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.PHS_NUM);
        CEP.TRC(SCCGWA, WS_N_RATE);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.PHS_DATA[1-1].PHS_TOT_TERM);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.PHS_DATA[1-1].PHS_PRIN_AMT);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.PHS_DATA[1-1].PHS_INST_AMT);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.PHS_DATA[1-1].PHS_TOT_TERM);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.PHS_DATA[1-1].PHS_PRIN_AMT);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.PHS_DATA[1-1].PHS_INST_AMT);
        WS_PHS_NO = 1;
        if (LNCULNC.COMM_DATA.PHS_FLG == 'Y') {
            B910_PHS_YES_PROCESS();
            if (pgmRtn) return;
        } else {
            WS_PRIN_AMT = LNCULNC.COMM_DATA.ORIG_TOT_AMT;
            WS_INST_MTH = LNCULNC.COMM_DATA.INST_MTH;
            WS_REP_OPT = LNCULNC.COMM_DATA.REP_OPT;
            WS_INST_PERD = LNCULNC.COMM_DATA.CAL_PERD;
            WS_INST_PERD_UNIT = LNCULNC.COMM_DATA.CAL_PERD_UNIT;
            WS_INST_AMT = LNCULNC.COMM_DATA.INST_AMT;
            WS_INST_TERM = LNCULNC.COMM_DATA.INST_TERM;
            B920_PHS_PAIP_PROCESS();
            if (pgmRtn) return;
            LNCULNC.COMM_DATA.INST_AMT = LNCILCM.COMM_DATA.INST_AMT;
            CEP.TRC(SCCGWA, LNCILCM.COMM_DATA.INST_AMT);
            LNCULNC.COMM_DATA.INST_TERM = LNCILCM.COMM_DATA.TERM;
        }
        if (LNCULNC.COMM_DATA.MAX_TERM == 0) {
            LNCULNC.COMM_DATA.MAX_TERM = LNCULNC.COMM_DATA.INST_TERM;
        }
        if (LNCULNC.COMM_DATA.INST_TERM > LNCULNC.COMM_DATA.MAX_TERM) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_LN5747, LNCULNC.RC);
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void B910_PHS_YES_PROCESS() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, "B910-PHS-YES-PROCESS0001");
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.PHS_DATA[1-1].PHS_PRIN_AMT);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.PHS_DATA[2-1].PHS_PRIN_AMT);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.PHS_DATA[3-1].PHS_PRIN_AMT);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.PHS_DATA[4-1].PHS_PRIN_AMT);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.PHS_DATA[5-1].PHS_PRIN_AMT);
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.PHS_NUM);
        LNCULNC.COMM_DATA.INST_TERM = 0;
        for (WS_I = 1; WS_I <= LNCULNC.COMM_DATA.PHS_NUM; WS_I += 1) {
            WS_REP_OPT = LNCULNC.COMM_DATA.PHS_DATA[WS_I-1].PHS_REP_OPT;
            WS_INST_MTH = LNCULNC.COMM_DATA.PHS_DATA[WS_I-1].PHS_INST_MTH;
            WS_INST_TERM = LNCULNC.COMM_DATA.PHS_DATA[WS_I-1].PHS_TOT_TERM;
            WS_PRIN_AMT = LNCULNC.COMM_DATA.PHS_DATA[WS_I-1].PHS_PRIN_AMT;
            WS_INST_AMT = LNCULNC.COMM_DATA.PHS_DATA[WS_I-1].PHS_INST_AMT;
            WS_INST_PERD = LNCULNC.COMM_DATA.PHS_DATA[WS_I-1].PHS_PERD;
            WS_INST_PERD_UNIT = LNCULNC.COMM_DATA.PHS_DATA[WS_I-1].PHS_PERU;
            WS_PHS_NO = (short) WS_I;
            CEP.TRC(SCCGWA, WS_PRIN_AMT);
            CEP.TRC(SCCGWA, WS_I);
            CEP.TRC(SCCGWA, "WS-I2018062701");
            CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.PHS_DATA[1-1].PHS_PRIN_AMT);
            CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.PHS_DATA[2-1].PHS_PRIN_AMT);
            CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.PHS_DATA[3-1].PHS_PRIN_AMT);
            CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.PHS_DATA[4-1].PHS_PRIN_AMT);
            CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.PHS_DATA[5-1].PHS_PRIN_AMT);
            CEP.TRC(SCCGWA, "WS-I2018062702");
            B920_PHS_PAIP_PROCESS();
            if (pgmRtn) return;
            LNCULNC.COMM_DATA.PHS_DATA[WS_I-1].PHS_INST_AMT = LNCILCM.COMM_DATA.INST_AMT;
            WS_TOT_PRIN_AMT += LNCILCM.COMM_DATA.PRIN_AMT;
            LNCULNC.COMM_DATA.PHS_DATA[WS_I-1].PHS_TOT_TERM = LNCILCM.COMM_DATA.TERM;
            LNCULNC.COMM_DATA.INST_TERM += LNCILCM.COMM_DATA.TERM;
            CEP.TRC(SCCGWA, WS_REP_OPT);
            CEP.TRC(SCCGWA, WS_INST_MTH);
            CEP.TRC(SCCGWA, WS_INST_TERM);
            CEP.TRC(SCCGWA, WS_PRIN_AMT);
            CEP.TRC(SCCGWA, WS_INST_AMT);
            CEP.TRC(SCCGWA, LNCILCM.COMM_DATA.INST_AMT);
            CEP.TRC(SCCGWA, LNCILCM.COMM_DATA.TERM);
        }
        if (WS_TOT_PRIN_AMT > LNCULNC.COMM_DATA.LN_TOT_AMT) {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_ERR_GE_PAY_P_AMT, LNCULNC.RC);
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void B920_PHS_PAIP_PROCESS() throws IOException,SQLException,Exception {
        if (WS_INST_MTH == '1') {
            WS_FORM_CODE = "31";
        } else if (WS_INST_MTH == '2') {
            WS_FORM_CODE = "34";
        } else if (WS_INST_MTH == '3'
            || WS_INST_MTH == '4') {
            WS_FORM_CODE = "33";
        } else if (WS_INST_MTH == '5') {
            WS_FORM_CODE = "32";
        }
        B911_INSTALMENT_PROCESS();
        if (pgmRtn) return;
        B912_ADD_PAIP_RECORD();
        if (pgmRtn) return;
    }
    public void B911_INSTALMENT_PROCESS() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, WS_REP_OPT);
        if (WS_REP_OPT == 'T') {
            B911_COMP_INSAMT_PROCESS();
            if (pgmRtn) return;
        } else {
            B911_COMP_TOTTRM_PROCESS();
            if (pgmRtn) return;
        }
    }
    public void B911_COMP_INSAMT_PROCESS() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, "WS-I201806270002");
        CEP.TRC(SCCGWA, WS_PRIN_AMT);
        IBS.init(SCCGWA, LNCILCM);
        LNCILCM.COMM_DATA.FORM_CODE = WS_FORM_CODE;
        LNCILCM.COMM_DATA.FUNC_CODE = '1';
        LNCILCM.COMM_DATA.PRIN_AMT = WS_PRIN_AMT;
        LNCILCM.COMM_DATA.RATE = WS_N_RATE;
        LNCILCM.COMM_DATA.BASDAYS_STD = LNCAPRDM.REC_DATA.INT_DBAS_STD;
        LNCILCM.COMM_DATA.PERIOD = WS_INST_PERD;
        LNCILCM.COMM_DATA.PERIOD_UNIT = WS_INST_PERD_UNIT;
        LNCILCM.COMM_DATA.HANDLING_PERC = 0;
        CEP.TRC(SCCGWA, LNCULNC.COMM_DATA.CCY);
        LNCILCM.COMM_DATA.CCY = LNCULNC.COMM_DATA.CCY;
        LNCILCM.COMM_DATA.TERM = WS_INST_TERM;
        CEP.TRC(SCCGWA, LNCILCM.COMM_DATA.TERM);
        CEP.TRC(SCCGWA, LNCILCM.COMM_DATA.PRIN_AMT);
        S000_CALL_LNZILCM();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, LNCILCM.COMM_DATA.INST_AMT);
    }
    public void B911_COMP_TOTTRM_PROCESS() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCILCM);
        LNCILCM.COMM_DATA.FORM_CODE = WS_FORM_CODE;
        LNCILCM.COMM_DATA.FUNC_CODE = '2';
        LNCILCM.COMM_DATA.PRIN_AMT = WS_PRIN_AMT;
        LNCILCM.COMM_DATA.RATE = WS_N_RATE;
        LNCILCM.COMM_DATA.BASDAYS_STD = LNCAPRDM.REC_DATA.INT_DBAS_STD;
        LNCILCM.COMM_DATA.PERIOD = WS_INST_PERD;
        LNCILCM.COMM_DATA.PERIOD_UNIT = WS_INST_PERD_UNIT;
        LNCILCM.COMM_DATA.HANDLING_PERC = 0;
        LNCILCM.COMM_DATA.CCY = LNCULNC.COMM_DATA.CCY;
        LNCILCM.COMM_DATA.INST_AMT = WS_INST_AMT;
        S000_CALL_LNZILCM();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, LNCILCM.COMM_DATA.INST_AMT);
    }
    public void B912_ADD_PAIP_RECORD() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, LNCPAIPM);
        LNCPAIPM.FUNC = '0';
        LNCPAIPM.REC_DATA.KEY.CONTRACT_NO = LNCULNC.COMM_DATA.CONTRACT_NO;
        LNCPAIPM.REC_DATA.KEY.SUB_CTA_NO = LNCULNC.COMM_DATA.SUF_NO;
        LNCPAIPM.REC_DATA.KEY.PHS_NO = WS_PHS_NO;
        LNCPAIPM.REC_DATA.INST_MTH = WS_INST_MTH;
        LNCPAIPM.REC_DATA.PERD = WS_INST_PERD;
        LNCPAIPM.REC_DATA.PERD_UNIT = WS_INST_PERD_UNIT;
        LNCPAIPM.REC_DATA.PHS_PRIN_AMT = WS_PRIN_AMT;
        LNCPAIPM.REC_DATA.PHS_REM_PRIN_AMT = WS_PRIN_AMT;
        CEP.TRC(SCCGWA, LNCILCM.COMM_DATA.TERM);
        LNCPAIPM.REC_DATA.PHS_TOT_TERM = LNCILCM.COMM_DATA.TERM;
        LNCPAIPM.REC_DATA.PHS_INST_AMT = LNCILCM.COMM_DATA.INST_AMT;
        LNCPAIPM.REC_DATA.CUR_INST_AMT = LNCILCM.COMM_DATA.INST_AMT;
        LNCPAIPM.REC_DATA.CUR_INST_IRAT = WS_N_RATE;
        LNCPAIPM.REC_DATA.PHS_CAL_TERM = 0;
        LNCPAIPM.REC_DATA.PHS_CMP_TERM = 0;
        S000_CALL_LNZPAIPM();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, LNCILCM.COMM_DATA.INST_AMT);
    }
    public void T000_READ_LNTAGRE() throws IOException,SQLException,Exception {
        LNTAGRE_RD = new DBParm();
        LNTAGRE_RD.TableName = "LNTAGRE";
        LNTAGRE_RD.where = "CONTRACT_NO = :LNRAGRE.KEY.CONTRACT_NO";
        IBS.READ(SCCGWA, LNRAGRE, this, LNTAGRE_RD);
        if (SCCGWA.COMM_AREA.DBIO_FLG == '1') {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_AGRE_NOTFND, LNCULNC.RC);
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void T000_READ_LNTSETL() throws IOException,SQLException,Exception {
        LNTSETL_RD = new DBParm();
        LNTSETL_RD.TableName = "LNTSETL";
        LNTSETL_RD.where = "CONTRACT_NO = :LNRAGRE.KEY.CONTRACT_NO "
            + "AND CI_TYPE = 'B' "
            + "AND SETTLE_TYPE = '1'";
        LNTSETL_RD.fst = true;
        IBS.READ(SCCGWA, LNRSETL, this, LNTSETL_RD);
        if (SCCGWA.COMM_AREA.DBIO_FLG == '1') {
            IBS.CPY2CLS(SCCGWA, LNCMSG_ERROR_MSG.LN_SETL_NOTFND, LNCULNC.RC);
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void S000_CALL_LNZAPRDM() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, "ERRORERROR");
        CEP.TRC(SCCGWA, LNCAPRDM);
        IBS.CALLCPN(SCCGWA, "LN-SRC-APRD-MAINT", LNCAPRDM);
        if (LNCAPRDM.RC.RC_RTNCODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, LNCAPRDM.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], LNCULNC.RC);
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void S000_CALL_LNZLOANM() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-SRC-LOAN-MAINT", LNCLOANM);
        if (LNCLOANM.RC.RC_RTNCODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, LNCLOANM.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], LNCULNC.RC);
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void S000_CALL_LNZCONTM() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-SRC-CONT-MAINT", LNCCONTM);
        if (LNCCONTM.RC.RC_RTNCODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, LNCCONTM.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], LNCULNC.RC);
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void S000_CALL_LNZICTLM() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-SRC-ICTL-MAINT", LNCICTLM);
        if (LNCICTLM.RC.RC_RTNCODE != 0) {
            LNCULNC.RC.RC_APP = LNCICTLM.RC.RC_APP;
            LNCULNC.RC.RC_RTNCODE = LNCICTLM.RC.RC_RTNCODE;
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void S000_CALL_SCSSCLDT() throws IOException,SQLException,Exception {
        SCSSCLDT SCSSCLDT1 = new SCSSCLDT();
        SCSSCLDT1.MP(SCCGWA, SCCCLDT);
        CEP.TRC(SCCGWA, SCCCLDT.RC);
        if (SCCCLDT.RC != 0) {
            LNCULNC.RC.RC_APP = "SC";
            LNCULNC.RC.RC_RTNCODE = SCCCLDT.RC;
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void S000_CALL_LNZSRATE() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-SEV-RATE-MAINT", LNCSRATE);
        if (LNCSRATE.RC.RC_RTNCODE != 0) {
            LNCULNC.RC.RC_APP = LNCSRATE.RC.RC_APP;
            LNCULNC.RC.RC_RTNCODE = LNCSRATE.RC.RC_RTNCODE;
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void S000_CALL_LNZILCM() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-FUN-INST-AMT-CMP", LNCILCM);
        if (LNCILCM.RC.RC_RTNCODE != 0) {
            LNCULNC.RC.RC_APP = LNCILCM.RC.RC_APP;
            LNCULNC.RC.RC_RTNCODE = LNCILCM.RC.RC_RTNCODE;
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void S000_CALL_LNZBALLM() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-SRC-BALL-MAINT", LNCBALLM);
        if (LNCBALLM.RC.RC_RTNCODE != 0) {
            LNCULNC.RC.RC_APP = LNCBALLM.RC.RC_APP;
            LNCULNC.RC.RC_RTNCODE = LNCBALLM.RC.RC_RTNCODE;
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void S000_CALL_LNZPAIPM() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-SRC-PAIP-MAINT", LNCPAIPM);
        if (LNCPAIPM.RC.RC_RTNCODE != 0) {
            LNCULNC.RC.RC_APP = LNCPAIPM.RC.RC_APP;
            LNCULNC.RC.RC_RTNCODE = LNCPAIPM.RC.RC_RTNCODE;
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void S000_CALL_LNZSCKPD() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "LN-S-CHK-PROD", LNCSCKPD);
    }
    public void S000_CALL_SCZTPCL() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "SC-LINK-EXTSERV", SCCTPCL);
    }
    public void S000_CALL_CIZQACRI() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "CI-INQ-ACR-INF", CICQACRI);
        CEP.TRC(SCCGWA, CICQACRI.RC.RC_CODE);
        if (CICQACRI.RC.RC_CODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, CICQACRI.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], LNCULNC.RC);
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void S000_CALL_CIZACCU() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "CI-INQ-ACCU", CICACCU);
        if (CICACCU.RC.RC_CODE != 0) {
            JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, CICACCU.RC);
            IBS.CPY2CLS(SCCGWA, JIBS_tmp_str[0], LNCULNC.RC);
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void S000_CALL_BPZSCGWY() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, BPCSCGWY.PRDT_CODE);
        CEP.TRC(SCCGWA, BPCSCGWY.CHANG_WAY);
        IBS.CALLCPN(SCCGWA, "BP-S-MAINT-CGWY", BPCSCGWY);
        if (BPCSCGWY.RC.RC_CODE != 0) {
            LNCULNC.RC.RC_APP = BPCSCGWY.RC.RC_MMO;
            LNCULNC.RC.RC_RTNCODE = BPCSCGWY.RC.RC_CODE;
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void Z_RET() throws IOException,SQLException,Exception {
    if (SCCGWA.COMM_AREA.BSP_FLG.equalsIgnoreCase("BSP") || SCCGWA.COMM_AREA.CHNL.equalsIgnoreCase("BAT")) { //FROM #IFDEF BAT
        if (LNCULNC.RC.RC_RTNCODE != 0) {
            CEP.TRC(SCCGWA, "LNCULNC=");
            CEP.TRC(SCCGWA, LNCULNC);
        }
    } //FROM #ENDIF
        pgmRtn = true;
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
