package com.hisun.CI;

public class CICI9031 {
    public String CI_NO = " ";
    public String ID_TYPE = " ";
    public String ID_NO = " ";
    public int EXP_DT = 0;
    public String CI_NM = " ";
    public String CI_ENM = " ";
    public char CI_TYP = ' ';
    public char CI_ATTR = ' ';
    public String STSW = " ";
    public int OPEN_DT = 0;
    public int OWNER_BK = 0;
    public int CLOSE_DT = 0;
    public String OPN_CHNL = " ";
    public String SUB_TYP = " ";
    public char FTA_FLG = ' ';
    public char EP_FLG = ' ';
    public String SVR_LVL = " ";
    public String TAX_BANK = " ";
    public String TAX_AC = " ";
    public char TAX_TYPE = ' ';
    public String TAX_DSNO = " ";
    public char RESIDENT = ' ';
    public char SEX = ' ';
    public int BIRTH_DT = 0;
    public String NATION = " ";
    public String REG_CNTY = " ";
    public char SID_FLG = ' ';
    public String TEL_NO = " ";
    public String OIC_NO = " ";
    public String RESP_CD = " ";
    public String SUB_DP = " ";
    public char INFO_IND = ' ';
    public String VER_STS = " ";
    public char AG_FLG = ' ';
    public String AG_TP = " ";
    public String AG_ID_TP = " ";
    public String AG_ID_NO = " ";
    public String AG_NAME = " ";
    public String AG_TEL = " ";
    public char AG_SEX = ' ';
    public int AG_BIRTH = 0;
}
