package com.hisun.CI;

public class CICI5330 {
    public char CI_TYP = ' ';
    public char CI_ATTR = ' ';
    public String CI_NM = " ";
    public String CI_ENM = " ";
    public String CI_ONM = " ";
    public String ID_TYPE = " ";
    public String ID_NO = " ";
    public String ID_RMK = " ";
    public String SUB_TYP = " ";
    public char RESIDENT = ' ';
    public String ORG_TYPE = " ";
    public String FIN_TYPE = " ";
    public String ECO = " ";
    public String HECO = " ";
    public String INDUS1 = " ";
    public String ENC_CD = " ";
    public char SID_FLG = ' ';
    public char SIZE = ' ';
    public String BUSN_SCP = " ";
    public int REG_DT = 0;
    public String REG_CCY = " ";
    public double REG_AMT = 0;
    public String HCNTY = " ";
    public String SVR_LVL = " ";
    public String NED_TYP = " ";
    public String DEP_TYPE = " ";
    public String PB_AP_NO = " ";
    public String PB_BANK = " ";
    public String PB_AC_NO = " ";
    public String OIC_NO = " ";
    public String PROD_TYP = " ";
    public String STK_NO = " ";
    public String LST_CITY = " ";
    public String REMARK = " ";
    public double OPER_INC = 0;
    public double REVENUE = 0;
    public int EMP_NUM = 0;
    public double TOTL_ASS = 0;
    public double NET_ASS = 0;
    public double CAP_AMT = 0;
    public String CAP_CCY = " ";
    public char PL_FLG = ' ';
    public char PEA_FLG = ' ';
    public char GRE_FLG = ' ';
    public String COR_NO = " ";
    public String M_COR_NO = " ";
    public String NRA_TAX = " ";
    public char OWN_STR = ' ';
    public char ORGIN_TP = ' ';
    public String ORGIN1 = " ";
    public String ORGIN2 = " ";
    public String RESP_CD = " ";
    public String SUB_DP = " ";
    public char CDG_EMP = ' ';
    public String INDUS2 = " ";
    public String HKC_TYP = " ";
    public String CSTS_TYP = " ";
    public String FLTS_NO = " ";
    public String TICKER = " ";
    public int SCH_DT = 0;
    public CICI5330_ID_AREA[] ID_AREA = new CICI5330_ID_AREA[4];
    public CICI5330_ADR_AREA[] ADR_AREA = new CICI5330_ADR_AREA[4];
    public String SUP_NM = " ";
    public String SUP_ORNO = " ";
    public String SUP_APNO = " ";
    public CICI5330_CNT_AREA[] CNT_AREA = new CICI5330_CNT_AREA[4];
    public String CNT1_NM = " ";
    public String CNT1_MOB = " ";
    public String CNT1_TEL = " ";
    public String CNT2_NM = " ";
    public String CNT2_MOB = " ";
    public String CNT2_TEL = " ";
    public String DIR_NM = " ";
    public String DIR_MOB = " ";
    public String DIR_TEL = " ";
    public CICI5330_REL_AREA[] REL_AREA = new CICI5330_REL_AREA[20];
    public String TAX_BANK = " ";
    public String TAX_ACNO = " ";
    public char TAX_TYPE = ' ';
    public String TAX_DSNO = " ";
    public String FATCA_TP = " ";
    public int W8W9_DT = 0;
    public String TIN_NO = " ";
    public String GIIN_CD = " ";
    public String CRS_TYPE = " ";
    public String CRS_DESC = " ";
    public int PROOF_DT = 0;
    public char PROOF_CH = ' ';
    public CICI5330_CRS_AREA[] CRS_AREA = new CICI5330_CRS_AREA[25];
    public CICI5330() {
        for (int i=0;i<4;i++) ID_AREA[i] = new CICI5330_ID_AREA();
        for (int i=0;i<4;i++) ADR_AREA[i] = new CICI5330_ADR_AREA();
        for (int i=0;i<4;i++) CNT_AREA[i] = new CICI5330_CNT_AREA();
        for (int i=0;i<20;i++) REL_AREA[i] = new CICI5330_REL_AREA();
        for (int i=0;i<25;i++) CRS_AREA[i] = new CICI5330_CRS_AREA();
    }
}
