package com.hisun.CI;

public class CICOFDM_DATA {
    public String CI_NO = " ";
    public char BAS_CI_TYP = ' ';
    public char BAS_CI_ATTR = ' ';
    public String BAS_SVR_LVL = " ";
    public int BAS_OPEN_DT = 0;
    public int BAS_CLOSE_DT = 0;
    public String BAS_ORIGIN = " ";
    public String BAS_CI_NM = " ";
    public char FILLER10 = 0X02;
    public String BAS_ID_TYPE = " ";
    public String BAS_ID_NO = " ";
    public char FILLER13 = 0X02;
    public String BAS_ID_RGN = " ";
    public int BAS_BBR = 0;
    public String BAS_OIC_NO = " ";
    public char RESIDENT = ' ';
    public String CI_SUB_TYP = " ";
    public String INTEL_TYPE = " ";
    public String FIN_TYPE = " ";
    public String ECO = " ";
    public String HECO = " ";
    public String BUSN_SCP = " ";
    public char FILLER24 = 0X02;
    public int REG_DT = 0;
    public String REG_CCY = " ";
    public double REG_AMT = 0;
    public String NED_TYP = " ";
    public String INDUS1 = " ";
    public String ORG_TYPE = " ";
    public String ENC = " ";
    public char SIZE = ' ';
    public char INSIZE = ' ';
    public char TAX_CLS = ' ';
    public char CAS_FLG = ' ';
    public char SID_FLG = ' ';
    public String HCNTY = " ";
    public String FATCA = " ";
}
