package com.hisun.CI;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;

import java.io.IOException;
import java.sql.SQLException;

public class CIOT9150 {
    short WS_I = 0;
    CICMSG_ERROR_MSG CICMSG_ERROR_MSG = new CICMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCFMT SCCFMT = new SCCFMT();
    SCCMSG SCCMSG = new SCCMSG();
    CICSOPC CICSOPC = new CICSOPC();
    SCCGWA SCCGWA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    CIB9150_AWA_9150 CIB9150_AWA_9150;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "CIOT9150 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "CIB9150_AWA_9150>");
        CIB9150_AWA_9150 = (CIB9150_AWA_9150) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        IBS.init(SCCGWA, CICSOPC);
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B010_CHECK_INPUT_DATA();
        B020_OPEN_PER_CUST();
    }
    public void B010_CHECK_INPUT_DATA() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, CIB9150_AWA_9150.ID_TYPE);
        CEP.TRC(SCCGWA, CIB9150_AWA_9150.ID_NO);
        CEP.TRC(SCCGWA, CIB9150_AWA_9150.CI_NM);
    }
    public void B020_OPEN_PER_CUST() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, CICSOPC);
        CICSOPC.DATA.CI_TYP = '1';
        CICSOPC.DATA.CI_ATTR = '1';
        CICSOPC.DATA.CI_NM = CIB9150_AWA_9150.CI_NM;
        CICSOPC.DATA.ID_TYPE = CIB9150_AWA_9150.ID_TYPE;
        CICSOPC.DATA.ID_NO = CIB9150_AWA_9150.ID_NO;
        CICSOPC.DATA.ID_RMK = CIB9150_AWA_9150.ID_RMK;
        CICSOPC.DATA.SUB_TYP = CIB9150_AWA_9150.SUB_TYP;
        CICSOPC.DATA.RESIDENT = CIB9150_AWA_9150.RESIDENT;
        CICSOPC.DATA.SEX = CIB9150_AWA_9150.SEX;
        CICSOPC.DATA.BIRTH_DT = CIB9150_AWA_9150.BIRTH_DT;
        CICSOPC.DATA.REG_CNTY = CIB9150_AWA_9150.REG_CNTY;
        CICSOPC.DATA.NATION = CIB9150_AWA_9150.NATION;
        CICSOPC.DATA.OCCUP = CIB9150_AWA_9150.OCCUP;
        CICSOPC.DATA.VER_FLG = CIB9150_AWA_9150.VER_FLG;
        CICSOPC.DATA.SID_FLG = CIB9150_AWA_9150.SID_FLG;
        CICSOPC.DATA.PL_FLG = CIB9150_AWA_9150.PL_FLG;
        CICSOPC.DATA.PER_INC = CIB9150_AWA_9150.PER_INC;
        CICSOPC.DATA.ORGIN_TP = CIB9150_AWA_9150.ORGIN_TP;
        CICSOPC.DATA.ORGIN1 = CIB9150_AWA_9150.ORGIN1;
        CICSOPC.DATA.ORGIN2 = CIB9150_AWA_9150.ORGIN2;
        CICSOPC.DATA.OPEN_BR = CIB9150_AWA_9150.OPEN_BR;
        CICSOPC.DATA.HKC_TYP = "T10";
        for (WS_I = 1; WS_I <= 1; WS_I += 1) {
            CICSOPC.DATA.ID_AREA[WS_I-1].ID_OPT = 'A';
            CICSOPC.DATA.ID_AREA[WS_I-1].ID_IDTYP = CIB9150_AWA_9150.ID_TYPE;
            CICSOPC.DATA.ID_AREA[WS_I-1].ID_IDNO = CIB9150_AWA_9150.ID_NO;
            CICSOPC.DATA.ID_AREA[WS_I-1].ID_EXPDT = CIB9150_AWA_9150.ID_EXPDT;
            CICSOPC.DATA.ID_AREA[WS_I-1].ID_OPEN = 'Y';
            CICSOPC.DATA.ID_AREA[WS_I-1].ID_IDRMK = CIB9150_AWA_9150.ID_RMK;
        }
        for (WS_I = 1; WS_I <= 2; WS_I += 1) {
            if (CIB9150_AWA_9150.ADR_AREA[WS_I-1].ADR_TYPE.trim().length() > 0) {
                CICSOPC.DATA.ADR_AREA[WS_I-1].ADR_OPT = 'A';
                CICSOPC.DATA.ADR_AREA[WS_I-1].ADR_TYPE = CIB9150_AWA_9150.ADR_AREA[WS_I-1].ADR_TYPE;
                CICSOPC.DATA.ADR_AREA[WS_I-1].ADR_CNTY = CIB9150_AWA_9150.ADR_AREA[WS_I-1].ADR_CNTY;
                CICSOPC.DATA.ADR_AREA[WS_I-1].ADR_L1 = CIB9150_AWA_9150.ADR_AREA[WS_I-1].ADR_L1;
                CICSOPC.DATA.ADR_AREA[WS_I-1].ADR_L2 = CIB9150_AWA_9150.ADR_AREA[WS_I-1].ADR_L2;
                CICSOPC.DATA.ADR_AREA[WS_I-1].ADR_L3 = CIB9150_AWA_9150.ADR_AREA[WS_I-1].ADR_L3;
                CICSOPC.DATA.ADR_AREA[WS_I-1].ADR_NM = CIB9150_AWA_9150.ADR_AREA[WS_I-1].ADR_NM;
                CICSOPC.DATA.ADR_AREA[WS_I-1].ADR_POST = CIB9150_AWA_9150.ADR_AREA[WS_I-1].ADR_POST;
            }
        }
        for (WS_I = 1; WS_I <= 2; WS_I += 1) {
            if (CIB9150_AWA_9150.CNT_AREA[WS_I-1].CNT_TYPE.trim().length() > 0) {
                CICSOPC.DATA.CNT_AREA[WS_I-1].CNT_OPT = 'A';
                CICSOPC.DATA.CNT_AREA[WS_I-1].CNT_TYPE = CIB9150_AWA_9150.CNT_AREA[WS_I-1].CNT_TYPE;
                CICSOPC.DATA.CNT_AREA[WS_I-1].CNT_CNTY = CIB9150_AWA_9150.CNT_AREA[WS_I-1].CNT_CNTY;
                CICSOPC.DATA.CNT_AREA[WS_I-1].CNT_TECN = CIB9150_AWA_9150.CNT_AREA[WS_I-1].CNT_TECN;
                CICSOPC.DATA.CNT_AREA[WS_I-1].CNT_ZONE = CIB9150_AWA_9150.CNT_AREA[WS_I-1].CNT_ZONE;
                CICSOPC.DATA.CNT_AREA[WS_I-1].CNT_TEL = CIB9150_AWA_9150.CNT_AREA[WS_I-1].CNT_TEL;
                CICSOPC.DATA.CNT_AREA[WS_I-1].CNT_TEL2 = CIB9150_AWA_9150.CNT_AREA[WS_I-1].CNT_TEL2;
                CICSOPC.DATA.CNT_AREA[WS_I-1].CNT_INFO = CIB9150_AWA_9150.CNT_AREA[WS_I-1].CNT_INFO;
            }
        }
        CICSOPC.DATA.TAX_BANK = CIB9150_AWA_9150.TAX_BANK;
        CICSOPC.DATA.TAX_ACNO = CIB9150_AWA_9150.TAX_ACNO;
        CICSOPC.DATA.TAX_TYPE = CIB9150_AWA_9150.TAX_TYPE;
        CICSOPC.DATA.TAX_DSNO = CIB9150_AWA_9150.TAX_DSNO;
        CICSOPC.DATA.CRS_TYPE = CIB9150_AWA_9150.CRS_TYPE;
        CICSOPC.DATA.CRS_DESC = CIB9150_AWA_9150.CRS_DESC;
        CICSOPC.DATA.PROOF_DT = CIB9150_AWA_9150.PROOF_DT;
        CICSOPC.DATA.PROOF_CH = CIB9150_AWA_9150.PROOF_CH;
        for (WS_I = 1; WS_I <= 25; WS_I += 1) {
            CICSOPC.DATA.CRS_AREA[WS_I-1].CRS_ADR = CIB9150_AWA_9150.CRS_AREA[WS_I-1].CRS_ADR;
            CICSOPC.DATA.CRS_AREA[WS_I-1].CRS_DSNO = CIB9150_AWA_9150.CRS_AREA[WS_I-1].CRS_DSNO;
            CICSOPC.DATA.CRS_AREA[WS_I-1].CRS_NDCD = CIB9150_AWA_9150.CRS_AREA[WS_I-1].CRS_NDCD;
            CICSOPC.DATA.CRS_AREA[WS_I-1].CRS_NDRE = CIB9150_AWA_9150.CRS_AREA[WS_I-1].CRS_NDRE;
        }
        S000_CALL_CIZSOPC();
    }
    public void S000_CALL_CIZSOPC() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "CI-OPEN-PER-CI", CICSOPC);
        if (CICSOPC.RC.RC_CODE != 0) {
            CEP.ERR(SCCGWA, CICSOPC.RC);
        }
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
