package com.hisun.BA;

public class BAB4010_AWA_4010 {
    public String PRPHSYSC = " ";
    public short PRPHSYSC_NO = 0;
    public int PRPHSYSD = 0;
    public short PRPHSYSD_NO = 0;
    public String PRPH_JRN = " ";
    public short PRPH_JRN_NO = 0;
    public int TX_BR = 0;
    public short TX_BR_NO = 0;
    public String PROD_CD = " ";
    public short PROD_CD_NO = 0;
    public String CNTR_NO = " ";
    public short CNTR_NO_NO = 0;
    public double LBZ_AMT = 0;
    public short LBZ_AMT_NO = 0;
    public short ACCT_CNT = 0;
    public short ACCT_CNT_NO = 0;
    public String BILL_NO = " ";
    public short BILL_NO_NO = 0;
    public String PYE_B_CD = " ";
    public short PYE_B_CD_NO = 0;
    public String B_REF_NO = " ";
    public short B_REF_NO_NO = 0;
    public String CD_UB_NO = " ";
    public short CD_UB_NO_NO = 0;
    public String LBZ_CCY = " ";
    public short LBZ_CCY_NO = 0;
    public String LMT_SYS = " ";
    public short LMT_SYS_NO = 0;
    public String PYE_B_NM = " ";
    public short PYE_B_NM_NO = 0;
    public String BILL_CUR = " ";
    public short BILL_CUR_NO = 0;
    public double BILL_AMT = 0;
    public short BILL_AMT_NO = 0;
    public int B_MAT_DT = 0;
    public short B_MAT_DT_NO = 0;
    public int DRW_DT = 0;
    public short DRW_DT_NO = 0;
    public int ACPT_DT = 0;
    public short ACPT_DT_NO = 0;
    public String ACPTBKCD = " ";
    public short ACPTBKCD_NO = 0;
    public int BIMATDT = 0;
    public short BIMATDT_NO = 0;
    public double GDALAMT = 0;
    public short GDALAMT_NO = 0;
    public double OVD_RAT = 0;
    public short OVD_RAT_NO = 0;
    public short FEE_CNT = 0;
    public short FEE_CNT_NO = 0;
    public String FEEFRZNO = " ";
    public short FEEFRZNO_NO = 0;
    public String DRWR_AC = " ";
    public short DRWR_AC_NO = 0;
    public String PYE_AC = " ";
    public short PYE_AC_NO = 0;
    public String PYE_NM = " ";
    public short PYE_NM_NO = 0;
    public String PYE_BKCD = " ";
    public short PYE_BKCD_NO = 0;
    public String PYE_BKNM = " ";
    public short PYE_BKNM_NO = 0;
    public int ACPT_BK = 0;
    public short ACPT_BK_NO = 0;
    public char DBT_SEQ = ' ';
    public short DBT_SEQ_NO = 0;
    public String FEE_BSNO = " ";
    public short FEE_BSNO_NO = 0;
    public BAB4010_FEE_DATA[] FEE_DATA = new BAB4010_FEE_DATA[5];
    public BAB4010_AWA_4010() {
        for (int i=0;i<5;i++) FEE_DATA[i] = new BAB4010_FEE_DATA();
    }
}
