package com.hisun.BA;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;

import java.io.IOException;
import java.sql.SQLException;

public class BAOT3061 {
    String K_OUTPUT_FMT = "BAI04";
    String WS_ERR_MSG = " ";
    short WS_FLD_NO = 0;
    BAOT3061_WS_OUTPUT_LIST WS_OUTPUT_LIST = new BAOT3061_WS_OUTPUT_LIST();
    BACMSG_ERROR_MSG BACMSG_ERROR_MSG = new BACMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    SCCCKDT SCCCKDT = new SCCCKDT();
    SCCFMT SCCFMT = new SCCFMT();
    BACUICLC BACUICLC = new BACUICLC();
    SCCGWA SCCGWA;
    BAB3061_AWA_3061 BAB3061_AWA_3061;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    SCCGAPV SCCGAPV;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        A000_TRANCHE_MAIN_PROC();
        CEP.TRC(SCCGWA, "BAOT3061 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "BAB3061_AWA_3061>");
        BAB3061_AWA_3061 = (BAB3061_AWA_3061) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        SCCGAPV = (SCCGAPV) GWA_SC_AREA.APVL_AREA_PTR;
    }
    public void A000_TRANCHE_MAIN_PROC() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, BAB3061_AWA_3061.K_DT);
        CEP.TRC(SCCGWA, BAB3061_AWA_3061.K_JRNNO);
        CEP.TRC(SCCGWA, BAB3061_AWA_3061.RMK);
        IBS.init(SCCGWA, BACUICLC);
        BACUICLC.DATA.K_DT = BAB3061_AWA_3061.K_DT;
        BACUICLC.DATA.K_JRNNO = BAB3061_AWA_3061.K_JRNNO;
        BACUICLC.DATA.I_RMK = BAB3061_AWA_3061.RMK;
        S000_CALL_BAZUICLC();
        if (BACUICLC.RC.RC_CODE != 0) {
            WS_ERR_MSG = IBS.CLS2CPY(SCCGWA, BACUICLC.RC);
            S000_ERR_MSG_PROC();
        } else {
            A100_FMT_OUTPUT_PROC();
        }
    }
    public void A100_FMT_OUTPUT_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, WS_OUTPUT_LIST);
        WS_OUTPUT_LIST.WS_TX_DT = BACUICLC.DATA.TX_DT;
        WS_OUTPUT_LIST.WS_CRE_JRN = BACUICLC.DATA.CRE_JRN;
        WS_OUTPUT_LIST.WS_TX_TM = BACUICLC.DATA.TX_TM;
        WS_OUTPUT_LIST.WS_BILL_NO = BACUICLC.DATA.BILL_NO;
        WS_OUTPUT_LIST.WS_CLCT_STS = BACUICLC.DATA.STP_STS;
        WS_OUTPUT_LIST.WS_BILL_STS = BACUICLC.DATA.BILL_STS;
        CEP.TRC(SCCGWA, BACUICLC.DATA.BILL_CUR);
        WS_OUTPUT_LIST.WS_BILL_CUR = BACUICLC.DATA.BILL_CUR;
        CEP.TRC(SCCGWA, WS_OUTPUT_LIST.WS_BILL_CUR);
        WS_OUTPUT_LIST.WS_BILL_AMT = BACUICLC.DATA.BILL_AMT;
        WS_OUTPUT_LIST.WS_C_REC_DT = BACUICLC.DATA.C_REC_DT;
        WS_OUTPUT_LIST.WS_C_PYE_DT = BACUICLC.DATA.C_PYE_DT;
        WS_OUTPUT_LIST.WS_C_PYE_AC = BACUICLC.DATA.C_PYE_AC;
        WS_OUTPUT_LIST.WS_C_PYE_NM = BACUICLC.DATA.C_PYE_NM;
        WS_OUTPUT_LIST.WS_C_PYE_BR = BACUICLC.DATA.C_PYE_BR;
        WS_OUTPUT_LIST.WS_C_PYE_BN = BACUICLC.DATA.C_PYE_BN;
        WS_OUTPUT_LIST.WS_DRWR_AC = BACUICLC.DATA.DRWR_AC;
        WS_OUTPUT_LIST.WS_DRWR_NM = BACUICLC.DATA.DRWR_NM;
        WS_OUTPUT_LIST.WS_DRWR_BR = BACUICLC.DATA.DRWR_BR;
        WS_OUTPUT_LIST.WS_B_MAT_DT = BACUICLC.DATA.B_MAT_DT;
        WS_OUTPUT_LIST.WS_PAY_DT = BACUICLC.DATA.PAY_DT;
        WS_OUTPUT_LIST.WS_RTN_DT = BACUICLC.DATA.RTN_DT;
        WS_OUTPUT_LIST.WS_RTN_RSN = BACUICLC.DATA.RTN_RSN.RTN_RSN_TEXT;
        WS_OUTPUT_LIST.WS_PAY_MTH = BACUICLC.DATA.PAY_MTH;
        WS_OUTPUT_LIST.WS_PAY_CHNL = BACUICLC.DATA.PAY_CHNL;
        WS_OUTPUT_LIST.WS_SPPM_FLG = BACUICLC.DATA.SPPM_FLG;
        WS_OUTPUT_LIST.WS_REMK = BACUICLC.DATA.O_REMK;
        CEP.TRC(SCCGWA, WS_OUTPUT_LIST.WS_TX_DT);
        CEP.TRC(SCCGWA, WS_OUTPUT_LIST.WS_CRE_JRN);
        CEP.TRC(SCCGWA, WS_OUTPUT_LIST.WS_TX_TM);
        CEP.TRC(SCCGWA, WS_OUTPUT_LIST.WS_BILL_NO);
        CEP.TRC(SCCGWA, WS_OUTPUT_LIST.WS_CLCT_STS);
        CEP.TRC(SCCGWA, WS_OUTPUT_LIST.WS_BILL_STS);
        CEP.TRC(SCCGWA, WS_OUTPUT_LIST.WS_BILL_CUR);
        CEP.TRC(SCCGWA, WS_OUTPUT_LIST.WS_BILL_AMT);
        CEP.TRC(SCCGWA, WS_OUTPUT_LIST.WS_C_REC_DT);
        CEP.TRC(SCCGWA, WS_OUTPUT_LIST.WS_C_PYE_DT);
        CEP.TRC(SCCGWA, WS_OUTPUT_LIST.WS_C_PYE_AC);
        CEP.TRC(SCCGWA, WS_OUTPUT_LIST.WS_C_PYE_NM);
        CEP.TRC(SCCGWA, WS_OUTPUT_LIST.WS_C_PYE_BR);
        CEP.TRC(SCCGWA, WS_OUTPUT_LIST.WS_C_PYE_BN);
        CEP.TRC(SCCGWA, WS_OUTPUT_LIST.WS_DRWR_AC);
        CEP.TRC(SCCGWA, WS_OUTPUT_LIST.WS_DRWR_NM);
        CEP.TRC(SCCGWA, WS_OUTPUT_LIST.WS_DRWR_BR);
        CEP.TRC(SCCGWA, WS_OUTPUT_LIST.WS_B_MAT_DT);
        CEP.TRC(SCCGWA, WS_OUTPUT_LIST.WS_PAY_DT);
        CEP.TRC(SCCGWA, WS_OUTPUT_LIST.WS_RTN_DT);
        CEP.TRC(SCCGWA, WS_OUTPUT_LIST.WS_RTN_RSN);
        CEP.TRC(SCCGWA, WS_OUTPUT_LIST.WS_PAY_MTH);
        CEP.TRC(SCCGWA, WS_OUTPUT_LIST.WS_PAY_CHNL);
        CEP.TRC(SCCGWA, WS_OUTPUT_LIST.WS_SPPM_FLG);
        CEP.TRC(SCCGWA, WS_OUTPUT_LIST.WS_REMK);
        IBS.init(SCCGWA, SCCFMT);
        SCCFMT.FMTID = K_OUTPUT_FMT;
        SCCFMT.DATA_PTR = WS_OUTPUT_LIST;
        SCCFMT.DATA_LEN = 1299;
        IBS.FMT(SCCGWA, SCCFMT);
    }
    public void S000_CALL_BAZUICLC() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BA-U-INQ-CLCT", BACUICLC);
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.MSG_PROC_AREA.MSG_TYPE);
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
