package com.hisun.BA;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;

import java.io.IOException;
import java.sql.SQLException;

public class BAOT3010 {
    String K_OUTPUT_FMT = "BAI01";
    String WS_ERR_MSG = " ";
    short WS_FLD_NO = 0;
    BAOT3010_WS_OUT_DATA WS_OUT_DATA = new BAOT3010_WS_OUT_DATA();
    BACMSG_ERROR_MSG BACMSG_ERROR_MSG = new BACMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    SCCFMT SCCFMT = new SCCFMT();
    BACUBINF BACUBINF = new BACUBINF();
    SCCGWA SCCGWA;
    BAB3010_AWA_3010 BAB3010_AWA_3010;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    SCCGAPV SCCGAPV;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "BAOT3010 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "BAB3010_AWA_3010>");
        BAB3010_AWA_3010 = (BAB3010_AWA_3010) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        SCCGAPV = (SCCGAPV) GWA_SC_AREA.APVL_AREA_PTR;
        CEP.TRC(SCCGWA, BAB3010_AWA_3010.BILL_NO);
        CEP.TRC(SCCGWA, BAB3010_AWA_3010.CNTR_NO);
        CEP.TRC(SCCGWA, BAB3010_AWA_3010.ACCT_CNT);
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B010_CHECK_INPUT_DATA();
        B020_TRANCHE_MAIN_PROC();
        B030_OUTPUT_PROC();
    }
    public void B010_CHECK_INPUT_DATA() throws IOException,SQLException,Exception {
        if (BAB3010_AWA_3010.BILL_NO.trim().length() == 0) {
            if (BAB3010_AWA_3010.CNTR_NO.trim().length() == 0 
                || BAB3010_AWA_3010.ACCT_CNT == 0) {
                CEP.TRC(SCCGWA, "1111111111111");
                WS_ERR_MSG = BACMSG_ERROR_MSG.BA_BIL_CNTR_ACCT_ALL_SP;
                S000_ERR_MSG_CONTINUE();
            }
        }
        if (BAB3010_AWA_3010.CNTR_NO.trim().length() == 0 
            && BAB3010_AWA_3010.ACCT_CNT == 0) {
            CEP.TRC(SCCGWA, "2222222222222");
            if (BAB3010_AWA_3010.BILL_NO.trim().length() == 0) {
                WS_ERR_MSG = BACMSG_ERROR_MSG.BA_CR_AT_NULL_BI_M_P;
                S000_ERR_MSG_CONTINUE();
            }
        }
        S000_ERR_MSG_LAST();
    }
    public void B020_TRANCHE_MAIN_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BACUBINF);
        BACUBINF.COMM_DATA.BILL_NO = BAB3010_AWA_3010.BILL_NO;
        BACUBINF.COMM_DATA.CNTR_NO = BAB3010_AWA_3010.CNTR_NO;
        BACUBINF.COMM_DATA.ACCT_CNT = BAB3010_AWA_3010.ACCT_CNT;
        CEP.TRC(SCCGWA, BACUBINF.COMM_DATA.BILL_NO);
        CEP.TRC(SCCGWA, BACUBINF.COMM_DATA.CNTR_NO);
        CEP.TRC(SCCGWA, BACUBINF.COMM_DATA.ACCT_CNT);
        S000_CALL_BAZUBINF();
        if (BACUBINF.RC.RC_CODE != 0) {
            WS_ERR_MSG = IBS.CLS2CPY(SCCGWA, BACUBINF.RC);
            S000_ERR_MSG_PROC();
        }
    }
    public void B030_OUTPUT_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, WS_OUT_DATA);
        CEP.TRC(SCCGWA, "1111111");
        WS_OUT_DATA.WS_BILL_NO = BACUBINF.COMM_DATA.BILL_NO;
        WS_OUT_DATA.WS_BILL_TYP = BACUBINF.COMM_DATA.BILL_TYP;
        WS_OUT_DATA.WS_CNTR_NO = BACUBINF.COMM_DATA.CNTR_NO;
        WS_OUT_DATA.WS_ACCT_CNT = BACUBINF.COMM_DATA.ACCT_CNT;
        WS_OUT_DATA.WS_PROD_CD = BACUBINF.COMM_DATA.PROD_CD;
        WS_OUT_DATA.WS_CTA_NO = BACUBINF.COMM_DATA.CTA_NO;
        WS_OUT_DATA.WS_SUSP_NO = BACUBINF.COMM_DATA.SUSP_NO;
        WS_OUT_DATA.WS_BILL_STS = BACUBINF.COMM_DATA.BILL_STS;
        WS_OUT_DATA.WS_AMT_STS = BACUBINF.COMM_DATA.AMT_STS;
        WS_OUT_DATA.WS_PLDG_STS = BACUBINF.COMM_DATA.PLDG_STS;
        WS_OUT_DATA.WS_BLK_STS = BACUBINF.COMM_DATA.BLK_STS;
        WS_OUT_DATA.WS_WO_PAY_FLG = BACUBINF.COMM_DATA.WO_PAY_FLG;
        WS_OUT_DATA.WS_CHG_DRW_FLG = BACUBINF.COMM_DATA.CHG_DRW_FLG;
        WS_OUT_DATA.WS_GL_T_FLG = BACUBINF.COMM_DATA.GL_T_FLG;
        WS_OUT_DATA.WS_ORG_B_NO = BACUBINF.COMM_DATA.O_BILL_NO;
        WS_OUT_DATA.WS_DRW_DT = BACUBINF.COMM_DATA.DRW_DT;
        WS_OUT_DATA.WS_ACPT_BR = BACUBINF.COMM_DATA.ACPT_BR;
        WS_OUT_DATA.WS_A_BK_CD = BACUBINF.COMM_DATA.A_BK_CD;
        WS_OUT_DATA.WS_ACPT_DT = BACUBINF.COMM_DATA.ACPT_DT;
        WS_OUT_DATA.WS_A_REF_NO = BACUBINF.COMM_DATA.A_REF_NO;
        WS_OUT_DATA.WS_B_MAT_DT = BACUBINF.COMM_DATA.B_MAT_DT;
        WS_OUT_DATA.WS_DY_BR = BACUBINF.COMM_DATA.PRT_BR;
        WS_OUT_DATA.WS_BILL_CUR = BACUBINF.COMM_DATA.BILL_CUR;
        WS_OUT_DATA.WS_BILL_AMT = BACUBINF.COMM_DATA.BILL_AMT;
        WS_OUT_DATA.WS_CI_NO = BACUBINF.COMM_DATA.CI_NO;
        WS_OUT_DATA.WS_DRWR_AC = BACUBINF.COMM_DATA.DRWR_AC;
        WS_OUT_DATA.WS_DRWR_NM = BACUBINF.COMM_DATA.DRWR_NM;
        WS_OUT_DATA.WS_PYE_AC = BACUBINF.COMM_DATA.PYE_AC;
        WS_OUT_DATA.WS_PYE_NM = BACUBINF.COMM_DATA.PYE_NM;
        WS_OUT_DATA.WS_P_BK_CD = BACUBINF.COMM_DATA.P_BK_CD;
        WS_OUT_DATA.WS_P_BK_NM = BACUBINF.COMM_DATA.P_BK_NM;
        WS_OUT_DATA.WS_DBT_SEQ = BACUBINF.COMM_DATA.DBT_SEQ;
        WS_OUT_DATA.WS_G_CCY = BACUBINF.COMM_DATA.G_CCY;
        WS_OUT_DATA.WS_G_L_AMT = BACUBINF.COMM_DATA.G_L_AMT;
        WS_OUT_DATA.WS_PAY_DT = BACUBINF.COMM_DATA.PAY_DT;
        WS_OUT_DATA.WS_RTN_DT = BACUBINF.COMM_DATA.RTN_DT;
        WS_OUT_DATA.WS_SETL_MTH = BACUBINF.COMM_DATA.SETL_MTH;
        WS_OUT_DATA.WS_PAY_MTH = BACUBINF.COMM_DATA.PAY_MTH;
        WS_OUT_DATA.WS_PAY_CHNL = BACUBINF.COMM_DATA.PAY_CHNL;
        WS_OUT_DATA.WS_REM_AMT = BACUBINF.COMM_DATA.REM_AMT;
        WS_OUT_DATA.WS_OVD_RAT = BACUBINF.COMM_DATA.OVD_RAT;
        WS_OUT_DATA.WS_TRADE_FLG = BACUBINF.COMM_DATA.TRADE_FLG;
        WS_OUT_DATA.WS_TRADE_AC = BACUBINF.COMM_DATA.TRADE_AC;
        WS_OUT_DATA.WS_REMK = BACUBINF.COMM_DATA.REMK;
        WS_OUT_DATA.WS_BK_STS = BACUBINF.COMM_DATA.BK_STS;
        WS_OUT_DATA.WS_BK_X50 = BACUBINF.COMM_DATA.BK_X50;
        WS_OUT_DATA.WS_HAND_AMT = BACUBINF.COMM_DATA.HAND_AMT;
        WS_OUT_DATA.WS_PROD_AMT = BACUBINF.COMM_DATA.PROD_AMT;
        WS_OUT_DATA.WS_LOSS_FLG = BACUBINF.COMM_DATA.LOSS_FLG;
        WS_OUT_DATA.WS_CLCT_FLG = BACUBINF.COMM_DATA.CLCT_FLG;
        WS_OUT_DATA.WS_ACPT_BR_NM = BACUBINF.COMM_DATA.ACPT_BR_NM;
        WS_OUT_DATA.WS_B_REF_NO = BACUBINF.COMM_DATA.B_REF_NO;
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_B_REF_NO);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_ACPT_BR_NM);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_BILL_NO);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_BILL_TYP);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_CNTR_NO);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_ACCT_CNT);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_PROD_CD);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_CTA_NO);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_SUSP_NO);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_BILL_STS);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_AMT_STS);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_PLDG_STS);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_BLK_STS);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_WO_PAY_FLG);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_CHG_DRW_FLG);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_GL_T_FLG);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_ORG_B_NO);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_DRW_DT);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_ACPT_BR);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_A_BK_CD);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_ACPT_DT);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_A_REF_NO);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_B_MAT_DT);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_DY_BR);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_BILL_CUR);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_BILL_AMT);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_CI_NO);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_DRWR_AC);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_DRWR_NM);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_PYE_AC);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_PYE_NM);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_P_BK_CD);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_P_BK_NM);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_DBT_SEQ);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_G_CCY);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_PAY_DT);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_RTN_DT);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_SETL_MTH);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_PAY_MTH);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_PAY_CHNL);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_REM_AMT);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_OVD_RAT);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_TRADE_FLG);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_TRADE_AC);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_REMK);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_BK_STS);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_BK_X50);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_PROD_AMT);
        CEP.TRC(SCCGWA, WS_OUT_DATA.WS_CLCT_FLG);
        IBS.init(SCCGWA, SCCFMT);
        SCCFMT.FMTID = K_OUTPUT_FMT;
        SCCFMT.DATA_PTR = WS_OUT_DATA;
        SCCFMT.DATA_LEN = 1537;
        IBS.FMT(SCCGWA, SCCFMT);
    }
    public void S000_CALL_BAZUBINF() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "BA-U-INQ-BILL-INF", BACUBINF);
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG);
    }
    public void S000_ERR_MSG_CONTINUE() throws IOException,SQLException,Exception {
        CEP.ERRC(SCCGWA, WS_ERR_MSG);
    }
    public void S000_ERR_MSG_LAST() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
        CEP.TRC(SCCGWA, SCCGWA.COMM_AREA.MSG_PROC_AREA.MSG_TYPE);
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
