package com.hisun.BA;

import com.hisun.SM.*;
import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;

import java.io.IOException;
import java.sql.SQLException;

public class BAOT1010 {
    String JIBS_tmp_str[] = new String[10];
    char K_ERROR = 'E';
    BAOT1010_WS_TEMP_VARIABLE WS_TEMP_VARIABLE = new BAOT1010_WS_TEMP_VARIABLE();
    SMCMSG_ERROR_MSG SMCMSG_ERROR_MSG = new SMCMSG_ERROR_MSG();
    SCCWOUT SCCWOUT = new SCCWOUT();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    SCCMPAG SCCMPAG = new SCCMPAG();
    SCCFMT SCCFMT = new SCCFMT();
    BACUPROD BACUPROD = new BACUPROD();
    BACXP01 BACXP01 = new BACXP01();
    SCCGWA SCCGWA;
    BAB1010_AWA_1010 BAB1010_AWA_1010;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A00_INIT_PROCESS();
        B000_MAIN_PROCESS();
        CEP.TRC(SCCGWA, "BAOT1010 return!");
        Z_RET();
    }
    public void A00_INIT_PROCESS() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "BAB1010_AWA_1010>");
        BAB1010_AWA_1010 = (BAB1010_AWA_1010) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        IBS.init(SCCGWA, WS_TEMP_VARIABLE);
    }
    public void B000_MAIN_PROCESS() throws IOException,SQLException,Exception {
        B100_CHECK_INPUT();
        B200_CALL_BAZUPROD();
        B300_OUTPUT_PROCESS();
    }
    public void B100_CHECK_INPUT() throws IOException,SQLException,Exception {
        if (BAB1010_AWA_1010.FUNC != 'I' 
            && BAB1010_AWA_1010.FUNC != 'A' 
            && BAB1010_AWA_1010.FUNC != 'M' 
            && BAB1010_AWA_1010.FUNC != 'D') {
            IBS.CPY2CLS(SCCGWA, SMCMSG_ERROR_MSG.SM_INPUT_ERROR, WS_TEMP_VARIABLE.WS_MSGID);
            IBS.CPY2CLS(SCCGWA, SMCMSG_ERROR_MSG.SM_INPUT_ERROR, BACUPROD.RC);
            WS_TEMP_VARIABLE.WS_FLD_NO = BAB1010_AWA_1010.FUNC_NO;
            S000_ERR_MSG_PROC();
        }
    }
    public void B200_CALL_BAZUPROD() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BACUPROD);
        CEP.TRC(SCCGWA, BAB1010_AWA_1010.PTYP);
        CEP.TRC(SCCGWA, BAB1010_AWA_1010.CODE);
        CEP.TRC(SCCGWA, BAB1010_AWA_1010.FUNC);
        CEP.TRC(SCCGWA, BAB1010_AWA_1010.PTYP);
        CEP.TRC(SCCGWA, BAB1010_AWA_1010.CODE);
        CEP.TRC(SCCGWA, BAB1010_AWA_1010.EFFDATE);
        CEP.TRC(SCCGWA, BAB1010_AWA_1010.EXPDATE);
        CEP.TRC(SCCGWA, BAB1010_AWA_1010.DESC);
        CEP.TRC(SCCGWA, BAB1010_AWA_1010.CDESC);
        CEP.TRC(SCCGWA, BAB1010_AWA_1010.PRODMO);
        CEP.TRC(SCCGWA, BAB1010_AWA_1010.BILL_FLG);
        CEP.TRC(SCCGWA, BAB1010_AWA_1010.AGTIB_FL);
        CEP.TRC(SCCGWA, BAB1010_AWA_1010.DLY_CODE);
        CEP.TRC(SCCGWA, BAB1010_AWA_1010.INFO_DAY);
        CEP.TRC(SCCGWA, BAB1010_AWA_1010.OVD_RAT);
        BACUPROD.FUNC = BAB1010_AWA_1010.FUNC;
        BACUPROD.KEY.TYPE = BAB1010_AWA_1010.PTYP;
        BACUPROD.KEY.CODE = BAB1010_AWA_1010.CODE;
        BACUPROD.EFF_DATE = BAB1010_AWA_1010.EFFDATE;
        BACUPROD.EXP_DATE = BAB1010_AWA_1010.EXPDATE;
        BACUPROD.DESC = BAB1010_AWA_1010.DESC;
        BACUPROD.CDESC = BAB1010_AWA_1010.CDESC;
        BACUPROD.DATA_TXT.PRODMO = BAB1010_AWA_1010.PRODMO;
        BACUPROD.DATA_TXT.BILL_FLG = BAB1010_AWA_1010.BILL_FLG;
        BACUPROD.DATA_TXT.AGTIB_FLG = BAB1010_AWA_1010.AGTIB_FL;
        BACUPROD.DATA_TXT.DLY_CODE = BAB1010_AWA_1010.DLY_CODE;
        BACUPROD.DATA_TXT.INFO_DAY = BAB1010_AWA_1010.INFO_DAY;
        BACUPROD.DATA_TXT.OVD_RAT = BAB1010_AWA_1010.OVD_RAT;
        BACUPROD.DATA_LEN = 31;
        CEP.TRC(SCCGWA, BACUPROD.KEY.TYPE);
        CEP.TRC(SCCGWA, BACUPROD.KEY.CODE);
        S000_CALL_BAZUPROD();
    }
    public void B300_OUTPUT_PROCESS() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, BACXP01);
        IBS.init(SCCGWA, SCCFMT);
        CEP.TRC(SCCGWA, BACUPROD.FUNC);
        CEP.TRC(SCCGWA, BACUPROD.KEY.CODE);
        BACXP01.FUNC = BACUPROD.FUNC;
        BACXP01.TYPE = BACUPROD.KEY.TYPE;
        BACXP01.CODE = BACUPROD.KEY.CODE;
        BACXP01.DESC = BACUPROD.DESC;
        BACXP01.CDESC = BACUPROD.CDESC;
        BACXP01.FLAG = 0X02;
        BACXP01.EFF_DATE = BACUPROD.EFF_DATE;
        BACXP01.EXP_DATE = BACUPROD.EXP_DATE;
        BACXP01.PRODMO = BACUPROD.DATA_TXT.PRODMO;
        BACXP01.BILL_FLG = BACUPROD.DATA_TXT.BILL_FLG;
        BACXP01.AGTIB_FLG = BACUPROD.DATA_TXT.AGTIB_FLG;
        BACXP01.DLY_CODE = BACUPROD.DATA_TXT.DLY_CODE;
        BACXP01.INFO_DAY = BACUPROD.DATA_TXT.INFO_DAY;
        CEP.TRC(SCCGWA, BACUPROD.DATA_TXT.OVD_RAT);
        BACXP01.OVD_RAT = BACUPROD.DATA_TXT.OVD_RAT;
        CEP.TRC(SCCGWA, BACXP01.FUNC);
        CEP.TRC(SCCGWA, BACXP01.TYPE);
        CEP.TRC(SCCGWA, BACXP01.CODE);
        CEP.TRC(SCCGWA, BACXP01.DESC);
        CEP.TRC(SCCGWA, BACXP01.CDESC);
        CEP.TRC(SCCGWA, BACXP01.EFF_DATE);
        CEP.TRC(SCCGWA, BACXP01.EXP_DATE);
        CEP.TRC(SCCGWA, BACXP01.PRODMO);
        CEP.TRC(SCCGWA, BACXP01.BILL_FLG);
        CEP.TRC(SCCGWA, BACXP01.AGTIB_FLG);
        CEP.TRC(SCCGWA, BACXP01.DLY_CODE);
        CEP.TRC(SCCGWA, BACXP01.INFO_DAY);
        CEP.TRC(SCCGWA, BACXP01.OVD_RAT);
        SCCFMT.FMTID = "BAP01";
        SCCFMT.DATA_PTR = BACXP01;
        SCCFMT.DATA_LEN = 174;
        IBS.FMT(SCCGWA, SCCFMT);
    }
    public void R00_CHECK_ERROR() throws IOException,SQLException,Exception {
        if (SCCGWA.COMM_AREA.MSG_PROC_AREA.MSG_TYPE == K_ERROR 
            && SCCGWA.COMM_AREA.MSG_PROC_AREA.MSG_ID.MSG_CODE == 0) {
            IBS.CPY2CLS(SCCGWA, SMCMSG_ERROR_MSG.SM_INPUT_ERROR, WS_TEMP_VARIABLE.WS_MSGID);
            WS_TEMP_VARIABLE.WS_FLD_NO = 0;
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_CALL_BAZUPROD() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, BACUPROD);
        IBS.CALLCPN(SCCGWA, "BA-U-PROD-MAINTAIN", BACUPROD);
        CEP.TRC(SCCGWA, BACUPROD);
        if (BACUPROD.RC.RC_RTNCODE != 0) {
            WS_TEMP_VARIABLE.WS_MSGID.WS_MSG_AP = BACUPROD.RC.RC_APP;
            WS_TEMP_VARIABLE.WS_MSGID.WS_MSG_CODE = BACUPROD.RC.RC_RTNCODE;
            S000_ERR_MSG_PROC();
        }
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, WS_TEMP_VARIABLE.WS_MSGID);
        CEP.ERR(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_FLD_NO);
    }
    public void S000_ERR_MSG_PROC_CONTINUE() throws IOException,SQLException,Exception {
        JIBS_tmp_str[0] = IBS.CLS2CPY(SCCGWA, WS_TEMP_VARIABLE.WS_MSGID);
        CEP.ERRC(SCCGWA, JIBS_tmp_str[0], WS_TEMP_VARIABLE.WS_FLD_NO);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
