package com.hisun.GD;

public class GDB5200_AWA_5200 {
    public String RSEQ = " ";
    public short RSEQ_NO = 0;
    public String DD_AC = " ";
    public short DD_AC_NO = 0;
    public char AC_TYP = ' ';
    public short AC_TYP_NO = 0;
    public String CI_NM = " ";
    public short CI_NM_NO = 0;
    public int SEQ = 0;
    public short SEQ_NO = 0;
    public String CCY = " ";
    public short CCY_NO = 0;
    public char CCY_TYP = ' ';
    public short CCY_TYP_NO = 0;
    public String CTA_NO = " ";
    public short CTA_NO_NO = 0;
    public String REF_NO = " ";
    public short REF_NO_NO = 0;
    public String RMK = " ";
    public short RMK_NO = 0;
    public String CI_NO = " ";
    public short CI_NO_NO = 0;
    public String OTCI_NM = " ";
    public short OTCI_NM_NO = 0;
    public String PROD_CD = " ";
    public short PROD_CD_NO = 0;
    public double BAL = 0;
    public short BAL_NO = 0;
    public double AMT1 = 0;
    public short AMT1_NO = 0;
    public double AMT2 = 0;
    public short AMT2_NO = 0;
    public double AMT3 = 0;
    public short AMT3_NO = 0;
    public double AMT4 = 0;
    public short AMT4_NO = 0;
    public char BUR_MTH = ' ';
    public short BUR_MTH_NO = 0;
    public String SYS_NO = " ";
    public short SYS_NO_NO = 0;
    public String TXHLD_NO = " ";
    public short TXHLD_NO_NO = 0;
}
