package com.hisun.GD;

public class GDCSMPIN_VAL {
    public String CI_NO = " ";
    public String CI_NM = " ";
    public char FILLER4 = 0X02;
    public String DD_AC1 = " ";
    public String DR_CARD1 = " ";
    public String CI_NM1 = " ";
    public char FILLER8 = 0X02;
    public String PROD_CD = " ";
    public String CCY = " ";
    public char CCY_TYP = ' ';
    public double AMT = 0;
    public char STL_MTH = ' ';
    public String REV_NO = " ";
    public String DD_AC2 = " ";
    public String DR_CARD2 = " ";
    public String CI_NM2 = " ";
    public char FILLER18 = 0X02;
    public String CHQ_NO = " ";
    public char PN_TYP = ' ';
    public int ISSUE_DT = 0;
    public String PAY_AC = " ";
    public String BRANCH = " ";
    public String PAY_CI_NM = " ";
    public char FILLER25 = 0X02;
    public char RL_FLG = ' ';
    public String CTA_NO = " ";
    public String REF_NO = " ";
    public String BSTYP = " ";
    public double RL_AMT = 0;
    public int EXP_DT = 0;
    public String RL_SEQ = " ";
    public String TXPSW = " ";
    public String TXPSW2 = " ";
    public short SEQ = 0;
    public String RMK = " ";
    public String MMO = " ";
}
