package com.hisun.GD;

import com.hisun.DD.*;
import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;
import com.hisun.BP.*;

import java.io.IOException;
import java.sql.SQLException;

public class GDOT1109 {
    short WS_FLD_NO = 0;
    String WS_ERR_MSG = " ";
    char WS_HIS_FLG = ' ';
    DDCMSG_ERROR_MSG DDCMSG_ERROR_MSG = new DDCMSG_ERROR_MSG();
    GDCMSG_ERROR_MSG GDCMSG_ERROR_MSG = new GDCMSG_ERROR_MSG();
    SCCMSG SCCMSG = new SCCMSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    GDCSMPIN GDCSMPIN = new GDCSMPIN();
    GDRHIS GDRHIS = new GDRHIS();
    SCCGWA SCCGWA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    BPCPQBNK_DATA_INFO BPCRBANK;
    GDB1100_AWA_1100 GDB1100_AWA_1100;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROCESS();
        B000_MAIN_PROCESS();
        CEP.TRC(SCCGWA, "GDOT1109 return!");
        Z_RET();
    }
    public void A000_INIT_PROCESS() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "GDB1100_AWA_1100>");
        GDB1100_AWA_1100 = (GDB1100_AWA_1100) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        BPCRBANK = (BPCPQBNK_DATA_INFO) SCCGWA.COMM_AREA.BANK_AREA_PTR;
    }
    public void B000_MAIN_PROCESS() throws IOException,SQLException,Exception {
        B100_CHECK_INPUT_DATA();
    }
    public void B100_CHECK_INPUT_DATA() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, GDB1100_AWA_1100);
        B200_REVERSL_PROC();
    }
    public void B200_REVERSL_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, GDCSMPIN);
        GDCSMPIN.VAL.DD_AC1 = GDB1100_AWA_1100.TXDD_AC1;
        GDCSMPIN.VAL.CI_NM1 = GDB1100_AWA_1100.TXCI_NM1;
        GDCSMPIN.VAL.CCY = GDB1100_AWA_1100.TXCCY;
        GDCSMPIN.VAL.CCY_TYP = GDB1100_AWA_1100.TXCTYP;
        GDCSMPIN.VAL.AMT = GDB1100_AWA_1100.TXAMT;
        GDCSMPIN.VAL.STL_MTH = GDB1100_AWA_1100.STL_MTH;
        GDCSMPIN.VAL.REV_NO = GDB1100_AWA_1100.TXREV_NO;
        GDCSMPIN.VAL.DD_AC2 = GDB1100_AWA_1100.TXDD_AC2;
        GDCSMPIN.VAL.DR_CARD2 = GDB1100_AWA_1100.DR_CARD;
        GDCSMPIN.VAL.CI_NM2 = GDB1100_AWA_1100.TXCI_NM2;
        GDCSMPIN.VAL.PN_TYP = GDB1100_AWA_1100.PN_TYP;
        GDCSMPIN.VAL.CHQ_NO = GDB1100_AWA_1100.CHQ_NO;
        GDCSMPIN.VAL.ISSUE_DT = GDB1100_AWA_1100.TXDT;
        GDCSMPIN.VAL.PAY_AC = GDB1100_AWA_1100.TXAC;
        GDCSMPIN.VAL.BRANCH = GDB1100_AWA_1100.TXBK;
        GDCSMPIN.VAL.PAY_CI_NM = GDB1100_AWA_1100.TXCI_NM3;
        GDCSMPIN.VAL.RL_FLG = GDB1100_AWA_1100.TXRFLG;
        GDCSMPIN.VAL.CTA_NO = GDB1100_AWA_1100.TXCTA_NO;
        GDCSMPIN.VAL.REF_NO = GDB1100_AWA_1100.TXREF_NO;
        GDCSMPIN.VAL.BSTYP = GDB1100_AWA_1100.TXBSTYP;
        GDCSMPIN.VAL.RL_AMT = GDB1100_AWA_1100.TXRAMT;
        GDCSMPIN.VAL.EXP_DT = GDB1100_AWA_1100.TXEXPDT;
        GDCSMPIN.VAL.RL_SEQ = GDB1100_AWA_1100.TXRSEQ;
        GDCSMPIN.VAL.RMK = GDB1100_AWA_1100.TXRMK;
        GDCSMPIN.VAL.MMO = GDB1100_AWA_1100.TXMMO;
        GDCSMPIN.VAL.TXPSW = GDB1100_AWA_1100.TXPSW;
        GDCSMPIN.VAL.TXPSW2 = GDB1100_AWA_1100.TXPSW2;
        CEP.TRC(SCCGWA, GDB1100_AWA_1100.TXDD_AC1);
        CEP.TRC(SCCGWA, GDCSMPIN.VAL.DD_AC1);
        S000_CALL_GDZSMPIN();
    }
    public void S000_CALL_GDZSMPIN() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "GD-SVR-GDZSMPIN", GDCSMPIN);
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
