package com.hisun.ibscore.app.bp.domain;

import java.io.Serializable;
import java.util.Date;

public class UserG implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.TLR
     *
     * @mbggenerated
     */
    private String tlr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.TLR_BR
     *
     * @mbggenerated
     */
    private Integer tlrBr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.TLR_TKS
     *
     * @mbggenerated
     */
    private Short tlrTks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.STAF_NO
     *
     * @mbggenerated
     */
    private String stafNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.CI_NO
     *
     * @mbggenerated
     */
    private String ciNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.ID_TYP
     *
     * @mbggenerated
     */
    private String idTyp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.ID_NO
     *
     * @mbggenerated
     */
    private String idNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.TLR_CN_NM
     *
     * @mbggenerated
     */
    private String tlrCnNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.TLR_EN_NM
     *
     * @mbggenerated
     */
    private String tlrEnNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.EFF_DT
     *
     * @mbggenerated
     */
    private Integer effDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.EXP_DT
     *
     * @mbggenerated
     */
    private Integer expDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.UPD_DT
     *
     * @mbggenerated
     */
    private Integer updDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.UPD_TLR
     *
     * @mbggenerated
     */
    private String updTlr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.TLR_TYP
     *
     * @mbggenerated
     */
    private String tlrTyp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.TLR_LVL
     *
     * @mbggenerated
     */
    private String tlrLvl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.TX_LVL
     *
     * @mbggenerated
     */
    private String txLvl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.ATH_LVL
     *
     * @mbggenerated
     */
    private String athLvl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.ATH_GRN
     *
     * @mbggenerated
     */
    private String athGrn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.TMP_TX_LVL
     *
     * @mbggenerated
     */
    private String tmpTxLvl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.TMP_ATH_LVL
     *
     * @mbggenerated
     */
    private String tmpAthLvl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.TX_MODE
     *
     * @mbggenerated
     */
    private String txMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.SIGN_STS
     *
     * @mbggenerated
     */
    private String signSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.TLR_STS
     *
     * @mbggenerated
     */
    private String tlrSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.REG_TYP
     *
     * @mbggenerated
     */
    private String regTyp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.SIGN_DT
     *
     * @mbggenerated
     */
    private Integer signDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.CRO_BR_SIGN
     *
     * @mbggenerated
     */
    private String croBrSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.IGN_TIMES
     *
     * @mbggenerated
     */
    private Integer ignTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.PSW_RETRY
     *
     * @mbggenerated
     */
    private Integer pswRetry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.TRM_TYP
     *
     * @mbggenerated
     */
    private String trmTyp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.SIGN_TRM
     *
     * @mbggenerated
     */
    private String signTrm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.PRT_IP
     *
     * @mbggenerated
     */
    private String prtIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.TLR_STSW
     *
     * @mbggenerated
     */
    private String tlrStsw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.LAST_JRN
     *
     * @mbggenerated
     */
    private Long lastJrn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.ACC_VCH_NO
     *
     * @mbggenerated
     */
    private String accVchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.TLR_CRD_NO
     *
     * @mbggenerated
     */
    private String tlrCrdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.CRD_PSW_DT
     *
     * @mbggenerated
     */
    private Integer crdPswDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.KB_PSW_DT
     *
     * @mbggenerated
     */
    private Integer kbPswDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.TELE
     *
     * @mbggenerated
     */
    private String tele;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.PST_ADDRESS
     *
     * @mbggenerated
     */
    private String pstAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.SIGN_TRM_FLG
     *
     * @mbggenerated
     */
    private String signTrmFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.TRM_INFO
     *
     * @mbggenerated
     */
    private String trmInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.PSW_TYP
     *
     * @mbggenerated
     */
    private String pswTyp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.IDEN_DEV_ID
     *
     * @mbggenerated
     */
    private String idenDevId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.NEW_BR
     *
     * @mbggenerated
     */
    private Integer newBr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.NEW_BR_EFF
     *
     * @mbggenerated
     */
    private Integer newBrEff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.TM_OUT_LMT
     *
     * @mbggenerated
     */
    private Integer tmOutLmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.ACC_SEN_CUS
     *
     * @mbggenerated
     */
    private String accSenCus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.ACC_SEN_GL
     *
     * @mbggenerated
     */
    private String accSenGl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.SUPER_FLG
     *
     * @mbggenerated
     */
    private String superFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.PRT_NAME1
     *
     * @mbggenerated
     */
    private String prtName1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.PRT_NAME2
     *
     * @mbggenerated
     */
    private String prtName2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.PRT_NAME3
     *
     * @mbggenerated
     */
    private String prtName3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.TS
     *
     * @mbggenerated
     */
    private Date ts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.TLR_CRD_PSW
     *
     * @mbggenerated
     */
    private byte[] tlrCrdPsw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.KB_PSW
     *
     * @mbggenerated
     */
    private byte[] kbPsw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BPTTLT.LAST_KB_PSW
     *
     * @mbggenerated
     */
    private byte[] lastKbPsw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BPTTLT
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.TLR
     *
     * @return the value of BPTTLT.TLR
     *
     * @mbggenerated
     */
    public String getTlr() {
        return tlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.TLR
     *
     * @param tlr the value for BPTTLT.TLR
     *
     * @mbggenerated
     */
    public void setTlr(String tlr) {
        this.tlr = tlr == null ? null : tlr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.TLR_BR
     *
     * @return the value of BPTTLT.TLR_BR
     *
     * @mbggenerated
     */
    public Integer getTlrBr() {
        return tlrBr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.TLR_BR
     *
     * @param tlrBr the value for BPTTLT.TLR_BR
     *
     * @mbggenerated
     */
    public void setTlrBr(Integer tlrBr) {
        this.tlrBr = tlrBr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.TLR_TKS
     *
     * @return the value of BPTTLT.TLR_TKS
     *
     * @mbggenerated
     */
    public Short getTlrTks() {
        return tlrTks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.TLR_TKS
     *
     * @param tlrTks the value for BPTTLT.TLR_TKS
     *
     * @mbggenerated
     */
    public void setTlrTks(Short tlrTks) {
        this.tlrTks = tlrTks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.STAF_NO
     *
     * @return the value of BPTTLT.STAF_NO
     *
     * @mbggenerated
     */
    public String getStafNo() {
        return stafNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.STAF_NO
     *
     * @param stafNo the value for BPTTLT.STAF_NO
     *
     * @mbggenerated
     */
    public void setStafNo(String stafNo) {
        this.stafNo = stafNo == null ? null : stafNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.CI_NO
     *
     * @return the value of BPTTLT.CI_NO
     *
     * @mbggenerated
     */
    public String getCiNo() {
        return ciNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.CI_NO
     *
     * @param ciNo the value for BPTTLT.CI_NO
     *
     * @mbggenerated
     */
    public void setCiNo(String ciNo) {
        this.ciNo = ciNo == null ? null : ciNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.ID_TYP
     *
     * @return the value of BPTTLT.ID_TYP
     *
     * @mbggenerated
     */
    public String getIdTyp() {
        return idTyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.ID_TYP
     *
     * @param idTyp the value for BPTTLT.ID_TYP
     *
     * @mbggenerated
     */
    public void setIdTyp(String idTyp) {
        this.idTyp = idTyp == null ? null : idTyp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.ID_NO
     *
     * @return the value of BPTTLT.ID_NO
     *
     * @mbggenerated
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.ID_NO
     *
     * @param idNo the value for BPTTLT.ID_NO
     *
     * @mbggenerated
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.TLR_CN_NM
     *
     * @return the value of BPTTLT.TLR_CN_NM
     *
     * @mbggenerated
     */
    public String getTlrCnNm() {
        return tlrCnNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.TLR_CN_NM
     *
     * @param tlrCnNm the value for BPTTLT.TLR_CN_NM
     *
     * @mbggenerated
     */
    public void setTlrCnNm(String tlrCnNm) {
        this.tlrCnNm = tlrCnNm == null ? null : tlrCnNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.TLR_EN_NM
     *
     * @return the value of BPTTLT.TLR_EN_NM
     *
     * @mbggenerated
     */
    public String getTlrEnNm() {
        return tlrEnNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.TLR_EN_NM
     *
     * @param tlrEnNm the value for BPTTLT.TLR_EN_NM
     *
     * @mbggenerated
     */
    public void setTlrEnNm(String tlrEnNm) {
        this.tlrEnNm = tlrEnNm == null ? null : tlrEnNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.EFF_DT
     *
     * @return the value of BPTTLT.EFF_DT
     *
     * @mbggenerated
     */
    public Integer getEffDt() {
        return effDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.EFF_DT
     *
     * @param effDt the value for BPTTLT.EFF_DT
     *
     * @mbggenerated
     */
    public void setEffDt(Integer effDt) {
        this.effDt = effDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.EXP_DT
     *
     * @return the value of BPTTLT.EXP_DT
     *
     * @mbggenerated
     */
    public Integer getExpDt() {
        return expDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.EXP_DT
     *
     * @param expDt the value for BPTTLT.EXP_DT
     *
     * @mbggenerated
     */
    public void setExpDt(Integer expDt) {
        this.expDt = expDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.UPD_DT
     *
     * @return the value of BPTTLT.UPD_DT
     *
     * @mbggenerated
     */
    public Integer getUpdDt() {
        return updDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.UPD_DT
     *
     * @param updDt the value for BPTTLT.UPD_DT
     *
     * @mbggenerated
     */
    public void setUpdDt(Integer updDt) {
        this.updDt = updDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.UPD_TLR
     *
     * @return the value of BPTTLT.UPD_TLR
     *
     * @mbggenerated
     */
    public String getUpdTlr() {
        return updTlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.UPD_TLR
     *
     * @param updTlr the value for BPTTLT.UPD_TLR
     *
     * @mbggenerated
     */
    public void setUpdTlr(String updTlr) {
        this.updTlr = updTlr == null ? null : updTlr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.TLR_TYP
     *
     * @return the value of BPTTLT.TLR_TYP
     *
     * @mbggenerated
     */
    public String getTlrTyp() {
        return tlrTyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.TLR_TYP
     *
     * @param tlrTyp the value for BPTTLT.TLR_TYP
     *
     * @mbggenerated
     */
    public void setTlrTyp(String tlrTyp) {
        this.tlrTyp = tlrTyp == null ? null : tlrTyp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.TLR_LVL
     *
     * @return the value of BPTTLT.TLR_LVL
     *
     * @mbggenerated
     */
    public String getTlrLvl() {
        return tlrLvl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.TLR_LVL
     *
     * @param tlrLvl the value for BPTTLT.TLR_LVL
     *
     * @mbggenerated
     */
    public void setTlrLvl(String tlrLvl) {
        this.tlrLvl = tlrLvl == null ? null : tlrLvl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.TX_LVL
     *
     * @return the value of BPTTLT.TX_LVL
     *
     * @mbggenerated
     */
    public String getTxLvl() {
        return txLvl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.TX_LVL
     *
     * @param txLvl the value for BPTTLT.TX_LVL
     *
     * @mbggenerated
     */
    public void setTxLvl(String txLvl) {
        this.txLvl = txLvl == null ? null : txLvl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.ATH_LVL
     *
     * @return the value of BPTTLT.ATH_LVL
     *
     * @mbggenerated
     */
    public String getAthLvl() {
        return athLvl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.ATH_LVL
     *
     * @param athLvl the value for BPTTLT.ATH_LVL
     *
     * @mbggenerated
     */
    public void setAthLvl(String athLvl) {
        this.athLvl = athLvl == null ? null : athLvl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.ATH_GRN
     *
     * @return the value of BPTTLT.ATH_GRN
     *
     * @mbggenerated
     */
    public String getAthGrn() {
        return athGrn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.ATH_GRN
     *
     * @param athGrn the value for BPTTLT.ATH_GRN
     *
     * @mbggenerated
     */
    public void setAthGrn(String athGrn) {
        this.athGrn = athGrn == null ? null : athGrn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.TMP_TX_LVL
     *
     * @return the value of BPTTLT.TMP_TX_LVL
     *
     * @mbggenerated
     */
    public String getTmpTxLvl() {
        return tmpTxLvl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.TMP_TX_LVL
     *
     * @param tmpTxLvl the value for BPTTLT.TMP_TX_LVL
     *
     * @mbggenerated
     */
    public void setTmpTxLvl(String tmpTxLvl) {
        this.tmpTxLvl = tmpTxLvl == null ? null : tmpTxLvl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.TMP_ATH_LVL
     *
     * @return the value of BPTTLT.TMP_ATH_LVL
     *
     * @mbggenerated
     */
    public String getTmpAthLvl() {
        return tmpAthLvl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.TMP_ATH_LVL
     *
     * @param tmpAthLvl the value for BPTTLT.TMP_ATH_LVL
     *
     * @mbggenerated
     */
    public void setTmpAthLvl(String tmpAthLvl) {
        this.tmpAthLvl = tmpAthLvl == null ? null : tmpAthLvl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.TX_MODE
     *
     * @return the value of BPTTLT.TX_MODE
     *
     * @mbggenerated
     */
    public String getTxMode() {
        return txMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.TX_MODE
     *
     * @param txMode the value for BPTTLT.TX_MODE
     *
     * @mbggenerated
     */
    public void setTxMode(String txMode) {
        this.txMode = txMode == null ? null : txMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.SIGN_STS
     *
     * @return the value of BPTTLT.SIGN_STS
     *
     * @mbggenerated
     */
    public String getSignSts() {
        return signSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.SIGN_STS
     *
     * @param signSts the value for BPTTLT.SIGN_STS
     *
     * @mbggenerated
     */
    public void setSignSts(String signSts) {
        this.signSts = signSts == null ? null : signSts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.TLR_STS
     *
     * @return the value of BPTTLT.TLR_STS
     *
     * @mbggenerated
     */
    public String getTlrSts() {
        return tlrSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.TLR_STS
     *
     * @param tlrSts the value for BPTTLT.TLR_STS
     *
     * @mbggenerated
     */
    public void setTlrSts(String tlrSts) {
        this.tlrSts = tlrSts == null ? null : tlrSts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.REG_TYP
     *
     * @return the value of BPTTLT.REG_TYP
     *
     * @mbggenerated
     */
    public String getRegTyp() {
        return regTyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.REG_TYP
     *
     * @param regTyp the value for BPTTLT.REG_TYP
     *
     * @mbggenerated
     */
    public void setRegTyp(String regTyp) {
        this.regTyp = regTyp == null ? null : regTyp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.SIGN_DT
     *
     * @return the value of BPTTLT.SIGN_DT
     *
     * @mbggenerated
     */
    public Integer getSignDt() {
        return signDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.SIGN_DT
     *
     * @param signDt the value for BPTTLT.SIGN_DT
     *
     * @mbggenerated
     */
    public void setSignDt(Integer signDt) {
        this.signDt = signDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.CRO_BR_SIGN
     *
     * @return the value of BPTTLT.CRO_BR_SIGN
     *
     * @mbggenerated
     */
    public String getCroBrSign() {
        return croBrSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.CRO_BR_SIGN
     *
     * @param croBrSign the value for BPTTLT.CRO_BR_SIGN
     *
     * @mbggenerated
     */
    public void setCroBrSign(String croBrSign) {
        this.croBrSign = croBrSign == null ? null : croBrSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.IGN_TIMES
     *
     * @return the value of BPTTLT.IGN_TIMES
     *
     * @mbggenerated
     */
    public Integer getIgnTimes() {
        return ignTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.IGN_TIMES
     *
     * @param ignTimes the value for BPTTLT.IGN_TIMES
     *
     * @mbggenerated
     */
    public void setIgnTimes(Integer ignTimes) {
        this.ignTimes = ignTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.PSW_RETRY
     *
     * @return the value of BPTTLT.PSW_RETRY
     *
     * @mbggenerated
     */
    public Integer getPswRetry() {
        return pswRetry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.PSW_RETRY
     *
     * @param pswRetry the value for BPTTLT.PSW_RETRY
     *
     * @mbggenerated
     */
    public void setPswRetry(Integer pswRetry) {
        this.pswRetry = pswRetry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.TRM_TYP
     *
     * @return the value of BPTTLT.TRM_TYP
     *
     * @mbggenerated
     */
    public String getTrmTyp() {
        return trmTyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.TRM_TYP
     *
     * @param trmTyp the value for BPTTLT.TRM_TYP
     *
     * @mbggenerated
     */
    public void setTrmTyp(String trmTyp) {
        this.trmTyp = trmTyp == null ? null : trmTyp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.SIGN_TRM
     *
     * @return the value of BPTTLT.SIGN_TRM
     *
     * @mbggenerated
     */
    public String getSignTrm() {
        return signTrm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.SIGN_TRM
     *
     * @param signTrm the value for BPTTLT.SIGN_TRM
     *
     * @mbggenerated
     */
    public void setSignTrm(String signTrm) {
        this.signTrm = signTrm == null ? null : signTrm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.PRT_IP
     *
     * @return the value of BPTTLT.PRT_IP
     *
     * @mbggenerated
     */
    public String getPrtIp() {
        return prtIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.PRT_IP
     *
     * @param prtIp the value for BPTTLT.PRT_IP
     *
     * @mbggenerated
     */
    public void setPrtIp(String prtIp) {
        this.prtIp = prtIp == null ? null : prtIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.TLR_STSW
     *
     * @return the value of BPTTLT.TLR_STSW
     *
     * @mbggenerated
     */
    public String getTlrStsw() {
        return tlrStsw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.TLR_STSW
     *
     * @param tlrStsw the value for BPTTLT.TLR_STSW
     *
     * @mbggenerated
     */
    public void setTlrStsw(String tlrStsw) {
        this.tlrStsw = tlrStsw == null ? null : tlrStsw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.LAST_JRN
     *
     * @return the value of BPTTLT.LAST_JRN
     *
     * @mbggenerated
     */
    public Long getLastJrn() {
        return lastJrn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.LAST_JRN
     *
     * @param lastJrn the value for BPTTLT.LAST_JRN
     *
     * @mbggenerated
     */
    public void setLastJrn(Long lastJrn) {
        this.lastJrn = lastJrn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.ACC_VCH_NO
     *
     * @return the value of BPTTLT.ACC_VCH_NO
     *
     * @mbggenerated
     */
    public String getAccVchNo() {
        return accVchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.ACC_VCH_NO
     *
     * @param accVchNo the value for BPTTLT.ACC_VCH_NO
     *
     * @mbggenerated
     */
    public void setAccVchNo(String accVchNo) {
        this.accVchNo = accVchNo == null ? null : accVchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.TLR_CRD_NO
     *
     * @return the value of BPTTLT.TLR_CRD_NO
     *
     * @mbggenerated
     */
    public String getTlrCrdNo() {
        return tlrCrdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.TLR_CRD_NO
     *
     * @param tlrCrdNo the value for BPTTLT.TLR_CRD_NO
     *
     * @mbggenerated
     */
    public void setTlrCrdNo(String tlrCrdNo) {
        this.tlrCrdNo = tlrCrdNo == null ? null : tlrCrdNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.CRD_PSW_DT
     *
     * @return the value of BPTTLT.CRD_PSW_DT
     *
     * @mbggenerated
     */
    public Integer getCrdPswDt() {
        return crdPswDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.CRD_PSW_DT
     *
     * @param crdPswDt the value for BPTTLT.CRD_PSW_DT
     *
     * @mbggenerated
     */
    public void setCrdPswDt(Integer crdPswDt) {
        this.crdPswDt = crdPswDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.KB_PSW_DT
     *
     * @return the value of BPTTLT.KB_PSW_DT
     *
     * @mbggenerated
     */
    public Integer getKbPswDt() {
        return kbPswDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.KB_PSW_DT
     *
     * @param kbPswDt the value for BPTTLT.KB_PSW_DT
     *
     * @mbggenerated
     */
    public void setKbPswDt(Integer kbPswDt) {
        this.kbPswDt = kbPswDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.TELE
     *
     * @return the value of BPTTLT.TELE
     *
     * @mbggenerated
     */
    public String getTele() {
        return tele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.TELE
     *
     * @param tele the value for BPTTLT.TELE
     *
     * @mbggenerated
     */
    public void setTele(String tele) {
        this.tele = tele == null ? null : tele.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.PST_ADDRESS
     *
     * @return the value of BPTTLT.PST_ADDRESS
     *
     * @mbggenerated
     */
    public String getPstAddress() {
        return pstAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.PST_ADDRESS
     *
     * @param pstAddress the value for BPTTLT.PST_ADDRESS
     *
     * @mbggenerated
     */
    public void setPstAddress(String pstAddress) {
        this.pstAddress = pstAddress == null ? null : pstAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.SIGN_TRM_FLG
     *
     * @return the value of BPTTLT.SIGN_TRM_FLG
     *
     * @mbggenerated
     */
    public String getSignTrmFlg() {
        return signTrmFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.SIGN_TRM_FLG
     *
     * @param signTrmFlg the value for BPTTLT.SIGN_TRM_FLG
     *
     * @mbggenerated
     */
    public void setSignTrmFlg(String signTrmFlg) {
        this.signTrmFlg = signTrmFlg == null ? null : signTrmFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.TRM_INFO
     *
     * @return the value of BPTTLT.TRM_INFO
     *
     * @mbggenerated
     */
    public String getTrmInfo() {
        return trmInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.TRM_INFO
     *
     * @param trmInfo the value for BPTTLT.TRM_INFO
     *
     * @mbggenerated
     */
    public void setTrmInfo(String trmInfo) {
        this.trmInfo = trmInfo == null ? null : trmInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.PSW_TYP
     *
     * @return the value of BPTTLT.PSW_TYP
     *
     * @mbggenerated
     */
    public String getPswTyp() {
        return pswTyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.PSW_TYP
     *
     * @param pswTyp the value for BPTTLT.PSW_TYP
     *
     * @mbggenerated
     */
    public void setPswTyp(String pswTyp) {
        this.pswTyp = pswTyp == null ? null : pswTyp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.IDEN_DEV_ID
     *
     * @return the value of BPTTLT.IDEN_DEV_ID
     *
     * @mbggenerated
     */
    public String getIdenDevId() {
        return idenDevId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.IDEN_DEV_ID
     *
     * @param idenDevId the value for BPTTLT.IDEN_DEV_ID
     *
     * @mbggenerated
     */
    public void setIdenDevId(String idenDevId) {
        this.idenDevId = idenDevId == null ? null : idenDevId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.NEW_BR
     *
     * @return the value of BPTTLT.NEW_BR
     *
     * @mbggenerated
     */
    public Integer getNewBr() {
        return newBr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.NEW_BR
     *
     * @param newBr the value for BPTTLT.NEW_BR
     *
     * @mbggenerated
     */
    public void setNewBr(Integer newBr) {
        this.newBr = newBr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.NEW_BR_EFF
     *
     * @return the value of BPTTLT.NEW_BR_EFF
     *
     * @mbggenerated
     */
    public Integer getNewBrEff() {
        return newBrEff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.NEW_BR_EFF
     *
     * @param newBrEff the value for BPTTLT.NEW_BR_EFF
     *
     * @mbggenerated
     */
    public void setNewBrEff(Integer newBrEff) {
        this.newBrEff = newBrEff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.TM_OUT_LMT
     *
     * @return the value of BPTTLT.TM_OUT_LMT
     *
     * @mbggenerated
     */
    public Integer getTmOutLmt() {
        return tmOutLmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.TM_OUT_LMT
     *
     * @param tmOutLmt the value for BPTTLT.TM_OUT_LMT
     *
     * @mbggenerated
     */
    public void setTmOutLmt(Integer tmOutLmt) {
        this.tmOutLmt = tmOutLmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.ACC_SEN_CUS
     *
     * @return the value of BPTTLT.ACC_SEN_CUS
     *
     * @mbggenerated
     */
    public String getAccSenCus() {
        return accSenCus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.ACC_SEN_CUS
     *
     * @param accSenCus the value for BPTTLT.ACC_SEN_CUS
     *
     * @mbggenerated
     */
    public void setAccSenCus(String accSenCus) {
        this.accSenCus = accSenCus == null ? null : accSenCus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.ACC_SEN_GL
     *
     * @return the value of BPTTLT.ACC_SEN_GL
     *
     * @mbggenerated
     */
    public String getAccSenGl() {
        return accSenGl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.ACC_SEN_GL
     *
     * @param accSenGl the value for BPTTLT.ACC_SEN_GL
     *
     * @mbggenerated
     */
    public void setAccSenGl(String accSenGl) {
        this.accSenGl = accSenGl == null ? null : accSenGl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.SUPER_FLG
     *
     * @return the value of BPTTLT.SUPER_FLG
     *
     * @mbggenerated
     */
    public String getSuperFlg() {
        return superFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.SUPER_FLG
     *
     * @param superFlg the value for BPTTLT.SUPER_FLG
     *
     * @mbggenerated
     */
    public void setSuperFlg(String superFlg) {
        this.superFlg = superFlg == null ? null : superFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.PRT_NAME1
     *
     * @return the value of BPTTLT.PRT_NAME1
     *
     * @mbggenerated
     */
    public String getPrtName1() {
        return prtName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.PRT_NAME1
     *
     * @param prtName1 the value for BPTTLT.PRT_NAME1
     *
     * @mbggenerated
     */
    public void setPrtName1(String prtName1) {
        this.prtName1 = prtName1 == null ? null : prtName1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.PRT_NAME2
     *
     * @return the value of BPTTLT.PRT_NAME2
     *
     * @mbggenerated
     */
    public String getPrtName2() {
        return prtName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.PRT_NAME2
     *
     * @param prtName2 the value for BPTTLT.PRT_NAME2
     *
     * @mbggenerated
     */
    public void setPrtName2(String prtName2) {
        this.prtName2 = prtName2 == null ? null : prtName2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.PRT_NAME3
     *
     * @return the value of BPTTLT.PRT_NAME3
     *
     * @mbggenerated
     */
    public String getPrtName3() {
        return prtName3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.PRT_NAME3
     *
     * @param prtName3 the value for BPTTLT.PRT_NAME3
     *
     * @mbggenerated
     */
    public void setPrtName3(String prtName3) {
        this.prtName3 = prtName3 == null ? null : prtName3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.TS
     *
     * @return the value of BPTTLT.TS
     *
     * @mbggenerated
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.TS
     *
     * @param ts the value for BPTTLT.TS
     *
     * @mbggenerated
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.TLR_CRD_PSW
     *
     * @return the value of BPTTLT.TLR_CRD_PSW
     *
     * @mbggenerated
     */
    public byte[] getTlrCrdPsw() {
        return tlrCrdPsw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.TLR_CRD_PSW
     *
     * @param tlrCrdPsw the value for BPTTLT.TLR_CRD_PSW
     *
     * @mbggenerated
     */
    public void setTlrCrdPsw(byte[] tlrCrdPsw) {
        this.tlrCrdPsw = tlrCrdPsw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.KB_PSW
     *
     * @return the value of BPTTLT.KB_PSW
     *
     * @mbggenerated
     */
    public byte[] getKbPsw() {
        return kbPsw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.KB_PSW
     *
     * @param kbPsw the value for BPTTLT.KB_PSW
     *
     * @mbggenerated
     */
    public void setKbPsw(byte[] kbPsw) {
        this.kbPsw = kbPsw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BPTTLT.LAST_KB_PSW
     *
     * @return the value of BPTTLT.LAST_KB_PSW
     *
     * @mbggenerated
     */
    public byte[] getLastKbPsw() {
        return lastKbPsw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BPTTLT.LAST_KB_PSW
     *
     * @param lastKbPsw the value for BPTTLT.LAST_KB_PSW
     *
     * @mbggenerated
     */
    public void setLastKbPsw(byte[] lastKbPsw) {
        this.lastKbPsw = lastKbPsw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BPTTLT
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tlr=").append(tlr);
        sb.append(", tlrBr=").append(tlrBr);
        sb.append(", tlrTks=").append(tlrTks);
        sb.append(", stafNo=").append(stafNo);
        sb.append(", ciNo=").append(ciNo);
        sb.append(", idTyp=").append(idTyp);
        sb.append(", idNo=").append(idNo);
        sb.append(", tlrCnNm=").append(tlrCnNm);
        sb.append(", tlrEnNm=").append(tlrEnNm);
        sb.append(", effDt=").append(effDt);
        sb.append(", expDt=").append(expDt);
        sb.append(", updDt=").append(updDt);
        sb.append(", updTlr=").append(updTlr);
        sb.append(", tlrTyp=").append(tlrTyp);
        sb.append(", tlrLvl=").append(tlrLvl);
        sb.append(", txLvl=").append(txLvl);
        sb.append(", athLvl=").append(athLvl);
        sb.append(", athGrn=").append(athGrn);
        sb.append(", tmpTxLvl=").append(tmpTxLvl);
        sb.append(", tmpAthLvl=").append(tmpAthLvl);
        sb.append(", txMode=").append(txMode);
        sb.append(", signSts=").append(signSts);
        sb.append(", tlrSts=").append(tlrSts);
        sb.append(", regTyp=").append(regTyp);
        sb.append(", signDt=").append(signDt);
        sb.append(", croBrSign=").append(croBrSign);
        sb.append(", ignTimes=").append(ignTimes);
        sb.append(", pswRetry=").append(pswRetry);
        sb.append(", trmTyp=").append(trmTyp);
        sb.append(", signTrm=").append(signTrm);
        sb.append(", prtIp=").append(prtIp);
        sb.append(", tlrStsw=").append(tlrStsw);
        sb.append(", lastJrn=").append(lastJrn);
        sb.append(", accVchNo=").append(accVchNo);
        sb.append(", tlrCrdNo=").append(tlrCrdNo);
        sb.append(", crdPswDt=").append(crdPswDt);
        sb.append(", kbPswDt=").append(kbPswDt);
        sb.append(", tele=").append(tele);
        sb.append(", pstAddress=").append(pstAddress);
        sb.append(", signTrmFlg=").append(signTrmFlg);
        sb.append(", trmInfo=").append(trmInfo);
        sb.append(", pswTyp=").append(pswTyp);
        sb.append(", idenDevId=").append(idenDevId);
        sb.append(", newBr=").append(newBr);
        sb.append(", newBrEff=").append(newBrEff);
        sb.append(", tmOutLmt=").append(tmOutLmt);
        sb.append(", accSenCus=").append(accSenCus);
        sb.append(", accSenGl=").append(accSenGl);
        sb.append(", superFlg=").append(superFlg);
        sb.append(", prtName1=").append(prtName1);
        sb.append(", prtName2=").append(prtName2);
        sb.append(", prtName3=").append(prtName3);
        sb.append(", ts=").append(ts);
        sb.append(", tlrCrdPsw=").append(tlrCrdPsw);
        sb.append(", kbPsw=").append(kbPsw);
        sb.append(", lastKbPsw=").append(lastKbPsw);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}