package com.hisun.PY;

public class PYB1200_AWA_1200 {
    public int PRD_CD = 0;
    public short PRD_CD_NO = 0;
    public String CON_NAME = " ";
    public short CON_NAME_NO = 0;
    public String CNTR_NO = " ";
    public short CNTR_NO_NO = 0;
    public short ATCH_NUM = 0;
    public short ATCH_NUM_NO = 0;
    public String COLL_CCY = " ";
    public short COLL_CCY_NO = 0;
    public double COLL_AMT = 0;
    public short COLL_AMT_NO = 0;
    public char COLL_WAY = ' ';
    public short COLL_WAY_NO = 0;
    public char COL_KIND = ' ';
    public short COL_KIND_NO = 0;
    public long RBANK_NO = 0;
    public short RBANK_NO_NO = 0;
    public String RBANK_NM = " ";
    public short RBANK_NM_NO = 0;
    public String RACC_NO = " ";
    public short RACC_NO_NO = 0;
    public String RACC_NM = " ";
    public short RACC_NM_NO = 0;
    public long PBANK_NO = 0;
    public short PBANK_NO_NO = 0;
    public String PBANK_NM = " ";
    public short PBANK_NM_NO = 0;
    public String PACC_NO = " ";
    public short PACC_NO_NO = 0;
    public String PACC_NM = " ";
    public short PACC_NM_NO = 0;
    public char FEE_FLG = ' ';
    public short FEE_FLG_NO = 0;
    public double FEE_AMT = 0;
    public short FEE_AMT_NO = 0;
    public String FE_AC_NO = " ";
    public short FE_AC_NO_NO = 0;
}
