package com.hisun.DC;

public class DCB0205_AWA_0205 {
    public char FUNC = ' ';
    public short FUNC_NO = 0;
    public String PROD_CD = " ";
    public short PROD_CD_NO = 0;
    public String PROD_NM = " ";
    public short PROD_NM_NO = 0;
    public String LN_AC = " ";
    public short LN_AC_NO = 0;
    public String DD_AC = " ";
    public short DD_AC_NO = 0;
    public String CCY = " ";
    public short CCY_NO = 0;
    public char CCY_TYP = ' ';
    public short CCY_TYP_NO = 0;
    public char LN_TYP = ' ';
    public short LN_TYP_NO = 0;
    public char ADP_TYP = ' ';
    public short ADP_TYP_NO = 0;
    public char DED_MTH = ' ';
    public short DED_MTH_NO = 0;
    public double D_MN_AMT = 0;
    public short D_MN_AMT_NO = 0;
    public double D_MX_AMT = 0;
    public short D_MX_AMT_NO = 0;
    public double DD_D_PER = 0;
    public short DD_D_PER_NO = 0;
    public double LN_D_PER = 0;
    public short LN_D_PER_NO = 0;
    public short C_ED_PER = 0;
    public short C_ED_PER_NO = 0;
    public short T_ED_PER = 0;
    public short T_ED_PER_NO = 0;
    public double STRAMT = 0;
    public short STRAMT_NO = 0;
    public int STRDT = 0;
    public short STRDT_NO = 0;
    public int EXPDT = 0;
    public short EXPDT_NO = 0;
}
