package com.hisun.DC;

public class DCCSNCGC {
    public DCCSNCGC_INP_DATA INP_DATA = new DCCSNCGC_INP_DATA();
    public DCCSNCGC_AORC_OUT_DATA AORC_OUT_DATA = new DCCSNCGC_AORC_OUT_DATA();
    public DCCSNCGC_QUIRE_OUT_DATA QUIRE_OUT_DATA = new DCCSNCGC_QUIRE_OUT_DATA();
    public DCCSNCGC_UPD_OUT_DATA UPD_OUT_DATA = new DCCSNCGC_UPD_OUT_DATA();
}
