package com.hisun.DC;

public class DCCUOPEN {
    public String CARD_PROD_CD = " ";
    public String CARD_CLS_PROD = " ";
    public String BV_CD_NO = " ";
    public String CARD_NO = " ";
    public String CARD_BIN = " ";
    public long CARD_SEG1 = 0;
    public long CARD_SEQ = 0;
    public String PRIM_CD_NO = " ";
    public String PRIM_CD_HD_IDTYP = " ";
    public String PRIM_CD_HD_IDNO = " ";
    public String PRIM_CD_PSW = " ";
    public String HOLDER_IDTYP = " ";
    public String HOLDER_IDNO = " ";
    public String HOLDER_CINO = " ";
    public String HOLDER_NAME = " ";
    public String EMBOSS_NAME = " ";
    public String OWNER_IDTYP = " ";
    public String OWNER_IDNO = " ";
    public String OWNER_CINO = " ";
    public String OWNER_NAME = " ";
    public String AC_NO = " ";
    public char AC_TYP = ' ';
    public char ISSUE_MTH = ' ';
    public char SNAME_TRAN_FLG = ' ';
    public char DNAME_TRAN_FLG = ' ';
    public char OUT_DRAW_FLG = ' ';
    public char CARD_LNK_TYP = ' ';
    public char PROD_LMT_FLG = ' ';
    public char TRAN_WITH_CARD = ' ';
    public char TRAN_NO_CARD = ' ';
    public char TRAN_CRS_BOR = ' ';
    public char TRAN_ATM_FLG = ' ';
    public char HOLD_AC_FLG = ' ';
    public char AC_TYPE = ' ';
    public char AGENT_FLG = ' ';
    public String AGENT_IDTYP = " ";
    public String AGENT_IDNO = " ";
    public String AGENT_NAME = " ";
    public char DB_FREE = ' ';
    public String CUS_MGR = " ";
    public String REG_CENT = " ";
    public String SUB_BIZ = " ";
    public DCZUOPEN_RC RC = new DCZUOPEN_RC();
}
