package com.hisun.DC;

import com.hisun.TC.XStreamUtil;
import com.hisun.TD.*;
import com.hisun.SC.*;

import java.io.IOException;
import java.sql.SQLException;

public class DCOT7680 {
    short WS_FLD_NO = 0;
    String WS_ERR_MSG = " ";
    DCCMSG_ERROR_MSG DCCMSG_ERROR_MSG = new DCCMSG_ERROR_MSG();
    TDCMSG_ERROR_MSG TDCMSG_ERROR_MSG = new TDCMSG_ERROR_MSG();
    SCCMSG SCCMSG = new SCCMSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCFMT SCCFMT = new SCCFMT();
    DCCSTTZC DCCSTTZC = new DCCSTTZC();
    SCCGWA SCCGWA;
    DCB7680_AWA_7680 DCB7680_AWA_7680;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROCESS();
        B000_MAIN_PROCESS();
        CEP.TRC(SCCGWA, "DCOT7680 return!");
        Z_RET();
    }
    public void A000_INIT_PROCESS() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "DCB7680_AWA_7680>");
        DCB7680_AWA_7680 = (DCB7680_AWA_7680) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
    }
    public void B000_MAIN_PROCESS() throws IOException,SQLException,Exception {
        B010_CHECK_INPUT();
        B200_TRANS_DATA_PROC();
    }
    public void B010_CHECK_INPUT() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, DCB7680_AWA_7680);
        CEP.TRC(SCCGWA, DCB7680_AWA_7680.PROD_CD);
        CEP.TRC(SCCGWA, DCB7680_AWA_7680.BV_TYP);
        CEP.TRC(SCCGWA, DCB7680_AWA_7680.MAIN_AC);
        CEP.TRC(SCCGWA, DCB7680_AWA_7680.ID_TYP);
        CEP.TRC(SCCGWA, DCB7680_AWA_7680.ID_NO);
        CEP.TRC(SCCGWA, DCB7680_AWA_7680.CI_NO);
        CEP.TRC(SCCGWA, DCB7680_AWA_7680.CCY);
        CEP.TRC(SCCGWA, DCB7680_AWA_7680.TERM);
        CEP.TRC(SCCGWA, DCB7680_AWA_7680.DRAW_MTH);
        CEP.TRC(SCCGWA, DCB7680_AWA_7680.VAL_DT);
        CEP.TRC(SCCGWA, DCB7680_AWA_7680.CT_FLG);
        CEP.TRC(SCCGWA, DCB7680_AWA_7680.CALR_STD);
        if (DCB7680_AWA_7680.PROD_CD.trim().length() == 0) {
            WS_ERR_MSG = TDCMSG_ERROR_MSG.TD_PRD_NOT_MATCH;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        if (DCB7680_AWA_7680.BV_TYP == ' ') {
            WS_ERR_MSG = TDCMSG_ERROR_MSG.TD_BV_TYP_ERR;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        if (DCB7680_AWA_7680.MAIN_AC.trim().length() == 0) {
            WS_ERR_MSG = DCCMSG_ERROR_MSG.DC_VIA_AC_MUST_INPUT;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        if (DCB7680_AWA_7680.ID_TYP.trim().length() == 0) {
            WS_ERR_MSG = TDCMSG_ERROR_MSG.TD_ID_TYP_NEED;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        if (DCB7680_AWA_7680.ID_NO.trim().length() == 0) {
            WS_ERR_MSG = TDCMSG_ERROR_MSG.TD_ID_NO_MST_IPT;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        if (DCB7680_AWA_7680.CI_NO.trim().length() == 0) {
            WS_ERR_MSG = TDCMSG_ERROR_MSG.TD_CI_NO_MST_IPT;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        if (DCB7680_AWA_7680.CCY.trim().length() == 0) {
            WS_ERR_MSG = TDCMSG_ERROR_MSG.TD_CCY_NOT_MATCH;
            S000_ERR_MSG_PROC_CONTINUE();
        } else {
            if (!DCB7680_AWA_7680.CCY.equalsIgnoreCase("156")) {
                WS_ERR_MSG = TDCMSG_ERROR_MSG.TD_CCY_NOT_MATCH;
                S000_ERR_MSG_PROC_CONTINUE();
            }
        }
        if (DCB7680_AWA_7680.TERM.trim().length() == 0) {
            WS_ERR_MSG = TDCMSG_ERROR_MSG.TD_TERM_M_IPT;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        if (DCB7680_AWA_7680.DRAW_MTH == ' ') {
            WS_ERR_MSG = TDCMSG_ERROR_MSG.TD_DRAW_MTH_M_INPUT;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        if (DCB7680_AWA_7680.VAL_DT == 0) {
            WS_ERR_MSG = TDCMSG_ERROR_MSG.TD_VAL_DT_M_INPUT;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        if (DCB7680_AWA_7680.CT_FLG == ' ') {
            WS_ERR_MSG = TDCMSG_ERROR_MSG.TD_CT_FLG_M_INPUT;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        if (DCB7680_AWA_7680.CALR_STD.trim().length() == 0) {
            WS_ERR_MSG = TDCMSG_ERROR_MSG.TD_CALR_STD_M_INPUT;
            S000_ERR_MSG_PROC_CONTINUE();
        }
        WS_ERR_MSG = DCCMSG_ERROR_MSG.DC_INPUT_DATA_ERR;
        S000_ERR_MSG_PROC_LAST();
    }
    public void B200_TRANS_DATA_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, DCCSTTZC);
        DCCSTTZC.VAL.PROD_CD = DCB7680_AWA_7680.PROD_CD;
        DCCSTTZC.VAL.BV_CD = DCB7680_AWA_7680.BV_CD;
        DCCSTTZC.VAL.BV_TYP = DCB7680_AWA_7680.BV_TYP;
        DCCSTTZC.VAL.PRT_FLG = DCB7680_AWA_7680.PRT_FLG;
        DCCSTTZC.VAL.BV_NO = DCB7680_AWA_7680.BV_NO;
        DCCSTTZC.VAL.MAIN_AC = DCB7680_AWA_7680.MAIN_AC;
        DCCSTTZC.VAL.CARD_NO = DCB7680_AWA_7680.CARD_NO;
        DCCSTTZC.VAL.CVV = DCB7680_AWA_7680.CVV;
        DCCSTTZC.VAL.ID_TYP = DCB7680_AWA_7680.ID_TYP;
        DCCSTTZC.VAL.ID_NO = DCB7680_AWA_7680.ID_NO;
        DCCSTTZC.VAL.CI_NO = DCB7680_AWA_7680.CI_NO;
        DCCSTTZC.VAL.NAME = DCB7680_AWA_7680.NAME;
        DCCSTTZC.VAL.ADDR = DCB7680_AWA_7680.ADDR;
        DCCSTTZC.VAL.TEL = DCB7680_AWA_7680.TEL;
        DCCSTTZC.VAL.CCY = DCB7680_AWA_7680.CCY;
        DCCSTTZC.VAL.CCY_TYP = DCB7680_AWA_7680.CCY_TYP;
        DCCSTTZC.VAL.FC_CD = DCB7680_AWA_7680.FC_CD;
        DCCSTTZC.VAL.TXN_AMT = DCB7680_AWA_7680.TXN_AMT;
        DCCSTTZC.VAL.TERM = DCB7680_AWA_7680.TERM;
        DCCSTTZC.VAL.DRAW_MTH = DCB7680_AWA_7680.DRAW_MTH;
        DCCSTTZC.VAL.CUS_PSW_FLG = DCB7680_AWA_7680.PSW_FLG;
        DCCSTTZC.VAL.PSW = DCB7680_AWA_7680.PSW;
        DCCSTTZC.VAL.CROS_DR_FLG = DCB7680_AWA_7680.CS_D_FLG;
        DCCSTTZC.VAL.VAL_DT = DCB7680_AWA_7680.VAL_DT;
        DCCSTTZC.VAL.CT_FLG = DCB7680_AWA_7680.CT_FLG;
        DCCSTTZC.VAL.OPP_AC = DCB7680_AWA_7680.OPP_AC;
        DCCSTTZC.VAL.OPP_BV_NO = DCB7680_AWA_7680.OPP_BVNO;
        DCCSTTZC.VAL.OPP_CARD_NO = DCB7680_AWA_7680.OPP_CANO;
        DCCSTTZC.VAL.OPP_NAME = DCB7680_AWA_7680.OPP_NAME;
        DCCSTTZC.VAL.OPP_REV_NO = DCB7680_AWA_7680.OPP_RVNO;
        DCCSTTZC.VAL.OPP_DRAW_MTH = DCB7680_AWA_7680.OPP_DWMH;
        DCCSTTZC.VAL.OPP_PSW = DCB7680_AWA_7680.OPP_PSW;
        DCCSTTZC.VAL.OPP_ID_TYP = DCB7680_AWA_7680.OPP_IDTP;
        DCCSTTZC.VAL.OPP_ID_NO = DCB7680_AWA_7680.OPP_ID;
        DCCSTTZC.VAL.CHQ_TYPE = DCB7680_AWA_7680.CHQ_TYPE;
        DCCSTTZC.VAL.CHQ_NO = DCB7680_AWA_7680.CHQ_NO;
        DCCSTTZC.VAL.CHQ_DATE = DCB7680_AWA_7680.CHQ_DATE;
        DCCSTTZC.VAL.TXN_CHNL = DCB7680_AWA_7680.TXN_CHNL;
        DCCSTTZC.VAL.TXN_PNT = DCB7680_AWA_7680.TXN_PNT;
        DCCSTTZC.VAL.AC = DCB7680_AWA_7680.AC;
        DCCSTTZC.VAL.INSTR_MTH = DCB7680_AWA_7680.ISR_MTH;
        DCCSTTZC.VAL.CALR_STD = DCB7680_AWA_7680.CALR_STD;
        DCCSTTZC.VAL.MMO = DCB7680_AWA_7680.MMO;
        DCCSTTZC.VAL.REMARK = DCB7680_AWA_7680.REMARK;
        DCCSTTZC.VAL.INT_SEL = DCB7680_AWA_7680.INT_SEL;
        DCCSTTZC.VAL.SPRD_PCT = DCB7680_AWA_7680.SPRD_PCT;
        DCCSTTZC.VAL.SPRD_PNT = DCB7680_AWA_7680.SPRD_PNT;
        DCCSTTZC.VAL.RUL_CD = DCB7680_AWA_7680.RUL_CD;
        DCCSTTZC.VAL.INT_RAT = DCB7680_AWA_7680.INT_RAT;
        DCCSTTZC.VAL.AC_TRK2 = DCB7680_AWA_7680.AC_TRK2;
        DCCSTTZC.VAL.AC_TRK3 = DCB7680_AWA_7680.AC_TRK3;
        DCCSTTZC.VAL.OPP_TRK2 = DCB7680_AWA_7680.OPP_TRK2;
        DCCSTTZC.VAL.OPP_TRK3 = DCB7680_AWA_7680.OPP_TRK3;
        DCCSTTZC.VAL.PAY_PSW = DCB7680_AWA_7680.PAY_PSW;
        S000_CALL_DCZSTTZC();
        CEP.TRC(SCCGWA, DCB7680_AWA_7680.AC);
        DCB7680_AWA_7680.AC = DCCSTTZC.VAL.AC;
        CEP.TRC(SCCGWA, DCB7680_AWA_7680.AC);
    }
    public void S000_CALL_DCZSTTZC() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "DC-SVR-DCZSTTZC", DCCSTTZC);
    }
    public void S000_ERR_MSG_PROC_CONTINUE() throws IOException,SQLException,Exception {
        CEP.ERRC(SCCGWA, WS_ERR_MSG, WS_FLD_NO);
    }
    public void S000_ERR_MSG_PROC_LAST() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_ERR_MSG);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
