package com.hisun.DC;

import com.hisun.PN.ODDAT_KEY;

public class DCRODDAT {
    ODDAT_KEY KEY = new ODDAT_KEY();
    char ACNO_TYPE = ' ';
    short EXC_CARD_TMS = 0;
    String CARD_CLS_PROD = " ";
    String BV_CD_NO = " ";
    char CARD_LNK_TYP = ' ';
    String PROD_CD = " ";
    String CARD_OWN_CINO = " ";
    String CARD_HLDR_CINO = " ";
    char CARD_MEDI = ' ';
    char CARD_STS = ' ';
    String CARD_STSW = " ";
    String CARD_TYP = " ";
    String TRAN_PIN_DAT = " ";
    String QURY_PIN_DAT = " ";
    char PVK_TYP = ' ';
    char HOLD_AC_FLG = ' ';
    char PROD_LMT_FLG = ' ';
    char CVV_FLG = ' ';
    char SAME_NAME_TFR_FLG = ' ';
    char DIFF_NAME_TFR_FLG = ' ';
    char DRAW_OVER_FLG = ' ';
    char SF_FLG = ' ';
    char DOUBLE_FREE_FLG = ' ';
    char JOIN_CUS_FLG = ' ';
    char ANNUAL_FEE_FREE = ' ';
    int ISSU_BR = 0;
    int CLT_BR = 0;
    String OPEN_CHNL = " ";
    int EMBS_DT = 0;
    int ISSU_DT = 0;
    int ACT_DT = 0;
    int EXP_DT = 0;
    int CLO_DT = 0;
    int ANU_FEE_NXT = 0;
    double ANU_FEE_PCT = 0;
    short ANU_FEE_FREE = 0;
    double ANU_FEE_ARG = 0;
    int PIN_ERR_CNT = 0;
    int PIN_LCK_DT = 0;
    int CVV_LCK_DT = 0;
    int LAST_TXN_DT = 0;
    String AC_OIC_NO = " ";
    String AC_OIC_CODE = " ";
    String SUB_DP = " ";
    char MOVE_FLG = ' ';
    char PSW_TYP = ' ';
    String PRIM_CARD_NO = " ";
    String E_CARD_NO = " ";
    char TRAN_WITH_CARD = ' ';
    char TRAN_NO_CARD = ' ';
    char TRAN_CRS_BOR = ' ';
    char TRAN_ATM_FLG = ' ';
    int CRT_DATE = 0;
    String CRT_TLR = " ";
    int UPDTBL_DATE = 0;
    String UPDTBL_TLR = " ";
    String TS = " ";
}
