package com.hisun.DC;

import java.io.IOException;
import java.sql.SQLException;

import com.hisun.BP.BPCPNHIS;
import com.hisun.BP.BPCPQPRD;
import com.hisun.BP.BPCUBUSE;
import com.hisun.CI.CICACCU;
import com.hisun.CI.CICCUST;
import com.hisun.CI.CICMAGT;
import com.hisun.CI.CICMSG_ERROR_MSG;
import com.hisun.DD.DDCSCINM;
import com.hisun.SC.SCCCALL;
import com.hisun.SC.SCCEXCP;
import com.hisun.SC.SCCFMT;
import com.hisun.SC.SCCMPAG;
import com.hisun.SC.SCCMSG;

public class DCZSWEBD {
    boolean pgmRtn = false;
    String CPN_DCZPQPRD = "DC-P-QUERY-PROD";
    String CPN_BPZPQPRD = "BP-P-QUERY-PRDT-INFO";
    String CPN_DCZUCSET = "DC-U-CARD-SETUP";
    String CPN_DDZSCINM = "DD-SVR-CI-NAME";
    String CPN_REC_NHIS = "BP-REC-NHIS";
    String K_OUTPUT_FMT = "DC960";
    String K_DC_IN_CI_TYPE = "DC";
    String WS_ERR_MSG = " ";
    int WS_CNT = 0;
    char WS_CUST_CI_TYP = ' ';
    long WS_SEQNO = 0;
    long WS_S_SEQNO = 0;
    long WS_BATCHNO = 0;
    char WS_OLDCARD_FLG = 'N';
    char WS_RECORD_FLG = 'N';
    char WS_PSW_ENV_FLG = ' ';
    char WS_CARD_TYPE = ' ';
    char WS_CIZACCU_FLG = 'N';
    short WS_FLD_NO = 0;
    int WS_TOT_SUB_CARD_CNT = 0;
    int WS_MAX_SUP_CNT = 0;
    String WS_LNK_AC_CCY = " ";
    String WS_CDORD_BV_CD_NO = " ";
    DCZSWEBD_WS_CARD_NO_18 WS_CARD_NO_18 = new DCZSWEBD_WS_CARD_NO_18();
    long WS_CARD_SEG2 = 0;
    String WS_CARD_NO = " ";
    String WS_PARM_CODE = " ";
    String WS_TRAN_PIN_DAT = " ";
    DCZSWEBD_WS_OUTPUT WS_OUTPUT = new DCZSWEBD_WS_OUTPUT();
    int WS_CNT_SQL = 0;
    long WS_E_SEQ = 0;
    char WS_OPEN_CARD_FLG = ' ';
    char WS_TBL_FLAG = ' ';
    DCCMSG_ERROR_MSG DCCMSG_ERROR_MSG = new DCCMSG_ERROR_MSG();
    CICMSG_ERROR_MSG CICMSG_ERROR_MSG = new CICMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCFMT SCCFMT = new SCCFMT();
    SCCMPAG SCCMPAG = new SCCMPAG();
    SCCMSG SCCMSG = new SCCMSG();
    DCRCDORD DCRCDORD = new DCRCDORD();
    DCRBINPM DCRBINPM = new DCRBINPM();
    DCRCDPRT DCRCDPRT = new DCRCDPRT();
    DCRNOCRD DCRNOCRD = new DCRNOCRD();
    DCRDCCLS DCRDCCLS = new DCRDCCLS();
    BPCPNHIS BPCPNHIS = new BPCPNHIS();
    BPCPQPRD BPCPQPRD = new BPCPQPRD();
    DCCPQPRD DCCDQPRD = new DCCPQPRD();
    DCCUCINF DCCUCINF = new DCCUCINF();
    DCCUCSET DCCUCSET = new DCCUCSET();
    DCCSSPOT DCCHISTY = new DCCSSPOT();
    DDCSCINM DDCSCINM = new DDCSCINM();
    DDCUOPAC DDCUOPAC = new DDCUOPAC();
    CICSACRL CICSACRL = new CICSACRL();
    BPCUBUSE BPCUBUSE = new BPCUBUSE();
    DCCUPSWM DCCUPSWM = new DCCUPSWM();
    CICCUST CICCUST = new CICCUST();
    CICMAGT CICMAGT = new CICMAGT();
    CICUAGT CICUAGT = new CICUAGT();
    DCRCDDAT DCRCDDAT = new DCRCDDAT();
    CICACCU CICACCU = new CICACCU();
