package com.hisun.DC;

import java.io.IOException;
import java.sql.SQLException;

import com.hisun.SC.SCCCALL;
import com.hisun.SC.SCCEXCP;
import com.hisun.SC.SCCFMT;
import com.hisun.SC.SCCGBPA_BP_AREA;
import com.hisun.SC.SCCGSCA_SC_AREA;
import com.hisun.SC.SCCGWA;
import com.hisun.SC.SCCMPAG;
import com.hisun.SC.SCCMSG;

public class DCZUMPRM {
    boolean pgmRtn = false;
    String K_OUTPUT_FMT = "DCXXX";
    int WS_OUT_CNT = 0;
    String WS_MSGID = " ";
    short WS_FLD_NO = 0;
    char WS_MPRM_FLG = ' ';
    DCCMSG_ERROR_MSG DCCMSG_ERROR_MSG = new DCCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    SCCFMT SCCFMT = new SCCFMT();
    SCCMPAG SCCMPAG = new SCCMPAG();
    DCRMPRM DCRMPRM = new DCRMPRM();
    DCRMPRM DCRMPRO = new DCRMPRM();
    SCCGWA SCCGWA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    DCCUMPRM DCCUMPRM;
    public void MP(SCCGWA SCCGWA, DCCUMPRM DCCUMPRM) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        this.DCCUMPRM = DCCUMPRM;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        if (pgmRtn) return;
        B000_MAIN_PROC();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, "DCZUMPRM return!");
        Z_RET();
        if (pgmRtn) return;
        JIBS_RETURN();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B100_CHECK_INPUT_DATA();
        if (pgmRtn) return;
        if (DCCUMPRM.FUNC == 'I') {
            B200_INQ_PARM_CD_PROC();
            if (pgmRtn) return;
        } else if (DCCUMPRM.FUNC == 'A') {
            B300_ADD_PARM_CD_PROC();
            if (pgmRtn) return;
        } else if (DCCUMPRM.FUNC == 'M') {
            B400_MOD_PARM_CD_PROC();
            if (pgmRtn) return;
        } else if (DCCUMPRM.FUNC == 'D') {
            B500_DEL_PARM_CD_PROC();
            if (pgmRtn) return;
        } else {
            IBS.init(SCCGWA, SCCEXCP);
            SCCEXCP.MSG_TEXT.KEY_OR_OTHER = "INVALID TX TYPE(" + DCCUMPRM.FUNC + ")";
            CEP.EXCP(SCCGWA, SCCEXCP.MSG_TEXT.KEY_OR_OTHER);
        }
    }
    public void B100_CHECK_INPUT_DATA() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, DCCUMPRM.FUNC);
        CEP.TRC(SCCGWA, DCCUMPRM.BANK_NO);
        CEP.TRC(SCCGWA, DCCUMPRM.DATA.KEY.CON_MDEL);
        CEP.TRC(SCCGWA, DCCUMPRM.DATA.KEY.PROD_CODE);
        CEP.TRC(SCCGWA, DCCUMPRM.DATA.EFFDAT);
        if (DCCUMPRM.FUNC == ' ') {
            IBS.CPY2CLS(SCCGWA, DCCMSG_ERROR_MSG.DC_FUNC_M_INPUT, DCCUMPRM.RC);
            Z_RET();
            if (pgmRtn) return;
        }
        if (DCCUMPRM.FUNC != 'A' 
            && DCCUMPRM.FUNC != 'D' 
            && DCCUMPRM.FUNC != 'M' 
            && DCCUMPRM.FUNC != 'I') {
            IBS.CPY2CLS(SCCGWA, DCCMSG_ERROR_MSG.DC_FUNC_INVALID, DCCUMPRM.RC);
            Z_RET();
            if (pgmRtn) return;
        }
        if (DCCUMPRM.BANK_NO.trim().length() == 0) {
            DCCUMPRM.BANK_NO = SCCGWA.COMM_AREA.TR_BANK;
        }
        if (DCCUMPRM.DATA.KEY.CON_MDEL.trim().length() == 0) {
            DCCUMPRM.DATA.KEY.CON_MDEL = "IRDD";
        }
        if (DCCUMPRM.DATA.EFFDAT == 0) {
            DCCUMPRM.DATA.EFFDAT = SCCGWA.COMM_AREA.AC_DATE;
        }
        if (DCCUMPRM.DATA.EXPDAT == 0) {
            DCCUMPRM.DATA.EXPDAT = 20991231;
        }
        if (DCCUMPRM.DATA.KEY.PROD_CODE.trim().length() == 0) {
            IBS.CPY2CLS(SCCGWA, DCCMSG_ERROR_MSG.DC_PARM_CODE_M_INPUT, DCCUMPRM.RC);
            Z_RET();
            if (pgmRtn) return;
        }
        if (DCCUMPRM.FUNC == 'A') {
            if (DCCUMPRM.DATA.EFFDAT < SCCGWA.COMM_AREA.AC_DATE) {
                IBS.CPY2CLS(SCCGWA, DCCMSG_ERROR_MSG.DC_EFF_LT_AC_DATE, DCCUMPRM.RC);
                Z_RET();
                if (pgmRtn) return;
            }
        }
        if (DCCUMPRM.DATA.EFFDAT >= DCCUMPRM.DATA.EXPDAT) {
            IBS.CPY2CLS(SCCGWA, DCCMSG_ERROR_MSG.DC_EFF_MUST_LT_EXP_DT, DCCUMPRM.RC);
            Z_RET();
            if (pgmRtn) return;
        }
    }
    public void B200_INQ_PARM_CD_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, DCRMPRM);
        DCRMPRM.KEY.IBS_AC_BK = DCCUMPRM.BANK_NO;
        DCRMPRM.KEY.PRDMO_CD = DCCUMPRM.DATA.KEY.CON_MDEL;
        DCRMPRM.KEY.PARM_CODE = DCCUMPRM.DATA.KEY.PROD_CODE;
        DCRMPRM.KEY.EFF_DATE = DCCUMPRM.DATA.EFFDAT;
        R000_STARTBR_DCTMPRM_FIRST();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, WS_MPRM_FLG);
        if (WS_MPRM_FLG == 'N') {
            IBS.CPY2CLS(SCCGWA, DCCMSG_ERROR_MSG.DC_PRD_REC_NOTFND, DCCUMPRM.RC);
            Z_RET();
            if (pgmRtn) return;
        } else {
            R000_TRANS_DATA_OUTPUT();
            if (pgmRtn) return;
        }
    }
    public void B300_ADD_PARM_CD_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, DCRMPRM);
        DCRMPRM.KEY.IBS_AC_BK = DCCUMPRM.BANK_NO;
        DCRMPRM.KEY.PRDMO_CD = DCCUMPRM.DATA.KEY.CON_MDEL;
        DCRMPRM.KEY.PARM_CODE = DCCUMPRM.DATA.KEY.PROD_CODE;
        T000_READ_DCTMPRM_FIRST();
        if (pgmRtn) return;
        if (WS_MPRM_FLG == 'Y' 
            && DCRMPRM.EXP_DATE > SCCGWA.COMM_AREA.AC_DATE) {
            IBS.CPY2CLS(SCCGWA, DCCMSG_ERROR_MSG.DC_REC_ALR_EXIST, DCCUMPRM.RC);
            Z_RET();
            if (pgmRtn) return;
        }
        DCRMPRM.PROD_DESC = DCCUMPRM.DATA.PROD_DESC;
        DCRMPRM.KEY.EFF_DATE = DCCUMPRM.DATA.EFFDAT;
        DCRMPRM.EXP_DATE = DCCUMPRM.DATA.EXPDAT;
        DCRMPRM.CI_TYP = DCCUMPRM.DATA.CI_TYP;
        DCRMPRM.CCY = DCCUMPRM.DATA.CCY;
        DCRMPRM.CCY_TYPE = DCCUMPRM.DATA.CCY_TYPE;
        DCRMPRM.OVR_CARD_FLG = DCCUMPRM.DATA.OVR_CARD_FLG;
        DCRMPRM.PROD_DD1 = DCCUMPRM.DATA.PROD_DD_INFO[1-1].PROD_DD;
        DCRMPRM.DESC_DD1 = DCCUMPRM.DATA.PROD_DD_INFO[1-1].DESC_DD;
        DCRMPRM.PROD_DD2 = DCCUMPRM.DATA.PROD_DD_INFO[2-1].PROD_DD;
        DCRMPRM.DESC_DD2 = DCCUMPRM.DATA.PROD_DD_INFO[2-1].DESC_DD;
        DCRMPRM.PROD_DD3 = DCCUMPRM.DATA.PROD_DD_INFO[3-1].PROD_DD;
        DCRMPRM.DESC_DD3 = DCCUMPRM.DATA.PROD_DD_INFO[3-1].DESC_DD;
        DCRMPRM.PROD_DD4 = DCCUMPRM.DATA.PROD_DD_INFO[4-1].PROD_DD;
        DCRMPRM.DESC_DD4 = DCCUMPRM.DATA.PROD_DD_INFO[4-1].DESC_DD;
        DCRMPRM.PROD_DD5 = DCCUMPRM.DATA.PROD_DD_INFO[5-1].PROD_DD;
        DCRMPRM.DESC_DD5 = DCCUMPRM.DATA.PROD_DD_INFO[5-1].DESC_DD;
        DCRMPRM.PROD_DD6 = DCCUMPRM.DATA.PROD_DD_INFO[6-1].PROD_DD;
        DCRMPRM.DESC_DD6 = DCCUMPRM.DATA.PROD_DD_INFO[6-1].DESC_DD;
        DCRMPRM.PROD_DD7 = DCCUMPRM.DATA.PROD_DD_INFO[7-1].PROD_DD;
        DCRMPRM.DESC_DD7 = DCCUMPRM.DATA.PROD_DD_INFO[7-1].DESC_DD;
        DCRMPRM.PROD_DD8 = DCCUMPRM.DATA.PROD_DD_INFO[8-1].PROD_DD;
        DCRMPRM.DESC_DD8 = DCCUMPRM.DATA.PROD_DD_INFO[8-1].DESC_DD;
        DCRMPRM.PROD_DD9 = DCCUMPRM.DATA.PROD_DD_INFO[9-1].PROD_DD;
        DCRMPRM.DESC_DD9 = DCCUMPRM.DATA.PROD_DD_INFO[9-1].DESC_DD;
        DCRMPRM.PROD_DD10 = DCCUMPRM.DATA.PROD_DD_INFO[10-1].PROD_DD;
        DCRMPRM.DESC_DD10 = DCCUMPRM.DATA.PROD_DD_INFO[10-1].DESC_DD;
        DCRMPRM.PROD_TD1 = DCCUMPRM.DATA.PROD_TD_INFO[1-1].PROD_TD;
        DCRMPRM.DESC_TD1 = DCCUMPRM.DATA.PROD_TD_INFO[1-1].DESC_TD;
        DCRMPRM.PROD_TD2 = DCCUMPRM.DATA.PROD_TD_INFO[2-1].PROD_TD;
        DCRMPRM.DESC_TD2 = DCCUMPRM.DATA.PROD_TD_INFO[2-1].DESC_TD;
        DCRMPRM.PROD_TD3 = DCCUMPRM.DATA.PROD_TD_INFO[3-1].PROD_TD;
        DCRMPRM.DESC_TD3 = DCCUMPRM.DATA.PROD_TD_INFO[3-1].DESC_TD;
        DCRMPRM.PROD_TD4 = DCCUMPRM.DATA.PROD_TD_INFO[4-1].PROD_TD;
        DCRMPRM.DESC_TD4 = DCCUMPRM.DATA.PROD_TD_INFO[4-1].DESC_TD;
        DCRMPRM.PROD_TD5 = DCCUMPRM.DATA.PROD_TD_INFO[5-1].PROD_TD;
        DCRMPRM.DESC_TD5 = DCCUMPRM.DATA.PROD_TD_INFO[5-1].DESC_TD;
        DCRMPRM.PROD_TD6 = DCCUMPRM.DATA.PROD_TD_INFO[6-1].PROD_TD;
        DCRMPRM.DESC_TD6 = DCCUMPRM.DATA.PROD_TD_INFO[6-1].DESC_TD;
        DCRMPRM.PROD_TD7 = DCCUMPRM.DATA.PROD_TD_INFO[7-1].PROD_TD;
        DCRMPRM.DESC_TD7 = DCCUMPRM.DATA.PROD_TD_INFO[7-1].DESC_TD;
        DCRMPRM.PROD_TD8 = DCCUMPRM.DATA.PROD_TD_INFO[8-1].PROD_TD;
        DCRMPRM.DESC_TD8 = DCCUMPRM.DATA.PROD_TD_INFO[8-1].DESC_TD;
        DCRMPRM.PROD_TD9 = DCCUMPRM.DATA.PROD_TD_INFO[9-1].PROD_TD;
        DCRMPRM.DESC_TD9 = DCCUMPRM.DATA.PROD_TD_INFO[9-1].DESC_TD;
        DCRMPRM.PROD_TD10 = DCCUMPRM.DATA.PROD_TD_INFO[10-1].PROD_TD;
        DCRMPRM.DESC_TD10 = DCCUMPRM.DATA.PROD_TD_INFO[10-1].DESC_TD;
        DCRMPRM.USAGE_MTH = DCCUMPRM.DATA.USAGE_MTH;
        DCRMPRM.DRAW_MTH = DCCUMPRM.DATA.DRAW_MTH;
        DCRMPRM.DRAW_ORDER = DCCUMPRM.DATA.DRAW_ORDER;
        DCRMPRM.INOUT_FG = DCCUMPRM.DATA.INOUT_FG;
        DCRMPRM.OUT_LVL = DCCUMPRM.DATA.OUT_LVL;
        DCRMPRM.IN_LVL = DCCUMPRM.DATA.IN_LVL;
        DCRMPRM.OVR_BANK = DCCUMPRM.DATA.OVR_BANK;
        DCRMPRM.TRIG_TMS = DCCUMPRM.DATA.TRIG_TMS;
        DCRMPRM.PERM_KND1 = DCCUMPRM.DATA.PERM_INFO[1-1].PERM_KND;
        DCRMPRM.PERM_KND2 = DCCUMPRM.DATA.PERM_INFO[2-1].PERM_KND;
        DCRMPRM.PERM_KND3 = DCCUMPRM.DATA.PERM_INFO[3-1].PERM_KND;
        DCRMPRM.PERM_KND4 = DCCUMPRM.DATA.PERM_INFO[4-1].PERM_KND;
        DCRMPRM.PERM_KND5 = DCCUMPRM.DATA.PERM_INFO[5-1].PERM_KND;
        DCRMPRM.PERM_MTH1 = DCCUMPRM.DATA.PERM_INFO1[1-1].PERM_MTH;
        DCRMPRM.PERM_MTH2 = DCCUMPRM.DATA.PERM_INFO1[2-1].PERM_MTH;
        DCRMPRM.PERM_MTH3 = DCCUMPRM.DATA.PERM_INFO1[3-1].PERM_MTH;
        DCRMPRM.PERM_MTH4 = DCCUMPRM.DATA.PERM_INFO1[4-1].PERM_MTH;
        DCRMPRM.PERM_MTH5 = DCCUMPRM.DATA.PERM_INFO1[5-1].PERM_MTH;
        DCRMPRM.INT_MTH1 = DCCUMPRM.DATA.INT_INFO[1-1].INT_MTH;
        DCRMPRM.INT_MTH2 = DCCUMPRM.DATA.INT_INFO[2-1].INT_MTH;
        DCRMPRM.INT_MTH3 = DCCUMPRM.DATA.INT_INFO[3-1].INT_MTH;
        DCRMPRM.INT_MTH4 = DCCUMPRM.DATA.INT_INFO[4-1].INT_MTH;
        DCRMPRM.INT_MTH5 = DCCUMPRM.DATA.INT_INFO[5-1].INT_MTH;
        DCRMPRM.CRT_DATE = SCCGWA.COMM_AREA.AC_DATE;
        DCRMPRM.CRT_TLR = SCCGWA.COMM_AREA.TL_ID;
        T000_WRITE_DCTMPRM();
        if (pgmRtn) return;
    }
    public void B400_MOD_PARM_CD_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, DCRMPRM);
        DCRMPRM.KEY.IBS_AC_BK = DCCUMPRM.BANK_NO;
        DCRMPRM.KEY.PRDMO_CD = DCCUMPRM.DATA.KEY.CON_MDEL;
        DCRMPRM.KEY.PARM_CODE = DCCUMPRM.DATA.KEY.PROD_CODE;
        T000_READ_DCTMPRM_FIRST();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, WS_MPRM_FLG);
        if (WS_MPRM_FLG == 'N') {
            CEP.TRC(SCCGWA, "--PARMCODE NOTFND--");
            IBS.CPY2CLS(SCCGWA, DCCMSG_ERROR_MSG.DC_PRD_REC_NOTFND, DCCUMPRM.RC);
            Z_RET();
            if (pgmRtn) return;
        } else {
            CEP.TRC(SCCGWA, "--ADD A NEW RECORD--");
            if (DCRMPRM.KEY.EFF_DATE == DCCUMPRM.DATA.EFFDAT) {
                R000_MODIFY_PROC();
                if (pgmRtn) return;
            } else {
                B300_ADD_PARM_CD_PROC();
                if (pgmRtn) return;
            }
        }
    }
    public void B500_DEL_PARM_CD_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, DCRMPRM);
        DCRMPRM.KEY.IBS_AC_BK = DCCUMPRM.BANK_NO;
        DCRMPRM.KEY.PRDMO_CD = DCCUMPRM.DATA.KEY.CON_MDEL;
        DCRMPRM.KEY.PARM_CODE = DCCUMPRM.DATA.KEY.PROD_CODE;
        T000_READ_DCTMPRM_FIRST();
        if (pgmRtn) return;
        CEP.TRC(SCCGWA, WS_MPRM_FLG);
        if (WS_MPRM_FLG == 'N') {
            IBS.CPY2CLS(SCCGWA, DCCMSG_ERROR_MSG.DC_PRD_REC_NOTFND, DCCUMPRM.RC);
            Z_RET();
            if (pgmRtn) return;
        } else {
            CEP.TRC(SCCGWA, DCRMPRM.EXP_DATE);
            if (DCRMPRM.EXP_DATE <= SCCGWA.COMM_AREA.AC_DATE) {
                IBS.CPY2CLS(SCCGWA, DCCMSG_ERROR_MSG.DC_PRDREC_ALR_EXP, DCCUMPRM.RC);
                Z_RET();
                if (pgmRtn) return;
            } else {
                DCRMPRM.EXP_DATE = SCCGWA.COMM_AREA.AC_DATE;
                DCRMPRM.UPDTBL_DATE = SCCGWA.COMM_AREA.AC_DATE;
                DCRMPRM.UPDTBL_TLR = SCCGWA.COMM_AREA.TL_ID;
                T000_REWRITE_DCTMPRM();
                if (pgmRtn) return;
            }
        }
    }
    public void R000_MODIFY_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, DCRMPRM);
        IBS.init(SCCGWA, DCRMPRO);
        DCRMPRM.KEY.IBS_AC_BK = DCCUMPRM.BANK_NO;
        DCRMPRM.KEY.PRDMO_CD = DCCUMPRM.DATA.KEY.CON_MDEL;
        DCRMPRM.KEY.PARM_CODE = DCCUMPRM.DATA.KEY.PROD_CODE;
        DCRMPRM.KEY.EFF_DATE = DCCUMPRM.DATA.EFFDAT;
        T000_READUP_DCTMPRM();
        if (pgmRtn) return;
        IBS.CLONE(SCCGWA, DCRMPRM, DCRMPRO);
        DCRMPRM.KEY.IBS_AC_BK = DCCUMPRM.BANK_NO;
        DCRMPRM.KEY.PRDMO_CD = DCCUMPRM.DATA.KEY.CON_MDEL;
        DCRMPRM.KEY.PARM_CODE = DCCUMPRM.DATA.KEY.PROD_CODE;
        DCRMPRM.PROD_DESC = DCCUMPRM.DATA.PROD_DESC;
        DCRMPRM.KEY.EFF_DATE = DCCUMPRM.DATA.EFFDAT;
        DCRMPRM.EXP_DATE = DCCUMPRM.DATA.EXPDAT;
        DCRMPRM.CI_TYP = DCCUMPRM.DATA.CI_TYP;
        DCRMPRM.CCY = DCCUMPRM.DATA.CCY;
        DCRMPRM.CCY_TYPE = DCCUMPRM.DATA.CCY_TYPE;
        DCRMPRM.OVR_CARD_FLG = DCCUMPRM.DATA.OVR_CARD_FLG;
        DCRMPRM.PROD_DD1 = DCCUMPRM.DATA.PROD_DD_INFO[1-1].PROD_DD;
        DCRMPRM.DESC_DD1 = DCCUMPRM.DATA.PROD_DD_INFO[1-1].DESC_DD;
        DCRMPRM.PROD_DD2 = DCCUMPRM.DATA.PROD_DD_INFO[2-1].PROD_DD;
        DCRMPRM.DESC_DD2 = DCCUMPRM.DATA.PROD_DD_INFO[2-1].DESC_DD;
        DCRMPRM.PROD_DD3 = DCCUMPRM.DATA.PROD_DD_INFO[3-1].PROD_DD;
        DCRMPRM.DESC_DD3 = DCCUMPRM.DATA.PROD_DD_INFO[3-1].DESC_DD;
        DCRMPRM.PROD_DD4 = DCCUMPRM.DATA.PROD_DD_INFO[4-1].PROD_DD;
        DCRMPRM.DESC_DD4 = DCCUMPRM.DATA.PROD_DD_INFO[4-1].DESC_DD;
        DCRMPRM.PROD_DD5 = DCCUMPRM.DATA.PROD_DD_INFO[5-1].PROD_DD;
        DCRMPRM.DESC_DD5 = DCCUMPRM.DATA.PROD_DD_INFO[5-1].DESC_DD;
        DCRMPRM.PROD_DD6 = DCCUMPRM.DATA.PROD_DD_INFO[6-1].PROD_DD;
        DCRMPRM.DESC_DD6 = DCCUMPRM.DATA.PROD_DD_INFO[6-1].DESC_DD;
        DCRMPRM.PROD_DD7 = DCCUMPRM.DATA.PROD_DD_INFO[7-1].PROD_DD;
        DCRMPRM.DESC_DD7 = DCCUMPRM.DATA.PROD_DD_INFO[7-1].DESC_DD;
        DCRMPRM.PROD_DD8 = DCCUMPRM.DATA.PROD_DD_INFO[8-1].PROD_DD;
        DCRMPRM.DESC_DD8 = DCCUMPRM.DATA.PROD_DD_INFO[8-1].DESC_DD;
        DCRMPRM.PROD_DD9 = DCCUMPRM.DATA.PROD_DD_INFO[9-1].PROD_DD;
        DCRMPRM.DESC_DD9 = DCCUMPRM.DATA.PROD_DD_INFO[9-1].DESC_DD;
        DCRMPRM.PROD_DD10 = DCCUMPRM.DATA.PROD_DD_INFO[10-1].PROD_DD;
        DCRMPRM.DESC_DD10 = DCCUMPRM.DATA.PROD_DD_INFO[10-1].DESC_DD;
        DCRMPRM.PROD_TD1 = DCCUMPRM.DATA.PROD_TD_INFO[1-1].PROD_TD;
        DCRMPRM.DESC_TD1 = DCCUMPRM.DATA.PROD_TD_INFO[1-1].DESC_TD;
        DCRMPRM.PROD_TD2 = DCCUMPRM.DATA.PROD_TD_INFO[2-1].PROD_TD;
        DCRMPRM.DESC_TD2 = DCCUMPRM.DATA.PROD_TD_INFO[2-1].DESC_TD;
        DCRMPRM.PROD_TD3 = DCCUMPRM.DATA.PROD_TD_INFO[3-1].PROD_TD;
        DCRMPRM.DESC_TD3 = DCCUMPRM.DATA.PROD_TD_INFO[3-1].DESC_TD;
        DCRMPRM.PROD_TD4 = DCCUMPRM.DATA.PROD_TD_INFO[4-1].PROD_TD;
        DCRMPRM.DESC_TD4 = DCCUMPRM.DATA.PROD_TD_INFO[4-1].DESC_TD;
        DCRMPRM.PROD_TD5 = DCCUMPRM.DATA.PROD_TD_INFO[5-1].PROD_TD;
        DCRMPRM.DESC_TD5 = DCCUMPRM.DATA.PROD_TD_INFO[5-1].DESC_TD;
        DCRMPRM.PROD_TD6 = DCCUMPRM.DATA.PROD_TD_INFO[6-1].PROD_TD;
        DCRMPRM.DESC_TD6 = DCCUMPRM.DATA.PROD_TD_INFO[6-1].DESC_TD;
        DCRMPRM.PROD_TD7 = DCCUMPRM.DATA.PROD_TD_INFO[7-1].PROD_TD;
        DCRMPRM.DESC_TD7 = DCCUMPRM.DATA.PROD_TD_INFO[7-1].DESC_TD;
        DCRMPRM.PROD_TD8 = DCCUMPRM.DATA.PROD_TD_INFO[8-1].PROD_TD;
        DCRMPRM.DESC_TD8 = DCCUMPRM.DATA.PROD_TD_INFO[8-1].DESC_TD;
        DCRMPRM.PROD_TD9 = DCCUMPRM.DATA.PROD_TD_INFO[9-1].PROD_TD;
        DCRMPRM.DESC_TD9 = DCCUMPRM.DATA.PROD_TD_INFO[9-1].DESC_TD;
        DCRMPRM.PROD_TD10 = DCCUMPRM.DATA.PROD_TD_INFO[10-1].PROD_TD;
        DCRMPRM.DESC_TD10 = DCCUMPRM.DATA.PROD_TD_INFO[10-1].DESC_TD;
        DCRMPRM.USAGE_MTH = DCCUMPRM.DATA.USAGE_MTH;
        DCRMPRM.DRAW_MTH = DCCUMPRM.DATA.DRAW_MTH;
        DCRMPRM.DRAW_ORDER = DCCUMPRM.DATA.DRAW_ORDER;
        DCRMPRM.INOUT_FG = DCCUMPRM.DATA.INOUT_FG;
        DCRMPRM.OUT_LVL = DCCUMPRM.DATA.OUT_LVL;
        DCRMPRM.IN_LVL = DCCUMPRM.DATA.IN_LVL;
        DCRMPRM.OVR_BANK = DCCUMPRM.DATA.OVR_BANK;
        DCRMPRM.TRIG_TMS = DCCUMPRM.DATA.TRIG_TMS;
        DCRMPRM.PERM_KND1 = DCCUMPRM.DATA.PERM_INFO[1-1].PERM_KND;
        DCRMPRM.PERM_KND2 = DCCUMPRM.DATA.PERM_INFO[2-1].PERM_KND;
        DCRMPRM.PERM_KND3 = DCCUMPRM.DATA.PERM_INFO[3-1].PERM_KND;
        DCRMPRM.PERM_KND4 = DCCUMPRM.DATA.PERM_INFO[4-1].PERM_KND;
        DCRMPRM.PERM_KND5 = DCCUMPRM.DATA.PERM_INFO[5-1].PERM_KND;
        DCRMPRM.PERM_MTH1 = DCCUMPRM.DATA.PERM_INFO1[1-1].PERM_MTH;
        DCRMPRM.PERM_MTH2 = DCCUMPRM.DATA.PERM_INFO1[2-1].PERM_MTH;
        DCRMPRM.PERM_MTH3 = DCCUMPRM.DATA.PERM_INFO1[3-1].PERM_MTH;
        DCRMPRM.PERM_MTH4 = DCCUMPRM.DATA.PERM_INFO1[4-1].PERM_MTH;
        DCRMPRM.PERM_MTH5 = DCCUMPRM.DATA.PERM_INFO1[5-1].PERM_MTH;
        DCRMPRM.INT_MTH1 = DCCUMPRM.DATA.INT_INFO[1-1].INT_MTH;
        DCRMPRM.INT_MTH2 = DCCUMPRM.DATA.INT_INFO[2-1].INT_MTH;
        DCRMPRM.INT_MTH3 = DCCUMPRM.DATA.INT_INFO[3-1].INT_MTH;
        DCRMPRM.INT_MTH4 = DCCUMPRM.DATA.INT_INFO[4-1].INT_MTH;
        DCRMPRM.INT_MTH5 = DCCUMPRM.DATA.INT_INFO[5-1].INT_MTH;
