package com.hisun.CM;

public class CMB0018_AWA_0018 {
    public char TR_TYPE = ' ';
    public short TR_TYPE_NO = 0;
    public String REQ_JRN = " ";
    public short REQ_JRN_NO = 0;
    public int REQ_DATE = 0;
    public short REQ_DATE_NO = 0;
    public String REQ_SYS = " ";
    public short REQ_SYS_NO = 0;
    public String REQ_CHNL = " ";
    public short REQ_CHNL_NO = 0;
    public String TL_NO = " ";
    public short TL_NO_NO = 0;
    public int TR_BR = 0;
    public short TR_BR_NO = 0;
    public String AP_REF = " ";
    public short AP_REF_NO = 0;
    public String CHN_TYP = " ";
    public short CHN_TYP_NO = 0;
    public CMB0018_AC_DATA[] AC_DATA = new CMB0018_AC_DATA[9];
    public String P_IN_AC = " ";
    public short P_IN_AC_NO = 0;
    public String INT_AC = " ";
    public short INT_AC_NO = 0;
    public String ERR_AC = " ";
    public short ERR_AC_NO = 0;
    public String F_PRO_CD = " ";
    public short F_PRO_CD_NO = 0;
    public String FIN_AC = " ";
    public short FIN_AC_NO = 0;
    public CMB0018_EVE_DATA[] EVE_DATA = new CMB0018_EVE_DATA[4];
    public double TAX_RAT1 = 0;
    public short TAX_RAT1_NO = 0;
    public double TAX_RAT2 = 0;
    public short TAX_RAT2_NO = 0;
    public double TAX_RAT3 = 0;
    public short TAX_RAT3_NO = 0;
    public double TAX_RAT4 = 0;
    public short TAX_RAT4_NO = 0;
    public double TAX_RAT5 = 0;
    public short TAX_RAT5_NO = 0;
    public double TAX_RAT6 = 0;
    public short TAX_RAT6_NO = 0;
    public double TAX_RAT7 = 0;
    public short TAX_RAT7_NO = 0;
    public double TAX_RAT8 = 0;
    public short TAX_RAT8_NO = 0;
    public double TAX_RAT9 = 0;
    public short TAX_RAT9_NO = 0;
    public double TAX_RA10 = 0;
    public short TAX_RA10_NO = 0;
    public String RMK = " ";
    public short RMK_NO = 0;
    public char PROC_STS = ' ';
    public short PROC_STS_NO = 0;
    public String RET_CODE = " ";
    public short RET_CODE_NO = 0;
    public String RET_MSG = " ";
    public short RET_MSG_NO = 0;
    public int DATE = 0;
    public short DATE_NO = 0;
    public long JRNNO = 0;
    public short JRNNO_NO = 0;
    public String VCH_NO = " ";
    public short VCH_NO_NO = 0;
    public CMB0018_RET_DATA[] RET_DATA = new CMB0018_RET_DATA[9];
    public double BAL_AMT = 0;
    public short BAL_AMT_NO = 0;
    public double INT_AMT = 0;
    public short INT_AMT_NO = 0;
    public String RET_CREV = " ";
    public short RET_CREV_NO = 0;
    public CMB0018_AWA_0018() {
        for (int i=0;i<9;i++) AC_DATA[i] = new CMB0018_AC_DATA();
        for (int i=0;i<4;i++) EVE_DATA[i] = new CMB0018_EVE_DATA();
        for (int i=0;i<9;i++) RET_DATA[i] = new CMB0018_RET_DATA();
    }
}
