package com.hisun.CM;

public class CMB6010_ARRAY {
    public char FUNC = ' ';
    public short FUNC_NO = 0;
    public String AC = " ";
    public short AC_NO = 0;
    public String CHQ_NO = " ";
    public short CHQ_NO_NO = 0;
    public String CCY = " ";
    public short CCY_NO = 0;
    public char CCY_TYPE = ' ';
    public short CCY_TYPE_NO = 0;
    public String HOLD_NO = " ";
    public short HOLD_NO_NO = 0;
    public double AMT = 0;
    public short AMT_NO = 0;
    public int EFF_DATE = 0;
    public short EFF_DATE_NO = 0;
    public int EXP_DATE = 0;
    public short EXP_DATE_NO = 0;
    public char SPR_TYP = ' ';
    public short SPR_TYP_NO = 0;
    public int HOLD_BR = 0;
    public short HOLD_BR_NO = 0;
    public String SPR_NO = " ";
    public short SPR_NO_NO = 0;
    public String SPR_NAME = " ";
    public short SPR_NAME_NO = 0;
    public String LAW_NM1 = " ";
    public short LAW_NM1_NO = 0;
    public String LAW_NO1 = " ";
    public short LAW_NO1_NO = 0;
    public String LAW_NM2 = " ";
    public short LAW_NM2_NO = 0;
    public String LAW_NO2 = " ";
    public short LAW_NO2_NO = 0;
    public String REASON = " ";
    public short REASON_NO = 0;
    public String REMARK = " ";
    public short REMARK_NO = 0;
}
