package com.hisun.CM;

public class CMB8140_AWA_8140 {
    public String AC = " ";
    public short AC_NO = 0;
    public String ACNO = " ";
    public short ACNO_NO = 0;
    public int AC_SEQ = 0;
    public short AC_SEQ_NO = 0;
    public String CCY = " ";
    public short CCY_NO = 0;
    public char CCY_TYP = ' ';
    public short CCY_TYP_NO = 0;
    public char CHK_PSW = ' ';
    public short CHK_PSW_NO = 0;
    public String PSW = " ";
    public short PSW_NO = 0;
    public char CHK_ID = ' ';
    public short CHK_ID_NO = 0;
    public String ID_TYPE = " ";
    public short ID_TYPE_NO = 0;
    public String ID_NO = " ";
    public short ID_NO_NO = 0;
    public char CHK_MAG = ' ';
    public short CHK_MAG_NO = 0;
    public String TRK2_DAT = " ";
    public short TRK2_DAT_NO = 0;
    public String TRK3_DAT = " ";
    public short TRK3_DAT_NO = 0;
    public char CHK_CVN2 = ' ';
    public short CHK_CVN2_NO = 0;
    public String CVN2 = " ";
    public short CVN2_NO = 0;
    public char C_E_DATE = ' ';
    public short C_E_DATE_NO = 0;
    public int EXP_DATE = 0;
    public short EXP_DATE_NO = 0;
    public char CHK_NAME = ' ';
    public short CHK_NAME_NO = 0;
    public String NAME = " ";
    public short NAME_NO = 0;
    public char CHK_TEL = ' ';
    public short CHK_TEL_NO = 0;
    public String TEL_NO = " ";
    public short TEL_NO_NO = 0;
}
