package com.hisun.CM;

public class CMCF630_INF {
    public String CUS_AC = " ";
    public String CI_NO = " ";
    public char CI_TYP = ' ';
    public String CI_NM = " ";
    public char FILLER6 = 0X02;
    public String CI_ID_TYP = " ";
    public String CI_ID_NO = " ";
    public char FILLER9 = 0X02;
    public String CI_STSW = " ";
    public String TEL_NO = " ";
    public int CI_OPE_BR = 0;
    public String ACR_STSW = " ";
    public String CPN_NM = " ";
    public char FILLER15 = 0X02;
    public String FRM_APP = " ";
    public String CUS_AC_TYP = " ";
    public char CUS_STS = ' ';
    public String CUS_STSW = " ";
    public int CUS_OPE_BR = 0;
    public int CUS_OWN_BR = 0;
    public char BV_TYP = ' ';
    public String BV_CODE = " ";
    public String BV_NO = " ";
    public char LOST_FLG = ' ';
    public char DRW_TYP = ' ';
    public int AC_SEQ = 0;
    public String CCY = " ";
    public char CCY_TYP = ' ';
    public String ACO_NO = " ";
    public char ACO_STS = ' ';
    public String ACO_STSW = " ";
    public int ACO_OPE_BR = 0;
    public int ACO_OWN_BR = 0;
    public double LAST_BAL = 0;
    public char FILLER36 = 0X02;
    public double AVA_BAL = 0;
    public char FILLER38 = 0X02;
    public double CUR_BAL = 0;
    public char FILLER40 = 0X02;
    public char ENTY_TYP = ' ';
    public char AC_KND = ' ';
    public String OP_CHL = " ";
}
