package com.hisun.CM;

public class CMCI1200_AC_DATA {
    public char DC_FLG01 = ' ';
    public String TR_CTL01 = " ";
    public String CHK_CTL01 = " ";
    public char AC_TYP01 = ' ';
    public String CUS_AC01 = " ";
    public int AC_SEQ01 = 0;
    public String CCY_AC01 = " ";
    public char CCY_TYP01 = ' ';
    public String CREV_NO01 = " ";
    public String HLD_NO01 = " ";
    public double TXN_AMT01 = 0;
    public String AC_NM01 = " ";
    public String ID_TYP01 = " ";
    public String ID_NO01 = " ";
    public String TRK2_DAT01 = " ";
    public String TRK3_DAT01 = " ";
    public String PSW01 = " ";
    public String BV_CODE01 = " ";
    public String BV_NO01 = " ";
    public String CHQ_TYP01 = " ";
    public int SIGN_DT01 = 0;
    public String CHQ_NO01 = " ";
    public String PAY_PSW01 = " ";
    public String RMK_CD01 = " ";
    public String CTA_NO01 = " ";
    public String REF_NO01 = " ";
    public String OPP_AC01 = " ";
    public String OPP_ACNM01 = " ";
    public String OPP_BKNM01 = " ";
    public String OPP_BKNO01 = " ";
    public String PAL_INAC01 = " ";
    public String INT_INAC01 = " ";
    public String ERR_PRAC01 = " ";
    public double HLD_AMT01 = 0;
    public String INR_CINO01 = " ";
    public String INR_PROD01 = " ";
}
