package com.hisun.CM;

import com.hisun.SC.*;
import com.hisun.TC.XStreamUtil;
import com.hisun.DC.*;

import java.io.IOException;
import java.sql.SQLException;

public class CMOT6010 {
    CMOT6010_WS_TEMP_VARIABLE WS_TEMP_VARIABLE = new CMOT6010_WS_TEMP_VARIABLE();
    CMCMSG_ERROR_MSG CMCMSG_ERROR_MSG = new CMCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    SCCFMT SCCFMT = new SCCFMT();
    DCCURHLD DCCURHLD = new DCCURHLD();
    DCCUHLD DCCUHLD = new DCCUHLD();
    CMCF601 CMCF601 = new CMCF601();
    SCCGWA SCCGWA;
    CMB6010_AWA_6010 CMB6010_AWA_6010;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    public void MP(SCCGWA SCCGWA) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "CMOT6010 return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        SCCGWA.COMM_AREA.AWA_AREA_PTR = SCCGWA.COMM_AREA.AWA_AREA_PTR.replaceAll("BODY>", "CMB6010_AWA_6010>");
        CMB6010_AWA_6010 = (CMB6010_AWA_6010) XStreamUtil.xmlToBean(SCCGWA.COMM_AREA.AWA_AREA_PTR);
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B010_CHECK_INPUT();
        B030_HAMT_PROC();
        B050_OUT_PROC();
    }
    public void B010_CHECK_INPUT() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, "B010-CHK-INPUT-BEGIN");
        CEP.TRC(SCCGWA, CMB6010_AWA_6010.REC_CNT);
        if (CMB6010_AWA_6010.REC_CNT > 0 
            && CMB6010_AWA_6010.REC_CNT <= 10) {
            CEP.TRC(SCCGWA, "B010-CHK-INPUT-IN");
        } else {
            CEP.TRC(SCCGWA, "M-CM-AC-CNT-ERRO");
            WS_TEMP_VARIABLE.WS_ERR_MSG = CMCMSG_ERROR_MSG.CM_AC_CNT_ERRO;
            S000_ERR_MSG_PROC();
        }
    }
    public void B030_HAMT_PROC() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, CMB6010_AWA_6010);
        for (WS_TEMP_VARIABLE.WS_I = 1; WS_TEMP_VARIABLE.WS_I <= CMB6010_AWA_6010.REC_CNT; WS_TEMP_VARIABLE.WS_I += 1) {
            CEP.TRC(SCCGWA, "B030-HAMT-PROC-IN");
            CEP.TRC(SCCGWA, CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].FUNC);
            if (CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].FUNC == '1' 
                || CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].FUNC == '2' 
                || CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].FUNC == '3') {
                IBS.init(SCCGWA, DCCUHLD);
                DCCUHLD.DATA.AC = CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].AC;
                DCCUHLD.DATA.CHQ_NO = CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].CHQ_NO;
                DCCUHLD.DATA.HLD_TYP = CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].FUNC;
                DCCUHLD.DATA.SPR_TYP = CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].SPR_TYP;
                DCCUHLD.DATA.CCY = CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].CCY;
                DCCUHLD.DATA.CCY_TYP = CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].CCY_TYPE;
                DCCUHLD.DATA.AMT = CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].AMT;
                CEP.TRC(SCCGWA, CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].AMT);
                DCCUHLD.DATA.HLD_BR = CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].HOLD_BR;
                DCCUHLD.DATA.SPR_NO = CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].SPR_NO;
                DCCUHLD.DATA.SPR_NM = CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].SPR_NAME;
                DCCUHLD.DATA.LAW_NM1 = CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].LAW_NM1;
                DCCUHLD.DATA.LAW_NO1 = CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].LAW_NO1;
                DCCUHLD.DATA.LAW_NM2 = CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].LAW_NM2;
                DCCUHLD.DATA.LAW_NO2 = CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].LAW_NO2;
                DCCUHLD.DATA.RMK = CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].REMARK;
                DCCUHLD.DATA.RSN = CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].REASON;
                S000_CALL_DCZUHLD();
                B030_10_MOVE_PROC();
            } else {
                if (CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].FUNC == '4' 
                    || CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].FUNC == '5') {
                    IBS.init(SCCGWA, DCCURHLD);
                    DCCURHLD.DATA.HLD_NO = CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].HOLD_NO;
                    DCCURHLD.DATA.AC = CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].AC;
                    DCCURHLD.DATA.RHLD_TYP = CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].FUNC;
                    DCCURHLD.DATA.RAMT = CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].AMT;
                    DCCURHLD.DATA.CHG_NO = CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].SPR_NO;
                    DCCURHLD.DATA.SPR_NM = CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].SPR_NAME;
                    DCCURHLD.DATA.LAW_NM1 = CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].LAW_NM1;
                    DCCURHLD.DATA.LAW_NO1 = CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].LAW_NO1;
                    DCCURHLD.DATA.LAW_NM2 = CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].LAW_NM2;
                    DCCURHLD.DATA.LAW_NO2 = CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].LAW_NO2;
                    S000_CALL_DCZURHLD();
                    B030_20_MOVE_PROC();
                } else {
                    CEP.TRC(SCCGWA, "M-CM-FUNC-ERROR");
                    WS_TEMP_VARIABLE.WS_ERR_MSG = CMCMSG_ERROR_MSG.CM_FUNC_ERROR;
                    S000_ERR_MSG_PROC();
                }
            }
        }
    }
    public void B030_10_MOVE_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1]);
        CMCF601.REC_CNT = CMB6010_AWA_6010.REC_CNT;
        CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].AC = DCCUHLD.DATA.AC;
        CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].CHQ_NO = DCCUHLD.DATA.CHQ_NO;
        CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].FUNC = DCCUHLD.DATA.HLD_TYP;
        CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].CCY = DCCUHLD.DATA.CCY;
        CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].CCY_TYPE = DCCUHLD.DATA.CCY_TYP;
        CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].AMT = DCCUHLD.DATA.AMT;
        CEP.TRC(SCCGWA, DCCUHLD.DATA.AMT);
        CEP.TRC(SCCGWA, CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].AMT);
        CEP.TRC(SCCGWA, DCCUHLD.DATA.EXP_DT);
        if (CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].EFF_DATE != 0) {
            CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].EFF_DATE = CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].EFF_DATE;
        } else {
            CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].EFF_DATE = SCCGWA.COMM_AREA.AC_DATE;
        }
        CEP.TRC(SCCGWA, DCCUHLD.DATA.EFF_DT);
        if (CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].EXP_DATE != 0) {
            CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].EXP_DATE = CMB6010_AWA_6010.ARRAY[WS_TEMP_VARIABLE.WS_I-1].EXP_DATE;
        } else {
            CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].EXP_DATE = 99991231;
        }
        CEP.TRC(SCCGWA, CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].EFF_DT);
        CEP.TRC(SCCGWA, CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].EXP_DT);
        CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].HOLD_BR = DCCUHLD.DATA.HLD_BR;
        CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].HOLD_HAMT = DCCUHLD.DATA.HAMT;
        CEP.TRC(SCCGWA, DCCUHLD.DATA.HAMT);
        CEP.TRC(SCCGWA, CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].HOLD_HAMT);
        CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].HOLD_UAMT = DCCUHLD.DATA.UAMT;
        CEP.TRC(SCCGWA, DCCUHLD.DATA.UAMT);
        CEP.TRC(SCCGWA, CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].HOLD_UAMT);
    }
    public void B030_20_MOVE_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1]);
        CMCF601.REC_CNT = CMB6010_AWA_6010.REC_CNT;
        CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].AC = DCCURHLD.DATA.AC;
        CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].HOLD_NO = DCCURHLD.DATA.HLD_NO;
        CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].FUNC = DCCURHLD.DATA.RHLD_TYP;
        CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].AMT = DCCURHLD.DATA.RAMT;
        CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].HOLD_BR = DCCURHLD.DATA.CHG_BR;
        CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].BEF_AMT = DCCURHLD.DATA.BEF_AMT;
        CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].CCY = DCCURHLD.DATA.CCY;
        CEP.TRC(SCCGWA, CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].CCY);
        CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].CCY_TYPE = DCCURHLD.DATA.CCY_TYP;
        CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].EFF_DT = DCCURHLD.DATA.EFF_DT;
        CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].EXP_DT = DCCURHLD.DATA.EXP_DT;
        CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].REM_AMT = DCCURHLD.DATA.REM_AMT;
        CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].PRI_AC_FLG = DCCURHLD.DATA.PRI_AC_FLG;
        CMCF601.ARRAY[WS_TEMP_VARIABLE.WS_I-1].PRI_HLD_AMT = DCCURHLD.DATA.PRI_HLD_AMT;
    }
    public void B050_OUT_PROC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, SCCFMT);
        SCCFMT.FMTID = "35601";
        SCCFMT.ODM_FLG = 'Y';
        SCCFMT.DATA_PTR = CMCF601;
        SCCFMT.DATA_LEN = 2145;
        IBS.FMT(SCCGWA, SCCFMT);
    }
    public void S000_CALL_DCZUHLD() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, "CALL DCZUHLD BEGEIN");
        IBS.CALLCPN(SCCGWA, "DC-UNIT-HLD", DCCUHLD);
    }
    public void S000_CALL_DCZURHLD() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, "CALL DCZURHLD BEGEIN");
        IBS.CALLCPN(SCCGWA, "DC-UNIT-RHLD", DCCURHLD);
    }
    public void S000_ERR_MSG_PROC() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_TEMP_VARIABLE.WS_ERR_MSG);
    }
    public void S000_ERR_MSG_PROC_CONTINUE() throws IOException,SQLException,Exception {
        CEP.ERRC(SCCGWA, WS_TEMP_VARIABLE.WS_ERR_MSG, WS_TEMP_VARIABLE.WS_FLD_NO);
    }
    public void S000_ERR_MSG_PROC_LAST() throws IOException,SQLException,Exception {
        CEP.ERR(SCCGWA, WS_TEMP_VARIABLE.WS_ERR_MSG, WS_TEMP_VARIABLE.WS_FLD_NO);
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
