package com.hisun.CM;

import java.io.IOException;
import java.sql.SQLException;

public class CMZSSUBP {
    boolean pgmRtn = false;
    short WS_HEADER_CNT = 19;
    short WS_SYSIN_CNT = 12;
    short WS_PROC_START_POS = 19;
    short WS_CNT = 0;
    short WS_SUB_I = 0;
    short WS_POS = 0;
    int RESP = 0;
    long WK_TRS_SEQ = 0;
    int WS_I = 0;
    long WS_SMS_SEQ = 0;
    String WS_SMS_SEQ2 = " ";
    short WS_JOB_SEQ = 0;
    String WS_SMS_SEQ_HEX = " ";
    CMZSSUBP_WS_SMS_VAR WS_SMS_VAR = new CMZSSUBP_WS_SMS_VAR();
    CMZSSUBP_WS_MSGID WS_MSGID = new CMZSSUBP_WS_MSGID();
    String WS_ERR_MSG = " ";
    String WK_APL_ID = " ";
    String CMZSSUBP_FILLER2 = "SC";
    short WK_JOB_NO = 0;
    String CMZSSUBP_FILLER1 = "//         JOB ,'SCBSUBJB',CLASS=4,MSGCLASS=X,";
    String WK_ENQ_PARM = "               ";
    String CMZSSUBP_FILLER4 = "                   ";
    String CMZSSUBP_FILLER5 = "//        MSGLEVEL=(1,1),SCHENV=SECOREB,REGION=0M";
    String CMZSSUBP_FILLER6 = "//         SET LVL=";
    String WK_JCL_DSN = " ";
    String CMZSSUBP_FILLER8 = "                                                     ";
    CMZSSUBP_WK_APLID_LINE WK_APLID_LINE = new CMZSSUBP_WK_APLID_LINE();
    CMZSSUBP_WK_JOBNM_LINE WK_JOBNM_LINE = new CMZSSUBP_WK_JOBNM_LINE();
    String CMZSSUBP_FILLER17 = "//LIBSRCH  JCLLIB ORDER=(&LVL..IBS.PROCLIB,";
    String CMZSSUBP_FILLER18 = "//         &LVL..IBS.PARMLIB,";
    String CMZSSUBP_FILLER19 = "//         &LVL..BAT.PROCLIB,&LVL..BAT.PARMLIB)";
    String CMZSSUBP_FILLER20 = "//         INCLUDE MEMBER=SCPENV&ALPID";
    String CMZSSUBP_FILLER21 = "//JOBLIB   DD  DSN=&DBLOAD,DISP=SHR";
    String CMZSSUBP_FILLER22 = "//         DD  DSN=&LVL..BAT.LOADLIB,DISP=SHR";
    String CMZSSUBP_FILLER23 = "//         DD  DSN=CICSTS.CICS.SDFHEXCI,DISP=SHR";
    String CMZSSUBP_FILLER24 = "// EXPORT SYMLIST=(MO)";
    String WK_INP_DATA1 = "// SET ";
    String WK_INP_DATA2 = "// SET ";
    String WK_INP_DATA3 = "// SET ";
    String WK_INP_DATA4 = "// SET ";
    String WK_INP_DATA5 = "// SET ";
    String WK_INP_DATA6 = "// SET ";
    String WK_INP_DATA7 = "// SET BSPSEQ=        ";
    String WK_INP_DATA8 = "//DEFQBSP  EXEC PGM=IEFBR14,COND=(7,LT)";
    String WK_INP_DATA9 = "//SCQBSP   DD DISP=(NEW,PASS),DSN=&&SCQBSP,UNIT=SYSALLDA,";
    String WK_INP_DATAA = "//         DCB=(DSORG=PS,RECFM=FB,LRECL=80),";
    String WK_INP_DATAB = "//         SPACE=(CYL,(1,1))";
    String WK_EXEC_PROC = "//         EXEC PROC=";
    String WK_EXEC_PROC2 = "//         EXEC PROC=";
    String WK_EXEC_PROC3 = "//         EXEC PROC=";
    String CMZSSUBP_FILLER39 = "//*";
    String WK_INP_FILLER = "                                                                                                                                                                                                                                                                                                                                                                                                                ";
