package com.hisun.CM;

import com.hisun.SC.*;
import com.hisun.SC.SCCCALL;
import com.hisun.SC.SCCEXCP;
import com.hisun.SC.SCCFMT;
import com.hisun.SC.SCCGBPA_BP_AREA;
import com.hisun.SC.SCCGSCA_SC_AREA;
import com.hisun.SC.SCCGWA;
import com.hisun.SC.SCCMSG;
import com.hisun.CI.*;
import com.hisun.BP.*;
import com.hisun.DC.*;
import com.hisun.DD.*;
import com.hisun.TD.*;
import com.hisun.IB.*;
import com.hisun.AI.*;
import com.hisun.LN.*;

import java.io.IOException;
import java.sql.SQLException;

public class CMZSIQAC {
    int JIBS_tmp_int;
    String WS_ERR_MSG = " ";
    short WS_FLD_NO = 0;
    int WS_I = 0;
    short WS_R = 0;
    String WS_ACO_NO = " ";
    String WS_DDAC_STSW = " ";
    String WS_CUS_CUS_AC = " ";
    String WS_CUS_CI_NO = " ";
    String WS_CUS_ACO_NO = " ";
    int WS_CUS_CI_OPN_BR = 0;
    char WS_CUS_CI_TYP = ' ';
    String WS_CUS_CI_STSW = " ";
    String WS_CUS_ID_TYP = " ";
    String WS_CUS_ID_NO = " ";
    String WS_CUS_CI_NM = " ";
    String WS_CUS_CPN_NM = " ";
    String WS_CUS_TEL_NO = " ";
    int WS_CUS_OPEN_BR = 0;
    String WS_CUS_CARD_NO = " ";
    char WS_CUS_CD_MEDI = ' ';
    char WS_CUS_CD_STS = ' ';
    String WS_CUS_CD_STSW = " ";
    String WS_CUS_PROD_CD = " ";
    int WS_CUS_CD_OP_BR = 0;
    int WS_CUS_CD_CLT_BR = 0;
    char WS_CUS_LOST_FLG = ' ';
    int WS_CUS_AC_SEQ = 0;
    String WS_CUS_CCY = " ";
    char WS_CUS_CCY_TYP = ' ';
    char WS_CUS_AC_STS = ' ';
    String WS_CUS_AC_STSW = " ";
    int WS_CUS_AC_BR = 0;
    String WS_CUS_FRM_APP = " ";
    String WS_CUS_IBAC_TYP = " ";
    String WS_CUS_TDAC_TYP = " ";
    char WS_CUS_DDAC_TYP = ' ';
    char WS_CUS_CR_FLG = ' ';
    char WS_CUS_UEW_FLG = ' ';
    char WS_CUS_HLD_TYP = ' ';
    double WS_CUS_HLD_AMT = 0;
    double WS_CUS_LAST_BAL = 0;
    double WS_CUS_AVA_BAL = 0;
    double WS_CUS_CUR_BAL = 0;
    char WS_CUS_DRW_FLG = ' ';
    double WS_CUS_INT_RAT = 0;
    int WS_CUS_SDT = 0;
    int WS_CUS_EDT = 0;
    String WS_CUS_TERM_CD = " ";
    String WS_CUS_BV_CODE = " ";
    String WS_CUS_BV_NO = " ";
    char WS_CUS_BV_TYP = ' ';
    char WS_CUS_DRW_TYP = ' ';
    char WS_CUS_CASH_FLG = ' ';
    String WS_AC = " ";
    String WS_REL_CUS_AC = " ";
    String WS_OLD_CUS_AC = " ";
    char WS_MIB_CHK_FLG = ' ';
    char WS_DD_VCH_FLG = ' ';
    char WS_DC_DWK_FLG = ' ';
    CMCMSG_ERROR_MSG CMCMSG_ERROR_MSG = new CMCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    SCCFMT SCCFMT = new SCCFMT();
    CICQACAC CICQACAC = new CICQACAC();
    BPCPACTY BPCPACTY = new BPCPACTY();
    DCCUCINF DCCUCINF = new DCCUCINF();
    DDCIMMST DDCIMMST = new DDCIMMST();
    DDCIQBAL DDCIQBAL = new DDCIQBAL();
    TDCACE TDCACE = new TDCACE();
    CICCUST CICCUST = new CICCUST();
    DCCPCDCK DCCPCDCK = new DCCPCDCK();
    DDCIMPAY DDCIMPAY = new DDCIMPAY();
    TDCACM TDCACM = new TDCACM();
    IBCQINF IBCQINF = new IBCQINF();
    IBCQINFT IBCQINFT = new IBCQINFT();
    CICQACRI CICQACRI = new CICQACRI();
    TDCMACE TDCMACE = new TDCMACE();
    AICPQMIB AICPQMIB = new AICPQMIB();
    DDCUVCH DDCUVCH = new DDCUVCH();
    DDCUINVS DDCUINVS = new DDCUINVS();
    CICQACRL CICQACRL = new CICQACRL();
    LNRCONT LNRCONT = new LNRCONT();
    LNCRCONT LNCRCONT = new LNCRCONT();
    SCCGWA SCCGWA;
    SCCGSCA_SC_AREA GWA_SC_AREA;
    SCCGBPA_BP_AREA GWA_BP_AREA;
    CMCSIQAC CMCSIQAC;
    public void MP(SCCGWA SCCGWA, CMCSIQAC CMCSIQAC) throws IOException,SQLException,Exception {
        this.SCCGWA = SCCGWA;
        this.CMCSIQAC = CMCSIQAC;
        CEP.TRC(SCCGWA);
        A000_INIT_PROC();
        B000_MAIN_PROC();
        CEP.TRC(SCCGWA, "CMZSIQAC return!");
        Z_RET();
    }
    public void A000_INIT_PROC() throws IOException,SQLException,Exception {
        GWA_BP_AREA = (SCCGBPA_BP_AREA) SCCGWA.BP_AREA_PTR;
        GWA_SC_AREA = (SCCGSCA_SC_AREA) SCCGWA.SC_AREA_PTR;
        IBS.init(SCCGWA, CMCSIQAC.OUT_INF);
    }
    public void B000_MAIN_PROC() throws IOException,SQLException,Exception {
        B100_INPUT_CHECK_PROC();
        B200_INQ_MAIN_PROC();
    }
    public void B100_INPUT_CHECK_PROC() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, CMCSIQAC.I_FUNC);
        CEP.TRC(SCCGWA, CMCSIQAC.I_CUS_AC);
        CEP.TRC(SCCGWA, CMCSIQAC.I_PSW);
        CEP.TRC(SCCGWA, CMCSIQAC.I_AC_SEQ);
        if (CMCSIQAC.I_CUS_AC.trim().length() == 0) {
            CEP.ERR(SCCGWA, CMCMSG_ERROR_MSG.CM_CUS_AC_ERR);
        }
        if (CMCSIQAC.I_FUNC == '3' 
            && ((CMCSIQAC.I_CCY.trim().length() == 0 
            || CMCSIQAC.I_CCY.charAt(0) == 0X00) 
            && (CMCSIQAC.I_BV_NO.trim().length() == 0 
            || CMCSIQAC.I_BV_NO.charAt(0) == 0X00) 
            && (CMCSIQAC.I_AC_SEQ == 0))) {
            CEP.ERR(SCCGWA, CMCMSG_ERROR_MSG.CM_CCY_SEQ_BV_ERR);
        }
        if (CMCSIQAC.I_FUNC == '4' 
            && (CMCSIQAC.I_PSW.trim().length() == 0 
            || CMCSIQAC.I_PSW.charAt(0) == 0X00)) {
            CEP.ERR(SCCGWA, CMCMSG_ERROR_MSG.CM_PSW_INP_ERR);
        }
        if (CMCSIQAC.I_CCY.equalsIgnoreCase("156") 
            && CMCSIQAC.I_CCY_TYP == ' ') {
            CMCSIQAC.I_CCY_TYP = '1';
        }
    }
    public void B200_INQ_MAIN_PROC() throws IOException,SQLException,Exception {
        if (CMCSIQAC.I_FUNC == '1') {
            B210_INQ_CUS_INF();
        } else if (CMCSIQAC.I_FUNC == '2') {
            B210_INQ_CUS_INF();
            B300_INQ_CUS_AC_INF_PROC();
        } else if (CMCSIQAC.I_FUNC == '3') {
            B210_INQ_CUS_INF();
            B300_INQ_CUS_AC_INF_PROC();
            B400_INQ_ACO_NO_INF_PROC();
        } else if (CMCSIQAC.I_FUNC == '4') {
            B210_INQ_CUS_INF();
        } else if (CMCSIQAC.I_FUNC == '5') {
            B210_INQ_CUS_INF();
            B400_INQ_ACO_NO_INF_PROC();
        } else {
            CEP.ERR(SCCGWA, CMCMSG_ERROR_MSG.CM_FUNC_TYP_ERR);
        }
        B700_CHK_AC_PSWD_PROC();
        B800_OUTPUT_MERGER_PROC();
    }
    public void B210_INQ_CUS_INF() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, CICQACRI);
        CEP.TRC(SCCGWA, CMCSIQAC.I_CUS_AC);
        CICQACRI.FUNC = 'A';
        CICQACRI.DATA.AGR_NO = CMCSIQAC.I_CUS_AC;
        S000_CALL_CIZQACRI();
        CMCSIQAC.OUT_INF.BAS_INF.BAS_CPN_NM = CICQACRI.O_DATA.O_AC_CNM;
        CMCSIQAC.OUT_INF.BAS_INF.BAS_CPN_ENM = CICQACRI.O_DATA.O_AC_ENM;
        CEP.TRC(SCCGWA, "NCBZXJ180412");
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_CPN_NM);
        CEP.TRC(SCCGWA, CMCSIQAC.I_FUNC);
        CEP.TRC(SCCGWA, CICQACRI.O_DATA.O_STS_OLD);
        CEP.TRC(SCCGWA, CICQACRI.O_DATA.O_OPN_BR);
        CMCSIQAC.OUT_INF.BAS_INF.BAS_CI_OPE_BR = CICQACRI.O_DATA.O_OPN_BR;
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_CI_OPE_BR);
        CMCSIQAC.OUT_INF.BAS_INF.BAS_ACR_STSW = CICQACRI.O_DATA.O_STSW;
        if (CICQACRI.O_DATA.O_FRM_APP_OLD.trim().length() > 0) {
            CMCSIQAC.OUT_INF.BAS_INF.BAS_FRM_APP = CICQACRI.O_DATA.O_FRM_APP_OLD;
        } else {
            CMCSIQAC.OUT_INF.BAS_INF.BAS_FRM_APP = CICQACRI.O_DATA.O_FRM_APP;
        }
        CMCSIQAC.OUT_INF.BAS_INF.BAS_ENTY_TYP = CICQACRI.O_DATA.O_ENTY_TYP;
        if (CICQACRI.O_DATA.O_CNTRCT_TYP.equalsIgnoreCase("IBDD") 
            || CICQACRI.O_DATA.O_CNTRCT_TYP.equalsIgnoreCase("IBTD")) {
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_AC_TYP = CICQACRI.O_DATA.O_CNTRCT_TYP;
        }
        if (CMCSIQAC.OUT_INF.BAS_INF.BAS_FRM_APP.equalsIgnoreCase("DC") 
            && CICQACRI.O_DATA.O_CI_TYP == '2' 
            && CICQACRI.O_DATA.O_STS_OLD > '1') {
            WS_OLD_CUS_AC = CMCSIQAC.I_CUS_AC;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_ADD_INF.BAS_DWK_FLG = '1';
            IBS.init(SCCGWA, CICQACRL);
            CICQACRL.FUNC = 'I';
            CICQACRL.DATA.AC_NO = CMCSIQAC.I_CUS_AC;
            CICQACRL.DATA.AC_REL = "04";
            S000_CALL_CIZQACRL();
            CMCSIQAC.I_CUS_AC = CICQACRL.O_DATA.O_REL_AC_NO;
            WS_REL_CUS_AC = CICQACRL.O_DATA.O_REL_AC_NO;
            IBS.init(SCCGWA, CICQACRI);
            CICQACRI.FUNC = 'A';
            CICQACRI.DATA.AGR_NO = CMCSIQAC.I_CUS_AC;
            S000_CALL_CIZQACRI();
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CPN_NM = CICQACRI.O_DATA.O_AC_CNM;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CPN_ENM = CICQACRI.O_DATA.O_AC_ENM;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CI_OPE_BR = CICQACRI.O_DATA.O_OPN_BR;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_ACR_STSW = CICQACRI.O_DATA.O_STSW;
            if (CICQACRI.O_DATA.O_FRM_APP_OLD.trim().length() > 0) {
                CMCSIQAC.OUT_INF.BAS_INF.BAS_FRM_APP = CICQACRI.O_DATA.O_FRM_APP_OLD;
            } else {
                CMCSIQAC.OUT_INF.BAS_INF.BAS_FRM_APP = CICQACRI.O_DATA.O_FRM_APP;
            }
            CMCSIQAC.OUT_INF.BAS_INF.BAS_ENTY_TYP = CICQACRI.O_DATA.O_ENTY_TYP;
            if (CICQACRI.O_DATA.O_CNTRCT_TYP.equalsIgnoreCase("IBDD") 
                || CICQACRI.O_DATA.O_CNTRCT_TYP.equalsIgnoreCase("IBTD")) {
                CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_AC_TYP = CICQACRI.O_DATA.O_CNTRCT_TYP;
            }
        }
        if (!CMCSIQAC.OUT_INF.BAS_INF.BAS_FRM_APP.equalsIgnoreCase("AI")) {
            IBS.init(SCCGWA, CICCUST);
            CICCUST.FUNC = 'A';
            CICCUST.DATA.AGR_NO = CMCSIQAC.I_CUS_AC;
            S000_CALL_CIZCUST();
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CI_ID_TYP = CICCUST.O_DATA.O_ID_TYPE;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CI_ID_NO = CICCUST.O_DATA.O_ID_NO;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CI_NO = CICCUST.O_DATA.O_CI_NO;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CI_NM = CICCUST.O_DATA.O_CI_NM;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_TEL_NO = CICCUST.O_DATA.O_TEL_NO;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CI_TYP = CICCUST.O_DATA.O_CI_TYP;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CI_STSW = CICCUST.O_DATA.O_STSW;
            CMCSIQAC.OUT_INF.BAS_INF.RESIDENT = CICCUST.O_DATA.O_RESIDENT;
            CMCSIQAC.OUT_INF.BAS_INF.OPEN_DT = CICCUST.O_DATA.O_OPEN_DT;
            CMCSIQAC.OUT_INF.BAS_INF.REG_CNTY = CICCUST.O_DATA.O_REG_CNTY;
            CMCSIQAC.OUT_INF.BAS_INF.SID_FLG = CICCUST.O_DATA.O_SID_FLG;
            if (CMCSIQAC.OUT_INF.BAS_INF.BAS_CI_TYP == '1') {
                CMCSIQAC.OUT_INF.BAS_INF.BAS_CPN_NM = CMCSIQAC.OUT_INF.BAS_INF.BAS_CI_NM;
            }
        }
    }
    public void B300_INQ_CUS_AC_INF_PROC() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_FRM_APP);
        CEP.TRC(SCCGWA, WS_OLD_CUS_AC);
        CEP.TRC(SCCGWA, WS_REL_CUS_AC);
        CEP.TRC(SCCGWA, CMCSIQAC.I_CUS_AC);
        if (CMCSIQAC.OUT_INF.BAS_INF.BAS_FRM_APP.equalsIgnoreCase("DC")) {
            B320_INQ_DC_CUS_AC();
        } else if (CMCSIQAC.OUT_INF.BAS_INF.BAS_FRM_APP.equalsIgnoreCase("DD")) {
            B330_INQ_DD_CUS_AC();
        } else if (CMCSIQAC.OUT_INF.BAS_INF.BAS_FRM_APP.equalsIgnoreCase("TD")) {
            B340_INQ_TD_CUS_AC();
        } else if (CMCSIQAC.OUT_INF.BAS_INF.BAS_FRM_APP.equalsIgnoreCase("IB")) {
            B350_INQ_IB_CUS_AC();
        } else if (CMCSIQAC.OUT_INF.BAS_INF.BAS_FRM_APP.equalsIgnoreCase("AI")) {
            B360_INQ_AI_CUS_AC();
        } else if (CMCSIQAC.OUT_INF.BAS_INF.BAS_FRM_APP.equalsIgnoreCase("LN")) {
        } else {
            CEP.ERR(SCCGWA, CMCMSG_ERROR_MSG.CM_AC_TYP_ERR);
        }
    }
    public void B320_INQ_DC_CUS_AC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, DCCUCINF);
        DCCUCINF.CARD_NO = CMCSIQAC.I_CUS_AC;
        S000_CALL_DCZUCINF();
        CMCSIQAC.OUT_INF.DC_INF.DC_CARD_NO = DCCUCINF.CARD_NO;
        CMCSIQAC.OUT_INF.DC_INF.DC_PROD_CD = DCCUCINF.PROD_CD;
        CMCSIQAC.OUT_INF.DC_INF.DC_CD_MEDI = DCCUCINF.CARD_MEDI;
        CMCSIQAC.OUT_INF.DC_INF.DC_CD_STS = DCCUCINF.CARD_STS;
        CMCSIQAC.OUT_INF.DC_INF.DC_CD_STSW = DCCUCINF.CARD_STSW;
        CMCSIQAC.OUT_INF.DC_INF.DC_OPE_DT = DCCUCINF.ISSU_DT;
        CMCSIQAC.OUT_INF.DC_INF.DC_OPE_BR = DCCUCINF.ISSU_BR;
        CMCSIQAC.OUT_INF.DC_INF.DC_CLT_BR = DCCUCINF.CLT_BR;
        CMCSIQAC.OUT_INF.DC_INF.DC_BV_CODE = DCCUCINF.BV_CD_NO;
        if (DCCUCINF.CARD_NO == null) DCCUCINF.CARD_NO = "";
        JIBS_tmp_int = DCCUCINF.CARD_NO.length();
        for (int i=0;i<19-JIBS_tmp_int;i++) DCCUCINF.CARD_NO += " ";
        CMCSIQAC.OUT_INF.DC_INF.DC_BV_NO = DCCUCINF.CARD_NO.substring(0, 18);
        CMCSIQAC.OUT_INF.DC_INF.DC_LNK_TYP = DCCUCINF.CARD_LNK_TYP;
        CMCSIQAC.OUT_INF.DC_INF.DC_AC_TYP = "" + DCCUCINF.AC_TYP;
        JIBS_tmp_int = CMCSIQAC.OUT_INF.DC_INF.DC_AC_TYP.length();
        for (int i=0;i<1-JIBS_tmp_int;i++) CMCSIQAC.OUT_INF.DC_INF.DC_AC_TYP = "0" + CMCSIQAC.OUT_INF.DC_INF.DC_AC_TYP;
        CMCSIQAC.OUT_INF.DC_INF.DC_EXP_DT = DCCUCINF.EXP_DT;
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DC_INF.DC_AC_TYP);
        CEP.TRC(SCCGWA, DCCUCINF.OPEN_CHNL);
        CMCSIQAC.OUT_INF.DC_INF.DC_OPEN_CHNL = DCCUCINF.OPEN_CHNL;
        CMCSIQAC.OUT_INF.DC_INF.DC_ADSC_TYPE = DCCUCINF.ADSC_TYPE;
        if (CMCSIQAC.OUT_INF.DC_INF.DC_CD_STSW == null) CMCSIQAC.OUT_INF.DC_INF.DC_CD_STSW = "";
        JIBS_tmp_int = CMCSIQAC.OUT_INF.DC_INF.DC_CD_STSW.length();
        for (int i=0;i<99-JIBS_tmp_int;i++) CMCSIQAC.OUT_INF.DC_INF.DC_CD_STSW += " ";
        if (CMCSIQAC.OUT_INF.DC_INF.DC_CD_STSW == null) CMCSIQAC.OUT_INF.DC_INF.DC_CD_STSW = "";
        JIBS_tmp_int = CMCSIQAC.OUT_INF.DC_INF.DC_CD_STSW.length();
        for (int i=0;i<99-JIBS_tmp_int;i++) CMCSIQAC.OUT_INF.DC_INF.DC_CD_STSW += " ";
        if (CMCSIQAC.OUT_INF.DC_INF.DC_CD_STSW.substring(0, 1).equalsIgnoreCase("1") 
            || CMCSIQAC.OUT_INF.DC_INF.DC_CD_STSW.substring(2 - 1, 2 + 1 - 1).equalsIgnoreCase("1")) {
            CMCSIQAC.OUT_INF.BAS_INF.BAS_LOST_FLG = '1';
        } else {
            CMCSIQAC.OUT_INF.BAS_INF.BAS_LOST_FLG = '0';
        }
    }
    public void B330_INQ_DD_CUS_AC() throws IOException,SQLException,Exception {
        if (CMCSIQAC.OUT_INF.BAS_INF.BAS_ENTY_TYP == '4') {
            B332_INQ_VIRTUAL_DD_CUS_AC();
        } else {
            B331_INQ_NORMAL_DD_CUS_AC();
        }
        if (CMCSIQAC.OUT_INF.BAS_INF.BAS_ADD_INF.BAS_DWK_FLG == '1') {
            CMCSIQAC.I_CUS_AC = WS_OLD_CUS_AC;
            B320_INQ_DC_CUS_AC();
            CMCSIQAC.I_CUS_AC = WS_REL_CUS_AC;
        }
    }
    public void B331_INQ_NORMAL_DD_CUS_AC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, DDCIMMST);
        DDCIMMST.TX_TYPE = 'I';
        DDCIMMST.DATA.KEY.AC_NO = CMCSIQAC.I_CUS_AC;
        S000_CALL_DDZIMMST();
        CMCSIQAC.OUT_INF.DD_INF.DD_CUS_AC = DDCIMMST.DATA.KEY.AC_NO;
        CMCSIQAC.OUT_INF.DD_INF.DD_CUS_STS = DDCIMMST.DATA.AC_STS;
        CMCSIQAC.OUT_INF.DD_INF.DD_CUS_AC_TYP = "" + DDCIMMST.DATA.AC_TYPE;
        JIBS_tmp_int = CMCSIQAC.OUT_INF.DD_INF.DD_CUS_AC_TYP.length();
        for (int i=0;i<1-JIBS_tmp_int;i++) CMCSIQAC.OUT_INF.DD_INF.DD_CUS_AC_TYP = "0" + CMCSIQAC.OUT_INF.DD_INF.DD_CUS_AC_TYP;
        CMCSIQAC.OUT_INF.DD_INF.DD_DRW_TYP = DDCIMMST.DATA.PAY_TYPE;
        CMCSIQAC.OUT_INF.DD_INF.DD_CUS_OPE_BR = DDCIMMST.DATA.OPEN_DP;
        CMCSIQAC.OUT_INF.DD_INF.DD_CUS_OWN_BR = DDCIMMST.DATA.OWNER_BR;
        CMCSIQAC.OUT_INF.DD_INF.DD_UEW_FLG = DDCIMMST.DATA.CROS_DR_FLG;
        CMCSIQAC.OUT_INF.DD_INF.DD_CR_FLG = DDCIMMST.DATA.CROS_CR_FLG;
        CMCSIQAC.OUT_INF.DD_INF.DD_CUS_STSW = DDCIMMST.DATA.AC_STS_WORD;
        CMCSIQAC.OUT_INF.DD_INF.DD_CASH_FLG = DDCIMMST.DATA.CASH_FLG;
        CMCSIQAC.OUT_INF.DD_INF.DD_BV_NO = DDCIMMST.DATA.PSBK_NO;
        CMCSIQAC.OUT_INF.DD_INF.DD_PROD_CD = DDCIMMST.DATA.PROD_CODE;
        CMCSIQAC.OUT_INF.DD_INF.DD_FRG_CODE = DDCIMMST.DATA.FRG_CODE;
        CMCSIQAC.OUT_INF.DD_INF.DD_YW_TYP = DDCIMMST.DATA.YW_TYP;
        CMCSIQAC.OUT_INF.DD_INF.DD_ACC_CODE = DDCIMMST.DATA.AC_TYPE;
        CMCSIQAC.OUT_INF.DD_INF.DD_CUS_OWN_BR = DDCIMMST.DATA.OWNER_BR;
        CMCSIQAC.OUT_INF.DD_INF.DD_BV_TYP = DDCIMMST.DATA.BV_TYPE;
        if (CMCSIQAC.OUT_INF.BAS_INF.BAS_ENTY_TYP != '3') {
            CMCSIQAC.OUT_INF.DD_INF.DD_CCY = CICQACRI.O_DATA.O_CCY;
        }
        CMCSIQAC.OUT_INF.DD_INF.DD_PROD_CD = DDCIMMST.DATA.PROD_CODE;
        CMCSIQAC.OUT_INF.DD_INF.DD_OPE_DT = DDCIMMST.DATA.OPEN_DATE;
        CMCSIQAC.OUT_INF.DD_INF.DD_EXP_DATE = DDCIMMST.DATA.EXP_DATE;
        if (CMCSIQAC.OUT_INF.DD_INF.DD_CUS_STSW == null) CMCSIQAC.OUT_INF.DD_INF.DD_CUS_STSW = "";
        JIBS_tmp_int = CMCSIQAC.OUT_INF.DD_INF.DD_CUS_STSW.length();
        for (int i=0;i<99-JIBS_tmp_int;i++) CMCSIQAC.OUT_INF.DD_INF.DD_CUS_STSW += " ";
        if (CMCSIQAC.OUT_INF.DD_INF.DD_CUS_STSW == null) CMCSIQAC.OUT_INF.DD_INF.DD_CUS_STSW = "";
        JIBS_tmp_int = CMCSIQAC.OUT_INF.DD_INF.DD_CUS_STSW.length();
        for (int i=0;i<99-JIBS_tmp_int;i++) CMCSIQAC.OUT_INF.DD_INF.DD_CUS_STSW += " ";
        if (CMCSIQAC.OUT_INF.DD_INF.DD_CUS_STSW == null) CMCSIQAC.OUT_INF.DD_INF.DD_CUS_STSW = "";
        JIBS_tmp_int = CMCSIQAC.OUT_INF.DD_INF.DD_CUS_STSW.length();
        for (int i=0;i<99-JIBS_tmp_int;i++) CMCSIQAC.OUT_INF.DD_INF.DD_CUS_STSW += " ";
        if (CMCSIQAC.OUT_INF.DD_INF.DD_CUS_STSW.substring(7 - 1, 7 + 1 - 1).equalsIgnoreCase("1") 
            || CMCSIQAC.OUT_INF.DD_INF.DD_CUS_STSW.substring(8 - 1, 8 + 1 - 1).equalsIgnoreCase("1") 
            || CMCSIQAC.OUT_INF.DD_INF.DD_CUS_STSW.substring(9 - 1, 9 + 1 - 1).equalsIgnoreCase("1")) {
            CMCSIQAC.OUT_INF.BAS_INF.BAS_LOST_FLG = '1';
        } else {
            CMCSIQAC.OUT_INF.BAS_INF.BAS_LOST_FLG = '0';
        }
        IBS.init(SCCGWA, DDCUVCH);
        DDCUVCH.FUNC = '2';
        DDCUVCH.KEY.CUS_AC = CMCSIQAC.I_CUS_AC;
        S000_CALL_DDZUVCH();
        if (DDCUVCH.EXIST_FLG == 'Y') {
            CMCSIQAC.OUT_INF.DD_INF.DD_PSBK_STS = DDCUVCH.PSBK_STS;
            CMCSIQAC.OUT_INF.DD_INF.DD_VCH_TYPE = DDCUVCH.KEY.VCH_TYPE;
            CMCSIQAC.OUT_INF.DD_INF.DD_PSBK_NO = DDCUVCH.PSBK_NO;
            CMCSIQAC.OUT_INF.DD_INF.DD_LOST_NO = DDCUVCH.LOST_NO;
        }
    }
    public void B332_INQ_VIRTUAL_DD_CUS_AC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, DDCUINVS);
        DDCUINVS.I_FUNC = '4';
        DDCUINVS.VS_AC = CMCSIQAC.I_CUS_AC;
        S000_CALL_DDZUINVS();
        CMCSIQAC.OUT_INF.DD_INF.DD_CUS_AC = DDCUINVS.VS_AC;
        CMCSIQAC.OUT_INF.BAS_INF.BAS_CPN_NM = DDCUINVS.O_AC_NAME;
        CMCSIQAC.OUT_INF.DD_INF.DD_DRW_TYP = DDCUINVS.O_DRAW_MTH;
        CMCSIQAC.OUT_INF.DD_INF.DD_CCY = DDCUINVS.O_CCY;
        CMCSIQAC.OUT_INF.DD_INF.DD_CCY_TYP = DDCUINVS.O_CCY_TYP;
        CMCSIQAC.OUT_INF.DD_INF.DD_CUS_STS = DDCUINVS.VS_STS;
        CMCSIQAC.OUT_INF.DD_INF.DD_CUS_OWN_BR = DDCUINVS.O_OWNER_BR;
        CMCSIQAC.OUT_INF.DD_INF.DD_CUS_OPE_BR = DDCUINVS.O_ACO_OPE_BR;
        CMCSIQAC.OUT_INF.DD_INF.DD_ACO_STS = DDCUINVS.O_ACO_STS;
        CMCSIQAC.OUT_INF.DD_INF.DD_ACO_STSW = DDCUINVS.O_ACO_STSW;
        CMCSIQAC.OUT_INF.DD_INF.DD_ACO_OPE_BR = DDCUINVS.O_ACO_OPE_BR;
        CMCSIQAC.OUT_INF.DD_INF.DD_ACO_OWN_BR = DDCUINVS.O_OWNER_BR;
        CMCSIQAC.OUT_INF.DD_INF.DD_LAST_BAL = DDCUINVS.O_LAST_BAL;
        CMCSIQAC.OUT_INF.DD_INF.DD_AVA_BAL = DDCUINVS.O_AVA_BAL;
        CMCSIQAC.OUT_INF.DD_INF.DD_CUR_BAL = DDCUINVS.O_CUR_BAL;
        CMCSIQAC.OUT_INF.DD_INF.DD_CUS_STSW = "ZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZEROZERO";
    }
    public void B340_INQ_TD_CUS_AC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, TDCACE);
        TDCACE.PAGE_INF.AC_NO = CMCSIQAC.I_CUS_AC;
        TDCACE.PAGE_INF.AC_STS = 'A';
        S000_CALL_TDZACE();
        CMCSIQAC.OUT_INF.TD_INF.TD_CUS_AC = TDCACE.PAGE_INF.AC_NO;
        CMCSIQAC.OUT_INF.TD_INF.TD_CUS_STS = TDCACE.PAGE_INF.AC_STS;
        CMCSIQAC.OUT_INF.TD_INF.TD_CUS_STSW = TDCACE.PAGE_INF.STSW;
        CMCSIQAC.OUT_INF.TD_INF.TD_CR_FLG = TDCACE.PAGE_INF.CROS_CR_FLG;
        CMCSIQAC.OUT_INF.TD_INF.TD_UEW_FLG = TDCACE.PAGE_INF.CROS_DR_FLG;
        CMCSIQAC.OUT_INF.TD_INF.TD_DRW_TYP = TDCACE.PAGE_INF.DRAW_MTH;
        CEP.TRC(SCCGWA, TDCACE.PAGE_INF.AC_STS);
        CEP.TRC(SCCGWA, TDCACE.PAGE_INF.DRAW_MTH);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_DRW_TYP);
        CMCSIQAC.OUT_INF.TD_INF.TD_MPROD_CD = TDCACE.PAGE_INF.MPROD_CD;
        CMCSIQAC.OUT_INF.TD_INF.TD_CUS_AC_TYP = TDCACE.DATA[1-1].AC_TYP;
        CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_AC_TYP = TDCACE.DATA[1-1].AC_TYP;
        CMCSIQAC.OUT_INF.TD_INF.TD_CUS_OWN_BR = TDCACE.DATA[1-1].OWN_BR;
        CMCSIQAC.OUT_INF.TD_INF.TD_CUS_OPE_BR = TDCACE.DATA[1-1].OPEN_BR;
        CMCSIQAC.OUT_INF.TD_INF.TD_FC_CD = TDCACE.DATA[1-1].FC_CD;
        if (CMCSIQAC.OUT_INF.BAS_INF.BAS_ENTY_TYP != '3') {
            CMCSIQAC.OUT_INF.TD_INF.TD_CCY = TDCACE.DATA[1-1].CCY;
            CMCSIQAC.OUT_INF.TD_INF.TD_CCY_TYP = TDCACE.DATA[1-1].CCY_TYP;
        }
        if (CMCSIQAC.OUT_INF.TD_INF.TD_CUS_STSW == null) CMCSIQAC.OUT_INF.TD_INF.TD_CUS_STSW = "";
        JIBS_tmp_int = CMCSIQAC.OUT_INF.TD_INF.TD_CUS_STSW.length();
        for (int i=0;i<99-JIBS_tmp_int;i++) CMCSIQAC.OUT_INF.TD_INF.TD_CUS_STSW += " ";
        if (CMCSIQAC.OUT_INF.TD_INF.TD_CUS_STSW == null) CMCSIQAC.OUT_INF.TD_INF.TD_CUS_STSW = "";
        JIBS_tmp_int = CMCSIQAC.OUT_INF.TD_INF.TD_CUS_STSW.length();
        for (int i=0;i<99-JIBS_tmp_int;i++) CMCSIQAC.OUT_INF.TD_INF.TD_CUS_STSW += " ";
        if (CMCSIQAC.OUT_INF.TD_INF.TD_CUS_STSW == null) CMCSIQAC.OUT_INF.TD_INF.TD_CUS_STSW = "";
        JIBS_tmp_int = CMCSIQAC.OUT_INF.TD_INF.TD_CUS_STSW.length();
        for (int i=0;i<99-JIBS_tmp_int;i++) CMCSIQAC.OUT_INF.TD_INF.TD_CUS_STSW += " ";
        if (CMCSIQAC.OUT_INF.TD_INF.TD_CUS_STSW.substring(2 - 1, 2 + 1 - 1).equalsIgnoreCase("1") 
            || CMCSIQAC.OUT_INF.TD_INF.TD_CUS_STSW.substring(3 - 1, 3 + 1 - 1).equalsIgnoreCase("1") 
            || CMCSIQAC.OUT_INF.TD_INF.TD_CUS_STSW.substring(7 - 1, 7 + 1 - 1).equalsIgnoreCase("1")) {
            CMCSIQAC.OUT_INF.BAS_INF.BAS_LOST_FLG = '1';
        } else {
            CMCSIQAC.OUT_INF.BAS_INF.BAS_LOST_FLG = '0';
        }
        CMCSIQAC.OUT_INF.TD_INF.TD_BV_CODE = TDCACE.DATA[01-1].BV_CD;
        CMCSIQAC.OUT_INF.TD_INF.TD_BV_TYP = TDCACE.DATA[01-1].BV_TYP;
        CMCSIQAC.OUT_INF.TD_INF.TD_BV_NO = TDCACE.DATA[01-1].BV_NO;
    }
    public void B350_INQ_IB_CUS_AC() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, IBCQINF);
        IBS.init(SCCGWA, IBCQINFT);
        if (CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_AC_TYP.equalsIgnoreCase("IBDD")) {
            IBCQINF.INPUT_DATA.AC_NO = CMCSIQAC.I_CUS_AC;
            S000_CALL_IBZQINF();
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_STS = IBCQINF.OUTPUT_DATA.AC_STS;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_STSW = IBCQINF.OUTPUT_DATA.AC_STATUS;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_OPE_BR = IBCQINF.OUTPUT_DATA.OPEN_BR;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CUR_BAL = IBCQINF.OUTPUT_DATA.VALUE_BAL;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_LAST_BAL = IBCQINF.OUTPUT_DATA.L_VALUE_BAL;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_OWN_BR = IBCQINF.OUTPUT_DATA.POST_ACT_CTR;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_ACO_OWN_BR = IBCQINF.OUTPUT_DATA.POST_ACT_CTR;
        } else if (CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_AC_TYP.equalsIgnoreCase("IBTD")) {
            IBCQINFT.AC_NO = CMCSIQAC.I_CUS_AC;
            S000_CALL_IBZQINFT();
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_STS = IBCQINFT.AC_STS;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_OPE_BR = IBCQINFT.OPEN_BR;
        } else {
            CEP.ERR(SCCGWA, CMCMSG_ERROR_MSG.CM_IBAC_TYP_ERR);
        }
    }
    public void B360_INQ_AI_CUS_AC() throws IOException,SQLException,Exception {
        WS_MIB_CHK_FLG = 'Y';
        IBS.init(SCCGWA, AICPQMIB);
        AICPQMIB.INPUT_DATA.AC = CMCSIQAC.I_CUS_AC;
        S000_CALL_AIZPQMIB();
        CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_AC = AICPQMIB.INPUT_DATA.AC;
        CMCSIQAC.OUT_INF.BAS_INF.BAS_CPN_NM = AICPQMIB.OUTPUT_DATA.CHS_NM;
        CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_AC_TYP = "" + AICPQMIB.OUTPUT_DATA.AC_TYP;
        JIBS_tmp_int = CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_AC_TYP.length();
        for (int i=0;i<1-JIBS_tmp_int;i++) CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_AC_TYP = "0" + CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_AC_TYP;
        CMCSIQAC.OUT_INF.BAS_INF.BAS_CCY = AICPQMIB.INPUT_DATA.CCY;
        CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_STS = AICPQMIB.OUTPUT_DATA.STS;
        CMCSIQAC.OUT_INF.BAS_INF.BAS_LAST_BAL = AICPQMIB.OUTPUT_DATA.LBAL;
        CMCSIQAC.OUT_INF.BAS_INF.BAS_AVA_BAL = AICPQMIB.OUTPUT_DATA.CBAL;
        CMCSIQAC.OUT_INF.BAS_INF.BAS_CUR_BAL = AICPQMIB.OUTPUT_DATA.CBAL;
        if (AICPQMIB.INPUT_DATA.AC == null) AICPQMIB.INPUT_DATA.AC = "";
        JIBS_tmp_int = AICPQMIB.INPUT_DATA.AC.length();
        for (int i=0;i<32-JIBS_tmp_int;i++) AICPQMIB.INPUT_DATA.AC += " ";
        if (AICPQMIB.INPUT_DATA.AC.substring(0, 6).trim().length() == 0) CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_OPE_BR = 0;
        else CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_OPE_BR = Integer.parseInt(AICPQMIB.INPUT_DATA.AC.substring(0, 6));
        if (AICPQMIB.INPUT_DATA.AC.substring(0, 6).trim().length() == 0) CMCSIQAC.OUT_INF.BAS_INF.BAS_ACO_OPE_BR = 0;
        else CMCSIQAC.OUT_INF.BAS_INF.BAS_ACO_OPE_BR = Integer.parseInt(AICPQMIB.INPUT_DATA.AC.substring(0, 6));
        if (AICPQMIB.INPUT_DATA.AC == null) AICPQMIB.INPUT_DATA.AC = "";
        JIBS_tmp_int = AICPQMIB.INPUT_DATA.AC.length();
        for (int i=0;i<32-JIBS_tmp_int;i++) AICPQMIB.INPUT_DATA.AC += " ";
        if (AICPQMIB.INPUT_DATA.AC.substring(0, 6).trim().length() == 0) CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_OWN_BR = 0;
        else CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_OWN_BR = Integer.parseInt(AICPQMIB.INPUT_DATA.AC.substring(0, 6));
        if (AICPQMIB.INPUT_DATA.AC.substring(0, 6).trim().length() == 0) CMCSIQAC.OUT_INF.BAS_INF.BAS_ACO_OWN_BR = 0;
        else CMCSIQAC.OUT_INF.BAS_INF.BAS_ACO_OWN_BR = Integer.parseInt(AICPQMIB.INPUT_DATA.AC.substring(0, 6));
    }
    public void B400_INQ_ACO_NO_INF_PROC() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_FRM_APP);
        CEP.TRC(SCCGWA, CMCSIQAC.I_AC_SEQ);
        if (CMCSIQAC.OUT_INF.BAS_INF.BAS_FRM_APP.equalsIgnoreCase("DC")) {
            if (CMCSIQAC.I_AC_SEQ == 0) {
                B420_INQ_DD_ACO_NO();
            } else {
                B440_INQ_TD_ACO_NO();
            }
        } else if (CMCSIQAC.OUT_INF.BAS_INF.BAS_FRM_APP.equalsIgnoreCase("DD")) {
            B420_INQ_DD_ACO_NO();
        } else if (CMCSIQAC.OUT_INF.BAS_INF.BAS_FRM_APP.equalsIgnoreCase("TD")) {
            B440_INQ_TD_ACO_NO();
        } else if (CMCSIQAC.OUT_INF.BAS_INF.BAS_FRM_APP.equalsIgnoreCase("IB")) {
        } else if (CMCSIQAC.OUT_INF.BAS_INF.BAS_FRM_APP.equalsIgnoreCase("AI")) {
            if (WS_MIB_CHK_FLG != 'Y') {
                B360_INQ_AI_CUS_AC();
            }
        } else if (CMCSIQAC.OUT_INF.BAS_INF.BAS_FRM_APP.equalsIgnoreCase("LN")) {
            B450_INQ_LN_ACO_NO();
        } else {
            CEP.ERR(SCCGWA, CMCMSG_ERROR_MSG.CM_AC_TYP_ERR);
        }
    }
    public void B450_INQ_LN_ACO_NO() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, CICQACAC);
        CICQACAC.FUNC = 'R';
        CICQACAC.DATA.AGR_NO = CMCSIQAC.I_CUS_AC;
        CICQACAC.DATA.AGR_SEQ = CMCSIQAC.I_AC_SEQ;
        CICQACAC.DATA.CCY_ACAC = CMCSIQAC.I_CCY;
        CICQACAC.DATA.CR_FLG = CMCSIQAC.I_CCY_TYP;
        CICQACAC.DATA.BV_NO = CMCSIQAC.I_BV_NO;
        CEP.TRC(SCCGWA, "NCBZXJ180412-1");
        CEP.TRC(SCCGWA, CICQACAC.DATA.AGR_NO);
        CEP.TRC(SCCGWA, CICQACAC.DATA.AGR_SEQ);
        CEP.TRC(SCCGWA, CICQACAC.DATA.CCY_ACAC);
        CEP.TRC(SCCGWA, CICQACAC.DATA.CR_FLG);
        CEP.TRC(SCCGWA, CICQACAC.DATA.BV_NO);
        S000_CALL_CIZQACAC();
        CMCSIQAC.OUT_INF.BAS_INF.BAS_ACO_NO = CICQACAC.O_DATA.O_ACAC_DATA.O_ACAC_NO;
        CMCSIQAC.OUT_INF.BAS_INF.BAS_AC_SEQ = CICQACAC.O_DATA.O_ACAC_DATA.O_AGR_SEQ;
        CMCSIQAC.OUT_INF.BAS_INF.BAS_CCY = CICQACAC.O_DATA.O_ACAC_DATA.O_CCY_ACAC;
        CMCSIQAC.OUT_INF.BAS_INF.BAS_CCY_TYP = CICQACAC.O_DATA.O_ACAC_DATA.O_CR_FLG;
        CMCSIQAC.OUT_INF.BAS_INF.BAS_BV_NO = CICQACAC.O_DATA.O_ACAC_DATA.O_BV_NO;
        CEP.TRC(SCCGWA, "NCBZXJ180412-2");
        CEP.TRC(SCCGWA, CICQACAC.O_DATA.O_ACAC_DATA.O_ACAC_NO);
        CEP.TRC(SCCGWA, CICQACAC.O_DATA.O_ACAC_DATA.O_AGR_SEQ);
        CEP.TRC(SCCGWA, CICQACAC.O_DATA.O_ACAC_DATA.O_CCY_ACAC);
        CEP.TRC(SCCGWA, CICQACAC.O_DATA.O_ACAC_DATA.O_CR_FLG);
        CEP.TRC(SCCGWA, CICQACAC.O_DATA.O_ACAC_DATA.O_BV_NO);
    }
    public void B420_INQ_DD_ACO_NO() throws IOException,SQLException,Exception {
        if ((CMCSIQAC.I_CCY.trim().length() == 0 
            || CMCSIQAC.I_CCY.charAt(0) == 0X00)) {
            CEP.ERR(SCCGWA, CMCMSG_ERROR_MSG.CM_CCY_INP_ERR);
        }
        if (CMCSIQAC.I_CCY.equalsIgnoreCase("156") 
            && (CMCSIQAC.I_CCY_TYP == ' ' 
            || CMCSIQAC.I_CCY_TYP == 0X00)) {
            CEP.ERR(SCCGWA, CMCMSG_ERROR_MSG.CM_CCY_TYP_INP_ERR);
        }
        if (CMCSIQAC.OUT_INF.BAS_INF.BAS_ENTY_TYP != '4') {
            IBS.init(SCCGWA, DDCIQBAL);
            DDCIQBAL.DATA.AC = CMCSIQAC.I_CUS_AC;
            DDCIQBAL.DATA.CCY = CMCSIQAC.I_CCY;
            DDCIQBAL.DATA.CCY_TYPE = CMCSIQAC.I_CCY_TYP;
            S000_CALL_DDZIQBAL();
            CMCSIQAC.OUT_INF.DD_INF.DD_ACO_OWN_BR = DDCIQBAL.DATA.OWNER_BR;
            CMCSIQAC.OUT_INF.DC_INF.DC_ACO_OWN_BR = DDCIQBAL.DATA.OWNER_BR;
            CMCSIQAC.OUT_INF.DD_INF.DD_ACO_STS = DDCIQBAL.DATA.CCY_STS;
            CMCSIQAC.OUT_INF.DC_INF.DC_ACO_STS = DDCIQBAL.DATA.CCY_STS;
            CMCSIQAC.OUT_INF.DD_INF.DD_ACO_STSW = DDCIQBAL.DATA.CCY_STS_WORD;
            CMCSIQAC.OUT_INF.DC_INF.DC_ACO_STSW = DDCIQBAL.DATA.CCY_STS_WORD;
            CMCSIQAC.OUT_INF.DD_INF.DD_CCY = DDCIQBAL.DATA.CCY;
            CMCSIQAC.OUT_INF.DC_INF.DC_CCY = DDCIQBAL.DATA.CCY;
            CMCSIQAC.OUT_INF.DD_INF.DD_CCY_TYP = DDCIQBAL.DATA.CCY_TYPE;
            CMCSIQAC.OUT_INF.DC_INF.DC_CCY_TYP = DDCIQBAL.DATA.CCY_TYPE;
            CMCSIQAC.OUT_INF.DD_INF.DD_AVA_BAL = DDCIQBAL.DATA.AVL_BAL;
            CMCSIQAC.OUT_INF.DC_INF.DC_AVA_BAL = DDCIQBAL.DATA.AVL_BAL;
            CMCSIQAC.OUT_INF.DD_INF.DD_LAST_BAL = DDCIQBAL.DATA.LAST_BAL;
            CMCSIQAC.OUT_INF.DC_INF.DC_LAST_BAL = DDCIQBAL.DATA.LAST_BAL;
            CMCSIQAC.OUT_INF.DD_INF.DD_CUR_BAL = DDCIQBAL.DATA.CURR_BAL;
            CMCSIQAC.OUT_INF.DC_INF.DC_CUR_BAL = DDCIQBAL.DATA.CURR_BAL;
            CMCSIQAC.OUT_INF.DD_INF.DD_AC_TYPE = "" + DDCIQBAL.DATA.AC_TYPE;
            JIBS_tmp_int = CMCSIQAC.OUT_INF.DD_INF.DD_AC_TYPE.length();
            for (int i=0;i<1-JIBS_tmp_int;i++) CMCSIQAC.OUT_INF.DD_INF.DD_AC_TYPE = "0" + CMCSIQAC.OUT_INF.DD_INF.DD_AC_TYPE;
            CMCSIQAC.OUT_INF.DC_INF.DC_AC_TYPE = "" + DDCIQBAL.DATA.AC_TYPE;
            JIBS_tmp_int = CMCSIQAC.OUT_INF.DC_INF.DC_AC_TYPE.length();
            for (int i=0;i<1-JIBS_tmp_int;i++) CMCSIQAC.OUT_INF.DC_INF.DC_AC_TYPE = "0" + CMCSIQAC.OUT_INF.DC_INF.DC_AC_TYPE;
            CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DC_INF.DC_AC_TYPE);
        }
        IBS.init(SCCGWA, CICQACAC);
        CICQACAC.FUNC = 'C';
        CICQACAC.DATA.AGR_NO = CMCSIQAC.I_CUS_AC;
        CICQACAC.DATA.CCY_ACAC = CMCSIQAC.I_CCY;
        CICQACAC.DATA.CR_FLG = CMCSIQAC.I_CCY_TYP;
        S000_CALL_CIZQACAC();
        CMCSIQAC.OUT_INF.DD_INF.DD_ACO_NO = CICQACAC.O_DATA.O_ACAC_DATA.O_ACAC_NO;
        CMCSIQAC.OUT_INF.DC_INF.DC_ACO_NO = CICQACAC.O_DATA.O_ACAC_DATA.O_ACAC_NO;
        CMCSIQAC.OUT_INF.DD_INF.DD_ACO_OPE_BR = CICQACAC.O_DATA.O_ACAC_DATA.O_OPN_BR_ACAC;
        CMCSIQAC.OUT_INF.DC_INF.DC_ACO_OPE_BR = CICQACAC.O_DATA.O_ACAC_DATA.O_OPN_BR_ACAC;
    }
    public void B440_INQ_TD_ACO_NO() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, TDCACE);
        TDCACE.PAGE_INF.AC_NO = CMCSIQAC.I_CUS_AC;
        TDCACE.PAGE_INF.I_AC_SEQ = CMCSIQAC.I_AC_SEQ;
        TDCACE.PAGE_INF.I_BV_NO = CMCSIQAC.I_BV_NO;
        S000_CALL_TDZACE();
        CMCSIQAC.OUT_INF.TD_INF.TD_SDT = TDCACE.DATA[01-1].OPEN_DATE;
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_SDT);
        CMCSIQAC.OUT_INF.TD_INF.TD_AC_SEQ = TDCACE.DATA[01-1].AC_SEQ;
        CMCSIQAC.OUT_INF.DC_INF.DC_AC_SEQ = TDCACE.DATA[01-1].AC_SEQ;
        CMCSIQAC.OUT_INF.TD_INF.TD_ACO_STS = TDCACE.DATA[01-1].ACO_STS;
        CMCSIQAC.OUT_INF.DC_INF.DC_ACO_STS = TDCACE.DATA[01-1].ACO_STS;
        CMCSIQAC.OUT_INF.TD_INF.TD_ACO_STSW = TDCACE.DATA[01-1].DAC_STSW;
        CMCSIQAC.OUT_INF.DC_INF.DC_ACO_STSW = TDCACE.DATA[01-1].DAC_STSW;
        CMCSIQAC.OUT_INF.TD_INF.TD_ACO_NO = TDCACE.DATA[01-1].ACO_AC;
        CMCSIQAC.OUT_INF.DC_INF.DC_ACO_NO = TDCACE.DATA[01-1].ACO_AC;
        CMCSIQAC.OUT_INF.TD_INF.TD_AC_SEQ = TDCACE.PAGE_INF.I_AC_SEQ;
        CMCSIQAC.OUT_INF.DC_INF.DC_AC_SEQ = TDCACE.PAGE_INF.I_AC_SEQ;
        CMCSIQAC.OUT_INF.TD_INF.TD_SDT = TDCACE.DATA[01-1].SDT;
        CMCSIQAC.OUT_INF.DC_INF.DC_SDT = TDCACE.DATA[01-1].SDT;
        CMCSIQAC.OUT_INF.TD_INF.TD_EDT = TDCACE.DATA[01-1].DDT;
        CMCSIQAC.OUT_INF.DC_INF.DC_EDT = TDCACE.DATA[01-1].DDT;
        CMCSIQAC.OUT_INF.TD_INF.TD_TERM_CD = TDCACE.DATA[01-1].TERM;
        CMCSIQAC.OUT_INF.DC_INF.DC_TERM_CD = TDCACE.DATA[01-1].TERM;
        CMCSIQAC.OUT_INF.TD_INF.TD_INT_RAT = TDCACE.DATA[01-1].INT_RAT;
        CMCSIQAC.OUT_INF.DC_INF.DC_INT_RAT = TDCACE.DATA[01-1].INT_RAT;
        CMCSIQAC.OUT_INF.TD_INF.TD_ACO_OPE_BR = TDCACE.DATA[01-1].OPEN_BR;
        CMCSIQAC.OUT_INF.DC_INF.DC_ACO_OPE_BR = TDCACE.DATA[01-1].OPEN_BR;
        CMCSIQAC.OUT_INF.TD_INF.TD_ACO_OWN_BR = TDCACE.DATA[01-1].OWN_BR;
        CMCSIQAC.OUT_INF.DC_INF.DC_ACO_OWN_BR = TDCACE.DATA[01-1].OWN_BR;
        CMCSIQAC.OUT_INF.TD_INF.TD_BV_CODE = TDCACE.DATA[01-1].BV_CD;
        CMCSIQAC.OUT_INF.TD_INF.TD_BV_TYP = TDCACE.DATA[01-1].BV_TYP;
        CMCSIQAC.OUT_INF.TD_INF.TD_BV_NO = TDCACE.DATA[01-1].BV_NO;
        CMCSIQAC.OUT_INF.TD_INF.TD_TDAC_TYP = TDCACE.DATA[01-1].AC_TYP.charAt(0);
        CMCSIQAC.OUT_INF.TD_INF.TD_CUR_BAL = TDCACE.DATA[01-1].BAL;
        CMCSIQAC.OUT_INF.DC_INF.DC_CUR_BAL = TDCACE.DATA[01-1].BAL;
        CMCSIQAC.OUT_INF.TD_INF.TD_AVA_BAL = TDCACE.DATA[01-1].KY_BAL;
        CMCSIQAC.OUT_INF.DC_INF.DC_AVA_BAL = TDCACE.DATA[01-1].KY_BAL;
        CMCSIQAC.OUT_INF.TD_INF.TD_DRW_FLG = TDCACE.DATA[01-1].PREV_FLG;
        CMCSIQAC.OUT_INF.TD_INF.TD_CCY = TDCACE.DATA[01-1].CCY;
        CMCSIQAC.OUT_INF.DC_INF.DC_CCY = TDCACE.DATA[01-1].CCY;
        CMCSIQAC.OUT_INF.TD_INF.TD_CCY_TYP = TDCACE.DATA[01-1].CCY_TYP;
        CMCSIQAC.OUT_INF.DC_INF.DC_CCY_TYP = TDCACE.DATA[01-1].CCY_TYP;
    }
    public void B700_CHK_AC_PSWD_PROC() throws IOException,SQLException,Exception {
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_FRM_APP);
        CEP.TRC(SCCGWA, CMCSIQAC.I_PSW);
        if (CMCSIQAC.I_PSW.trim().length() > 0 
            && CMCSIQAC.I_PSW.charAt(0) != 0X00) {
            if (CMCSIQAC.OUT_INF.BAS_INF.BAS_FRM_APP.equalsIgnoreCase("DC")) {
                B710_CHK_DC_PSWD();
            } else if (CMCSIQAC.OUT_INF.BAS_INF.BAS_FRM_APP.equalsIgnoreCase("DD")) {
                B720_CHK_DD_PSWD();
            } else if (CMCSIQAC.OUT_INF.BAS_INF.BAS_FRM_APP.equalsIgnoreCase("TD")) {
                B730_CHK_TD_PSWD();
            } else {
                CEP.ERR(SCCGWA, CMCMSG_ERROR_MSG.CM_DDDCTD_PSW_CHK_ERR);
            }
        }
    }
    public void B710_CHK_DC_PSWD() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, DCCPCDCK);
        DCCPCDCK.FUNC_CODE = 'P';
        DCCPCDCK.CARD_NO = CMCSIQAC.I_CUS_AC;
        DCCPCDCK.CARD_PSW = CMCSIQAC.I_PSW;
        S000_CALL_DCZPCDCK();
    }
    public void B720_CHK_DD_PSWD() throws IOException,SQLException,Exception {
        if (CMCSIQAC.OUT_INF.BAS_INF.BAS_ADD_INF.BAS_DWK_FLG == '1') {
            CMCSIQAC.I_CUS_AC = WS_OLD_CUS_AC;
            B710_CHK_DC_PSWD();
            CMCSIQAC.I_CUS_AC = WS_REL_CUS_AC;
        } else {
            IBS.init(SCCGWA, DDCIMPAY);
            DDCIMPAY.FUNC = 'K';
            DDCIMPAY.PAY_MTH = '1';
            DDCIMPAY.AC = CMCSIQAC.I_CUS_AC;
            DDCIMPAY.PSWD_OLD = CMCSIQAC.I_PSW;
            S000_CALL_DDZIMPAY();
        }
    }
    public void B730_CHK_TD_PSWD() throws IOException,SQLException,Exception {
        IBS.init(SCCGWA, TDCACE);
        TDCACE.PAGE_INF.AC_NO = CMCSIQAC.I_CUS_AC;
        TDCACE.PAGE_INF.I_AC_SEQ = CMCSIQAC.I_AC_SEQ;
        TDCACE.PAGE_INF.I_BV_NO = CMCSIQAC.I_BV_NO;
        S000_CALL_TDZACE();
        if (TDCACE.DATA[01-1].AC_TYP.equalsIgnoreCase("021") 
            && CMCSIQAC.OUT_INF.BAS_INF.BAS_CI_TYP == '1') {
            IBS.init(SCCGWA, CICQACRL);
            CICQACRL.FUNC = 'I';
            CICQACRL.DATA.AC_NO = CMCSIQAC.I_CUS_AC;
            CICQACRL.DATA.AC_REL = "07";
            S000_CALL_CIZQACRL();
            IBS.init(SCCGWA, CICQACRI);
            CICQACRI.DATA.AGR_NO = CICQACRL.O_DATA.O_REL_AC_NO;
            CICQACRI.FUNC = 'A';
            S000_CALL_CIZQACRI();
            CEP.TRC(SCCGWA, CICQACRI.O_DATA.O_FRM_APP);
            if (CICQACRI.O_DATA.O_FRM_APP.equalsIgnoreCase("DD")) {
                IBS.init(SCCGWA, DDCIMPAY);
                DDCIMPAY.FUNC = 'K';
                DDCIMPAY.PAY_MTH = '1';
                DDCIMPAY.AC = CICQACRL.O_DATA.O_REL_AC_NO;
                DDCIMPAY.PSWD_OLD = CMCSIQAC.I_PSW;
                S000_CALL_DDZIMPAY();
            } else {
                IBS.init(SCCGWA, DCCPCDCK);
                DCCPCDCK.FUNC_CODE = 'P';
                DCCPCDCK.CARD_NO = CICQACRL.O_DATA.O_REL_AC_NO;
                DCCPCDCK.CARD_PSW = CMCSIQAC.I_PSW;
                S000_CALL_DCZPCDCK();
            }
        } else {
            IBS.init(SCCGWA, TDCACM);
            TDCACM.FUNC = 'C';
            TDCACM.AC_NO = CMCSIQAC.I_CUS_AC;
            TDCACM.OLD_AC_NO = CMCSIQAC.I_CUS_AC;
            TDCACM.CARD_PSW_OLD = CMCSIQAC.I_PSW;
            TDCACM.CARD_PSW_NEW = CMCSIQAC.I_PSW;
            TDCACM.ID_TYP = CMCSIQAC.OUT_INF.BAS_INF.BAS_CI_ID_TYP;
            TDCACM.ID_NO = CMCSIQAC.OUT_INF.BAS_INF.BAS_CI_ID_NO;
            TDCACM.CI_NM = CMCSIQAC.OUT_INF.BAS_INF.BAS_CI_NM;
            S000_CALL_TDZACM();
        }
    }
    public void B800_OUTPUT_MERGER_PROC() throws IOException,SQLException,Exception {
        CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_AC = CMCSIQAC.I_CUS_AC;
        CMCSIQAC.OUT_INF.BAS_INF.BAS_AC_SEQ = CMCSIQAC.I_AC_SEQ;
        CEP.TRC(SCCGWA, "NCBZXJ180412");
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_CCY);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_CCY_TYP);
        CEP.TRC(SCCGWA, CMCSIQAC.I_CCY);
        CEP.TRC(SCCGWA, CMCSIQAC.I_CCY_TYP);
        if (CMCSIQAC.OUT_INF.BAS_INF.BAS_CCY.trim().length() == 0) {
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CCY = CMCSIQAC.I_CCY;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CCY_TYP = CMCSIQAC.I_CCY_TYP;
        }
        if (CMCSIQAC.OUT_INF.BAS_INF.BAS_FRM_APP.equalsIgnoreCase("DC")) {
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_STS = CMCSIQAC.OUT_INF.DC_INF.DC_CD_STS;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_STSW = CMCSIQAC.OUT_INF.DC_INF.DC_CD_STSW;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_OPE_BR = CMCSIQAC.OUT_INF.DC_INF.DC_OPE_BR;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_OWN_BR = CMCSIQAC.OUT_INF.DC_INF.DC_OPE_BR;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_BV_CODE = CMCSIQAC.OUT_INF.DC_INF.DC_BV_CODE;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_BV_NO = CMCSIQAC.OUT_INF.DC_INF.DC_BV_NO;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_AC_SEQ = CMCSIQAC.OUT_INF.DC_INF.DC_AC_SEQ;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CCY = CMCSIQAC.OUT_INF.DC_INF.DC_CCY;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CCY_TYP = CMCSIQAC.OUT_INF.DC_INF.DC_CCY_TYP;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_ACO_NO = CMCSIQAC.OUT_INF.DC_INF.DC_ACO_NO;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_ACO_STS = CMCSIQAC.OUT_INF.DC_INF.DC_ACO_STS;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_ACO_STSW = CMCSIQAC.OUT_INF.DC_INF.DC_ACO_STSW;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_ACO_OPE_BR = CMCSIQAC.OUT_INF.DC_INF.DC_ACO_OPE_BR;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_ACO_OWN_BR = CMCSIQAC.OUT_INF.DC_INF.DC_ACO_OWN_BR;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_LAST_BAL = CMCSIQAC.OUT_INF.DC_INF.DC_LAST_BAL;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_AVA_BAL = CMCSIQAC.OUT_INF.DC_INF.DC_AVA_BAL;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CUR_BAL = CMCSIQAC.OUT_INF.DC_INF.DC_CUR_BAL;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_PROD_CD = CMCSIQAC.OUT_INF.DC_INF.DC_PROD_CD;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_ADD_INF.BAS_AC_KND = CMCSIQAC.OUT_INF.DC_INF.DC_AC_TYP.charAt(0);
            CMCSIQAC.OUT_INF.BAS_INF.BAS_ADD_INF.BAS_OPEN_CHNL = CMCSIQAC.OUT_INF.DC_INF.DC_OPEN_CHNL;
        } else if (CMCSIQAC.OUT_INF.BAS_INF.BAS_FRM_APP.equalsIgnoreCase("DD")) {
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_AC_TYP = CMCSIQAC.OUT_INF.DD_INF.DD_CUS_AC_TYP;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_STS = CMCSIQAC.OUT_INF.DD_INF.DD_CUS_STS;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_STSW = CMCSIQAC.OUT_INF.DD_INF.DD_CUS_STSW;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_OPE_BR = CMCSIQAC.OUT_INF.DD_INF.DD_CUS_OPE_BR;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_OWN_BR = CMCSIQAC.OUT_INF.DD_INF.DD_CUS_OWN_BR;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_BV_TYP = CMCSIQAC.OUT_INF.DD_INF.DD_BV_TYP;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_BV_CODE = CMCSIQAC.OUT_INF.DD_INF.DD_BV_CODE;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_BV_NO = CMCSIQAC.OUT_INF.DD_INF.DD_BV_NO;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_DRW_TYP = CMCSIQAC.OUT_INF.DD_INF.DD_DRW_TYP;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_AC_SEQ = CMCSIQAC.OUT_INF.DD_INF.DD_AC_SEQ;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CCY = CMCSIQAC.OUT_INF.DD_INF.DD_CCY;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CCY_TYP = CMCSIQAC.OUT_INF.DD_INF.DD_CCY_TYP;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_ACO_NO = CMCSIQAC.OUT_INF.DD_INF.DD_ACO_NO;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_ACO_STS = CMCSIQAC.OUT_INF.DD_INF.DD_ACO_STS;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_ACO_STSW = CMCSIQAC.OUT_INF.DD_INF.DD_ACO_STSW;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_ACO_OPE_BR = CMCSIQAC.OUT_INF.DD_INF.DD_ACO_OPE_BR;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_ACO_OWN_BR = CMCSIQAC.OUT_INF.DD_INF.DD_ACO_OWN_BR;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_LAST_BAL = CMCSIQAC.OUT_INF.DD_INF.DD_LAST_BAL;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_AVA_BAL = CMCSIQAC.OUT_INF.DD_INF.DD_AVA_BAL;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CUR_BAL = CMCSIQAC.OUT_INF.DD_INF.DD_CUR_BAL;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_PROD_CD = CMCSIQAC.OUT_INF.DD_INF.DD_PROD_CD;
            if (CMCSIQAC.OUT_INF.BAS_INF.BAS_ADD_INF.BAS_DWK_FLG == '1') {
                CMCSIQAC.OUT_INF.BAS_INF.BAS_FRM_APP = "DC";
                CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_STS = CMCSIQAC.OUT_INF.DC_INF.DC_CD_STS;
                CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_STSW = CMCSIQAC.OUT_INF.DC_INF.DC_CD_STSW;
                CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_OPE_BR = CMCSIQAC.OUT_INF.DC_INF.DC_OPE_BR;
                CMCSIQAC.OUT_INF.BAS_INF.BAS_PROD_CD = CMCSIQAC.OUT_INF.DC_INF.DC_PROD_CD;
                CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_OPE_BR = CMCSIQAC.OUT_INF.DC_INF.DC_OPE_BR;
                CMCSIQAC.OUT_INF.BAS_INF.BAS_BV_CODE = CMCSIQAC.OUT_INF.DC_INF.DC_BV_CODE;
                CMCSIQAC.OUT_INF.BAS_INF.BAS_BV_NO = CMCSIQAC.OUT_INF.DC_INF.DC_BV_NO;
                CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_AC = WS_OLD_CUS_AC;
            }
            if (CMCSIQAC.OUT_INF.DD_INF.DD_CUS_AC_TYP.equalsIgnoreCase("A")) {
                CMCSIQAC.OUT_INF.BAS_INF.BAS_ADD_INF.BAS_AC_KND = '1';
            }
        } else if (CMCSIQAC.OUT_INF.BAS_INF.BAS_FRM_APP.equalsIgnoreCase("TD")) {
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_AC_TYP = CMCSIQAC.OUT_INF.TD_INF.TD_CUS_AC_TYP;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_STS = CMCSIQAC.OUT_INF.TD_INF.TD_CUS_STS;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_STSW = CMCSIQAC.OUT_INF.TD_INF.TD_CUS_STSW;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_OPE_BR = CMCSIQAC.OUT_INF.TD_INF.TD_CUS_OPE_BR;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_OWN_BR = CMCSIQAC.OUT_INF.TD_INF.TD_CUS_OWN_BR;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_BV_TYP = CMCSIQAC.OUT_INF.TD_INF.TD_BV_TYP;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_BV_CODE = CMCSIQAC.OUT_INF.TD_INF.TD_BV_CODE;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_BV_NO = CMCSIQAC.OUT_INF.TD_INF.TD_BV_NO;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_DRW_TYP = CMCSIQAC.OUT_INF.TD_INF.TD_DRW_TYP;
            CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_DRW_TYP);
            CMCSIQAC.OUT_INF.BAS_INF.BAS_AC_SEQ = CMCSIQAC.OUT_INF.TD_INF.TD_AC_SEQ;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CCY = CMCSIQAC.OUT_INF.TD_INF.TD_CCY;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CCY_TYP = CMCSIQAC.OUT_INF.TD_INF.TD_CCY_TYP;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_ACO_NO = CMCSIQAC.OUT_INF.TD_INF.TD_ACO_NO;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_ACO_STS = CMCSIQAC.OUT_INF.TD_INF.TD_ACO_STS;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_ACO_STSW = CMCSIQAC.OUT_INF.TD_INF.TD_ACO_STSW;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_ACO_OPE_BR = CMCSIQAC.OUT_INF.TD_INF.TD_ACO_OPE_BR;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_ACO_OWN_BR = CMCSIQAC.OUT_INF.TD_INF.TD_ACO_OWN_BR;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_LAST_BAL = CMCSIQAC.OUT_INF.TD_INF.TD_LAST_BAL;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_AVA_BAL = CMCSIQAC.OUT_INF.TD_INF.TD_AVA_BAL;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_CUR_BAL = CMCSIQAC.OUT_INF.TD_INF.TD_CUR_BAL;
            CMCSIQAC.OUT_INF.BAS_INF.BAS_PROD_CD = CMCSIQAC.OUT_INF.TD_INF.TD_MPROD_CD;
        } else {
        }
        CEP.TRC(SCCGWA, CMCSIQAC.I_FUNC);
        CEP.TRC(SCCGWA, CMCSIQAC.I_CUS_AC);
        CEP.TRC(SCCGWA, CMCSIQAC.I_AC_SEQ);
        CEP.TRC(SCCGWA, CMCSIQAC.I_CCY);
        CEP.TRC(SCCGWA, CMCSIQAC.I_CCY_TYP);
        CEP.TRC(SCCGWA, CMCSIQAC.I_BV_NO);
        CEP.TRC(SCCGWA, CMCSIQAC.I_PSW);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_AC);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_CI_NO);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_CI_TYP);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_CI_NM);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_CI_ID_TYP);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_CI_ID_NO);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_CI_STSW);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_TEL_NO);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_CI_OPE_BR);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_ACR_STSW);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_CPN_NM);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_FRM_APP);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_AC_TYP);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_STS);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_STSW);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_OPE_BR);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_CUS_OWN_BR);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_BV_TYP);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_BV_CODE);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_BV_NO);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_LOST_FLG);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_DRW_TYP);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_AC_SEQ);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_CCY);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_CCY_TYP);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_ACO_NO);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_ACO_STS);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_ACO_STSW);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_ACO_OPE_BR);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_ACO_OWN_BR);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_LAST_BAL);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_AVA_BAL);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_CUR_BAL);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_ENTY_TYP);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_ADD_INF.BAS_AC_KND);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_ADD_INF.BAS_OPEN_CHNL);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DC_INF.DC_CARD_NO);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DC_INF.DC_CD_MEDI);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DC_INF.DC_CD_STS);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DC_INF.DC_CD_STSW);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DC_INF.DC_PROD_CD);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DC_INF.DC_OPE_BR);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DC_INF.DC_CLT_BR);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DC_INF.DC_BV_CODE);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DC_INF.DC_BV_NO);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DC_INF.DC_LNK_TYP);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DC_INF.DC_OPE_DT);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DC_INF.DC_ACO_NO);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DC_INF.DC_AC_SEQ);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DC_INF.DC_CCY);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DC_INF.DC_CCY_TYP);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DC_INF.DC_ACO_STS);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DC_INF.DC_ACO_STSW);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DC_INF.DC_ACO_OPE_BR);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DC_INF.DC_ACO_OWN_BR);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DC_INF.DC_LAST_BAL);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DC_INF.DC_AVA_BAL);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DC_INF.DC_CUR_BAL);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_ADD_INF.BAS_AC_KND);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.BAS_INF.BAS_ADD_INF.BAS_OPEN_CHNL);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DD_INF.DD_CUS_AC);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DD_INF.DD_CUS_AC_TYP);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DD_INF.DD_CUS_STS);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DD_INF.DD_CUS_STSW);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DD_INF.DD_CUS_OPE_BR);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DD_INF.DD_CUS_OWN_BR);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DD_INF.DD_BV_TYP);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DD_INF.DD_BV_CODE);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DD_INF.DD_BV_NO);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DD_INF.DD_DRW_TYP);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DD_INF.DD_CR_FLG);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DD_INF.DD_UEW_FLG);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DD_INF.DD_CASH_FLG);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DD_INF.DD_ACO_NO);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DD_INF.DD_AC_SEQ);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DD_INF.DD_CCY);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DD_INF.DD_CCY_TYP);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DD_INF.DD_ACO_STS);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DD_INF.DD_ACO_STSW);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DD_INF.DD_ACO_OPE_BR);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DD_INF.DD_ACO_OWN_BR);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DD_INF.DD_LAST_BAL);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DD_INF.DD_AVA_BAL);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DD_INF.DD_CUR_BAL);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DD_INF.DD_FRG_CODE);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.DD_INF.DD_YW_TYP);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_CUS_AC);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_CUS_AC_TYP);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_CUS_STS);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_CUS_STSW);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_CUS_OPE_BR);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_CUS_OWN_BR);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_CR_FLG);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_UEW_FLG);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_DRW_TYP);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_MPROD_CD);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_ACO_NO);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_AC_SEQ);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_CCY);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_CCY_TYP);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_ACO_STS);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_ACO_STSW);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_ACO_OPE_BR);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_ACO_OWN_BR);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_TDAC_TYP);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_DRW_FLG);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_LAST_BAL);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_AVA_BAL);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_CUR_BAL);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_BV_TYP);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_BV_CODE);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_BV_NO);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_INT_RAT);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_SDT);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_EDT);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_TERM_CD);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_FC_CD);
        CEP.TRC(SCCGWA, CMCSIQAC.OUT_INF.TD_INF.TD_YW_TYP);
    }
    public void S000_CALL_CIZQACRI() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "CI-INQ-ACR-INF", CICQACRI);
        CEP.TRC(SCCGWA, CICQACRI.RC.RC_CODE);
        if (CICQACRI.RC.RC_CODE != 0) {
            CEP.ERR(SCCGWA, CICQACRI.RC);
        }
    }
    public void S000_CALL_CIZCUST() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "CI-CIZCUST", CICCUST);
        CEP.TRC(SCCGWA, CICCUST.RC.RC_CODE);
        if (CICCUST.RC.RC_CODE != 0) {
            CEP.ERR(SCCGWA, CICCUST.RC);
        }
    }
    public void S000_CALL_CIZQACAC() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "CI-INQ-ACAC", CICQACAC, true);
        CEP.TRC(SCCGWA, CICQACAC.RC.RC_CODE);
        if (CICQACAC.RC.RC_CODE != 0) {
            CEP.ERR(SCCGWA, CICQACAC.RC);
        }
    }
    public void S000_CALL_DCZUCINF() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "DC-U-CARD-INF ", DCCUCINF, true);
        CEP.TRC(SCCGWA, DCCUCINF.RC.RC_CODE);
        if (DCCUCINF.RC.RC_CODE != 0) {
            CEP.ERR(SCCGWA, DCCUCINF.RC);
        }
    }
    public void S000_CALL_CIZQACRL() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "CI-INQ-ACRL ", CICQACRL, true);
        CEP.TRC(SCCGWA, CICQACRL.RC.RC_CODE);
        if (CICQACRL.RC.RC_CODE != 0) {
            CEP.ERR(SCCGWA, CICQACRL.RC);
        }
    }
    public void S000_CALL_DDZIQBAL() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "DD-I-INQ-CCY-BAL", DDCIQBAL, true);
        CEP.TRC(SCCGWA, DDCIQBAL.RC.RC_CODE);
        if (DDCIQBAL.RC.RC_CODE != 0) {
            CEP.ERR(SCCGWA, DDCIQBAL.RC);
        }
    }
    public void S000_CALL_DDZIMMST() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "DD-I-NFIN-M-MST ", DDCIMMST, true);
        CEP.TRC(SCCGWA, DDCIMMST.RC.RC_CODE);
        if (DDCIMMST.RC.RC_CODE != 0 
            && DDCIMMST.RC.RC_CODE != 1401) {
            CEP.ERR(SCCGWA, DDCIMMST.RC);
        }
    }
    public void S000_CALL_TDZACE() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "TD-AC-ENQ", TDCACE, true);
    }
    public void S000_CALL_IBZQINF() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "IB-IBZQINF", IBCQINF, true);
        CEP.TRC(SCCGWA, IBCQINF.RC.RC_CODE);
        if (IBCQINF.RC.RC_CODE != 0) {
            CEP.ERR(SCCGWA, IBCQINF.RC);
        }
    }
    public void S000_CALL_IBZQINFT() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "IB-IBZQINFT", IBCQINFT, true);
        CEP.TRC(SCCGWA, IBCQINFT.RC.RC_CODE);
        if (IBCQINFT.RC.RC_CODE != 0) {
            CEP.ERR(SCCGWA, IBCQINFT.RC);
        }
    }
    public void S000_CALL_LNZRCONT() throws IOException,SQLException,Exception {
        LNCRCONT.REC_PTR = LNRCONT;
        LNCRCONT.REC_LEN = 416;
        IBS.CALLCPN(SCCGWA, "LN-RSC-LNTCONT", LNCRCONT);
        CEP.TRC(SCCGWA, LNCRCONT.RC);
        if (LNCRCONT.RETURN_INFO != 'F') {
            CEP.ERR(SCCGWA, LNCRCONT.RC);
        }
    }
    public void S000_CALL_CISOCUST() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "CI-CISOCUST", CICCUST, true);
        CEP.TRC(SCCGWA, CICCUST.RC.RC_CODE);
        if (CICCUST.RC.RC_CODE != 0) {
            CEP.ERR(SCCGWA, CICCUST.RC);
        }
    }
    public void S000_CALL_DCZPCDCK() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "DC-P-CARD-TRKDAT-CHK", DCCPCDCK, true);
    }
    public void S000_CALL_DDZUINVS() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "DD-I-VS-INFO", DDCUINVS, true);
    }
    public void S000_CALL_DDZIMPAY() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "DD-I-MPAY-PROC", DDCIMPAY, true);
    }
    public void S000_CALL_TDZACM() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "TD-AC-PSW-CHECK", TDCACM, true);
    }
    public void S000_CALL_DDZUVCH() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "DD-AC-PSBK-INQ", DDCUVCH, true);
    }
    public void S000_CALL_AIZPQMIB() throws IOException,SQLException,Exception {
        IBS.CALLCPN(SCCGWA, "AI-P-INQ-MIB", AICPQMIB, true);
        CEP.TRC(SCCGWA, AICPQMIB.RC.RC_CODE);
        if (AICPQMIB.RC.RC_CODE != 0) {
            CEP.ERR(SCCGWA, AICPQMIB.RC);
        }
    }
    public void Z_RET() throws IOException,SQLException,Exception {
        return;
    }
    public void B_DB_EXCP() throws IOException,SQLException,Exception {
        throw new SQLException(SCCGWA.e);
    }
}
