package com.hisun.CM;

import java.io.IOException;
import java.sql.SQLException;

import com.hisun.AI.AICUUPIA;
import com.hisun.BP.BPCFFCON;
import com.hisun.BP.BPCFFTXI;
import com.hisun.BP.BPCMSG_ERROR_MSG;
import com.hisun.BP.BPCRTLVB;
import com.hisun.BP.BPCSPLIF;
import com.hisun.BP.BPCTLVBF;
import com.hisun.BP.BPCUABOX;
import com.hisun.BP.BPCUSBOX;
import com.hisun.BP.BPRTLVB;
import com.hisun.CI.CICCUST;
import com.hisun.CI.CICQACRI;
import com.hisun.DC.DCCUCINF;
import com.hisun.DC.DCCURHLD;
import com.hisun.DD.DDCMSG_ERROR_MSG;
import com.hisun.DD.DDCUCRAC;
import com.hisun.DD.DDCUDRAC;
import com.hisun.IB.IBCPOSTA;
import com.hisun.SC.SCCCALL;
import com.hisun.SC.SCCEXCP;
import com.hisun.SC.SCCFMT;
import com.hisun.SC.SCCMSG;
import com.hisun.TD.TDCACDRU;

public class CMZS1600 {
    boolean pgmRtn = false;
    String K_CNY = "156";
    String K_OUTPUT_FMT = "CM160";
    String WK_PGM_CIZQACRI = "CI-INQ-ACR-INF      ";
    String WK_PGM_CIZCUST = "CI-INQ-CUST";
    String WK_PGM_DCZUCINF = "DC-U-CARD-INF       ";
    String WK_PGM_DCZURHLD = "DC-UNIT-RHLD        ";
    String WK_PGM_BPZUSBOX = "BP-U-SUB-CBOX       ";
    String WK_PGM_BPZTLVBF = "BP-R-ADW-TLVB       ";
    String WK_PGM_BPZSPLIF = "BP-S-ALC-PVAL-MAINT ";
    String WK_PGM_DDZUDRAC = "DD-UNIT-DRAW-PROC   ";
    String WK_PGM_IBZDRAC = "IB-IBZDRAC          ";
    String WK_PGM_BPZUABOX = "BP-U-ADD-CBOX       ";
    String WK_PGM_DDZUCRAC = "DD-UNIT-DEP-PROC    ";
    String WK_PGM_IBZCRAC = "IB-IBZCRAC          ";
    String WK_PGM_DCZUHLD = "DC-UNIT-HLD";
    String WK_PGM_AIZUUPIA = "AI-U-UPDATE-IA      ";
    String WK_PGM_BPZFFCON = "BP-F-F-CON-CHG-INFO ";
    String WK_PGM_BPZFFTXI = "BP-F-F-TX-INFO      ";
    String WK_PGM_TDZACDRU = "TD-ACDR-UNT";
    CMZS1600_WS_TEMP_VARIABLE WS_TEMP_VARIABLE = new CMZS1600_WS_TEMP_VARIABLE();
    CMZS1600_WS_CUS_INF[] WS_CUS_INF = new CMZS1600_WS_CUS_INF[6];
    CMZS1600_WS_FEE_INF[] WS_FEE_INF = new CMZS1600_WS_FEE_INF[5];
    CMZS1600_WS_HLD_INF WS_HLD_INF = new CMZS1600_WS_HLD_INF();
    CMZS1600_WS_CASH_INF WS_CASH_INF = new CMZS1600_WS_CASH_INF();
    CMZS1600_WS_TD_INF[] WS_TD_INF = new CMZS1600_WS_TD_INF[2];
    CMZS1600_WS_INR_AC_INF[] WS_INR_AC_INF = new CMZS1600_WS_INR_AC_INF[10];
    char WS_FEE_CUS_AC_MATCH_FLG = ' ';
    char WS_DEAL_FLG = ' ';
    CMCMSG_ERROR_MSG CMCMSG_ERROR_MSG = new CMCMSG_ERROR_MSG();
    BPCMSG_ERROR_MSG BPCMSG_ERROR_MSG = new BPCMSG_ERROR_MSG();
    DDCMSG_ERROR_MSG DDCMSG_ERROR_MSG = new DDCMSG_ERROR_MSG();
    SCCEXCP SCCEXCP = new SCCEXCP();
    SCCFMT SCCFMT = new SCCFMT();
    SCCCALL SCCCALL = new SCCCALL();
    SCCMSG SCCMSG = new SCCMSG();
    CICQACRI CICQACRI = new CICQACRI();
    IBCPOSTA IBCPOSTA = new IBCPOSTA();
    DCCUCINF DCCUCINF = new DCCUCINF();
    AICUUPIA AICUUPIA = new AICUUPIA();
    DDCUCRAC DDCUCRAC = new DDCUCRAC();
    DDCUDRAC DDCUDRAC = new DDCUDRAC();
    BPCUSBOX BPCUSBOX = new BPCUSBOX();
    BPCUABOX BPCUABOX = new BPCUABOX();
    BPCFFTXI BPCFFTXI = new BPCFFTXI();
    BPCFFCON BPCFFCON = new BPCFFCON();
    DCCUHLD DCCUHLD = new DCCUHLD();
    DCCURHLD DCCURHLD = new DCCURHLD();
    BPRTLVB BPRTLVB = new BPRTLVB();
    BPCTLVBF BPCTLVBF = new BPCTLVBF();
    BPCSPLIF BPCSPLIF = new BPCSPLIF();
    CICCUST CICCUST = new CICCUST();
    BPCRTLVB BPCRTLVB = new BPCRTLVB();
    TDCACDRU TDCACDRU = new TDCACDRU();
