package com.hisun.GL;

public class GLCDEF02_VARIABLES {
    public String ERR_MSG = " ";
    public char JRN_IN_USE = ' ';
    public GLCDEF02_GL_INF[] GL_INF = new GLCDEF02_GL_INF[10];
    public String SUS_ITM_MD = " ";
    public int SUS_SEQ_MD = 0;
    public String SUS_ITM_MC = " ";
    public int SUS_SEQ_MC = 0;
    public String SUS_ITM_RD = " ";
    public int SUS_SEQ_RD = 0;
    public String SUS_ITM_RC = " ";
    public int SUS_SEQ_RC = 0;
    public String SUS_RSN = " ";
    public short SUS_BOOK = 0;
    public int ITM_SEQ = 0;
    public String STR = " ";
    public String MOD_NO = " ";
    public int VCNT = 0;
    public int BCNT = 0;
    public int CCNT = 0;
    public int ICNT = 0;
    public int ECNT = 0;
    public int ACNT = 0;
    public int SCNT = 0;
    public int MCNT = 0;
    public int COMMIT_CNT = 0;
    public int CUR_BCNT = 0;
    public int I = 0;
    public int B = 0;
    public int J = 0;
    public int CNT = 0;
    public int CNT1 = 0;
    public int PRDM_CNT = 0;
    public int CNGL_CNT = 0;
    public int GLM_CNT = 0;
    public int EVENT_CNT = 0;
    public int ITM_CNT = 0;
    public short CUR_EVENT_CNT = 0;
    public int READ_BPQOVET_CNT = 0;
    public int VCH_LENGTH = 0;
    public int LST_MST1 = 0;
    public int LST_MST2 = 0;
    public String LAST_SET_NO = " ";
    public char LAST_EC_IND = ' ';
    public char INNER_PRDT_IND = ' ';
    public int GL_MST_NO = 0;
    public GLCDEF02_BOOK_PARM[] BOOK_PARM = new GLCDEF02_BOOK_PARM[10];
    public GLCDEF02_CUR_BOOK CUR_BOOK = new GLCDEF02_CUR_BOOK();
    public GLCDEF02_CUR_GLMST CUR_GLMST = new GLCDEF02_CUR_GLMST();
    public GLCDEF02_GLMST_DETAIL[] GLMST_DETAIL = new GLCDEF02_GLMST_DETAIL[1000];
    public GLCDEF02_CUR_EVN_VCH CUR_EVN_VCH = new GLCDEF02_CUR_EVN_VCH();
    public GLCDEF02_EVENT_VCH_GROUP[] EVENT_VCH_GROUP = new GLCDEF02_EVENT_VCH_GROUP[1000];
    public GLCDEF02_EVENT_VCH_TEMP EVENT_VCH_TEMP = new GLCDEF02_EVENT_VCH_TEMP();
    public GLCDEF02_CUR_EVN_AMT_DETAIL[] CUR_EVN_AMT_DETAIL = new GLCDEF02_CUR_EVN_AMT_DETAIL[76];
    public GLCDEF02_INTER_AC INTER_AC = new GLCDEF02_INTER_AC();
    public char VCH_AC_FLG = ' ';
    public GLCDEF02_SUM_VCHT[] SUM_VCHT = new GLCDEF02_SUM_VCHT[400];
    public GLCDEF02_VCH VCH = new GLCDEF02_VCH();
    public GLCDEF02_SVCH SVCH = new GLCDEF02_SVCH();
    public GLCDEF02_EVCH EVCH = new GLCDEF02_EVCH();
    public GLCDEF02_DATE_COMPUTE DATE_COMPUTE = new GLCDEF02_DATE_COMPUTE();
    public GLCDEF02_CLS_INFO[] CLS_INFO = new GLCDEF02_CLS_INFO[400];
    public GLCDEF02_BAL_INFO[] BAL_INFO = new GLCDEF02_BAL_INFO[400];
    public GLCDEF02_PARM_PRDM[] PARM_PRDM = new GLCDEF02_PARM_PRDM[200];
    public GLCDEF02_PARM_CNGL[] PARM_CNGL = new GLCDEF02_PARM_CNGL[2000];
    public GLCDEF02_PARM_ITM[] PARM_ITM = new GLCDEF02_PARM_ITM[5000];
    public char[] N_FLG = new char[100];
    public char EWAB_FLG = ' ';
    public char GUP_FLG = ' ';
    public char BOOK_FLAG = ' ';
    public char FST_FLG = ' ';
    public char N_PNT_FLG = ' ';
    public char FND_ORG_FLG = ' ';
    public char FND_AUTH_FLG = ' ';
    public char AUTH_RECOND_FLG = ' ';
    public char DB2_REC_STATUS = ' ';
    public char ITM_BAL_SN_FLG = ' ';
    public char ITM_FND_FLG = ' ';
    public char ITM_LVL_FLG = ' ';
    public char MEMO_ITM_FLG = ' ';
    public char CLS_KEY_FLG = ' ';
    public char BKPM_FLG = ' ';
    public char SUS_FLG = ' ';
    public char CL_SUS_FLG = ' ';
    public char WL_SUS_FLG = ' ';
    public char CL_SPEC_SEQ_FLG = ' ';
    public char LNP_SUS_FLG = ' ';
    public char LNC_SUS_FLG = ' ';
    public char BAL_KEY_FLG = ' ';
    public char CHANGE_FLG = ' ';
    public char OVET_FLG = ' ';
    public char ERR_FLG = ' ';
    public char PRDM_FLG = ' ';
    public char PARM_EOF_FLG = ' ';
    public char CNGL_FOUND_FLG = ' ';
    public char GLM_FOUND_FLG = ' ';
    public char EVET_FOUND_FLG = ' ';
    public char ITM_FOUND_FLG = ' ';
    public GLCDEF02_VARIABLES() {
        for (int i=0;i<10;i++) GL_INF[i] = new GLCDEF02_GL_INF();
        for (int i=0;i<10;i++) BOOK_PARM[i] = new GLCDEF02_BOOK_PARM();
        for (int i=0;i<1000;i++) GLMST_DETAIL[i] = new GLCDEF02_GLMST_DETAIL();
        for (int i=0;i<1000;i++) EVENT_VCH_GROUP[i] = new GLCDEF02_EVENT_VCH_GROUP();
        for (int i=0;i<76;i++) CUR_EVN_AMT_DETAIL[i] = new GLCDEF02_CUR_EVN_AMT_DETAIL();
        for (int i=0;i<400;i++) SUM_VCHT[i] = new GLCDEF02_SUM_VCHT();
        for (int i=0;i<400;i++) CLS_INFO[i] = new GLCDEF02_CLS_INFO();
        for (int i=0;i<400;i++) BAL_INFO[i] = new GLCDEF02_BAL_INFO();
        for (int i=0;i<200;i++) PARM_PRDM[i] = new GLCDEF02_PARM_PRDM();
        for (int i=0;i<2000;i++) PARM_CNGL[i] = new GLCDEF02_PARM_CNGL();
        for (int i=0;i<5000;i++) PARM_ITM[i] = new GLCDEF02_PARM_ITM();
    }
}
