package com.hisun.GL;

public class GLCDEF03_GLMST_ITM {
    public GLCDEF03_GLMST1_INFO GLMST1_INFO = new GLCDEF03_GLMST1_INFO();
    public GLCDEF03_GLMST2_INFO GLMST2_INFO = new GLCDEF03_GLMST2_INFO();
}
