package com.hisun.GL;

public class GLCDEF04_CURR_GLMST1_INFO {
    public GLCDEF04_CURR_MST1_BASIC CURR_MST1_BASIC = new GLCDEF04_CURR_MST1_BASIC();
    public GLCDEF04_CURR_MST1_REL_ITMS[] CURR_MST1_REL_ITMS = new GLCDEF04_CURR_MST1_REL_ITMS[60];
    public GLCDEF04_CURR_GLMST1_INFO() {
        for (int i=0;i<60;i++) CURR_MST1_REL_ITMS[i] = new GLCDEF04_CURR_MST1_REL_ITMS();
    }
}
