package com.hisun.GL;

public class GLCDEF01_VARIABLES {
    public String ERR_MSG = " ";
    public char JRN_IN_USE = ' ';
    public GLCDEF01_GL_INF[] GL_INF = new GLCDEF01_GL_INF[10];
    public String SUS_ITM_MD = " ";
    public int SUS_SEQ_MD = 0;
    public String SUS_ITM_MC = " ";
    public int SUS_SEQ_MC = 0;
    public String SUS_ITM_RD = " ";
    public int SUS_SEQ_RD = 0;
    public String SUS_ITM_RC = " ";
    public int SUS_SEQ_RC = 0;
    public String SUS_RSN = " ";
    public short SUS_BOOK = 0;
    public int ITM_SEQ = 0;
    public String STR = " ";
    public String MOD_NO = " ";
    public int VCNT = 0;
    public int BCNT = 0;
    public int CCNT = 0;
    public int ICNT = 0;
    public int ECNT = 0;
    public int ACNT = 0;
    public int SCNT = 0;
    public int MCNT = 0;
    public int CUR_BCNT = 0;
    public int I = 0;
    public int B = 0;
    public int J = 0;
    public int I1 = 0;
    public int I2 = 0;
    public int I3 = 0;
    public int I4 = 0;
    public int CNT = 0;
    public int VCH_LENGTH = 0;
    public int LST_MST1 = 0;
    public int LST_MST2 = 0;
    public GLCDEF01_BOOK_PARM[] BOOK_PARM = new GLCDEF01_BOOK_PARM[10];
    public GLCDEF01_CUR_BOOK CUR_BOOK = new GLCDEF01_CUR_BOOK();
    public GLCDEF01_CUR_GLMST CUR_GLMST = new GLCDEF01_CUR_GLMST();
    public GLCDEF01_GLMST_DETAIL[] GLMST_DETAIL = new GLCDEF01_GLMST_DETAIL[10];
    public GLCDEF01_EVENT_VCH EVENT_VCH = new GLCDEF01_EVENT_VCH();
    public GLCDEF01_CUR_EVN_VCH CUR_EVN_VCH = new GLCDEF01_CUR_EVN_VCH();
    public GLCDEF01_CUR_EVN_AMT_DETAIL[] CUR_EVN_AMT_DETAIL = new GLCDEF01_CUR_EVN_AMT_DETAIL[76];
    public GLCDEF01_INTER_AC INTER_AC = new GLCDEF01_INTER_AC();
    public char VCH_AC_FLG = ' ';
    public GLCDEF01_SUM_VCHT[] SUM_VCHT = new GLCDEF01_SUM_VCHT[400];
    public GLCDEF01_VCH VCH = new GLCDEF01_VCH();
    public GLCDEF01_SVCH SVCH = new GLCDEF01_SVCH();
    public GLCDEF01_EVCH EVCH = new GLCDEF01_EVCH();
    public GLCDEF01_DATE_COMPUTE DATE_COMPUTE = new GLCDEF01_DATE_COMPUTE();
    public GLCDEF01_CLS_INFO[] CLS_INFO = new GLCDEF01_CLS_INFO[400];
    public GLCDEF01_BAL_INFO[] BAL_INFO = new GLCDEF01_BAL_INFO[400];
    public GLCDEF01_COMPA_KEY COMPA_KEY = new GLCDEF01_COMPA_KEY();
    public GLCDEF01_COMPB_KEY COMPB_KEY = new GLCDEF01_COMPB_KEY();
    public char[] N_FLG = new char[100];
    public char EWAB_FLG = ' ';
    public char GUP_FLG = ' ';
    public char BOOK_FLAG = ' ';
    public char FST_FLG = ' ';
    public char N_PNT_FLG = ' ';
    public char FND_ORG_FLG = ' ';
    public char FND_AUTH_FLG = ' ';
    public char AUTH_RECOND_FLG = ' ';
    public char DB2_REC_STATUS = ' ';
    public char ITM_BAL_SN_FLG = ' ';
    public char ITM_FND_FLG = ' ';
    public char ITM_LVL_FLG = ' ';
    public char MEMO_ITM_FLG = ' ';
    public char CLS_KEY_FLG = ' ';
    public char BKPM_FLG = ' ';
    public char SUS_FLG = ' ';
    public char CL_SUS_FLG = ' ';
    public char WL_SUS_FLG = ' ';
    public char LNP_SUS_FLG = ' ';
    public char LNC_SUS_FLG = ' ';
    public char BAL_KEY_FLG = ' ';
    public char CHANGE_FLG = ' ';
    public GLCDEF01_VARIABLES() {
        for (int i=0;i<10;i++) GL_INF[i] = new GLCDEF01_GL_INF();
        for (int i=0;i<10;i++) BOOK_PARM[i] = new GLCDEF01_BOOK_PARM();
        for (int i=0;i<10;i++) GLMST_DETAIL[i] = new GLCDEF01_GLMST_DETAIL();
        for (int i=0;i<76;i++) CUR_EVN_AMT_DETAIL[i] = new GLCDEF01_CUR_EVN_AMT_DETAIL();
        for (int i=0;i<400;i++) SUM_VCHT[i] = new GLCDEF01_SUM_VCHT();
        for (int i=0;i<400;i++) CLS_INFO[i] = new GLCDEF01_CLS_INFO();
        for (int i=0;i<400;i++) BAL_INFO[i] = new GLCDEF01_BAL_INFO();
    }
}
